### ISSUE TITLE
US Cookie Unlock Fails 50% of the Time

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#1]
When i press on use US Cookie it sometimes just doesnt work, its like a 50/50 chance and its fkn annoying.

**Comment by hama3254** [comment]
i know  the issue but unfortunately i have no idea why crunchyroll sometimes don't accept the cookie and othertime it does. 
the Firefox addon still works fine with the same api to get the cookie and it set the same cookie as the GeckoFX engine in the downloader.
i look into it again (it has been a while since the last time) maybe i find something

**Comment by KoroFX** [comment]
Thank you, let me know if you find the error.
-
Im currently downloading like 60 animes

**Comment by hama3254** [comment]
i looked into it and even with no really change to the code  it seems to work. 
My tests: https://www.youtube.com/watch?v=k-A5McYj6f0 
changes: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/commit/916124751b54dc9f829523e0f1d901bc47f26dcc

**Comment by KoroFX** [comment]
How to update the Downloader ?

**Comment by KoroFX** [comment]
Erklärs mir auf deutsch ich kenn mich nicht aus mit github.
Du scheinst ja deutsch zu sein.

**Comment by hama3254** [comment]
ich hab die neue version komplett hochgeladen.
einfach unten bei "Dev-build-51-19-Crunchyroll-Downloader-v3.x.zip    51.3 MB" klicken 
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/3.x

**Comment by KoroFX** [comment]
Also die die Dev version laden und nicht die base version ?

**Comment by KoroFX** [comment]
Gut, ich guck nächstes jahr oder so nochmal nach ob du noch ein update gemacht hast oder falls ich nen Fehler finde.

**Comment by KoroFX** [comment]
Was anderes was ich mich Frage ist kannst du es nicht so machen das man ne einstellung hat um den cookie automatisch beim start einzubinden ?

**Comment by hama3254** [comment]
> Wie update ich den Downloader ? Einfach nochmal die Base version (3.0.1) laden oder die dev version (Dev-build-51-19)

Ich habe keine update Funktion im downloader drinnen, also muss man immer den zip ordner komplett neu runterladen, die einstellungen sind jedoch in der windows registry gespeichert
