### ISSUE TITLE
Version mit der Searchbar Crasht, manchmal.

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#10]
Ich gehe auf Queue -> Anime-> Anime Name -> Ganzes Program Crasht mit ner 50% chance.
Die Url leiste dauert auch so ne sekunde bis die den neuen link anzeigt nachn laden.

Die Url Leiste verursacht glaube ich diesen bug, vielleicht guckst du nochmal rein oder entfernst die bar und machst n knopf hin um die derzeitige url zu kopieren.

**Comment by KoroFX** [comment]
Ups wollte es nicht schließen.

**Comment by KoroFX** [comment]
Kann ich dir irgendwo ne Donation geben für dein Programm und weil du meine Features einbaust und die Fehler so schnell behebst ?

**Comment by hama3254** [comment]
> Ich gehe auf Queue -> Anime-> Anime Name -> Ganzes Program Crasht mit ner 50% chance.

jetzt nochmal bitte in verständlich was du machst, wenn du eine übersicht hinzufügst kannst du danach keinen Namen mehr eingeben und davor solltest du das auch nicht machen funktioniert nämlich nicht (hab das jetzt abgeschaltet)

> Die Url leiste dauert auch so ne sekunde bis die den neuen link anzeigt nachn laden.

ist logisch hab das selbe event verwendet wie für den rest und zwar "WebBrowser1.DocumentCompleted" 

> Die Url Leiste verursacht glaube ich diesen bug, vielleicht guckst du nochmal rein oder entfernst die bar und machst n knopf hin um die derzeitige url zu kopieren.

das ist sehr unwahrscheinlich, den button hab ich vergessen überhaupt ne Funktion zu geben 🤫
und dem browser ist egal was man dem eingibt der versucht eh aus allem eine .com adresse zu machen

**Comment by KoroFX** [comment]
> jetzt nochmal bitte in verständlich was du machst, wenn du eine übersicht hinzufügst kannst du danach keinen Namen mehr eingeben und davor solltest du das auch nicht machen funktioniert nämlich nicht (hab das jetzt abgeschaltet)

Ich gehe in crunchyroll auf queue und dann auf den anime den ich runterladen will und dann crasht das Programm, ich komme nichtmal dazu die URL zu kopieren.

> das ist sehr unwahrscheinlich, den button hab ich vergessen überhaupt ne Funktion zu geben 🤫
> und dem browser ist egal was man dem eingibt der versucht eh aus allem eine .com adresse zu machen

Das ist seid die URL Leiste da ist. Und der Knopf in der Leiste heißt Ente, du könntest auch einfach nur den Knopf die Funktion zum Kopieren geben und die URL Leiste an sich wegmachen.

**Comment by KoroFX** [comment]
Aber ich mache dir gleich mal ne Aufnahme was ich mache und erkläre dir was ich meine.

**Comment by KoroFX** [comment]
https://www.youtube.com/watch?v=GcluS9hoZ6U

**Comment by hama3254** [comment]
Der browser ist eigentlich nur gedacht um die cloudflare ddos protection zu umgehen und nicht als vollwertiger browser ersatz.
Die übersicht aus dem normalen Desktop browser zu kopieren würde reichen.
nichts desto trotz sollte er nicht crashen, ist dir vlt. ein Anime aufgefallen der nicht geht oder das komplett zufälllig?
ich denke nicht das der fehler was mit der URL leiste zu tun hat, das auslesen er url ist immerhin schon die ganze zeit drinnen (zumindest beim download) nur eben nicht sichtbar bzw. wurde keiner textbox der wert zugewiesen

**Comment by KoroFX** [comment]
1. Jo aber der Browser ist halt ganz Praktisch vorallen mit den US Cookie brauche ich keinen VPN mehr um US eingeloggt zu sein.
2. Das ist komplett Random wann der crasht, aber meistens wenn ich dann auf der eigentlichen seite vom Anime bin.
3. Hau die Leiste am besten raus und lass nur den Button da um den Link der derzeitigen website zu kopieren.
3.1 Nenn den Knopf dann irgendwie Copy URL oder sowas.

**Comment by KoroFX** [comment]
und bau son button ein um zu donaten xD

**Comment by KoroFX** [comment]
Das meine ich mit eigentliche seite vom Anime:
![image](https://user-images.githubusercontent.com/46395233/71768131-c4bfa700-2f13-11ea-9bbe-f3c3a7f23515.png)
Wie gesagt der Button mit den Namen Copy Url (anstatt Enter) würde reichen ohne die Leiste nur um dann die URL zu kopieren.
![image](https://user-images.githubusercontent.com/46395233/71768136-cc7f4b80-2f13-11ea-8c6b-c4823a99d5ba.png)

**Comment by hama3254** [comment]
> 1. Jo aber der Browser ist halt ganz Praktisch vorallen mit den US Cookie brauche ich keinen VPN mehr um US eingeloggt zu sein.

Das geht auch im Firefox
https://addons.mozilla.org/de/firefox/addon/crunchy-unblocker/

**Comment by KoroFX** [comment]
> > 1. Jo aber der Browser ist halt ganz Praktisch vorallen mit den US Cookie brauche ich keinen VPN mehr um US eingeloggt zu sein.
> 
> Das geht auch im Firefox
> https://addons.mozilla.org/de/firefox/addon/crunchy-unblocker/

Ich benutze aber chrome und der eingebaute funktioniert ja ausreichend nur halt die Searchbar kann weg und der knopf soll die derzeitige url einfach kopieren.

> 3. Hau die Leiste am besten raus und lass nur den Button da um den Link der derzeitigen website zu kopieren.
>    ![image](https://user-images.githubusercontent.com/46395233/71768136-cc7f4b80-2f13-11ea-8c6b-c4823a99d5ba.png)
>    3.1 Nenn den Knopf dann irgendwie Copy URL oder sowas.

**Comment by KoroFX** [comment]
Hab ne Version für Chrome gefunden, aber das gleich in deiner anwendung zu machen ist besser.
Währe auch cool das du den eingebauten Browser fixt das es nicht crasht. 
(halt die URL Leiste weg machen und ggf nur der Knopf zum Kopieren der URL noch da ist. (Nenn den Knopf dann auch Cpy URL))

**Comment by KoroFX** [comment]
Achso und den Knopf dann auch Copy Url und nicht enter nennen xd

**Comment by hama3254** [comment]
> Ich gehe auf Queue -> Anime-> Anime Name -> Ganzes Program Crasht mit ner 50% chance.

nach unzähligen versuchen nicht nachvollziehbar -> vlt ein lokales problem? 

> Die Url leiste dauert auch so ne sekunde bis die den neuen link anzeigt nachn laden.

Fixed!

> 3. Hau die Leiste am besten raus und lass nur den Button da um den Link der derzeitigen website zu kopieren.
>    ![image](https://user-images.githubusercontent.com/46395233/71768136-cc7f4b80-2f13-11ea-8c6b-c4823a99d5ba.png)
>    3.1 Nenn den Knopf dann irgendwie Copy URL oder sowas.

"Enter" Button ersetzt mit "Copy URL" Button

**Comment by hama3254** [comment]
Release wurde upgedatet :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x
