### ISSUE TITLE
I get "No media found in:" error when downloading from Funimation

### ISSUE THREAD

**Issue by Priception** [hama3254/Crunchyroll-Downloader-v3.0#101]
I'm trying to download videos from Funimation but i keep getting this error. 
![image](https://user-images.githubusercontent.com/50168181/101336259-2b5eea80-3872-11eb-8e43-447b964d57a9.png)

I'm getting the videos through the use of the Firefox Extention.

**Comment by hama3254** [comment]
You need a premium account and you need to login at the browser of the downloader.
You can open the browser with the World icon on the main page of the downloader, it should load by default crunchyroll.com but you can change the URL and press the enter key to navigate to funimation.

**Comment by Priception** [comment]
Ok , thanks that fixed the issue.
