### ISSUE TITLE
I can't download any subtitles

### ISSUE THREAD

**Issue by ZioBomba-AW** [hama3254/Crunchyroll-Downloader-v3.0#105]
I'm trying since yesterday to download the subtitles from crunchyroll but it keeps telling me "Idle", and can't download anything, I'm logged in with my premium account and before yesterday I never had this problem, solutions?

Screen: https://prnt.sc/vztbxy
This also happens if I download a hardsub video by selecting the "Merge soft-subs with video file" checkbox.

**Comment by hama3254** [comment]
Fist of all the "Merge soft-subs with video file" option is no Hardsub, it just adds the subtitle files as text stream to the video 
![grafik](https://user-images.githubusercontent.com/52826614/101785528-2bbee600-3afd-11eb-85e3-31c72455bcd4.png)

This also means that the Hardsub language setting does not get applied to neither the merge option or the subtitle download. 

However it should tell you after you press "download" if no languages are selected or if the language can not be found and then return to idle.
