### ISSUE TITLE
Download Crashed & Folder Issue

### ISSUE THREAD

**Issue by Elwador** [hama3254/Crunchyroll-Downloader-v3.0#106]
I tried to download a few One Piece Episodes most of them work fine but some just don't work. For example in Season 1: 3 8 9 14 33 51 didn't work.

It always ends like this when it reaches 100%
![grafik](https://user-images.githubusercontent.com/75888166/101985052-c2b6aa00-3c85-11eb-8313-4f6f5f5073f2.png)

And also the Consol spams this:
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Crunchyroll_Downloader.Main.Timer3_Tick(Object sender, EventArgs e) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:Zeile 2710.

Also in the earlier Versions of your Downloader i got a Folder with subfolders for the Seasons of the Anime. But now i only get all the files in the directorie of the Downloader. With names like "One Piece - East Blue (1-61) Folge 52, Buggy's Revenge! the Man Who Smiles On the Execution Platform!,.mp4One Piece Staffel 1 Folge 52". 
I have set the Filename to: [episode number] & in the add video window to [automatic: Series/Season]

**Comment by hama3254** [comment]
> Also in the earlier Versions of your Downloader i got a Folder with subfolders for the Seasons of the Anime. But now i only get all the files in the directorie of the Downloader. With names like "One Piece - East Blue (1-61) Folge 52, Buggy's Revenge! the Man Who Smiles On the Execution Platform!,.mp4One Piece Staffel 1 Folge 52".
> I have set the Filename to: [episode number] & in the add video window to [automatic: Series/Season]

The old `[automatic: Series/Season]` should not be uses any more, you can now directly select in the drop down by instead of the extra setting.
![grafik](https://user-images.githubusercontent.com/52826614/101987863-d9b1c800-3c96-11eb-806a-f3e86af21334.png)

**Comment by hama3254** [comment]
> It always ends like this when it reaches 100%

if you have used the Hybrid Mode than the issue with the old subfolder setting could cause the download process to crash while the Hybrid Mode makes a temp folder which might work fine enough to not crash.

**Comment by hama3254** [comment]
> And also the Consol spams this:
> System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
> bei Crunchyroll_Downloader.Main.Timer3_Tick(Object sender, EventArgs e) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:Zeile 2710.

this can be ignored, it's just the display for the browser add-on's

**Comment by Elwador** [comment]
thanks the [automatic by Series and Season] fixed both issues 👍
