### ISSUE TITLE
what is hybrid mode?

### ISSUE THREAD

**Issue by thecarlosv** [hama3254/Crunchyroll-Downloader-v3.0#107]
i have been searching other realeases trying to explain what it does it do, but nothing. thanks in advance

**Comment by hama3254** [comment]
The stream is split in small files with just 2 to 10 seconds playtime.
The media library ffmpeg which I use to download the stream just does one at the time.
The hybride Mode download more of this fragments at the same time based on your computer hardware (half of the threads from your CPU) and saves them to be processed by ffmpeg later from your hard drive which makes it overall faster [as you see in the video.](https://www.youtube.com/watch?v=s_SY3RM1F3Y)

**Comment by thecarlosv** [comment]
thanks man!
