### ISSUE TITLE
Download crash/error

### ISSUE THREAD

**Issue by Hikami69** [hama3254/Crunchyroll-Downloader-v3.0#108]
![Cattura](https://user-images.githubusercontent.com/75862746/102007830-8be79f00-3d2c-11eb-809c-8c8616983770.PNG)
1. When I try to download [this](https://www.crunchyroll.com/it/kabaneri-of-the-iron-fortress/kabaneri-of-the-iron-fortress-compilation-movies-film-riassuntivo-prima-parte-luce-ritrovata-793437) episode the download process crash (I attach the log). In hybrid mode, instead, the program closes by itself without create any log file.
[Film riassuntivo Prima Parte Luce ritrovata.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5684377/Film.riassuntivo.Prima.Parte.Luce.ritrovata.log)
2. In the recent releases you've added the _"Error handling"_ option that I think is very useful. When enabled, does this option also report download errors you may have while using hybrid mode? Or by downloading in this way the episodes do not have errors or missing seconds in any case, in your experience?
3. Is it possible to add the icon to minimize the program in the taskbar?

Thanks in advance.

**Comment by hama3254** [comment]
> 1. When I try to download this episode the download process crash (I attach the log). 
>In hybrid mode, instead, the program closes by itself without create any log file.
> Film riassuntivo Prima Parte Luce ritrovata.log

The hybrid mode seems to have the same issue as the normal download ` HTTP error 502 Bad Gateway` .
I was able to fix the compleed crash in hybrid mode, [but 502 is a Server error i i can not do much about that](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_server_errors) 

![grafik](https://user-images.githubusercontent.com/52826614/102009858-93ae4000-3d3a-11eb-8049-4343cbc8babe.png)



>  In the recent releases you've added the _"Error handling"_ option that I think is very useful. When enabled, does this option also report download errors you may have while using hybrid mode? Or by downloading in this way the episodes do not have errors or missing seconds in any case, in your experience?

![grafik](https://user-images.githubusercontent.com/52826614/102009997-70d05b80-3d3b-11eb-8988-7577eddb820e.png)

the error handling just detects missing fragments during the ffmpeg processing so the hybrid mode would have downloaded all files before that even can detect something, however i already have added a second try for errors in the hybrid mode which i could expand to a proper error handling in the next version.  


>     3. Is it possible to add the icon to minimize the program in the taskbar?

That should be possible for the next version

**Comment by Hikami69** [comment]
All right, thanks a lot!
