### ISSUE TITLE
Resolution set on Auto and Downloader crashes

### ISSUE THREAD

**Issue by quamt** [hama3254/Crunchyroll-Downloader-v3.0#109]
Hello,

I found that when the Downloader is set to Auto and the resolution is for example 1920x1072, the program crashes.

Setting manual to 1080 and it works but will prompt for every episode to select resolution wanted. 

Is it possible to make a option to remember the setting that has been selected?

Example:
`www.crunchyroll.com/fairytail`

**Comment by hama3254** [comment]
i see, the issue is that [Auto] does not work with the hybrid mode so it uses 1080p as fallback if [Auto] and hybrid mode is selected. 
The issue is then i don't use the same checks like on the normal resolution filter.

I change it up so that it will ignore the [Auto] setting for the hybrid mode from the start since it can not work and add a save value for the selected resolution.

**Comment by hama3254** [comment]
this issue should be solved in v3.6.7, the hybrid mode does no longer work with [Auto] setting and if it is still enabled it should be changed otherwise the 'resolution not found' will appear.
The downloader now also saves the selected resolution from the 'resolution not found' until it get closed.

**Comment by quamt** [comment]
Thank you for the implementation.

I noticed some strange behaviour. 

1. Selected is 1072p
The first episode downloads OK. 
The second episode however is a lot smaller. 

2. The Downloader freezes after a few downloads. 

I am still checking as where to what is causing this. Testing 1080p to compare.

**Comment by hama3254** [comment]
I tested a view episodes myself and could not found the issue you are describing.
I notice a little bit of low frame rate like animation while moving the main window and that the download can be slower or faster depending on which server the file is on. 
![grafik](https://user-images.githubusercontent.com/52826614/102132927-943af980-3e54-11eb-91b6-716e32aaa070.png)

**Comment by quamt** [comment]
Seemed to be an issue on my machine.
After restart it was OK. 
Thank you for checking.

**Comment by quamt** [comment]
I did some more testing and was able to reproduce the issue.
It happens when redirect multi download to queue is enabled. 
If not enabled downloding has no issues.

**Comment by hama3254** [comment]
> I did some more testing and was able to reproduce the issue.
> It happens when redirect multi download to queue is enabled.
> If not enabled downloding has no issues.

Thanks for the feedback and testing, but i can not reproduce the issue and i don't see how that setting can affect the filesize or freezes the downloader. 
this setting just adds the urls from the Season download to the download queue.
![grafik](https://user-images.githubusercontent.com/52826614/102400249-eb220980-3fe1-11eb-9be1-c37d07a0358f.png)

**Comment by D3ltaNuub** [comment]
Hi, I tried your previous version of Crunchyroll downloader it worked fine, then I stopped using it. Now I downloaded the latest version and now every time I try to download an anime it just crashes.

**Comment by D3ltaNuub** [comment]
![image](https://user-images.githubusercontent.com/64754563/102808730-141b1380-43c1-11eb-9f4a-04ecfc63dc9c.png)

**Comment by hama3254** [comment]
@D3ltaNuub please enable the logfile in the settings and try again, if it still fails or you already had the logfile enabled then take a look at your set download path and see if there is a `.log` file with the name of the failed download.
