### ISSUE TITLE
Support ADN 

### ISSUE THREAD

**Issue by Ever4engel** [hama3254/Crunchyroll-Downloader-v3.0#113]
Hello

could you please consider supporting [https://animedigitalnetwork.fr/](https://animedigitalnetwork.fr/) ?

it's a french VOD editor for animes (like funimation and Crucnhyroll)

it require a free account to watch anime (in 480P) with premium account it could unlock all the catalog (in 1080P)

**Comment by hama3254** [comment]
I can not look at that VoD service since they use Geo blocking and i have just a German and US VPN so i just get that :
![grafik](https://user-images.githubusercontent.com/52826614/102509232-96849a00-4086-11eb-9eb3-cdef72a3b90e.png)

**Comment by Ever4engel** [comment]
you must use a french speaking territory (France, Belgium and so on)

**Comment by hama3254** [comment]
> you must use a french speaking territory (France, Belgium and so on)

as i sayed 




> i have just a German and US VPN

**Comment by Ever4engel** [comment]
i recommend you this public vpn (educationnal vpn) he's from japan, you'll find all countries in it with a fair bandwidth.
[VPNgate](https://www.vpngate.net/en/)

But if you don't want to invest on it , all what i can say is, you done a outstanding app for Crunchyroll and funimation thanks a lot for it

**Comment by hama3254** [comment]
developing a downloader over a vpn is not that funny so i pass on that until [Mozilla launches there service ](https://vpn.mozilla.org/).

[but you can give the network scan a chance](https://www.youtube.com/watch?v=fqWotJY7p94), if it is a m3u8 file it should work to find the video, if they use softsubs it might be a problem if they don't use `.vtt` or just ignore the right format (like crunchyroll) and use `.txt` as file extension

**Comment by Ever4engel** [comment]
yes it use m3u8 files 
How i'm i supposed to catch subs (theoretically) ?

**Comment by hama3254** [comment]
> yes it use m3u8 files
> How i'm i supposed to catch subs (theoretically) ?

if they are using hardsub then the subtitles are anyways burned/written in the video stream so you don't need to do anything expect getting the videofile.
if they use softsubs it wont work with the current downloader version even if you get the video, i just looked at the code and i have no idea what i did back then (it has been a while) but the compled funktion is just bad and txt or vtt get searched but never processed ... 
you can see them in the network traffic but it is just impossible to find if you don't know what you are looking for like on crunchyroll, the subs are the only `.txt` file if you know that ok, if not then good luck finding them...
![grafik](https://user-images.githubusercontent.com/52826614/102546715-5807d300-40b8-11eb-8857-58e5d33d0c51.png)

**Comment by hama3254** [comment]
i now rewrite the network grabber and try to get as many sub files as possible

**Comment by Ever4engel** [comment]
ADN use softsubs

**Comment by hama3254** [comment]
> ADN use softsubs

if found this : https://github.com/ytdl-org/youtube-dl/issues/12724 

as far i have understand they encrypt the subtitles which is outside of my capability.
You can try with youtube-dl but my downloader won't be able to get them if that is still true.

**Comment by Ever4engel** [comment]
> 
> 
> > ADN use softsubs
> 
> if found this : [ytdl-org/youtube-dl#12724](https://github.com/ytdl-org/youtube-dl/issues/12724)
> 
> as far i have understand they encrypt the subtitles which is outside of my capability.
> You can try with youtube-dl but my downloader won't be able to get them if that is still true.

Yeah i use it from while ago it rip ADN and Crunchyroll an and bunch of ather websites (videos and subs).
the drawbacks of youtube dl is, a command line app...

**Comment by hama3254** [comment]
I continue to improve the network scan but a dedicated function for ADN will never be there as long they use encrypted soft subtitles.
I close this now if you have any other question feel free to make a new issue.
