### ISSUE TITLE
Batch Download (Complete Season/Anime)

### ISSUE THREAD

**Issue by ramxdier** [hama3254/Crunchyroll-Downloader-v3.0#114]
Is there a way to download all the subtitles of a season/anime in one download?

**Comment by Ever4engel** [comment]
yes there is a way to do it

**Comment by Ever4engel** [comment]
one language at a time 
![image](https://user-images.githubusercontent.com/47645041/102540109-d9f2fe80-40ae-11eb-9cbb-e9ab7844fd91.png)
and do save 

you go to subtitles download

![image](https://user-images.githubusercontent.com/47645041/102540573-8208c780-40af-11eb-9ac3-b7ff80e63a91.png)

**Comment by hama3254** [comment]
If there are no further questions i close this now.
Feel free to make a new issue if you have any other question.

**Comment by snintendog** [comment]
not an issue but This is a great candidate to be added to the README.
