### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by REDAKUN** [hama3254/Crunchyroll-Downloader-v3.0#118]
Enter your version below, it can be found in the "About" section of the settings.
Version : v3.7

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 

![Capture](https://user-images.githubusercontent.com/68442725/103113786-85c2be00-465c-11eb-8940-c4b5055ca23e.PNG)

**Comment by hama3254** [comment]
You need the x86 version from the visual c++ redistributable 2019
[wich you can download here:](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

![grafik](https://user-images.githubusercontent.com/52826614/93120687-03714800-f6c4-11ea-9109-2538679ad19a.png)
