### ISSUE TITLE
Crunchyroll removed soft subtitles

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#12]
for now it seems that cr has removed the soft subtiles and uses hard subtitles on there website.
i remove the button for the softsubtile soon and ignore the settings in the next version, please make sure you set the right hard sub in the settings.

**Comment by Luro02** [comment]
You can not get them with the Xml RPC API? https://github.com/CloudMax94/crunchyroll-api/wiki/rpc-api

**Comment by hama3254** [comment]
Soft Subs are back like it was before!
