### ISSUE TITLE
Freezing download

### ISSUE THREAD

**Issue by juaao** [hama3254/Crunchyroll-Downloader-v3.0#121]
The download starts, but after a while the download freeze and does not progress.
I waited to see if the download will continue, but nothing happened and it stopped at 26%

![Sem título](https://user-images.githubusercontent.com/65497651/103320305-95068a80-4a13-11eb-9454-b1b386273a1a.png)

**Comment by hama3254** [comment]
please use the context menu (right click on the download) to copy the log into the clipboard and paste it here.

**Comment by juaao** [comment]
[5.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5754983/5.log)
I closed the app and the download disappeared. I started another download and the same thing happens, this time stuck at 16%.

**Comment by hama3254** [comment]
> I closed the app and the download disappeared

That's normal.


>  I started another download and the same thing happens, this time stuck at 16%.

based on the logfile there is nothing wrong, it's nothing really wrong the media library i use ([ffmpeg](https://ffmpeg.org/)) just stops as it seems. 

You can try to enable the hybrid mode in the settings maybe that works better for you.
