### ISSUE TITLE
Different Subtitle Font?

### ISSUE THREAD

**Issue by MarbleMann** [hama3254/Crunchyroll-Downloader-v3.0#127]
I have a suggestion, i know this may sound stupid and not necessary but will there ever be an option to select different fonts like for instance impact font or sans serif?

**Comment by hama3254** [comment]
> this may sound stupid and not necessary

It does not sound stupid but it's unnecessary.
If you Download soft subtitles you can change the subtitle files as you like it.
I am sure there are already programs that allow you to modify every of the 4 formats my downloader can provide.
