### ISSUE TITLE
[AOD] Episoden Benennung´s Bug

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#128]
Hy ich wünsche dir erstmal ein Gutes neues Jahr!

Mir ist bei der Version 3.7 ein Fehler bei der Episoden Benennung aufgefallen.
Die Erste Episode (Wenn Mann mehrere runterlädt) wird noch Richtig benannt  aber ab der 2. Folge wird dann der Name der Ersten Episode benutzt und der Name der 2. Episode angehängt. Bei den Episoden 3 & 4 Verschlimmert sich das ganze dann.

Gefühlt alle 2 Folgen stürzt das Programm komplett ab ohne Fehlermeldung schließt sich das Programm komplett.
Aber erst nachdem die Folgen runtergeladen wurden und dann erst im zusammenfügen Prozess (der Temp Ordner mit den TS-Parts ist noch vorhanden). Vielleicht weil der Dateiname zu lang ist!?

Vielen Dank schon mal.

![3 7](https://user-images.githubusercontent.com/74493510/103635304-9cb0bc80-4f48-11eb-9bed-f6b1923799bb.png)

**Comment by hama3254** [comment]
warum der downloader abstürzt sollte im Windows event log stehen, das mit den namen ist aber durchaus seltsam, vorallem weil es dass auf einmal wieder anfängst du passen ab der fünften folge.

Das mit den Namen schau ich mir mal an, für die abstürzte müsstest du im eventlog nachsehen.

**Comment by hama3254** [comment]
Das mit dem Namen hab ich gelöst, aber abstürze kann ich keine feststellen : 
![grafik](https://user-images.githubusercontent.com/52826614/103646362-d6d68a00-4f59-11eb-8116-12f0cb2a67ce.png)

**Comment by Schizo1987** [comment]
Wegen den Abstürzen habe ich jetzt im Eventlog nachgesehen

<details>
  <summary>.Net Runtime</summary>
  

  ```
Anwendung: Crunchyroll Downloader.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.InvalidOperationException
   bei System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   bei System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   bei System.Windows.Forms.Control.Invoke(System.Delegate)
   bei Crunchyroll_Downloader.CRD_List_Item.FFMPEGOutput(System.Object, System.Diagnostics.DataReceivedEventArgs)
   bei System.Diagnostics.Process.ErrorReadNotifyUser(System.String)
   bei System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   bei System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   bei System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   bei System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   bei System.Threading.Tasks.Task.FinishContinuations()
   bei System.Threading.Tasks.Task.FinishStageThree()
   bei System.Threading.Tasks.Task.FinishStageTwo()
   bei System.Threading.Tasks.Task.Finish(Boolean)
   bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   bei System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   bei System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
   bei System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
  
</details>
<details>
  <summary>Application Error</summary>
  

  ```
Name der fehlerhaften Anwendung: Crunchyroll Downloader.exe, Version: 3.7.0.0, Zeitstempel: 0x5fe4b927
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.662, Zeitstempel: 0xe6477cce
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0012a892
ID des fehlerhaften Prozesses: 0xda4
Startzeit der fehlerhaften Anwendung: 0x01d6e34b2e0330d6
Pfad der fehlerhaften Anwendung: N:\******\Crunchyroll Downloader.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 0410e0f0-67cd-4160-b8db-8816e070f5af
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

**Comment by hama3254** [comment]
Warum Windows mit der Funktion jetzt auf einmal Probleme hat wäre interessant zu wissen, `FFMPEGOutput` funktioniert seit längerem gleich inklusive UI zugriff welcher jetzt scheinbar eine `InvalidOperation` ist...
kannst du deine Windows Version sagen ich hab nämlich nur Windows 10 Pro 1909 drauf.

schau mal was die version v3.7.1 macht, einfach nur die `.exe` ins selbe Verzeichnis legen wie die alte ist und starten
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7

**Comment by Schizo1987** [comment]
Ich habe vor ein paar tagen die Windows 20H2 19042.685 rauf gemacht.

Danke schon mal ich werde die neue Version gleich testen!

**Comment by Schizo1987** [comment]
Habe jetzt 8 Folgen Runtergeladen ohne Probleme und richtiger Episoden-Benennung.

Vielen vielen Dank!

**Comment by hama3254** [comment]
nur mal aus Neugier kannst du in die Konsole schauen, da sollte der Fehler drinnen stehen wenn er wieder auftritt 
![grafik](https://user-images.githubusercontent.com/52826614/103662672-8159a780-4f70-11eb-9cf3-792e88817535.png)

**Comment by Schizo1987** [comment]
Vorhin habe ich 13 Folgen am Stück runtergeladen dann hing das Programm. Es war noch Offen aber es hat sich nichts mehr getan ich musste es schließen. Jetzt Lade ich noch ein paar Folgen runter und schau in der Konsole 👍

**Comment by hama3254** [comment]
Ich mach hier mal zu, falls wieder was ist einfach ein neues aufmachen
