### ISSUE TITLE
How to Add it to chrome Extension 

### ISSUE THREAD

**Issue by MarbleMann** [hama3254/Crunchyroll-Downloader-v3.0#129]
If im not wrong at one point you talked about how you can have this as an extension on chrome? How do i take the V3.7.zip file and make it to an extension?$

**Comment by hama3254** [comment]
I guess you misunderstood something.
There is a chrome extension to allow a (limited) control of the downloader from the browser. (You need to enable it in the settings of the downloader)
This looks then like this : https://youtu.be/ZHCH3rNWYS8
To install the chrome add-on use this guide:
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-guide

**Comment by MarbleMann** [comment]
Oke Thank you very much for helping me
