### ISSUE TITLE
Can't download single episode

### ISSUE THREAD

**Issue by weareblahs** [hama3254/Crunchyroll-Downloader-v3.0#13]

**Comment by hama3254** [comment]
please add more information to the issue. 
What version of the downloader are you using?
what episodes you have tryed?
from what country are? 
whats your settings?

**Comment by weareblahs** [comment]
Version 3.1.4
Keep Your Hands Off Eizouken! (https://www.crunchyroll.com/keep-your-hands-off-eizouken), Episode 1
I'm using the US Cookie
Here's my settings:
![image](https://user-images.githubusercontent.com/37889443/74100825-e3960680-4b6d-11ea-96d1-05a6def5ec33.png)
![image](https://user-images.githubusercontent.com/37889443/74100830-eb55ab00-4b6d-11ea-858b-45288c5aae97.png)
![image](https://user-images.githubusercontent.com/37889443/74100834-f6a8d680-4b6d-11ea-8102-7474ef23d752.png)

**Comment by hama3254** [comment]
i can not see anything wrong with this episode in v3.1.4
do you get a error message  or does it not do anything at all? 
![3](https://user-images.githubusercontent.com/52826614/74101338-ef1b0a80-4b38-11ea-9139-a16c5c897834.PNG)

**Comment by weareblahs** [comment]
When I click "Download", it just closes back to the Crunchyroll Downloader page with **Status: null**. If I download Episode 1 and Episode 2 together, like this: 
![image](https://user-images.githubusercontent.com/37889443/74101451-e7795700-4b74-11ea-9514-693c85b33976.png)
The download works properly.

Maybe it's a bug on my PC.

**Comment by hama3254** [comment]
I'm sorry but i can not reproduce this error : https://www.youtube.com/watch?v=Xy3JSOm8qAc

can you open the webbrowser (the worl icon on the top left) while trying to download it again and tell me if the URL is correct wich he try's to access ?

**Comment by weareblahs** [comment]
Using the episode link (https://www.crunchyroll.com/keep-your-hands-off-eizouken/episode-1-the-greatest-world-792447) works.

**Comment by hama3254** [comment]
if this comment was not from you than i really would like to look for more details what this may cause.
i already know from the past that Crunchyroll uses ramdon people as "beta testers" without telling someone [like at the time they change the player](https://www.crunchyroll.com/de/anime-news/2019/10/04/meet-the-new-crunchyroll-web-video-player)
![5](https://user-images.githubusercontent.com/52826614/74103081-69538b00-4b49-11ea-88e8-6efb8ca2076d.png)
