### ISSUE TITLE
Funimation Uzaki Chan

### ISSUE THREAD

**Issue by MarbleMann** [hama3254/Crunchyroll-Downloader-v3.0#132]
So i wanna Batch Download all the eps of Uzaki chan wants to hang out on funimation, but when i put a link it says "no video found" can you plz help me with downloading  all the eps of Uzaki Chan Wants to hang out?

**Comment by hama3254** [comment]
This happens if you use not a funimation url with a video stream, funimation works not that easy to mass download : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/116
