### ISSUE TITLE
Funimation Download crashes immediately

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#135]
Version: 3.7

I keep trying to download The Highschoold DxD Episode 9 from Funimation and it keeps crashing. The only time it doesn't crash is when I **disable** the hard subtitle for English. But I want the English hard subtitles.

<img width="810" alt="error 01" src="https://user-images.githubusercontent.com/75436296/104394896-e3d91780-551d-11eb-8588-1b70d237c19c.png">
<img width="731" alt="error 02" src="https://user-images.githubusercontent.com/75436296/104394897-e5a2db00-551d-11eb-9b2b-16e4bb8eaec5.png">

**Comment by hama3254** [comment]
Please add the log here.
You can copy it from the context menu of the failed download : Right click in the failed download and copy log to clipboard

**Comment by Azul772** [comment]
1/13/2021 6:28:48 AM -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0" -i "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/1349501/Japanese/1349501_Japanese_a394af20-c5a4-e811-8175-020165574d09_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xMzQ5NTAxL0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MTA1MzczMjR9fX1dfQ__&Signature=cXoGZeeBcfp8~JeA30BMOkXRXnWU2t3~3XWxf9dcHWPeXrUorAZHYBckijIZmwEeB9MCV63EG8KEGZsOfpMkmPenq4L5NUGCPs~5wEtMlAMifGBCaVQlYAeXpGE9mF-W61rryPBUoAmvRMSrsTduw7iErCRRjir1cJJH1eXdKBSlY7Xef45UhAU4JLcYMLDe5iYfL-eCjtSYGi7kqg-vClY9Y0p1~crTnVFlrtNbWfn3pUqgQxVH85~ASg1pQ9VtdsmjCIMd2U-GqOLBVAyO3ALFf3JXPjVU2LyBUqQYBCk~SgGq9Ip5XwkNa51qPpn8kSISddtpXLXKgpj7qqJwNg__&rt=1437932" -vf subtitles="CRD-Temp-File-IgLIcMgKMHSYMTYT.dfxp" -bsf:a aac_adtstoasc "D:\A\High School DxD\High School DxD Season 1 Episode 9 I x27 ve Begun My Training.mp4"

1/13/2021 6:28:48 AM ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
1/13/2021 6:28:48 AM   built with gcc 9.3.1 (GCC) 20200523
1/13/2021 6:28:48 AM   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
1/13/2021 6:28:48 AM   libavutil      56. 31.100 / 56. 31.100
1/13/2021 6:28:48 AM   libavcodec     58. 54.100 / 58. 54.100
1/13/2021 6:28:48 AM   libavformat    58. 29.100 / 58. 29.100
1/13/2021 6:28:48 AM   libavdevice    58.  8.100 / 58.  8.100
1/13/2021 6:28:48 AM   libavfilter     7. 57.100 /  7. 57.100
1/13/2021 6:28:48 AM   libswscale      5.  5.100 /  5.  5.100
1/13/2021 6:28:48 AM   libswresample   3.  5.100 /  3.  5.100
1/13/2021 6:28:48 AM   libpostproc    55.  5.100 / 55.  5.100
1/13/2021 6:28:48 AM [https @ 060b4080] No trailing CRLF found in HTTP header. Adding it.
1/13/2021 6:28:51 AM [hls @ 060c4480] Skip ('#EXT-X-VERSION:3')
1/13/2021 6:28:53 AM [hls @ 060c4480] Opening 'https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/1349501/Japanese/1349501_Japanese_a394af20-c5a4-e811-8175-020165574d09_Layer10_0.key' for reading
1/13/2021 6:28:53 AM [hls @ 060c4480] Opening 'crypto+https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/1349501/Japanese/1349501_Japanese_a394af20-c5a4-e811-8175-020165574d09_Layer10_00000.ts?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xMzQ5NTAxL0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MTA1MzczMjR9fX1dfQ__&Signature=cXoGZeeBcfp8~JeA30BMOkXRXnWU2t3~3XWxf9dcHWPeXrUorAZHYBckijIZmwEeB9MCV63EG8KEGZsOfpMkmPenq4L5NUGCPs~5wEtMlAMifGBCaVQlYAeXpGE9mF-W61rryPBUoAmvRMSrsTduw7iErCRRjir1cJJH1eXdKBSlY7Xef45UhAU4JLcYMLDe5iYfL-eCjtSYGi7kqg-vClY9Y0p1~crTnVFlrtNbWfn3pUqgQxVH85~ASg1pQ9VtdsmjCIMd2U-GqOLBVAyO3ALFf3JXPjVU2LyBUqQYBCk~SgGq9Ip5XwkNa51qPpn8kSISddtpXLXKgpj7qqJwNg__&rt=1437932' for reading
1/13/2021 6:28:56 AM Input #0, hls, from 'https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/1349501/Japanese/1349501_Japanese_a394af20-c5a4-e811-8175-020165574d09_Layer10.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8xMzQ5NTAxL0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MTA1MzczMjR9fX1dfQ__&Signature=cXoGZeeBcfp8~JeA30BMOkXRXnWU2t3~3XWxf9dcHWPeXrUorAZHYBckijIZmwEeB9MCV63EG8KEGZsOfpMkmPenq4L5NUGCPs~5wEtMlAMifGBCaVQlYAeXpGE9mF-W61rryPBUoAmvRMSrsTduw7iErCRRjir1cJJH1eXdKBSlY7Xef45UhAU4JLcYMLDe5iYfL-eCjtSYGi7kqg-vClY9Y0p1~crTnVFlrtNbWfn3pUqgQxVH85~ASg1pQ9VtdsmjCIMd2U-GqOLBVAyO3ALFf3JXPjVU2LyBUqQYBCk~SgGq9Ip5XwkNa51qPpn8kSISddtpXLXKgpj7qqJwNg__&rt=1437932':
1/13/2021 6:28:56 AM   Duration: 00:23:57.89, start: 1.440756, bitrate: 1 kb/s
1/13/2021 6:28:56 AM   Program 0 
1/13/2021 6:28:56 AM     Metadata:
1/13/2021 6:28:56 AM       variant_bitrate : 0
1/13/2021 6:28:56 AM     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
1/13/2021 6:28:56 AM     Metadata:
1/13/2021 6:28:56 AM       variant_bitrate : 0
1/13/2021 6:28:56 AM     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
1/13/2021 6:28:56 AM     Metadata:
1/13/2021 6:28:56 AM       variant_bitrate : 0
1/13/2021 6:28:56 AM Stream mapping:
1/13/2021 6:28:56 AM   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
1/13/2021 6:28:56 AM   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
1/13/2021 6:28:56 AM Press [q] to stop, [?] for help
1/13/2021 6:28:56 AM [Parsed_subtitles_0 @ 0916d640] Shaper: FriBidi 1.0.9 (SIMPLE)
1/13/2021 6:28:56 AM [Parsed_subtitles_0 @ 0916d640] Unable to open CRD-Temp-File-IgLIcMgKMHSYMTYT.dfxp
1/13/2021 6:28:56 AM [AVFilterGraph @ 067c6f80] Error initializing filter 'subtitles' with args 'CRD-Temp-File-IgLIcMgKMHSYMTYT.dfxp'
1/13/2021 6:28:56 AM Error reinitializing filters!
1/13/2021 6:28:56 AM Failed to inject frame into filter network: Invalid data found when processing input
1/13/2021 6:28:56 AM Error while processing the decoded data for stream #0:0
1/13/2021 6:28:56 AM [aac @ 066fde00] Qavg: 9073.819
1/13/2021 6:28:56 AM [aac @ 066fde00] 2 frames left in the queue on closing
1/13/2021 6:28:56 AM Conversion failed!
1/13/2021 6:28:56 AM 
1/13/2021 6:28:56 AM

**Comment by hama3254** [comment]
i see the issue, i just used a random subtitle format without knowing that `dfxp` does not work while `vtt` and `srt` do.
![grafik](https://user-images.githubusercontent.com/52826614/104621563-8913fd00-5690-11eb-80f1-dff3e7c4d0ef.png)

**Comment by hama3254** [comment]
i added an filter for vtt and srt subfiles to that function so it should work now :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.2

**Comment by Azul772** [comment]
Thanks, it worked.
