### ISSUE TITLE
Can't download a season from crunchyroll

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#136]
Version: 

I tried to download the third season of my My Teen Romantic Comedy SNAFU on crunchyroll, the one that says "Climax!" and the download doesn't even start. It just gives me this error message whether I try to download in batch or separately.
<img width="1920" alt="error 01" src="https://user-images.githubusercontent.com/75436296/104632274-d3d34c00-5673-11eb-93e4-b36d1eef7eed.png">

**Comment by hama3254** [comment]
i see the issue, it's the old naming method that i keeped in there as backup file name.
That combined with a strange website title (even if i change it to english it stays german) with "Watch on Crunchyroll" missing gives a empty backup name. 
![grafik](https://user-images.githubusercontent.com/52826614/104635591-64288580-56a2-11eb-81e7-50d79c51b6f6.png)

i simply removed it : 
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.2.1

**Comment by Azul772** [comment]
Thank you, it worked.
