### ISSUE TITLE
No media found in

### ISSUE THREAD

**Issue by Killuad** [hama3254/Crunchyroll-Downloader-v3.0#138]
When I try to dowload a video from funimation I get this error
![Captura de pantalla (1)](https://user-images.githubusercontent.com/71679711/104662702-03448180-5691-11eb-9c43-390052b282b0.png)

Idk if I'am doing something wrong, I'm from Mexico and i only copy the link where the video is attached. for example this
"  https://www.funimation.com/shows/assassination-classroom/assassination-time/?qid=undefined  "

Also i have tried with other series and episedes and i still getting the same error (with Crunchyroll it works perfectly)

**Comment by Ferfu** [comment]
![image](https://user-images.githubusercontent.com/32347896/104671901-76fc8380-56bd-11eb-896f-fc07e40d639f.png)

I can't download it by placing the direct link where you showed above, but a bass like the one shown in the image,
only way I managed to download single episodes was using the browser addon

**Comment by hama3254** [comment]
> When I try to dowload a video from funimation I get this error
> ![Captura de pantalla (1)](https://user-images.githubusercontent.com/71679711/104662702-03448180-5691-11eb-9c43-390052b282b0.png)
> 
> Idk if I'am doing something wrong, I'm from Mexico and i only copy the link where the video is attached. for example this
> " https://www.funimation.com/shows/assassination-classroom/assassination-time/?qid=undefined "
> 
> Also i have tried with other series and episedes and i still getting the same error (with Crunchyroll it works perfectly)

The error code tells you what's wrong, there is no free version of that episode avalible, based on the website background the only free language is japanese so you either select japanese or you have to login at the build in Webbrowser to allow the downloader access with the account cookies.
You can set the dub language in the settings, this will add  a tag to the url if not already there which leads funimation to load that language.

**Comment by Killuad** [comment]
I logged in using the webbrowser from the program, but I had to change the default adress from settings, otherwise when i closed the browser it sign me off.

**Comment by hama3254** [comment]
>  but I had to change the default adress from settings, otherwise when i closed the browser it sign me off.

i'm not sure how that should work since the default page is just a address that i load after the browser gets opened by the user.



> Also i had another problem, when i log in with my account and triend to dowload videos it automatically set Español as dub language, even if i set japanese in the configuration. I change the default language from funimation configuration but it didn´t fix it.
> Idk how but it got fixed after a couple of attemps.

The language setting for funimation adds the tag for the chosen language but does not override existing ones.

more an that here : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/139

**Comment by hama3254** [comment]
> The language setting for funimation adds the tag for the chosen language but does not override existing ones.

This has been changed and now it should override the tag if it is not disabled
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3
