### ISSUE TITLE
funimation forcing language

### ISSUE THREAD

**Issue by Ferfu** [hama3254/Crunchyroll-Downloader-v3.0#139]
**funimation link forces the program to download in the language the link is in**

****Example**,**
https://www.funimation.com/pt-br/shows/my-hero-academia/rage-you-damn-nerd/uncut/?lang=japanese&qid=

this episode has the tag "lang=japonese", even if i change the audio to english or portuguese it continues with this tag
on the link and when I download this episode it forces the audio in Japonese

**Comment by hama3254** [comment]
The downloader has an option to add this tag, however it does not over write existing ones.
(I probably should add over writing as extra setting.)
You need simply to remove that tag from the url then the downloader can add it's own tag again.

**Comment by hama3254** [comment]
The new version v3.7.3 should now override existing languages tags :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3

**Comment by Ferfu** [comment]
I tested it the way you told me to just change the language name on the tag and it worked fine.
then I saw that you updated the program to automatically replace the tag, really good, I tested it and it works perfectly

thank you so much.

**Comment by hama3254** [comment]
>  I tested it and it works perfectly

Thanks for the feedback, i think i can close this now.
if you have any more questions feel free to make a new issue.
