### ISSUE TITLE
Wakanim Player Support ?

### ISSUE THREAD

**Issue by Mujaca** [hama3254/Crunchyroll-Downloader-v3.0#14]
I tried a few days ago to download an Episode from wakanim using youre Crunchyroll downloader and as far as i understood this should work totally fine. 
The Problem is, that the Player throws an Error : 
![image](https://user-images.githubusercontent.com/47077607/75522943-65f64580-5a0b-11ea-8cf2-381bef1003ca.png). 
Would it be possible to implement a support for wakanim?

**Comment by hama3254** [comment]
Wakanim ist nicht Supportet und wird auch nicht gehen, da sie einen Kopierschutz auf ihren Streams haben.
Die einzige Möglichkeit die ich kenne das zu umgehen wäre die [analoge lücke](https://www.heise.de/newsticker/meldung/Urteil-bestaetigt-Existenz-der-analogen-Luecke-im-Urheberrecht-142631.html) also einfach den Bildschirm mit Ton aufnehmen aber dafür eine Software zu entwickeln wäre wettbewerbswidrig.
