### ISSUE TITLE
Error: System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by Killuad** [hama3254/Crunchyroll-Downloader-v3.0#140]
Hi!

I have a little problem to report i think. When i try to open the program sometimes it give me this error, and when it appears I´m not able to use the firefox add-on.
![Captura de pantalla (2)](https://user-images.githubusercontent.com/71679711/104776567-e4e98f00-573f-11eb-80f9-932ac9f49342.png)
![Captura de pantalla (3)](https://user-images.githubusercontent.com/71679711/104776572-e61abc00-573f-11eb-84ef-2f868af0ec86.png)

The only way that i found to fix it is rebooting my PC

**Comment by hama3254** [comment]
This is an issue with an still running background process of the downloader while starting it again, it still blocks the http port which connects to the add-on but has no UI so while string to add something the UI access will fail resulting in that error.
The question is how do you tried close the first one?

**Comment by hama3254** [comment]
i added the stop command to the port listener of the web server, after pressing the close button of the main windows it should stop the build in web server even if it does not shutdown as it should.

https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3
