### ISSUE TITLE
Can't open Crunchyroll Downloader.

### ISSUE THREAD

**Issue by Dltanuub** [hama3254/Crunchyroll-Downloader-v3.0#145]
Hi, I downloaded your recently updated Crunchyroll Downloader but when I try to open it I get an error box with a bunch of messages. 
![image](https://user-images.githubusercontent.com/42467895/104964118-1aaaa400-59dc-11eb-812d-187a42f0cb2a.png)

**Comment by hama3254** [comment]
You need to have the x86 version from the Visual C++ redistributable which you can find here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
