### ISSUE TITLE
Crunchyroll.Downloader.v3.7.3.1.exe not working

### ISSUE THREAD

**Issue by maxlefou** [hama3254/Crunchyroll-Downloader-v3.0#149]
as title says. this exe is very small and doesn't do anything.

Fortunately there's the zip version aside...

**Comment by hama3254** [comment]
That's just an hotfix for issues #144 and #146 and needs to be placed in a v3.7.3 folder.

**Comment by hama3254** [comment]
This version has been removed, you should go back to v3.7.3 for the moment.
