### ISSUE TITLE
where the subtitles are stored?

### ISSUE THREAD

**Issue by marcocorriero** [hama3254/Crunchyroll-Downloader-v3.0#15]
Title

**Comment by hama3254** [comment]
There are two ways subtitles are stored, as ".ass" file in the same folder as the video file or inside the video files. 
Wich way depends on your settings, Hardsubtitle will save the Episodes with burned-in subtitles, softsubtitles can be attached to the video file or just download as extra files.
In both cases it may require to activate then in your player.
