### ISSUE TITLE
How Do I Remove Videos From Queue

### ISSUE THREAD

**Issue by MarbleMann** [hama3254/Crunchyroll-Downloader-v3.0#161]
So i went in setting on the latest version on CR Downloader and enabled The "Redirect Multi Downloads to queue" but now i cant download anything because stuff is in queue. But It Doesnt Show Any Episodes In queue. How to i remove the files from the queue?

**Comment by hama3254** [comment]
If the queue appears to be empty then just close the add form, if that does not work try to restart the downloader (after finishing all running downloads).
Normally a double click on the link deletes it from the queue.

**Comment by MarbleMann** [comment]
I tried restarting the downloader but then when i tried to download some tokyo ghoul off funimation via the chome addon  it added to queue but not in the viewable queue

**Comment by hama3254** [comment]
> But it might just be my laptop because i use a 2001 Acer Laptop

I have no chance of knowing the performance of a device that is just 5 years younger than me ...

And my current system is top of the line so even just a view year old hardware is a huge difference and I can not test it perfectly.

![grafik](https://user-images.githubusercontent.com/52826614/105504690-59847680-5cc8-11eb-962a-cbd4edd6e4c2.png)

**Comment by MarbleMann** [comment]
Oke, Also just Like an Hour Ago I Fixed it.

**Comment by hama3254** [comment]
> Oke, Also just Like an Hour Ago I Fixed it.

if everything works now i can close this
