### ISSUE TITLE
Can't open funimation site

### ISSUE THREAD

**Issue by xZebaahx** [hama3254/Crunchyroll-Downloader-v3.0#163]
Whenever I try to open funimation to login I get the following error message:

www.funimation.com uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

Error code: <a id="errorCode" title="SEC_ERROR_UNKNOWN_ISSUER">SEC_ERROR_UNKNOWN_ISSUER</a>

Crunchyroll works fine

**Comment by xZebaahx** [comment]
Error code: <a id="errorCode" title="SEC_ERROR_UNKNOWN_ISSUER">SEC_ERROR_UNKNOWN_ISSUER</a>

**Comment by hama3254** [comment]
I'm aware of this due to #162 but I'm not sure what causes this that.
Some also experience this Problem in the normal Firefox others not.
Please check the normal Firefox and add your country.

**Comment by xZebaahx** [comment]
Funimation works fine in Desktop Firefox
I'm from Chile

**Comment by H3rdell** [comment]
Same error of "Funimation invalid security certificate" here. I'm from Brazil.

**Comment by xZebaahx** [comment]
> I'm aware of this due to #162 but I'm not sure what causes this that.
> Some also experience this Problem in the normal Firefox others not.
> Please check the normal Firefox and add your country.

Fixed the problem by installing Entrust certificates in Firefox, I don't know exactly which one did the trick, as I installed them all.
link here: https://www.entrust.com/resources/certificate-solutions/tools/root-certificate-downloads

**Comment by H3rdell** [comment]
> 
> Fixed the problem by installing Entrust certificates in Firefox, I don't know exactly which one did the trick, as I installed them all.
> link here: https://www.entrust.com/resources/certificate-solutions/tools/root-certificate-downloads

Hi. How did you to install the certificates? I installed all of them but the problem stills. Can you please share details on how did you?

**Comment by hama3254** [comment]
I would not recommend installing any unknown certificates.

This seems on one side not to be a isolated problem of the downloader but at the other side with the normal Firefox working i have no idea what is going on.

The last info from #162 

>I looked in some anime forums, and apparently it's a problem with Funimation itself, not with the program. Although there is no solution, users reported that the problem disappeared on its own in a few days. For me, I tried to download today, and it worked fine.
>
>Thank you very much @hama3254 for all your support.

_Originally posted by @LogusRed in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/162#discussioncomment-325742_

**Comment by xZebaahx** [comment]
> > Fixed the problem by installing Entrust certificates in Firefox, I don't know exactly which one did the trick, as I installed them all.
> > link here: https://www.entrust.com/resources/certificate-solutions/tools/root-certificate-downloads
> 
> Hi. How did you to install the certificates? I installed all of them but the problem stills. Can you please share details on how did you?

Imported them on firefox (settings, privacy and security, at the bottom there's a button for certificates) some already were installed by default
