### ISSUE TITLE
Add new link during downloading

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#164]
Hi, possible to add fetaure where we can add new link during the program downloading the video?

**Comment by hama3254** [comment]
You already can, the only time you need to wait is the video grabbing itself and that is relatively short.

**Comment by x3inspire** [comment]
![Capture](https://user-images.githubusercontent.com/4635825/106383546-acb1a400-6401-11eb-8a68-1d242ea53553.JPG)
How to add another link during downloading like this?

**Comment by hama3254** [comment]
You can go back by pressing `Cancel ` and add new episodes.
the list will stay as it is. 
Or you use the add-on which adds even if the list is open.

https://user-images.githubusercontent.com/52826614/106386470-6b0b0400-63d5-11eb-906f-74820a66f08f.mp4

**Comment by x3inspire** [comment]
Oh i thought the video cancelled if we click cancel button? So it will go back to previous form instead of cancelled the current list?

**Comment by hama3254** [comment]
The "add video" window just adds the video to the downloader.
The download is controlled by the individual item-control itself and it's buttons.

**Comment by hama3254** [comment]
since this has been answered i close this.
