### ISSUE TITLE
How to download from funimation?

### ISSUE THREAD

**Issue by stayTranK2** [hama3254/Crunchyroll-Downloader-v3.0#165]
Is there any tutorial/guide to download from funimation? (Using this) because i cant find one :(

**Comment by hama3254** [comment]
There is no real tutorial for funimation, and that what I have is mostly unlisted on youtube.
First of all for all episodes which requires an account you have to login at the browser of the downloader, just open it with the world icon and navigate to funimation.
Single episode download is relatively easy, that's the same as for crunchyroll.
ou have to open the add window (top left icon) then enter the url and press download.
The downloader will use the preferences from the settings and looks for the specific resolution and subtitles.
To download an season at once is a little bit more complicated.
[I added a funimation button for that](https://youtu.be/18qBIUYdlEM) or [you could give the add-on a try](https://youtu.be/ZHCH3rNWYS8) 
You just need to enable it in the settings.
[Get it for Chrome](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-guide)
[Get it for Firefox](https://addons.mozilla.org/en-US/firefox/addon/crunchyroll-downloader-addon/)

**Comment by stayTranK2** [comment]
> There is no real tutorial for funimation, and that what I have is mostly unlisted on youtube.
> First of all for all episodes which requires an account you have to login at the browser of the downloader, just open it with the world icon and navigate to funimation.
> Single episode download is relatively easy, that's the same as for crunchyroll.
> ou have to open the add window (top left icon) then enter the url and press download.
> The downloader will use the preferences from the settings and looks for the specific resolution and subtitles.
> To download an season at once is a little bit more complicated.
> [I added a funimation button for that](https://youtu.be/18qBIUYdlEM) or [you could give the add-on a try](https://youtu.be/ZHCH3rNWYS8) 
> You just need to enable it in the settings.
> [Get it for Chrome](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-guide)
> [Get it for Firefox](https://addons.mozilla.org/en-US/firefox/addon/crunchyroll-downloader-addon/)

I paste the URL but when i press download, it says something like "funimation uses an invalid security certificate"
Any idea?

**Comment by hama3254** [comment]
not really, some report it's an issue with funimation while other just have this issue in the downloader.
you can read #162 and #163 for more information

**Comment by stayTranK2** [comment]
Do you think that that could be related to the fact that im from argentina? (so i need a vpn to acces funimation)

**Comment by hama3254** [comment]
I don't think the VPN makes that problem.
Other users that have access to Funimation the normal way also have this issue.
I'm also from a country (central Europe) needs a VPN to access there service and it works fine for me.

The only pattern i see is that all country's that seems to have problemlos are from south america
