### ISSUE TITLE
For Whom The Alchemist Exists The Movie - Error 502

### ISSUE THREAD

**Issue by ScarVite** [hama3254/Crunchyroll-Downloader-v3.0#166]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.7.3.2

link: https://www.crunchyroll.com/de/for-whom-the-alchemist-exists-the-movie/for-whom-the-alchemist-exists-the-movie-for-whom-the-alchemist-exists-the-movie-806647

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  

or 
<details>
  <summary>LogText: </summary>
05.02.2021 18:08:54 -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0" -i "https://pl.crunchyroll.com/evs1/5658585de077c2db252ca87208b3c59d/assets/6335542ea622f1f115f69128ae620e1c_3973628.mp4/index-v1-a1.m3u8?Expires=1612717735&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS81NjU4NTg1ZGUwNzdjMmRiMjUyY2E4NzIwOGIzYzU5ZC9hc3NldHMvNjMzNTU0MmVhNjIyZjFmMTE1ZjY5MTI4YWU2MjBlMWNfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MTI3MTc3MzV9fX1dfQ__&Signature=puxsSmjmjH2xzNA~DKiPIuXyB4-Y~uZ1aL9mTqAa~ZuACv1lSsOrbTgnwIldSrkQdcxs-G2aLozV87avac7WinpyAaOh96ZIgJbay4IvhjGNwL47xrGhSEsXMDxvj4cjYR6mAPr095s9jo4Y1s2XSvAnzwoKwbW1SAQoi0vt2tcY3hh6v6ONfD1rINrJ2GTbzwo1~NE2EsoJhvALMjNps-WQR7eOJARHAwyF465yM1Si-BARl-EIOesIDvqpzIcEzHYNLt1kp33eqRKAc9K8-7qXArb3OMYGmW8zuYvEiTr4n9kyOn9FU1mxj-h2R01phMjBRf~datNGcG71dr-ogw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod" -metadata:s:a:0 language=jpn  -c copy -bsf:a aac_adtstoasc "D:\Downloads\.mp4.mp4"
05.02.2021 18:08:54 ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
05.02.2021 18:08:54   built with gcc 9.3.1 (GCC) 20200523
05.02.2021 18:08:54   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
05.02.2021 18:08:54   libavutil      56. 31.100 / 56. 31.100
05.02.2021 18:08:54   libavcodec     58. 54.100 / 58. 54.100
05.02.2021 18:08:54   libavformat    58. 29.100 / 58. 29.100
05.02.2021 18:08:54   libavdevice    58.  8.100 / 58.  8.100
05.02.2021 18:08:54   libavfilter     7. 57.100 /  7. 57.100
05.02.2021 18:08:54   libswscale      5.  5.100 /  5.  5.100
05.02.2021 18:08:54   libswresample   3.  5.100 /  3.  5.100
05.02.2021 18:08:54   libpostproc    55.  5.100 / 55.  5.100
05.02.2021 18:08:54 [https @ 05d34580] No trailing CRLF found in HTTP header. Adding it.
05.02.2021 18:08:54 [https @ 05d34580] HTTP error 502 Bad Gateway
05.02.2021 18:08:55 https://pl.crunchyroll.com/evs1/5658585de077c2db252ca87208b3c59d/assets/6335542ea622f1f115f69128ae620e1c_3973628.mp4/index-v1-a1.m3u8?Expires=1612717735&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS81NjU4NTg1ZGUwNzdjMmRiMjUyY2E4NzIwOGIzYzU5ZC9hc3NldHMvNjMzNTU0MmVhNjIyZjFmMTE1ZjY5MTI4YWU2MjBlMWNfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MTI3MTc3MzV9fX1dfQ__&Signature=puxsSmjmjH2xzNA~DKiPIuXyB4-Y~uZ1aL9mTqAa~ZuACv1lSsOrbTgnwIldSrkQdcxs-G2aLozV87avac7WinpyAaOh96ZIgJbay4IvhjGNwL47xrGhSEsXMDxvj4cjYR6mAPr095s9jo4Y1s2XSvAnzwoKwbW1SAQoi0vt2tcY3hh6v6ONfD1rINrJ2GTbzwo1~NE2EsoJhvALMjNps-WQR7eOJARHAwyF465yM1Si-BARl-EIOesIDvqpzIcEzHYNLt1kp33eqRKAc9K8-7qXArb3OMYGmW8zuYvEiTr4n9kyOn9FU1mxj-h2R01phMjBRf~datNGcG71dr-ogw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod: Server returned 5XX Server Error reply
05.02.2021 18:08:55 
05.02.2021 18:08:55 
</details>

Edit: Attached LogFile as the copy output was malformed
[log.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5934151/log.log)

**Comment by hama3254** [comment]
The issue here is that they now use `HTTP compression` which works with ffmpeg but is not enabled by default. 
![grafik](https://user-images.githubusercontent.com/52826614/107073482-b95e3f80-67e7-11eb-9b0d-798454c44bd1.png)

i added the parameter and now it looks good, but i found another issue with the naming so the update will come in the next days.
![grafik](https://user-images.githubusercontent.com/52826614/107076552-deed4800-67eb-11eb-871c-ef93e4b75117.png)

**Comment by hama3254** [comment]
this issue has been fixed with v3.7.4.
if there are no other question i would close this.
