### ISSUE TITLE
Funimation related problem

### ISSUE THREAD

**Issue by DaerLegrand** [hama3254/Crunchyroll-Downloader-v3.0#169]
Hello, first of all, thanks for developing this, it is really helpful.
I have that Funimation certificate problem.
![image](https://user-images.githubusercontent.com/67795896/107289033-6b894780-6a32-11eb-9920-4f7ffd7001b5.png)

The thing is I'm from a country where Funimation is not available yet, but I got some URLs of the shows I really like thanks to google.
When I enter the URL and download it, I get that certificate error.

**Comment by hama3254** [comment]
This is a known problem, unfortunately I don't know what causes this.
I am also not from a country where funimation is available, but neither with VPN or without i get this error.
.
Some have this just in the downloader while others report the same issue in the normal Firefox as well.
You can read #162 and #163 for more information
