### ISSUE TITLE
"Please Make sure that the url is correct" even that url is correct

### ISSUE THREAD

**Issue by theruleof4** [hama3254/Crunchyroll-Downloader-v3.0#17]
Some series are showing this error, I paste the url normally, it recognizes the series, I select the episodes, but when it goes to download this message appears for all episodes and the download do not starts.

Here is one that happens this:  https://www.crunchyroll.com/gifu-dodo-kanetsugu-and-keiji

**Comment by hama3254** [comment]
i checked the URL and it is working, but it seems that outside of the US you either need the US unlock active or be logged into an premium account to be albe to access the videos.

**Comment by theruleof4** [comment]
How to get this US unlock active?

**Comment by hama3254** [comment]
in the settings is a button for this 
![5](https://user-images.githubusercontent.com/52826614/80258968-cceb5000-8684-11ea-842e-49835587207e.png)

**Comment by theruleof4** [comment]
Do I have to login on this page? Because I receive a message: "Unlock Failes" and the windows closed when a pressed Ok

**Comment by hama3254** [comment]
that should work, [try if you can access this website](https://api.criater-stiftung.org/)

**Comment by theruleof4** [comment]
It worked here, but I was still giving the message "Please Make sure that the url is correct", I noticed that it appeared when the url was of a series +18, so I opened that browser, I entered with my login and then, it worked
