### ISSUE TITLE
A notice if there are missing seconds?

### ISSUE THREAD

**Issue by Kyouma95** [hama3254/Crunchyroll-Downloader-v3.0#170]
Sometimes while watching an Episode there is a part with few seconds (3-4) missing in the video file. I think the connection got lost for that moment? But instead of realizing that while watching, is it possible to get a notice when this happens during the download? So i can just re-download it. (I´m downloading from Crunchyroll)

**Comment by hama3254** [comment]
This is an know issue, the video files are split into small segments with 2 to 10 seconds each.
If one of this files is missing then you get the effect you describing.
There is however already two options which can reduce the effect.

1. we have the `Hybrid Mode` which caches the segments before the media library `ffmpeg` combines them. This not only allows the speed to be increased with multi threading of the download but also gives me more control and i can retry a failed segment without the user even noticing.  
 
2. This should be what you wanted with a detection of failed segments
![grafik](https://raw.githubusercontent.com/hama3254/Crunchyroll-Downloader-v3.0/master/readme/settings1.png)

>6 . This is relative new, while the downloader processes the status of the download it can catch error which can result in a view second skip in the video. This is by default turned off with the value "0". From value 1 to 100 is on, the number is at the same time the tolerance of after how much it should trigger the error mode. As example the value of "1" would trigger at the first missing piece and set the download at a paused state which you need to resume/cancle/retry by hand!

**Comment by Kyouma95** [comment]
Did not know there were already 2 helping options, I´ll use them now and close this.

Thank you very much!
