### ISSUE TITLE
Merge soft-subs with video file: Change standard subtitles to the first/prefered language

### ISSUE THREAD

**Issue by thethinker990** [hama3254/Crunchyroll-Downloader-v3.0#171]
I'm always frustrated when I have to select the subtitles for every episode when I watch them. There are 3rd party software in which we can do such things in a batch but it would be nice if implemented.

**Comment by hama3254** [comment]
I already looked into this and it did not work with every video Player, in fact it only worked with Kodi for me.
I can add the tag in the next version but I can not promise that it will work.

**Comment by hama3254** [comment]
added with v3.7.5
