### ISSUE TITLE
Downloader + Firefox Addon

### ISSUE THREAD

**Issue by thethinker990** [hama3254/Crunchyroll-Downloader-v3.0#172]
Get a error with the firefox addon:

```
---------------------------
Crunchyroll Downloader
---------------------------
System.Net.Sockets.SocketException (0x80004005): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig

   bei System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)

   bei System.Net.Sockets.Socket.Bind(EndPoint localEP)

   bei System.Net.Sockets.TcpListener.Start(Int32 backlog)

   bei System.Net.Sockets.TcpListener.Start()

   bei Crunchyroll_Downloader.Main.ServerStart() in **D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb**:Zeile 2926.
---------------------------
OK   
---------------------------
```

I don't know what the program is searching in this path, I got nothing there. Downloader is in "E:\Crunchyroll-Downloader-v3.7.4"

**Comment by hama3254** [comment]
The path if fine, i publish my downloader as `debug` versions, that includes a file which links the executable with the source file. That way I can see the line which causes the issue but it still thinks it's at the same path as my complier creates the files, that is why it shows my project path.

Now to your problem.
It is likely that you already have something running on port 80 so the downloader can not use the port and generates a access violation.

**Comment by thethinker990** [comment]
Could you add a option to change the port? I don't know if I run anything on port 80, at least I don't know anything about it.

```powershell
Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
   6450       0      228      14468     114,70      4   0 System
```

**Comment by hama3254** [comment]
I already tough of an idea to have a list of ports and than use some sort of [handshake](https://en.m.wikipedia.org/wiki/Handshaking) to find the downloader port in the add-on.
I see in the next days if I get it to work how i think.

**Comment by thethinker990** [comment]
Thank you. I appreciate your work. If you need any further help or informations which I can offer then get in touch.

**Comment by hama3254** [comment]
i changed the add-on and the downloader to allow for custom ports.
you can try the add-on and new version : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Debug
the add-on is not uploaded to the Mozilla add-on store yet but you can load it via [about:debugging#/runtime/this-firefox](https://www.youtube.com/watch?v=AzgNzCrXfpo)

**Comment by thethinker990** [comment]
I've downloaded the newest version von your downloader. In Firefox I can not set the port. It just close the addon-popup and ask me again for the port. I cannot "select to download". I deactivated the old addon.

Update: I killed the Microsoft IIS Server and now it works.
1. I installed the addon
2. I set the port in the downloader
3. I set the port in the addon
4. killed IIS server

Maybe for the readme a note, that ms iis server can cause such problems. Maybe it will work now with the standard-port on 80.

**Comment by thethinker990** [comment]
```powershell
Get-Process -Id (Get-NetTCPConnection -LocalPort 8080).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    911      65    73644     104468       0,77  13132   1 Crunchyroll Downloader
```

```powershell
Get-Process -Id (Get-NetTCPConnection -LocalPort 80).OwningProcess
Get-NetTCPConnection : Es wurden keine MSFT_NetTCPConnection-Objekte gefunden, bei denen die LocalPort-Eigenschaft
gleich "80" ist. Überprüfen Sie den Wert der Eigenschaft, und versuchen Sie es erneut.
```

**Comment by hama3254** [comment]
port can be changed in v3.7.5 as desired.
