### ISSUE TITLE
v3.7.4 Fehlermeldung beim Download von AOD

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#175]
Hy, ich bekomme bei der Version 3.7.4 eine Fehlermeldung wenn ich was von AOD runterladen will.
Wenn ich auf OK drücke schließt sich das Programm.
In der Console steht nichts.

![AOD v374 Fehlermeldung](https://user-images.githubusercontent.com/74493510/108073801-bfb2ae00-7068-11eb-8006-cb954bcc482e.png)

Bei der Version 3.7.3.3 klappt der Download

Das Selbe habe ich bei Crunchyroll getestet mit der Version 3.7.4 aber da Funktioniert der Download.

Vielen Dank schon mal.

**Comment by hama3254** [comment]
Crunchyroll und funimation geben die streaming datei mit HTTP Compression aus, AoD kann das scheinbar nicht.
Hier ist eine Zwischenversion unter v3.7.5 : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3
![grafik](https://user-images.githubusercontent.com/52826614/107073482-b95e3f80-67e7-11eb-9b0d-798454c44bd1.png)

**Comment by Schizo1987** [comment]
Vielen Dank mit dieser Version funktioniert es jetzt.

MFG Schizo1987
