### ISSUE TITLE
How are you scraping the segment links from crunchyroll?

### ISSUE THREAD

**Issue by RootEncrypter** [hama3254/Crunchyroll-Downloader-v3.0#176]
>I have the decryption keys for the video but I'm not able to decrypt the video segements. How is downloading segements anf decryption working ?

**Comment by hama3254** [comment]
I use the default m3u8 files with the AES key and the .ts stream files.
CR uses Widevine encrypted streams for the playback but still delivers normal HLS streams and that is what I use.
The decryption itself is done by ffmpeg, either directly during the download or after the hybrid mode cached the .ts files locally.

**Comment by RootEncrypter** [comment]
I went through the network traffic and found the mpd (manifest) file. I downloaded all segements from the manifest. Then tried to decrypt them using the keys. I did not find any m3u8 file. Could you just show in a function format ?

**Comment by RootEncrypter** [comment]
Are you on discord so that I can show you my program ? @hama3254

**Comment by hama3254** [comment]
You can add me on Discord Hama#4155

**Comment by RootEncrypter** [comment]
> You can add me on Discord Hama#4155

Added
