### ISSUE TITLE
Bei Anime on Demand kommt bei Download eine Fehlermeldung.

### ISSUE THREAD

**Issue by Ryo-Saeba** [hama3254/Crunchyroll-Downloader-v3.0#177]
Bei Anime on Demand kommt die Fehlermeldung, dass die Magic-Number im GZip-Header nicht richtig ist und deswegen der GZip-Stream nicht übergeben werden kann. [https://s20.directupload.net/images/210218/7aqjb43v.png](url)

**Comment by hama3254** [comment]
>Crunchyroll und funimation geben die streaming datei mit HTTP Compression aus, AoD kann das scheinbar nicht.
Hier ist eine Zwischenversion unter v3.7.5 : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3
![grafik](https://user-images.githubusercontent.com/52826614/107073482-b95e3f80-67e7-11eb-9b0d-798454c44bd1.png)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/175#issuecomment-780035666_

**Comment by hama3254** [comment]
> Hier ist eine Zwischenversion unter v3.7.5 : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.3

jetzt gibts auch die finale version : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.5
