### ISSUE TITLE
Cancels in the middle of downloading

### ISSUE THREAD

**Issue by HelloBot-Namea** [hama3254/Crunchyroll-Downloader-v3.0#18]
Hello,

With me, episodes are simply not randomly reloaded. So it just stops randomly at 100mb. Is this a bug at the moment or what could be the reason?

**Comment by hama3254** [comment]
please provide more details like:

What episode you have tryed ?

wich settings do you use ? (hardsub, resolution)

do you have enouth storage space?

does the download stop or do you still see that he file get bigger ?

did you tryed it more than once ?

**Comment by HelloBot-Namea** [comment]
> What episode you have tryed 


No anime works for me, I have tried many and with none it has worked

> wich settings do you use ? (hardsub, resolution)

720p, Hardsub

> do you have enouth storage space?

Yes

> does the download stop or do you still see that he file get bigger ?

The download stops, the file does not become larger after time

> did you tryed it more than once ?

I have often tried it with different anime.

**Comment by hama3254** [comment]
[Testrun.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/4532798/Testrun.zip)
Please decompress the zip file and run the "Debug.cmd" and send me the "log.txt" after it has finished.
This cmd will use one episode of the show RWBY with 720p (~450MB file size) and log the result to an file wich i can look at because it seems not  to be a error with the downloader itself.

**Comment by HelloBot-Namea** [comment]
first try: Download aborted after 17.5 mb

second try: Download aborted after 103mb

Log files: https://wetransfer.com/downloads/010a0878be71e11a96dc9d0b081149a520200425121023/37d153

**Comment by hama3254** [comment]
so it's not a bug with the downloader, ffmpeg just get closed somehow.
you're logs end with :

> ^C

wich i  can not even reproduce, if i close the command promt then i get 

> Exiting normally, received signal 15.
> ^C

and if i press CTRL + C in the promt i get

> Exiting normally, received signal 2.

just killing the ffmpeg.exe process just stops the logging as i would expect with an crash.

**Comment by HelloBot-Namea** [comment]
And what can you do now against?

**Comment by hama3254** [comment]
what operating system do you have?

**Comment by HelloBot-Namea** [comment]
Windows Server 2016. It was working two days ago. After that it just didn't work anymore.

**Comment by hama3254** [comment]
try this [ffmpeg version](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20200424-a501947-win64-static.zip) it is a 64-bit version and a newer version (4.2.2 insead of 4.2.1)

**Comment by HelloBot-Namea** [comment]
Mit der neusten Version scheint es wieder zu funktionieren. Danke und könntest du noch die Funktion einbauen die Datein Custom umzubennen. z.B. "{seasonTitle!scene}.{resolution}.WEB.x264-byME/{seasonTitle!scene}.E{episodeNumber}.{resolution}.WEB.x264-byME"

**Comment by HelloBot-Namea** [comment]
With the latest version it seems to work again. Thank you and could you add the function to rename the files custom. e.g. "{seasonTitle!scene}.{resolution}.WEB.x264-byME/{seasonTitle!scene}.E{episodeNumber}.{resolution}.WEB.x264-byME"

**Comment by hama3254** [comment]
> Mit der neusten Version scheint es wieder zu funktionieren. Danke und könntest du noch die Funktion einbauen die Datein Custom umzubennen. z.B. "{seasonTitle!scene}.{resolution}.WEB.x264-byME/{seasonTitle!scene}.E{episodeNumber}.{resolution}.WEB.x264-byME"

nichts leichter als das, [Hier das ist was du willst](https://www.youtube.com/watch?v=SAp0xO-LwFs&t=2s)
