### ISSUE TITLE
"The add-on support Port can only be numbers"?

### ISSUE THREAD

**Issue by balloony123** [hama3254/Crunchyroll-Downloader-v3.0#180]
![error](https://user-images.githubusercontent.com/79473099/108747777-d430f380-750b-11eb-8a5b-c70a675ce6bf.png)
when i try to change any setting and save and exit, this pops up and nothing saves, why does this happen and can i fix it ?

**Comment by hama3254** [comment]
the add-on port is only as number valid or the disabled option
![grafik](https://user-images.githubusercontent.com/52826614/108770196-50eabe80-755a-11eb-83df-2840859bb896.png)

**Comment by hama3254** [comment]
the issue with a empty default value has been fixed with v3.7.6
