### ISSUE TITLE
www.funimation.com uses an invalid security certificate.

### ISSUE THREAD

**Issue by mancinokids** [hama3254/Crunchyroll-Downloader-v3.0#181]
Every time i open up the GeckoFx Firefox browser it gives me an error message, I've tried many different versions and tried turning off security on my Firefox browser. Is there any way i can fix this?
![Gecko FX error message](https://user-images.githubusercontent.com/57275223/108798880-d7a09b00-755c-11eb-9bec-4b73cf502ca5.png)

**Comment by hama3254** [comment]
I don't know what causes this.
Some reports mentioned it just disappeared on its own other just installed certificates and some reports where never answered.
You can read more in the old issues #162, #163, #165 or #169.

**Comment by hama3254** [comment]
see #191 for workaround
