### ISSUE TITLE
Spanish/Latino for Funimation dub?

### ISSUE THREAD

**Issue by nhocnine** [hama3254/Crunchyroll-Downloader-v3.0#192]
When I choose Spanish Dub for Funimation it alway downloads English dub,

**Comment by hama3254** [comment]
please make sure you have access to the language you want.
The downloader can not detect the `Sorry, this video is not available. ` message that i get when i try spanish dub and uses the player id which is for the English dub.

**Comment by NatsuFT36** [comment]
Certainly what happens is that I tried in Azur Lane and in Fruits Basket to download what brings multiple languages and I want to choose the Spanish language and it comes out in English, but when I change region to Mexico it uses Spanish and Brazil uses Portuguese.

**Comment by hama3254** [comment]
> when I change region

With a VPN or is there any other setting on funimation?

The only thing I can add is a check if the set dub language is the detected one, otherwise a error/information could be issued.
