### ISSUE TITLE
SoftSubs work abnormally

### ISSUE THREAD

**Issue by AlexMiniReal** [hama3254/Crunchyroll-Downloader-v3.0#194]
When there is only text, everything is fine, but when, for example, it has to replace part of a video, it bugs.

Crunchyroll Downloader SoftSubs:
![Screenshot (54)](https://user-images.githubusercontent.com/76444133/109493548-f5a25a00-7a8c-11eb-960a-d3db16556a84.png)

Official Crunchyroll:
![Screenshot (56)](https://user-images.githubusercontent.com/76444133/109493877-66497680-7a8d-11eb-9592-e2c677dfb2f0.png)

**Comment by AlexMiniReal** [comment]
![Uploading Screenshot (56).png…]()

**Comment by AlexMiniReal** [comment]
The crunchyroll one is a bit glitched so here is a better image: 
![Screenshot (56)](https://user-images.githubusercontent.com/76444133/109493811-4fa31f80-7a8d-11eb-82c3-9db482e7c95e.png)

**Comment by hama3254** [comment]
it seems to be an issue with merged subs.
![grafik](https://user-images.githubusercontent.com/52826614/109535754-34e89f00-7abd-11eb-8b34-aec7b06b9da9.png)

as far i can see the issue can be resolved by disabling the merge, the other option is for me to implement `mkv` as format which can hold the `ass` subtitles without loosing the format required for that kind of display style.

**Comment by AlexMiniReal** [comment]
Ok thanks for everything you do, will you code the mkv format compatibility when you can?

**Comment by hama3254** [comment]
in the past i tough it was not necessary because mp4 was just fine until this example.
i think i will add it but it has not the highest priority since hard-subs and not merged soft subs are easy workarounds for that particular problem.

**Comment by hama3254** [comment]
[the new version has been released.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.7)
it is marked as pre-release because i can not test every possible ffmpeg command combination right now.
