### ISSUE TITLE
Problem Download Funimation

### ISSUE THREAD

**Issue by nhocnine** [hama3254/Crunchyroll-Downloader-v3.0#195]
#
![capture 1](https://user-images.githubusercontent.com/9522855/109517955-615fe380-7adc-11eb-888c-ac4e1b90848e.PNG)

This notification alway appears when I download form Funimation

**Comment by hama3254** [comment]
i uploaded a possible fix for that, i just have not the time to test it properly right now.

https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.6

**Comment by jeanfelixdev** [comment]
When you insert episodes in the queue, it appears. "Status: no video found"

Tested with the first season of Boku No Hero.

When I add just 1 episode it downloads normally

![erro1](https://user-images.githubusercontent.com/11441861/109545969-51c6a780-7aa8-11eb-84f3-a2cee8650003.png)

**Comment by hama3254** [comment]
if a single episode added normally works for you then i would suggest you try v3.7.5.1
i added a bypass with v3.7.6 for the whole certificate issue (more in #191 ) and it worked but i never tested it fully 
<details>
  <summary>and i can not test anything right now</summary>

![grafik](https://user-images.githubusercontent.com/52826614/109553121-ea721d00-7ad2-11eb-9f7a-df8428435f7f.png)
 
</details>

**Comment by jeanfelixdev** [comment]
> if a single episode added normally works for you then i would suggest you try v3.7.5.1
> i added a bypass with v3.7.6 for the whole certificate issue (more in #191 ) and it worked but i never tested it fully
> 
> and i can not test anything right now

I'm sorry. I expressed myself badly.

What I meant is answering exactly the open issue, that when inserting more than one episode in the queue it does not start.

Prior to this version, I was unable to download the funimation due to the certificate error. With v3.7.6 it reports the error of the beginning of that issue, with v3.7.6.1 it presents the error that I reported.


P.S .: One thing I noticed is that in the queue of multiple episodes the end of the link is:
?qid=undefined
but the link to a single episode is:
?qid=undefined&lang=portuguese (Brazil)

I am downloading in Portuguese (Brazil)

I don't know if that helps anything.

Good luck with your internet! D:

**Comment by hama3254** [comment]
> P.S .: One thing I noticed is that in the queue of multiple episodes the end of the link is:
> ?qid=undefined
> but the link to a single episode is:
> ?qid=undefined&lang=portuguese (Brazil)

The url Parameter are getting edited with your settings right before the url is actually in use.
This ensures that changes on the settings will apply even after the episode is already in the queue.

> What I meant is answering exactly the open issue, that when inserting more than one episode in the queue it does not start

> When I add just 1 episode it downloads normally

Do you add 1 episode in the queue and it works or did you add one episode with the add-on (like the video from #191 ) or did you just add the url into the `add video` from and it did work?

The first should have the same result no matter if you have 1 or 10 episodes in the queue, it just does 1 as t the time anyway.

If you add a single Episode from the add-on (with v0.5) it usues technical the same code with just Minor changes but it should throw the same error as the initial issue if funimation does not return a `gzip` answer.

And if you add the url just to the "Add Video" from then it should use the same functions as the older version and give the certificate error.

**Comment by jeanfelixdev** [comment]
> > The url Parameter are getting edited with your settings right before the url is actually in use.
> > This ensures that changes on the settings will apply even after the episode is already in the queue.

Yes. It's pointed as portuguese (Brazil). But it's only sending to queue with (?qid=undefined&lang=portuguese (Brazil)) when is sent 1 by 1. Batch shipping is just leaving the link  (?qid=undefined)


> > What I meant is answering exactly the open issue, that when inserting more than one episode in the queue it does not start
> 
> > When I add just 1 episode it downloads normally
> 
> Do you add 1 episode in the queue and it works or did you add one episode with the add-on (like the video from #191 ) or did you just add the url into the `add video` from and it did work?
> 
> The first should have the same result no matter if you have 1 or 10 episodes in the queue, it just does 1 as t the time anyway.
> 
> If you add a single Episode from the add-on (with v0.5) it usues technical the same code with just Minor changes but it should throw the same error as the initial issue if funimation does not return a `gzip` answer.
> 
> And if you add the url just to the "Add Video" from then it should use the same functions as the older version and give the certificate error.

The only way I'm dowloading from Funimation is from addon, directly from tool and it's showing certificate error. I'm using addon v0.5 and tool v3.7.6.1

When I got directly on the episode and I click on "add this funimation episode", it works normally, even if I open more than 1 page with a lot of episodes and click on each in "add this funimation episode". The queue recognizes normally the episodes with final's link: (?qid=undefined&lang=portuguese (Brazil))

When I'm in the screen of season and click on "select episodes" > select all > add selected funimation episodes. It send the episodes to the queue but it doesn't do the dowload. Then, I noticed that final of link stays only: (?qid=undefined)

**Comment by hama3254** [comment]
> Yes. It's pointed as portuguese (Brazil). But it's only sending to queue with (?qid=undefined&lang=portuguese (Brazil)) when is sent 1 by 1. Batch shipping is just leaving the link (?qid=undefined)

with the single add button it applys the parameters before it checks if it can download right away, which might fail if either another video is searched or the max amount of downloads is reached.
The queue applys the same parameter again before it gets processed :

https://user-images.githubusercontent.com/52826614/109682252-89078800-7b7e-11eb-9515-4315fb7f81cd.mp4

**Comment by hama3254** [comment]
but the parameter does anyway not make the download fail entirely like you see in #192 

i made some smaller changes to the queue with a new error message if the website can not be reached.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.6

**Comment by jeanfelixdev** [comment]
387 / 5000
Resultados de tradução
Here are some prints with examples.

Print 1 - select all> add selected Funimation Episodes >open the queue > and status: Video not found
![print1](https://user-images.githubusercontent.com/11441861/109685215-cd376000-7b5f-11eb-9f10-1ea5c115b9b8.png)


Print 2 - open the episode page> add this funimation episode. Starts Download
![print2](https://user-images.githubusercontent.com/11441861/109685228-d0325080-7b5f-11eb-855e-23339f35108a.png)


Print 2.1 - add other episodes with the steps of print 2. Then they go to the queue and download normally.
![print2 1](https://user-images.githubusercontent.com/11441861/109685244-d3c5d780-7b5f-11eb-937f-426213029c83.png)


Print 3 - all episodes downloaded successfully, added 1 by 1 to the queue. 
![print3](https://user-images.githubusercontent.com/11441861/109685258-d6c0c800-7b5f-11eb-830c-ddb6fdd49f6c.png)

Did you see the difference in queue links from print 1 to print 2?

Sorry for my poor english.

**Comment by hama3254** [comment]
> Did you see the difference in queue links from print 1 to print 2?

Yes i know, but it does not matter. I change the links anyway right before i open the website.

> with the single add button it applys the parameters before it checks if it can download right away, which might fail if either another video is searched or the max amount of downloads is reached.
><details>
>  <summary>The queue applys the same parameter again before it gets processed :</summary>
>  
>![vlcsnap-2021-03-02-17h46m57s252](https://user-images.githubusercontent.com/52826614/109683257-75a8ec80-7b7f-11eb-8b78-454b16c9d027.png)
>
> 
></details>

Both ways use mostly the same program code with just minimal changes, it should get the same result.
That no video can be found has nothing to do with the parameter of the language, if it is invalid you get anyway some language back. 

<details>
  <summary>it also works perfectly fine for me</summary>
    
![grafik](https://user-images.githubusercontent.com/52826614/109882360-0a901080-7c7a-11eb-961d-220cc4f92fde.png)

</details>

**Comment by RICKYSTER** [comment]
Having this problem when downloading any video from Funimation.
![Screenshot 2021-03-11 105711](https://user-images.githubusercontent.com/63411627/110740318-e4113d00-8258-11eb-8bc9-b502fa2c836c.png)
I am using the CRD add on v0.5 and crunchyroll downloader v3.7.7. Earlier I used the v3.7.6.2, thought would not get this problem. Yet this persists.
I am using a VPN which allows me to access Funimation from India. I am sure it won't cause any problem as it is not a Chrome extension but a software. Anyway, @hama3254 is there any way to not get this problem?
