### ISSUE TITLE
Access Error: Download Canceled

### ISSUE THREAD

**Issue by AlexMiniReal** [hama3254/Crunchyroll-Downloader-v3.0#196]
I'm unable to download animes. Please help. This happens with all animes.

![Screenshot_6](https://user-images.githubusercontent.com/76444133/109627472-f648f800-7b41-11eb-94ba-f79d474ea474.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/76444133/109627474-f6e18e80-7b41-11eb-8576-77a974c86329.jpg)

**Comment by hama3254** [comment]
Interesting, that did work yesterday perfectly.
Try to disable the hybrid mode.
I take a look after work.

**Comment by AlexMiniReal** [comment]
I tried disabling hybrid mode but then this error pops up:

![Screenshot_8](https://user-images.githubusercontent.com/76444133/109628777-6e63ed80-7b43-11eb-8eb0-f18e0e7076c6.jpg)

**Comment by AlexMiniReal** [comment]
Hybrid Mode doesn't generate a log, so here is the no-hybrid log to help you:
[nohybrid.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6067697/nohybrid.log)

**Comment by hama3254** [comment]
I see the issue, it is a DNS problem.
It is nothing I can fix and should resolve itself anyway.

`02/03/2021 10:47:47[tcp @ 07afac40] Failed to resolve hostname ll.v.vrv.co: Temporary failure in name resolution`

**Comment by AlexMiniReal** [comment]
Ok, thanks!
