### ISSUE TITLE
The certificate error still remains in the v3.7.6.2

### ISSUE THREAD

**Issue by Marcos875433** [hama3254/Crunchyroll-Downloader-v3.0#198]
I tried with different versions of the app, and with the add-on as well, I tried v3.0, it didnt work, I tried v3.7.6.2 and didnt work, then tried that same version but with the add-on v0.5 and didnt work, tried with firefox (I was trying to do it with chrome) with Funimation add-on only with the v3.7.5.1 and didnt work.

And if this helps, the last thing I tried was to use a vpn in chrome, since for some reason in my country (Mexico) the chapters dont play unless you have the subscription, and it seemed to work, or at least it appeared that it was being added to the queue, But nothing happened, not even the certificate prompt appeared, and yes, I tried adding several chapters, it didn't work, I tried adding one by one, it didn't work either, obviously I also tried it from the app, it didn't work either, it is worth mentioning that after that attempt now if the prompts appear even if it tried to download the vpn for chrome

**Comment by hama3254** [comment]
The only versions the browser bypass is added is from v3.7.6 onwords.
That versions combined with add-on v0.5 (Chrome or Firefox does not matter) should work.
There are some issues like #195 that i don't understand right now but at least the single Episode adding was working for most of the people.

Keep in mind older version of the add-on don't work with newer version of the download and the same the other way around.

**Comment by Marcos875433** [comment]
> That versions combined with add-on v0.5 (Chrome or Firefox does not matter) should work.

Yeah, I know it should work, but it doesnt, at least for me, this is what I mean:
https://user-images.githubusercontent.com/58754180/109861645-261cfc00-7c25-11eb-84a8-f33730e2dbce.mp4

And this is what I said happened with the VPN:
https://user-images.githubusercontent.com/58754180/109869177-2968b580-7c2e-11eb-8df7-5c8e990e8eb6.mp4

**Comment by hama3254** [comment]
> And it stays like that, doesnt download anything, the only thing I could notice that it does is create the series folder, but it doesn't download the chapter

The folder gets created before the download starts.

>And this is what I said happened with the VPN:

The VPN is only active in the webbrowser, the downloader needs to access the funimation website on it's own because of [access problems inside the website.
](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

The error you get the fist time is the same as you get displayed by funimation, you need a subscription to watch it. or a system wide VPN would also do the trick in that case.

**Comment by Marcos875433** [comment]
> The VPN is only active in the webbrowser, the downloader needs to access the funimation website on it's own because of [access problems inside the website. ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

I was suspecting it was from my region, so I did exactly that, I downloaded a vpn for the whole pc, more or less it worked, the downloader found the video, found the resolution, but didnt found the subtitles, and I tried the softsubs and hardsubs , and tried spanish (LA) and english subtitles just in case, but didnt work, so it downloads the episode but not the subtitles

**Comment by hama3254** [comment]
>  and I tried the softsubs and hardsubs

that does not really matter on funimation since hardubs are just softsubs that get bunred into the video while downloading.
That's why you should get that warning if re-encoding is disabled in the output settings.
![grafik](https://user-images.githubusercontent.com/52826614/109948445-a18cb500-7cda-11eb-9d87-ccfc9c4bd7fd.png)

and the other issues you mentioned may result from that VPN so i can not fix something that is heavenly dependent on your setup.

**Comment by Marcos875433** [comment]
The only problem I have now is that I cannot download them in Japanese dub, and I cant download the subtitles in Spanish, only in English, I know that the way the downloader works is by scanning the network traffic to find the m3u8 file and downloading it with ffmpeg, or at least I think so, and I also only think I've seen that there are Spanish subtitles and Japanese dub in my country since when I have the vpn activated for USA when I change the dub to Japanese in the funimation player it says something like it is not available in your country, but as I told you in my country you cant play a video unless you are subscribed, but I have noticed in the downloader I don't even need to play the video, thanks to the scan function of the network traffic, so I was wondering if there is any way to use the scan function to find the m3u8 in Japanese and the subtitles in Spanish without having to subscribe? Or if you can at least tell me how you did for the downloader to scan network traffic?, because at least I didn't see any way to do it using ffmpeg, so, is it a script that you made?

**Comment by hama3254** [comment]
> chose series that just don't have Spanish subtitles, although it's weird, because in animes that don't have Spanish subtitles it says, "this video is exclusive for subscribers", but imagine that someone subscribes and sees that there are only English subtitles LOL

funimation is weird in many places, you also don't have any rules what is free and what not.

>  well I have to say that the downloader still didn't work for funimation

i still can not be sure that the downloader is the issue and not any other stuff like the VPN.


>  I would like to know if there is a way to download them without subscribing

even if that is possible i don't add something like that, that just makes me a target for either a DMCA or worse...

**Comment by Marcos875433** [comment]
> even if that is possible i don't add something like that, that just makes me a target for either a DMCA or worse...

Yeah, anyways now that I think about it, most of the anime you need to suscribe is just for new chapters and animes, so I dont care so much, but what I wanna know are 2 things, the first is how did you make the program find the m3u8 file? Because I know that the more or less average way to find it is by playing the video and having the devtools open in the network tab, but I still couldn't find it, and in other sites that too they use m3u8 if I found it, I only found m3u8 files in the elements tab of the devtools but I could not discover the way it was ordered since there were several that were m3u8 and I didnt manage to see that they were for different resolutions, and I couldnt figured out how to do it with ffmpeg, so I would like to know how you did it

And another thing, how the program merges the soft subs?, because if I merge manually with a program called mkvtoolnix, the thumbnail of the video disappears, also, in the version merged by the crunchyroll downloader it doesnt show the same subtitles as in crunchyroll, and somthe so I would like to know how I could merge the subtitles with the video without losing the original subtitles and preserving the thumbnail, and something curious is that in the microsoft player the subtitles dont appear in the video downloaded by the crunchyroll downlader, and in the vlc player they do appear, and if I look at the vlc codec there the subtitle track appears, but in the program that I use to merge the videos and subtitles, if I look in the codec the subtitle track does not appear

**Comment by hama3254** [comment]
I look at the website and try to reverse engineer where it gets the m3u8 url from, for funimation the m3u8 is not in the website, it gets loaded by an API.

**Comment by Marcos875433** [comment]
> I look at the website and try to reverse engineer where it gets the m3u8 url from

yeah, I meant for crunchyroll, beacause for funimation is gets loaded in the network tab, so it's not that complicated, but in crunchyroll I have no idea and thats what I wanted to know, but if its very difficult to explain it better let's leave it like that xd

**Comment by hama3254** [comment]
Crunchyroll is even simpler than funimation.
They use something else than m3u8 files and DRM so the network search is unlikely to work, but the have a list of urls for every hardsub language including raw inside the page directly.
Just look for the format `adaptive_hls` and select the language of choice.
Now you just need to remove every backslash `\` from the url and you get the master file with all resolution.
![Screenshot_20210312-065354](https://user-images.githubusercontent.com/52826614/110898556-bc28e480-82ff-11eb-86e0-f375efd68f99.jpg)

**Comment by Marcos875433** [comment]
OMG it worked!!, I had already assumed that if it was not in the network tab, it had to be in the source code of the page, and that is precisely the part that I found, because I just pressed Ctrl + F and search for m3u8, and that is the part in the I told you that I didnt understand the way it was ordered, because apart from the adaptive_slash, there are also the adaptive_dash, so there were too many m3u8 and I didnt understand it, thank you so much really !!!, and I'll tell you something,  I love your program and your work, I really appreciate it, and by the way, regarding funimation downloads, I'll try it again later, because at least where I live is 1am, because I think it didn't work because it bugged  on that occasion, but I'm not sure, and, in case it doesn't work, could you tell me how to make a log so that you know why it happens? I know there is an option in the application, but I don't really know how it works, not even I know if with that you could deduce something, but if it is helpful for you I would like to do it, and if it is not just tell me and we end this topic xd

**Comment by hama3254** [comment]
> so there were too many m3u8

They just have streams for every hardsub language for the anime and one without subs and that times 4 in m3u8 and additional 2 times in dash.
That's just 42 m3u8 files for example one RWBY episode (and 70 streams total)🤐
