### ISSUE TITLE
Hybrid Download ends up in Access Error

### ISSUE THREAD

**Issue by inter5tella** [hama3254/Crunchyroll-Downloader-v3.0#199]
Every time I want to use Hybrid Download on CR, it gives an 'Access error - download canceled' error message.
Switching back to 'Normal' mode makes the app works fine but just downloading on default speed.

![grafik](https://user-images.githubusercontent.com/12923644/110226421-5eeff600-7eef-11eb-91af-aec147236e32.png)

**Comment by hama3254** [comment]
i can not see an issue with the hybrid download.
This might just be an random issue like #196 but that would not explain why the default ffmpeg download is working.
For the next version i added a debug message to the console. 
![grafik](https://user-images.githubusercontent.com/52826614/110235998-b6b05080-7f33-11eb-83bb-34fb41f264e2.png)
