### ISSUE TITLE
Option um den US Cookie automatisch zu laden.

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#2]
Ist es möglich für dich eine Einstellung einzubauen das der US Cookie automatisch geladen wird beim starten von dem Downloader ?

**Comment by hama3254** [comment]
Der Cookie verliert seine Gültigkeit wenn der Downloader komplett geschlossen wird,  daher muss eh das selbste gemacht werden wie wenn man den Button drückt und die 3 Klicks sind jetzt nicht so aufwendig das man das weiter automatisieren müsste.
zudem weiß so der User besser was er macht.
