### ISSUE TITLE
Crop black bars

### ISSUE THREAD

**Issue by Androkai** [hama3254/Crunchyroll-Downloader-v3.0#20]
Crunchyroll is encoding all videos in 16:9 ratio but some animes (e.p. The Fruit of Grisaia) have 21:9 (maybe also 4:3 for some old ones) ratio resulting in black bars. ffmpeg has a filter [cropdetect](http://ffmpeg.org/ffmpeg-filters.html#cropdetect) to detect these. Maybe you can find a good way to integrate some automatic cropping.

Great job by the way, the h265 GPU encoding support is pretty neat!

**Comment by hama3254** [comment]
I look at it later but I'm ever time surprised what ffmpeg is capable of.
The only problem is that the commands get really difficult with all the possibilities. right now there is even a bug in the downloader with resolution [Auto] and the sub merge feature because it uses "0:v" it just gets all available resolutions 😅.
So I can not promise anything because I don't know for myself if I can add it without getting unforeseen consequences.

**Comment by hama3254** [comment]
we already have two problems. hardsubs are in the black parts so they most likley get cropped 
![9](https://user-images.githubusercontent.com/52826614/80597684-78e7bf00-8a28-11ea-96e9-d344e05bb30d.png)
and the cropdetect works but i haped it crop automaticly but i need to process the output and run a second command for the download, cropping and re-encoding :/

**Comment by Androkai** [comment]
Hm, yeah, the sub is already a heavy weighting argument because now that you talk about it I would expect that also softsub has a position information (remembering background talk which is often placed in top center while the actual talk is in the bottom center or some translated signs somewhere etc.) so should not work without some manual replacing. In this case it's probably better to do it manually and not to blow up your downloader.

But great thx for your research on this topic.

**Comment by hama3254** [comment]
![10](https://user-images.githubusercontent.com/52826614/80631499-17d6e000-8a56-11ea-859a-36c2cca47100.PNG)
VLC seems not to have a problem with the crop and the subs 
a small sklaing problem but that seems ok i guess
![11](https://user-images.githubusercontent.com/52826614/80631902-c11dd600-8a56-11ea-86bc-f9bf27c3d2c0.PNG)

**Comment by Androkai** [comment]
Not bad, much better than expected! 👍

**Comment by hama3254** [comment]
> Not bad, much better than expected! 👍

but this is not really good, it dos not get that the opening logo of 'rooster teeth' is black :/ 
the first valid detection is at "t:0.333667" so i would say you crop id manual and we call this a failure.

![12](https://user-images.githubusercontent.com/52826614/80639094-cd5b6080-8a61-11ea-82f7-1945db329d13.png)

**Comment by Androkai** [comment]
Will do, thx for the interesting feedback.
