### ISSUE TITLE
Can you add support for Arabic Subtitle ?

### ISSUE THREAD

**Issue by EngMohamedOsama** [hama3254/Crunchyroll-Downloader-v3.0#21]
Thanks for your amazing work.
Can you add support for Arabic Subtitle ?

**Comment by hama3254** [comment]
They are already in the downloader.
You can even choose between hardsub and softsubs.
![Screenshot_20200506-055614](https://user-images.githubusercontent.com/52826614/81137249-71f80980-8f5e-11ea-99d0-b04733134d67.jpg)
![Screenshot_20200506-055652](https://user-images.githubusercontent.com/52826614/81137251-7290a000-8f5e-11ea-9490-9dbec0c5cabc.jpg)
