### ISSUE TITLE
wetv.vip

### ISSUE THREAD

**Issue by ncplus0** [hama3254/Crunchyroll-Downloader-v3.0#210]
hi mt8

do you think we can creat an option to download as well from the wetv.vip, its a series site that i love it.
i cant find program that downloads from there, do you think you can adapt to make it compatible or you kwon any program like yours that do the same job.

tks in advance

**Comment by hama3254** [comment]
i have improved the [network scan](https://www.youtube.com/watch?v=fqWotJY7p94) to work with your specific site.
![grafik](https://user-images.githubusercontent.com/52826614/111868121-6a740000-8978-11eb-9b76-628c2bc53da8.png)

**Comment by ncplus0** [comment]
hiu mt8, tks for your work.
but i cant make it to work,
when i just do the add url it only says looking for a non cr video file, and does not add up. 
and if i use the browser and do the network scan, it recognise the stream but not the subtitle
also it does an error after the 3º download of the stream.
im using this series as an example:
https://wetv.vip/en/play/scoslq3wkjbwo0m?vid=m0032le6gzz

![Untitled](https://user-images.githubusercontent.com/72767232/111883104-176a6f00-89b1-11eb-8b49-fb935d6e9667.jpg)
![Untitled2](https://user-images.githubusercontent.com/72767232/111883167-9364b700-89b1-11eb-9390-576625c21878.jpg)

**Comment by ncplus0** [comment]
i was able to download the full series now but with a lot of trys, as for the subtiles i cant do it any of them.

also can you do the same thing with the tv.line.me, but this one you muts have the international liks becouse they block 
i give a few of them to try

https://tv.line.me/embed/12033208
https://tv.line.me/embed/12122117
https://tv.line.me/embed/12244370
https://tv.line.me/embed/12362738

this 4 are random episodes to test, the full ones are here
http://world-of-bl.com/index.php/Thai/WhyRU

see if you can make the conection like you did on the network scan, and if possible the subtitles as well
tks in advance

**Comment by hama3254** [comment]
> when i just do the add url it only says looking for a non cr video file, and does not add up.

that might have something to do that the website never finishes loading (at least for me) and stays in the `document.readyState`  [`interactive`](https://www.w3schools.com/jsref/prop_doc_readystate.asp)

> and if i use the browser and do the network scan, it recognise the stream but not the subtitle

in my tests the subtitles worked with vlc after selecting subtitles not video streams

> also it does an error after the 3º download of the stream.

i guess you mean the OutOfMemory error from the last screenshot.
that is a random issue, i would in any case suggest a 1 by 1 download with the network scan.

and as i'm seeing the screenshot below, the subfolder setting automatic has no effect on other sites as Crunchyroll, Funimation and Anime on Demand.

> ![Untitled](https://user-images.githubusercontent.com/72767232/111883104-176a6f00-89b1-11eb-8b49-fb935d6e9667.jpg)

**Comment by hama3254** [comment]
> also can you do the same thing with the tv.line.me, but this one you must have the international links because they block

well use an interesting method for loading the stream, as far i can see they don't load a `m3u8` file they create it in the browser while you watch. 
this makes it impossible to find so i'm unable to add it into the network scan.
it would require a full implementation like i did with `Anime on Demand` and that takes more time and effort as i'm willing to put into a site that i don't use.

but you can find all information you need to download from the website in the following request :  

![grafik](https://user-images.githubusercontent.com/52826614/111885768-26115000-89ca-11eb-93b8-53005ffeeb16.png)

just copy it in a good text program [(like notepad++)](https://notepad-plus-plus.org/downloads/) then replace `https://` with `\n` and you get all urls listed at the front (subs and mp4 files)
![grafik](https://user-images.githubusercontent.com/52826614/111885999-6b824d00-89cb-11eb-9667-69b6de46b4c6.png)

**Comment by ncplus0** [comment]
how did you get all that text, im unable to reproduce till this moment

**Comment by ncplus0** [comment]
i've found the m3u8 you talked. 
is it this one, i used the F12 key on browser

![Untitled3](https://user-images.githubusercontent.com/72767232/111886876-16ddd280-89c9-11eb-9bf1-168fe796c239.jpg)


as the data you had past on notepad i have no idea how you got it

**Comment by hama3254** [comment]
If you open the F12 menu before loading the video page then you can use the `network` tab to see what has been loaded.
look for an entry like the `false?key` in my screenshot then click on it.
you should get a window like the bottom one from my screenshot on the right side and look if there is a `response` tab
that should contain the data you are looking for

**Comment by ncplus0** [comment]
found it tks, but how did you past it into notepad++ and making several lines, mine only make 1
sorry the stupid question

still there is no need for that i found a faster workaround thanks to you
if we copy the text in the response with already open jdownloader2 program it automatically detects  the subtitle and video
in the end we just need to change the vtt extension to srt

really thanks for your brilliant help

**Comment by hama3254** [comment]
> found it tks, but how did you past it into notepad++ and making several lines, mine only make 1
> sorry the stupid question

i replaced the `https://` with a line break as i said 

> just copy it in a good text program [(like notepad++)](https://notepad-plus-plus.org/downloads/) then replace `https://` with `\n` (the placeholder for a new line) and you get all urls listed at the front (subs and mp4 files)


> if we copy the text in the response with already open jdownloader2 program it automatically detects the subtitle and video
> in the end we just need to change the vtt extension to srt

nice to hear that you found an simpler way.

**Comment by ncplus0** [comment]
hi mt8 tnks again for all the help, btw since you are a brain in this do can you help me in finding it on the QIY site, link: https://www.iq.com/play/ej42wo41j0 
of course the same name does not apear but also i cant find any that looks close to what the tv.line.me used

if you have time can you take a look plz
tks in advance mt8

**Comment by hama3254** [comment]
> help me in finding it on the QIY site, link:

![grafik](https://user-images.githubusercontent.com/52826614/111914673-36c9d080-8a73-11eb-88ea-4d60bc453081.png)

**Comment by ncplus0** [comment]
hi mt8
ive found it but it only works for srt, but no matter i notice that the 1080p quality is only avaliable for vip so even with this i cant download the quality a want
