### ISSUE TITLE
ASS Files? [Not an issue]

### ISSUE THREAD

**Issue by aserralta** [hama3254/Crunchyroll-Downloader-v3.0#213]
What are those ASS Files for? Are they needed?

![image](https://user-images.githubusercontent.com/44881213/111514028-5a151880-871f-11eb-8c91-19077a4dd366.png)

**Comment by hama3254** [comment]
This files are the soft subtitles which are is just all the text from the Video with the timestamps. 
You can either merge the soft subs with the video file or use the hardsub option.

**Comment by aserralta** [comment]
Thanks @hama3254 , I'll leave like that, I just want it to know what it was. I will close the issue, again thanks!
