### ISSUE TITLE
Add downloads of multiple Funimation subtitles in single mode without video to modify the BD

### ISSUE THREAD

**Issue by NatsuFT36** [hama3254/Crunchyroll-Downloader-v3.0#216]
Eng: As it is known that downloads are added for only subtitles from Crunchyroll but I wanted them to make the proposal to have that same one but for Funimation and select both the English, Spanish (LA) and Portuguese (Brazil) subs through Single Download SoftSubs and that also do it to select a series to download the complete chapters and select the formats of dfxp, vtt and srt.

Esp: Como se sabe que se agrega decargas para solo subtítulos desde Crunchyroll pero quería que hicieran la propuesta de haber ese mismo pero para Funimation y seleccionar tanto los subs de Ingles, Español (LA) y Portugués (Brasil) a través de SoftSubs de Single Download y que también lo hagan para seleccionar una serie para descargar los capítulos completos y seleccionar los formatos de dfxp, vtt y srt.

https://raw.githubusercontent.com/hama3254/Crunchyroll-Downloader-v3.0/master/readme/settings3.png

**Comment by hama3254** [comment]
i already planed to move the subtitle only function into the normal download function.
It will be as an option inside the add video window.
I am thinking of this to apply on the direct download, the queue and for CR the multi download.
I'm not sure yet if i save the selection and apply it to downloads directly started from the add-on.

![grafik](https://user-images.githubusercontent.com/52826614/111773268-40560b80-88ae-11eb-8895-f765f350ae42.png)

**Comment by NatsuFT36** [comment]
That is, since for Crunchyroll subs if I can download and do without video since I have that for BD and for Funimation since it started with multiple subs and there are parts that the video has censored and that I wanted to download only the sub either English, Spanish and Portuguese.

**Comment by hama3254** [comment]
i added the option which simply skips the video in the download process.

https://user-images.githubusercontent.com/52826614/111868252-2c2b1080-8979-11eb-97c9-840c3bc6a5fd.mp4

**Comment by NatsuFT36** [comment]
It is good and I tried it in Log Horizon T3 although at first it could not be downloaded because I had selected the Spanish dub as the default and only changed the language in Japanese and it could be downloaded.
