### ISSUE TITLE
Frozen scenes

### ISSUE THREAD

**Issue by DiegoKuOffi** [hama3254/Crunchyroll-Downloader-v3.0#22]
Hi. It seems like lately, every time I download the cap, and by going through it completely, some scenes are shown to freeze for a time of 5 or 6 seconds. I don't know if there can be any solution for it.

Posdata: I'm sorry for my English.

**Comment by hama3254** [comment]
this is most likely a network problem.
The video files on CR are segmented if one is missing for whatever reason you get what you descripe.
The only thing you can do is make sure you do less downloads than your badwith can handle and make sure that every domain from Cr is accessable (with other DNS like cloudflare or google)

**Comment by DiegoKuOffi** [comment]
Oh, I see ... thanks for the info. By the way, will there be an update to the program?
