### ISSUE TITLE
Settings Problem

### ISSUE THREAD

**Issue by sept-mg** [hama3254/Crunchyroll-Downloader-v3.0#221]
The setting does not save. (I try all version and i have this problem)
Version :  all 

https://user-images.githubusercontent.com/67376828/111912738-40e7d100-8a6b-11eb-8113-aea7a280ebe8.mp4

**Comment by dopuke** [comment]
same here

**Comment by hama3254** [comment]
It's not a bug, it's a feature.
With Software re-encoding (`libx`) the limit is 1 and with `nvenc` the limit is 2.

**Comment by NatsuFT36** [comment]
But what version does it have since it is an old version without the format function of funimation

**Comment by dopuke** [comment]
> It's not a bug, it's a feature.
> With Software re-encoding (`libx`) the limit is 1 and with `nvenc` the limit is 2.

so i can't use simultanous downloads?

**Comment by hama3254** [comment]
> so i can't use simultanous downloads?

Yes, with re-encoding you have this limits :

> With Software re-encoding (libx) the limit is 1 and with nvenc the limit is 2.

the re-encoding takes anyway the most of the CPU power for a single task so more than one has close to no benefit.

and for the `nvenc` versions the limit of 2 is in the nvidia driver and if it i try to do more the process just failes.
