### ISSUE TITLE
new version v3.7.8.1 error finish download

### ISSUE THREAD

**Issue by rcyclope** [hama3254/Crunchyroll-Downloader-v3.0#226]
hi, i've alittle pb with the new version
when my download finish i haven't ass file and the video file 0Ko (the sub-folder 1.3Go with ts file)

![crdownload 3 7 8 1](https://user-images.githubusercontent.com/17126922/112309142-4a5b7e00-8ca3-11eb-97b4-9651f82dc37b.png)

**Comment by hama3254** [comment]
That looks like an issue with the ffmpeg command after the hybrid mode finished caching.
Please add a log file from a failed download.
You can either save the log file by right clicking the failed and select save log file or just select the copy log to clipboard.

**Comment by rcyclope** [comment]
i have the log, there is a problem with the audio codec "vorbis"

[JUJUTSU KAISEN Épisode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6197983/JUJUTSU.KAISEN.Episode.1.log)

**Comment by hama3254** [comment]
i guess i found the issue.
the same ffmpeg command converts the audio from `aac `to `vorbis` for `mkv` but not for `mp4`
<details>
  <summary>Log mp4</summary>
  
24.03.2021 16:42:21 -i "[url]" -metadata:s:a:0 language=eng  -c:v libx265 -preset fast -b:v 2000k -bsf:a aac_adtstoasc "E:\Test\RWBY Staffel 2 Folge 4.5 Die Welt von Remnant 1 Dust.mp4"

24.03.2021 16:42:23   Duration: 00:02:16.67, start: 0.101000, bitrate: 0 kb/s
24.03.2021 16:42:23   Program 0 
24.03.2021 16:42:23     Metadata:
24.03.2021 16:42:23       variant_bitrate : 0
24.03.2021 16:42:23     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
24.03.2021 16:42:23     Metadata:
24.03.2021 16:42:23       variant_bitrate : 0
24.03.2021 16:42:23     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
24.03.2021 16:42:23     Metadata:
24.03.2021 16:42:23       variant_bitrate : 0
24.03.2021 16:42:23     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
24.03.2021 16:42:23     Metadata:
24.03.2021 16:42:23       variant_bitrate : 0
24.03.2021 16:42:23 Stream mapping:
24.03.2021 16:42:23   Stream #0:0 -> #0:0 (h264 (native) -> hevc (libx265))
24.03.2021 16:42:23   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
  
</details>
<details>
  <summary>Log mkv</summary>

24.03.2021 16:38:11 -i "[url]" -metadata:s:a:0 language=eng  -c:v libx264 -preset fast -b:v 2000k -bsf:a aac_adtstoasc "E:\Test\RWBY Staffel 2 Folge 4.5 Die Welt von Remnant 1 Dust.mkv"

24.03.2021 16:38:13   Duration: 00:02:16.67, start: 0.101000, bitrate: 0 kb/s
24.03.2021 16:38:13   Program 0 
24.03.2021 16:38:13     Metadata:
24.03.2021 16:38:13       variant_bitrate : 0
24.03.2021 16:38:13     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
24.03.2021 16:38:13     Metadata:
24.03.2021 16:38:13       variant_bitrate : 0
24.03.2021 16:38:13     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
24.03.2021 16:38:13     Metadata:
24.03.2021 16:38:13       variant_bitrate : 0
24.03.2021 16:38:13     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
24.03.2021 16:38:13     Metadata:
24.03.2021 16:38:13       variant_bitrate : 0
24.03.2021 16:38:13 Stream mapping:
24.03.2021 16:38:13   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
24.03.2021 16:38:13   Stream #0:1 -> #0:1 (aac (native) -> vorbis (libvorbis))
24.03.2021 16:38:13 Press [q] to stop, [?] for help
24.03.2021 16:38:13 [aac_adtstoasc @ 07adeec0] Codec 'vorbis' (86021) is not supported by the bitstream filter 'aac_adtstoasc'. Supported codecs are: aac (86018) 
24.03.2021 16:38:13 Error initializing bitstream filter: aac_adtstoasc
24.03.2021 16:38:13 Error initializing output stream 0:1 -- 
24.03.2021 16:38:13 Conversion failed!



</details>

**Comment by hama3254** [comment]
adding a ` -c:a copy` is enough to stop this error from happening 
<details>
  <summary>Log fixed</summary>
  
24.03.2021 17:08:05 -i "[url]" -metadata:s:a:0 language=eng  -c:v hevc_nvenc -preset fast -b:v 7000k -c:a copy -bsf:a aac_adtstoasc "E:\Test\RWBY Staffel 2 Folge 4.5 Die Welt von Remnant 1 Dust.mkv"


24.03.2021 17:08:06 Stream mapping:
24.03.2021 17:08:06   Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
24.03.2021 17:08:06   Stream #0:1 -> #0:1 (copy)
24.03.2021 17:08:06 Press [q] to stop, [?] for help
24.03.2021 17:08:06 Output #0, matroska, to 'E:\Test\RWBY Staffel 2 Folge 4.5 Die Welt von Remnant 1 Dust.mkv':
 
</details>

**Comment by rcyclope** [comment]
nice dude you're great 👍

**Comment by rcyclope** [comment]
Fixed
