### ISSUE TITLE
Download im Hybrid Modus hängt sich auf

### ISSUE THREAD

**Issue by yannikbungert** [hama3254/Crunchyroll-Downloader-v3.0#228]
Sobald ich im Hybridmodus eine Ganze Staffel von CR Downloade hängt es sich bei etwa der Hälfte auf und macht nichts mehr

<details>
  <summary>Screenshots</summary>
  
![Screenshot_75](https://user-images.githubusercontent.com/34244940/112371173-9a0b6b00-8cde-11eb-8aa4-fa6a58e4bebb.png)
![Screenshot_76](https://user-images.githubusercontent.com/34244940/112371175-9aa40180-8cde-11eb-9984-5df650c8e8a3.png)
![Screenshot_77](https://user-images.githubusercontent.com/34244940/112371177-9aa40180-8cde-11eb-8dd0-f31c20b1cc69.png)

  
</details>

**Comment by hama3254** [comment]
Was genau hängt? Der einzelne download oder das ganze Programm?

**Comment by yannikbungert** [comment]
Das Ganze Programm also ich muss es über den Task-Manager beenden

**Comment by hama3254** [comment]
Bei nur einem download gleichzeitig ohne CPU re-encoding sollte selbst im hybrid mode nicht allzuviel Leistung nötig sein.
Zumal der hybrid mode sich an der Anzahl an CPU Threads orientiert im Bezug auf Parallelisierung.
(Je 2 CPU Threads wird ein download Thread genutzt, das untere Limit ist jedoch 2 download Threads).
.
Passiert das immer nach ungefähr nach der selben folgenden Zahl (±2)?

**Comment by yannikbungert** [comment]
Jetzt als ich 2 Folgen gleichzeitig eingestellt habe hat es ohne probleme funktioniert

**Comment by hama3254** [comment]
Ich mach hier mal zu, bei weiteren Problemen einfach wieder aufmachen oder ein neues.
