### ISSUE TITLE
Not able to download from Funimation

### ISSUE THREAD

**Issue by dnr18lol** [hama3254/Crunchyroll-Downloader-v3.0#229]
When trying to download a show or chapter from Funimation:

I've tried both the app (browser mode) and the addon but it just doesn't download anything. I can add the playlist to the queue but when I click to start the download, it never starts. instead it just displays "loading..." but never starts. I'm using a VPN but so far I've never had problems. Could be that the problem?

V: 3.7.8.2

**Comment by hama3254** [comment]
The internet connection can always be an issue, no matter if you use a VPN or not.
If you try the browser you can open it before you start the download that way you can see what's he doing.
The browser is bypassed after you used the add-on (the cookies get stored until the downloader is restarted).

**Comment by dnr18lol** [comment]
Sorry to bother you again. This is still happening to me. It only happens in bulk mode for Funimation. Is this happening to you too? I must say I have a free account in FM although I will start a Premium subscription next month but in the meanwhile. Could this be the case? In the free tier ads and previews are shown but I'm not sure if that's the problem.

I must say I've been this afternoon testing several setting and uninstalling but none seems to work. FYI, the browser is open and loads the FM page and it even plays and buffers the stream but the app is stuck in "loading".

**Comment by hama3254** [comment]
> Is there any way to fully reset the app setting?

all settings are stored in the windows registry `HKEY_CURRENT_USER\Software\CRDownloader`

**Comment by hama3254** [comment]
i also found two issues, the fist one looks like this :
![grafik](https://user-images.githubusercontent.com/52826614/112701507-2067ae80-8e91-11eb-9dd7-a2f3cc8b2c5e.png)

and the second one is the cause of your loading problem which i can fix.

**Comment by hama3254** [comment]
v3.7.8.3 should now work again with the browser in queue mode.

>  Is this happening to you too?

i never use funimation personally, i watch only German sub or German Dub.

**Comment by NatsuFT36** [comment]
The one from Germany I think uses Wakanim together with France and Russia right

**Comment by dnr18lol** [comment]
Hi again!

I've been doing some testing and it seems the problem is solved now! Thank you very much @hama3254!!
