### ISSUE TITLE
Download scheint zu "crashen"

### ISSUE THREAD

**Issue by xILikepuddingx** [hama3254/Crunchyroll-Downloader-v3.0#232]
Moin moin,

habe es nun öfters gehabt und wollte nun mal nachfragen.
Und zwar geht es darum, dass ich in letzter Zeit vermehrt das Problem bekomme, dass der Download direkt nach dem Start "crashed".
In diesem Falle geht es zum Beispiel um Staffel 2 Folge 12 von My Teen Romantic Comedy SNAFU, welche auf verschiedene Systeme das Problem aufweist.
Ich sollte auch noch erwähnen, dass es nur bestimmte Folgen sind, die sich nicht runterladen lassen. 
Von dieser Serie ging z.B. nur diese eine Folge nicht.

Womöglich habe ich vielleicht eine falsche Einstellung und wollte Fragen ob und wie ich das beheben kann.

Alles weitere findest/findet du/ihr unten

LG

Enter your version below, it can be found in the "About" section of the settings.
Version : v3.7.8.3

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>
<summary>
Log File
</summary>

27.03.2021 05:47:22 -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/index-v1-a1.m3u8?Expires=1616993242&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9mMTMyYWNhOWQzOWQxMmNhMmUxMmU3ZmM1YWM5M2VmMS9hc3NldHMvbnpmZHNjNWtlcG5ycXVuXyoubTN1OD8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjE2OTkzMjQyfX19XX0_&Signature=Mq3Bk8~Fwhyly-f2ZCyyX1M7Y~jMvgvQx2Yhqgg-D0KcCfobFZRhp9cxa8vjzOKTTgbqIc~FLb4YGIYFhixzAjuqbaqg0pzWsoZzf21zfRdJpszkEltRe0h0RfwBmxRXF~YSZX2bd7Db25JjbYydROOSMNgJ7u8GT9ELcjTmzfQKeQxETaayqX5cTuFvg~WU~baQ20qnpBJrKwgBvkxIKkKGai7M8~ZLj7CGB5n2HvuSMza3OxIJwrwUkxdV87p-sG5sh2buP21RbO4ZUeVCSxCqLn6yVn~Hn62cT2vlPaUmARLqvgV33zssaO2NCXfdwsvghAjNlV4yVOJWWqcuQQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=akamai-prod" -map 0:v -map 0:a  -c copy -bsf:a aac_adtstoasc -c:s mov_text -metadata:s:a:0 language=jpn "C:\Users\---\My Teen Romantic Comedy SNAFU\Staffel 2\My Teen Romantic Comedy SNAFU Staffel 2 Folge 12 Für seine ersehnte Antwort, die bisher immer noch außerhalb seiner Reichweite liegt, wird seine Unverfälschtheit weiter verkehrt fortgesetzt.mp4"

27.03.2021 05:47:22 ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
27.03.2021 05:47:22   built with gcc 10.2.1 (GCC) 20200726
27.03.2021 05:47:22   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
27.03.2021 05:47:22   libavutil      56. 51.100 / 56. 51.100
27.03.2021 05:47:22   libavcodec     58. 91.100 / 58. 91.100
27.03.2021 05:47:22   libavformat    58. 45.100 / 58. 45.100
27.03.2021 05:47:22   libavdevice    58. 10.100 / 58. 10.100
27.03.2021 05:47:22   libavfilter     7. 85.100 /  7. 85.100
27.03.2021 05:47:22   libswscale      5.  7.100 /  5.  7.100
27.03.2021 05:47:22   libswresample   3.  7.100 /  3.  7.100
27.03.2021 05:47:22   libpostproc    55.  7.100 / 55.  7.100
27.03.2021 05:47:22 [https @ 0703ef80] The "user-agent" option is deprecated: use the "user_agent" option instead
27.03.2021 05:47:22 [https @ 07034dc0] No trailing CRLF found in HTTP header. Adding it.
27.03.2021 05:47:22 [hls @ 0703e1c0] Skip ('#EXT-X-ALLOW-CACHE:YES')
27.03.2021 05:47:22 [hls @ 0703e1c0] Skip ('#EXT-X-VERSION:5')
27.03.2021 05:47:22 [hls @ 0703e1c0] Opening 'https://a-vrv.akamaized.net/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/encryption.key?t=exp=1616990033~acl=/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/*~hmac=7e820ea2070b71369f78f0cc70d554b7c3617977adc8d434bd770b20939afd9d' for reading
27.03.2021 05:47:23 [hls @ 0703e1c0] Opening 'crypto+https://a-vrv.akamaized.net/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/seg-1-v1-a1.ts?t=exp=1616990033~acl=/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/*~hmac=7e820ea2070b71369f78f0cc70d554b7c3617977adc8d434bd770b20939afd9d' for reading
27.03.2021 05:47:23 Input #0, hls, from 'https://pl.crunchyroll.com/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/index-v1-a1.m3u8?Expires=1616993242&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9mMTMyYWNhOWQzOWQxMmNhMmUxMmU3ZmM1YWM5M2VmMS9hc3NldHMvbnpmZHNjNWtlcG5ycXVuXyoubTN1OD8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjE2OTkzMjQyfX19XX0_&Signature=Mq3Bk8~Fwhyly-f2ZCyyX1M7Y~jMvgvQx2Yhqgg-D0KcCfobFZRhp9cxa8vjzOKTTgbqIc~FLb4YGIYFhixzAjuqbaqg0pzWsoZzf21zfRdJpszkEltRe0h0RfwBmxRXF~YSZX2bd7Db25JjbYydROOSMNgJ7u8GT9ELcjTmzfQKeQxETaayqX5cTuFvg~WU~baQ20qnpBJrKwgBvkxIKkKGai7M8~ZLj7CGB5n2HvuSMza3OxIJwrwUkxdV87p-sG5sh2buP21RbO4ZUeVCSxCqLn6yVn~Hn62cT2vlPaUmARLqvgV33zssaO2NCXfdwsvghAjNlV4yVOJWWqcuQQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=akamai-prod':
27.03.2021 05:47:23   Duration: 00:24:09.28, start: 0.101000, bitrate: 0 kb/s
27.03.2021 05:47:23   Program 0 
27.03.2021 05:47:23     Metadata:
27.03.2021 05:47:23       variant_bitrate : 0
27.03.2021 05:47:23     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
27.03.2021 05:47:23     Metadata:
27.03.2021 05:47:23       variant_bitrate : 0
27.03.2021 05:47:23     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
27.03.2021 05:47:23     Metadata:
27.03.2021 05:47:23       variant_bitrate : 0
27.03.2021 05:47:23     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
27.03.2021 05:47:23     Metadata:
27.03.2021 05:47:23       variant_bitrate : 0
27.03.2021 05:47:23 C:\Users\---\My Teen Romantic Comedy SNAFU\Staffel 2\My Teen Romantic Comedy SNAFU Staffel 2 Folge 12 FÃ¼r seine ersehnte Antwort, die bisher immer noch auÃŸerhalb seiner Reichweite liegt, wird seine UnverfÃ¤lschtheit weiter verkehrt fortgesetzt.mp4: No such file or directory
27.03.2021 05:47:23 
27.03.2021 05:47:23 
27.03.2021 05:49:43 -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/index-v1-a1.m3u8?Expires=1616993242&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9mMTMyYWNhOWQzOWQxMmNhMmUxMmU3ZmM1YWM5M2VmMS9hc3NldHMvbnpmZHNjNWtlcG5ycXVuXyoubTN1OD8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjE2OTkzMjQyfX19XX0_&Signature=Mq3Bk8~Fwhyly-f2ZCyyX1M7Y~jMvgvQx2Yhqgg-D0KcCfobFZRhp9cxa8vjzOKTTgbqIc~FLb4YGIYFhixzAjuqbaqg0pzWsoZzf21zfRdJpszkEltRe0h0RfwBmxRXF~YSZX2bd7Db25JjbYydROOSMNgJ7u8GT9ELcjTmzfQKeQxETaayqX5cTuFvg~WU~baQ20qnpBJrKwgBvkxIKkKGai7M8~ZLj7CGB5n2HvuSMza3OxIJwrwUkxdV87p-sG5sh2buP21RbO4ZUeVCSxCqLn6yVn~Hn62cT2vlPaUmARLqvgV33zssaO2NCXfdwsvghAjNlV4yVOJWWqcuQQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=akamai-prod" -map 0:v -map 0:a  -c copy -bsf:a aac_adtstoasc -c:s mov_text -metadata:s:a:0 language=jpn "C:\Users\---\My Teen Romantic Comedy SNAFU\Staffel 2\My Teen Romantic Comedy SNAFU Staffel 2 Folge 12 Für seine ersehnte Antwort, die bisher immer noch außerhalb seiner Reichweite liegt, wird seine Unverfälschtheit weiter verkehrt fortgesetzt.mp4"
27.03.2021 05:49:43 ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
27.03.2021 05:49:43   built with gcc 10.2.1 (GCC) 20200726
27.03.2021 05:49:43   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
27.03.2021 05:49:43   libavutil      56. 51.100 / 56. 51.100
27.03.2021 05:49:43   libavcodec     58. 91.100 / 58. 91.100
27.03.2021 05:49:43   libavformat    58. 45.100 / 58. 45.100
27.03.2021 05:49:43   libavdevice    58. 10.100 / 58. 10.100
27.03.2021 05:49:43   libavfilter     7. 85.100 /  7. 85.100
27.03.2021 05:49:43   libswscale      5.  7.100 /  5.  7.100
27.03.2021 05:49:43   libswresample   3.  7.100 /  3.  7.100
27.03.2021 05:49:43   libpostproc    55.  7.100 / 55.  7.100
27.03.2021 05:49:43 [https @ 06d9ef80] The "user-agent" option is deprecated: use the "user_agent" option instead
27.03.2021 05:49:43 [https @ 06d94dc0] No trailing CRLF found in HTTP header. Adding it.
27.03.2021 05:49:43 [hls @ 06d9e1c0] Skip ('#EXT-X-ALLOW-CACHE:YES')
27.03.2021 05:49:43 [hls @ 06d9e1c0] Skip ('#EXT-X-VERSION:5')
27.03.2021 05:49:43 [hls @ 06d9e1c0] Opening 'https://a-vrv.akamaized.net/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/encryption.key?t=exp=1616990033~acl=/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/*~hmac=7e820ea2070b71369f78f0cc70d554b7c3617977adc8d434bd770b20939afd9d' for reading
27.03.2021 05:49:44 [hls @ 06d9e1c0] Opening 'crypto+https://a-vrv.akamaized.net/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/seg-1-v1-a1.ts?t=exp=1616990033~acl=/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/*~hmac=7e820ea2070b71369f78f0cc70d554b7c3617977adc8d434bd770b20939afd9d' for reading
27.03.2021 05:49:44 Input #0, hls, from 'https://pl.crunchyroll.com/evs1/f132aca9d39d12ca2e12e7fc5ac93ef1/assets/nzfdsc5kepnrqun_3951482.mp4/index-v1-a1.m3u8?Expires=1616993242&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9mMTMyYWNhOWQzOWQxMmNhMmUxMmU3ZmM1YWM5M2VmMS9hc3NldHMvbnpmZHNjNWtlcG5ycXVuXyoubTN1OD8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjE2OTkzMjQyfX19XX0_&Signature=Mq3Bk8~Fwhyly-f2ZCyyX1M7Y~jMvgvQx2Yhqgg-D0KcCfobFZRhp9cxa8vjzOKTTgbqIc~FLb4YGIYFhixzAjuqbaqg0pzWsoZzf21zfRdJpszkEltRe0h0RfwBmxRXF~YSZX2bd7Db25JjbYydROOSMNgJ7u8GT9ELcjTmzfQKeQxETaayqX5cTuFvg~WU~baQ20qnpBJrKwgBvkxIKkKGai7M8~ZLj7CGB5n2HvuSMza3OxIJwrwUkxdV87p-sG5sh2buP21RbO4ZUeVCSxCqLn6yVn~Hn62cT2vlPaUmARLqvgV33zssaO2NCXfdwsvghAjNlV4yVOJWWqcuQQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=akamai-prod':
27.03.2021 05:49:44   Duration: 00:24:09.28, start: 0.101000, bitrate: 0 kb/s
27.03.2021 05:49:44   Program 0 
27.03.2021 05:49:44     Metadata:
27.03.2021 05:49:44       variant_bitrate : 0
27.03.2021 05:49:44     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
27.03.2021 05:49:44     Metadata:
27.03.2021 05:49:44       variant_bitrate : 0
27.03.2021 05:49:44     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
27.03.2021 05:49:44     Metadata:
27.03.2021 05:49:44       variant_bitrate : 0
27.03.2021 05:49:44     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
27.03.2021 05:49:44     Metadata:
27.03.2021 05:49:44       variant_bitrate : 0
27.03.2021 05:49:44 C:\Users\---\My Teen Romantic Comedy SNAFU\Staffel 2\My Teen Romantic Comedy SNAFU Staffel 2 Folge 12 FÃ¼r seine ersehnte Antwort, die bisher immer noch auÃŸerhalb seiner Reichweite liegt, wird seine UnverfÃ¤lschtheit weiter verkehrt fortgesetzt.mp4: No such file or directory
27.03.2021 05:49:44 
27.03.2021 05:49:44 </details>

**Comment by hama3254** [comment]
> 27.03.2021 05:47:23 C:\Users---\My Teen Romantic Comedy SNAFU\Staffel 2\My Teen Romantic Comedy SNAFU Staffel 2 Folge 12 FÃ¼r seine ersehnte Antwort, die bisher immer noch auÃŸerhalb seiner Reichweite liegt, wird seine UnverfÃ¤lschtheit weiter verkehrt fortgesetzt.mp4: No such file or directory

Es scheint als würde es den Ordner nicht finden.

Die falsch dargestellten Buchstaben kann man übrigens ignorieren, das zeigt er bei mir genauso an.

<details>
<summary>
Log File
</summary>

>27.03.2021 13:51:53 Output #0, mp4, to 'C:\Users---\My Teen Romantic Comedy SNAFU\Staffel 2\My Teen Romantic Comedy SNAFU Staffel 2 Folge 12 FÃ¼r seine ersehnte Antwort, die bisher immer noch auÃŸerhalb seiner Reichweite liegt, wird seine UnverfÃ¤lschtheit weiter verkehrt fortgesetzt.mp4':
27.03.2021 13:51:53   Metadata:
27.03.2021 13:51:53     encoder         : Lavf58.45.100
27.03.2021 13:51:53     Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 23.98 fps, 23.98 tbr, 90k tbn, 90k tbc
27.03.2021 13:51:53     Metadata:
27.03.2021 13:51:53       variant_bitrate : 0
27.03.2021 13:51:53     Stream #0:1(jpn): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
27.03.2021 13:51:53     Metadata:
27.03.2021 13:51:53       variant_bitrate : 0
27.03.2021 13:51:53 Stream mapping:
27.03.2021 13:51:53   Stream #0:0 -> #0:0 (copy)
27.03.2021 13:51:53   Stream #0:1 -> #0:1 (copy)
27.03.2021 13:51:53 Press [q] to stop, [?] for help

</details>

Abgesehen davon zu versuchen einen anderen Ordner zu verwenden bzw. den Namen auf Staffel + Episode zu beschränken sehe ich nichts was den Fehler auslösen könnte.

**Comment by llinke** [comment]
Pfade dürfen unter Windows max 248 Zeichen oder so lang sein. Der Pfad könnte evtl einfach nur zu lang sein. Ließe sich im Code prüfen und ggf. Dateiname kürzen. 

Probier mal anderes Benennungsschema oder Ordner, wenn das hilft, dann war's der zu lange Name.

**Comment by xILikepuddingx** [comment]
Scheint tatsächlich an der Länge zu liegen.
Kann man da eventuell was machen?

**Comment by hama3254** [comment]
Da lässt sich nichts machen.

>System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein

ich baue für die nächste version eine abfrage für den fall ein und kürze den Pfad/Dateiname.
