### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by PAVfr** [hama3254/Crunchyroll-Downloader-v3.0#233]
When I click on "browser" it shows me this message.
It is impossible for me to make it work.

![cr_bug1](https://user-images.githubusercontent.com/40724816/112725127-eb9e3a80-8f16-11eb-9208-91d225a5cb3a.png)

**Comment by hama3254** [comment]
This issue is yot solved yet but i already added a workaround.
You find more information at issue #191
