### ISSUE TITLE
Error while downloading anime from Funimation

### ISSUE THREAD

**Issue by AlexMiniReal** [hama3254/Crunchyroll-Downloader-v3.0#236]
Hi, when i try to download anime from Funimation (using Surfshark VPN), this error pops-up:
![Screenshot_1](https://user-images.githubusercontent.com/76444133/113054932-47ccbd00-91aa-11eb-9a1f-64e10fd71eb1.jpg)

I'm using the latest version of the downloader.

**Comment by hama3254** [comment]
That feature has not been added.
You can read #116 for more information.
