### ISSUE TITLE
Episode list doesn't show up.

### ISSUE THREAD

**Issue by Aetohatir** [hama3254/Crunchyroll-Downloader-v3.0#237]
Hello, I'm new to your program but it doesn't seem to work correctly for me.
When I choose the show under crunchyroll and press download when confronted with the episode selector the list is empty. In addition, when I open crunchyroll over the integrated browser the episodes also don't show up.
To make things even weirder it seems to work with some shows and not with others.

In particular One Piece doesn't work but Naruto Shippuden works.
I'm a bit frustrated because I've already spent a lot of time trying to find anime with German subtitles for my 10yo brother.

**Comment by hama3254** [comment]
The downloader has the same restriction as the normal Web browser.
This includes your country and the language selected. 
The Link has the selected language added to it like : 
`https://www.crunchyroll.com/de/one-piece` for German and `https://www.crunchyroll.com/one-piece` would be English with no video.

![grafik](https://user-images.githubusercontent.com/52826614/113356511-a2991c80-9342-11eb-8f46-3110d02318a0.png)

![grafik](https://user-images.githubusercontent.com/52826614/113356124-1ab31280-9342-11eb-966b-0559dd371d5a.png)
