### ISSUE TITLE
Download or Record?

### ISSUE THREAD

**Issue by fionamorrison13** [hama3254/Crunchyroll-Downloader-v3.0#238]
Does this download the file from Crunchyroll servers or record the episode? (WEB-DL or WEBrip?)

**Comment by hama3254** [comment]
The Downloader does what its name suggest, it downloads the hls video stream and converts it to mp4/mkv.

**Comment by fionamorrison13** [comment]
> The Downloader does what its name suggest, it downloads the hls video stream and converts it to mp4/mkv.

Thank you for the quick reply! I'm amazed by your project and I will recommend it to everyone I know.

**Comment by fionamorrison13** [comment]
I closed this too quickly before asking a follow-up. When the video converts from HLS to MP4 or MKV, is there any compression involved or does it stay as it was downloaded?

**Comment by hama3254** [comment]
> 
> 
> I closed this too quickly before asking a follow-up. When the video converts from HLS to MP4 or MKV, is there any compression involved or does it stay as it was downloaded?

that is up to your settings, default is a 1:1 copy (just format changed from ts to mp4/mkv) but you can re-encode it if you want.
![grafik](https://user-images.githubusercontent.com/52826614/113435603-71bcf400-93e3-11eb-9f23-75c179c8be03.png)

**Comment by fionamorrison13** [comment]
That's super neat. Thank you so much for answering my questions.
