### ISSUE TITLE
The program does not open me in any way

### ISSUE THREAD

**Issue by Esmintor** [hama3254/Crunchyroll-Downloader-v3.0#24]
My problem is the following, in one of the previous versions the program would have perfectly suited me (to be precise in 3.0.1), but just today I tried to open it but nothing, there would be no more than I gave it, it does not show me any message of error or anything, try to run it as administrator but nothing either, I go to the task manager and what I see is that the program tries to open but enters a state of suspension and closes without having started, so I have the doubt that if it is my pc that cannot open it or it will be something else.

**Comment by hama3254** [comment]
please check if you have the Software Requirements:
Microsoft Visual C++ 2017 Redistributable
.net Framework 4.5.2

**Comment by Esmintor** [comment]
![79822528_p](https://user-images.githubusercontent.com/47908594/83867034-f799e100-a6e5-11ea-885d-ca08c493714b.png)
hola

**Comment by hama3254** [comment]
> 
> 
> please check if you have the Software Requirements:
> Microsoft Visual C++ 2017 Redistributable
> .net Framework 4.5.2

i need an answer to this if i should help you.

**Comment by Kyouma95** [comment]
Hi, i have the same Issue on my mini-pc. On my main PC it works fine, but on my mini-pc (which i use for downloads and so on) it doesnt open up. The Requirements you´ve listed are installed on both machines and i cant seem to find the difference.

**Comment by hama3254** [comment]
@Kyouma95 @Esmintor 
please try to launch the app again and tehn look at the windows event view and send me the error listed there.
Short Video:
https://www.youtube.com/watch?v=DTbwyV4tHSk
if your Windows is not in english the then look for the "eventvwr.exe"

**Comment by Kyouma95** [comment]
Application Error
`Name der fehlerhaften Anwendung: Crunchyroll Downloader.exe, Version: 3.2.5.0, Zeitstempel: 0x5ed52f66
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.18362.815, Zeitstempel: 0x67005c2a
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00114402
ID des fehlerhaften Prozesses: 0x1814
Startzeit der fehlerhaften Anwendung: 0x01d63cf3a6e825b7
Pfad der fehlerhaften Anwendung: D:\Downloads\CR\Crunchyroll Downloader.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 61b6e539-b5f6-444b-a75b-b448bc333818
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: `

.NET Runtime Error
`Anwendung: Crunchyroll Downloader.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.DllNotFoundException
   bei Gecko.Xpcom.Alloc(IntPtr)
   bei Gecko.nsAString..ctor()
   bei Gecko.nsAString..ctor(System.String)
   bei Gecko.Xpcom.Initialize(System.String)
   bei Crunchyroll_Downloader.My.MyApplication.OnStartup(Microsoft.VisualBasic.ApplicationServices.StartupEventArgs)
   bei Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   bei Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   bei Crunchyroll_Downloader.My.MyApplication.Main(System.String[])
`

**Comment by hama3254** [comment]
>System.DllNotFoundException

is seems some files are missing in your folder, i suggest you re-download the last version.

**Comment by Kyouma95** [comment]
Deleted the Folder and downloaded the 3.2.5 release, but it didnt helped still not opening.

**Comment by hama3254** [comment]
then you only can try to reinstall the x86 version from here :
https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Kyouma95** [comment]
Will try that when im back home at the weekend.

**Comment by Kyouma95** [comment]
Installing the x86 version helped and it works now, thank you

**Comment by x3inspire** [comment]
Possible to support Windows Server?

**Comment by hama3254** [comment]
> 
> 
> Possible to support Windows Server?

It is not supported and never will again

**Comment by hama3254** [comment]
> 
> 
> Installing the x86 version helped and it works now, thank you

thanks for the answer, i close this issue.
