### ISSUE TITLE
Request to add Netflix

### ISSUE THREAD

**Issue by proall** [hama3254/Crunchyroll-Downloader-v3.0#241]
i see i'm can use another link to download MPD or m3u8 file, you can enable it for Netflix too?
or if you can learn me how to download from netflix i have Widevine breaker i can get the key but i can't find the Stream Link from netflix the MPD or the m3u8 file..
plz it will help i can pay money for that..

**Comment by hama3254** [comment]
>I am not able to download DRM protected content. This includes Netflix and many more like Amazon Prime and Wakanim
>
>_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/168#issuecomment-775461080_

**Comment by proall** [comment]
You know how to find the m3u8 stream link on netflix? it will help a lot i have Widevine breaker thats break the protection
but i'm can't find the link..

**Comment by hama3254** [comment]
I don't know if they even use m3u8 also known as HLS stream and it's illegal to break DRM anyway:

>(1) Wirksame technische Maßnahmen zum Schutz eines nach diesem Gesetz geschützten Werkes oder eines anderen nach diesem Gesetz geschützten Schutzgegenstandes dürfen ohne Zustimmung des Rechtsinhabers nicht umgangen werden, soweit dem Handelnden bekannt ist oder den Umständen nach bekannt sein muss, dass die Umgehung erfolgt, um den Zugang zu einem solchen Werk oder Schutzgegenstand oder deren Nutzung zu ermöglichen.
[§ 95a Schutz technischer Maßnahmen](https://www.gesetze-im-internet.de/urhg/__95a.html)

**Comment by NatsuFT36** [comment]
But it would be good to add Wakanim download option for France, Germany and Russia since they are providers together with Funimation

**Comment by hama3254** [comment]
> But it would be good to add Wakanim download option

 
>  I am not able to download DRM protected content. This includes Netflix and many more like Amazon Prime and Wakanim
> _Originally posted by @hama3254 in [#168 (comment)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/168#issuecomment-775461080)_

![image](https://user-images.githubusercontent.com/52826614/114264497-97ea2180-99eb-11eb-8856-0156bac25692.png)

**Comment by proall** [comment]
Not think, Amazon and Crunchyroll play the media with MPD stream, with DRM protection.
On Netflix i know they using DRM but its only the High Profile can be download with Widevine, the main able only with PlayReady DRM, but amazon its works like crunchyroll.
