### ISSUE TITLE
System.Net.WebException: The operation has timed out

### ISSUE THREAD

**Issue by trueamnot** [hama3254/Crunchyroll-Downloader-v3.0#242]
![Screenshot 2021-04-07 145737](https://user-images.githubusercontent.com/82114577/113912927-152a5200-97b2-11eb-8051-e250e28c1aa9.png)

**Comment by hama3254** [comment]
Timeouts are random issues that can be caused either by your internet or the server.
There is nothing I can do to prevent it.

**Comment by trueamnot** [comment]
> 
> 
> Timeouts are random issues that can be caused either by your internet or the server.
> There is nothing I can do to prevent it.

I see. Anyhow, thanks for clarifying.
