### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by gummykage** [hama3254/Crunchyroll-Downloader-v3.0#246]
![image](https://user-images.githubusercontent.com/9695713/113987552-63b40c80-9803-11eb-8dd3-bcf5dfef995f.png)

Whenever I try to download an episode it does this.

**Comment by hama3254** [comment]
It seems like you are using the v3.8-Beta.
As already mentioned in #243 the path generator has an issue which makes it fail in the most cases for the regular crunchyroll download.
You need to use the last release version instead of the beta version.

**Comment by hama3254** [comment]
fixed in new beta release
