### ISSUE TITLE
"The connection was refused when attempting to contact"

### ISSUE THREAD

**Issue by JauCR** [hama3254/Crunchyroll-Downloader-v3.0#248]
Every time I insert the link for an episode or just enter the browser I get this error and I don't know how to fix it :(
![refused](https://user-images.githubusercontent.com/60068235/114414914-8782a400-9baf-11eb-96e1-37de2e308792.png)

**Comment by hama3254** [comment]
I found [this Firefox support article](https://support.mozilla.org/en-US/questions/1254183) for there Thunderbird.
You can give it a try
