### ISSUE TITLE
I don't know how this happened

### ISSUE THREAD

**Issue by Adhit001** [hama3254/Crunchyroll-Downloader-v3.0#250]
![Capture](https://user-images.githubusercontent.com/55088676/114826471-21d62800-9dfa-11eb-8e20-5c7961196705.PNG)

**Comment by hama3254** [comment]
You have enabled the error detection, the video on the website is not a single file it's split into hundreds or even thousands of pieces depending on the Duration.
For you 5 of that have failed to download which would result in a view seconds skip/lagg for each of them.
Why that happens is mostly unknown, it can be network related issues or just server issue from the website.
