### ISSUE TITLE
The program automatically re-encodes in x265 without being told to

### ISSUE THREAD

**Issue by Figgyee** [hama3254/Crunchyroll-Downloader-v3.0#251]
As of title, the program automatically re-encodes in h.265, making the process of downloading even a single episode painfully slow, without being told to through the settings.

**Comment by hama3254** [comment]
the downloader should use the ffmpeg command specified in the settings.
The checkbox is no enable/disable switch it just prevents the user from changing anything on accident. 
If you download from funimation with hardsub enabled you also re-encode the video (most likely in h264) to convert there softsub to hardsub.
![grafik](https://user-images.githubusercontent.com/52826614/115061972-16fac080-9eea-11eb-9c72-ce9d54f615e8.png)

**Comment by Figgyee** [comment]
Thank you very much, I didn't know that the checkbox is not an enable/disable switch. Apparently I set it on HEVC and left like that without knowing it.
