### ISSUE TITLE
Funimation Queue Protocol Violation

### ISSUE THREAD

**Issue by MSI-Toby** [hama3254/Crunchyroll-Downloader-v3.0#253]
![image](https://user-images.githubusercontent.com/11889553/115065694-b056b200-9eab-11eb-97e8-edd8689e1063.png)

Not sure if this has been reported already, but the queue breaks when you load multiple Funi videos. Thx

**Comment by hama3254** [comment]
That seems to a server side issue to me, the response was invalid according to the error message.

**Comment by Dantrech** [comment]
Looh here #249

**Comment by MSI-Toby** [comment]
Looks like its a slightly different issue. .NET doesn't like CR without a LF. If you just add _useUnsafeHeaderParsing = "true"_ to the app.config file, it should make the error go away.

https://docs.microsoft.com/en-us/dotnet/api/system.net.configuration.httpwebrequestelement.useunsafeheaderparsing?view=netframework-4.8

**Comment by MSI-Toby** [comment]
I reset my Firefox and it seems to have fixed the problem.
