### ISSUE TITLE
10-second stuck in the video

### ISSUE THREAD

**Issue by Mercedes-Huo** [hama3254/Crunchyroll-Downloader-v3.0#26]
I've downloaded some Crunchyroll anime from this downloader, but there is always a 10-second stuck in the middle of the video. Sometimes the stuck is at the video start, sometimes at the back. I've tried a lot of time, delete it and re-download, but it always happens. Does it attribute to the speed of the internet? Can you fix that problem?

**Comment by hama3254** [comment]
This problem is most likely that ffmpeg did not get one of the segments of the m3u8 file.
There is nothing i can do about it, you can just make sure that you not run to many downloads at once to prevent a timeout.

**Comment by kingbroseph2594** [comment]
ok thanks but im pretty sure ive figured out the problem, basically I'm downloading to an external drive and I'm pretty sure the contact points are kinda crappy so as soon as it "disconnects" for like a little while it stops and doesn't continue but now i just download straight to my computer then copy it onto my microSD :):)

**Comment by hama3254** [comment]
> 
> 
> if there are still problems you can now save a log file
> i added the function, so in the same folder as the downloader there get all data wich i have saved (<100KB)
> you can enable it in v3.2.7 or above
 
> to send me the file you can just attach it on this issue.

it seems there are no more problem so i will close this now.
you can re-open this issue with a log file if this happens again.
