### ISSUE TITLE
Error in funimation download

### ISSUE THREAD

**Issue by Nults** [hama3254/Crunchyroll-Downloader-v3.0#263]
When i hit the download button, it shows me an error:
![Screenshot_2](https://user-images.githubusercontent.com/51493797/115476728-dae09c00-a218-11eb-8838-355ee496b76b.png)

Then, when i hit "ok", the download start, but in some weird way:
![Screenshot_1](https://user-images.githubusercontent.com/51493797/115476792-f8156a80-a218-11eb-945e-550467b7ddfd.png)

And it keep stuck at 1%, in latest version (v3.7.8.6)
(I don't have the hybrid option enabled.)

**Comment by hama3254** [comment]
> I don't have the hybrid option enabled.

I would suggest you check that again because the error is in `CRD_List_Item.DownloadHybrid` and the episode should not have more than 450 Gigabyte

**Comment by Nults** [comment]
Oh, indeed. Maybe the option didn't save, sorry.
