### ISSUE TITLE
Acces denied

### ISSUE THREAD

**Issue by lenny1400** [hama3254/Crunchyroll-Downloader-v3.0#264]
![image](https://user-images.githubusercontent.com/61922603/115516305-46ad1e00-a286-11eb-86cb-95ebf98f1091.png)

I read that this issue was fixed a while ago, but i got this in the latest version too

**Comment by hama3254** [comment]
It is possible that i just fixed it in the v3.8-Beta and since the v3.7.8.x has non of the beta code it could be that the fix is also missing.
You can try to use the beta until I merge both versions.

**Comment by lenny1400** [comment]
I tried the 3.7.8.3 version and it worked again. Either way, thanks
