### ISSUE TITLE
There is a Main AVC codec?

### ISSUE THREAD

**Issue by proall** [hama3254/Crunchyroll-Downloader-v3.0#268]
Crucnhyroll have Main AVC codec (When i'm using your software or ripping with the DRM key its (High@L4))?
I tried use Edge, but its the same as chrome, firefox.

**Comment by proall** [comment]
And if they support DDP (Dolby Digital Plus) and Dolby Atoms Audio?
I saw someone ripping with 224kb/s, 48.0kHz, 2 channels, **E-AC-3** (Dolby Digital Plus)
or its just decoded? i think so cause the Video was
6509kb/s, 1920*1080 (16:9), at 23.976 (24000/1001) FPS, AVC (High 10@L5.1) (CABAC / 16 Ref Frames)

**Comment by hama3254** [comment]
I'm not sure what you want from me? 
The default setting downloads an copy from the Crunchyroll hls/m3u8 stream without changing the video codec. 
![grafik](https://user-images.githubusercontent.com/52826614/115749635-962f3f00-a397-11eb-93d9-50c5c72ed833.png)

**Comment by STRATOS99K** [comment]
> And if they support DDP (Dolby Digital Plus) and Dolby Atoms Audio?
> I saw someone ripping with 224kb/s, 48.0kHz, 2 channels, **E-AC-3** (Dolby Digital Plus)
> or its just decoded? i think so cause the Video was
> 6509kb/s, 1920*1080 (16:9), at 23.976 (24000/1001) FPS, AVC (High 10@L5.1) (CABAC / 16 Ref Frames)

CR is 128 Kbps AAC, ac-3 usually comes from amazon
