### ISSUE TITLE
AoD Login nicht erkannt

### ISSUE THREAD

**Issue by Serady273** [hama3254/Crunchyroll-Downloader-v3.0#270]
Mal vorweg, danke für dieses super Programm.
Bei Crunchyroll hat es super funktioniert.
Allerdings hab ich bei AoD das Problem, dass er jedes mal sagt, dass ich prüfen soll ob ich eingeloggt bin. Was ich bin. Egal ob ich Firefox öffne oder es über den Browser im Tool mache ich bekomme jedes Mal diese Meldung
![Unbenannt](https://user-images.githubusercontent.com/83249738/116154277-c0ab3000-a6e8-11eb-9b94-9b0002475fd9.PNG)
Was mache ich falsch? 
Ich logge mich bei AoD ein während das Tool bereits läuft ein und suche mir dann den entsprechenden Link (https://www.anime-on-demand.de/anime/XXX) heraus und füge diesen genauso wie bei Crunchyroll in das Tool ein und klicke dann auf Download. Danach kommt dann diese Meldung oben.

**Comment by hama3254** [comment]
Du musst im Browser vom downloader eingeloggt sein und den Haken zum merken setzen, sonst verliert er den Login beim Schließen des Browser Fensters wieder.

**Comment by Serady273** [comment]
Super vielen Dank. Jetzt klappt es.
