### ISSUE TITLE
Funimation Website changes

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#271]
>I use the relative one to get the `experienceID` so it does not find the video any more.
>I fix that soon.

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/256#issuecomment-827305664_

Well if the url was the only thing they changes it would be a easy fix.

The short explanation is that they changed the site and i have to rewrite the whole funimation part of the downloader.

The long version is they have no data to speak of in the HMTL any more and load everything via JavaScript. That means i need to find the data somewhere else and then rewrite the downloader and the add-on.

**Comment by hama3254** [comment]
Temporary workaround would be to use a language based url.
if i use `https://www.funimation.com/en/shows/[some anime]/[some epiode]/` instead of  `https://www.funimation.com/shows/[some anime]/[some epiode]/` then i get the old version.
![grafik](https://user-images.githubusercontent.com/52826614/116434570-ce78c680-a84a-11eb-85b5-0437e43b2297.png)

**Comment by lemming104** [comment]
The Javascript stuff talks to a set of RESTful web services, one of which you can hit with just the experienceID, e.g. `GET https://www.funimation.com/api/experience/<experienceId>`.  This returns a pretty big Json payload that contains _detailed_ information (such as the specific streams, etc. available) for the currently selected experience, but limited metadata for other experiences available for the current episode, and even information about other episodes/seasons.  It's kind of weird, and you're almost certainly going to want to use a proper Json parser to explore the data, rather than attempting to parse the raw text.

For example, here, I randomly selected the most recently updated episode of Hetalia, which is apparently episode 5.
https://pastebin.com/LerVi5zj

If you scroll _way_ down to line 1564 of the paste, you'll see the actual metadata for that episode.

**Comment by NatsuFT36** [comment]
I have seen how the Golumpa that uploads dubbing in English has an audio change from 128 to 256 kbps but I wanted to know what extension can be used to see an audio in a Funimation anime to see if maybe it can do something

**Comment by hama3254** [comment]
@NatsuFT36  Funimation has just 128kbps you wont get more from my downloader.
![grafik](https://user-images.githubusercontent.com/52826614/118396010-c217aa80-b64d-11eb-8bb7-49b4815dac7b.png)

**Comment by NatsuFT36** [comment]
Although the quality of the video is varied, such as 720p that comes out in 2 times one of 2150 kb / s and the other of 3500 kb / s

**Comment by NatsuFT36** [comment]
Example of My Hero Academia 94: 3547 kb / s, 95: 2290 kb / s

**Comment by MSI-Toby** [comment]
I think I got the logic of how to get from the API to the URL. From the API, for me it is (https://title-api.prd.funimationsvc.com/v1/seasons/{id}?region=CA&deviceType=web), we the entire show's data.  From what I can figure, it's 'https://www.funimation.com/en/shows/{"show"/"slug"}/{"episodes"/[ ]/"slug"} . 

For example the below image gets me the URL 'https://www.funimation.com/en/shows/mars-red/dawn-67df1e54-8e4d-11eb-adec-0242ac110003'

![Screenshot 2021-05-17 123758](https://user-images.githubusercontent.com/11889553/118539542-c3f47300-b70c-11eb-8a5a-7784ad67ff07.png)

Hope this helps.

**Comment by Rule1311** [comment]
I am new to this...
Can you give a step by step explanation how to get the json.

**Comment by MSI-Toby** [comment]
So starting at a show URL ex 'https://www.funimation.com/shows/spice-and-wolf/?qid=', we could extract the show string 'spice-and-wolf'.

The URL https://title-api.prd.funimationsvc.com/v2/shows/{show}?region=CA&deviceType=web gets us a JSON with the ID tag. (ex https://title-api.prd.funimationsvc.com/v2/shows/spice-and-wolf?region=CA&deviceType=web).

That's how I think the JS getting the data to get the URLs.

**Comment by hama3254** [comment]
@MSI-Toby Thank you, it really helps to know what i have to look for and to know that there is a JSON viewer plugin for notepad++ also makes things simpler

**Comment by Rule1311** [comment]
I have the JSON viewer plugin installed but don't know how to use it.

**Comment by MSI-Toby** [comment]
Without any JS rendering, this is how I think we can get to the m3u8 file. I'm not sure how to get the pinst_id yet.

Starting at an episode:
https://www.funimation.com/shows/{name}/{slug}

Get (season) id and (season) number
https://title-api.prd.funimationsvc.com/v2/shows/{name}?region=CA&deviceType=web

Get showId
Have to guess on seasons
https://title-api.prd.funimationsvc.com/v1/seasons/{id}?region=CA&deviceType=web

Get experience
https://www.funimation.com/api/episodes/?title_id={showId}&season={number}&sort=order&sort_direction=ASC

Get m3u8
https://www.funimation.com/api/showexperience/{experience}/?pinst_id={pinst_id}

**Comment by hama3254** [comment]
with the new API i finally added the same style of mass download as on Crunchyroll and Anime On Demand. 
Now i just need completely rewrite the download for Funimation for the new JavaScript based site.

https://user-images.githubusercontent.com/52826614/118817256-5171c780-b8b3-11eb-8305-698cc03a9e6e.mp4

**Comment by MSI-Toby** [comment]
That looks great! Thanks for the amazing work you do!

**Comment by hama3254** [comment]
v3.8-Beta-U7 now includes the function to process the changed website.

**Comment by NatsuFT36** [comment]
The audio that is downloaded in the Funimation chapters is slower compared to the video that is downloaded normally

**Comment by NatsuFT36** [comment]
By the way, the Funimation chapters are uploaded on Brightcove

**Comment by hama3254** [comment]
> By the way, the Funimation chapters are uploaded on Brightcove

They just use the player, the files are on `cloudfront` [CDN](https://de.wikipedia.org/wiki/Content_Delivery_Network)
![grafik](https://user-images.githubusercontent.com/52826614/120886249-40cc8b80-c5ed-11eb-8e8c-6194b137dd0a.png)


> The audio that is downloaded in the Funimation chapters is slower compared to the video that is downloaded normally

That's a simplification, with just one exception the downloader reads the full stream anyway and just saves the audio stream so it should be no difference in overall download time it is just relative slow for the final amount of data.

>v3.8-Beta-U7 now includes the option for audio only as aac format, this however does not reduce the amount of downloaded data with the exception for the latest funimation  episodes which use `#EXT-X-VERSION:4` and are already splitted audio and video files.

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/285#discussioncomment-826114_

**Comment by hama3254** [comment]
since there are no current issues here i close this, if anybody finds something just make a new issue.
