### ISSUE TITLE
Only "Episode 0" is downloadable at AOD

### ISSUE THREAD

**Issue by ahillebrandt** [hama3254/Crunchyroll-Downloader-v3.0#272]
Hi,

in series https://www.anime-on-demand.de/anime/333 there is an Episode 0.
I'm not able to select another episode - is this a little Bug? 

![image](https://user-images.githubusercontent.com/7041209/116531695-be5ef680-a8df-11eb-93f4-6e4be7950009.png)

Thank you.

**Comment by hama3254** [comment]
Ich muss mir den Fall später genau anschauen, es könnte entweder damit zusammenhängen das die Folgen gekauft/geliehen sind oder Folge 0 ist einfach als eigenständiges Werk hinterlegt.

**Comment by hama3254** [comment]
Es liegt tatsächlich an dem account type, ohne Abo haben die ersten folgen den `/single` tag in der url, den überschreibe ich einfach dann gibt AoD genau die links der gekauften/geliehen folgen.
Hotfix ist als download verfügbar, die `Crunchyroll Downloader.exe` von der letzten Version einfach mit der `Crunchyroll Downloader-AoD.exe` ersetzen :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by ahillebrandt** [comment]
Ah, Du bist genial... 
hab mir grade beholfen indem ich die Links mit youtube-dl rausgesucht habe.. aber das ist wirklich super unpraktisch.
Dank Dir!

**Comment by ahillebrandt** [comment]
> Es liegt tatsächlich an dem account type, ohne Abo haben die ersten folgen den `/single` tag in der url, den überschreibe ich einfach dann gibt AoD genau die links der gekauften/geliehen folgen.
> Hotfix ist als download verfügbar, die `Crunchyroll Downloader.exe` von der letzten Version einfach mit der `Crunchyroll Downloader-AoD.exe` ersetzen :
> https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

Jetzt muss ich trotzdem nochmal blöd fragen:
Ich kann bei der Serie jetzt keine Sprache wählen und er läd immer OmU obwohl es Dub gibt, 
könntest Du da noch nach schauen?

**Comment by hama3254** [comment]
Es kommt eigentlich nicht vor das die erste folge kein Dub hat aber die zweite schon, daher ist er etwas durcheinander gekommen.
Das sollte mit `Crunchyroll-Downloader-v3.8-Beta-U3` behoben sein.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta
