### ISSUE TITLE
Video files with issues.

### ISSUE THREAD

**Issue by ElMatrixx** [hama3254/Crunchyroll-Downloader-v3.0#281]
Hi, i started using this app like a year ago and everything was fine, until now...
I was downloading Hunter x Hunter and i notice that sometimes a video file comes with a issue that bothers me a lot, the episode freezes like 6 times, its like a scratched DVD.
Something that I have noticed that those episodes where that failure occurs weigh less than 1.33 gb (the normal weight of a chapter),
![image](https://user-images.githubusercontent.com/84057108/117912379-0816ec00-b2a5-11eb-94fe-1727ee44e74b.png)
PD: Excuse me if my English is bad, im Peruvian.

**Comment by hama3254** [comment]
This is a know issue and an answer can be found in issue #170

**Comment by ElMatrixx** [comment]
when i put the restart button, it never starts!
