### ISSUE TITLE
Trying the new beta on the beta of crunchyroll

### ISSUE THREAD

**Issue by cimmy01** [hama3254/Crunchyroll-Downloader-v3.0#282]
I tried to use the new beta on crunchy's beta page and it will bring up the correct download info and will let me select the season .ie My hero academia season 5 but the episodes that I can get are blank. This is true for all of the shows that I tried to look at even older titles. I currently am running Version 3.8 beta-u3

**Comment by hama3254** [comment]
I have no issues after selecting a season to see it's content. 

![grafik](https://user-images.githubusercontent.com/52826614/119228005-1967c000-bb11-11eb-8a6d-06ca183b2380.png)

**Comment by cimmy01** [comment]
it works fine on the old site but hasn't worked on the beta site for me

**Comment by cimmy01** [comment]
![image](https://user-images.githubusercontent.com/56510595/119234369-8cfed280-bafb-11eb-84e4-3016f38da8f5.png)

**Comment by cimmy01** [comment]
![image](https://user-images.githubusercontent.com/56510595/119234380-9ab45800-bafb-11eb-8afa-2526886fed8d.png)

**Comment by hama3254** [comment]
Please open the console/log in the bottom of the downloader by pressing the Gray bar at the bottom, that is an normal textfield where you can select the text and add it here.
![grafik](https://user-images.githubusercontent.com/52826614/119235080-01a03400-bb31-11eb-9e79-5c79049482bb.png)

**Comment by cimmy01** [comment]
![image](https://user-images.githubusercontent.com/56510595/119235342-05679280-bb00-11eb-981d-9a7cb2c938e3.png)

**Comment by cimmy01** [comment]
this one is easier to read

![crunchyroll log](https://user-images.githubusercontent.com/56510595/119235436-84f56180-bb00-11eb-9cac-b439146f164e.jpg)

**Comment by hama3254** [comment]
> this one is easier to read

well ...

> that is an normal textfield where you can select the text and add it here.

but that enough because i guess i found the issue.

The call for the episode api has that base url : `"https://beta-api.crunchyroll.com/cms/v2/DE/M3/crunchyroll/episodes?season_id=" ` with the added parameters for the location `"&locale=" ` but i think the the `DE` in the base already refers to the German version so that might be the cause since all other api called use the data from the browser even for the base url.

i added the `Crunchyroll Downloader_Beta.exe` in the v3.8-Beta release which just needs to be placed inside the folder you already have and then you need to see if work then. 
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by cimmy01** [comment]
It has been sitting like this for some time. It has let me choose the episode but will not start the download.

5/22/2021 3:30:45 PM.138
https://beta-api.crunchyroll.com/cms/v2/US/M3/crunchyroll/episodes?season_id=GYE5CQ5N2&locale=en-US&Signature=fXXI-ssWxyZqhhfK18XP~iDdYvKi80JRge7tuVkCx3ITxmrWYa0QXNswAUxn6iinfwnJWrVtaJnLqoXjP8ssGoAXEEe-xbC35TCTgqis4z1kZRzmMv4GRGqx23TuPjtPXUd62bnXsLJBAt2HzHZ00~8XbMzRK9LGIrBsllqNuLHjbADwo2YZbeoisWMKXrmizJJDHe3nlMJnetJ8cR3xHLeMMhMYxTr07ANjsNqqxvHmw-0Zv9cqX8unJeuoeDLWYBb2WE1H036DoVWYlg~XmyxUIWmOEdTT1~GN-m3h3-4MsNKq7NEwL8pg9bLQ8leBVtSEoherzn5l8qLfLVC1wA__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00zL2NydW5jaHlyb2xsLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjE3OTgyNDZ9fX1dfQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
5/22/2021 3:32:38 PM.293
https://beta-api.crunchyroll.com/cms/v2/US/M3/crunchyroll/episodes?season_id=GYE5CQ5N2&locale=en-US&Signature=XDj9X4Ljc-4wUKUCUeyqVsLzFuuyMFqjTtbMVnnSgwe9JTG~VUEAp4M45Gr1o21So43yLNVNDyI-kLy27GY3f5Y5Lifn-YY2y~ypZOdsxRWVHSbprJXGo25nMWQekPZ0TdHhuViGktHybEol8nlg2k6JPH3NjvC8BKa7eVx0yIJC2qv~j8kkFVUEh21aYPeAFrxES88Qiq7GxWtyKlAK5aWzU7Bloqr5LiUYnl3J6oT25dyIVhp8AeY32MtVrvqJjv6UrmRULqiyK4vvGrTBlI04MRB4AZnm00gQjUJh~Y3lDY5njZ5b2dXu~DDyjtOqUWD9QjtixoBhUiaLT1op2w__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00zL2NydW5jaHlyb2xsLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjE3OTgzNTl9fX1dfQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA

**Comment by hama3254** [comment]
there is nothing really to see in that log, just two times the season selection api call.
if you have selected the season/episode you need to click the bottom download button
![grafik](https://user-images.githubusercontent.com/52826614/119240068-ca8c4b80-bb4d-11eb-8238-7817e00f32d0.png)
The download button should become a cancel directly after clicking.
![grafik](https://user-images.githubusercontent.com/52826614/119240084-e263cf80-bb4d-11eb-92e0-4ea03683d630.png)

to see any error message you can enable the debug messages with two double clicks on the settings icon until this messages apers : 
![grafik](https://user-images.githubusercontent.com/52826614/119240392-7aae8400-bb4f-11eb-9cee-a8a863ab51a9.png)

**Comment by cimmy01** [comment]
5/22/2021 5:38:58 PM.327
https://beta-api.crunchyroll.com/cms/v2/US/M3/crunchyroll/episodes?season_id=GYE5CQ5N2&locale=en-US&Signature=jaGkP5UiR7ijtnLmPZF1hth5xhC2yKJP4QZMyWWqIc0-p6U3iC-cilnGVg~aWh12SmYPBbCpgNutZJ85s6qK52g4DfVZMgFRvJLfrleay39JfkNGgAtScT5QwYoWooRUD4DDozR0vUtwxUlHf5Gnri0XOL3PQsWpl2L-x57oOtoLxjmrFRL2uloMeTsSo2iU8Vmq0No-d6-vdzSLGoNb5y6vnUO8WQzDVa~Giw0l9UPckl3HbbZkgICtgaENYCE3WuGhh27RGg2PpX~qLa0SVcj9LCo9Zr9-Rg8Z0FnfChMpa3WFNpErwRVbmfjriJ1~yJSMepk5Ho8c68uOhz3JHA__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00zL2NydW5jaHlyb2xsLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjE4MDU5NDB9fX1dfQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at Crunchyroll_Downloader.Einstellungen.BackgroundWorker1_DoWork(Object sender, DoWorkEventArgs e)

**Comment by cimmy01** [comment]
the download button does convert to the cancel but that is all the farther it goes

**Comment by hama3254** [comment]
For the function that gets called is nothing in the debug log, it is only available as debug popup inside the the debug mode.
> 
> to see any error message you can enable the debug messages with two double clicks on the settings icon until this messages apers :
> ![grafik](https://user-images.githubusercontent.com/52826614/119240392-7aae8400-bb4f-11eb-9cee-a8a863ab51a9.png)

Without any debug message there is no chance of guessing where it fails at your end and since it works fine for me i can not look it up myself.

**Comment by cimmy01** [comment]
I tried to redownload again and tried it and its giving me this error. 
system.nullReferenceException: object reference not set to and instance of an objec. 
at Crunchyroll_downloader.main.getbetaVideo(string Streams, String WebsiteURL)

This is the Address that I was trying

https://beta.crunchyroll.com/series/GW4HM79VM/ive-been-killing-slimes-for-300-years-and-maxed-out-my-level

**Comment by hama3254** [comment]
i guess i found the issue or at least i found a view issues ...
you can try `Crunchyroll Downloader_Beta_U4.exe` from here:
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

selecting a single episode there did not work because if was just not implemented i just don't know why.
<details>
  <summary>Old Code</summary>

  ```
 If Anime_Add.comboBox4.SelectedIndex > Anime_Add.comboBox3.SelectedIndex Then
    First = Anime_Add.comboBox3.SelectedIndex
    Last = Anime_Add.comboBox4.SelectedIndex
 ElseIf Anime_Add.comboBox4.SelectedIndex = Anime_Add.comboBox3.SelectedIndex Then
     Exit Sub
 Else
     First = Anime_Add.comboBox4.SelectedIndex
    Last = Anime_Add.comboBox4.SelectedIndex
  End If
  ```
  
</details> 

<details>
  <summary>New Code</summary>

  ```
 If Anime_Add.comboBox4.SelectedIndex > Anime_Add.comboBox3.SelectedIndex Or Anime_Add.comboBox4.SelectedIndex = Anime_Add.comboBox3.SelectedIndex Then
   First = Anime_Add.comboBox3.SelectedIndex
   Last = Anime_Add.comboBox4.SelectedIndex
  ElseIf Anime_Add.comboBox3.SelectedIndex > Anime_Add.comboBox4.SelectedIndex Then
    First = Anime_Add.comboBox4.SelectedIndex
    Last = Anime_Add.comboBox3.SelectedIndex
 End If
  ```
  
</details> 

![grafik](https://user-images.githubusercontent.com/52826614/119263573-de808d80-bbdf-11eb-9362-6225a3967bbc.png)

and the other was an issue with the `ConvertCC` function which should translate the old language code to the new one like `enUS` to `en-US` and it did exactly the opposite so it did not work with `enUS` because it was looking for `en-US` and it returned an invalid response.

**Comment by cimmy01** [comment]
I appreciate the work your doing I know it is frustrating; but I got the same message again this time after it trying to download the subtitles.

**Comment by hama3254** [comment]
The only thing that is frustrating is the lack of information you give me.
some simple things like your settings the anime and like "after it trying to download the subtitles." did it download the subs or failed it there already? 
and we have already been in the console/log there are also useful information in there.

**Comment by cimmy01** [comment]
ive given you everything its giving me it did download the subtitles but gives the error after that. Here is the log with the debugging mode turned on 
5/23/2021 2:16:18 PM.775
https://beta-api.crunchyroll.com/cms/v2/US/M3/crunchyroll/episodes?season_id=GR9PC2WG8&locale=en-US&Signature=qauXUU7eHr0gqJuQJuOV67iZ5HheYWt3TEh~7~ZlCHSoYYpzf~2efpQGy1BiEpnJw6k4~NGE42zCuD6lVBDnBdLOs09gEQ23314WTf~EOvonXVHY1gp3X4C3tXlMb8fhzzmfO1QUg5JBzgMDNrhTCGIldRE~Yw1t9I1bQSA7THNz4SV7ITV22jg~~m175WJJgU-X4~QVuASPYFA2ktxcC7yqCLYfroE~dv-xorSAggfPgwAb~iH-2JI3CfSMkXCsiHobc875NrrWLf6Env4HIV9ybNGnCy9ZUcL~DS2PElL3BQY2woVLBu5FSj6I~Y~l00agiLpa7K59swYWVjO8mg__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00zL2NydW5jaHlyb2xsLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjE4ODAxNzl9fX1dfQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
5/23/2021 2:16:26 PM.60
D:\Downloaded\Crunchy\
5/23/2021 2:16:28 PM.142
en-US
The subtitles are downloaded and I receive this error in a pop up window
**system.nullReferenceException: object reference not set to and instance of an objec.
at Crunchyroll_downloader.main.getbetaVideo(string Streams, String WebsiteURL)**
All of my settings are default I have not changed anything except the download location
This is all I know how to give you.

**Comment by hama3254** [comment]
Try the U5 version : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by cimmy01** [comment]
Error given after downloading the Subtitles in to the correct folder
System.nullReferenceException:object reference not set to an instance of an object.
    At Crunchyroll_downloader.main.getbetavidio(string Streams,string websiteurl) in d:\projecte\crunhyroll
downloder - 
v3.0-final\crunchyroll 
Downloader\main.vb:line 2273

**Comment by hama3254** [comment]
i found the issue, you use custom names which does not require the api call for the name so i was not done but in the same file are also the urls for the thumbnail so without it failed on the empty string.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by cimmy01** [comment]
That got it! Thank you very much.
