### ISSUE TITLE
Apps hanging?

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#283]
May i know why the apps is sometime freezed and hanging?

I can't even close it, had to end task.
![Capture](https://user-images.githubusercontent.com/4635825/119283369-5c3faa00-bc6f-11eb-93b3-5c1de463d379.PNG)

Left it downloading from the last night, check this morning it's freezed :(

**Comment by hama3254** [comment]
I don't know, i usually don't try to download half of crunchyroll at once.
Settings like hybrid mode and the amount of simultaneous downloads may have an impact how likely it is to freeze.

**Comment by x3inspire** [comment]
> I don't know, i usually don't try to download half of crunchyroll at once.
> Settings like hybrid mode and the amount of simultaneous downloads may have an impact how likely it is to freeze.

I think so, now using without hybird mode seem like works fine but slow downlading.

**Comment by hama3254** [comment]
I wrote the hybrid mode as good as i can i only can add an option to reduce the download threads per download.

**Comment by JanikWie** [comment]
Hey did you run it on a second computer and remoted into it?
