### ISSUE TITLE
Download stopps at 99% / 100%

### ISSUE THREAD

**Issue by LTech77** [hama3254/Crunchyroll-Downloader-v3.0#286]
Enter your version below, it can be found in the "About" section of the settings.
Version : 
3.7.8.6
Please provide a logfile or text.
[Wanna be the Strongest in the World Episode 7 Die Weltmeisterin kommt nach Japan.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6577916/Wanna.be.the.Strongest.in.the.World.Episode.7.Die.Weltmeisterin.kommt.nach.Japan.log)

I tried downloding this anime from AOD https://www.anime-on-demand.de/anime/292. The first 6 Eps as Dub has downloded without a problem. But Eps 7-12 didn't worked. I tried other Versions (Beta 3.8 too), and with re-encoding and without (-c copy).
After that I tried downloading other Animes without a problem so far.

**Comment by hama3254** [comment]
Welche version des downloaders sollte in dem fall egal sein, alle neueren haben ffmpeg 4.3.1 dabei.
Interessanterweise ist im Log nichts zu sehen, beim testen aber merke ich das er für ca 10 Minuten hängt weil er auf eine antwort wartet.
Da kann ich nichts machen, vlt den `Hybrid Mode` mal versuchen der Cached die Dateien bevor sie vom ffmpeg Prozess verarbeitet werden. 

```
01.06.2021 19:46:35 [https @ 0765a780] Opening '177.ts' for reading
01.06.2021 19:48:05 [https @ 07759180] HTTP error 504 Gateway Time-out
```
```
01.06.2021 19:56:10 [hls @ 06b1e240] Opening '177.ts' for reading
01.06.2021 19:57:40 [https @ 0766f980] HTTP error 504 Gateway Time-out
01.06.2021 19:57:40 [hls @ 06b1e240] Failed to open segment 177 of playlist 0
```

**Comment by LTech77** [comment]
Beim Hybrid Mode hingegen habe ich leider das Problem das die Dateien beschädigt sind bzw. in einer falsche reinfolge.
