### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by proall** [hama3254/Crunchyroll-Downloader-v3.0#287]
Can i speed up the download?

**Comment by proall** [comment]
i tried hybrid mode btw

**Comment by hama3254** [comment]
The hybrid mode should increase the speed drastically due to multi threading, this is however bound on the CPU to not overwhelm older systems.
If that does not bring the desired effect then i can't help any further.

**Comment by LTech77** [comment]
Have you done a speed test?
