### ISSUE TITLE
I can't change the value "Simultaneous Downloads"

### ISSUE THREAD

**Issue by orezraey** [hama3254/Crunchyroll-Downloader-v3.0#291]
Everytime that I try to change this value and I press "Save & Exit", I open configs again and the value not change. Basically, I can't download more than one file per once.

**Comment by MSI-Toby** [comment]
In your registry, what is the value of the following key? You could manually set it to 1.

HKEY_CURRENT_USER\SOFTWARE\CRDownloader\QueueMode
![image](https://user-images.githubusercontent.com/11889553/121267982-44287700-c87a-11eb-858c-bc707b4eb82b.png)
