### ISSUE TITLE
can't download 2 episodes of a series

### ISSUE THREAD

**Issue by LTech77** [hama3254/Crunchyroll-Downloader-v3.0#294]
Enter your version below, it can be found in the "About" section of the settings.
Version :  v3.7.8.6

Hallo Hama, mal eine kurze Frage soll ich solche Probleme lieber über GitHub lösen oder über Discord? Was wäre dir in zukunft lieber?
Also zum Problem. Ich habe versucht diese Serie von Crunchyroll zu Downloaden: https://www.crunchyroll.com/de/my-mental-choices-are-completely-interfering-with-my-school-romantic-comedy. Die Serie lies sich soweit ohne Probleme herunterladen bis auf Folgen 4 und 9. Dort ist der Download Prozess direkt gecrasht.  Ein Log file kann ich gar nicht normal erstellen, da bekomme ich immer eine Fehlermeldung.
![image](https://user-images.githubusercontent.com/83650927/121918033-f6a68100-cd35-11eb-8956-8694fe857739.png)
Über copy to clipboard hingegen klappt es.
[Log4.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6649536/Log4.txt)
[Log9.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6649537/Log9.txt)
Ich denke mal das es an der Zeichenbeschränkung in Windows liegt um Sachen zu benenne.
Vielleicht hast du ja eine Idee.
Achso nur so als Zusatz Info. Ich benutze die Beta 3.8 nicht da dort die Folgen nicht mehr mit benannt werden. Aber AMD GPU Encoding funktioniert auch trotzdem mit der älteren Version da eine config geteilt wird.
Update: Beta v3.8 und (AMD-version) funktionieren auch nicht.

**Comment by hama3254** [comment]
> Hallo Hama, mal eine kurze Frage soll ich solche Probleme lieber über GitHub lösen oder über Discord? Was wäre dir in zukunft lieber?

Das ist mir eigentlich egal, mach in Zukunft was für dich leichter ist.

>  Ein Log file kann ich gar nicht normal erstellen, da bekomme ich immer eine Fehlermeldung.

beides mal der selbe Fehler und zwar genau der

>Ich denke mal das es an der Zeichenbeschränkung in Windows liegt um Sachen zu benenne.

versuch mal auf nur Nummer umzuschalten, Folge 4 und 9 haben schon abnormal lange Episoden titel
![grafik](https://user-images.githubusercontent.com/52826614/121934156-3aee4d00-cd47-11eb-89a5-86ae74d8d937.png)

> Achso nur so als Zusatz Info. Ich benutze die Beta 3.8 nicht da dort die Folgen nicht mehr mit benannt werden

Das kann ich leider nicht nachvollziehen gerade, bei mir siehst gut aus.
![grafik](https://user-images.githubusercontent.com/52826614/121933770-c87d6d00-cd46-11eb-96c9-585731992457.png)


>Encoding funktioniert auch trotzdem mit der älteren Version da eine config geteilt wird. 

durchaus möglich davon würde ich dennoch abraten und den rat `prepare for unforeseen consequences` mitgeben. 

>Update: Beta v3.8 und (AMD-version) funktionieren auch nicht.

Da bräuchte ich ne etwas genauere Beschreibung, ist es das selbe Problem das er nichts downloadet oder die Zusatz Info von oben 

> Achso nur so als Zusatz Info. Ich benutze die Beta 3.8 nicht da dort die Folgen nicht mehr mit benannt werden

**Comment by LTech77** [comment]
> Achso nur so als Zusatz Info. Ich benutze die Beta 3.8 nicht da dort die Folgen nicht mehr mit benannt werden
>Das kann ich leider nicht nachvollziehen gerade, bei mir siehst gut aus.

Ich habe das ganze bei Crunchyroll glaube ich noch nie probiert aber bei AOD trat das Problem auf.
>Update: Beta v3.8 und (AMD-version) funktionieren auch nicht.
>Da bräuchte ich ne etwas genauere Beschreibung, ist es das selbe Problem das er nichts downloadet oder die Zusatz Info von oben

Dort ist das gleiche Problem das er nicht Downloaded (Bei gleichen Einstellungen)
Ich werde gleich mal den Tipp ausprobieren und den Folgen Titel deaktivieren.

**Comment by LTech77** [comment]
Gerade alles ausprobiert und hat problemlos geklappt.

**Comment by hama3254** [comment]
> Gerade alles ausprobiert und hat problemlos geklappt.

wenn nichts weiter aufgefallen ist mach hier mal zu
