### ISSUE TITLE
Crunchyroll fonts

### ISSUE THREAD

**Issue by proall** [hama3254/Crunchyroll-Downloader-v3.0#295]
Hey,
Can you make option to download the fonts too with the subtitles?
I mean i saw someone with .mp4 that had in the fonts with the subs from crunchyroll.

And if you can make a non GUI version, i'm wanna make a script that using your download to download when episode get publish.

**Comment by MSI-Toby** [comment]
It doesn't appear (to me) that CR supplies font files with their videos. The only reference to a specific font that I can find is to Lato Medium (https://fonts.google.com/specimen/Lato). You'll have to use MKVmerge or FFmpeg to deal with it after the fact.

CLI is addressed in issue #228.

**Comment by proall** [comment]
@MSI-Toby 
Hey, thank you for the reply.
Here you can see there is a fonts attach on .mkv.

[Ijiranaide, Nagatoro-san - 10 HD.mkv.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6672597/Ijiranaide.Nagatoro-san.-.10.HD.mkv.txt)

**Comment by proall** [comment]
Attachments                 : Roboto-Medium.ttf / Roboto-MediumItalic.ttf / arial.ttf / arialbd.ttf / comic.ttf / comicbd.ttf / times.ttf / timesbd.ttf / trebuc.ttf / trebucbd.ttf / verdana.ttf / verdanab.ttf

**Comment by MSI-Toby** [comment]
That looks like work that someone did to add to the file. CR uses VTT, which is normally restricted to websafe fonts. Those fonts you have listed are easily available and don't really need to be embedded. If you are worried about archival and compatibly, you may want to consider PGS to reduce issues.

https://fonts.google.com/specimen/Roboto
https://docs.microsoft.com/en-us/typography/font-list/arial
https://docs.microsoft.com/en-us/typography/font-list/comic-sans-ms
https://catalog.monotype.com/family/monotype/times-new-roman
https://docs.microsoft.com/en-us/typography/font-list/trebuchet-ms
https://docs.microsoft.com/en-us/typography/font-list/verdana

**Comment by proall** [comment]
Thank you so much!
@MSI-Toby

**Comment by hama3254** [comment]
Crunchyroll uses `Trebuchet MS` as font for subs which should be a default windows font that can be found in the `C:\Windows\Fonts` folder.
![grafik](https://user-images.githubusercontent.com/52826614/122650941-f3e0cd00-d135-11eb-95d8-9cc50f81ed68.png)

![grafik](https://user-images.githubusercontent.com/52826614/122650757-eaa33080-d134-11eb-8f88-1ef87b4eff0f.png)

**Comment by Funami580** [comment]
> It doesn't appear (to me) that CR supplies font files with their videos.

They do. But they load the fonts externally, they are not included in the video. You can find the default list of fonts in the `bundle.js` file.

```
{"Adobe Arabic":"AdobeArabic-Bold.woff2","Andale Mono":"andalemo.woff2",Arial:"arial.woff2","Arial Bold":"arialbd.woff2","Arial Bold Italic":"arialbi.woff2","Arial Italic":"ariali.woff2","Arial Unicode MS":"arialuni.woff2","Arial Black":"ariblk.woff2","Comic Sans MS":"comic.woff2","Comic Sans MS Bold":"comicbd.woff2","Courier New":"cour.woff2","Courier New Bold":"courbd.woff2","Courier New Bold Italic":"courbi.woff2","Courier New Italic":"couri.woff2",default:"default.woff2","DejaVu LGC Sans Mono Bold":"DejaVuLGCSansMono-Bold.woff2","DejaVu LGC Sans Mono Bold Oblique":"DejaVuLGCSansMono-BoldOblique.woff2","DejaVu LGC Sans Mono Oblique":"DejaVuLGCSansMono-Oblique.woff2","DejaVu LGC Sans Mono":"DejaVuLGCSansMono.woff2","DejaVu Sans Bold":"DejaVuSans-Bold.woff2","DejaVu Sans Bold Oblique":"DejaVuSans-BoldOblique.woff2","DejaVu Sans ExtraLight":"DejaVuSans-ExtraLight.woff2","DejaVu Sans Oblique":"DejaVuSans-Oblique.woff2","DejaVu Sans":"DejaVuSans.woff2","DejaVu Sans Condensed Bold":"DejaVuSansCondensed-Bold.woff2","DejaVu Sans Condensed Bold Oblique":"DejaVuSansCondensed-BoldOblique.woff2","DejaVu Sans Condensed Oblique":"DejaVuSansCondensed-Oblique.woff2","DejaVu Sans Condensed":"DejaVuSansCondensed.woff2","DejaVu Sans Mono Bold":"DejaVuSansMono-Bold.woff2","DejaVu Sans Mono Bold Oblique":"DejaVuSansMono-BoldOblique.woff2","DejaVu Sans Mono Oblique":"DejaVuSansMono-Oblique.woff2","DejaVu Sans Mono":"DejaVuSansMono.woff2",Georgia:"georgia.woff2","Georgia Bold":"georgiab.woff2","Georgia Italic":"georgiai.woff2","Georgia Bold Italic":"georgiaz.woff2",Impact:"impact.woff2","Rubik Black":"Rubik-Black.woff2","Rubik Black Italic":"Rubik-BlackItalic.woff2","Rubik Bold":"Rubik-Bold.woff2","Rubik Bold Italic":"Rubik-BoldItalic.woff2","Rubik Italic":"Rubik-Italic.woff2","Rubik Light":"Rubik-Light.woff2","Rubik Light Italic":"Rubik-LightItalic.woff2","Rubik Medium":"Rubik-Medium.woff2","Rubik Medium Italic":"Rubik-MediumItalic.woff2",Rubik:"Rubik-Regular.woff2",Tahoma:"tahoma.woff2","Times New Roman":"times.woff2","Times New Roman Bold":"timesbd.woff2","Times New Roman Bold Italic":"timesbi.woff2","Times New Roman Italic":"timesi.woff2","Trebuchet MS":"trebuc.woff2","Trebuchet MS Bold":"trebucbd.woff2","Trebuchet MS Bold Italic":"trebucbi.woff2","Trebuchet MS Italic":"trebucit.woff2",Verdana:"verdana.woff2","Verdana Bold":"verdanab.woff2","Verdana Italic":"verdanai.woff2","Verdana Bold Italic":"verdanaz.woff2",Webdings:"webdings.woff2"}
```

With this information, you can directly access every font file:
Arial: https://static.crunchyroll.com/vilos-v2/web/vilos/assets/libass-fonts/arial.woff2

One should check the subtitle file though, so not every file is downloaded:
```
[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H7F404040,-1,0,0,0,100,100,0,0,1,2,1,2,0020,0020,0022,0
Style: On Top,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H7F404040,-1,0,0,0,100,100,0,0,1,2,1,8,0020,0020,0022,0
Style: Italics,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H7F404040,-1,-1,0,0,100,100,0,0,1,2,1,2,0020,0020,0022,0
Style: next,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H7F404040,-1,0,0,0,100,100,0,0,1,2,1,7,0050,0020,0090,0
```
For this one, Arial would be enough. Afterwards, the fonts just have to be merged into an MKV file.

**Comment by hama3254** [comment]
I guess everything is said here since such an option will not be added from my side.
