### ISSUE TITLE
When I go in settings output 

### ISSUE THREAD

**Issue by malzen** [hama3254/Crunchyroll-Downloader-v3.0#298]
When I go in settings output and change present from fast to slow then click save and exit. Then went back and checked and goes back to fast present.

Could you fix this please.

**Comment by MSI-Toby** [comment]
Not a fix, but you can add '-preset slow' to the following key. I would suggest recompressing outside the app since it will pretty slow and you can get better optimizations by doing FFmpeg (or Handbrake) yourself.

HKEY_CURRENT_USER\SOFTWARE\CRDownloader\ffmpeg_command
![image](https://user-images.githubusercontent.com/11889553/121267982-44287700-c87a-11eb-858c-bc707b4eb82b.png)

**Comment by hama3254** [comment]
> When I go in settings output and change present from fast to slow then click save and exit. Then went back and checked and goes back to fast present.
> 
> Could you fix this please.

What ffmpeg command are you using at the first selection?

**Comment by malzen** [comment]
At first section the default is present fast.

**Comment by hama3254** [comment]
> At first section the default is present fast.

I mean the first part of the command like `-c copy`

**Comment by hama3254** [comment]
i found the issue fix is coming soon

**Comment by hama3254** [comment]
`Crunchyroll-Downloader-v3.8-Beta-U9` should fix this issue.

**Comment by malzen** [comment]
> > At first section the default is present fast.
> 
> I mean the first part of the command like `-c copy`

-c copy -present fast -b:v 7000k

Present fast is default. I want to change from fast to slow.

**Comment by malzen** [comment]
The new verison does not if the issue as you can not change the present to slow instead of fast.

**Comment by hama3254** [comment]
> 
> 
> > > At first section the default is present fast.
> > 
> > 
> > I mean the first part of the command like `-c copy`
> 
> -c copy -present fast -b:v 7000k
> 
> Present fast is default. I want to change from fast to slow.

the option is not saved because it is not in use with `-c copy`.

**Comment by malzen** [comment]
So what can I do then

**Comment by hama3254** [comment]
> So what can I do then

I'm not sure what you even want to do.
If you want to use `-c copy` then you should not even be able to select any present because `copy` has no conversation presents since it is no conversation.

**Comment by hama3254** [comment]
the issue that the ffmpeg command was not has been solved and `-c copy` works as intended since it does not need or support any presets the default gets displayed.
