### ISSUE TITLE
Dev Version US Cookie ist noch Schlechter.

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#3]
Die von dir "gefixte" Dev version der US Cookie funktioniert noch seltener als bei der OG 3.0.1 Release Version.
-
Vielleicht hast du im Code was vertudelt, guck nochmal rein ^^

**Comment by hama3254** [comment]
> ## Die von dir "gefixte" Dev version der US Cookie funktioniert noch seltener als bei der OG 3.0.1 Release Version.
> Vielleicht hast du im Code was vertudelt, guck nochmal rein ^^
als ich es getestet hab hat's funktioniert 🤷.
Habs mal auf JavsScript umgestellt versuch jetzt mal dein Glück:
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/3.x
