### ISSUE TITLE
After error with downloading video, click on pause icon will create stacktrace

### ISSUE THREAD

**Issue by Manicraft1001** [hama3254/Crunchyroll-Downloader-v3.0#30]
After the application automatically reported an unexpected error with the download of an video, a simple click on the pause
icon will produce a stacktrace. Might be an unwanted access to an closed thread?
This error might be a result from the first reported issue?

[Click here to get the stacktrace](https://ghostbin.co/paste/od85neb7)
Password to get access: 2472482472

Windows 10, AMD x86

**Comment by hama3254** [comment]
This is an error in the code, i did not check for finished/crashed processes and well you can not access something that not exist anymore. 

> This error might be a result from the first reported issue?

that depents if you tryed to download "Re:ZERO Folge 25" then the report from 04.07.20, 22:18 might be your's:

>System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> >System.Net.Sockets.SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten >Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat >[some CR IPv4 adress]
>   bei System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket

wich means no the error are not directly related.

**Comment by Manicraft1001** [comment]
Yes, the report is mine.
It might occured, because i was not only downloading crunchy videos,
i was downloading different things synchrounously, so my ping rised (error looks like a timeout issue, right?).

**Comment by hama3254** [comment]
> 
> 
> Yes, the report is mine.
> It might occured, because i was not only downloading crunchy videos,
> i was downloading different things synchrounously, so my ping rised (error looks like a timeout issue, right?).

that is possible.

> 
> 
> This is an error in the code, i did not check for finished/crashed processes and well you can not access something that not exist anymore.

i added the check if the process has exited and also added a retry function.
