### ISSUE TITLE
Unable to download anything from Crunchyroll Beta

### ISSUE THREAD

**Issue by Rule665** [hama3254/Crunchyroll-Downloader-v3.0#300]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.8 Beta U9

Video no longer loads in the browser for any show through Crunchyroll Beta.

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>
  <summary>Insert the logtext before the second details</summary>
6/21/2021 9:11:23 PM -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/index-v1-a1.m3u8?Expires=1624497084&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lNmUxNmNhZmRmNjRkNjVkZGEwZTkwMDk0NmVjOThmYi9hc3NldHMvODRlOGJmYTA3YWQ4NThiNWUwYjdmYmIyOTdiZjgwZDVfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjQ0OTcwODR9fX1dfQ__&Signature=ZLj-v5KLAQGl5mULXo~dVU99MvQed8ot1biDiKYpJbbS09F3drSKhQmsEfERkrl2APymy70El0nlGofSMkCZ0ojd-UaV~QwRXr26nOJ85jk0YowURwILAC8l~xe~D8Hh7T6Fm-VPuqNifI6mg~a-p2tGX1HN~6G2F-r-rm3dK5QxSLCk~3XD-~yaZOV0ZpRmJNehbsvBu5bsStrUQ~et6YBKsFTkdYa46-5EBRIHxVKleB02hQ2pcSnNFXD6UQaF3ICSuwhOpfAnYisUBrH3EmyRbwcsx6858~XWTZzmsgvLMAG9Jlx6lIon6bHCDlo1J8bosogmul9MgWLOvd9cwA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=vcdn-prod" -map 0:v -map 0:a  -c copy -c:a copy -bsf:a aac_adtstoasc -c:s mov_text -metadata:s:a:0 language=jpn F:\\To Your Eternity Episode 11.mp4

6/21/2021 9:11:24 PM ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
6/21/2021 9:11:24 PM   built with gcc 10.2.1 (GCC) 20200726
6/21/2021 9:11:24 PM   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
6/21/2021 9:11:24 PM   libavutil      56. 51.100 / 56. 51.100
6/21/2021 9:11:24 PM   libavcodec     58. 91.100 / 58. 91.100
6/21/2021 9:11:24 PM   libavformat    58. 45.100 / 58. 45.100
6/21/2021 9:11:24 PM   libavdevice    58. 10.100 / 58. 10.100
6/21/2021 9:11:24 PM   libavfilter     7. 85.100 /  7. 85.100
6/21/2021 9:11:24 PM   libswscale      5.  7.100 /  5.  7.100
6/21/2021 9:11:24 PM   libswresample   3.  7.100 /  3.  7.100
6/21/2021 9:11:24 PM   libpostproc    55.  7.100 / 55.  7.100
6/21/2021 9:11:24 PM [https @ 06d1f3c0] The "user-agent" option is deprecated: use the "user_agent" option instead
6/21/2021 9:11:24 PM [https @ 0554d6c0] No trailing CRLF found in HTTP header. Adding it.
6/21/2021 9:11:24 PM [hls @ 06d1ee00] Skip ('#EXT-X-ALLOW-CACHE:YES')
6/21/2021 9:11:24 PM [hls @ 06d1ee00] Skip ('#EXT-X-VERSION:5')
6/21/2021 9:11:24 PM [hls @ 06d1ee00] Opening 'https://vc.v.vrv.co/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/encryption.key?t=exp=1624497085~acl=/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/*~hmac=334ffb1109572a55172e88c6a28e2b37601e9f57b131a1adf102230f04bd1149' for reading
6/21/2021 9:11:24 PM [hls @ 06d1ee00] Opening 'crypto+https://vc.v.vrv.co/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/seg-1-v1-a1.ts?t=exp=1624497085~acl=/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/*~hmac=334ffb1109572a55172e88c6a28e2b37601e9f57b131a1adf102230f04bd1149' for reading
6/21/2021 9:11:24 PM Input #0, hls, from 'https://pl.crunchyroll.com/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/index-v1-a1.m3u8?Expires=1624497084&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lNmUxNmNhZmRmNjRkNjVkZGEwZTkwMDk0NmVjOThmYi9hc3NldHMvODRlOGJmYTA3YWQ4NThiNWUwYjdmYmIyOTdiZjgwZDVfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjQ0OTcwODR9fX1dfQ__&Signature=ZLj-v5KLAQGl5mULXo~dVU99MvQed8ot1biDiKYpJbbS09F3drSKhQmsEfERkrl2APymy70El0nlGofSMkCZ0ojd-UaV~QwRXr26nOJ85jk0YowURwILAC8l~xe~D8Hh7T6Fm-VPuqNifI6mg~a-p2tGX1HN~6G2F-r-rm3dK5QxSLCk~3XD-~yaZOV0ZpRmJNehbsvBu5bsStrUQ~et6YBKsFTkdYa46-5EBRIHxVKleB02hQ2pcSnNFXD6UQaF3ICSuwhOpfAnYisUBrH3EmyRbwcsx6858~XWTZzmsgvLMAG9Jlx6lIon6bHCDlo1J8bosogmul9MgWLOvd9cwA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=vcdn-prod':
6/21/2021 9:11:24 PM   Duration: 00:25:00.04, start: 0.101000, bitrate: 0 kb/s
6/21/2021 9:11:24 PM   Program 0 
6/21/2021 9:11:24 PM     Metadata:
6/21/2021 9:11:24 PM       variant_bitrate : 0
6/21/2021 9:11:24 PM     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
6/21/2021 9:11:24 PM     Metadata:
6/21/2021 9:11:24 PM       variant_bitrate : 0
6/21/2021 9:11:24 PM     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
6/21/2021 9:11:24 PM     Metadata:
6/21/2021 9:11:24 PM       variant_bitrate : 0
6/21/2021 9:11:24 PM     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
6/21/2021 9:11:24 PM     Metadata:
6/21/2021 9:11:24 PM       variant_bitrate : 0
6/21/2021 9:11:24 PM [NULL @ 07d77040] Unable to find a suitable output format for 'F:\\To'
6/21/2021 9:11:24 PM F:\\To: Invalid argument
6/21/2021 9:11:24 PM 
6/21/2021 9:11:24 PM 
6/21/2021 9:14:22 PM -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/index-v1-a1.m3u8?Expires=1624497084&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lNmUxNmNhZmRmNjRkNjVkZGEwZTkwMDk0NmVjOThmYi9hc3NldHMvODRlOGJmYTA3YWQ4NThiNWUwYjdmYmIyOTdiZjgwZDVfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjQ0OTcwODR9fX1dfQ__&Signature=ZLj-v5KLAQGl5mULXo~dVU99MvQed8ot1biDiKYpJbbS09F3drSKhQmsEfERkrl2APymy70El0nlGofSMkCZ0ojd-UaV~QwRXr26nOJ85jk0YowURwILAC8l~xe~D8Hh7T6Fm-VPuqNifI6mg~a-p2tGX1HN~6G2F-r-rm3dK5QxSLCk~3XD-~yaZOV0ZpRmJNehbsvBu5bsStrUQ~et6YBKsFTkdYa46-5EBRIHxVKleB02hQ2pcSnNFXD6UQaF3ICSuwhOpfAnYisUBrH3EmyRbwcsx6858~XWTZzmsgvLMAG9Jlx6lIon6bHCDlo1J8bosogmul9MgWLOvd9cwA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=vcdn-prod" -map 0:v -map 0:a  -c copy -c:a copy -bsf:a aac_adtstoasc -c:s mov_text -metadata:s:a:0 language=jpn F:\\To Your Eternity Episode 11.mp4
6/21/2021 9:14:23 PM ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
6/21/2021 9:14:23 PM   built with gcc 10.2.1 (GCC) 20200726
6/21/2021 9:14:23 PM   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
6/21/2021 9:14:23 PM   libavutil      56. 51.100 / 56. 51.100
6/21/2021 9:14:23 PM   libavcodec     58. 91.100 / 58. 91.100
6/21/2021 9:14:23 PM   libavformat    58. 45.100 / 58. 45.100
6/21/2021 9:14:23 PM   libavdevice    58. 10.100 / 58. 10.100
6/21/2021 9:14:23 PM   libavfilter     7. 85.100 /  7. 85.100
6/21/2021 9:14:23 PM   libswscale      5.  7.100 /  5.  7.100
6/21/2021 9:14:23 PM   libswresample   3.  7.100 /  3.  7.100
6/21/2021 9:14:23 PM   libpostproc    55.  7.100 / 55.  7.100
6/21/2021 9:14:23 PM [https @ 071bf3c0] The "user-agent" option is deprecated: use the "user_agent" option instead
6/21/2021 9:14:23 PM [https @ 055bd6c0] No trailing CRLF found in HTTP header. Adding it.
6/21/2021 9:14:23 PM [hls @ 071bee00] Skip ('#EXT-X-ALLOW-CACHE:YES')
6/21/2021 9:14:23 PM [hls @ 071bee00] Skip ('#EXT-X-VERSION:5')
6/21/2021 9:14:23 PM [hls @ 071bee00] Opening 'https://vc.v.vrv.co/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/encryption.key?t=exp=1624497264~acl=/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/*~hmac=f5abc9d6d03338fe4f7cca6614677b3e2fcc20dd90e4cdd9a6dbece8dd77d5d7' for reading
6/21/2021 9:14:23 PM [hls @ 071bee00] Opening 'crypto+https://vc.v.vrv.co/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/seg-1-v1-a1.ts?t=exp=1624497264~acl=/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/*~hmac=f5abc9d6d03338fe4f7cca6614677b3e2fcc20dd90e4cdd9a6dbece8dd77d5d7' for reading
6/21/2021 9:14:24 PM Input #0, hls, from 'https://pl.crunchyroll.com/evs1/e6e16cafdf64d65dda0e900946ec98fb/assets/84e8bfa07ad858b5e0b7fbb297bf80d5_4092103.mp4/index-v1-a1.m3u8?Expires=1624497084&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9lNmUxNmNhZmRmNjRkNjVkZGEwZTkwMDk0NmVjOThmYi9hc3NldHMvODRlOGJmYTA3YWQ4NThiNWUwYjdmYmIyOTdiZjgwZDVfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjQ0OTcwODR9fX1dfQ__&Signature=ZLj-v5KLAQGl5mULXo~dVU99MvQed8ot1biDiKYpJbbS09F3drSKhQmsEfERkrl2APymy70El0nlGofSMkCZ0ojd-UaV~QwRXr26nOJ85jk0YowURwILAC8l~xe~D8Hh7T6Fm-VPuqNifI6mg~a-p2tGX1HN~6G2F-r-rm3dK5QxSLCk~3XD-~yaZOV0ZpRmJNehbsvBu5bsStrUQ~et6YBKsFTkdYa46-5EBRIHxVKleB02hQ2pcSnNFXD6UQaF3ICSuwhOpfAnYisUBrH3EmyRbwcsx6858~XWTZzmsgvLMAG9Jlx6lIon6bHCDlo1J8bosogmul9MgWLOvd9cwA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=vcdn-prod':
6/21/2021 9:14:24 PM   Duration: 00:25:00.04, start: 0.101000, bitrate: 0 kb/s
6/21/2021 9:14:24 PM   Program 0 
6/21/2021 9:14:24 PM     Metadata:
6/21/2021 9:14:24 PM       variant_bitrate : 0
6/21/2021 9:14:24 PM     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
6/21/2021 9:14:24 PM     Metadata:
6/21/2021 9:14:24 PM       variant_bitrate : 0
6/21/2021 9:14:24 PM     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
6/21/2021 9:14:24 PM     Metadata:
6/21/2021 9:14:24 PM       variant_bitrate : 0
6/21/2021 9:14:24 PM     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
6/21/2021 9:14:24 PM     Metadata:
6/21/2021 9:14:24 PM       variant_bitrate : 0
6/21/2021 9:14:24 PM [NULL @ 07de7040] Unable to find a suitable output format for 'F:\\To'
6/21/2021 9:14:24 PM F:\\To: Invalid argument
6/21/2021 9:14:24 PM 
6/21/2021 9:14:24 PM     
</details>

**Comment by hama3254** [comment]
The video does not need to load since you don't need to use the `network scan` for crunchyroll, funimation or anime on demand.
If you use the `Add Video` form it should work fine.

Did you get the log file with the `network scan` since it even found the video and just the path generator seems broken.
