### ISSUE TITLE
"The download process seems to have crashed" 

### ISSUE THREAD

**Issue by pcprogamer** [hama3254/Crunchyroll-Downloader-v3.0#305]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.8 Beta U8

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>6/25/2021 9:34:28 AM -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs1/53560b584b1381c3daf14ce07b8ae9a6/assets/6ba0da54807bae91ef9f260d4aaa1938_4027683.mp4/index-v1-a1.m3u8?Expires=1624800869&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS81MzU2MGI1ODRiMTM4MWMzZGFmMTRjZTA3YjhhZTlhNi9hc3NldHMvNmJhMGRhNTQ4MDdiYWU5MWVmOWYyNjBkNGFhYTE5MzhfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjQ4MDA4Njl9fX1dfQ__&Signature=EwX4LEIaZoZplJf1xM4VYb76vdaQYBTLA6jegIoX0AHql49D433G1sSWPfHVPjhhMzluVM6mTXmmRo3G-DMrhRbvyv~uENLCO7IIg6MUkfTccGJpKKo9e8alMzo0ybAcUfMugbOH4kXL0o9~CIYsrBYOa010tYU3CE3ptINnH1nZdSQsEYSP0J5TgvsjWDZjsitC9PZX8grVKKmdO8azKh7kVwQO~4rig34y2q9VR~2mOvYKudTWKRQKKjEYVnSECeokejGHqZP3LKbxtjTpbg~lU~DT9q3OmvdvwnyNUksZdt8rjM51wdl3bHXwQPPfDbRL1gjoRJXDF2Yj0poPNA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=vcdn-prod" -metadata:s:a:0 language=jpn  -c copy -c:a copy -bsf:a aac_adtstoasc D:\\I've Been Killing Slimes For 300 Years And Maxed Out My Level Episode 1.mp4

6/25/2021 9:34:29 AM ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
6/25/2021 9:34:29 AM   built with gcc 10.2.1 (GCC) 20200726
6/25/2021 9:34:29 AM   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
6/25/2021 9:34:29 AM   libavutil      56. 51.100 / 56. 51.100
6/25/2021 9:34:29 AM   libavcodec     58. 91.100 / 58. 91.100
6/25/2021 9:34:29 AM   libavformat    58. 45.100 / 58. 45.100
6/25/2021 9:34:29 AM   libavdevice    58. 10.100 / 58. 10.100
6/25/2021 9:34:29 AM   libavfilter     7. 85.100 /  7. 85.100
6/25/2021 9:34:29 AM   libswscale      5.  7.100 /  5.  7.100
6/25/2021 9:34:29 AM   libswresample   3.  7.100 /  3.  7.100
6/25/2021 9:34:29 AM   libpostproc    55.  7.100 / 55.  7.100
6/25/2021 9:34:29 AM [https @ 0710fd40] The "user-agent" option is deprecated: use the "user_agent" option instead
6/25/2021 9:34:29 AM [https @ 07104bc0] No trailing CRLF found in HTTP header. Adding it.
6/25/2021 9:34:29 AM [hls @ 0710f7c0] Skip ('#EXT-X-ALLOW-CACHE:YES')
6/25/2021 9:34:29 AM [hls @ 0710f7c0] Skip ('#EXT-X-VERSION:5')
6/25/2021 9:34:29 AM [hls @ 0710f7c0] Opening 'https://vc.v.vrv.co/evs1/53560b584b1381c3daf14ce07b8ae9a6/assets/6ba0da54807bae91ef9f260d4aaa1938_4027683.mp4/encryption.key?t=exp=1624800871~acl=/evs1/53560b584b1381c3daf14ce07b8ae9a6/assets/6ba0da54807bae91ef9f260d4aaa1938_4027683.mp4/*~hmac=ace4a27410bb4528957d7ea7301f7c687d53dc4842d8768fce74461db9513f9b' for reading
6/25/2021 9:34:29 AM [hls @ 0710f7c0] Opening 'crypto+https://vc.v.vrv.co/evs1/53560b584b1381c3daf14ce07b8ae9a6/assets/6ba0da54807bae91ef9f260d4aaa1938_4027683.mp4/seg-1-v1-a1.ts?t=exp=1624800871~acl=/evs1/53560b584b1381c3daf14ce07b8ae9a6/assets/6ba0da54807bae91ef9f260d4aaa1938_4027683.mp4/*~hmac=ace4a27410bb4528957d7ea7301f7c687d53dc4842d8768fce74461db9513f9b' for reading
6/25/2021 9:34:29 AM Input #0, hls, from 'https://pl.crunchyroll.com/evs1/53560b584b1381c3daf14ce07b8ae9a6/assets/6ba0da54807bae91ef9f260d4aaa1938_4027683.mp4/index-v1-a1.m3u8?Expires=1624800869&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS81MzU2MGI1ODRiMTM4MWMzZGFmMTRjZTA3YjhhZTlhNi9hc3NldHMvNmJhMGRhNTQ4MDdiYWU5MWVmOWYyNjBkNGFhYTE5MzhfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MjQ4MDA4Njl9fX1dfQ__&Signature=EwX4LEIaZoZplJf1xM4VYb76vdaQYBTLA6jegIoX0AHql49D433G1sSWPfHVPjhhMzluVM6mTXmmRo3G-DMrhRbvyv~uENLCO7IIg6MUkfTccGJpKKo9e8alMzo0ybAcUfMugbOH4kXL0o9~CIYsrBYOa010tYU3CE3ptINnH1nZdSQsEYSP0J5TgvsjWDZjsitC9PZX8grVKKmdO8azKh7kVwQO~4rig34y2q9VR~2mOvYKudTWKRQKKjEYVnSECeokejGHqZP3LKbxtjTpbg~lU~DT9q3OmvdvwnyNUksZdt8rjM51wdl3bHXwQPPfDbRL1gjoRJXDF2Yj0poPNA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=vcdn-prod':
6/25/2021 9:34:29 AM   Duration: 00:23:40.08, start: 0.101000, bitrate: 0 kb/s
6/25/2021 9:34:29 AM   Program 0 
6/25/2021 9:34:29 AM     Metadata:
6/25/2021 9:34:29 AM       variant_bitrate : 0
6/25/2021 9:34:29 AM     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
6/25/2021 9:34:29 AM     Metadata:
6/25/2021 9:34:29 AM       variant_bitrate : 0
6/25/2021 9:34:29 AM     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
6/25/2021 9:34:29 AM     Metadata:
6/25/2021 9:34:29 AM       variant_bitrate : 0
6/25/2021 9:34:29 AM     Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
6/25/2021 9:34:29 AM     Metadata:
6/25/2021 9:34:29 AM       variant_bitrate : 0
6/25/2021 9:34:29 AM [NULL @ 07a6b100] Unable to find a suitable output format for 'D:\\I've'
6/25/2021 9:34:29 AM D:\\I've: Invalid argument
6/25/2021 9:34:29 AM 
6/25/2021 9:34:29 AM 
  <summary>Insert the logtext before the second details</summary>
    
</details> Not able to download anything at all.

**Comment by hama3254** [comment]
It seems to me that the subfolder creation had failed for you and the error handling is missing some `"`. 
Please try to disable the subfolder setting and try the download with a valid folder selected.

**Comment by hama3254** [comment]
i released update 10 for the 3.8-Beta which should fix the missing `"` but i can not tell why the folder has not been created but i guess it's an permissions error from windows so i would recommend to use not directly the drive as path but a Folder on that drive.   

https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by hama3254** [comment]
If there is no feedback then i can close this here.
You can open a new issue at any time.
