### ISSUE TITLE
dont download video in funimation

### ISSUE THREAD

**Issue by feren6190** [hama3254/Crunchyroll-Downloader-v3.0#306]
i dont download video in funimation please repair this error
![Captura](https://user-images.githubusercontent.com/86535486/123524981-67815d80-d693-11eb-8ac1-f3f1efdb0bcc.JPG)

**Comment by hama3254** [comment]
There is no error visible in the screenshot.

**Comment by hama3254** [comment]
Without an error there is nothing i can or need to fix.
