### ISSUE TITLE
U10: Startet teilweise kein Download

### ISSUE THREAD

**Issue by xILikepuddingx** [hama3254/Crunchyroll-Downloader-v3.0#312]
Moin Moin :D,

hab mal wieder ein kleines Problemchen.
Und zwar geht es darum, dass der Downloader hin und wieder mit der aktuellsten Version (Beta U10) teilweise keine Downloads startet.
Habe aus interesse mal die aktuelle Release Version (3.7.8.6) genommen und eben diese Folge probiert und das mehrmals.

Hier habe ich nochmal ein Video:
https://streamable.com/ii8v2d

Eine Fehlermeldung gibt es nicht wirklich sonst würde ich das direkt mit posten.

LG

**Comment by hama3254** [comment]
ich hab den Fehler gefunden und nehme die url welche aufgerufen wird aus dem billig adblocker raus. 
![grafik](https://user-images.githubusercontent.com/52826614/124390436-eb6ac380-dceb-11eb-8280-fe25f87b0295.png)

**Comment by hama3254** [comment]
`Crunchyroll-Downloader-v3.8-Beta-U11` sollte das problem beheben.

**Comment by xILikepuddingx** [comment]
xD
Top Danke x3
