### ISSUE TITLE
us unlock doesnt work

### ISSUE THREAD

**Issue by kazuhachuli** [hama3254/Crunchyroll-Downloader-v3.0#314]
After using the US unlock option and exploring anime, the browser closes, I open it again but US unlock doesn't seem to work :(

**Comment by hama3254** [comment]
since the us unlock is in it's core a bug inside crunchyroll it does not work as reliable as i would like.
there are known issues with redirecting to the beta site with an account after using the unlock and it is known that you might need to restart the downloader after unlocking to finish it of.

**Comment by kazuhachuli** [comment]
I show you a more detailed video of what happens:

https://user-images.githubusercontent.com/59351873/124663276-27e41e00-deaa-11eb-871e-5d4596856613.mp4

**Comment by hama3254** [comment]
The US unlock does not work for the beta website.
If you did not opt-in for the beta website then you might get to this issue. There is nothing I can do about it.

> there are known issues with redirecting to the beta site with an account after using the unlock

**Comment by kazuhachuli** [comment]
I did not sign up for the beta, it is a very annoying problem :(

**Comment by LTech77** [comment]
I had the same Problem. You need to scroll down and need the select go back to Normal. It's quite hidden.

**Comment by hama3254** [comment]
Crunchyroll Classic does not work for me after using the US session cookie and the Beta website has not the issue that made the us unlock possible.
That means the us unlock does not work any longer with an account.

**Comment by kazuhachuli** [comment]
And what can be done to fix it? ty

**Comment by LTech77** [comment]
You could use a VPN.

**Comment by feren6190** [comment]
![Desktop 11-07-2021 10-27-15 a  m -468](https://user-images.githubusercontent.com/86535486/125200997-ec8f7980-e232-11eb-9331-56721642f02f.png)

**Comment by feren6190** [comment]
![Desktop 11-07-2021 10-27-15 a  m -468](https://user-images.githubusercontent.com/86535486/125201075-337d6f00-e233-11eb-9940-8c4a8bc76e67.png)

**Comment by feren6190** [comment]
![Desktop 11-07-2021 10-31-18 a  m -891](https://user-images.githubusercontent.com/86535486/125201086-3f693100-e233-11eb-82df-d798a3f40e67.png)

**Comment by hama3254** [comment]
@feren6190 please stay in your issue or at least one with an related topic. 
further more if you want to report an issue please follow my instructions from #311 otherwise i have nowhere to start for any issue.
It would also be helpful if you can add information an not just post a bunch of screenshots that makes me search for the issue and some key information like the exact version is also required since what i see there has been reported in #297 and was addressed with "update-10"  of the beta version.
