### ISSUE TITLE
Tsubasa Chronicle 2 EP 23-26 only 396P?

### ISSUE THREAD

**Issue by LTech77** [hama3254/Crunchyroll-Downloader-v3.0#316]
Hallo Hama,
Ich habe versucht die letzten 4 Episoden von den Tsubasa Chronicles (EP 23-26) auf AOD herunterzuladen. Dabei kann ich das ganze aber nur auf 396P herunterladen. Alle Episoden davor waren auf 1080p und auf der AOD Webseite sind die letzten 4 Episoden auch mit dem Format verfügbar.
Hier mal der log von EP 23.:
[Tsubasa Chronicle - 2 Staffel Ep 23.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6776803/Tsubasa.Chronicle.-.2.Staffel.Ep.23.log)

**Comment by hama3254** [comment]
Ich sehe das problem.
AoD gibt jeder Folge eine Nummer (Sub und Dub haben die selbe) welche beim den `Deutsch` bzw `Japanisch (UT)` als url hinterlegt sind. normalerweise ist die Antwort die AoD auf die url gibt immer die selbe nur das die angefragte Folge die erste ist und es dann aufsteigt, bei `Tsubasa Chronicle - 2 Staffel` ist das nicht ganz der fall da ändert sich der Stream irgendwann zwischen Folge 1 und eben 23 sodass 23 selbst ein 1080p+ video hat während in der playlist von Folge 1 bei folge 23 es eben nur 396p gibt.  

Es sollte möglich sein das zu beheben aber es ist verdammt aufwendig weil ich den halben Ablauf ändern müsste weshalb ich derzeit nicht versprechen kann ob bzw. wann ich da was mache.

**Comment by LTech77** [comment]
Wäre es nicht theoretisch möglich das ganze Manuell zu machen? Es sind ja nur 4 Streams zum Downloaden. Wonach muss ich denn in der Netzwerkanalyse suchen, um den passenden Stream zu finden?

**Comment by hama3254** [comment]
Ich hab das ganze mal in einem kurzen Video zusammengefasst :
https://www.youtube.com/watch?v=FyzTZ7cskRo
Nur der Hinweis alles was mit Audio zu tun hat wird bei dir fehlen.

**Comment by LTech77** [comment]
Hab gerade mal dein Tipp ausprobiert und hat auch geklappt, sogar mit Audio. Vielen Dank.
Das mit Audio hat aber bloß mit der Version v3.7.8.6 funktioniert.
