### ISSUE TITLE
Error "Please make sure that the URL is correct"

### ISSUE THREAD

**Issue by Kyouma95** [hama3254/Crunchyroll-Downloader-v3.0#32]
Getting this Error with version 3.3.0 and 3.3.1
https://i.imgur.com/xh0FcSZ.png

Any idea why?

**Comment by hama3254** [comment]
> 
> 
> Getting this Error with version 3.3.0 and 3.3.1
> https://i.imgur.com/xh0FcSZ.png
> 
> Any idea why?

the reason for that error is that the downloader has not found any of the 3 possible valid strings to indicate that he site contains an anime or the overview.
this can be either a false negative or the anime is simply not avalibe in your country or crunchyroll had a error page

**Comment by Kyouma95** [comment]
Looks like crunchyroll just had an error, it works now just fine.
