### ISSUE TITLE
Unable to Log into Funimation site

### ISSUE THREAD

**Issue by 619beave** [hama3254/Crunchyroll-Downloader-v3.0#321]
Hello,

When using the GekoFireFox Browser, I am unable to log in on the Funimation Site. It just sits there and does not proceed to the next page.

**Comment by hama3254** [comment]
it appears that the login form itself does not work any more.
Unfortunately i can not fix anything on the browser itself but i already look into replacing it with [CefSharp](https://cefsharp.github.io/) which is based on the chrome engine.

**Comment by 619beave** [comment]
Please, keep us updated. 

Thanks for the great work and support

**Comment by hama3254** [comment]
i'm not finished yet but it looks better than expected 
![grafik](https://user-images.githubusercontent.com/52826614/126042911-289e8f55-ee29-40cc-a01e-d9e703d5a579.png)

**Comment by lawspotr** [comment]
please upload beta

**Comment by hama3254** [comment]
> please upload beta

There is nothing to upload yet because it would be simpler for you to report things that work rather than things that don't.

For a work around for that login issue you can try the add-on https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/296

**Comment by lawspotr** [comment]
> 
> 
> > please upload beta
> 
> There is nothing to upload yet because it would be simpler for you to report things that work rather than things that don't.
> 
> For a work around for that login issue you can try the add-on #296

the issue with the extension is that you can't download premium content from funimation, such as anime on broadcast u.u

**Comment by hama3254** [comment]
> the issue with the extension is that you can't download premium content from funimation, such as anime on broadcast u.u

If you would make a proper error report than I might be able to fix it but don't saying anything until I bring up the add-on as possible work around and then you would need to add more details.
Did you tryed single and multi download from the add-on?
What kind of error or behavior did you get ?
Have you been logged in on Funimation inside your normal Webbrowser?

**Comment by lawspotr** [comment]
> 
> 
> > the issue with the extension is that you can't download premium content from funimation, such as anime on broadcast u.u
> 
> If you would make a proper error report than I might be able to fix it but don't saying anything until I bring up the add-on as possible work around and then you would need to add more details.
> Did you tryed single and multi download from the add-on?
> What kind of error or behavior did you get ?
> Have you been logged in on Funimation inside your normal Webbrowser?

sorry, I think it was because of my subscription, but it works with the extension.

**Comment by hama3254** [comment]
Here is a version with cefsharp might even download something https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x

**Comment by 619beave** [comment]
Hello Hama3254,

The download above works with a little glitch here and there.

At first, I was able to login into Funimation Site and download, but the download locked up.

After restarting the program it works correctly.

I do see GekoFireFox running as well after running the Chromium.

THanks for uploading the Beta Fix.

**Comment by NatsuFT36** [comment]
Good, in Funimation even though it has 128 kbps audios but look at that on Dirpy's page I get 256 kbps audio and it is because it uses a Hybrik 1.217.17 format that I tried with the free chapter https://www.funimation.com/es/shows/my-hero-academia/off-to-endeavors-agency/?qid=
And that is the site that can see the video with its resolution in 540p https://dirpy.com/

**Comment by NatsuFT36** [comment]
I downloaded the test video with IDM and see the specification of that video

**Comment by hama3254** [comment]
@NatsuFT36 Just stop with that kind of unnecessary comments, funimation has 128kbps and that's it.

**Comment by bybpow** [comment]
Hi, @hama3254. Any news on this topic? I've tried to bypass this unsuccessfully. What is wrong with Gecko that is not happening in Chromium? Sorry if those are too much questions. The weird thing is that for example, the Funimation Shop login button works in Gecko and looks exactly the same that the other one.

**Comment by hama3254** [comment]
@bybpow i don't understand why the gecko version stoped working with the login button.
 My guess is that it is just to old, you can see that on the Crunchyroll beta webaite as well, i suppress a message telling the user that the browser is outdated and he should switch.
Which makes sense since the last gecko version i can get is `60.0.55` and with the first version `60.0.8-alpha` is from August 2018 i assume it is still based on Firefox 60 since then we got up to Firefox 90...

This seems not to be issue with CefSharp Chromium i got the latest version for that.

**Comment by bybpow** [comment]
@hama3254 . Where do you usually download Gecko versions from? I want to try out some test with different versions.

**Comment by hama3254** [comment]
i use the [NuGet package Geckofx60.32](https://www.nuget.org/packages/Geckofx60.32/)

**Comment by NatsuFT36** [comment]
Hi, I can't access the Funimation account from GeckoFX-Firefox to download more series

**Comment by NatsuFT36** [comment]
![Captura20](https://user-images.githubusercontent.com/51544427/128538310-4981ac2c-520d-46fa-8bc8-e3241538a834.PNG)

**Comment by hama3254** [comment]
@NatsuFT36 the current state has already been described in this thread, please read it.

**Comment by NatsuFT36** [comment]
This time, Funimation changed its formats that previously had 128kbps (22MB) to 256kbps (44MB) in the audios and now in 720p it brings 2 formats (2150 and 3500) of quality
![Captura21](https://user-images.githubusercontent.com/51544427/128545743-7248dba0-551d-4a4b-8ce6-f8414eb46830.PNG)

**Comment by NatsuFT36** [comment]
Hi, when I am downloading the dubbed series I get this error message
![Captura22](https://user-images.githubusercontent.com/51544427/129438600-a59bc736-258b-4ad2-b24b-d4ef7044e31c.PNG)

**Comment by hama3254** [comment]
@NatsuFT36 that is a random response issue from funimation

**Comment by hama3254** [comment]
since there is not direct issue right now i will close this, if any new issue is found everyone is free open a new issue for that specific case.
