### ISSUE TITLE
Unable to download from add-on 

### ISSUE THREAD

**Issue by Bellcranel98** [hama3254/Crunchyroll-Downloader-v3.0#323]
When I add episodes trough add-on and press "click to work off" in the status bar shows "Status:loading" but nothing happens there's no downloads in progress.

![image](https://user-images.githubusercontent.com/64061971/126049652-7d8c2a39-30fa-4006-a132-f201131d81f4.png)

Here's the log:

Web server started at: 127.0.0.1:80
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
System.ArgumentNullException: Referencia a cadena no establecida como una instancia de cadena.
Nombre del parámetro: s
   en System.Text.Encoding.GetBytes(String s)
   en Crunchyroll_Downloader.Main.SendHTMLResponse(String httpRequest, NetworkStream stream) en D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:línea 5150
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
System.ArgumentNullException: Referencia a cadena no establecida como una instancia de cadena.
Nombre del parámetro: s
   en System.Text.Encoding.GetBytes(String s)
   en Crunchyroll_Downloader.Main.SendHTMLResponse(String httpRequest, NetworkStream stream) en D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:línea 5150
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
System.ArgumentNullException: Referencia a cadena no establecida como una instancia de cadena.
Nombre del parámetro: s
   en System.Text.Encoding.GetBytes(String s)
   en Crunchyroll_Downloader.Main.SendHTMLResponse(String httpRequest, NetworkStream stream) en D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:línea 5150
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
System.ArgumentNullException: Referencia a cadena no establecida como una instancia de cadena.
Nombre del parámetro: s
   en System.Text.Encoding.GetBytes(String s)
   en Crunchyroll_Downloader.Main.SendHTMLResponse(String httpRequest, NetworkStream stream) en D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:línea 5150
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
System.ArgumentNullException: Referencia a cadena no establecida como una instancia de cadena.
Nombre del parámetro: s
   en System.Text.Encoding.GetBytes(String s)
   en Crunchyroll_Downloader.Main.SendHTMLResponse(String httpRequest, NetworkStream stream) en D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:línea 5150
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\balken.png
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\balken.png
multi episode mode
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\Post_Mass_Sucess.html
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
17/7/2021 16:16:01.719
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html
17/7/2021 16:16:07.712
C:\Users\DAVID.DESKTOP-9IHQPSD\Desktop\Crunchyroll-Downloader-v3.8-Beta-U12\WebInterface\index.html

**Comment by hama3254** [comment]
there is not real error handling for the beta website yet, please check that you are logged in to access the beta website and check that you don't get a 404 site
![grafik](https://user-images.githubusercontent.com/52826614/126050535-4b22aaf4-b48a-43b6-9019-567a451a35ce.png)

a complete black site is fine as however, CR seems to try making there website as incompatible as possible 
![grafik](https://user-images.githubusercontent.com/52826614/126050548-99027126-fe35-4efa-932e-e4ce49a696fe.png)

**Comment by Bellcranel98** [comment]
Thanks. You were right it was because I wasn't logged in on the browser. Now I am able to download, thanks again for your help.

**Comment by Bellcranel98** [comment]
Now I have a problem with login I don't know why it is requesting me again to login. I input well my login information but it shows "the csrf..."

![image](https://user-images.githubusercontent.com/64061971/126051186-9d924768-47eb-4f8b-ad14-f19ea5f53797.png)

**Comment by Bellcranel98** [comment]
I fixed by logging in through settings option set us cookie
