### ISSUE TITLE
(AOD) alle animes über folge 1 downloaden nicht.

### ISSUE THREAD

**Issue by denis34343** [hama3254/Crunchyroll-Downloader-v3.0#324]
Version : v3.8 Beta-U12

Alle animes über folge 1 werden nicht gedownloadet.
Sie haben einen komischen Namen in der preview und der log schmeisst einen directory fehler.

![image](https://user-images.githubusercontent.com/73022874/126533944-c971db38-f5e9-45a1-bacf-46e01b169083.png)

<details>
  <summary>Insert the logtext before the second details</summary>
    21.07.2021 19:18:15 -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" -headers "ACCEPT-ENCODING: *" -i "https://58dbf94b247de.streamlock.net/aod-cdn3-cloud/_definst_/smil:aod-cloud/1800_a0d0fda603bbfb90f87b87778d139ce1.smil/chunklist_w1258693749_b13568000_tkYW9kU2VjdXJlX3N0YXJ0dGltZT0xNjI2ODg3OTMyJmFvZFNlY3VyZV9lbmR0aW1lPTE2MjY5MDIzMzImYW9kU2VjdXJlX2hhc2g9TzJtVDdDeDR0Nzl0bjlnT2trSFc0T3BqbjE0QjdVUEY3N3FiaEFHQlR5Zz0=.m3u8"  -c copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\denwi\Desktop\aod\\Love Chunibyo \u0026 Other Delusions Ep 2.mp4"

21.07.2021 19:18:16 ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
21.07.2021 19:18:16   built with gcc 10.2.1 (GCC) 20200726
21.07.2021 19:18:16   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
21.07.2021 19:18:16   libavutil      56. 51.100 / 56. 51.100
21.07.2021 19:18:16   libavcodec     58. 91.100 / 58. 91.100
21.07.2021 19:18:16   libavformat    58. 45.100 / 58. 45.100
21.07.2021 19:18:16   libavdevice    58. 10.100 / 58. 10.100
21.07.2021 19:18:16   libavfilter     7. 85.100 /  7. 85.100
21.07.2021 19:18:16   libswscale      5.  7.100 /  5.  7.100
21.07.2021 19:18:16   libswresample   3.  7.100 /  3.  7.100
21.07.2021 19:18:16   libpostproc    55.  7.100 / 55.  7.100
21.07.2021 19:18:16 [https @ 06b8dc40] The "user-agent" option is deprecated: use the "user_agent" option instead
21.07.2021 19:18:16 [https @ 04c8ec00] No trailing CRLF found in HTTP header. Adding it.
21.07.2021 19:18:16 [hls @ 06b8ce80] Skip ('#EXT-X-VERSION:3')
21.07.2021 19:18:16 [hls @ 06b8ce80] Opening 'https://58dbf94b247de.streamlock.net/aod-cdn3-cloud/_definst_/smil:aod-cloud/1800_a0d0fda603bbfb90f87b87778d139ce1.smil/media_w1258693749_b13568000_tkYW9kU2VjdXJlX3N0YXJ0dGltZT0xNjI2ODg3OTMyJmFvZFNlY3VyZV9lbmR0aW1lPTE2MjY5MDIzMzImYW9kU2VjdXJlX2hhc2g9TzJtVDdDeDR0Nzl0bjlnT2trSFc0T3BqbjE0QjdVUEY3N3FiaEFHQlR5Zz0=_0.ts' for reading
21.07.2021 19:18:17 [hls @ 06b8ce80] Opening 'https://58dbf94b247de.streamlock.net/aod-cdn3-cloud/_definst_/smil:aod-cloud/1800_a0d0fda603bbfb90f87b87778d139ce1.smil/media_w1258693749_b13568000_tkYW9kU2VjdXJlX3N0YXJ0dGltZT0xNjI2ODg3OTMyJmFvZFNlY3VyZV9lbmR0aW1lPTE2MjY5MDIzMzImYW9kU2VjdXJlX2hhc2g9TzJtVDdDeDR0Nzl0bjlnT2trSFc0T3BqbjE0QjdVUEY3N3FiaEFHQlR5Zz0=_1.ts' for reading
21.07.2021 19:18:17 Input #0, hls, from 'https://58dbf94b247de.streamlock.net/aod-cdn3-cloud/_definst_/smil:aod-cloud/1800_a0d0fda603bbfb90f87b87778d139ce1.smil/chunklist_w1258693749_b13568000_tkYW9kU2VjdXJlX3N0YXJ0dGltZT0xNjI2ODg3OTMyJmFvZFNlY3VyZV9lbmR0aW1lPTE2MjY5MDIzMzImYW9kU2VjdXJlX2hhc2g9TzJtVDdDeDR0Nzl0bjlnT2trSFc0T3BqbjE0QjdVUEY3N3FiaEFHQlR5Zz0=.m3u8':
21.07.2021 19:18:17   Duration: 00:23:35.46, start: 0.000000, bitrate: 0 kb/s
21.07.2021 19:18:17   Program 0 
21.07.2021 19:18:17     Metadata:
21.07.2021 19:18:17       variant_bitrate : 0
21.07.2021 19:18:17     Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
21.07.2021 19:18:17     Metadata:
21.07.2021 19:18:17       variant_bitrate : 0
21.07.2021 19:18:17     Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
21.07.2021 19:18:17     Metadata:
21.07.2021 19:18:17       variant_bitrate : 0
21.07.2021 19:18:17     Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
21.07.2021 19:18:17     Metadata:
21.07.2021 19:18:17       variant_bitrate : 0
21.07.2021 19:18:17 Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 1, only the last option '-c:a copy' will be used.
21.07.2021 19:18:17 C:\Users\denwi\Desktop\aod\\Love Chunibyo \u0026 Other Delusions Ep 2.mp4: No such file or directory
21.07.2021 19:18:17 
21.07.2021 19:18:17 
</details>

**Comment by denis34343** [comment]
ich hab einfach mal eine random ältere version gedownloadet und die funktioniert v3.7.5.1

**Comment by hama3254** [comment]
das ist ein Problem mit dem Namen, mit dem `\` sucht Windows nach einem Unterordner anstatt einer Datei.
ich habe eine einzelne `Crunchyroll.Downloader.exe` hochgeladen welche das Problem beheben sollte, diese muss in den Ordner der U12 und die alte exe ersetzen.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta
