### ISSUE TITLE
All chapters downloaded have hardsubed english subs

### ISSUE THREAD

**Issue by Hamuske33** [hama3254/Crunchyroll-Downloader-v3.0#33]
Hello, i tried your downloader, and is very cool, but all the chapters that i've downloaded have the english subs in hard sub, even if i've chose othe lenguage, [example](https://i.ibb.co/vd905cF/example.jpg), i don't have premium but suposly i can download 480p without troubles.

**Comment by Hamuske33** [comment]
It only hapen if you select the option "[automatic: Series/Season]", if you select another in option, all works fine.

**Comment by hama3254** [comment]
> 
> 
> It only hapen if you select the option "[automatic: Series/Season]", if you select another in option, all works fine.

that option has nothing to do with the Subtitels, it's just the Subfolder so the downloader creates a folder structure for the current download.
you can see that by the fact that it also list every subfolder in the current download folder :
![grafik](https://user-images.githubusercontent.com/52826614/86754483-36062100-c041-11ea-8201-87ad7cc97e66.png)

the Hardsub language ist a sperate option in the  outpur settings, if you want softsubs or dub anime you just need to select "[ without (none) ]"
![grafik](https://user-images.githubusercontent.com/52826614/86754608-4c13e180-c041-11ea-9a7c-02279570d36e.png)

**Comment by hama3254** [comment]
> 
> Hello, i tried your downloader, and is very cool, but all the chapters that i've downloaded have the english subs in hard sub, even if i've chose othe lenguage, [example](https://i.ibb.co/vd905cF/example.jpg), i don't have premium but suposly i can download 480p without troubles.

you should even without premium be able to download 1080p.

**Comment by Hamuske33** [comment]
yes, everything works fine, my player was selecting the subtitle track with the same name that the chapter, this only happen if you select al most one file in SoftSubs, and only happen if your player use the subtitle fine in the same folder with the same name.
