### ISSUE TITLE
Timetable

### ISSUE THREAD

**Issue by AlexMiniReal** [hama3254/Crunchyroll-Downloader-v3.0#331]
**Is your feature request related to a problem? Please describe.**
I would like to know the time episodes have finished downloading.

**Describe the solution you'd like**
I would suggest a timetable to put in the empty space here:
![Screenshot_18](https://user-images.githubusercontent.com/76444133/126869723-29af1fe3-6c73-4c06-93d4-4dc869dff819.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by hama3254** [comment]
This is not only a unnecessary gimmick  but also easy to fin out with the windows explorer property's.  

![grafik](https://user-images.githubusercontent.com/52826614/126870168-6dc16607-43ac-417d-8ba5-2e1d2c26d25e.png)

**Comment by garsbien** [comment]
![crunchy](https://user-images.githubusercontent.com/45321704/127237417-33dbb7b1-f191-4cbc-9a47-973660036910.png)

good evening Hama and all, deselect enable dark mode :)

**Comment by hama3254** [comment]
> ![crunchy](https://user-images.githubusercontent.com/45321704/127237417-33dbb7b1-f191-4cbc-9a47-973660036910.png)
> 
> good evening Hama and all, deselect enable dark mode :)

As for your two issues i have no idea what you want from me.
