### ISSUE TITLE
Crunchyroll Episoden Benennung und Nummer fehlen

### ISSUE THREAD

**Issue by ShadowDragonX** [hama3254/Crunchyroll-Downloader-v3.0#332]
Wenn ich von crunchyroll lade und in den Einstellungen sage das er mir den Namen der Episode und die Nummer mit speichern soll steht da immer none

Benutze U12
![settings](https://user-images.githubusercontent.com/22052427/126872981-500405f9-cb0c-4dd7-8b8c-ed8aac97abdf.PNG)
![preview](https://user-images.githubusercontent.com/22052427/126872979-170910f6-ab46-482a-8622-101cee6002d0.PNG)

**Comment by hama3254** [comment]
Ich kann das gerade nicht nachvollziehen auf die schnelle. 
![grafik](https://user-images.githubusercontent.com/52826614/126873880-33ebcdc7-66e3-43aa-9051-c39bcacd9103.png)

**Comment by ShadowDragonX** [comment]
ich hab nicht die url von der folge genommen sondern zu der serie
wenn ich das so mache wie du bekomme ich den Episoden Titel und Nummer 


kann man die Folgen auch so bennen das es am ende als "Bouto 120 - Der neue Schüler" gespeichert wird? <- nur ein beispiel damit du siehts welchen syntax ich meine

**Comment by hama3254** [comment]
> steht da immer none

das ist übrigens ein Platzhalter, ist derzeit noch nicht drinnen
![grafik](https://user-images.githubusercontent.com/52826614/126875699-f72882ee-4609-455c-b57c-227ce5bed4dc.png)


> ich hab nicht die url von der folge genommen sondern zu der serie

das sollte eigentlich keinen unterschied machen, ich schau aber gleich mal nach.

> kann man die Folgen auch so bennen das es am ende als "[Titel] [Episode Nummer] - [Episode Titel]" gespeichert wird?

wenn mit [Titel] der anime name gemeint ist, dann haben wir das ja schon abgesehen vom binde strich welcher so minimal den namen ändert das es mir die zeit nicht wert ist das als option hinzuzufügen.

**Comment by hama3254** [comment]
> > ich hab nicht die url von der folge genommen sondern zu der serie
> 
> das sollte eigentlich keinen unterschied machen, ich schau aber gleich mal nach.

warum der Name da auf einmal auf englisch ist wäre mal schön zu wissen.

![grafik](https://user-images.githubusercontent.com/52826614/126875851-ecedbfd9-e47c-4f61-8280-c4ed96dd4502.png)

**Comment by ShadowDragonX** [comment]
also ich hab das problem gefunden warum er nicht bei der url zu serie die episode nicht benannt hatte. Ich habe im bereich "Name of the Anime" den Anime Namen eingetragen, aber wenn ich das weglasse speichert er die episode mit episoden titel

**Comment by hama3254** [comment]
>Ich habe im bereich "Name of the Anime" den Anime Namen eingetragen, aber wenn ich das weglasse speichert er die episode mit episoden titel

hast du den link für nur eine folge eingefügt oder die Übersichtsseite und dann die folgen ausgewählt? 
das erste nimmt einfach den text aus der box ohne staffel bzw. folge hinzuzufügen, das zweite sollte es einfach ignorieren.
ich hab zudem den text von `Name of the Anime`  zu `Use Custom Name` geändert.

>aber in englisch wie du ja bereits gesagt hattest

Das scheint mir ein problem mit CR gewesen zu sein, jetzt läuft es wieder auf deutsch.
![grafik](https://user-images.githubusercontent.com/52826614/127668984-ce347600-60dc-4891-960c-2335da5a515f.png)

**Comment by ShadowDragonX** [comment]
> 
> hast du den link für nur eine folge eingefügt oder die Übersichtsseite und dann die folgen ausgewählt?
> das erste nimmt einfach den text aus der box ohne staffel bzw. folge hinzuzufügen, das zweite sollte es einfach ignorieren.

- hab den link zur übersichtsseite des animes eingefügt und dann die folgen ausgewählt

> ich hab zudem den text von `Name of the Anime` zu `Use Custom Name` geändert.

- ich denke das ist verständlicher XD
