### ISSUE TITLE
Little bug when you press +

### ISSUE THREAD

**Issue by garsbien** [hama3254/Crunchyroll-Downloader-v3.0#333]
Good evening when you press the "+" we have the download screen. But when we cut via the cross then when we press on it we don't always have it ?

Thx in advance !! ♥

**Comment by hama3254** [comment]
Please try to write your issue understandable, I have no idea what your issue is.

**Comment by garsbien** [comment]
the + tab never open again

**Comment by hama3254** [comment]
The intended behavior of that button is that if the window is closed or minimized then the form will be opened, if it is already open in the background then it will not do anything so you need to organize your foreground and background window on your own.

**Comment by garsbien** [comment]
Thanks :(
