### ISSUE TITLE
Chromium or me I have always firefox ?

### ISSUE THREAD

**Issue by garsbien** [hama3254/Crunchyroll-Downloader-v3.0#334]
Hi so it's a pre release v3 chromium but it's normal that I still have firefox instead of chrome, thx again !!

**Comment by hama3254** [comment]
Please try to write your issue understandable, I have no idea what your issue is.

**Comment by garsbien** [comment]
The software isn't working on Chromium

**Comment by hama3254** [comment]
The chromium version is a `highly experimental` version so you only should download it if you have the funimation login issue.
