### ISSUE TITLE
Add a function to Download a whole Series, not just single Episodes

### ISSUE THREAD

**Issue by calvinthefreak** [hama3254/Crunchyroll-Downloader-v3.0#335]
Maybe add a funtion to download whole episodes, and not just only the choosen episode.

Or what is also possible is, that you add an Commandline Option, so I can parse the Page myself and download choosen episodes.

**Comment by hama3254** [comment]
> Maybe add a funtion to download whole episodes, and not just only the choosen episode.

Already in there, just use the overview Page with all episodes.

> Or what is also possible is, that you add an Commandline Option, so I can parse the Page myself and download choosen episodes.

The Downloader is not made for cli support so everything depends on the UI but i made a http server which can receive input via post requests.

If you want you can either use the add-on for it or you can make something of your own, the source for the Firefox add-on can be found in this repository while the chrome version was moved for simpler releases.
https://github.com/hama3254/CRD-add-on-for-Chrome/releases
