### ISSUE TITLE
AR issue with a SD show

### ISSUE THREAD

**Issue by KuronekosHerald** [hama3254/Crunchyroll-Downloader-v3.0#336]
I'm downloading this SD [show](https://www.crunchyroll.com/pretty-cure). The problem is that when I try to play it that's what happens:
![vlcsnap-2021-07-30-15h59m18s049](https://user-images.githubusercontent.com/57872968/127664219-453ded8d-da07-48ad-bda4-d7671c1131f8.png)

The aspect ratio is totally wrong.
I loaded the file on mkvtoolnix and found this: 
![InkedMKVToolNix GUI v58 0 0 ('Supper's Ready') 64-bit 30_07_2021 11_26_57_LI](https://user-images.githubusercontent.com/57872968/127664648-5cd9f219-1743-4244-aae3-b1331e13e60f.jpg)
Changing the values fix it obviously.

I also tried to randomly download other SD shows ([this one](https://www.crunchyroll.com/yu-gi-oh) and [this one](https://www.crunchyroll.com/miss-machiko)) to see if it was a general issue but they seem to run fine.

The popup asking to choose a resolution on Crunchyroll Downloader showed respectively: 656x480 for the [first](https://www.crunchyroll.com/pretty-cure), 640x480 for the [second](https://www.crunchyroll.com/yu-gi-oh), 624x480 for the [third](https://www.crunchyroll.com/miss-machiko).

I'm using v3.8 U12 and VLC (Windows 10).

P.S. The Display width/height values of the other two files on mkvtoolnix are 229x170 and 113x86, but they have no problem somehow.

**Comment by hama3254** [comment]
this is a issue with the metadata of the video stream.

you can fix that with `ffmpeg -i <INPUT_FILE> -aspect [height:with] -c copy [OUTPUT_FILE]`

```
30.07.2021 16:52:56 Input #0, hls, from 'E:\Test\Pretty-Cure-Season-1-Episode-1-Wir-verwandeln-uns!-Das-gibt's-doch-nicht!\index.m3u8':
30.07.2021 16:52:56   Duration: 00:24:21.79, start: 0.101000, bitrate: 0 kb/s
30.07.2021 16:52:56   Program 0 
30.07.2021 16:52:56     Metadata:
30.07.2021 16:52:56       variant_bitrate : 0
30.07.2021 16:52:56     Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 656x480 [SAR 4007:4012 DAR 164287:120360], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
30.07.2021 16:52:56     Metadata:
30.07.2021 16:52:56       variant_bitrate : 0
```

**Comment by garsbien** [comment]
![ratiocrunchy](https://user-images.githubusercontent.com/45321704/127725807-d07ba173-48e4-41aa-914d-f3c974e6ba19.png)

576p checked ?

**Comment by KuronekosHerald** [comment]
@hama3254 
Thank you for the reply.
Do I need to do that using CMD right?

@garsbien 
Was set on 1080p+

**Comment by garsbien** [comment]
because you can settle

settings -> output -> resolution -> 480p

and also put 576p in AoD

The video of the stream being in sd 640 * can be that the software upscale?

**Comment by hama3254** [comment]
> 
> 
> 
> 576p checked ?


> @garsbien
> Was set on 1080p+

this setting is entirely for `anime-on-demand.de` and has no use for CR or Funimation. 


> @hama3254
> Thank you for the reply.
> Do I need to do that using CMD right?

well yes but actually no, i did not read that you can fix it with mkvtoolnix and it should be the same so you can do what you prefere 

> Changing the values fix it obviously.
