### ISSUE TITLE
Unable to download from Funimation

### ISSUE THREAD

**Issue by AlexMiniReal** [hama3254/Crunchyroll-Downloader-v3.0#337]
After clicking the Add Video button to put the url of the anime and writing the url, when I click on download it just says "Fail?".

![Screenshot_1](https://user-images.githubusercontent.com/76444133/128023393-c4666396-7070-491a-8fcb-db6c2d17df32.jpg)

**Comment by hama3254** [comment]
please add what version you are using, you can find that in the About section of the settings.

**Comment by AlexMiniReal** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/76444133/128046467-53e12a9f-0704-437b-b09a-2dd5fb84cec5.jpg)

**Comment by hama3254** [comment]
then we already have the issue there, you try to use the overview site of the anime which is only supported since `Crunchyroll-Downloader-v3.8-Beta-U7.zip`

**Comment by AlexMiniReal** [comment]
so I just need to wait the update?

**Comment by hama3254** [comment]
you can already download the latest version here: [Crunchyroll-Downloader-v3.8-Beta-U12](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta)

**Comment by garsbien** [comment]
no problem with the latest chromium version too
![funimation](https://user-images.githubusercontent.com/45321704/128054219-2ce1469a-db5e-473e-8555-e48c59980eae.png)
