### ISSUE TITLE
Unable to download a single CR episode

### ISSUE THREAD

**Issue by bybpow** [hama3254/Crunchyroll-Downloader-v3.0#338]
Hi,

I found a weird "bug" with S1E11 of "The Misfit of Demon King Academy":
https://beta.crunchyroll.com/watch/GY79EWW0R/The-Glow-of-Life

The downloader is unable to get this asset. It seems the app is trying to get the asset from VRV for some reason I don't know. This just happens in this episode.

Log fragment:

`C:\My Stuff\Utils\Crunchyroll-Downloader-v3.8-Beta-U12\The Misfit of Demon King Academy\CRD-Temp-File-gYgDERRRJKWfaXVK\
Download error #1: C:\My Stuff\Utils\Crunchyroll-Downloader-v3.8-Beta-U12\The Misfit of Demon King Academy\CRD-Temp-File-gYgDERRRJKWfaXVK\00001
Download error #1: C:\My Stuff\Utils\Crunchyroll-Downloader-v3.8-Beta-U12\The Misfit of Demon King Academy\CRD-Temp-File-gYgDERRRJKWfaXVK\00002
Download error #1: C:\My Stuff\Utils\Crunchyroll-Downloader-v3.8-Beta-U12\CRD-Temp-File-KBHcKUWRYMKWFYOJ.key
Download error #1: C:\My Stuff\Utils\Crunchyroll-Downloader-v3.8-Beta-U12\The Misfit of Demon King Academy\CRD-Temp-File-gYgDERRRJKWfaXVK\00000
Download error #2: https://fy.v.vrv.co/evs1/a52867781dd302fbf52cc58549ffc393/assets/07fd871b6ba792a3b00a75b55d9e22f9_3868703.mp4/seg-2-v1-a1.ts?t=exp=1628325518~acl=/evs1/a52867781dd302fbf52cc58549ffc393/assets/07fd871b6ba792a3b00a75b55d9e22f9_3868703.mp4/*~hmac=ccf3a169d18b4b66ee2c3a68c0dd1029e434a3843211b92d9807f1d6498449a6
C:\My Stuff\Utils\Crunchyroll-Downloader-v3.8-Beta-U12\The Misfit of Demon King Academy\CRD-Temp-File-gYgDERRRJKWfaXVK\00001
System.Net.WebException: The remote name could not be resolved: 'fy.v.vrv.co'
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Crunchyroll_Downloader.CRD_List_Item.TS_DownloadAsync(String DL_URL, String DL_Pfad) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\CRD_List_Item.vb:line 934
https://fy.v.vrv.co/evs1/a52867781dd302fbf52cc58549ffc393/assets/07fd871b6ba792a3b00a75b55d9e22f9_3868703.mp4/seg-2-v1-a1.ts?t=exp=1628325518~acl=/evs1/a52867781dd302fbf52cc58549ffc393/assets/07fd871b6ba792a3b00a75b55d9e22f9_3868703.mp4/*~hmac=ccf3a169d18b4b66ee2c3a68c0dd1029e434a3843211b92d9807f1d6498449a6
`

**Comment by hama3254** [comment]
> It seems the app is trying to get the asset from VRV for some reason I don't know. This just happens in this episode.

Crunchyroll uses for nearly all streams the some vrv domain.
`fy.v.vrv.co` is a new one for me and it seems that your DNS server can not find it.

> `The remote name could not be resolved: 'fy.v.vrv.co'`

You can try to change it [there are a ton of public DNS server available](https://duckduckgo.com/?q=public+dns+server&t=fpas&ia=answer&iax=answer)

**Comment by garsbien** [comment]
this site does not work

**Comment by bybpow** [comment]
> this site does not work

?

**Comment by bybpow** [comment]
Hi again, @hama3254 

I don't understand what you mean. I'm using a VPN and tried to change different connections, changing the DNS but the problem still happened.  I gotta say I've been able to finally get it. But before that, you're right. It seems CR uses a lot of VRV features. They seem to use the same naming and even thumbnails follow the same rules.

As I said, I was unable to download it using a VPN so after reading to comment a tried to change DNS etc. but didn't work.  I thought maybe the issue was with the manifest so I tried to download it with YT-DL and I could download it. After that I tried to  disabled my VPN and tried to use the "Set Cookies" app's option. The problem is that the new beta site requires you to login so I think that when I logged in I lost the cookie. I'm not sure about this last thing because I don't know how to check in the beta site where my location is, it was easier in the old site. So I did exactly that. I set the cookie but not logging in and using the old site with the app browser. I grabbed the URL and this time the app worked perfectly.

I don't know if the problem is my VPN or the new goddam beta site. Crunchyroll and Funimation new sites are making me go crazy.

**Comment by hama3254** [comment]
> Crunchyroll and Funimation new sites are making me go crazy.

You are not alone ...

>  I'm using a VPN

i can not help you with that, the issue is clearly the [DNS](https://www.youtube.com/watch?v=Rck3BALhI5c) and i may even be possible that the VPN Server sets your DNS so you might not even be able change it.

i just tested the domain and it is working.
funny thing is you can see that the server is intended to be accessed from Europe otherwise my ping should be way higher. 
![grafik](https://user-images.githubusercontent.com/52826614/128368282-c0fbe0ce-e375-4755-acd8-c9425d37648c.png)

**Comment by garsbien** [comment]
![mistfit](https://user-images.githubusercontent.com/45321704/128378619-0f886ab4-d830-4334-848a-3a8efe3059dc.png)

**Comment by bybpow** [comment]
> edit : I can't read the video with the embedded browser: /

The video is US available only. If you're not using a VPN you will not be able to view it. Have you tried to set the cookie with the app?

**Comment by bybpow** [comment]
@hama3254 If you think the problem is my DNS, then close this issue. 

Thank you for your help.

**Comment by garsbien** [comment]
i am with a vpn in america but i don't have the software cookie in settings. Weird on my firefox the video works but not in the software :(

**Comment by bybpow** [comment]
@garsbien 
Don't use the VPN when setting the cookies. That is what that option is for. The option is here:

![Capture](https://user-images.githubusercontent.com/62562341/128436392-ab8bd352-642b-4252-a9e9-2940fdffc6b0.PNG)

**Comment by garsbien** [comment]
even where you say I don't have the button :( white theme

**Comment by bybpow** [comment]
Uhm that's seems weird. What version are you using? Go to the "About" tab and tell me. Could you share some screencaps too?

**Comment by garsbien** [comment]
![about](https://user-images.githubusercontent.com/45321704/128444761-82d2fd59-3868-41ed-9177-0f5d1b4f0429.png)
![crunchcook](https://user-images.githubusercontent.com/45321704/128444765-66ee1032-1fb0-4dfc-9d07-8ea914b287a2.png)

**Comment by bybpow** [comment]
I think you're using the Chromium verision. That's I thinks your problem. Download the one using Gecko.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8-Beta

**Comment by garsbien** [comment]
yes I use the chromium pre release thank you again :)

**Comment by hama3254** [comment]
> edit : I can't read the video with the embedded browser: /

That does not work even if the anime is available since CR uses a DRM protected video for the playback and neither the GeckoFX or CefSharp version support that.

Cookies also don't work on the beta website so i didn't even start to implement it into the CefSharp version.

A interesting sidenote is that CR does not check for the country at a file level that means you should have perfectly fine access to the video without the VPN after it has been added to the Downloader.

So if you disable the hybrid mode, then the download will fail completely and you can disconnect the VPN then restarting the download with the play/pause button should work.
This won't work with the hybrid mode since it does not crash like ffmpeg does.

**Comment by garsbien** [comment]
Thanks in advance hama :)
