### ISSUE TITLE
File labling seems to messing up in the latest beta version

### ISSUE THREAD

**Issue by Defectuous** [hama3254/Crunchyroll-Downloader-v3.0#339]
I am currently using Crunchyroll-Downloader-v3.8-Beta-U12

The downloading fuction is downloading files

when i select my download folder it adds it to the front of the time name like so
"FolderAnimeNameSeasonNumberEpisodeNumber" instead of Folder/AnimeName/EpisodeNameSeasonNumberEpisodeNumber

**Comment by bybpow** [comment]
This has also happened to me with some shows. I think the problem is in the site's API. What show are you trying to download? Also, there are show titles that are too long text strings. 
Try this:
In "Add video" section, select the option "Ignore subfolder". This will not create a folder with the usual names but usually works with these problematic shows.

**Comment by hama3254** [comment]
I'm not sure if it is the API in your case so i need to take a look later but it is for sure that the have some issues inside there API.
This is for example the same episode.
![grafik](https://user-images.githubusercontent.com/52826614/114275306-51fc8000-9a22-11eb-8360-7ed378f09257.png)

**Comment by Defectuous** [comment]
for me it's every series I download, it's mostly just maintenance downloading to update the series i am watching

**Comment by bybpow** [comment]
@Defectuous 
Please share the show so I can do some tests. Also please share some screencaps of your settings if you don't mind.

**Comment by hama3254** [comment]
i can not find the issue you are describing, i only found minor naming issues for CR Beta which should be fixed in U13.

**Comment by Defectuous** [comment]
> @Defectuous
> Please share the show so I can do some tests. Also please share some screencaps of your settings if you don't mind.



> @Defectuous
> Please share the show so I can do some tests. Also please share some screencaps of your settings if you don't mind.

The last three shows i grabbed from are these

and as for which, it's every show not just these shows anything I download from crunchy

**Comment by bybpow** [comment]
I'm not having this problem. I've done some test with "To Your Eternity" and everything seems fine. Can you disable the Kodi option and try again to see what happens?

Also, @hama3254 while doing this I've found I can't log in to CR anymore. 
"The CSRF token is invalid. Please try to resubmit the form."

This looks to be a Gecko problem too.

**Comment by hama3254** [comment]
> Can you disable the Kodi option and try again to see what happens?

that should not do much about the path.
![grafik](https://user-images.githubusercontent.com/52826614/129044820-8494d62b-001e-453a-a55f-72a70e457dba.png)



> Also, @hama3254 while doing this I've found I can't log in to CR anymore.
> "The CSRF token is invalid. Please try to resubmit the form."
> 
> This looks to be a Gecko problem too.

That is a CR issue, that token is a hidden value in the login form 

![grafik](https://user-images.githubusercontent.com/52826614/129044420-331d6b92-15b7-4f91-ae79-647b02f0c40e.png)

**Comment by bybpow** [comment]
I commented this in another issue, the Funimation one. I've been trying different versions, mainly:

- geckofx60.64.60.0.55
- geckofx60.64.60.0.54

- Geckofx60.32.60.0.55
- Geckofx60.32.60.0.55

I've never use Gecko or VB so its all new to me. but after some tests I gotta say:

Using the current version with beta 13 the token log in error appears. Is this happening to you to or it's just me? But using geckofx60.64.60.0.54 (probably with geckofx60.64.60.0.55 will work too) the error doesn't happen. It logs in although this popup displays:
![image](https://user-images.githubusercontent.com/62562341/129066002-28f85218-be0d-489f-b30e-7c6c7fbb8774.png)

In both version in browser mode a black screen seems to happen if you're connected to CR beta site. In Funimation none version seems to fix the login problem.

**Comment by bybpow** [comment]
I see. I downloaded the zip from the beta repo so it's probably outdated. Sorry to bother you and thanks for your time.
