### ISSUE TITLE
windows server error

### ISSUE THREAD

**Issue by Zeniitsu** [hama3254/Crunchyroll-Downloader-v3.0#34]
bro how can i fix this problem.
when i try to open crunchyroll downloader
it show me this message ' windows server is not supported '.

**Comment by x3inspire** [comment]
Means Windows Server not supported.

**Comment by Zeniitsu** [comment]
Is there a way to run it on windows server?

**Comment by Zeniitsu** [comment]
or, can the owner make a compatible version with win server

**Comment by hama3254** [comment]
Windows Server is not supported, there is no fix from my side.

**Comment by Zeniitsu** [comment]
okay, thanks for the reply.
