### ISSUE TITLE
Certain series won't download

### ISSUE THREAD

**Issue by Jaynator495** [hama3254/Crunchyroll-Downloader-v3.0#343]
I'm on the latest beta, u12. I'm trying to download How not to summon a demon lord omega (double summon ver.), when I attempt to download it, even signed in, it doesn't give me an error and will forever sit at 1/10, never actually adding anything to the download queue

**Comment by hama3254** [comment]
> I'm on the latest beta, u12.

U13 has been released yesterday, not that it changes much.


> never actually adding anything to the download queue

please add with what url that happens (CR beta or normal) and make sure there is more than 0 here :
![grafik](https://user-images.githubusercontent.com/52826614/128630472-189bebba-3848-4416-af8e-d26177ebb212.png)

**Comment by Jaynator495** [comment]
It is both beta and normal, I've tried both, and downloads is set to 4

**Comment by hama3254** [comment]
is the anime available in your country and have you checked if the Mature filter is disabled in the account settings?

**Comment by Jaynator495** [comment]
Yes and Yes. I'm in America so country isn't a problem, as for account settings, whoops that was it, I mostly watch on VRV so I must have never disabled on crunchyroll. However now there is something else odd... It only downloads from the beta, even if I try to download from the non-beta it just autochanges to beta for the download.  A tad odd, but at least it works now. Thanks for the help

**Comment by hama3254** [comment]
> It only downloads from the beta, even if I try to download from the non-beta it just autochanges to beta for the download

if you are still logged in inside the downloader that is very likely to happen.
