### ISSUE TITLE
Unable to download subtitles from Funimation

### ISSUE THREAD

**Issue by AlexMiniReal** [hama3254/Crunchyroll-Downloader-v3.0#346]
Download is stuck.
![Screenshot_5](https://user-images.githubusercontent.com/76444133/129484099-f85e5a71-6c0e-4142-8328-accc51153cb6.jpg)

Version: v3.8 BETA-U12

**Comment by AlexMiniReal** [comment]
I click on add video, then I put this url: "https://www.funimation.com/shows/assassination-classroom/?qid=", then select Season 1 and episoded, click download and nothing happenes.

**Comment by hama3254** [comment]
The Gecko version has no timeout so it can get stuck, this is fixed in the CefSharp version.
Please try [`Crunchyroll-Downloader-Chromium-U1`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by AlexMiniReal** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/76444133/129492072-0f010d1f-5db7-4c7d-b19d-bc0c1fa00aab.jpg)

I just tried and the problem is the same.

**Comment by hama3254** [comment]
The issue seems to be inside funimation itself.
The website the downloader is trying to open does not load properly for me and that neither in the build in browser or a normal browser.
This issue happens if no region is inside the url, i added a fall back to the `en` region tag if there was none inside the url. 
please try [Crunchyroll-Downloader-Chromium-U2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by AlexMiniReal** [comment]
IT WORKS!!!

**Comment by AlexMiniReal** [comment]
Here are some errors I encountered

[Assassination Classroom Season 1 Episode 12-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994785/Assassination.Classroom.Season.1.Episode.12-subtitle_error.log)
[Assassination Classroom Season 1 Episode 13-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994786/Assassination.Classroom.Season.1.Episode.13-subtitle_error.log)
[Assassination Classroom Season 1 Episode 17-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994787/Assassination.Classroom.Season.1.Episode.17-subtitle_error.log)
[Assassination Classroom Season 1 Episode 19-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994788/Assassination.Classroom.Season.1.Episode.19-subtitle_error.log)
[Assassination Classroom Season 1 Episode 20-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994789/Assassination.Classroom.Season.1.Episode.20-subtitle_error.log)
[Assassination Classroom Season 1 Episode 21-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994790/Assassination.Classroom.Season.1.Episode.21-subtitle_error.log)
[Assassination Classroom Season 1 Episode 22-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6994791/Assassination.Classroom.Season.1.Episode.22-subtitle_error.log)

**Comment by hama3254** [comment]
that seems to be funimation issue, i can watch for example episode 11 and 13 but 12 and every other you had issues with is `for subscribers only` which should actually not be the case based on the icons of the website 
![grafik](https://user-images.githubusercontent.com/52826614/129623223-dc3deb74-8d9f-41dd-aca9-573bea89074c.png)
and that issue can be found in the logs as well.
![grafik](https://user-images.githubusercontent.com/52826614/129623083-83ee44f6-9609-4f18-94ab-1b99900fc1e0.png)

the downloader just can not work invalid inputs like that.
