### ISSUE TITLE
How to chnage file name to Anime and episode name only?

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#347]
Hi, may i know how to change the video name to Anime and episode name only for this version?

This is sample file name with previous version:

`BORUTO NARUTO NEXT GENERATIONS Episode 210
`

The closest one is "BORUTO NARUTO NEXT GENERATIONS Clues to Kara Season 1 Episode 210", i want only BORUTO NARUTO NEXT GENERATIONS Episode 210 instead of BORUTO NARUTO NEXT GENERATIONS Clues to Kara Season 1 Episode 210.

I tried change everything for new version but cannot get it.

![Capture](https://user-images.githubusercontent.com/4635825/129672588-848e2dd1-dab7-4174-bc07-86ff44adcc5e.PNG)

**Comment by hama3254** [comment]
There is no way implement to do that.
If the season has a number it gets used.
You can disable it the episode name by just choosing the episode number in the settings.

**Comment by x3inspire** [comment]
When i choosing the episode number in the settings the out is "Season 1 Episode 210"
![Capture](https://user-images.githubusercontent.com/4635825/129691828-c6fa0fb1-0bec-4b4a-9c02-bb9bdfb6c2b5.PNG)

**Comment by hama3254** [comment]
Then you are using the CefSharp version and that is not the case any more? 
 
 >This version only keep loading, not even download any single file.

Originally posted by @x3inspire in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/326#discussioncomment-1189874

because the gecko version has been fixed in U13 as can be seens in the [Main.vb](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/master/Crunchyroll%20Downloader/Main.vb) from line 2036 to 2058

**Comment by x3inspire** [comment]
> Then you are using the CefSharp version and that is not the case any more?
I'm using Crunchyroll-Downloader-Chromium-U2 version, others version not working, only keep loading...

This is output setting:
![Capture](https://user-images.githubusercontent.com/4635825/129730595-7990c835-878e-426e-a047-47abcab1b025.PNG)
But the file name is only 'Season 1 Episode 210', which setting should i used for file name as "BORUTO NARUTO NEXT GENERATIONS Episode 210"?

I believe i used same setting as version 3.8

**Comment by hama3254** [comment]
> But the file name is only 'Season 1 Episode 210', which setting should i used for file name as "BORUTO NARUTO NEXT GENERATIONS Episode 210"?

There is currently none, i did not have a 1:1 copy of the code for the CefSharp version so it differs from the Gecko version.
I'm about to fix that and i also added a button that removes the "Season 1" from the name (ignore that it also removed Season 2 of `That Time I Got Reincarnated as a Slime` that is fixed) for version U3 which i upload 
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x


![grafik](https://user-images.githubusercontent.com/52826614/129761495-22da8b3f-015c-4606-acfd-63c55ec886bc.png)

**Comment by x3inspire** [comment]
> > But the file name is only 'Season 1 Episode 210', which setting should i used for file name as "BORUTO NARUTO NEXT GENERATIONS Episode 210"?
> 
> There is currently none, i did not have a 1:1 copy of the code for the CefSharp version so it differs from the Gecko version.
> I'm about to fix that and i also added a button that removes the "Season 1" from the name (ignore that it also removed Season 2 of `That Time I Got Reincarnated as a Slime` that is fixed) for version U3 which i upload
> https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/129761495-22da8b3f-015c-4606-acfd-63c55ec886bc.png)

Fantastic!

**Comment by hama3254** [comment]
i think i can close this now.
