### ISSUE TITLE
I can't login to funimation with version 3.8 Beta-U13

### ISSUE THREAD

**Issue by janilssonn** [hama3254/Crunchyroll-Downloader-v3.0#349]
I click on enter and nothing happens only in the new U3 version that has many bugs, I would like you to kindly fix it to download funimation video

**Comment by hama3254** [comment]
This is not a valid error report, without a valid report i can not fix the Chromium version.

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/129897841-eab8a17c-d88c-4f75-a9b7-11594261e548.png)
![image](https://user-images.githubusercontent.com/16007846/129898003-09853be7-7b9c-4650-a928-1a81e5304414.png)
![image](https://user-images.githubusercontent.com/16007846/129898022-5bdfe63c-586c-4b72-be56-8407295d6434.png)
I try to download in portuguese brazil but only go in japanese some download in portuguese as you can see in the print this active portuguese

**Comment by janilssonn** [comment]
version Chromium

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/129899006-61808530-d0b0-4546-9898-9a3d360e54ce.png)
don't get out of it when you try to lower the volume in Funimation

**Comment by janilssonn** [comment]
the episode was unavailable for my language sorry and thank you so much for providing a wonderful tool, just give Funimation a little more attention you would be happy

**Comment by hama3254** [comment]
> the episode was unavailable for my language sorry and thank you so much for providing a wonderful tool, just give Funimation a little more attention you would be happy

i don't use funimation so it will always be not the best support since i not only need to wait for an error report but then i also need to wait until i want to look into it since i also want free time.
