### ISSUE TITLE
Video freezes while sound moves on

### ISSUE THREAD

**Issue by Odietheodie** [hama3254/Crunchyroll-Downloader-v3.0#35]
At certain points, the video will freeze for a couple of seconds while the sound goes on normally. The video than skips and catches up to the sound. It doesn't happen randomly, it is at certain points in the video. It happens on both the preinstalled "Films and TV" Windows app and on VLC.

**Comment by hama3254** [comment]
thats most likely a problem with the download. the video file is splitted in smaller files wich can reach a count more than 700, if one of this files is not proper downloaded you get this error.
unforunaly i can not do anthying against any random internet error that might cause something like that. 

>I can give you some tips like try a lower resolution and do just one download at the time.
