### ISSUE TITLE
Funimation: Site not rendering properly, consequently unable to login

### ISSUE THREAD

**Issue by caioalexandre3** [hama3254/Crunchyroll-Downloader-v3.0#350]
On 3.7.8.6 stable version, the Funimation website is not loading properly on internal browser, causing some issues to login. When clicking in Login and inserting credentials, the "Access" button won't work due to some render error.

I tried to extract a clean version of CRD but the issue persists. I don't know if there is a way to clean cache of the internal browser, but if there is any, I think it can be helpful. Screens below:

Site not loading properly:
![1](https://user-images.githubusercontent.com/15368068/130002541-ac1d5044-164f-47d8-af41-2344d958c382.png)

Login screen with Access button not doing any action:
![2](https://user-images.githubusercontent.com/15368068/130002543-99339560-e813-4c61-8cf0-d7d42b1654a0.png)

**Comment by hama3254** [comment]
This issue is already listed as known at the `v3.8-Beta` release

>#321 the funimation login does not work with the Webbrowser anymore 

and the fix is available as [`experimental release`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

>This is required since the old version is not able to login into Funimation, see #321 for more information.
