### ISSUE TITLE
VRV Support

### ISSUE THREAD

**Issue by Jaynator495** [hama3254/Crunchyroll-Downloader-v3.0#355]
**Describe the solution you'd like**
I would like to be able to download files from VRV as well, since that and crunchy have a similar structure, especially crunchys beta, I imagine this wouldn't be that hard to implement.

**Comment by True-King** [comment]
I second this As this app is the only one I like UI wise and not use commands

**Comment by hama3254** [comment]
> since that and crunchy have a similar structure, especially crunchys beta

i wonder why ...

![grafik](https://user-images.githubusercontent.com/52826614/131795238-5f08ab73-232a-4c10-b18f-b3910f521635.png)

![grafik](https://user-images.githubusercontent.com/52826614/131795253-6c9b461e-68db-4c29-8d8f-5cfe5db7a734.png)

The only issue i have (except that i need to use a VPN to access vrv from europe which i have) i would need an premium account for to test every of there Channel.

**Comment by Jaynator495** [comment]
I can set you up with one if you like, but we should probably take that conversation somewhere else. Do you have discord? If so, Jaynator495#6750

**Comment by hama3254** [comment]
@Jaynator495 "Added you on discord" or something

**Comment by True-King** [comment]
> I wonder why ...

Crunchyroll Owns VRV.CO and Crunchyroll is owned by SONY.

**Comment by hama3254** [comment]
> > I wonder why ...
> 
> Crunchyroll Owns VRV.CO and Crunchyroll is owned by SONY.

i know that, it was just a joke with vrv using the crunchyroll domain ...

any ways :

>since that and crunchy have a similar structure, especially crunchys beta

after a view little fixes i could add the vrv api call to the function for the crunchyroll beta website and it worked with just an missing/invalid hardsub tag.

![grafik](https://user-images.githubusercontent.com/52826614/131980904-5eb0ccc0-2b2f-4490-9de6-474cd6c41fec.png)

**Comment by hama3254** [comment]
a Test build has been uploaded : [Crunchyroll-Downloade-Chromium-VRV-Test.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
vrv has no own settings for now so it uses the settings of the Crunchyroll tab.
mass downloaded also works 
![grafik](https://user-images.githubusercontent.com/52826614/131990402-d0900426-1e70-49b4-bd4d-bd5448090e41.png)

**Comment by True-King** [comment]
> > > I wonder why ...
> 
> > 
> 
> > Crunchyroll Owns VRV.CO and Crunchyroll is owned by SONY.
> 
> 
> 
> i know that, it was just a joke with vrv using the crunchyroll domain ...
> 
> 
> 
> any ways :
> 
> 
> 
> >since that and crunchy have a similar structure, especially crunchys beta
> 
> 
> 
> after a view little fixes i could add the vrv api call to the function for the crunchyroll beta website and it worked with just an missing/invalid hardsub tag.
> 
> 
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/131980904-5eb0ccc0-2b2f-4490-9de6-474cd6c41fec.png)
> 
> 
> 
> 
> 
> 
> 
> 

Nah u good thanks for working on the issue. And appreciate it

**Comment by True-King** [comment]
> a Test build has been uploaded : [Crunchyroll-Downloade-Chromium-VRV-Test.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
> 
> vrv has no own settings for now so it uses the settings of the Crunchyroll tab.
> 
> mass downloaded also works 
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/131990402-d0900426-1e70-49b4-bd4d-bd5448090e41.png)
> 
> 

So will hybrid mode work on VRV

**Comment by hama3254** [comment]
> So will hybrid mode work on VRV

i did not test that much but as seen on the screenshot it worked.
The hybrid mode is made to work with every m3u8 file that uses the [`HLS` versions](https://alexzambelli.com/blog/2016/05/04/understanding-hls-versions-and-client-compatibility/) `3`, `4` and `5`

but if you run into issues please report them so i can improve the downloader or keep it working.

**Comment by Jaynator495** [comment]
Ran into an error popup when attempting to download Made in Abyss, https://vrv.co/series/G6W4M3V0R/MADE-IN-ABYSS
![image](https://user-images.githubusercontent.com/13039635/132054818-1e9bf361-091a-48bf-9b10-ed4b3c76dabf.png)
After hitting continue, it opens the browser. This even seems to happen if I try to use the same URL as you have used in your screenshot, and I even changed my settings to match the screenshot aside from dark mode.

**Comment by True-King** [comment]
> Ran into an error popup when attempting to download Made in Abyss, https://vrv.co/series/G6W4M3V0R/MADE-IN-ABYSS
> ![image](https://user-images.githubusercontent.com/13039635/132054818-1e9bf361-091a-48bf-9b10-ed4b3c76dabf.png)
> After hitting continue, it opens the browser. This even seems to happen if I try to use the same URL as you have used in your screenshot, and I even changed my settings to match the screenshot aside from dark mode.

Can confirm that I tested this and it has the same error and same behaviour

**Comment by hama3254** [comment]
this issue should be fixed and [`Crunchyroll-Downloade-Chromium-VRV-Test-U1`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) has been uploaded.

**Comment by True-King** [comment]
> a Test build has been uploaded : [Crunchyroll-Downloade-Chromium-VRV-Test.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
> vrv has no own settings for now so it uses the settings of the Crunchyroll tab.
> mass downloaded also works
> ![grafik](https://user-images.githubusercontent.com/52826614/131990402-d0900426-1e70-49b4-bd4d-bd5448090e41.png)

Hi so question? How do i paste multiple links at once like you have in the middle of the image?

**Comment by hama3254** [comment]
> Hi so question? How do i paste multiple links at once like you have in the middle of the image?

you can add a season of a show by using the the series url instead of a single episode.
then you get a selection of seasons and episodes.
i got the screen because of the option `redirect multi-download to the queue` where is was to check the urls and is not required but adds the option to remove urls if you want with a double click

**Comment by Jaynator495** [comment]
Movies appear to properly show thumbnails, but series from vrv show a red x as the thumbnail. In addition to this series on vrv use "season 0", rather than "season 1" when downloading to have separated by series name and season

**Comment by True-King** [comment]
> you can add a season of a show by using the the series url instead of a single episode.

> 
> then you get a selection of seasons and episodes.
> 
> i got the screen because of the option `redirect multi-download to the queue` where is was to check the urls and is not required but adds the option to remove urls if you want with a double click


Ohh how neat is this a new feature you added just like the MKV soft-sub option( thank you so much I really appreciate it. U made it a bit easy for me not to go in MKVTOOLNIX to mux it for my MEDIA-Server).

**Comment by hama3254** [comment]
> Movies appear to properly show thumbnails, but series from vrv show a red x as the thumbnail (So far this seems true for GATE and Made in Abyss).

i take a look at that but it seemed fine for me as you can see at the top

>In addition to this series on vrv use "season 0", rather than "season 1" when downloading to have separated by series name and season

it seems i did not catch that because i use the `ignore Season 1 for the file name` option.
now i wonder how should i handel that? ignoring  "season 0" like the option does or override the value to be treated as season 1 which would be affected by the setting if you want to ignore it.

![grafik](https://user-images.githubusercontent.com/52826614/132125173-8f0c21b0-4f9b-47cf-bd0b-1a86360d45a3.png)


>  a new feature

not that new it's already in there for Crunchyroll for a while now

![grafik](https://user-images.githubusercontent.com/52826614/132124965-9828e9e3-cac0-445d-9ce5-b29cef4ab84b.png)

and even funimation got it with there website update 

>with the new API i finally added the same style of mass download as on Crunchyroll and Anime On Demand. 
>Now i just need completely rewrite the download for Funimation for the new JavaScript based site.
>
>https://user-images.githubusercontent.com/52826614/118817256-5171c780-b8b3-11eb-8305-698cc03a9e6e.mp4
>

Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/271#issuecomment-844088997

**Comment by hama3254** [comment]
> > Movies appear to properly show thumbnails, but series from vrv show a red x as the thumbnail (So far this seems true for GATE and Made in Abyss).
> 
> i take a look at that but it seemed fine for me as you can see at the top

for some reason there are just no thumbnails inside the json response which can also be seen if i select that version inside the normal webbrowser  

![grafik](https://user-images.githubusercontent.com/52826614/132128055-14a147a1-398b-4bcf-ab2b-a79e9cf28472.png)

![grafik](https://user-images.githubusercontent.com/52826614/132128058-351a1e1e-1130-4380-854f-d2f202effdc0.png)


![grafik](https://user-images.githubusercontent.com/52826614/132128000-ca0818f4-758b-430d-8634-9212d116853c.png)

**Comment by True-King** [comment]
![image](https://user-images.githubusercontent.com/53064449/132145478-2c804798-f1a3-429a-a166-c0b9e6fa8848.png)
is this a a new UI or old?

**Comment by bybpow** [comment]
This seems to be an awesome idea. Hope can be implemented!

Ones question related to this: As VRV also has HIDIVE, will we able to get also HIDIVE assets or just CR?

**Comment by Jaynator495** [comment]
> This seems to be an awesome idea. Hope can be implemented!
> 
> Ones question related to this: As VRV also has HIDIVE, will we able to get also HIDIVE assets or just CR?

So far, I am able to download from all vrv channels, including CR, HIDIVE, Rooster Teeth, VRV Select, and the others

**Comment by NatsuFT36** [comment]
Hi, I was trying to run the new version with VRV and it does not enter the program and the U4 version if it lets me enter

**Comment by hama3254** [comment]
@NatsuFT36 please add more details what happen.
If the downloader is not starting at all please check the event viewer for details.
it also helps if you could add at what version it stopped working for you so i can see what change could cause your issue.

**Comment by NatsuFT36** [comment]
What happens is that when I run the VRV program it does not come out and I check that from the task manager and the version I have is Windows 10 64-bit and when I run Chromium-U4 if I get it but without being able to download the series full of Funimation

**Comment by NatsuFT36** [comment]
Right now I tried it with a new folder and if it executes me but the strange thing is that I use the same folder where I have all the series and it does not execute me

**Comment by hama3254** [comment]
I'm not sure what you mean with `execute` but it is known that Windows can only use up to 260 characters for a file and only 247 for the path of the file.
This can be a problem with some of the long anime names or if you already use a long path to the download folder.
Please check if that is the case.

**Comment by Jaynator495** [comment]
> I'm not sure what you mean with `execute` but it is known that Windows can only use up to 260 characters for a file and only 247 for the path of the file.
> This can be a problem with some of the long anime names or if you already use a long path to the download folder.
> Please check if that is the case.

Luckily, in windows 10, you can disable the max file path character limit, though for the software it has to have it enabled in the manifest. More details here: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

In addition, you also have to on the PC run a PowerShell command to enable long paths - it's one of the first things I do on any personal PC. You can do this by running this in an elevated PowerShell.
```powershell
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

**Comment by janilssonn** [comment]
Error Funimation 

Start loading: 18/09/2021 09:13:44
get html
18/09/2021 09:13:47.555
https://www.funimation.com/v/wonder-egg-priority/the-domain-of-children?lang=portuguese(Brazil)
https://title-api.prd.funimationsvc.com/v1/shows/wonder-egg-priority/episodes/the-domain-of-children/?region=BR&deviceType=web&locale=pt
1
processing :https://title-api.prd.funimationsvc.com/v1/shows/wonder-egg-priority/episodes/the-domain-of-children/?region=BR&deviceType=web&locale=pt
https://title-api.prd.funimationsvc.com/v1/shows/wonder-egg-priority/episodes/the-domain-of-children/?region=BR&deviceType=web&locale=pt
error- getting v1Json data
System.Net.WebException: The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF
   em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   em System.Net.WebClient.DownloadString(Uri address)
   em Crunchyroll_Downloader.Main.GetFunimationJS_Video(String v1JsonUrl, String v1JsonData) na D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:linha 4730
https://title-api.prd.funimationsvc.com/v1/shows/wonder-egg-priority/episodes/the-domain-of-children/?region=BR&deviceType=web&locale=pt
get html
18/09/2021 09:14:36.953
