### ISSUE TITLE
Funimation not working.

### ISSUE THREAD

**Issue by proall** [hama3254/Crunchyroll-Downloader-v3.0#356]
Hey,
I tried to Download Anime from Funimation but when i put the link (of the Episode) its says
Found Episode,
Found Resolution

and after that its showing the episode download proccess and its just crash after that.

i tried also with the addon but its just stack on "Status: 11 Downloads in Queue"

Edit: If its crash to you, then, turn off the Hybrid Mode"

**Comment by hama3254** [comment]
I can not see the issue on a quick look.
please add the version you are using, you can find that information in the `About` section of the Settings.
the episode you tried would also be helpful to know.
