### ISSUE TITLE
CPU overheats when downloading from funimation

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#358]
Whenever I download from Funimation my CPU starts to overheat because it's starts to use all of its processing power. This only happens when downloading from Funimation. Is this normal?
<img width="1920" alt="cpu temparature" src="https://user-images.githubusercontent.com/75436296/133804543-f437a774-8bd3-47ff-806e-e9bd5f8ad102.png">

**Comment by hama3254** [comment]
based on the size of the video you are using Hard Subs at funimation, other than Crunchyroll they don't have any hardsubs ready to download that why it is labelled `Hard Subtitle (post-processed)`  
![grafik](https://user-images.githubusercontent.com/52826614/133807274-1bb5a01a-8b1f-4ff9-97cf-6a5f793a7799.png)

My preferred solution to that would be to use Soft Subs that are merged into the video file itself and are not literally written on every frame of the video. 
The setting can be found on the `Output` page.


if you want to have real hardsubs then i might suggest using one of the two `nvenc` label options of the ffmpeg command, this will use your GPU which has hardware for that exact taks build into it [(It called Nvidia NVENC)](https://en.wikipedia.org/wiki/Nvidia_NVENC)
![grafik](https://user-images.githubusercontent.com/52826614/133808190-90d35251-c852-4731-aa33-11cccde4e42e.png)

**Comment by Azul772** [comment]
I used the nvec option and the CPU usage went down by a lot but in exchange the output video file was bigger in memory than when I didn't use the nvec option. Instead of a few MB (300 - 280 MB) the new file was 1.2 GB. Thank you but I will stick to the heat in order to save space.

**Comment by hama3254** [comment]
> I used the nvec option and the CPU usage went down by a lot but in exchange the output video file was bigger in memory than when I didn't use the nvec option. Instead of a few MB (300 - 280 MB) the new file was 1.2 GB. Thank you but I will stick to the heat in order to save space.

you can change the number on the right to get a smaller file with the cost of the quality
