### ISSUE TITLE
How to batch download in Funimation

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#359]
With the new crunchyroll downloader version the funimation button on the browser is no longer there and when I paste the anime series to download it just says "no video found, checking traffic". I then have to download each episode one by one.
<img width="679" alt="bad batch" src="https://user-images.githubusercontent.com/75436296/133833646-17b3e583-a020-4921-a185-2928e6d06750.png">

**Comment by hama3254** [comment]
due to changes on the funimation website the downloader is not fully functional currently this includes the mass downloader and everything with the new `/v/` in it's urls. 
i am working on that but they have new JSON format which mean i have to rewrite the whole mass download selection.

**Comment by Azul772** [comment]
okay
