### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by aitorhergon** [hama3254/Crunchyroll-Downloader-v3.0#360]
Hello there,

I have tried on two different computers and when the screen locks, the program freezes. It does not allow any site to be clicked and I have to close it forced.

I'm sorry for my English, it's not my language.

Version i tried:

- v3.8-Beta-U13
- v3.7.8.6
- Downloader-v3.x-Chromium ---> Works but not have US cookie options yet :(

Thanks!

**Comment by hama3254** [comment]
This seems to be the same issue as in #319 that is why the Chromium version works.
The other two are outdated and don't get updated any more, and the US cookie does not work on the Crunchyroll Beta website that why I never added it to the Chromium version.
