### ISSUE TITLE
Funimation Issues

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#373]
I made a view fixes for funimation with [Crunchyroll-Downloader-Chromium-U5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases) it should work now, if not this is the place to comment your specific issue.
![grafik](https://user-images.githubusercontent.com/52826614/137364310-86f5c135-df64-4606-876d-94a28d1bcd64.png)

**Comment by janilssonn** [comment]
Hello, there are some bugs in the new version, downloading with Funimation equal to CR only to use one season at a time and then you have to close the program and open it again to be able to download another anime, otherwise you'll be downloading the same anime infinitely other than the sometimes it doesn't create a folder, but what I really wanted was to have something to fix the crashing of the video and audio of animes downloaded from CR only happens with animes downloaded from there, the ones from funimation have perfect audio and video without crashing or anything, but from CR has an episode that crashes. can you help me?

**Comment by hama3254** [comment]
> one season at a time and then you have to close the program and open it again to be able to download another anime, otherwise you'll be downloading the same anime infinitely

That interesting but seems a smaller issue since everything except the end urls work fine, i see what I can do there.



> the crashing of the video and audio of animes downloaded from CR only happens with animes downloaded from there, the ones from funimation have perfect audio and video without crashing or anything, but from CR has an episode that crashes.

Are you using the `hybrid mode` ? that the only difference in the downloade i can think of since Funimation uses `v4` m3u8 files with crunchyroll uses `v5` or `v3` which needs different code to process.

@pruebark9 

> PS: The chrome extension to add several chapters at once does not work anymore?


I didn't test it for a while now, i take a look at it later

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/137484648-15e05a90-b342-4ca1-80f8-37bc82edb5e8.png)
does this have an influence?

**Comment by janilssonn** [comment]
I understand, so it doesn't work for me my internet is 800mb I download very fast in normal mode

**Comment by janilssonn** [comment]
[log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/7354460/log.txt)
in hybrid mode i had no problem with image freeze in at least two episodes i watched

**Comment by hama3254** [comment]
if fail to see any issue there, did you get any kind of error?
![grafik](https://user-images.githubusercontent.com/52826614/137522885-059f6e36-eeac-4361-a35e-6565e54e990f.png)

**Comment by hama3254** [comment]
> Is there an updated application (Non browser) version? The last release is from April and it keeps locking up during downloads. I attempted the get files version and running the binary but it hard crashes out.

The last released version is [Crunchyroll-Downloader-Chromium-U5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases) other version are not updated anymore.
if you have issues with this version i need a report what's not working.

**Comment by Serpentstar** [comment]
found a different issue.  One of my other security endpoint applications is causing an issue.  Will keep looking at it.  Thanks for your program.  I think it is pretty damned cool.

**Comment by pruebark9** [comment]
I have tried again and the chrome plugin is working.

I don't know what you have done but this is the best version I have used so far, the hybrid mode downloads faster than before and I always had it enabled. 

And the Crunchyroll download starts in less than 5 seconds of adding the link, before it took up to 10.

And in Funimation I had to try at least 5 times to start the download, now it does it the first time. It takes 10-15 seconds for no matter what, the good thing is that it starts it.

The only error that I see that is still present is that in Funimation, I have set the dub language as Spanish, before when I downloaded a chapter that did not have dubbing, it automatically downloaded the Japanese version. Now for some time, if it doesn't have Dub, it comes out a message saying that it hasn't found the dub and it doesn't do anything else.

Thank you very much for your work.

Translated with www.DeepL.com/Translator (free version)

**Comment by pruebark9** [comment]
I have tried again and the chrome plugin is working.

I don't know what you have done but this is the best version I have used so far, the hybrid mode downloads faster than before and I always had it enabled. 

And the Crunchyroll download starts in less than 5 seconds of adding the link, before it took up to 10.

And in Funimation I had to try at least 5 times to start the download, now it does it the first time. It takes 10-15 seconds for no matter what, the good thing is that it starts it.

The only error that I see that is still present is that in Funimation, I have set the dub language as Spanish, before when I downloaded a chapter that did not have dubbing, it automatically downloaded the Japanese version. Now for some time, if it doesn't have Dub, it comes out a message saying that it hasn't found the dub and it doesn't do anything else.

Thank you very much for your work.

**Comment by hama3254** [comment]
> the moment I try to do a download, the program tries to connect to China IP 42.250.217.131which my local network has GeoIP blocked.

The downloader loads the website you want to download from like a normal webbrowser and then process the data it finds during loading or inside the HTML of the website.
I have no influence what you try to access or what some websites use in the background.


> I don't know what you have done but this is the best version I have used so far, the hybrid mode downloads faster than before and I always had it enabled.
> 
> And the Crunchyroll download starts in less than 5 seconds of adding the link, before it took up to 10.

That sounds more like either your internet has become faster or your computer has, the normal crunchyroll website needs to load then i have all data i need so if the websites load  a view seconds faster the downloader can start the processing sooner.

For the hybrid mode i use the PCs `logical processors` for a baseline of threads i can run at once per download so better computer might increase the speed if the network can handle that. 


> And in Funimation I had to try at least 5 times to start the download, now it does it the first time. 

That was my greatest issue, something that works sometimes and sometimes not is hard to fix since if you look for an error it does not happen...

>It takes 10-15 seconds for no matter what, the good thing is that it starts it. 

That normal since i need to make sure that the video had time to load before i can see if i got something inside the network traffic.

**Comment by NatsuFT36** [comment]
In the chapters, for example of Mieruko-chan when I download it in the Japanese language, in the information I get that the language is in English and the dubbing has not yet debuted and they barely go in episode 3.
![Captura de pantalla (21)](https://user-images.githubusercontent.com/51544427/137633763-063f130f-e552-4805-8ef9-72aa0c2f76aa.png)

**Comment by hama3254** [comment]
> It would be good if I added Chinese language since Chinese series appear on Funimation such as Link Click and Ancient Girl's Frame

You probably can not even download that, the dub setting defaults to Japanese as value and I have no proper error Handling yet...

**Comment by hama3254** [comment]
i uploaded a test version that worked for me [`Crunchyroll-Downloader-Chromium-NewFuni`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)
for a better overview i will lock this issue here so please use the duplicate #382
![grafik](https://user-images.githubusercontent.com/52826614/139485913-4136bd14-5473-4341-a43d-f02a176b6064.png)
