### ISSUE TITLE
Appliation related files/folders appearing in Download destination folder

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#374]
Since I started using the Chromium version, the folder where I have files being delivered to is now being flooded.

000003.log
Cache
Code Cache
Cookies
Cookies-journal
CURRENT
databases
File System
Local Storage
LocalPrefs.json
LOCK
LOG
LOG.old
MANIFEST-000001
Network Persistent State
QuotaManager
QuotaManager-journal
Reporting and NEL
Reporting and NEL-journal
Session Storage
TransportSecurity
Visited Links

Is there a way to force these to be created where the the application is being launched from?  These cropped up when I began using the chromium version.

I do have to say the Chromium version is much more stable.  Thank you.

**Comment by hama3254** [comment]
The output folder and the profile folder are different ones by default and the profile folder is chosen to be outside of the downloader main folder to allow an easy upgrade to the next version.
![grafik](https://user-images.githubusercontent.com/52826614/137637701-cc1f5bc7-1179-4777-a3fe-51ebc98ea706.png)

**Comment by Serpentstar** [comment]
Perfect.  That was exactly what I was looking for, another stupid user (me) issue resolved.
