### ISSUE TITLE
DEBUG_Funimation

### ISSUE THREAD

**Issue by Ryahn** [hama3254/Crunchyroll-Downloader-v3.0#38]
I know its still experimental but I do have a premium account but its not using it. I did log into the site as well but somehow its bypassing that.

Below is the error I get for any new releases that require premium. I can watch it just fine on the site.
![image](https://user-images.githubusercontent.com/2089646/87857394-54e39d80-c8f4-11ea-9054-2ac2a58790ba.png)

**Comment by hama3254** [comment]
> I know its still experimental but I do have a premium account but its not using it. I did log into the site as well but somehow its bypassing that.

Thanks for the info, this helps a lot.
It's not bypassing it, i just forgot to add the cookie from the browser to the request, i changed it :

![grafik](https://user-images.githubusercontent.com/52826614/87872442-e87ea200-c9b8-11ea-9538-30cf6fcd9096.png)

you can now get the updated version here:
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Debug_Funimation

**Comment by Ryahn** [comment]
It works
![image](https://user-images.githubusercontent.com/2089646/87881732-2f749380-c9c9-11ea-8f8f-9187b5e95514.png)

Should I open a new ticket for this?
![image](https://user-images.githubusercontent.com/2089646/87881715-17047900-c9c9-11ea-9ea6-43eec32ebc21.png)

The videos show they are downloading but they do not save and I am not sure where they are saving to. I have a directory specified but I dont think its parsing the name correctly.
![image](https://user-images.githubusercontent.com/2089646/87881766-69459a00-c9c9-11ea-99df-a47340178668.png)

From testing it on other shows, its special characters that are throwing that error.

There is also an issue where its not grabbing the subs for the latest episode that is under premium. Deca-Dence and Uzaki-chan Wants to Hang Out! both had no subs downloaded. It downloads for the all other episodes so far.
[Uzaki-chan Wants to Hang Out! Episode 2 .log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/4944342/Uzaki-chan.Wants.to.Hang.Out.Episode.2.log)

Not sure if that log file will help at all. If there are any other places where I can find a log, I will gladly upload it to help troubleshoot.

**Comment by hama3254** [comment]
Windows does not like more than one ':' in the path, i have now added the same cleaning steps like on crunchyroll (replace illegal characters with space and remove double spaces). 
and it seems to work : 
![grafik](https://user-images.githubusercontent.com/52826614/87883680-40dd9000-ca09-11ea-993c-b6df5a8b8697.png)

but for the subs of the two other episodes i did not find any problem, everythings seems fine for me. 
However i have added the .vtt and .dfxp to be the backup subs, later i may be allow to change the priority but for now it is .srt > .vtt > .dfxp 

the release is now updated!

**Comment by Ryahn** [comment]
> but for the subs of the two other episodes i did not find any problem, everythings seems fine for me.
>However i have added the .vtt and .dfxp to be the backup subs, later i may be allow to change the priority but for now it is .srt > 
 > .vtt > .dfxp
I am still having issues with the sub on latest episode. Everything else is working fine now. If you like, I could purchase funimation premium for you, so you can test it.

**Comment by hama3254** [comment]
> 
> I am still having issues with the sub on latest episode. Everything else is working fine now. If you like, I could purchase funimation premium for you, so you can test it.

i already got access to a premium account from another user so it's not really necessary but it would be helpful with this type of errors:
![grafik](https://user-images.githubusercontent.com/52826614/88097799-0a367f80-cb99-11ea-8199-94a9527173f0.png)

i still don't see any issue with the way i was searching for the subtitle file(s), but i changed it to be later simpler to modify for other languages so you can try it again.

the new version is now avalaibe :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Debug_Funimation

**Comment by Ryahn** [comment]
Sorry for the late reply, IRL got busy. I will test this by tomorrow and let you know.

**Comment by hama3254** [comment]
@Ryahn if you have any new issue with the downloader you can open a new issue
