### ISSUE TITLE
Funimation Possible features

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#380]
Bitrate selection
![grafik](https://user-images.githubusercontent.com/52826614/139137876-4ba8251c-a5b4-4b94-8047-8fc51b73628e.png)

**Comment by hama3254** [comment]
Changes for [`Crunchyroll-Downloader-Chromium-U8:`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

With the new API i got easy access to the data for every available stream, this means i need to make some choices which stream i use.
The good thing is at this point i don't need to check for any account stuff since the API only gives available streams back.

The API gives a list with one "primary" stream back, this stream is always used by the downloader if no other stream is found machting your settings.
This means `Disabled` as Dub setting will always use that stream.
![grafik](https://user-images.githubusercontent.com/52826614/139946666-23893b08-86cc-4187-802d-3315fe7795af.png)

If you have selected a dub language inside the settings it should default to the `uncut` version of that stream if one is available for you (might require a premium membership). 
![grafik](https://user-images.githubusercontent.com/52826614/139946274-0061e2f2-1fef-4c5f-a923-e30fae41bc31.png)

**Comment by NatsuFT36** [comment]
The chapters that are downloaded in Crunchyroll and Funimation create a double space for me and that when the download finishes the folder is not automatically deleted
![image](https://user-images.githubusercontent.com/51544427/141741854-8ad413be-35cd-4443-977a-fa1e3e59aed4.png)

**Comment by hama3254** [comment]
@NatsuFT36 you probably pressed "Yes" there :
just disable the hybrid mode and enable it again and select "No"
![grafik](https://user-images.githubusercontent.com/52826614/141829389-a152d000-06b2-4bbc-a33d-de79b5ea94a2.png)

**Comment by kanohn** [comment]
@hama3254 I don't know if someone was talked about it, but in my tests the program does not allow us to put funimation url's on the queue.

I mean, url's for different titles, like: ep1-title1, ep5-title2, etc..

Queue only works if we put the title show and select from ep to ep but not the way like i said before..

This could be implemented?

thank you.
