### ISSUE TITLE
Funimation issues

### ISSUE THREAD

**Issue by bia160508** [hama3254/Crunchyroll-Downloader-v3.0#382]
Hi, I try to download the series but it has an error that does not pass check traffic
Version : Crunchyroll-Downloader-Chromium-U6.1

**Comment by DatCrazyDelphox** [comment]
Just to document here, I tested the new funimation release both on windows and Linux (wine).

Both show similar results with hybrid download crashing randomly while downloading and softsub merged in mkv does not work correctly for funimation downloads

**Comment by hama3254** [comment]
> Adding up, seems like the resolution selection of some episodes is not working correctly. Even if you set 1080p and funimation has the episode with this resolution, it downloads with a lower resolution setting

if is just for some episodes then i need an example.


> Both show similar results with hybrid download crashing randomly while downloading and softsub merged in mkv does not work correctly for funimation downloads

There is a known issue where everything is working with the hybrid mode but it still lists the key files as failed which can trigger the error detection if set to 1 or 2.

**Comment by pruebark9** [comment]
Once again, thank you for your work. Last night the new version was working perfectly but today, again it fails.

It seems that Funi doesn't like to have his videos downloaded :(

**Comment by hama3254** [comment]
@pruebark9 i don't see any issue right now, i made a view fixes for the Hybrid mode, Merged subs metadata and Thumbnail but the download itself seems fine.
![grafik](https://user-images.githubusercontent.com/52826614/139560394-62cd99e7-1337-405a-a7bb-37486e057d58.png)

**Comment by DatCrazyDelphox** [comment]
Seems to work fine now, although hybrid download seems still broken to me.

Happened while trying to download any episode from noragami or other series as an example

It gives an 'access error - retrying' message and gets stuck there

and the log that it generates is the following:
![img](https://user-images.githubusercontent.com/29310153/139575494-14916869-863a-41c9-be3f-35732eaec4d7.png)

**Comment by hama3254** [comment]
there is an issue where the retry would try indefinitely until the download worked.
This however has nothing to do with the reason the download of that part fails, that is a simple timeout which is set to 30 seconds.
I fix the issue with the indefinitely attempts with the next version.

**Comment by pruebark9** [comment]
> @pruebark9 i don't see any issue right now, i made a view fixes for the Hybrid mode, Merged subs metadata and Thumbnail but the download itself seems fine. ![grafik](https://user-images.githubusercontent.com/52826614/139560394-62cd99e7-1337-405a-a7bb-37486e057d58.png)

Well, since yesterday I get this error.

https://i.imgur.com/tQHhQnC.png

**Comment by DatCrazyDelphox** [comment]
> > @pruebark9 i don't see any issue right now, i made a view fixes for the Hybrid mode, Merged subs metadata and Thumbnail but the download itself seems fine. ![grafik](https://user-images.githubusercontent.com/52826614/139560394-62cd99e7-1337-405a-a7bb-37486e057d58.png)
> 
> Well, since yesterday I get this error.
> 
> https://i.imgur.com/tQHhQnC.png

To me seems like funimation blocked your ip or they changed something in the api (again)

**Comment by pruebark9** [comment]
> > > @pruebark9 i don't see any issue right now, i made a view fixes for the Hybrid mode, Merged subs metadata and Thumbnail but the download itself seems fine. ![grafik](https://user-images.githubusercontent.com/52826614/139560394-62cd99e7-1337-405a-a7bb-37486e057d58.png)
> > 
> > 
> > Well, since yesterday I get this error.
> > https://i.imgur.com/tQHhQnC.png
> 
> To me seems like funimation blocked your ip or they changed something in the api (again)

I use VPn and I tried with the U7 and it still comes out the same T_T

**Comment by hama3254** [comment]
i just checked and i get that issue when i try to download something that requires the premium subscription without be logged in or with my free account.
Please check if that is the issue for you too.
Note that funimation doesn't bother to show you what episodes needs a subscription if you have one.
![grafik](https://user-images.githubusercontent.com/52826614/139596168-af21a600-05e4-4f69-8252-89877dc57118.png)

**Comment by pruebark9** [comment]
God, it's true. I got the message that I was not logged in. I just logged into the app and it works.

Sorry for the delay.
