### ISSUE TITLE
Problem with Windows 11

### ISSUE THREAD

**Issue by soares23** [hama3254/Crunchyroll-Downloader-v3.0#386]
Hi,

The application on start is making .net framework error and don't work anymore.

The error you can see on the link below.
https://imgur.com/YuPAkPv

Thanks to check it and maybe fix it as soon as possible and sorry for my bad english.

Have a nice day.
Best Regards

**Comment by hama3254** [comment]
This does not look like any Windows related issue more like a missing file, please re-download the zip file of the latest version and try again.
Note that the GitHub project is missing some files that are more than 100MB because GitHub did not like files that size.

**Comment by soares23** [comment]
HI, is ok now. It was a problem with visual c++ package a had install the x64 version and not the x86 version and the project need x86 . Thanks for your reply have a nice weekend.
