### ISSUE TITLE
Funimation does not work

### ISSUE THREAD

**Issue by devamv** [hama3254/Crunchyroll-Downloader-v3.0#388]
Version :  
V3.8-Beta
V3.8.0.8 Chromium-U7

1.- I copy the url of the video
2.- I add it to the software
3.- Starts a countdown from 10 to 0
4.- I get that message "looking for video file".
5.- And finally the following error window appears

1.- https://i.imgur.com/kTeqjQQ.png
2.- https://i.imgur.com/cKrxJZr.png
3.- https://i.imgur.com/EAwCPNV.png
4.- https://i.imgur.com/qEAXzkM.png
5.- https://i.imgur.com/VG9t7N9.png

**Comment by hama3254** [comment]
Based on the first screenshot you are not logged in or have no premium account inside the browser but that episode is clearly requiring a subscription.
If you have a premium account please make sure you are logged in inside the downloaders Webbrowser and try again.

**Comment by devamv** [comment]
I have seen that they have uploaded a new version of the software
- v3.x
- v3.8.0.9 Chromium-U8
I have downloaded it and used it to see if it changed anything, but it is still the same

1.- I created a free account (with access to HD-1080 playback).
2.- I chose unblocked anime that does not require premium.
3.- I copied the URL of the chapter.
4.- I pasted it into the program
5.- The same countdown appears as the previous time.
6.- The following message also appears
7.- It ended with the same error.

1.- https://i.imgur.com/wee1za8.png
2.- https://i.imgur.com/IN4UoUH.png - https://i.imgur.com/hCPxKQR.jpeg
3.- https://i.imgur.com/5qc2A9W.png
4.- https://i.imgur.com/oQRzr1w.png
5.- https://i.imgur.com/FJI68kU.png
6.- https://i.imgur.com/Cf8IOcS.png
7.- https://i.imgur.com/Vtl3FfU.png

What is the problem? the selected chapters and series can be played freely in the browser, in 1080p and with subtitles, even with IDM I can download them, the problem is that it downloads a .ts file, and then I can't play it because of an apparent error.

If the problem lies in the user accounts, could you show me what a working URL looks like, to compare them with each other (use this very chapter as an example).

My URL: https://www.funimation.com/v/assassination-classroom/assassination-time

Your URL: ?


PS: What is the correct configuration here? https://i.imgur.com/2BdWtbi.png

**Comment by hama3254** [comment]
> PS: What is the correct configuration here? https://i.imgur.com/2BdWtbi.png

This has nothing to do with the current issue but i would suggest that you select at least one of the subtitle formats.

I need to take a look later but it would help if you could add the console output.
The console is hidden and can get displyed by clicking the bar at the bottom there are more details about the processing.

**Comment by dev-mv** [comment]
Hi, I have downloaded the latest version of the software and configured the Funimation section with all its options, and I have tried downloading chapters even without having an account started, and the download starts working, it is not clear to me what has changed, but now it works.

release: v3x / v3.8.0.9 Chromium-# 389

- downloading: https://i.imgur.com/xoyJvGx.png
- setup: https://i.imgur.com/AKCmSK3.png

pd: i'm the same user with different account :p

**Comment by hama3254** [comment]
@dev-mv thanks for the feedback i found the issue by accident while checking the output of a new debug value that was missing until now and there i have seen that the device type parameter was missing for the request.
this is fixed with the latest test version.
