### ISSUE TITLE
Funimation not working

### ISSUE THREAD

**Issue by FilipLac** [hama3254/Crunchyroll-Downloader-v3.0#389]
Hello,
today i wanted to download for first time from funimation and it is not working. In my normal browser it works normally, but when I try playing it in integrated browser in your app I am getting this error.
![image](https://user-images.githubusercontent.com/93822443/140607248-2add4bca-5188-46af-a83e-611779ccbd8e.png)
Even when I tried another show it only showed me this same error.
I am using newest release and also i tried logging in with free account but with no luck. Is there anything that I can do to fix this ?
I can also upload here log of me downloading it if you want to see what it showed me.

**Comment by FilipLac** [comment]
And when I try to download it I am getting almost same error as in issue #388 but it is in Main.vb:line 5220

**Comment by hama3254** [comment]
That the video does not load inside the browser is normal and should not affect the download.

I can not see any overall issue right now, to see that your issue is in `Main.vb:line 5220` you would need to view the console since that one is only semi-transparent to the user.
Please add the console log and the episode you tried that way i can try to reproduce your issue.
![grafik](https://user-images.githubusercontent.com/52826614/140608281-0f23c55b-35ed-4a9b-ac42-ef72fbb12a88.png)

**Comment by FilipLac** [comment]
Show: https://www.funimation.com/shows/full-dive-this-ultimate-next-gen-full-dive-rpg-is-even-shittier-than-real-life/
2nd show: https://www.funimation.com/shows/wonder-egg-priority/?qid=
First I tried multidownload but because of errors I then tried first episode.
Program version: v3.8.0.9 Chromium-U8
hybrid download enabled
Update: before i was able to post this my computer run out of battery and when I tried it again it is working for some reason :
[ErrorFunimation.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/7490466/ErrorFunimation.txt)
D

**Comment by FilipLac** [comment]
Btw one question. How can I enable hardsubs on funimation videos ?

**Comment by hama3254** [comment]
>Btw one question. How can I enable hardsubs on funimation videos ?

Hard subs are currently not implemented. 

[For the other issue i uploaded Crunchyroll-Downloader-Chromium-389 please try and see if it fixes your issue](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by FilipLac** [comment]
Ok, thanks. I will download it and try it as soon as possible.

**Comment by FilipLac** [comment]
Thanks for updated version. It looks like you fixed it. Thank you very much for that
