### ISSUE TITLE
Wakanim.tv Integration (German Equivalent of Funimation)

### ISSUE THREAD

**Issue by ScarVite** [hama3254/Crunchyroll-Downloader-v3.0#39]
It Would be amazing, if you could enable downloading from wakanim.
https://www.wakanim.tv/de/v2 is the German equivalent of Funimation (Funimation bought Wakanim a few years ago)
I Can't even try to download with your network scan feature, as Im Getting "Errorcode: 102630" when i'm trying to play a video.
If you want to try it on your own, they have premium and free episodes. 
You just need a german vpn and a free account.
It's like Crunchyroll and only the newest Episode is "Premium Only".
![Crunchyroll_Downloader_F8NBpLBjaP](https://user-images.githubusercontent.com/43887376/88475421-eaec7900-cf2f-11ea-90bc-0e0d9007ce52.png)

Would Be Truly Amazing, if you could add Full Support

**Comment by hama3254** [comment]
As stated in an other issue, it's not possible due to there DRM system.

>Wakanim ist nicht Supportet und wird auch nicht gehen, da sie einen Kopierschutz auf ihren Streams haben. Die einzige Möglichkeit die ich kenne das zu umgehen wäre die [analoge lücke](https://www.heise.de/newsticker/meldung/Urteil-bestaetigt-Existenz-der-analogen-Luecke-im-Urheberrecht-142631.html) also einfach den Bildschirm mit Ton aufnehmen aber dafür eine Software zu entwickeln wäre wettbewerbswidrig.

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/14#issuecomment-592469846_

**Comment by ScarVite** [comment]
Shouldn't it be possible, since wakanim is using widevine, which is the same drm crunchyroll is using

**Comment by hama3254** [comment]
> 
> 
> Shouldn't it be possible, since wakanim is using widevine, which is the same drm crunchyroll is using

Crunchyroll has still drm free streams, if they get removed someday i wont be able to download from crunchyroll eighter

**Comment by ScarVite** [comment]
oh ok, didnt knew that. 
Too bad

**Comment by hama3254** [comment]
@ScarVite  if you want to know more you can add me on Discord : Hama#4155
