### ISSUE TITLE
Unable to download more than 3epi on funimation at a time

### ISSUE THREAD

**Issue by devanshkasotia** [hama3254/Crunchyroll-Downloader-v3.0#390]
Fix this issue 
Always says checking traffic-10
Using U8 latest version
Unable to download more than 3 episode
(Able to download 12 episodes on crunchyroll at a time)
FIX IT!

**Comment by hama3254** [comment]
Please watch your language.
Your `FIX IT!` with all caps and the "!" implies [shouting](https://en.wikipedia.org/wiki/All_caps#Association_with_shouting) which is not appropriate here.

For your actual issue please add as much details as possible, what account type are you using?
when and how does the 4th download fail?'
What settings are chosen?

**Comment by FreddyT-Power** [comment]
> Fix this issue Always says checking traffic-10 Using U8 latest version Unable to download more than 3 episode (Able to download 12 episodes on crunchyroll at a time) FIX IT!
You've ever been told to say the MAGIC WORDS?: **PLEASE??**
