### ISSUE TITLE
Funimation download related issues

### ISSUE THREAD

**Issue by devanshkasotia** [hama3254/Crunchyroll-Downloader-v3.0#392]
Earlier I didn't mean to shout I was just very irretate because of listed down problems--(using U-8 version)
1>In funimation downloading it took 15-20 seconds each to download an episode(inrespect to it take 5-8 sec in crunchyroll)[Says check-traffic for 10 second each time on funimation)

2>I am currently only able to download 4 episode max at a time I am using $7.99 version.
[Status bar in add video screen freeze at error listed in image attached]

Currently major issue is--- point no.2 following no.1
[IMG_20211111_172630351](https://user-images.githubusercontent.com/25553664/141294570-1b113876-5f42-4efc-96ea-4c227f0cb97e.jpg)

**Comment by hama3254** [comment]
> 1>In funimation downloading it took 15-20 seconds each to download an episode(inrespect to it take 5-8 sec in crunchyroll)[Says check-traffic for 10 second each time on funimation)

You can not compare the old Crunchyroll website and Funimation.
Crunchyroll has everything the downloader needs inside the old website while funimation uses scripts to load everything.
This means i have to load Funimation, catch the API calls then make the first API calls myself then processing that data like the name, season, episode and other data to make the second request which gives me the video streams and subtitles.


> 2>I am currently only able to download 4 episode max at a time I am using $7.99 version. [Status bar in add video screen freeze at error listed in image attached]
> 
> Currently major issue is--- point no.2 following no.1 [IMG_20211111_172630351](https://user-images.githubusercontent.com/25553664/141294570-1b113876-5f42-4efc-96ea-4c227f0cb97e.jpg)

does just the text freeze or the whole application?

**Comment by devanshkasotia** [comment]
Text freeze just as many time I bash download button it didn't matter to that text(it freeze stating- check traffic-10)

-Also noticing after some time of using funimation permanent disable user from downloader(I have to remove and reextract it from rar every time this happen)

-is currently there is any way to download whole season simultaneously or in a batch file?

**Comment by hama3254** [comment]
> -is currently there is any way to download whole season simultaneously or in a batch file?

You can use the overview url then you can select a season and the episodes you want to download.


> -Also noticing after some time of using funimation permanent disable user from downloader(I have to remove application and reextract it from rar every time this happen)

I can not see any reason that would make such a behavior possible, everything the downloader saves is not i  the directory of the downloader so you get the same settings every time you extract it.

> Text freeze just as many time I bash download button it didn't matter to that text(it freeze stating- check traffic-10)

the text can only freeze if the downloader itself freezes since it just a loop that gets executed 10 times for each a second to gives funimation time to get it's website loaded fully.

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/141677943-587d99c5-715e-4c9b-9cff-e5d29b4c2f09.png)
![image](https://user-images.githubusercontent.com/16007846/141677955-1d6c1b6b-d27c-413a-8f86-d23af25ee6b4.png)
you cannot download any videos from Funimation

**Comment by hama3254** [comment]
@janilssonn  please add the log file otherwise i can not see any issue :

![grafik](https://user-images.githubusercontent.com/52826614/141679804-a9ed11ca-1c30-439a-9518-f6739abee509.png)

**Comment by janilssonn** [comment]
14/11/2021 16:47:38 -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" -headers "ACCEPT-ENCODING: *" -i "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634strnv-hl151_streaming_video_1280_720_3000000_index.m3u8?Key-Pair-Id=APKAJKRAL73VQHXFMW6A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MDI3Mi8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2OTIyODU0fSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzY5MTU2NTR9fX1dfQ__&Signature=MYDHfSzZ9plj-TOlCf1d2dHuYXfqDZxcqFrkbqZMJnWbF6w49ZiRzG-dwvoZWVfWNmiwpYyVr8LJb41WaoHnmN-i5VVHfg3onr2B0xsV9fboX~nAUAt2huqGEAArQijfSlFn6e0QVB2l0sWbexqulKDHyxIAZ3oA4HuslLFT6kyLv51LrVqwYRssmke9CkTNcmxIKxKjJNR1ZGvV1GyzFK8eQagzvspMZNU~2H7Rw7gDf5AfYTTxVragbRWDBJqjm7Y-ElKMd4FdVvOaGKcPofPox7X-rF-VorZCsE2sp5RFi4-6MwKw9Wb8nkLTWaXI9vOg88yOQ~t7~haSyYyp7A__" -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" -i "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634strna-hl102_streaming_audio_2_por_bra_composite_aac_pt_br_index.m3u8?Key-Pair-Id=APKAJKRAL73VQHXFMW6A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MDI3Mi8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2OTIyODU0fSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzY5MTU2NTR9fX1dfQ__&Signature=MYDHfSzZ9plj-TOlCf1d2dHuYXfqDZxcqFrkbqZMJnWbF6w49ZiRzG-dwvoZWVfWNmiwpYyVr8LJb41WaoHnmN-i5VVHfg3onr2B0xsV9fboX~nAUAt2huqGEAArQijfSlFn6e0QVB2l0sWbexqulKDHyxIAZ3oA4HuslLFT6kyLv51LrVqwYRssmke9CkTNcmxIKxKjJNR1ZGvV1GyzFK8eQagzvspMZNU~2H7Rw7gDf5AfYTTxVragbRWDBJqjm7Y-ElKMd4FdVvOaGKcPofPox7X-rF-VorZCsE2sp5RFi4-6MwKw9Wb8nkLTWaXI9vOg88yOQ~t7~haSyYyp7A__" -metadata:s:a:0 language=por  -c copy -c:a copy -bsf:a aac_adtstoasc -metadata:g encoding_tool=CrD_Funimation_JS "D:\Animes\Mushoku Tensei Jobless Reincarnation\Season 1\Mushoku Tensei Jobless Reincarnation Season 1 Episode 12.mp4"

14/11/2021 16:47:39 ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
14/11/2021 16:47:39   built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
14/11/2021 16:47:39   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
14/11/2021 16:47:39   libavutil      56. 70.100 / 56. 70.100
14/11/2021 16:47:39   libavcodec     58.134.100 / 58.134.100
14/11/2021 16:47:39   libavformat    58. 76.100 / 58. 76.100
14/11/2021 16:47:39   libavdevice    58. 13.100 / 58. 13.100
14/11/2021 16:47:39   libavfilter     7.110.100 /  7.110.100
14/11/2021 16:47:39   libswscale      5.  9.100 /  5.  9.100
14/11/2021 16:47:39   libswresample   3.  9.100 /  3.  9.100
14/11/2021 16:47:39   libpostproc    55.  9.100 / 55.  9.100
14/11/2021 16:47:39 [https @ 0000021d99c61d00] The "user-agent" option is deprecated: use the "user_agent" option instead
14/11/2021 16:47:39 [https @ 0000021d99c61900] No trailing CRLF found in HTTP header. Adding it.
14/11/2021 16:47:42 [hls @ 0000021d99c60a40] Skip ('#EXT-X-VERSION:4')
14/11/2021 16:47:42 [hls @ 0000021d99c60a40] Skip ('## Created with Unified Streaming Platform (version=1.10.28-22802)')
14/11/2021 16:47:42 [hls @ 0000021d99c60a40] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
14/11/2021 16:47:42 [hls @ 0000021d99c60a40] Skip ('#USP-X-MEDIA:BANDWIDTH=3492000,AVERAGE-BANDWIDTH=2370000,TYPE=VIDEO,GROUP-ID="video-avc1-2289",NAME="video",AUTOSELECT=YES,CODECS="avc1.640028",RESOLUTION=1280x720,FRAME-RATE=23.976')
14/11/2021 16:47:43 [hls @ 0000021d99c60a40] Opening 'https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634out.key' for reading
14/11/2021 16:47:43 [hls @ 0000021d99c60a40] Opening 'crypto+https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634strnv-hl151_streaming_video_1280_720_3000000.ts?Key-Pair-Id=APKAJKRAL73VQHXFMW6A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MDI3Mi8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2OTIyODU0fSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzY5MTU2NTR9fX1dfQ__&Signature=MYDHfSzZ9plj-TOlCf1d2dHuYXfqDZxcqFrkbqZMJnWbF6w49ZiRzG-dwvoZWVfWNmiwpYyVr8LJb41WaoHnmN-i5VVHfg3onr2B0xsV9fboX~nAUAt2huqGEAArQijfSlFn6e0QVB2l0sWbexqulKDHyxIAZ3oA4HuslLFT6kyLv51LrVqwYRssmke9CkTNcmxIKxKjJNR1ZGvV1GyzFK8eQagzvspMZNU~2H7Rw7gDf5AfYTTxVragbRWDBJqjm7Y-ElKMd4FdVvOaGKcPofPox7X-rF-VorZCsE2sp5RFi4-6MwKw9Wb8nkLTWaXI9vOg88yOQ~t7~haSyYyp7A__' for reading
14/11/2021 16:47:43     Last message repeated 1 times
14/11/2021 16:47:43 Input #0, hls, from 'https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634strnv-hl151_streaming_video_1280_720_3000000_index.m3u8?Key-Pair-Id=APKAJKRAL73VQHXFMW6A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MDI3Mi8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2OTIyODU0fSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzY5MTU2NTR9fX1dfQ__&Signature=MYDHfSzZ9plj-TOlCf1d2dHuYXfqDZxcqFrkbqZMJnWbF6w49ZiRzG-dwvoZWVfWNmiwpYyVr8LJb41WaoHnmN-i5VVHfg3onr2B0xsV9fboX~nAUAt2huqGEAArQijfSlFn6e0QVB2l0sWbexqulKDHyxIAZ3oA4HuslLFT6kyLv51LrVqwYRssmke9CkTNcmxIKxKjJNR1ZGvV1GyzFK8eQagzvspMZNU~2H7Rw7gDf5AfYTTxVragbRWDBJqjm7Y-ElKMd4FdVvOaGKcPofPox7X-rF-VorZCsE2sp5RFi4-6MwKw9Wb8nkLTWaXI9vOg88yOQ~t7~haSyYyp7A__':
14/11/2021 16:47:43   Duration: 00:23:47.03, start: 10.041711, bitrate: 3 kb/s
14/11/2021 16:47:43   Program 0 
14/11/2021 16:47:43     Metadata:
14/11/2021 16:47:43       variant_bitrate : 0
14/11/2021 16:47:43   Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
14/11/2021 16:47:43     Metadata:
14/11/2021 16:47:43       variant_bitrate : 0
14/11/2021 16:47:43 [https @ 0000021d9aaebb80] No trailing CRLF found in HTTP header. Adding it.
14/11/2021 16:47:45 [hls @ 0000021d9a17a6c0] Skip ('#EXT-X-VERSION:4')
14/11/2021 16:47:45 [hls @ 0000021d9a17a6c0] Skip ('## Created with Unified Streaming Platform (version=1.10.28-22802)')
14/11/2021 16:47:45 [hls @ 0000021d9a17a6c0] Skip ('#USP-X-MEDIA:BANDWIDTH=262000,AVERAGE-BANDWIDTH=259000,TYPE=AUDIO,GROUP-ID="audio-aacl-256",LANGUAGE="pt",NAME="Portuguese (Brazil)",AUTOSELECT=YES,CHANNELS="2",CODECS="mp4a.40.2"')
14/11/2021 16:47:45 [hls @ 0000021d9a17a6c0] Opening 'https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634out.key' for reading
14/11/2021 16:47:45 [hls @ 0000021d9a17a6c0] Opening 'crypto+https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634strna-hl102_streaming_audio_2_por_bra_composite_aac_pt_br.aac?Key-Pair-Id=APKAJKRAL73VQHXFMW6A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MDI3Mi8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2OTIyODU0fSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzY5MTU2NTR9fX1dfQ__&Signature=MYDHfSzZ9plj-TOlCf1d2dHuYXfqDZxcqFrkbqZMJnWbF6w49ZiRzG-dwvoZWVfWNmiwpYyVr8LJb41WaoHnmN-i5VVHfg3onr2B0xsV9fboX~nAUAt2huqGEAArQijfSlFn6e0QVB2l0sWbexqulKDHyxIAZ3oA4HuslLFT6kyLv51LrVqwYRssmke9CkTNcmxIKxKjJNR1ZGvV1GyzFK8eQagzvspMZNU~2H7Rw7gDf5AfYTTxVragbRWDBJqjm7Y-ElKMd4FdVvOaGKcPofPox7X-rF-VorZCsE2sp5RFi4-6MwKw9Wb8nkLTWaXI9vOg88yOQ~t7~haSyYyp7A__' for reading
14/11/2021 16:47:46 Input #1, hls, from 'https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V2140272/69ed7eff-df86-4793-b921-0d73c1b27634strna-hl102_streaming_audio_2_por_bra_composite_aac_pt_br_index.m3u8?Key-Pair-Id=APKAJKRAL73VQHXFMW6A&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMjE0MDI3Mi8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM2OTIyODU0fSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MzY5MTU2NTR9fX1dfQ__&Signature=MYDHfSzZ9plj-TOlCf1d2dHuYXfqDZxcqFrkbqZMJnWbF6w49ZiRzG-dwvoZWVfWNmiwpYyVr8LJb41WaoHnmN-i5VVHfg3onr2B0xsV9fboX~nAUAt2huqGEAArQijfSlFn6e0QVB2l0sWbexqulKDHyxIAZ3oA4HuslLFT6kyLv51LrVqwYRssmke9CkTNcmxIKxKjJNR1ZGvV1GyzFK8eQagzvspMZNU~2H7Rw7gDf5AfYTTxVragbRWDBJqjm7Y-ElKMd4FdVvOaGKcPofPox7X-rF-VorZCsE2sp5RFi4-6MwKw9Wb8nkLTWaXI9vOg88yOQ~t7~haSyYyp7A__':
14/11/2021 16:47:46   Duration: 00:23:47.08, start: 9.957333, bitrate: 3 kb/s
14/11/2021 16:47:46   Program 0 
14/11/2021 16:47:46     Metadata:
14/11/2021 16:47:46       variant_bitrate : 0
14/11/2021 16:47:46   Stream #1:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 259 kb/s
14/11/2021 16:47:46     Metadata:
14/11/2021 16:47:46       variant_bitrate : 0
14/11/2021 16:47:46       id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x0d\xac\xa0
14/11/2021 16:47:46 Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 1, only the last option '-c:a copy' will be used.
14/11/2021 16:47:46 D:\Animes\Mushoku Tensei Jobless Reincarnation\Season 1\Mushoku Tensei Jobless Reincarnation Season 1 Episode 12.mp4: No such file or directory
14/11/2021 16:47:46 
14/11/2021 16:47:46

**Comment by devanshkasotia** [comment]
Admin my problem is
After starting downloading 4 episodes one by one then after I copied another episode link in add url it and then click download it states loading and then check -traffic-10(it doesn't decrease from there)

After I click download button again it says loading and then check traffic-10 (loop cycle continues endless unless any previous episodes is completely download)

--- also after any previous downloading episode complete and then I unhappily  proceed to download another episode with link it take some times 2 minutes it count down slowly and slowly and somewhat it does again the upper point error

--- so I have to wait to download first 3 episode and then force close application to clear log and then bothersomely copy and click another 3 episode url one by one
[This is as layman I could explain to you]

It bothers a lot and I have wait/minimise untill any

Text doesn't freeze it just application doesn't able to proceed episode downloading after 3/4 episode on funimation.

**Comment by hama3254** [comment]
@janilssonn Thanks for the log, this is something you can not find otherwise.
I cleaned up the download path after the folder was already created so it did not find it.

[Crunchyroll-Downloader-Chromium-U9](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) is available and fixes this.

**Comment by hama3254** [comment]
@devanshkasotia You can use the overview url like `https://www.funimation.com/shows/mushoku-tensei-jobless-reincarnation` and then select a start and end episode.
Additional you can set a limit for downloads than run at the same time so the downloader will not do more that for me two download at once but after the first two are done it would continue with the 3rd and 4th download.
![grafik](https://user-images.githubusercontent.com/52826614/141698884-e4e48152-ddd8-4f34-b51f-d33a556ca3a2.png)

Please try it that way and just out of curiosity please add your hardware specs, if you don't know them just add a screenshot of the task manager please from this page :
![grafik](https://user-images.githubusercontent.com/52826614/141699037-e7f7d44b-c05d-4286-9464-d335ef644a70.png)

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/141953658-951b3f97-7a53-4def-9ff9-882b53c818dc.png)
sorry for the delay, i will test the new version

**Comment by hama3254** [comment]
@janilssonn there is no problem with any delay from you, your issue is something I found inside the code so it is simple to understand unlike the behavior @devanshkasotia describes.
But it is interesting to know what hardware you use.

**Comment by devanshkasotia** [comment]
![Uploading IMG_20211121_121457867.jpg…]()

**Comment by devanshkasotia** [comment]
![IMG_20211121_121457867](https://user-images.githubusercontent.com/25553664/142752627-6f988339-9dda-4a3c-b5bd-5dabfabe3d07.jpg)


Sorry for delay reply

**Comment by hama3254** [comment]
@devanshkasotia Thanks for the Screenshot, did you try [the method to download multiple episodes i mentioned](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/392#issuecomment-968365747)?

I need to add that i would not recommend to try more than the 3 videos which are running for you if i see that you use a 10+ Year old mobile Processor and it is on it's limit with just 3 and i am on my limit with how optimised the Downloader can be.
