### ISSUE TITLE
New bug on U9

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#396]
Hello,

The U9 fixed my subtitle issue that ins't downloading..
But now when we finish a download task, the seasons get duplicated if we try to select it again from the download widow..

It back to normal if we restart the program

https://postimg.cc/vxmpMCNr

**Comment by hama3254** [comment]
just a small cleasring issue, if now fixed with [Crunchyroll-Downloader-Chromium-U9.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by kanohn** [comment]
thanks!

**Comment by kanohn** [comment]
Today checking traffic went to 0 and don't downloaded the video i setup, forgot to check the log, i will in next time:
https://postimg.cc/DJdMLVzG

**Comment by kanohn** [comment]
Other bug i found: https://postimg.cc/rdvBSXLy
This anime don't have resolution 720p, so opened new widow to change the resolution, i changed and crashed the first episode..

**Comment by hama3254** [comment]
You can try [Crunchyroll-Downloader-Chromium-U9.2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by kanohn** [comment]
The bug changed: https://postimg.cc/CRv94QWD

**Comment by hama3254** [comment]
The downloader saves the resolution you selected the first time and save a backup url while looking for the wanted one.
This backup url was invalid so the downloaded failed.
You can try [Crunchyroll-Downloader-Chromium-U9.3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) and hopefully i did not miss anything this time.
Sorry for the trouble.

**Comment by kanohn** [comment]
tried to download the last episode of "Selection Project".
https://postimg.cc/hQLFz7cc

Thank you for your effort to solve this!!

**Comment by hama3254** [comment]
this is an expected error message if you are not logged in.
![grafik](https://user-images.githubusercontent.com/52826614/142763863-e65d25cf-cdc8-430e-9945-64e19d6d852b.png)

**Comment by Salehx47** [comment]
For example, the program automatically downloads all episodes of the season

Not manually, I copy the url of the episode

**Comment by hama3254** [comment]
@Salehx47 You can use the overview url like `https://www.funimation.com/shows/mushoku-tensei-jobless-reincarnation` and then select a start and end episode.
Additional you can set a limit for downloads than run at the same time so the downloader will not do more that for me two download at once but after the first two are done it would continue with the 3rd and 4th download.
![grafik](https://user-images.githubusercontent.com/52826614/141698884-e4e48152-ddd8-4f34-b51f-d33a556ca3a2.png)

**Comment by Salehx47** [comment]
@hama3254 
I have a problem with the program when I try to run it on a vps server windows 



![Capture](https://user-images.githubusercontent.com/95151237/144009451-12f5048f-6db3-4861-8599-cc5845526ec8.PNG)

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/144275759-f9e4304d-96c7-47ba-bd67-9e7db9fd319a.png)
error downloading from Funimation
