### ISSUE TITLE
Deine Umstellung auf Javascript funktioniert garnicht.

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#4]
Ich nutze immernoch den 3.0.1, deine Umstellung auf javascript hats komplett kaputt gemacht.
Der Downloader startet das fenster von firefox läd crunchy und dann ist da nurnch text im fenster, es lädt so 10-15 sekunden und failt dann mit den laden des us cookies zu 100% der zeit.

**Comment by KoroFX** [comment]
Würde es zurückrollen auf ohne javascript, das was es vorher war.
Das hat besser funktioniert, würde aber nochmal reingucken was das ist.

**Comment by KoroFX** [comment]
Und frohe Weinachten.

**Comment by KoroFX** [comment]
@hama3254

**Comment by hama3254** [comment]
> Ich nutze immernoch den 3.0.1, deine Umstellung auf javascript hats komplett kaputt gemacht.
> Der Downloader startet das fenster von firefox läd crunchy und dann ist da nurnch text im fenster, es lädt so 10-15 sekunden und failt dann mit den laden des us cookies zu 100% der zeit.

Wenn ich es probiere und es bei mir funktioniert, bei dir aber nicht mehr kann ich dir leider nicht helfen.
Vorallem nicht wenn ich über Weihnachten besseres zu tun habe als nur am PC zu sitzen.
Hol dir einen VPN und die Sache ist erledigt.

**Comment by KoroFX** [comment]
Nö mit der 3.0.1 funktioniert es ja noch.
