### ISSUE TITLE
"Path and/or specified name too long" error

### ISSUE THREAD

**Issue by Figgyee** [hama3254/Crunchyroll-Downloader-v3.0#400]
I'm always getting this error, "Path and/or specified name too long". I'm super noob and I don't know what is happenning. I have this error only with a single episode, others are fine.
![Senza titolo](https://user-images.githubusercontent.com/82511384/142766690-19385d34-8560-434c-93a5-f6a0b1dc53b1.png)

**Comment by hama3254** [comment]
Windows just does not like Files with a long name and/or path.
Please check that your Path is not to long and check inside the settings which naming type you use since some Anime just have long titles and adding the episode name can make them to long.

**Comment by Figgyee** [comment]
Thank you very much, solved!
