### ISSUE TITLE
Hybrid mode and 1st season

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#406]
Strangely enough, if I leave hybrid mode enabled, I can't get the episode listing for the first season of:

h***s://www.crunchyroll.com/it/world-trigger

If disable, I can select the episode range, if enabled it is blank.

**Comment by hama3254** [comment]
The hybrid mode setting has no effect on any selection before the episode gets download.
The anime seems to have some hard restrictions, it is available for Germany/Austria if i set crunchyroll to German but not if i set it to Italian except if i use a Italian VPN.
So the selected Crunchyroll language need to match with your region for the first season.
This is an unique case which i have not seen before.
