### ISSUE TITLE
Unable to download an episode from Crunchyroll when trying beta

### ISSUE THREAD

**Issue by MinionAttack** [hama3254/Crunchyroll-Downloader-v3.0#408]
Hi, I've selected to try the beta in _Crunchyroll_ and now when I want to download a video the procress stucks in "loading".

The url of the beta is: `https://beta.crunchyroll.com/es-es/series/GZJH3DPK0/blade-runner-black-lotus`

And the normal url is: `https://www.crunchyroll.com/es-es/blade-runner-black-lotus/episode-6-the-persistence-of-memory-821203`

It is possible to add a fix for this or until the beta finish it's only possible to download in classic mode?

Regards.

**Comment by hama3254** [comment]
Please check if you are logged in inside the downloader, the beta website is not accessible otherwise and since Crunchyroll redirects you from the old episode site to the beta site but not the other way around it will most likely get stuck on the main page of Crunchyroll.

**Comment by MinionAttack** [comment]
You were right, thank you!
