### ISSUE TITLE
Customize Filename

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#409]
Hello!

I saw there's a option to change somethings on the filename, like add ep number + ep name, etc..

For my purpose, the perfect filename should be:
Anime title + ep number with 3 digits, without "episódio string"

For now the filename that i get:
-> **The Idaten Deities Know Only Peace Episódio 11**

I need to rename all my episodes to:
-> **The Idaten Deities Know Only Peace 011**

if have seasons, example season 2:
-> **The Idaten Deities Know Only Peace 2 011**

Could you please add this feature? Maybe will save a lot of time for some peoples that need some exactly string for filename..
I work with lots of episodes everyday and rename files cost a lot of time for me.. even i created a script to rename bunk of files, its boring :/

Thank you for the great program.

**Comment by hama3254** [comment]
You can clear  the prefix with just setting a ` `  (blank space) in there since double blank spaces get shorten by the downloader anyway to remove the `Episódio`.
![grafik](https://user-images.githubusercontent.com/52826614/146742340-9789632b-54af-445d-a472-6c126ca8af29.png)

your leading zeros need to be added by hand.

**Comment by kanohn** [comment]
Thank you for the info, i did not know about this..

About the leading zeros, its not possible to add a option for it? I will take a look on the source..

If you have time and its possible to do, i can pay some value for this feature, since it will benefit me a lot. If i remember correct github has a option to paid commits or something.

**Comment by hama3254** [comment]
i have added the leading zero option with the `Crunchyroll-Downloader-Chromium-U10.1`

![grafik](https://user-images.githubusercontent.com/52826614/146805389-67e2441b-1cb5-4d03-b218-40728c3cc217.png)

**Comment by FilipLac** [comment]
Hi, I would like to extend on this issue...
After setting this option to "1" first 1-9 episodes downloaded without any issues but with episode 10 and higher it added "00" before that number
![Numbering](https://user-images.githubusercontent.com/93822443/146821896-250b68f7-8964-4bd8-b4bd-897e3deaca22.png)
.

**Comment by NatsuFT36** [comment]
Hi, including zeros is not a good idea to include since some do not download or close the program and it is better to leave it as it was before and have one modify it in your own way.
