### ISSUE TITLE
Debug-Funimation

### ISSUE THREAD

**Issue by HinataXNoa** [hama3254/Crunchyroll-Downloader-v3.0#41]
Got one episode to download but now I am stuck with this
![IMG_20200815_075337540](https://user-images.githubusercontent.com/69725537/90315756-c7837100-ded2-11ea-8b41-bd8cb9fbc710.jpg)

**Comment by hama3254** [comment]
i see there something strange in the code and i don't know what i have done there, but if you open the settings and check the "Merge softsubs with video file" box it should work (this setting adds the subtitles to the video file and you can active then in the video player later)
![grafik](https://user-images.githubusercontent.com/52826614/90317888-b5362100-df2c-11ea-9e08-d9fe46371d7f.png)

**Comment by HinataXNoa** [comment]
Thanks for the fast reply. This work around is working, thank you

**Comment by HinataXNoa** [comment]
After a while ive encountered this as well. Only happens to a few episodes
![IMG_20200815_141706673](https://user-images.githubusercontent.com/69725537/90321824-46dc6900-df02-11ea-81e4-415320c0ae0b.jpg)

**Comment by hama3254** [comment]
if you use this debug option the log might conation useful information why this happens :
![grafik](https://user-images.githubusercontent.com/52826614/90322442-600e0580-df54-11ea-9e3b-db99a522c30d.png)

**Comment by HinataXNoa** [comment]
i got a log, is there a place i should send you it? not a coder myself, so im not sure what to look for exactly. The seconds to last line does say "invalid data found when processing input"

**Comment by hama3254** [comment]
> i got a log, is there a place i should send you it? not a coder myself, so im not sure what to look for exactly. The seconds to last line does say "invalid data found when processing input"

for the future you can just drag and drop the files in the the textbox of this site, github uploads it automaticly. 

for this time i looked at the episode you have in the image and it seems to work fine so this might be just a random error. 
if you have other question or issues please let me know.

**Comment by hama3254** [comment]
This seem to work fine so I will close this issue
