### ISSUE TITLE
Dark mode issues

### ISSUE THREAD

**Issue by OshidaBCF** [hama3254/Crunchyroll-Downloader-v3.0#410]
The darkmode doesn't change the text color of "Default Subtitles", which make it really hard to read.
Also changing the theme of the app will not change everything, i would suggest "forcing" a reboot of the app to apply the change.
Also the colors seems a bit weird, i can't tell how it would be better.

Other than that, this app really saved me a few hours of digging though the internet to find a single torrent that doesn't get seed anymore.

Thank you

and Merry XMAS

![image](https://user-images.githubusercontent.com/61458287/147109028-636a6682-b74b-46e1-b1e3-77dd8f21f850.png)

**Comment by hama3254** [comment]
Seems like i missed an element which will be fixed after the holidays.

The change in color should update if the window changes in any way and even if not then not that bad compared what a forced restart can do if a download is running.
And you don't change that often so either a manual restart or some minor visual issues are not that bad.

For the color i don't see what's wrong with it but as light mode user i don't really understand why this important in the first place.
