### ISSUE TITLE
Better queue system

### ISSUE THREAD

**Issue by OshidaBCF** [hama3254/Crunchyroll-Downloader-v3.0#411]
**Is your feature request related to a problem? Please describe.**
The queue system is really hard to use correctly, we can't "clear" the queue other than by restarting the app, the queue seem to not work if you close the window that appears when you select the anime.

**Describe the solution you'd like**
Improve the queue system with various QoL changes, clearing and modification of the queue.

**Comment by hama3254** [comment]
I'm not sure if you mean the same with `queue` as me.
I have a season download where you start with `Episode X` until `Episode Z` and a queue where either the add-on saves it's urls or if the maximum downloads has been reached then the Url gets saved there for later.

Both only work if the window for them is open to make sure that the user wants to use them.
