### ISSUE TITLE
it is not possible to activate the option for hardsub in funimation 

### ISSUE THREAD

**Issue by Ferfu** [hama3254/Crunchyroll-Downloader-v3.0#413]
I'm using version 10.2 and noticed that the hardsub option of funimation cannot be activated
Is it disabled due to problems found in the program code or is it something that just happened to me?

![funimation](https://user-images.githubusercontent.com/32347896/147324847-3a991bbf-6cac-426c-8ac0-364981770d08.PNG)

**Comment by hama3254** [comment]
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/399

**Comment by Ferfu** [comment]
I hadn't noticed that there was an argument about it, thanks
