### ISSUE TITLE
US Cookie funktioniert nicht mehr

### ISSUE THREAD

**Issue by MariusAndersson** [hama3254/Crunchyroll-Downloader-v3.0#416]
Moin,

mein US Cookie will nicht mehr funktionieren. Normalerweise war es immer so, dass es irgendwann ging - und wenn es erst nach 3-5x Button klicken und captcha bei GeckoFX eingeben usw war. Aber jetzt geht es irgendwie gar nicht mehr. Hab seit 3 Tagen probiert in die US Oberfläche zu kommen. Keine Chance mehr. Hat sich etwas am Cookie geändert ? Kannst du das mal gegenprüfen ? Ich nutze aktuell noch Version 3.7.8.6

Danke :)

**Comment by hama3254** [comment]
Der US Cookie hat schon immer auf einen Bug von CR aufgebaut und war nie zuverlässig.
Mit dem wechsel auf Chromium als integrierten Webbrowser ist hab ich die Funktion gestrichen wegen weiteren Problemen mit der beta Webseite.
Im Grunde leitet CR einen immer auf die beta Webseite wenn man einen US Cookie hatte und eingeloggt ist, der Fehler von der alten webseite gibt es auf der aber nicht mehr und damit hat man den selben Katalog wie ohne Cookie.

**Comment by MariusAndersson** [comment]
Das heißt, ich brauche ab sofort einen VPN, um amerikanische Sachen zu bekommen ? Oder funktioniert noch in irgendeiner Version ? Hast du das gerade erst gestrichen ? Weil um den Jahreswechsel herum ging der Cookie noch.

**Comment by hama3254** [comment]
>Das heißt, ich brauche ab sofort einen VPN, um amerikanische Sachen zu bekommen ? 

Ja das heißt es, vorallem weil ich gerade ausversehn den server gekillt habe...

>Hast du das gerade erst gestrichen ? 

Ich hab den eingebauten webbrowser schon im August 21 umgestellt und dafür musste ich schon vieles neu schreiben und da der US cookie mit der beta webeite eh wegfällt hab ich das nie gemacht und werde ich auch nicht mehr machen.

**Comment by MariusAndersson** [comment]
ok, danke dir für die Antwort. Trotzdem komisch, dass es bis vor kurzem noch funktioniert hat xD
