### ISSUE TITLE
Repository is unlicensed

### ISSUE THREAD

**Issue by dsdude123** [hama3254/Crunchyroll-Downloader-v3.0#42]
Is there any plan to apply an open-source license to this repository? Would allow for better contributions from the community. I would recommend GPL or MPL since you use Firefox and ffmpeg components. 

https://choosealicense.com/

**Comment by hama3254** [comment]
i never looked into that license theme.
i released the source shortly after Crunchyroll added DRM protected streams so i thought the app will stop anyway in a few weeks but this was in october 2019.
