### ISSUE TITLE
Crash with very long episode title

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#420]
Enter your version below, it can be found in the "About" section of the settings.
Version : v3.8.2.0 Chromium-U11

Unable to properly save log file. I get the following error:

![image](https://user-images.githubusercontent.com/2351785/148815065-2f4cfcc4-7668-413b-8788-be59033017c7.png)

<details>
  <summary>Log:</summary>
  
 
  ```

10/01/2022 18:55:01 -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs1/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_3590449.mp4/index-v1-a1.m3u8?Expires=1642010102&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS81NGI4NjQ4YmJiZmI0YjM0OTUzOGI3YmMxMjllOGM5NS9hc3NldHMvZjk5OGIxMjExNzc3MzRmMDEwYTUwYTJjMjVkMmMyZDNfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDIwMTAxMDJ9fX1dfQ__&Signature=UvgyDDEGhHWU6cBfUl2V0O40ke4DNpOUyoDb9TotTq2lGYkqKbFZcgaZW0I8Mt1Y55CXjae0mLShBfzbOom~ZAyHQv0gAcjwnOfZPYdDUrJuAMogcd~hQMgNvzd2gX8NZMZjrZeGxwCDzLGxdGD8q7X8IE0zhB7~-dJrXDnUz0gw37RllOV9yttPrNsw~9~EyRzPqS9NHpsOepcGBd29grJpY6do2YkwJzXP0hMpKFOIOvXV8fMXLV9qDXwKED3eFaOfdjbIsqOMuc0rDcNcpFV~91vpEaFMbI8NJf2T~hquS3jCl-M-kR9CWih4YJ-QT-4oT~YsabInDBu32GrS6A__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod" -i "https://v.vrv.co/evs/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_202300.txt?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly92LnZydi5jby9ldnMvNTRiODY0OGJiYmZiNGIzNDk1MzhiN2JjMTI5ZThjOTUvYXNzZXRzL2Y5OThiMTIxMTc3NzM0ZjAxMGE1MGEyYzI1ZDJjMmQzXzIwMjMwMC50eHQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDIwMDU2OTN9fX1dfQ__&Signature=hq5eEx~wExQtD2di6se7gagxNGuysHrY-opqWzts3rhodPrGmMTAhCfCNeUVAziJm7utzOM43oipGeWMQRatr6reIYC1W4Fhu9EIpvEF15rZvb04xyCxNuyCIxafPvN97tT62ywAZwkwFHW0JlnVwtq70vB2Gc2p2c2kVOCmnIaeLsxuyCWoqH5MkPYRuskDG-lVa06fVd6QUutaZpMCwnbi56wtqqrcxh3lSUJ5~Sl0NUzZC7GzsRJiW1PvdP54i-1OnrtVdIO1TDHAuqNnwcevCPIu9nXa4Ro0qeRhQj03kfrq7KKUuj3RBatZx6BR3X2-HnsRw48f8RYhr1~hDw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA" -map 0:v -map 0:a -map 1  -c copy -c:a copy -bsf:a aac_adtstoasc -c:s copy -metadata:s:s:0 language=ita -metadata:s:s:0 title="Italiano (Italian)" -metadata:s:s:0 handler_name="Italiano (Italian)" -metadata:s:a:0 language=jpn "A:\Crunchyroll\ZOMBIE LAND SAGA\Season 1\[S01 E09] ZOMBIE LAND SAGA Season 1 Episode 09 Though My Life May Have Ended Once By Some Twist of Fate I Have Risen, and If Song and Dance Are to Be My Fate, Then Carrying the Memories of My Comrades In My Heart As I Sally Forth Shall Be My SAGA.mkv"

10/01/2022 18:55:01 ffmpeg version 4.4.1-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
10/01/2022 18:55:01   built with gcc 11.2.0 (Rev1, Built by MSYS2 project)
10/01/2022 18:55:01   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
10/01/2022 18:55:01   libavutil      56. 70.100 / 56. 70.100
10/01/2022 18:55:01   libavcodec     58.134.100 / 58.134.100
10/01/2022 18:55:01   libavformat    58. 76.100 / 58. 76.100
10/01/2022 18:55:01   libavdevice    58. 13.100 / 58. 13.100
10/01/2022 18:55:01   libavfilter     7.110.100 /  7.110.100
10/01/2022 18:55:01   libswscale      5.  9.100 /  5.  9.100
10/01/2022 18:55:01   libswresample   3.  9.100 /  3.  9.100
10/01/2022 18:55:01   libpostproc    55.  9.100 / 55.  9.100
10/01/2022 18:55:01 [https @ 000001c51d93fe80] The "user-agent" option is deprecated: use the "user_agent" option instead
10/01/2022 18:55:01 [https @ 000001c51d93fa80] No trailing CRLF found in HTTP header. Adding it.
10/01/2022 18:55:01 [hls @ 000001c51d93eac0] Skip ('#EXT-X-ALLOW-CACHE:YES')
10/01/2022 18:55:01 [hls @ 000001c51d93eac0] Skip ('#EXT-X-VERSION:5')
10/01/2022 18:55:01 [hls @ 000001c51d93eac0] Opening 'https://ll.v.vrv.co/evs1/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_3590449.mp4/encryption.key?t=exp=1642010103~acl=/evs1/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_3590449.mp4/*~hmac=dbcf757c485dc92d2c2758e239a308c3f8ea9aba482d615da1112cd25f827234' for reading
10/01/2022 18:55:01 [hls @ 000001c51d93eac0] Opening 'crypto+https://ll.v.vrv.co/evs1/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_3590449.mp4/seg-1-v1-a1.ts?t=exp=1642010103~acl=/evs1/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_3590449.mp4/*~hmac=dbcf757c485dc92d2c2758e239a308c3f8ea9aba482d615da1112cd25f827234' for reading
10/01/2022 18:55:02 Input #0, hls, from 'https://pl.crunchyroll.com/evs1/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_3590449.mp4/index-v1-a1.m3u8?Expires=1642010102&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS81NGI4NjQ4YmJiZmI0YjM0OTUzOGI3YmMxMjllOGM5NS9hc3NldHMvZjk5OGIxMjExNzc3MzRmMDEwYTUwYTJjMjVkMmMyZDNfKi5tM3U4PyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDIwMTAxMDJ9fX1dfQ__&Signature=UvgyDDEGhHWU6cBfUl2V0O40ke4DNpOUyoDb9TotTq2lGYkqKbFZcgaZW0I8Mt1Y55CXjae0mLShBfzbOom~ZAyHQv0gAcjwnOfZPYdDUrJuAMogcd~hQMgNvzd2gX8NZMZjrZeGxwCDzLGxdGD8q7X8IE0zhB7~-dJrXDnUz0gw37RllOV9yttPrNsw~9~EyRzPqS9NHpsOepcGBd29grJpY6do2YkwJzXP0hMpKFOIOvXV8fMXLV9qDXwKED3eFaOfdjbIsqOMuc0rDcNcpFV~91vpEaFMbI8NJf2T~hquS3jCl-M-kR9CWih4YJ-QT-4oT~YsabInDBu32GrS6A__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=ll-prod':
10/01/2022 18:55:02   Duration: 00:23:40.04, start: 0.101000, bitrate: 0 kb/s
10/01/2022 18:55:02   Program 0 
10/01/2022 18:55:02     Metadata:
10/01/2022 18:55:02       variant_bitrate : 0
10/01/2022 18:55:02   Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 47.95 tbc
10/01/2022 18:55:02     Metadata:
10/01/2022 18:55:02       variant_bitrate : 0
10/01/2022 18:55:02   Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
10/01/2022 18:55:02     Metadata:
10/01/2022 18:55:02       variant_bitrate : 0
10/01/2022 18:55:02   Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
10/01/2022 18:55:02     Metadata:
10/01/2022 18:55:02       variant_bitrate : 0
10/01/2022 18:55:02 Input #1, ass, from 'https://v.vrv.co/evs/54b8648bbbfb4b349538b7bc129e8c95/assets/f998b121177734f010a50a2c25d2c2d3_202300.txt?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly92LnZydi5jby9ldnMvNTRiODY0OGJiYmZiNGIzNDk1MzhiN2JjMTI5ZThjOTUvYXNzZXRzL2Y5OThiMTIxMTc3NzM0ZjAxMGE1MGEyYzI1ZDJjMmQzXzIwMjMwMC50eHQiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NDIwMDU2OTN9fX1dfQ__&Signature=hq5eEx~wExQtD2di6se7gagxNGuysHrY-opqWzts3rhodPrGmMTAhCfCNeUVAziJm7utzOM43oipGeWMQRatr6reIYC1W4Fhu9EIpvEF15rZvb04xyCxNuyCIxafPvN97tT62ywAZwkwFHW0JlnVwtq70vB2Gc2p2c2kVOCmnIaeLsxuyCWoqH5MkPYRuskDG-lVa06fVd6QUutaZpMCwnbi56wtqqrcxh3lSUJ5~Sl0NUzZC7GzsRJiW1PvdP54i-1OnrtVdIO1TDHAuqNnwcevCPIu9nXa4Ro0qeRhQj03kfrq7KKUuj3RBatZx6BR3X2-HnsRw48f8RYhr1~hDw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA':
10/01/2022 18:55:02   Duration: N/A, bitrate: N/A
10/01/2022 18:55:02   Stream #1:0: Subtitle: ass
10/01/2022 18:55:02 Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 1, only the last option '-c:a copy' will be used.
10/01/2022 18:55:02 Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 2, only the last option '-c:s copy' will be used.
10/01/2022 18:55:02 A:\Crunchyroll\ZOMBIE LAND SAGA\Season 1\[S01 E09] ZOMBIE LAND SAGA Season 1 Episode 09 Though My Life May Have Ended Once By Some Twist of Fate I Have Risen, and If Song and Dance Are to Be My Fate, Then Carrying the Memories of My Comrades In My Heart As I Sally Forth Shall Be My SAGA.mkv: No such file or directory
10/01/2022 18:55:02 
10/01/2022 18:55:02 
  ```
  
</details>

**Comment by hama3254** [comment]
It is a known issue that files with a very long names cause trouble, in this case disabling the episode name would solve the problem.

**Comment by tormento** [comment]
Thanks for the hint. I saw other similar downloaders work fine with that kind of issue, I thought it was solvable.

**Comment by Charles-the-hacker** [comment]
im also having this issue, is it possibly in ffmpeg, or is it an error in the code?

**Comment by hama3254** [comment]
i take a closer look on this soon but i think i now understand what Windows wants from me to use a path longer than the old 260 character limit.
it seems like i need to add `\\?\` before a  long path to let windows know that it will be a long one...

**Comment by Charles-the-hacker** [comment]
I did some experiments, it seams that downloading it in a MKV video format solves it.

**Comment by tormento** [comment]
@Charles-the-hacker I always download as MKV to preserve softsubs but the crash happens the same.

**Comment by Charles-the-hacker** [comment]
That's strange.

**Comment by tormento** [comment]
@Charles-the-hacker just try to download Zombie Land Saga season 01 and tell me about episode 09.

**Comment by hama3254** [comment]
mkv or mp4 does not change anything about the path execpt the type of file you get.

i made a test version that allows the use of the long path [notice that you need to change the windows setting on your own first!](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later)

[Crunchyroll-Downloader-Chromium-LongPathTest](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

**Comment by tormento** [comment]
@hama3254 tested and working. Before starting to download, I get a popup window:

![image](https://user-images.githubusercontent.com/2351785/150413963-d2eafb0e-524b-45eb-941f-8665010ace10.png)

Was it intended? Educated guess: number of characters in path+filename? :)

**Comment by Charles-the-hacker** [comment]
Will this be natively patched in a future update?

**Comment by hama3254** [comment]
> @hama3254 tested and working. Before starting to download, I get a popup window:
> 
> ![image](https://user-images.githubusercontent.com/2351785/150413963-d2eafb0e-524b-45eb-941f-8665010ace10.png)
> 
> Was it intended? Educated guess: number of characters in path+filename? :)

Oops i forget to remove that.
And yes that is the number of characters but it only shows if there are more than 255 inside the path.

**Comment by hama3254** [comment]
> Will this be natively patched in a future update?

What does `natively patched` mean? 
I just finished the test version and if there are no major issues found than this will be included with the next update

**Comment by tormento** [comment]
@hama3254 you could add an option to truncate the name. Perhaps somebody has old systems or simply doesn't care about having the complete title.

**Comment by Charles-the-hacker** [comment]
> > Will this be natively patched in a future update?
> 
> 
> 
> What does `natively patched` mean? 
> 
> I just finished the test version and if there are no major issues found than this will be included with the next update

Yes, this is what i ment. It sounds like it will be solved in an update in the near future.

**Comment by hama3254** [comment]
> @hama3254 you could add an option to truncate the name. Perhaps somebody has old systems or simply doesn't care about having the complete title.

i could just do a stuipid cut after X characters for both the Series name and the episode name that would reduce the chance of getting above the 260 character limit for older systems but it will not fully fix it since you can already have a long path to begin with.

I would have the redesing the settings and make an extra tab for naming and move everything for the naming to it.
if i do this than it would need to redo some of the existing code so it would be the best to do it at the time CR switches compleetly to the beta website so i could redo both at the same time and i don't have to care about the old page then.

i made a dissussion for that if you have any ideas or preferences you can add them there #425

**Comment by hama3254** [comment]
> Yes, this is what i ment. It sounds like it will be solved in an update in the near future.

the version that is currently available does support it, i just marked it as `LongPathTest` because i jus tried that one episode from above.

> @Charles-the-hacker just try to download Zombie Land Saga season 01 and tell me about episode 09.

_Originally posted by @tormento in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/420#issuecomment-1017443541_

[notice that it need be activated on windows by hand ](https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html)

**Comment by Charles-the-hacker** [comment]
> > Yes, this is what i ment. It sounds like it will be solved in an update in the near future.
> 
> 
> 
> the version that is currently available does support it, i just marked it as `LongPathTest` because i jus tried that one episode from above.
> 
> 
> 
> > @Charles-the-hacker just try to download Zombie Land Saga season 01 and tell me about episode 09.
> 
> 
> 
> _Originally posted by @tormento in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/420#issuecomment-1017443541_
> 
> 
> 
> [notice that it need be activated on windows by hand ](https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html)
> 
> 

Cool, I will deploy it as soon as possible

**Comment by JopoJP** [comment]
I have my Download location at the root of my second drive. So I don't really had this problem.

Workaround would be to go into windows settings and remove the 255 limit.

But my case is special anyway since I have a Mac and use a VM of windows.

The VM simply stores my content in my second drive which is APFS and Raid 1.
