### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Sakura1338** [hama3254/Crunchyroll-Downloader-v3.0#428]
Enter your version below, it can be found in the "About" section of the settings.
Version : v3.8.2.0 Chromium-U11-LongPathTest

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>
  <summary>Insert the logtext before the second details</summary>
    
[JoJo's Bizarre Adventure Season 4 Episode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/7955475/JoJo.s.Bizarre.Adventure.Season.4.Episode.1.log)

</details>
The URL of the video in question is https://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-golden-wind-777705

**Comment by hama3254** [comment]
This is a failure of the download library without any real issue.
You can retry the download then it should work or you can try the hybrid mode to cache the data before the library starts to process it.

**Comment by Sakura1338** [comment]
> This is a failure of the download library without any real issue. You can retry the download then it should work or you can try the hybrid mode to cache the data before the library starts to process it.

It works after I try again.Thanks a lot.
