### ISSUE TITLE
bug downloading videos doesn't work 

### ISSUE THREAD

**Issue by rudesniper44444** [hama3254/Crunchyroll-Downloader-v3.0#429]
first of all thank you for your hard work and for your get script that u made , 

i just wanna know why it doesn't work at all with funimation , it says preparing and it never finish , is there any solutions for this and thanks a lot 

![image](https://user-images.githubusercontent.com/97499870/151662196-4b5bb375-0b88-4943-b89f-3bf851a09e83.png)

**Comment by hama3254** [comment]
for a single download the direct url to the episode would be the simpler and faster.

If you want to download more than one episode and still get this issue then check if you using the latest version.
