### ISSUE TITLE
Mozilla firefox extension corrupt

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#43]
Hi, i'm not able to install FF extension.

https://i.imgur.com/KVa8DmL.png

FF version:
79.0 (64-bit)

**Comment by hama3254** [comment]
> 
> 
> Hi, i'm not able to install FF extension.
> 
> https://i.imgur.com/KVa8DmL.png
> 
> FF version:
> 79.0 (64-bit)

the addon was not approved at the time you tryed, but it should work now

**Comment by x3inspire** [comment]
> > Hi, i'm not able to install FF extension.
> > https://i.imgur.com/KVa8DmL.png
> > FF version:
> > 79.0 (64-bit)
> 
> the addon was not approved at the time you tryed, but it should work now

Same, still cannot install it right now.

**Comment by hama3254** [comment]
that's strange, i have no problem : https://www.youtube.com/watch?v=ZUNpsuZM16A

**Comment by x3inspire** [comment]
> that's strange, i have no problem : https://www.youtube.com/watch?v=ZUNpsuZM16A
> url: https://addons.mozilla.org/de/firefox/addon/crunchyroll-downloader-addon/

Ok, works after using ff link addon.
