### ISSUE TITLE
Multiple season/series queue

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#434]
I'd like to put more than one season/series on queue.

Now only a season can be queued, i.e. I can't queue episodes until the current queue is empty.

Am I doing something wrong or it is a missing feature?

**Comment by hama3254** [comment]
There is no dedicated feature to add more seasons/series, one season at the time should be enough for most users.
You can use the multi-download and redirect it into the queue (with the setting) then do another season/series or try the [Add-on](https://github.com/hama3254/CRD-add-on/discussions/1) for [Chrome and Firefox](https://github.com/hama3254/CRD-add-on/releases/tag/v0.6) this allows to add seasons/series from within your normal browser.
Notice that the downloader has not been tested with more than 12 episodes before closing it, higher numbers can cause issues.
