### ISSUE TITLE
can´t download with browser plugin

### ISSUE THREAD

**Issue by anthony2611** [hama3254/Crunchyroll-Downloader-v3.0#435]
hay the downloader works when i add episodes one by one but when i use the plugin it just says downloads in queue and nothing happens
I've tried different versions of the plugin and the software but nothing works
![Unbenannt](https://user-images.githubusercontent.com/25979755/153665461-de1e21d5-5725-4641-aa20-1450d740115e.PNG)

**Comment by hama3254** [comment]
You need to open the `Add Video` window and then click on the status text on that form which swichtches the downloader into the queue mode.
this will display a list with your episodes and it will start to work on the list immediately after you get into the queue mode.

**Comment by anthony2611** [comment]
ah ok thanks
sometimes I'm just stupid

thank you man and nice software
