### ISSUE TITLE
HiDive

### ISSUE THREAD

**Issue by Not-a-North-Korean** [hama3254/Crunchyroll-Downloader-v3.0#44]
Please add HiDive. I don't think they have DRM, so it probably won't be extremely difficult. Downloading video from it is possible with a Firefox extension, but not subtitles.

**Comment by SethAluma** [comment]
Hi @hama3254, I have a HiDive premium account if you wanted to take a look. It looks like it's using a .m3u8 file to download a .TS video, but I'm not savvy enough to try to implement it myself (yet).

**Comment by hama3254** [comment]
@SethAluma you can add me on Discord if you want Hama#4155 but my interest in HiDive is not really there but you can look and if you have questions I'm trying to help.

**Comment by hama3254** [comment]
HiDive support is not planned for the near future, i will close this now.
