### ISSUE TITLE
I can't download with subtitles

### ISSUE THREAD

**Issue by MonoConBigotes** [hama3254/Crunchyroll-Downloader-v3.0#441]
I configured all, and i triying all the posible setting, and i cant download with merge sutitles...

**Comment by hama3254** [comment]
I don't see any issue with that function.
Please check you seleceted the `Merge soft-subs with video file` checkbox in the output tab and your subtitle languages for Crunchyroll or funimation.
Also consider to check if your selected subtitle languages are even avalible at the streaming service.
![grafik](https://user-images.githubusercontent.com/52826614/155810267-a9802378-a267-4cee-9a36-3f055220479f.png)

**Comment by MonoConBigotes** [comment]
The anime is Haikyu, have espanisj subs ("latinos"), my configuration:

![Crunchyroll_Downloader_tJBN8C7NDe](https://user-images.githubusercontent.com/41840075/155820124-d409d006-7cd3-44a0-afc1-c02c55a1e080.png)

![Crunchyroll_Downloader_hxWPVhUSeH](https://user-images.githubusercontent.com/41840075/155820131-0216e052-e144-4700-b30a-26e96eef3be9.png)

**Comment by hama3254** [comment]
The settings should be fine, i just checked the Anime and it seems like Crunchyroll only serves the sub english subs for US users.
It should work fine if you are from Mexico but i did not test that due to the bad speed of the proxy connection.
Please check in your normal webbrowser that you can watch the spanish subs.

**Comment by hama3254** [comment]
Is there any chance that you two @DekuQJ03 and @MonoConBigotes are using the beta website?
i found this in there api answer which makes clear why it does not work, Cruchyroll uses another tag for softsubs and the downloader used `es-LA` or the old `esLA` for both...

[you can find the latest build with a fix here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x)

![grafik](https://user-images.githubusercontent.com/52826614/155879472-40b12234-fd83-4088-93f7-957b176adbb1.png)

**Comment by MonoConBigotes** [comment]
Thanks, now its works fine!!
the only problem now, is the sub spanish(LA), describe like chinese:
![vlc_PQdvFWnf1c](https://user-images.githubusercontent.com/41840075/155887567-601d425b-19f9-4600-a706-9e52e38ff964.png)...
and yes, i use the new beta portal.... :S

**Comment by hama3254** [comment]
that are the fallback strings in case something goes wrong and as you see something has gone wrong since i forgott to add the `es-419` to the subtitle paramter.
this is now fixed and the version has been replaced on github, feel free to redownload it.

**Comment by MonoConBigotes** [comment]
Thanks a lot!!!
