### ISSUE TITLE
Audio stream marked as "Unknown" language

### ISSUE THREAD

**Issue by SethAluma** [hama3254/Crunchyroll-Downloader-v3.0#45]
For media streamers, like Plex, it would be handy to have the language of the audio stream set. Could you please add in the ability to label the audio track with its language?
The ffmpeg command to set the language is apparently `-metadata:s:a:0 language=jpn` ("jpn" = "Japanese"). Other language codes can be found [here](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) (but I think Crunchyroll only does Japanese, yeah?).

Also for streamers, like Plex, you can set the subtitle language by including the language code before the extension (e.g. "Anime Episode 1.eng.ass" would give that subtitle the language of "English" instead of "Unknown").
Adding a checkbox to enable that naming format would be fantastic, too.

**Comment by hama3254** [comment]
Crunchyroll offers at least a view anime with different Dub (I already have seen German, Russian, Spanish, English and more).
[But Crunchyroll is kind enough to label the audio language](https://abload.de/img/screenshot_20200826-03sjjp.png) so it should be possible to translate this value the same way as I already do for merged softsubs. (I already use the metadata  " -metadata:s:s:[int]" for that).
The naming scheme for external files should be also pretty easy.

**Comment by hama3254** [comment]
> Also for streamers, like Plex, you can set the subtitle language by including the language code before the extension (e.g. "Anime Episode 1.eng.ass" would give that subtitle the language of "English" instead of "Unknown").

the subtitles are marked in the merged mp4, the option for unmerged subtitles will be added with the complete overhaul from the settings to separate Crunchyroll and funimation settings. 

the audio tag has been added with v3.4.2 
![grafik](https://user-images.githubusercontent.com/52826614/91439833-f3f1a280-e86d-11ea-94e6-5c7b49d51706.png)

**Comment by SethAluma** [comment]
I think the addition of the audio language has caused downloads to fail in v3.4.2.
I get the attached errors while trying to download "That Time I Got Reincarnated as a Slime": [That Time I Got Reincarnated as a Slime Episode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5154677/That.Time.I.Got.Reincarnated.as.a.Slime.Episode.1.log)

**Comment by hama3254** [comment]
> -I've found the fault. ~Will upload a pull request soon with the fix~ Fix uploaded

Fix is merged

**Comment by hama3254** [comment]
That should work and i finally uploaded v3.4.3 so i think i can close this
