### ISSUE TITLE
Application Download

### ISSUE THREAD

**Issue by brock4444** [hama3254/Crunchyroll-Downloader-v3.0#454]
![k](https://user-images.githubusercontent.com/102415153/160236977-639c6923-b798-4c6e-a56a-db8adaab6a8f.png)
Where do I find the application?

**Comment by hama3254** [comment]
You get to the release page here:

![grafik](https://user-images.githubusercontent.com/52826614/160237339-d135414f-5d7e-4707-a9b8-85d1d48ded1d.png)

Then you can use the top most release which for now would be [Crunchyroll-Downloader-v3.x-Chromium](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) just get he last version of the downloader which would be `Crunchyroll-Downloader-Chromium-U14` for now.

Older versions are available in case i screw something up but i don't recommend using them anymore.

**Comment by brock4444** [comment]
Worked for me, thanks!
