### ISSUE TITLE
Switch to Aria2c or improve download stability

### ISSUE THREAD

**Issue by matant94** [hama3254/Crunchyroll-Downloader-v3.0#455]
**Is your feature request related to a problem? Please describe.**

Downloading too slow, Improve downloading/connection stability, and more feature

**Describe the solution you'd like**

I noticed a really weak performance as compared to yt-dlp with specific settings, these performance (of CRD) are comparable to
yt-dlp w/FFmpeg but really weak if you compare it with yt-dlp w/Aria2c properly configured

**Describe alternatives you've considered**

Switch to Aria2c instead of FFmpeg ad download engine
adding support to hls to use mpegts and dynamic mpd

I'll attch a sample of yt-dlp  settings that give performance boost compared to CRD
[Sample CRD.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/8355610/Sample.CRD.txt)

**Comment by hama3254** [comment]
There is already a multi thread option called `Hybrid Mode` this will cache the files into the temporay folder and then use ffmpeg to combine the fragments to an finished video with all the ffmpeg settings you use below.
![grafik](https://user-images.githubusercontent.com/52826614/160244963-a7476f6d-5939-4518-b581-dcbe75711fd5.png)
