### ISSUE TITLE
Anime outside the catalog of my region or country

### ISSUE THREAD

**Issue by agmvw** [hama3254/Crunchyroll-Downloader-v3.0#458]
Version : V3.8.4.0 Chromium-U12
Error: 
`System.Net.WebException: The remote server returned an error: (403) Forbidden.
at System.Net.WebClient.DownloadString(Uri address) at Crunchyroll_Downloader.Main.GetFunimationNewJS_Video(Stringv1 JsonUrl, String v1JsonData) in D:\Projecte\Crunchyroll Downloader -
v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:line 3752`
[image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_wvkFYJIfzg_38ly9KYVk.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648673722366)

Details:
- Anime: Ergo Proxy
- Free streaming, only through VPN: [image](https://ik.imagekit.io/shdtv/otros/msedge_Zdb31QzJDc_CD3EjDxHx.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648680728927)
- I created a free account: [image](https://ik.imagekit.io/shdtv/otros/4SBiAtTQSL_jv6OjGPte.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648670284734)
- Without VPN this message appears: [image](https://ik.imagekit.io/shdtv/otros/msedge_cuug8KsprT_NOq_RZ1u-.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648670704693)
- With the VPN if it works, I can play the chapter: [image](https://ik.imagekit.io/shdtv/otros/foles148DF_C_T7fGajY.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648671397191)
- Open Crunchyroll Downloader (with VPN active): [image](https://ik.imagekit.io/shdtv/otros/Avira.WebAppHost_NRZJz16CGy__1__Xe9lpbQO_.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648672761249)
- I have it configured this way: [image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_6ru0eVkmoV_IrKvcJQLU.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648673069991) | [image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_CRzVFAEc0Z_9VpTXiYoc.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648673167184)
- Seeing that the Internet goes through a VPN, and the browser plays the episode smoothly, I thought Crunchyroll Downloader would do the same, but this pops up: [image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_wvkFYJIfzg_38ly9KYVk.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648673722366)
- It doesn't make much sense, since the download wizard (IDM), detects the .ts/.m3u8 streaming signal, and is able to play it on another player: [image](https://ik.imagekit.io/shdtv/otros/msedge_AJDDaR5Qvg2_1jNNVhMuM.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648674121529) | [image](https://ik.imagekit.io/shdtv/otros/msedge_I7evBbksfo_Je-tA4k0K.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648674024126) | [image](https://ik.imagekit.io/shdtv/otros/msedge_IrbGybdv9k_EPpM1BMr-.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648674339036)
- The only problem is that the .m3u8 audio doesn't seem to work.
- IDM (Internet Download Manager) cannot download the file, this message appears: [image](https://ik.imagekit.io/shdtv/otros/IDMan_MUGhrH8QzX_1NZ0CyegF.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648674516031)
- But Allavsoft can: [image](https://ik.imagekit.io/shdtv/otros/videodownloader_yf7TVGbwM9_2Y2-7ymSi.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648674618806) | [image](https://ik.imagekit.io/shdtv/otros/videodownloader_iUROxNlzCl_tUtc2xOlm.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648674618513)
- But the problem remains the lack of audio
- The curious thing is that I tried to use the URL detected by IDM, in Crunchyroll Downloader, and it seems to try to download it with a countdown: [image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_wtmIrFW3j7_-CfWvBog8M.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648675439371)
- I tested if it worked with other anime that do not require VPN, i.e. the anime catalog is available in my region, and there were no downloading problems: [image](https://ik.imagekit.io/shdtv/otros/msedge_aRblpj7ugm_GrE-30mdq.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648676100243)
- That's when I ask, if the PC is under the effects of a VPN, and the browser has no playback issues, the streaming signal is unhindered, and Crunchyroll Downloader is running under the same VPN, is it not able to detect the download?

p.s: I don't speak English, I use the translator
p.s2: The program here tells me it is version V3.8.4.0 Chromium-U12 [image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_m6B3mK5yDX_uoKFEtaHl.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648679596171), but here it says Chromium-U13 [image](https://ik.imagekit.io/shdtv/otros/Crunchyroll_Downloader_CT4nI39Kyh_fq_ETjcjx.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648679885139)

**Comment by hama3254** [comment]
Error `403` can mean access denied due to being `mature content` you would need to login into the build in Webbrowser of the downloader with your free account to use the mature content access from the account.

**Comment by agmvw** [comment]
In the third line, I put a picture of how my account is configured
- I created a free account: [image](https://ik.imagekit.io/shdtv/otros/4SBiAtTQSL_jv6OjGPte.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648670284734)
_Restrict adult content_ off

**Comment by agmvw** [comment]
I'm with the VPN active at the moment, I managed to enter and now the download works, the little problem would be the speed, as soon as I finish I will confirm if there is no error. [image](https://ik.imagekit.io/shdtv/otros/of4OgGU0Ad_XaVXba-wq.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648706695900)

**Comment by agmvw** [comment]
It worked, and there were no errors [image](https://ik.imagekit.io/shdtv/otros/vlc_9gg8fRj4ch_qqIJkQA3t.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1648710481673)

What a great tool you have created, my respects.
