### ISSUE TITLE
Progress percentage

### ISSUE THREAD

**Issue by SethAluma** [hama3254/Crunchyroll-Downloader-v3.0#46]
Not really an issue, but a suggestion for improvement.
When an episode finishes downloading, could the progress text be changed to something like "Done (size)"?
Having something like "706.15MB/705.65MB 100%" doesn't necessarily mean "Done"/"Finished". It could mean that it's still processing.
(the above size is for My Hero Academia Season 4 OVA1)

**Comment by hama3254** [comment]
the file size is just an estimate based on the bitrate and time. 
I guess this should fix the misleading output :
![grafik](https://user-images.githubusercontent.com/52826614/91434541-3d89bf80-e865-11ea-84a0-bcd31e8f056d.png)
even if the size is still not completely correct 
![grafik](https://user-images.githubusercontent.com/52826614/91434622-5d20e800-e865-11ea-9ade-e0af6f064330.png)

**Comment by SethAluma** [comment]
Looks good. Just fix up the typing mistake, and done :)
Line 365- change "Finsihed" to "Finished".

**Comment by hama3254** [comment]
> Looks good. Just fix up the typing mistake, and done :)
> Line 365- change "Finsihed" to "Finished".

fixed
