### ISSUE TITLE
Update CefSharp Dependencies

### ISSUE THREAD

**Issue by RonBergbauer** [hama3254/Crunchyroll-Downloader-v3.0#461]
**Is your feature request related to a problem? Please describe.**
The Chromium U14 version uses CefSharp version 98.1.210 which is outdated and has known security issues. 

**Describe the solution you'd like**
Please update to latest version of the CefSharp packages. 

**Describe alternatives you've considered**

**Additional context**
I'm aware that it's unlikely that the existing security issues in this old Chromium version can be abused in the CR Downloader context.

**Comment by hama3254** [comment]
the new version will be used with the next release, it is important to keep it somewhat uptodate but since the websites you access with it are usually trustfull i don't think an immediate update is necessary
