### ISSUE TITLE
 missing segment detected

### ISSUE THREAD

**Issue by Salehx47** [hama3254/Crunchyroll-Downloader-v3.0#466]
Enter your version below, it can be found in the "About" section of the settings.
Version : v3.8.4.1 chromium-u14

Please provide a logfile or text.
You can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
[1.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/8535168/1.txt)

<details>
  <summary>Insert the logtext before the second details</summary>
    
![123](https://user-images.githubusercontent.com/95151237/164555114-464b6ceb-3323-4910-8a1a-2a8d1602d1e5.png)

</details>

**Comment by hama3254** [comment]
the logfile seems a bit strange, it seems to me like .net or windows confuses itself with the path.
the `.key` files look like a normal path but the 3 segements that come after that look mixed up which can causes an invalid path issue and so it finds missing segments. 
can you tell me what the downloader tries to do inisde the download folder?
