### ISSUE TITLE
3.8.5 Filename prefix dosen´t work

### ISSUE THREAD

**Issue by ady479** [hama3254/Crunchyroll-Downloader-v3.0#469]
Hi, when i try to config the filename from 1 to 01 it dosen´t work, the app just download the videos example: [S01 E1] not [S01 E01]
![Captura de pantalla 2022-04-27 204145](https://user-images.githubusercontent.com/89944594/165597427-27fb95d8-017e-4221-81aa-6972854d8ed7.png)
![Captura de pantalla 2022-04-27 204322](https://user-images.githubusercontent.com/89944594/165597432-7bcd5f2b-979e-416a-ba5b-61eda76aaa92.png)

**Comment by hama3254** [comment]
seems like i just did not add the line for that into the old website.
[Crunchyroll-Downloader-v3.8.6 should solve that.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.6)

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/166821516-9957b08b-1d9f-4fd9-93a5-1ea77eef58f1.png)
can add this option to CR? Thank you!
