### ISSUE TITLE
Resolution not found

### ISSUE THREAD

**Issue by WhereIsF1** [hama3254/Crunchyroll-Downloader-v3.0#470]
Sup!
Sometimes the Downloader is not able to find the correct resolution (for example 1080p) even if this one **should** exist. 
Is there any fix or workaround for this problem?

Cheers

**Comment by hama3254** [comment]
There should be a popup for you to select an available resolution if that happens.

i could say more if i would know the Anime or better the exact episode or even just the platform since CR and Funimation handel there stuff differant.

**Comment by WhereIsF1** [comment]
I'm trying to download from CR only (The Downloader is able to find the 1080p resolution even if it exists on CR) 
I know that I can select another res. but I want to download the 1080p one not a lower res. 

For exmaple: Spy x Family Ep.4 (OmU.) has 1080p but the Downloader is only finding 480p or lower?

![grafik](https://user-images.githubusercontent.com/99078094/166112228-89a14e71-a194-40a0-8aa8-2b057fa277fe.png)
![grafik](https://user-images.githubusercontent.com/99078094/166112233-e465997c-73a0-4155-a542-b0920577d85e.png)

**Comment by WhereIsF1** [comment]
After testing a bit:
Seems like this problem is CR related. The downloader was not able to find the 1080p or 720p ep but now after a couple mins I can select the 720p.

**Comment by hama3254** [comment]
This is an possible behavior if you use hardsubs to download, on there websites they use a raw stream with softsubs that the player overlays. The downloader is able to get it that way too but your player also need to support it.
