### ISSUE TITLE
Add "Windows 11" in "Software Requirements"

### ISSUE THREAD

**Issue by Tizioincognit0** [hama3254/Crunchyroll-Downloader-v3.0#472]
Hi, I'm using flawlessly Crunchyroll Downloader on Windows 11 so it shoud be added in the README.md section named "[System Requirements](https://github.com/hama3254/Crunchyroll-Downloader-v3.0#software-requirements)".

**Comment by hama3254** [comment]
The whole readme would need to redone by now but i added it for now.

**Comment by Tizioincognit0** [comment]
You've mistakenly removed Windows 11 reference in [this commit](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/commit/f2442adfcda63b326473a859f478d4844aa6d92d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
