### ISSUE TITLE
Adding an specific link results in an error

### ISSUE THREAD

**Issue by DJPlaya** [hama3254/Crunchyroll-Downloader-v3.0#473]
Hello again,
testing the newest build, i found an bug when adding URLs in the GUI.
Leaving all values on default i get the following error when clicking the download button:
![](https://i.imgur.com/KH07tI9.png)

Ive also tested release 3.8.6 with the same results.
The URL I input is:
`https://www.crunchyroll.com/de/is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon-arrow-of-the-orion/danmachi-is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon-arrow-of-the-orion-unbekannt-827117`

Using other links works fine, so i guess its probably related to that specific movie / the url layout.

**Comment by hama3254** [comment]
i guess you are not logged in and that movie requires premium, normaly that should give you a clear error message but it seeme there premium notice 

```
<h4>
      Starten Sie jetzt Ihr 14-tägiges Probeabo!    </h4>
```
most likly triggers 
```
If CBool(InStr(WebbrowserText, "<h4>")) Then ' false on movie true on series
```
so we end on the wrong code path, which is not as bad if you are really not logged in since it wont work then anyway.
please check that and report back if that was the case.

**Comment by DJPlaya** [comment]
Strangely, i am logged in.
I could verify this issue on 2 devices.

**Comment by hama3254** [comment]
i see now with an non premium movie i was able to test it now properly and i made some changes to the error handling for movies.
[I don't have time for a full release but you can test this Crunchyroll Downloader.exe](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/master/Crunchyroll%20Downloader/bin/x64/Debug/Crunchyroll%20Downloader.exe)
