### ISSUE TITLE
No. of items in status is not consistently updated

### ISSUE THREAD

**Issue by RonBergbauer** [hama3254/Crunchyroll-Downloader-v3.0#477]
A minor error:
The number of items in the download queue is not displayed correct or no updated consistently.

To reproduce:
- Setup CRD to move additions to the queue.
- Select the add dialog (+)
- Add downloads
- close the add dialog
- The main window will show "Status X Downloads in queue" (btw. I think Downloads should be lower-case here, but I'm not a native English speaker)
- Add more downloads via the dialog
- do not close the dialog, but click the link to start processing the queue
- The Status message does not get updated. It still shows the same number of items as before. It also does not update when processing the queue and the queue is getting smaller.

**Comment by hama3254** [comment]
the downloader was not allowed for the queue to update the text if anything else than the idle `Crunchyroll Downloader` was displayed, i changed that to also allow it if the same text is on display and i added the update to the faster timer from the queue availability. 
This should fix most of the issue with that.

**Comment by hama3254** [comment]
Updated is now avalible as [Crunchyroll-Downloader-v3.8.7.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.7.1)

**Comment by RonBergbauer** [comment]
I can partially confirm the fix in 3.8.7.1.  
No. of queue items is updated during adding and while downloading.
But I have a strange effect right now: The displayed number of items is alternating between the previous value and the current value (7->15->7->15 etc.)

To Replicate:
- open CR
- Add a few download to the queue, don't start the queue
- close the add dialog
- The status will show the no. of items
- open the add dialog
- add more items to the queue
- no. of items will be increased, but now it's alternating between the old value and the new one.

**Comment by RonBergbauer** [comment]
Retested with 3.8.8.1 and the remaining issue I described above seems to be fixed.
