### ISSUE TITLE
Automatic fallback to lower resolutions when processing a queue

### ISSUE THREAD

**Issue by RonBergbauer** [hama3254/Crunchyroll-Downloader-v3.0#478]
**Is your feature request related to a problem? Please describe.**
On very rare occasions Crunchyroll cannot provide high-resolution versions of an episode. This blocks queue processing in CRD as there is a popup to select a lower resolution. Also the resolution display in CRD is wrong after these cases.

**Describe the solution you'd like**
If you set the output resolution to 1080p and only a lower resolution is available, then during queue processing the next best resolution should be used without manual input. 
Also this lower resolution should only be shown for the one specific file in the queue.
Currently there is a bug, as the queue will show the lower resolution for all following items in the queue, too. It's only shown in the UI wrong, the downloads do continue with the preselected higher resolution.

**Describe alternatives you've considered**
none

**Additional context**
If needed, I will need to dig into my files. I think one example was in the Detective Conan series.

**Comment by RonBergbauer** [comment]
To replicate the issue use https://www.crunchyroll.com/de/detektiv-conan where episode 63 is not available in 720p.
Set output to 720p. Select a download range of 62-65
Download of 62 is fine, 63 shows the select box for lower res (here the fallback would avoid the manual input). 
64 and 65 will show the wrong size in the download queue window, but will download as they should in 720p.
![cr1](https://user-images.githubusercontent.com/103939616/168421977-42de1b83-530a-4952-aab8-c8596e2923b8.png)
![cr2](https://user-images.githubusercontent.com/103939616/168421978-0fbde2b4-2579-4853-ae1b-4715fe8fe7af.png)

**Comment by hama3254** [comment]
The Display issue is solved with [Crunchyroll-Downloader-v3.8.7.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.7.1) an automatic resolution switch is not planned as it would lead to unwanted results like #470

**Comment by RonBergbauer** [comment]
I can confirm the display issue mentioned above is fixed in 3.8.7.1. 
Keeping this FR open, as you still need to confirm manually the fallback to a lower resolution.

**Comment by hama3254** [comment]
> Keeping this FR open, as you still need to confirm manually the fallback to a lower resolution.

that is a design choice of me and i will not change that.
