### ISSUE TITLE
CrunchyRoll not downloading

### ISSUE THREAD

**Issue by 619beave** [hama3254/Crunchyroll-Downloader-v3.0#481]
Found it downloading Acesendance of a Bookworm episode 32.  Also found it on other episodes being posted today.  Worked yesterday with Boruto.

Log:
Thread Name: Main
Web server started at: 127.0.0.1:8080
Start loading: 5/16/2022 12:04:21 PM
get html
5/16/2022 12:04:21 PM.779
https://www.funimation.com/
get html
5/16/2022 12:04:23 PM.19
https://beta.crunchyroll.com/watch/G2XU080Q3/the-abandoned-child-of-the-cathedral-and-making-colors
0
Thread Name: Main
0
Thread Name: 
Start loading: 5/16/2022 12:06:19 PM
get html
5/16/2022 12:06:20 PM.556
https://beta.crunchyroll.com/watch/G2XU080Q3/the-abandoned-child-of-the-cathedral-and-making-colors
0
Thread Name: Main
Start loading: 5/16/2022 12:08:03 PM
get html
5/16/2022 12:08:04 PM.475
https://beta.crunchyroll.com/watch/GEVUZ4Z9D/anniversary
0
Thread Name: Main

Using latest 3.8.7.1 version

**Comment by tormento** [comment]
I was about to submit the same the same issue, just go out from beta, as temporary solution,

**Comment by hama3254** [comment]
with just a short look it seems they changed the api subdomain 0as hotfix adding the new ones seems to work.
You can try [Crunchyroll-Downloader-v3.8.7.2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.7.2)
![grafik](https://user-images.githubusercontent.com/52826614/168670496-15128c9c-0324-4e01-adc1-468b4504e626.png)

**Comment by 619beave** [comment]
Confirmed now working.

Thanks for the quick response.
