### ISSUE TITLE
Problem loading video...

### ISSUE THREAD

**Issue by Kitty154** [hama3254/Crunchyroll-Downloader-v3.0#484]
When I click the download button, it continues loading and does not download the video.
I looked in the browser screen and the crunchyroll site says "Oops, something went wrong, Please try again."

Is there something I can do to fix it?

**Comment by hama3254** [comment]
> When I click the download button, it continues loading and does not download the video.

What website and which versions of the downloader did you use?

> I looked in the browser screen and the crunchyroll site says "Oops, something went wrong, Please try again."

Thats normal, the browser can not playback h264 content.

**Comment by Eevee125** [comment]
I used the latest version of the program and crunchyroll.com

**Comment by hama3254** [comment]
> I used the latest version of the program

i would prefer to get a number since the [v3.8.7.2 Pre-release](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.7.2) fixes an issue with the crunchyroll beta website and since you use `crunchyroll.com` which is a litte unclear since and could also mean `beta.crunchyroll.com` it would be better to know exactly what you mean because i am also not able to find any issues. 


![grafik](https://user-images.githubusercontent.com/52826614/169803710-e8b990d7-deda-46ae-8fc3-23ec9c2a88c2.png)

**Comment by Kitty154** [comment]
Yes, sorry, the website is not crunchyroll.com, it is beta.crunchyroll.com

**Comment by bybpow** [comment]
For me it was in 3.7.8.1.

**Comment by Kitty154** [comment]
For me it was 3.8.7.1

**Comment by hama3254** [comment]
then i would suggest you try [v3.8.7.2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.7.2) it is marked as ` Pre-release` because i did not have the time yet to properly lookt into #481 but the respone was that it would work so it does not seems as urgend for now...

**Comment by bybpow** [comment]
As I saw "pre-release" I though it was a testing feature, my bad. 
I just tried. Now the loading panel works but when selecting episodes there's none.

**Comment by vikseven7** [comment]
Having the same issue
used v3.8.7.2 & v3.8.7.1

![ss 1](https://user-images.githubusercontent.com/102570550/170033731-e3c14ea5-a984-4eb0-90ce-1f53fa8d7217.PNG)
,

**Comment by hama3254** [comment]
> Now the loading panel works but when selecting episodes there's none.

Did you select a season or it that empty as well?

**Comment by hama3254** [comment]
> Having the same issue used v3.8.7.2 & v3.8.7.1
> 
> ![ss 1](https://user-images.githubusercontent.com/102570550/170033731-e3c14ea5-a984-4eb0-90ce-1f53fa8d7217.PNG) ,


all i can see is the browser wich is normal as stated above

> > I looked in the browser screen and the crunchyroll site says "Oops, something went wrong, Please try again."
> 
> Thats normal, the browser can not playback h264 content.
