### ISSUE TITLE
Funimation download problem

### ISSUE THREAD

**Issue by bybpow** [hama3254/Crunchyroll-Downloader-v3.0#485]
Funimation download seems broken. When trying to download an error appears (Screenshot provides later).

**Where does the issue happen?**
 - Platform: Funimation
 - Settings: Softsubs
 - Version: 3.8.7.1

**Screenshots**
![Capture](https://user-images.githubusercontent.com/62562341/169883027-d63bb802-3889-4727-a989-0273d822f605.PNG)

**Additional context**
It happens using addon and app only.

**Comment by bybpow** [comment]
If you cant replicate, I just discovered it may not be a bug but that Funimation is banning VPN IPs. If so, please close this.

**Comment by hama3254** [comment]
This is a known issue, i truned on [useUnsafeHeaderParsing](https://docs.microsoft.com/en-us/dotnet/api/system.net.configuration.httpwebrequestelement.useunsafeheaderparsing?view=netframework-4.8) which seems to has been reseted at somehow so if you want you can replace the `Crunchyroll Downloader.exe.config` with [this one](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/v3.8.6/Crunchyroll%20Downloader/bin/x64/Debug/Crunchyroll%20Downloader.exe.config)

**Comment by bybpow** [comment]
Did this and now the video is added to the queue but it never starts the download.

**Comment by hama3254** [comment]
> is that config going to stay like that?

it should have been that way the entire time, i guess the faulty pull request and reverseing it messes up with that and i did not notice.
