### ISSUE TITLE
Picks up Movies and Previews as Episode 0 (One Piece 3D2Y - S12)

### ISSUE THREAD

**Issue by shinji257** [hama3254/Crunchyroll-Downloader-v3.0#486]
**Describe the bug**
When downloading "Season 12" of One Piece (3D2Y) it picks up both the Previews and the movie itself as Episode 0 and doesn't label them appropriately at all.  

**Where does the issue happen?**
 - Platform: CrunchyRoll Beta
 - Settings SoftSubs English -- otherwise app defaults
 - Version 3.8.7.2

**Screenshots**
N/A

**Additional context**
I don't actually mind it picking them all up as S12 E00 but I would expect the files to be labelled appropriately with PV1, PV2, and 
the special episode.  I'm using Kodi naming but I disabled it and it causes the same issue.  Just removes the [S12 E00] part at the start.  Files are just getting generically named "One Piece.mkv" 

Maybe there is a request buried in here because I check Attack on Titan as well and its preview did the same thing.

~~EDIT Insert: I keep editing here.  As I'm retrieving I noticed for some reason it didn't put any of the Season 12 episodes in its own folder now.  They are all ending up in the main folder.  I can create a folder (no issue) but I thought it odd and should mention it.  Same show.~~ This part was me being stupid and apparently a setting switched that I didn't notice...
![image](https://user-images.githubusercontent.com/261005/170878026-f94f25e3-a61e-457e-86e9-8135aad47a6c.png)

So side request: When retrieving "episodes" detected as Episode 0 (ex: no episode number) then use the title of the video in its place to ensure uniqueness.  This way S12 E00 in One Piece would still end up as 3 different files.  Named PV1, PV2, and 3D2Y (or E1 - 3D2Y) appropriately.  Not sure on the latter because I don't know why it is coming through as E00 even though it shows as E1 on the website.

Alternate request: Prompt (as it is already doing) but allow renaming with a generic marker on the end of the name like (1), (2), etc.  Useful if you know there are a bunch of previews in a season.

(Yes... I know it would be easy enough for me to just skip the previews.)

Screenshots:
![image](https://user-images.githubusercontent.com/261005/170877515-77ad09d6-61de-43a9-89a1-dcfabdcb6d7b.png)
![image](https://user-images.githubusercontent.com/261005/170877523-5ee52ccc-39fa-4d44-8bf0-f98403b46cbc.png)

**Comment by hama3254** [comment]
The episode is explainable with there api data, they have more than one key inside there json.
![grafik](https://user-images.githubusercontent.com/52826614/170881820-80fb0872-bb93-4cca-ace2-7b4f5c7ed4ea.png)

![grafik](https://user-images.githubusercontent.com/52826614/170881837-a44e6b58-991c-4bd2-9990-d641e427c16c.png)

This is fixed so the latest version should get you the data CR has but for movies i would suggest that that you use another naming methode.
![grafik](https://user-images.githubusercontent.com/52826614/170882289-e73ebbc8-ecc1-4150-ae4c-0d89ba4a4663.png)

I also added preventive a fallback for no meta data 
![grafik](https://user-images.githubusercontent.com/52826614/170882430-88505e16-44ae-42f9-9571-88f8b21b7ea6.png)

**Comment by shinji257** [comment]
Awesome ;)  I'll check this later on when I'm able to.

**Comment by shinji257** [comment]
Hmm... (https://beta.crunchyroll.com/series/G4PH0WXVJ/spy-x-family)
I reset all the settings (cleared registry entries) to make sure I was on defaults.  Only settings changed for this test was to enable hybrid mode and redirect multi-download to the queue
3.8.7.1
![image](https://user-images.githubusercontent.com/261005/170928015-372f41be-b3b7-4e4a-b043-993191db6287.png)
3.8.8.0
![image](https://user-images.githubusercontent.com/261005/170928324-5fb82624-36ba-4d63-96b0-d959899b5905.png)

Processing seems fine on One Piece though as you demonstrated above.
![image](https://user-images.githubusercontent.com/261005/170928552-01df3829-8b80-4d2c-b6a5-34c7629eb84a.png)

**Comment by shinji257** [comment]
In addition something seems to have broken when it came to those same episodes.  It worked fine in 3.8.7.1 but now enabling Kodi Naming.  This is on SPY x FAMILY as above.  Possibly related to episode number again.
```
---------------------------
Crunchyroll Downloader
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at Crunchyroll_Downloader.Main.AddLeadingZeros(String txt) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:line 331

   at Crunchyroll_Downloader.Main.GetBetaVideo(String Streams, String WebsiteURL) in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:line 1914
---------------------------
OK   
---------------------------
```

**Comment by hama3254** [comment]
a small oversight made the downloader not process the episode number correctly if both values where present, this should be fixed now.

**Comment by shinji257** [comment]
Haha.  It's back to E00 again but I honestly don't care.  It's fine that way for this.  It covers the other end which ensures uniqueness by adding in the episode name when it hits E00 so I guess everything is ok now?  All scenarios seem to check out ok. 😉 Closing this now.

![image](https://user-images.githubusercontent.com/261005/171064012-45dfa6ae-259a-4ea0-bd3c-4388b4fd2747.png)
![image](https://user-images.githubusercontent.com/261005/171064247-fdea1310-5c87-4b6f-91d2-ce9a07b2b6dc.png)
