### ISSUE TITLE
Layout suggestion

### ISSUE THREAD

**Issue by ValadaresX** [hama3254/Crunchyroll-Downloader-v3.0#490]
![image](https://user-images.githubusercontent.com/88790254/171041349-32624254-b664-4cb1-914a-f0c20cb15e42.png)

1 - Save the main link of the anime
2 - Newest save of the anime
3 - Save location that was last saved

I took this initiative because I find it boring every time I'm going to download a new episode I have to get the anime's link and remember where I last saved it.

**Comment by hama3254** [comment]
> I took this initiative because I find it boring every time I'm going to download a new episode I have to get the anime's link and remember where I last saved it.

Using a bookmark in your Webbrowser should give access to the main page of any crunchyroll anime within seconds.

Selecting episodes and selecting a save location is something I think you should be able to manage yourself, for the location you even get help with the subfolder settings which can automatically create a folder for that anime.
