### ISSUE TITLE
Portuguese Brazilian Subtitles Not Detected

### ISSUE THREAD

**Issue by kirz0** [hama3254/Crunchyroll-Downloader-v3.0#491]
**Describe the bug**
Brazilian Portuguese subtitles are not being detected automatically, they must be selected manually.

**Where does the issue happen?**
 - Platform: Cruchyroll
 - Settings Softsubs
 - Version v3.8.8.1 (latest)
![Screenshot_1](https://user-images.githubusercontent.com/22869778/171729265-452081c0-9578-4179-92e1-a555e49d8945.png)

**Comment by kirz0** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/22869778/171738122-2ed33fb3-0404-4fe9-b24a-24ea16ec7c94.png)

**Comment by hama3254** [comment]
Your hard sub language is set to English, that why it does not find the correct language since only `ptBR`and no hard subs are there.
You can either change it to `ptBR` or `[null]`.
