### ISSUE TITLE
Downloading The Irresponsible Captain Tylor causes an exception to be thrown.

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#495]
Version : 3.8.8.1

[browser.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/8895409/browser.log)
or 
<details>
![dl error](https://user-images.githubusercontent.com/751507/173471263-72f44b9b-dda2-4c69-9a4d-58a397a5a276.png)

When attempting to download the Captain Taylor episodes, the system throws exception errors.    
</details>
https://beta.crunchyroll.com/series/G0XHWM4V5/the-irresponsible-captain-tylor
This occurred last week when it was new.  The series showed as updated so I made another attempt.  I do not seem to be having issues with any of the other series I attempt to download.

**Comment by Serpentstar** [comment]
![dl error](https://user-images.githubusercontent.com/751507/173471307-9af27b32-de41-4414-84eb-2981e0b23994.png)
System would not let me upload the image.

**Comment by hama3254** [comment]
this seems to the the symptom of a bigger oversight inside the stream selector.
i guess you set the Crunchyroll hardsub language to `[null]` inside the settings.
for your case it should work if you choose english as hardsub language inside the setting, which is anyway the only one avalible as far i can see.

**Comment by hama3254** [comment]
fixed with [v3.8.9](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.9)

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/182377310-e7a63809-506f-4d20-a5be-c920e4612d8a.png)
if it's not too much to ask, can you remove or put an option to skip this step if you don't have forced subtitles?
