### ISSUE TITLE
Original Soft Subtitles (.ass) files breaks Plex and Jellyfin for Smart TV

### ISSUE THREAD

**Issue by ProtocolNebula** [hama3254/Crunchyroll-Downloader-v3.0#504]
**Describe the bug**
Videos downloaded in MKV/MP4 (external sub) format don't work properly on Smart TV (plex and jellyfin causes different issues).

The issue seems to be related to the **.ass** files, if the files get removed from the folder (external) or converted (in MP4 maybe uses .srt), the video plays correctly.

> In **plex** (android native app) the subtitles never appears, meanwhile in **jellyfin** the video auto restarts after 5 seconds or less (but subtitles works as expected).

Because this issue seems to be happening only on Smart TV, I'll check both jellyfin and plex versions and also report to the respective apps. But if someone has any idea, would be great a solution.

**Where does the issue happen?**
 - Platform: Crunchyroll Beta
 - Settings Hybrid & Default, 720p, MKV, merge soft subs, default subtitles (Spanish LA) + soft subs English, Spanis (españa), Spanish (LA)
 - Version: 3.8.8.1

If needed, I can provide access to both servers in order to test.

**Same settings with MP4 with merged subtitles** works fine BUT, just fail for MKV (merged and external subtitles) and MP4  
 (external subtitles).

The MP4 merged subtitles are too generic (lose the format) so when 2 phrases appear in the screen in parallel, de 1rst gets hidden (https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/505).

**Comment by hama3254** [comment]
> **Same settings with MP4 with merged subtitles** works fine BUT, just fail for MKV (merged and external subtitles) and MP4
> (external subtitles).

This would indicate to me that both plex and jellyfin have issues with `ass` as subtitles since as just explaind in #505 `mp4` requires me to give `ffmpeg` the `-c:s mov_text` while mkv allows `ass` so i just do `-c:s copy`

i personally use Kodi on a media pc (x86/x64) and i don't have any issues there.
