### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by yentcadan** [hama3254/Crunchyroll-Downloader-v3.0#51]
Hi, I'm having some problem with crashing, I'm downloading S01E07 of Bleach, and everytime shows up "The download process seems to have crashed", so I press the play button like the software ask to do and the download repeats the same error. The version I'm using is v3.4.1, but I've tried with v3.4.2 and the same error happens. 

But thanks for the software, it's amazing after all.

**Comment by hama3254** [comment]
please enable the log file and provide me the result. 
you can activate it in the settings and the log get saved in the download directory with the same name as the video file
![grafik](https://user-images.githubusercontent.com/52826614/84301783-a6aa4280-ab54-11ea-8fae-09de14fda064.png)
![grafik](https://user-images.githubusercontent.com/52826614/92991957-5d68e680-f4e7-11ea-8a9c-5bf63510b9b6.png)

**Comment by yentcadan** [comment]
Idk where I can post or upload the file, so I've uploaded on MEGA the .log file [https://mega.nz/file/LoEAGCwS#urqctb3cS6jb2EEyG3tINghcfKKQjX8QyYjS8vznsW4](url)

**Comment by hama3254** [comment]
> Idk where I can post or upload the file, so I've uploaded on MEGA the .log file [https://mega.nz/file/LoEAGCwS#urqctb3cS6jb2EEyG3tINghcfKKQjX8QyYjS8vznsW4](url)

you should be able to just drag and drop the file in the comments here for the future.
but it's ok i also get it from mega.

the problem seems to be the stream itself, it has invalid data.

you can try it again with different resolution but i can not fix invalid downloads  

`
12/09/2020 11:35:42[mp4 @ 08103a00] Application provided duration: 3003490000 is invalid
12/09/2020 11:35:42av_interleaved_write_frame(): Invalid argument
12/09/2020 11:35:42frame= 2655 fps=205 q=-1.0 Lsize=   15375kB time=00:01:32.16 bitrate=1366.7kbits/s speed=7.12x    
12/09/2020 11:35:43video:14276kB audio:1037kB subtitle:1kB other streams:0kB global headers:0kB muxing overhead: 0.397353%
12/09/2020 11:35:43Conversion failed!
`

**Comment by yentcadan** [comment]
Sad, I've tried with the lowest resolution, but the crash still happens. Hopefully this will only happens with this episode.

**Comment by yentcadan** [comment]
without wanting to speak bad about your work (even because your downloader is the best of the plataform in question that I've seen), but I've tried to download with other downloader of skid9000, and worked with this episode, I'm telling you because if there's some error, it would be nice seeing you improve your knowledge and your software. But thanks for everything

**Comment by yentcadan** [comment]
Trying to download with other ways, I've come with a conclusion. Maybe it is a problem with the softsub, because once when I've disabled they, the crash stopped.

**Comment by hama3254** [comment]
> Trying to download with other ways, I've come with a conclusion. Maybe it is a problem with the softsub, because once when I've disabled they, the crash stopped.

This is most likely not the reason.
The problem was a invalid length in the m3u8.
I know that m3u8 are not valid unlimited so maybe you just got a new one or you used hardsub now that would also be a other m3u8 file.

**Comment by drakan08** [comment]
Here is a log, hardsub enabled and softsub disabled

[Sword Art Online Temporada 3 Episodio 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5236050/Sword.Art.Online.Temporada.3.Episodio.1.log)

**Comment by hama3254** [comment]
> 
> 
> Here is a log with hardsub enabled and softsub disabled, im getting this:
> 
> 17/9/2020 00:17:33[https @ 06c26940] HTTP error 502 Bad Gateway
> 
> [Sword Art Online Temporada 3 Episodio 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5236050/Sword.Art.Online.Temporada.3.Episodio.1.log)

http error that starts with 5 are usual server side errors which is no problem with the downloader so i can not fix it.

[from wikipedia:](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_server_errors)
![grafik](https://user-images.githubusercontent.com/52826614/93456466-047dc180-f8de-11ea-8a42-cc7bd247101e.png)

**Comment by hama3254** [comment]
> Here is a log with hardsub enabled and softsub disabled, im getting this:
> 
> 17/9/2020 00:17:33[https @ 06c26940] HTTP error 502 Bad Gateway
> 
> [Sword Art Online Temporada 3 Episodio 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5236050/Sword.Art.Online.Temporada.3.Episodio.1.log)

@drakan08 i found a issue with one of the Content Delivery Network crunchyroll uses, this results in that 502 error. 
the workaround is already online : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.4.4

**Comment by hama3254** [comment]
this seems to have been a random issue from the m3u8 side and it seems not occurred in the past two weeks so i close this issue.
if see any other problem don't hesitate and make a new issue.
