### ISSUE TITLE
Cef.Sharp.Core.Runtime.dll or a dependence can't be found

### ISSUE THREAD

**Issue by AsIFall** [hama3254/Crunchyroll-Downloader-v3.0#512]
Trying to open any new version of CR Downloader above version 3.7 will show following problem:

The file or assembly "CefSharp.Core.Runtime.dll" or a dependence of this could not be found. The specified module was not found.
I have the option to ignore the problem which opens the CR Downloader seemingly normally but only the interface is normal. I can't get access to Crunchyroll as the browser does not load. If I choose "Beenden" the program will close.

Attached screenshot
![Screenshot (152)](https://user-images.githubusercontent.com/110290203/181912683-b0485cda-381a-46df-8c14-9f222de510d4.png)

**Comment by hama3254** [comment]
You probably miss the [Microsoft Visual C++ Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) just get the x64 version or [use this direct link](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by AsIFall** [comment]
Yes, this was my problem. The CR Downloader works and I can download episodes on BETA Crunchyroll. Thank you very much!
