### ISSUE TITLE
Queued downloading of non series will overwrite existing downloads.

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#515]
**Describe the bug**
If you go to download a given show, in this case Trinity-Seven
https://beta.crunchyroll.com/series/G60914JM6/trinity-seven
and there are individual specials, the naming convention does not change.
Since these are not episodes, they automatically receive an Episode 00
In this case, Trinity Seven Episode 00.mkv
The next video download will ask if you want to overwrite it.

**Where does the issue happen?**
Crunchyroll

**Screenshots**
![image](https://user-images.githubusercontent.com/751507/182975037-57da0d27-f1e5-4cc7-902a-1b5760686403.png)

**Additional context**
Add the first video to the download queue.
Add the second video to the download queue.
Begin the queue.
The downloads are named by the shows title
The 2nd non episodic video will attempt to overwrite the first.
I was able to rename the first video 01 and the next came in as 00.

**Comment by hama3254** [comment]
Fixed in the Snapshot release.
