### ISSUE TITLE
Add Video brings up cached page first

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#516]
**Describe the bug**
When adding a video, the first attempt will generally resolve to a previous search, not the current one.

**Where does the issue happen?**
Crunchroll Beta
I don't think those are relevant to the issue.
Version 3.8.9

**Screenshots**
There are several
First, look at any series.
![image](https://user-images.githubusercontent.com/751507/183287195-9032bd4e-b85b-4a33-b87c-6bb9690f1e68.png)
Then go look at another series.
![image](https://user-images.githubusercontent.com/751507/183287208-b3552d68-bcc6-4973-b4f6-a87dacedeacf.png)
![image](https://user-images.githubusercontent.com/751507/183287216-e49b441e-b0c6-47af-988d-dd47a30be869.png)
Copy the URL and paste it into Add video
![image](https://user-images.githubusercontent.com/751507/183287228-1cf23433-fe60-44ba-bc07-85584d110a23.png)
Hit download.  You initially get a cached entry
![image](https://user-images.githubusercontent.com/751507/183287241-3f01446a-d0d1-4c2f-a5e6-a21925df83fe.png)
Hit cancel and then hit download again.
![image](https://user-images.githubusercontent.com/751507/183287253-322db227-6a61-4efd-ac43-0e41bc160ead.png)
Now you get the series you were looking for.

**Additional context**
This has been going on for a while.
When you hit download the first time, the mini-browser looks like it loads the page, but doesn't.  This happens almost every time now if you look at something before downloading the one you intend to download.

**Comment by hama3254** [comment]
This is an issue with the http observer caching while loading and the check to prevent that seem not to work for some reason.
the fix simply clear the cache everytime the procssing detects that there is no download requested.

**Comment by hama3254** [comment]
fixed with the Snapshot
