### ISSUE TITLE
Donwload not resolved when from a direct episode link

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#517]
When you paste a direct episode url, such as [this](https://beta.crunchyroll.com/it/watch/GZ7UV8M9X/a-midnight-meeting-of-peers?utm_source=cap_cr&utm_medium=carousel_2&utm_campaign=shadows-house_it&referrer=cap_cr_carousel_2_shadows-house_it_20220810), the downloader can't resolve the video file.

**Comment by hama3254** [comment]
Please read issue #511 and see if your issue persists afterwards.

**Comment by tormento** [comment]
Nope and I saw that the author had a different issue.

Yesterday evening, I tried a direct url without the ? part and it did not work either.

**Comment by hama3254** [comment]
i asume you get the same like this one 

>> . It stays in "loading" and does not start downloading.

which would make that the answer

>That would indicate that CR might serve you an invalid site like the just the homepage, this usually happens if you don't have access to the beta website but try do access it.
If you are using an account inside your Webbrowser then you need to also login inside the build-in Webbrowser of the downloader to get the same access level.

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/511#issuecomment-1196349771_

Pleache check your login and report back if that fixes the issue.

![grafik](https://user-images.githubusercontent.com/52826614/184933115-57156113-b09f-41a0-8fa0-5581095daacc.png)

**Comment by tormento** [comment]
Nope, it briefly goes on loading and then back to idle.

I have access to beta and I am a paying customer too.

**Comment by hama3254** [comment]
> Nope, it briefly goes on loading and then back to idle.

what version are you using? newer versions should not go to idle since there is not timout anymore.

**Comment by tormento** [comment]
3.8.9

**Comment by hama3254** [comment]
Please open Crunchyroll inside the build in webbrowser and see what the downloader is doing, for me it does not go to idle if i am not logged in and if i am logged in it works without a flaw 

https://user-images.githubusercontent.com/52826614/185348044-a403362d-cc3e-4dc2-95cd-7c710e2c8293.mp4
