### ISSUE TITLE
Censorship removed

### ISSUE THREAD

**Issue by dreezy-official** [hama3254/Crunchyroll-Downloader-v3.0#519]
I would like to know if it would be possible to add an option that allows us to remove the censorship of animes for +18 from crunchyroll itself?
Because I believe it is a censorship with web layers by crunchyroll itself and not by the anime broadcaster, and even a person paying to watch uncensored will always find it in a simple kiss as we are visible at https://beta.crunchyroll.com/watch/GG1U2QV0N/trials and I would like to ask for your collaboration in introducing this option if possible, thank you for your chelente work in the development of this application and happy holidays.

**Comment by hama3254** [comment]
The downloader uses the direct video file, you can see if some of censorship is part of the (hard/soft) subtitles like [the text was here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/194#issuecomment-788149745_) but I doub that.

**Comment by bybpow** [comment]
Censorship is in the video itself as is the licensed broadcast option, not the uncut. The program won't be able to do this.

**Comment by dreezy-official** [comment]
what a shame and sorry for the inconvenience...
