### ISSUE TITLE
Short skips/freezes in downloaded episodes (v3.4.2)

### ISSUE THREAD

**Issue by flatrifter** [hama3254/Crunchyroll-Downloader-v3.0#52]
![Screenshot 2020-09-14 124645](https://user-images.githubusercontent.com/71238456/93033888-40214d00-f68c-11ea-8a96-854be7d3d5a9.png)
![Screenshot 2020-09-14 124709](https://user-images.githubusercontent.com/71238456/93033890-40b9e380-f68c-11ea-83e6-c9879b943240.png)
![Screenshot 2020-09-14 124723](https://user-images.githubusercontent.com/71238456/93033892-41527a00-f68c-11ea-8edb-4dba19fcad04.png)

I recently came across this amazing app of yours, and I've been really enjoying it! The only issue I've noticed is that in most of the episodes I have downloaded there will be one or two instances of both the video and audio freezing for a second or two, and resuming as if those breif moments had played out naturally. That is to say, some sections of audio and video are lost. 

Please find screenshots of my settings attatched. It may be worth noting that, not knowing I could batch-download episodes, I added the episodes I have watched so far manually one-by-one.

**Comment by hama3254** [comment]
> Please find screenshots of my settings attatched. It may be worth noting that, not knowing I could batch-download episodes, I added the episodes I have watched so far manually one-by-one

It's would be interesting for me to know how you found my downloader, the [YouTube video](https://youtu.be/1g2-QQajZ5Y) is not good and is from v3.0 but it shows the batch download.

Another note would be the [add-on support from v3.4](https://youtu.be/ZHCH3rNWYS8)

But now to the freezing problem.
This is not a problem of my downloader, I guess it's some sort of either problem with ffmpeg this is the library I use to download the video or any random internet issue.
You are not the first one to report this but I never got any real information back.
Since I don't have this issue I can just ask to please enable the log file and send it here to me if the video has missing parts again.

**Comment by flatrifter** [comment]
Hi again,

I really love the downloader! It works brilliantly. 

When I read your reply I had already figured out the batch-download function and downloaded the rest of the series using it. It seems that the freezing issue has continued. I use a wired connection so there shouldn't be any drops in the internet connection, but the connection is pretty slow since I currently live in University accomodation. I have enabled the log file and I will send it to you after downloading a few episodes of a new series.  

Thanks for your fast reply!

**Comment by flatrifter** [comment]
Hi again Hama, 

I have attatched the logs for a download of black clover in it's entirety. A thought just hit me, as I was prompted to log in to download the latest episode of black clover which is still premium-only. Could ads cause the skips for people who aren't signed in with premium accounts? 

It's worth noting that the downloads for episodes 10 and 107 froze without finishing and I had to delete them and re-start them (probably because I ran out of space on my hard drive), and the logs for episode 107 may be incomplete since I deleted them halfway through.

**Comment by hama3254** [comment]
> Could ads cause the skips for people who aren't signed in with premium accounts?
the ads are not in the stream itself, they get added by the player so that should not be the case.

**Comment by hama3254** [comment]
@flatrifter did you find any problems in your downloads ? or can i close this issue?

**Comment by flatrifter** [comment]
Hey hama,

sorry for being slow to get back to you, I'm in the middle of my universities exam period. I'll look through the first episode or two of black clover and send you the relevant logs. Yes, there have still been skips with what I have been watching recently, but it's all just stuff from the same original download (did about 140eps at once).

**Comment by flatrifter** [comment]
[Black Clover Episode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5338020/Black.Clover.Episode.1.log)
Here are the logs for an episode I downloaded with skips in it.

**Comment by hama3254** [comment]
Thanks for the log.
unfortunately i don't see any issue in the log.
there are 717 segmentes for that stream and all have been downloaded according to the log.

**Comment by hama3254** [comment]
as example i just tryed to download something with the hybrid mode due to an other issue and found this :
`10.10.2020 22:23:14[hls @ 063e3ec0] Opening 'crypto:E:\Test\CRD-Temp-File-dQJaMKBRCfHCOCDS\0240.ts' for reading`
`10.10.2020 22:23:14[crypto @ 063f8580] Unable to open resource: E:\Test\CRD-Temp-File-dQJaMKBRCfHCOCDS\0240.ts`
`10.10.2020 22:23:14[hls @ 063e3ec0] Failed to open segment 240 of playlist 0`
so from what i can see your video should be fine, please check if the video has a problem or if it a playback issue

**Comment by flatrifter** [comment]
The episode I sent the logs for definitely had some issues, although I'm not sure how to identify the source of the problems. How can I check whether it is the video that's the problem or a playback issue? 

Also, what is the hybrid download mode?

**Comment by hama3254** [comment]
First of all the hybrid mode is a new and faster methode to download the video.
The video gets splitt into in your log as example has 717 small files.
Normally I use the existing tool 'ffmpeg' to deal with download, decryption and merging these files.
The hybrid mode an the other hand downloades all segments so I can controll the online access and 'ffmpeg' just decrypts and combines the files.

For your issue you can take a look if the error happens always on the same time or if it radom, you can also test the file on another device.
If the error is at the same time and stays on more than one device than it's the video file.

**Comment by hama3254** [comment]
Do you still have issues or does it work now?

**Comment by flatrifter** [comment]
Hi there, 
 Everything is good now. Sorry for the late reply, I've had uni exams.
