### ISSUE TITLE
Crunchy Roll isnt working on my pc

### ISSUE THREAD

**Issue by LockedInDisc** [hama3254/Crunchyroll-Downloader-v3.0#520]
When i try to download some anime or whatever even if i have the right config it will just say ¨Loading¨, and when i use another config and i am lucky i just see in the main page ¨1 Download in the queue¨ but i dont see the download, so its not downloading

Also, when i start crunchyroll downloader it tells me that i need CefSharp.Core.Runtime.dll and i dont know how to fix this

(Sorry for the bad english, i am a spanish-talker so i am trying to do my best.)

**Comment by hama3254** [comment]
You probably miss the [Microsoft Visual C++ Redistributable](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) just get the x64 version or [use this direct link](https://aka.ms/vs/17/release/vc_redist.x64.exe)
