### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by justlunix** [hama3254/Crunchyroll-Downloader-v3.0#525]
I have a good internet connection, but the episodes get downloaded with insanely slow speeds. (Crunchyroll Naruto)

![image](https://user-images.githubusercontent.com/66276367/185770666-ad5427af-6a48-4744-a941-561180174fe7.png)

![image](https://user-images.githubusercontent.com/66276367/185770677-f5f989ea-65a7-48c6-b572-fd40238ec893.png)

**Comment by hama3254** [comment]
The hybrid mode scales with the CPU threads so a better CPU (or higher settings inside the debug menu) will increase the speed.
The problem is the small file size of each segment (>10MB) so the logic has to work faster with faster internet which means scales not efficient.

**Comment by justlunix** [comment]
I have a Ryzen 5 5600X so I guess it shouldn't be that bad? Is there any way to improve this?

**Comment by hama3254** [comment]
>I have a Ryzen 5 5600X so I guess it shouldn't be that bad?

It should be able to handle more than the downloader uses which should be 6 threads.
You can open the menu with a right click on any button at the top but i would not advice to use all 64 you can set with either the test version from the quote or the [Snapshot version from here.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot)
Just as a guess you can set it to something from 12 to 24.

>one way to increase the speed would be to use more threads so i added a debug option which allows to bypass the "self estimation" of the hardware by the downloader.
[You can find the test version here:](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.8.9)
![grafik](https://user-images.githubusercontent.com/52826614/181884494-f81a3370-5ec3-4da1-8cf6-1c92c44b32f4.png)

**Comment by justlunix** [comment]
Aight, I'll try that out. Thanks!
