### ISSUE TITLE
Status bar is showing "loading..."

### ISSUE THREAD

**Issue by JOHN748** [hama3254/Crunchyroll-Downloader-v3.0#526]
I'm having an issue downloading Out of Region Content from Crunchyroll. I've tried downloading the content that's not supported in my country using VPN, It's just showing 'Loading...." in Status. I've Microsoft Visual C++ Redistributable in my pc too I don't know why it's showing "loading". Other than that I can download the content that are supported in my country, there's no issue in it!

![image](https://user-images.githubusercontent.com/48284893/185825016-f26560af-f77a-43b0-b7e9-e90cc074324e.png)

**Comment by hama3254** [comment]
If it's stuck on `loading` the CR does not serve a valid site.
This can in your case be if you Download something before enabling the VPN, CR bugs that way or you are simply not logged in at the build in Webbrowser of the downloader which means you don't have access to the beta website with it and you get redirected to the classic home page making it invalid.

**Comment by JOHN748** [comment]
Thanks, Got it!
![image](https://user-images.githubusercontent.com/48284893/185844929-bf35bbc3-7b18-48f1-b3d5-f3d53ccdc4ea.png)
