### ISSUE TITLE
Doesn'T work with "beta.crunchyroll.com"

### ISSUE THREAD

**Issue by eisbaer9** [hama3254/Crunchyroll-Downloader-v3.0#527]
Downloads don't start, when the URL ist the new "beta.crunchyroll.com".

Also there is now longer an "Go Back" Button, so you cannot go back to the Old Style Website.

For example one URL:
Series: TSUKIMICHI -Moonlit Fantasy-

Crunchyroll-Beta-URL:
https://beta.crunchyroll.com/series/GZJH3D719/tsukimichi-moonlit-fantasy-

Crunchyroll-Normal-URL:
https://www.crunchyroll.com/tsukimichi-moonlit-fantasy-

As Workaround you can use to new beta URL und get rid of "beta" and the "series/GZJH3D719" to form the old URL, then the download works again.

**Comment by hama3254** [comment]
Please check if you are logged in inside the downloaders build in webbrowser otherwise you not have access to the beta website so CR redirects you to the homepage.

**Comment by crackerbad** [comment]
> Downloads don't start, when the URL ist the new "beta.crunchyroll.com".
> 
> Also there is now longer an "Go Back" Button, so you cannot go back to the Old Style Website.
> 
> For example one URL: Series: TSUKIMICHI -Moonlit Fantasy-
> 
> Crunchyroll-Beta-URL: https://beta.crunchyroll.com/series/GZJH3D719/tsukimichi-moonlit-fantasy-
> 
> Crunchyroll-Normal-URL: https://www.crunchyroll.com/tsukimichi-moonlit-fantasy-
> 
> As Workaround you can use to new beta URL und get rid of "beta" and the "series/GZJH3D719" to form the old URL, then the download works again.

This is a recurring problem for people who live outside the US, to solve it just add a slash "/" at the end of the link

**Comment by hama3254** [comment]
> This is a recurring problem for people who live outside the US, to solve it just add a slash "/" at the end of the link.
> 
> It would be nice if the program detects that the link does not have the slash and adds it

@crackerbad Where should the slash `/` be missing? I am unable to reproduce any issue with the links from the post.

https://user-images.githubusercontent.com/52826614/186701258-036cad7e-4cc8-4da9-ad2c-d4d04df6bb69.mp4

**Comment by crackerbad** [comment]
In youtube-dlp the same problem happens and adding the slash at the end of the link works.
This error does not always happen, but those who live outside the USA can occur.

To get around this, the slash must be added to the end of the link.
Example:
without slash `https://beta.crunchyroll.com/series/GZJH3D719/tsukimichi-moonlit-fantasy-`

with slash `https://beta.crunchyroll.com/series/GZJH3D719/tsukimichi-moonlit-fantasy-/`

**Comment by hama3254** [comment]
> In youtube-dlp the same problem happens and adding the slash at the end of the link works.

i guess i found the youtube-dlp issue you refering to 
<details>
  <summary> youtube-dlp issue</summary>
  
```
[debug] [generic] Extracting URL: https://beta.crunchyroll.com/fr/watch/G9DUEQW8G
[generic] G9DUEQW8G: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] G9DUEQW8G: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://beta.crunchyroll.com/fr/watch/G9DUEQW8G
```

```
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/fr/watch/G9DUEQW8G/
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] : Retrieving episode metadata
[crunchyroll:beta] : Retrieving stream info
[crunchyroll:beta] : Downloading adaptive_hls HLS manifest
```

  
</details>

which to me just look like an url parsing issue which has nothing to do with my downloader.

Urls like `https://beta.crunchyroll.com/series/GZJH3D719/tsukimichi-moonlit-fantasy-` don't get processed at all acutally, i have an embedded Chromium browser which opens the url like every webbrowser and i just read the network traffic to get the required data.
This however only works if you could stream the video with your access so for the beta website i need an account otherwise CR redirects me to the old homepage and nothing works.
For the next version i added a information text if the downloader detects the added url to be a beta url while the downloader recives the classic hompage.
