### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fedeangeles** [hama3254/Crunchyroll-Downloader-v3.0#53]
how do I solve it? https://prnt.sc/ugqldi
![Screenshot_1](https://user-images.githubusercontent.com/71239003/93033610-5b994300-f60d-11ea-9f10-d69ebf16bd06.png)

**Comment by hama3254** [comment]
This should be fixed by installing the x86 visual c++ redistributable 2019 

>then you only can try to reinstall the x86 version from here :
>https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/24#issuecomment-640782960_

**Comment by fedeangeles** [comment]
it worked but now i have this problem
![Screenshot_1](https://user-images.githubusercontent.com/71239003/93117058-9c886a80-f694-11ea-8d25-6b2a29b470cb.png)

**Comment by hama3254** [comment]
this seems to be still the same issue.
you don't need to have "mozglue.dll" in the programm folder like in the second screen

You need the x86 version from the visual c++ redistributable 2019
[wich you can download here:](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

![grafik](https://user-images.githubusercontent.com/52826614/93120687-03714800-f6c4-11ea-9109-2538679ad19a.png)

**Comment by fedeangeles** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/71239003/93136924-17f91480-f6b3-11ea-8ee8-5b20e72ce96a.png)

**Comment by fedeangeles** [comment]
Windows Defenders .-.

gpedit.msc and regedit

![Screenshot_2](https://user-images.githubusercontent.com/71239003/93151685-f3149980-f6d2-11ea-8271-1b2aef5cee73.png)

![Screenshot_1](https://user-images.githubusercontent.com/71239003/93151324-02471780-f6d2-11ea-8a8f-4b906a8815fe.png)

**Comment by hama3254** [comment]
Does it work now?
And what Version of Windows die you use ?
(For Windows 10 please with Version Numbers)

**Comment by hama3254** [comment]
after 16 days i think this has eighter worked or you have given up anyways.
you can reopen the issue or make a new one if this or any other problem is occurring.
