### ISSUE TITLE
Add support to Crunchyroll Chapters

### ISSUE THREAD

**Issue by matant94** [hama3254/Crunchyroll-Downloader-v3.0#531]
**Is your feature request related to a problem? Please describe.**
At this moment CRD can't extract chapters from Crunchyroll ('cause just few videos have it) but they're recently added this "feature"on api  

**Describe the solution you'd like**
From https://static.crunchyroll.com/datalab-intro-v2/[VIDEO_ID] is possible to extract che chapters (ex. from _Caotious Hero_) and maybe convert it to xml to be mux into files

**Comment by hama3254** [comment]
I see they added a `SKIP INTRO` button and for that they have the data in that api.
I can add Chapters for the Intro which can be forwared/skipped with VLC and Kodi so it also should work with other players.
![grafik](https://user-images.githubusercontent.com/52826614/192724325-ebf860e4-8751-4c17-bbbc-4481b4480997.png)

**Comment by hama3254** [comment]
The core changes are done, i made some tests with merged softsubs on an MKV container but i don't have the time to test every setting for every possible ffmpeg command to there might be some issues i don't know of.
You can try it from the [Crunchyroll-Downloader-Snapshot](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot) release
