### ISSUE TITLE
Cancel führt zu einem "Crash"

### ISSUE THREAD

**Issue by ghost** [hama3254/Crunchyroll-Downloader-v3.0#532]
Moin moin,

es ist früh morgens und bin zu müde um auf englisch zu schreiben^^
Wenn man, nachdem nachdem man den Link geladen hat, auf Cancel drückt kommt es zu einem gewissen "Crash". Also wenn man versucht danach ein Link zu laden, funktioniert es nicht. Der Downloader muss neugestartet werden.

Ist aber auch schon etwas länger^^

LG

**Comment by hama3254** [comment]
Ich vermute mal mit Link ist eine übersichtsseite gemeint, da hängt der status bei mir nur aber ich kann andere seiten nach dem Canceln hinzufügen.

**Comment by hama3254** [comment]
> Habe es nochmal getestet und kann nun mit Sicherheit sagen, dass da ein Problem ist.

> Wenn man, nachdem nachdem man den Link geladen hat, auf Cancel drückt

Ich bin bei der beschreibung vom ersten `Cancel` button ausgegangen (dem kleinen oberen drüber)

Das mit dem abbrechen während er mitten im verarbeiten ist macht die sache nicht umbedingt einfach.
Ich beobachte mal die beiden änderungen bevor ich eine instabile version hochlade, akutell laufen aktive downloads ja weiter und für neue muss man nur neustarten.
