### ISSUE TITLE
Untertitel naming ist nicht mehr korrekt

### ISSUE THREAD

**Issue by ghost** [hama3254/Crunchyroll-Downloader-v3.0#533]
**Describe the bug**
Untertitel naming ist nicht mehr korrekt

**Where does the issue happen?**
 - Platform: Crunchyroll Beta
 - Settings: Softsubs
 - Version: Snapshot

**Screenshots**
https://i.imgur.com/FOlqRAn.png

**Additional context**
Joar wie bereits gesagt, wird seit der Snapshot die Untertitel nicht mehr korrekt angezeigt.

Titel 1 (VLC) und kein Name (MediaInfo) ist eigentlich der deutsche Sub
DE bzw Deutsch ist eigentlich der englische Sub^^

**Comment by hama3254** [comment]
Die `Crunchyroll-Downloader-Snapshot.zip ` version scheint nicht betroffen zu sein, bei der `Crunchyroll-Downloader-metadata.zip `  ist so ein kleiner fehler fast schon zu erwarten mit den änderungen an den ffmpeg argumenten.

>The core changes are done, i made some tests with merged softsubs on an MKV container but i don't have the time to test every setting for every possible ffmpeg command to there might be some issues i don't know of.
You can try it from the [Crunchyroll-Downloader-Snapshot](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot) release

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/531#issuecomment-1260771242_

ich schau mir das ganze mal an.

**Comment by hama3254** [comment]
Soweit ich das sehen kann sollte das mit `Crunchyroll-Downloader-metadata_1.zip` behoben sein, die gibts jetzt im [Crunchyroll-Downloader-Snapshot](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot) release

**Comment by hama3254** [comment]
> Kann man die sich automatisch löschen lassen oder sowas in der Art?

ist derzeit noch nicht eingebaut wird aber kommen.
