### ISSUE TITLE
download very slow 

### ISSUE THREAD

**Issue by Salehx47** [hama3254/Crunchyroll-Downloader-v3.0#535]
Version : Crunchyroll-Downloader-v3.8.9

https://i.imgur.com/H69tVuR.png

I used it before the hybrid download

How do I activate it, it is not in the settings?

**Comment by hama3254** [comment]
it has been moved into a drop down menu.
![grafik](https://user-images.githubusercontent.com/52826614/193444584-f0a65ed7-b4b7-4524-9e7a-8a4f7a626c96.png)
