### ISSUE TITLE
ASS saved along with episode

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#536]
In the last snapshot version the ASS is saved separately from the episode.

Is it a issue or a feature?

**Comment by hama3254** [comment]
it could be both depending on your settings. please check the merge softsubs setting.

**Comment by tormento** [comment]
> it could be both depending on your settings. please check the merge softsubs setting.

![image](https://user-images.githubusercontent.com/2351785/193462589-2caf46b8-0d7e-4a09-a2fe-e2e57d8bf470.png)

That is my configuration.

**Comment by hama3254** [comment]
This seems to be an issue with the updated merge subs, since you now got more options than on and off (for mkv at least) it may convert the old vlaues wrong.
With that settings you just need to `Save & Exit` which cleans up the old values and it should work as intended again.
