### ISSUE TITLE
Feature request: Font change

### ISSUE THREAD

**Issue by ghost** [hama3254/Crunchyroll-Downloader-v3.0#539]
Moin moin erstmal^^

Ich wollte eigentlich nur fragen, ob es möglich wäre eine Funktion im Downloader einzubauen, damit man die Fonts ändern kann.
Ich glaube, es wird ja standardmäßig Arial genommen. Dass man das zb. zu Comic Sans oder sowas ändern kann.
Oder auch ScaledBorderAndShadow (was bei Crunchyroll komischerweise auf Aus ist).

Halt paar kleinere Einstellmöglichkeit bei den Untertitel.

Oder ist das generell nicht möglich?

LG

**Comment by hama3254** [comment]
Das wird nicht kommen.
Je nach optionen wird der direkte untertitel link an ffmpeg gegeben damit hab ich da keinen einfluss mehr drauf das ist ein unfassbarer aufwand da reinzupfuschen.
