### ISSUE TITLE
Automatic remember for no hardsubs

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#540]
![image](https://user-images.githubusercontent.com/4635825/194768707-16b701f5-f633-433b-b3a4-80dd62b417b5.png)

Hi, possible to make it auto remember and just prompt for one time if the source no hardsubs?

**Comment by hama3254** [comment]
the [Snapshot](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot) version should have what you need in that case.

>i can add the option to allow unsubbed or raw video to be allowed if the audio langauge is not japanese 
>
>![grafik](https://user-images.githubusercontent.com/52826614/183084084-65d0dabd-2c04-45ed-adc4-bf7bfd95bdea.png)
![grafik](https://user-images.githubusercontent.com/52826614/183084298-97934984-87ec-4ac6-b13f-6b64bdc70fa0.png)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/503#discussioncomment-3333535_

**Comment by x3inspire** [comment]
Yes, the langunage is in english.

**Comment by hama3254** [comment]
This option should work for most of the use cases and the popup is a reliable fallback.
