### ISSUE TITLE
Deutsche Untertitelbezeichnung fehlt

### ISSUE THREAD

**Issue by ghost** [hama3254/Crunchyroll-Downloader-v3.0#541]
Moinsen,

wenn man ein Video mit [merge disabled] runterlädt, damit man die Untertitel im ASS Format bekommt, fehlt bei der deutschen Datei die Bezeichnung. Auch wenn man dann mit MKVToolNix versucht die ASS Datei mit dem Video zu mergen, wird angezeigt, dass es eine unbekannte Sprache ist.
Ist nur bei deutsch. Die anderen Sprachen scheinen alle ohne Probleme zu sein.

![alt text](https://i.imgur.com/QJD0NMo.png)

![alt text](https://i.imgur.com/My9G8xB.png)

Bei Copy scheint es aber richtig zu sein.

Wollte dich das nur wissen lassen

LG

**Comment by hama3254** [comment]
[Dafür gib es eine Option in den Einstellungen.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/426#issuecomment-1019494161)
