### ISSUE TITLE
Download Error: "Failed to create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by yuukiasuna96** [hama3254/Crunchyroll-Downloader-v3.0#544]
Download Error: "Failed to create SSL/TLS secure channel" when try to download

- Platform Crunchyroll Beta 
- Settings Softsubs, ffmpeg default, Hybrid Mode
- Version 3.8.9 / metadata_2 Version

I've used software many times, and today 14.10.2022 I have an error "Failed to create SSL/TLS secure channel"
I've debugged software with dnSpy and here an error, only on when it try to get SoftSubs or m3u8 file from v.vrv.co domain, I can't use software ( So far the software has been working well. What could be causing this error?

```
System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)  
   в System.Net.WebClient.DownloadString(Uri address)  
   в Crunchyroll_Downloader.Main.GetBetaVideo(String Streams, String WebsiteURL) в D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:2023 
```

**Comment by hama3254** [comment]
This could have differnt causes.
My main suspect would be the TLS version which is 1.2 for the downloader while the latest version is 1.3 which my Firefox uses.
![grafik](https://user-images.githubusercontent.com/52826614/195992433-14c6b629-c957-4df7-b6a9-2de9de51e687.png)
I can change that but some systems might not like that.

**Comment by hama3254** [comment]
since i don't get any issues (maybe do to there CDN) i can only give you a test version: [Crunchyroll-Downloader_TLS1.3.zip ](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot)

**Comment by yuukiasuna96** [comment]
I've tested this version: [Crunchyroll-Downloader_TLS1.3.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Snapshot) at Windows 8.1 x64
Windows version lower than Windows 10 don't support TLS 1.3..
With TLS 1.2 or lower vrv.co domain reset connection with error "Failed to create SSL/TLS secure channel"
![telegram-cloud-photo-size-2-5357373890013283427-y](https://user-images.githubusercontent.com/115808364/196103491-34aecc59-afda-41b9-a445-1cbb833e5d37.jpg)

**Comment by yuukiasuna96** [comment]
Perhaps there are network libraries for Visual Basic, that supports TLS 1.3 work on .NET Framework 4.8?
Default .NET WebClient works through SChanel and only supports Windows TLS version.. As far as I understand it is impossible to add support TLS 1.3 for Windows 8.1 SChanel. I can't test software on Windows 10..

**Comment by hama3254** [comment]
I know to little about the underlying methodes the .net framework uses.
The TLS version is also just a theorie, i see no issues with either 1.2 or 1.3 (on Windows 11).
At the time it also seems like a smaller issues since i would expect more issues being opend like the last time with funimation.

**Comment by yuukiasuna96** [comment]
The program used to work without errors, before 14 October 2022..
I did not install new program updates, I used version 3.8.9. I didn't install any system updates either.
Nothing changed, just one day the error "Failed to create SSL / TLS secure channel" began to appear.

Moreover, when software requesting domains beta.crunchyroll.com with my Windows 8.1 TLS 1.2, there is no error.

The error occurs only when software requesting the server where the subtitle file / key file or m3u8 file is stored in the playlist. For me this is CDN server v.vrv.co/evs with many parameters, and only on this request starts error "Failed to create SSL / TLS secure channel". My Google Chrome works fine and I can watch anime on Crunchyroll without errors.

From what else I noticed, the built-in Cef.Sharp browser in the software stopped loading the series itself, when opening a page with video files, an error occurs SHAK 4032 and the video image is missing. All problems starts from 14 October.

I myself do not understand the cause of the error yet..
I debugged program using dnSpy and tried to solve the problem.
If I download m3u8 file manually, by using browser from v.vrv.co domain and upload it to my hosting, replace the link to my server into the software, then debugging, then software will work, but it cannot download TS fragments of the series, because each fragment is on the same server where the m3u8 playlist is. Maybe you have a solution in the future?

**Comment by hama3254** [comment]
> From what else I noticed, the built-in Cef.Sharp browser in the software stopped loading the series itself, when opening a page with video files, an error occurs SHAK 4032 and the video image is missing. All problems starts from 14 October.

That was always the case since the browser does not playback h264.

What you could try is setting the resolution to `[Auto]` this should bypass the request for the `master.m3u8` and forward the url to the download process which should be set to `Default - ffmpeg` because the hybrid mode is build with the .net webclient.

**Comment by hama3254** [comment]
@yuukiasuna96 please try [U7](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) to see if curl works for you on windows 8

**Comment by yuukiasuna96** [comment]
@hama3254, Version U7 works on my Windows 7 and 8.1) Curl is the best option, I think

**Comment by yuukiasuna96** [comment]
> @yuukiasuna96 please try [U7](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) to see if curl works for you on windows 8

Is there any way on Windows 8.1 to use Hybrid Mode in versions U7 and U9 Indev?
The download mode via ffmpeg is too slow and there are broken fragments in the video...

**Comment by hama3254** [comment]
No, the whole hybrid mode is made with the .net webclient.
