### ISSUE TITLE
Can't download and sometimes the download is stuck in 0%.

### ISSUE THREAD

**Issue by M1STERS** [hama3254/Crunchyroll-Downloader-v3.0#55]
I've been having problems recently first the downloads (doesn't matter the anime) just keep stuck in 0% and now after a couple of try it shows an error. I upload the log of my recent try in downloading shokugeki no souma.
[Food Wars Shokugeki no Soma Season 5 Episode 11.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5240768/Food.Wars.Shokugeki.no.Soma.Season.5.Episode.11.log)

**Comment by hama3254** [comment]
i see that a small error in the ffmpeg command that is already fixed but i just forgot uploaded the release. 

I'm sorry for that, here is the update: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.4.3

>I think the addition of the audio language has caused downloads to fail in v3.4.2.
I get the attached errors while trying to download "That Time I Got Reincarnated as a Slime": [That Time I Got Reincarnated as a Slime Episode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5154677/That.Time.I.Got.Reincarnated.as.a.Slime.Episode.1.log)
-I've found the fault. ~~Will upload a pull request soon with the fix~~ Fix uploaded

_Originally posted by @SethAluma in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/45#issuecomment-684527456_

**Comment by M1STERS** [comment]
Ty now is working
