### ISSUE TITLE
New v3.9 browser issue when downloading?

### ISSUE THREAD

**Issue by MattRBX** [hama3254/Crunchyroll-Downloader-v3.0#552]
So I'm not entirely sure of what to make of this. The program functions just fine, but in the new v3.9 when downloading an episode the browser window turns into a bunch of code of some sort.

It's not a big deal to me I just thought I'd let you know.

![068299ce6aa6549d214c83cef54a352b](https://user-images.githubusercontent.com/50133749/197177745-a0c4ba38-292b-49b3-927a-626439a9acbc.png)

**Comment by hama3254** [comment]
I would not so so far and call that "planned" but i had to do some workaround for the issues i had with the switching of the website.

Just for reference a small summery of why this was needed from the issue around the CR website switch:

>i am on it but there is no current time since it's not simply chaning the name because CR did something which returns the [`HTTP 403`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) status and i don't know why yet.
![grafik](https://user-images.githubusercontent.com/52826614/196751764-34dc9838-46b0-4d69-8366-7f02372c4d59.png)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/546#issuecomment-1284293732_

 >@hama3254 Crunchyroll added a cloudflare security / bot check (or they may had it every since on their main domain). It does a pretty good job of detecting requests that are not sent from a browser.

_Originally posted by @ByteDream in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/546#issuecomment-1285334971_
      
>A very early version is available, please be patient while using i have to load everything with the webbrowser and that takes a view seconds.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev
On a related note does CR load slower than usual or do they just don't like the amount of access from me?

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/546#issuecomment-1285847298_

**Comment by MattRBX** [comment]
I see. Also thought it might be due to this version simply being an early release.
Just thought I'd let you know in case it was a bug that you weren't aware of.
