### ISSUE TITLE
Accented chatacters not parsed correctly

### ISSUE THREAD

**Issue by Tizioincognit0** [hama3254/Crunchyroll-Downloader-v3.0#554]
**Describe the bug**
When I download an Italian subtitle, accented characters are not parsed correctly

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: Subtitles only
 - Version: 3.9 Indev U4

**Screenshots**
<img width="888" alt="Schermata 2022-10-23 alle 13 49 51" src="https://user-images.githubusercontent.com/40031873/197390423-715dc9ec-2db3-4bca-9efc-89da3ca080c0.png">

**Additional context**
_Ã¨_ should be _è_, _Ã_ should be _à_, _Ã©_ should be _é_ etc.

**Comment by ET1982** [comment]
it happens to me too

**Comment by hama3254** [comment]
the encoding gets lost somewhere, if you choose merged subs (see #555) it should be fine.

**Comment by hama3254** [comment]
i rolled back the changes to cause this, [U6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases) should work fine again

**Comment by Tizioincognit0** [comment]
> i rolled back the changes to cause this, [U6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases) should work fine again

Thanks. Now it works fine.
