### ISSUE TITLE
ass subtitle separated from mkv file

### ISSUE THREAD

**Issue by ET1982** [hama3254/Crunchyroll-Downloader-v3.0#555]
Hi! Thanks for the new indev version. It works fine, normal speed... but it save mkv and ass subtitle in separated files, even though I use the same setting as before.
What am I doing wrong?

![settings](https://user-images.githubusercontent.com/108487686/197403253-e843fac5-c7dd-41de-9cd2-a6a7c4f5cf4c.png)

**Comment by hama3254** [comment]
Merge is disabled in your settings, change it to `copy` and you should have only a video with included subtitles.
![grafik](https://user-images.githubusercontent.com/52826614/197409222-fcf3b073-0fff-41eb-a1a6-44ed393a827e.png)
