### ISSUE TITLE
Regarding quality and premium

### ISSUE THREAD

**Issue by stetamatea** [hama3254/Crunchyroll-Downloader-v3.0#558]
Hello, just wanted to quickly confirm if this software downloads the files in highest available quality and untouched without any re encoding (both audio and video) for free content (even 1080p is available to free users on CR) and I wanted to know if it supports downloading of premium only exclusive content (that's not available for free users even with ads and lower quality) that requires premium account to access.

Also, have there been any know account ban risks if using this to download premium only shows?

I used to use Youtube-dl, yt-dlp and one other CR downloader from GitHub and all of those have currently stopped working (even with free content) and just throw error 403 so your downloader seems to be the only one that's working right now.

Thank in advance.

**Comment by hama3254** [comment]
Since the website change i have worked to restore the function with my account always logged in.
Therefore i don't know what you can access with a free account or without any account.
The way the downloader works should allow you to download everything available to you but i can not confirm it.

For the risk of being banned, i don't know anyone that was banned. Even my videos that had my account name in them only got taken down via DMCA without any trouble for my account.
This does not mean it's not going to happen but i have no fear personally.
You still use the software on your own risk.

**Comment by stetamatea** [comment]
> Since the website change i have worked to restore the function with my account always logged in. Therefore i don't know what you can access with a free account or without any account. The way the downloader works should allow you to download everything available to you but i can not confirm it.
> 
> For the risk of being banned, i don't know anyone that was banned. Even my videos that had my account name in them only got taken down via DMCA without any trouble for my account. This does not mean it's not going to happen but i have no fear personally. You still use the software on your own risk.

Some shows are free and available in 1080p for free even without any account, those seem to download perfectly fine

Shows like for example Soul Buster are premium only, i dont have premium account at the moment but i guess even premium only stuff should be downloadable if i am logged in with premium account?

One more thing, if show is in 1080p then the downloader downloads the best file that is avalibel from the server and doesnt do any encoding therefore reducing quality, is that right?

**Comment by hama3254** [comment]
> Shows like for example Soul Buster are premium only, i dont have premium account at the moment but i guess even premium only stuff should be downloadable if i am logged in with premium account?

Yes, you should be able to download everything you have access to.

> One more thing, if show is in 1080p then the downloader downloads the best file that is avalibel from the server and doesnt do any encoding therefore reducing quality, is that right?

by default the video stream is a copy without any post-processing. you could re-encode if you want but it's not required i personally just save space on the computer with that.

**Comment by stetamatea** [comment]
Thank you :)
