### ISSUE TITLE
Error dll mozglue

### ISSUE THREAD

**Issue by Thesinxz** [hama3254/Crunchyroll-Downloader-v3.0#56]
[](https://imgur.com/a/q9QPibi
![Capturar](https://user-images.githubusercontent.com/47324018/93711138-d8e71b00-fb19-11ea-88f7-c62cec5867ed.PNG)
)

**Comment by hama3254** [comment]
You need the x86 version from the visual c++ redistributable 2019
[wich you can download here:](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

![grafik](https://user-images.githubusercontent.com/52826614/93120687-03714800-f6c4-11ea-9109-2538679ad19a.png)

**Comment by Thesinxz** [comment]
thanks, i downloaded only x64

**Comment by hama3254** [comment]
i guess this works now so i close this issue
