### ISSUE TITLE
Error when "Save & Exit"

### ISSUE THREAD

**Issue by Mayansito** [hama3254/Crunchyroll-Downloader-v3.0#560]
![image](https://user-images.githubusercontent.com/98242308/197601177-6a9d5f68-01bd-4950-9719-5763739ebb1d.png)

When I "Save & Exit" from settings have this error.

**Comment by Serpentstar** [comment]
@Mayansito Some of us who had similar issues had good effect by right clicking on the settings button and selecting clear settings.  close the program, wait a couple of minutes and open again.
![image](https://user-images.githubusercontent.com/751507/197660020-08c93376-4797-4661-9459-09452f8ffde1.png)

**Comment by Mayansito** [comment]
> @Mayansito Some of us who had similar issues had good effect by right clicking on the settings button and selecting clear settings. close the program, wait a couple of minutes and open again. ![image](https://user-images.githubusercontent.com/751507/197660020-08c93376-4797-4661-9459-09452f8ffde1.png)

Thx. That work!
