### ISSUE TITLE
There is no way to turn off chapters for crunchyroll

### ISSUE THREAD

**Issue by deadlynjdj** [hama3254/Crunchyroll-Downloader-v3.0#561]
There are no way to turn off chapters for videos for crunchyroll.

**Comment by hama3254** [comment]
That is true, is there any reason it should be an option?

**Comment by deadlynjdj** [comment]
It messes up plex and I don't like how it looks.

**Comment by hama3254** [comment]
and option has been added with [U6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases) the chapters are disabled by default.

**Comment by deadlynjdj** [comment]
Thank you
