### ISSUE TITLE
Frozen queued when downloading in cr

### ISSUE THREAD

**Issue by lawliet675** [hama3254/Crunchyroll-Downloader-v3.0#562]
I setup a queue with a set of chapters, and after downloading a few chapters, it froze on Processing... as I show in the screenshots

 - Platform: Crunchyroll Beta
 - Settings Softsubs, ffmpeg options (see pic)
 - Version 3.9 Indev U4

![image](https://user-images.githubusercontent.com/11916495/197634036-fccaa493-8c16-4b67-b161-50d4346370e3.png)

![image](https://user-images.githubusercontent.com/11916495/197635274-bbc767c6-ad78-4d72-b171-67e0768b52b0.png)

![image](https://user-images.githubusercontent.com/11916495/197635757-f7caf367-6919-4207-8693-0a38d238610f.png)

Now I'll update to U5 and try again. 

Thanks <3!!!

**Comment by hama3254** [comment]
I am on that issue, #553 has a lot of similar reports.
The 0 before the `Thread Name: Main` should mean there where not downloadable urls loaded by the Webbrowser.
the current theory is that CR has some issues which makes the downloader receive no or invalid data.
For more please follow the mention issue #553
