### ISSUE TITLE
What determines the language for the names of the files?

### ISSUE THREAD

**Issue by flagg19** [hama3254/Crunchyroll-Downloader-v3.0#564]
Some versions ago my downloaded files where named using the my main language (Italian). Then CR started the beta for the new (now current) version, and CRD got updated to support it, and the files started to get named in English.

Now I'm on `Crunchyroll-Downloader-v3.9_Indev_U5 `, the first file I downloaded got named in Italian, then I changed a totally unrelated setting (720p -> 1080p), redownloaded the same episode, and now it's in English!

What is it that determines the language for the names of the files?

```
Example: https://www.crunchyroll.com/it/series/GY190DKQR/mob-psycho-100 (premium)
Italian: Mob Psycho 100 Episode 03 Preso dal momento! ~100%~.mkv
English: Mob Psycho 100 Episode 03 Getting Carried Away ~100%~.mkv
```

**Comment by hama3254** [comment]
> the downloader has tweo ways of finding the naming data, the direct api access starts with the default value `en-US` and then try's to read the `c_locale` from the build in webbrowser.

changed to take this part as value for the direct api access, 

![grafik](https://user-images.githubusercontent.com/52826614/198332775-3cda5f51-4ab4-4276-97ec-724be7a73247.png)
