### ISSUE TITLE
no default subtitle

### ISSUE THREAD

**Issue by ET1982** [hama3254/Crunchyroll-Downloader-v3.0#565]
Even though I set the default subtitle, it doesn't be set as default, and the episodes starts without subtitle (I have to activate manually)

I don't know if I did something wrong, or I found a small bug, or it happens to me only.

![subita](https://user-images.githubusercontent.com/108487686/197845294-6fb03de1-4d16-426e-9ebd-7c4f813c36ad.png)

**Comment by CavemanTechandGamming** [comment]
I think it's because you're using the soft sub setting and not the hard subsetting

**Comment by hama3254** [comment]
this should be fixed with [U6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases)
