### ISSUE TITLE
Error - Getting Objection data

### ISSUE THREAD

**Issue by Redhookz** [hama3254/Crunchyroll-Downloader-v3.0#566]
So every time I try downloading an episode without adding "--insecure" to curl requests, it gives me this error

**Screenshots**
![image](https://user-images.githubusercontent.com/116734588/198042404-25d4e2e0-bb90-4cbc-8ca1-3f8dd0b7fe7a.png)

![image](https://user-images.githubusercontent.com/116734588/198042198-9f888fe3-c0bb-4abc-80dc-6c80bd71da40.png)

However it starts downloading when I add it, just wanted to let you know

**Comment by hama3254** [comment]
This is known and documented with #559.

**Comment by Redhookz** [comment]
Alright then appreciate it
