### ISSUE TITLE
Accented vowels and symbols in filename

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#568]
When downloading titles with an italian account I get

![image](https://user-images.githubusercontent.com/2351785/198132434-42071058-391c-430a-947d-f3caaf343b08.png)

and the file is saved with the same error, i.e. `[S03 E04] Mob Psycho 100 Season 3 Episode 04 Albero Divino nÂ°1 ~Ecco il Fondatore`~ instead of `[S03 E04] Mob Psycho 100 Season 3 Episode 04 Albero Divino n°1 ~Ecco il Fondatore~` and `[S01 E03] Chainsaw Man Season 1 Episode 03 Dovâ€™Ã¨ Nyako` instead of `[S01 E03] Chainsaw Man Season 1 Episode 03 Dov'è Nyako`

**Comment by hama3254** [comment]
it's the same issue as in #554 just that i can not access the file any other way.
i see if i can find the point where we loose the encoding.
