### ISSUE TITLE
Multi download keeps skipping episodes.

### ISSUE THREAD

**Issue by ohitstom** [hama3254/Crunchyroll-Downloader-v3.0#570]
**Describe the bug**

**Where does the issue happen?**
 - Platform: Crunchyroll Beta (i think its beta its the new design and i cant get it to go away)
 - Settings Hardsubs
 - Version latest

**Screenshots**
![image](https://user-images.githubusercontent.com/22730962/198629803-ba0a0266-45b4-41d4-a4b0-2f4b16ced330.png)

**Comment by hama3254** [comment]
some episodes might fail to download with the current `nothing found` issue, this downloads might get skipped.
