### ISSUE TITLE
Better naming conventions.

### ISSUE THREAD

**Issue by ohitstom** [hama3254/Crunchyroll-Downloader-v3.0#571]
**Is your feature request related to a problem? Please describe.**
I use many media libraries like jellyfin, they cannot recognize the wack naming conventions you currently use.

**Describe the solution you'd like**
a more custom way to set naming conventions.

**Describe alternatives you've considered**
Or a jellyfin/plex toggle like with the kodi button eg: title [s01 e01]
Without the name of the show in it would be a nice option too.

**Comment by flagg19** [comment]
How about a "simple" textbox where we can compose the name the way we want by using placeholders? Like:

```
[S{SEASON_NUMBER}, E{EPISODE_NUMBER}] - {EPISODE_NAME}.mkv 
```
would result in:
```
[S01, E03] - whatever the title is.mkv
```

**Comment by hama3254** [comment]
you already have the option to set some custom values for the season and episode, more advanced feature are currently not planned with the current (broken) state of the downloader
![grafik](https://user-images.githubusercontent.com/52826614/198833392-6dd30a63-29c6-4569-a8cf-d490c87bef17.png)
