### ISSUE TITLE
Simultaneos Download always save in 2

### ISSUE THREAD

**Issue by ManuelDiazIsaza** [hama3254/Crunchyroll-Downloader-v3.0#572]
**Describe the bug**
When i save the settings, simultaneous download always save in 2

**Where does the issue happen?**
 - Application settings - save

**Screenshots**
![image](https://user-images.githubusercontent.com/37357573/198645264-a47fd7af-3718-4c5e-9f7b-05bb4af90475.png)
![image](https://user-images.githubusercontent.com/37357573/198645567-1713476a-1a37-43e1-90a1-c571aabc5c9c.png)

ANOTHER THING: For me is working a lot better version U6 than U7
In version U7 when i try download only audios application glitch

**Comment by hama3254** [comment]
>ANOTHER THING: For me is working a lot better version U6 than U7
In version U7 when i try download only audios application glitch

U7 has bad audio on the download?

> When i save the settings, simultaneous download always save in 2

depending on your settings this is expected behavior.
the `nvenc` encoder is limited by the driver more streams would just fail.

**Comment by ManuelDiazIsaza** [comment]
In U7 he start download the first audio, then when it is looking for the second audio the application glitch

for the setting i can put 3 and it download just fine



>

**Comment by ManuelDiazIsaza** [comment]
Like i said before, U6 is working just fine

**Comment by hama3254** [comment]
> Like i said before, U6 is working just fine

i understand that part, what i don't understand is what issue you have with U7 

>In U7 he start download the first audio, then when it is looking for the second audio the application glitch

>In version U7 when i try download only audios application glitch

i don't get what you want to tell me with that, the audio processing has not changed between the U6 and U7 

anyways i uploaded [U8](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) with some issues from U7 fixed
