### ISSUE TITLE
Freezes after every episode

### ISSUE THREAD

**Issue by lucky1804** [hama3254/Crunchyroll-Downloader-v3.0#573]
**Describe the bug**
After starting the software and downloading one episode upon adding second one the downloader freezes and needs to be restarted and then I can add second episode, this happens after every episode.
I am not trying to download all episodes at once, so I am just copy pasting episode links one by one 

**Where does the issue happen?**
 - Platform: Crunchyroll new UI
 - Settings Soft subs, no re-encoding
 - Version 3.9 U7

**Screenshots**
Just frozen on this screen 
![image](https://user-images.githubusercontent.com/202993/198741596-e3c08e05-449e-426e-bd85-56e082547c29.png)

**Additional context**
I don't remember it happening in U6 so this might be a bug that appeared in U7

**Comment by MattRBX** [comment]
Same issue here. I've been having it for a while now though also in U6.

**Comment by Djidjo2** [comment]
Same issue here with U9. Had already this issue with U7. Happens both when trying to download whole serie (all vids are added in queue) -> program freezes after 1st download ; or when adding download 1 by 1 : program freezes also after 1st download.

**Comment by ProjectBots** [comment]
same issue here with 3.9_portable

**Comment by Djidjo2** [comment]
> Edit: checking the box "redirect multi-download..." under Output in the settings seems to be a viable workaround

you mean with portable edition you are able to have more than 1 download before it freezes ? Because i tried what you tell with U9 and no change. Same for "subtitle only" download, only download 1 sub even if more than 1 is checked.
