### ISSUE TITLE
about the helper you need.

### ISSUE THREAD

**Issue by gh0stdde4d** [hama3254/Crunchyroll-Downloader-v3.0#576]
the u8 version has less gpu consumption "which seems to me an improvement" but the speed has decreased, I would like to communicate with you through discord regarding the assistant, I await your response

**Comment by hama3254** [comment]
>the u8 version has less gpu consumption "which seems to me an improvement" but the speed has decreased,

The downloader itself shoould not use the GPU, only the encoders might use the GPU if you use hardware accelerated encoding but that did not change.

> I would like to communicate with you through discord regarding the assistant, I await your response

with @petenun help i was able to find the issue with the US season finding.
The main issue left right now is the downloader becomes unresponsive and i have no real plan where to start there.

**Comment by gh0stdde4d** [comment]
@hamma3254 can you do something about the speed? now they are taking too long

**Comment by Serpentstar** [comment]
@gh0stdde4d Something you can try.  I had extremely slow downloads between versions.  As has become a standard with me now, I used the contextual menu and cleared the old settings, and then I manually deleted everything in the CRD profile folder.  That made a huge impact on my download speeds.  That, and it is now an SSD now (which shouldn't make a difference).
