### ISSUE TITLE
Crunchyroll-Downloader-v3.9_portable

### ISSUE THREAD

**Issue by janilssonn** [hama3254/Crunchyroll-Downloader-v3.0#578]
![image](https://user-images.githubusercontent.com/16007846/199369209-1e8572cf-2268-4d38-9365-cc4ad6009bcc.png)

after adding Crunchyroll-Downloader-v3.9 I can't download in queue the program just stops working nor counts the 10 seconds and with each update it gets worse :/ I love this program

https://user-images.githubusercontent.com/16007846/199370619-e462914c-2494-49d0-85a8-49fb5ecdb0cd.mp4

As in the video I had to try about 4 times for it to work and as soon as one works if it is put another one to download or when it ends the program stops working

**Comment by janilssonn** [comment]
Log
[log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/9915005/log.txt)

**Comment by hama3254** [comment]
At first i would suggest to convert the old urls into the current ones that CR uses.
You can see the difference at the screenshot, the old urls don't have some data that the Downloader might access.
For that it's the simplest to just open the episode inside your default Webbrowser and copy the url then.

**Comment by janilssonn** [comment]
> No início eu sugeriria converter as urls antigas nas atuais que o CR usa. Você pode ver a diferença na captura de tela, as urls antigas não têm alguns dados que o Downloader possa acessar. Para isso, é mais simples apenas abrir o episódio dentro do seu Webbrowser padrão e copiar a url em seguida.

but is this fixable?

**Comment by janilssonn** [comment]
![image](https://user-images.githubusercontent.com/16007846/199508846-f710b07d-5cdf-49ab-a8bd-7577855e5380.png)
it's because of /watch/ and must also be of /series/

**Comment by bybpow** [comment]
Do the GUI breaks in this portable version when adding a new video or its just me?
![Capture](https://user-images.githubusercontent.com/62562341/199614696-463b70c6-1c78-4f04-bfc6-f89c80243bc6.PNG)

**Comment by hama3254** [comment]
> Do the GUI breaks in this portable version when adding a new video or its just me? ![Capture](https://user-images.githubusercontent.com/62562341/199614696-463b70c6-1c78-4f04-bfc6-f89c80243bc6.PNG)

I changed how the items are added to the main window so this is quite possible but i did not get an other notice for that yet.

It would be nice to know how the downloads react to scrolling or a size change of the main window.

**Comment by hama3254** [comment]
> > At first i would suggest to convert the old urls into the current ones that CR uses.
> > You can see the difference at the screenshot, the old urls don't have some data that the Downloader might access.
> > For that it's the simplest to just open the episode inside your default Webbrowser and copy the url then.
> 
> but is this fixable?

I don't see what I should fix there.
CR has changed there urls and the old ones have no direct api data.
I also never tried them since I would not expect that someone uses them anymore since if you open them (like from a bookmark) CR redirects your Webbrowser to the new one.


> ![image](https://user-images.githubusercontent.com/16007846/199508846-f710b07d-5cdf-49ab-a8bd-7577855e5380.png) it's because of /watch/ and must also be of /series/

This are the two new types, the first is a direct episode and the second is a series overview.
The Downloader directly try's to resolve the `/watch/` without using the build inWebbrowser.
If that fails it will load the url inside the browser and looks at the network traffic for any data.

**Comment by bybpow** [comment]
> > Do the GUI breaks in this portable version when adding a new video or its just me? ![Capture](https://user-images.githubusercontent.com/62562341/199614696-463b70c6-1c78-4f04-bfc6-f89c80243bc6.PNG)
> 
> I changed how the items are added to the main window so this is quite possible but I did not get an other notice for that yet.
> 
> It would be nice to know how the downloads react to scrolling or a size change of the main window.

The more eps. added, the more it breaks. This is something is just happening to me with this version, the "U" versions did not. Same window size. But the "U" version crashed and this one seems to crash way less.

**Comment by LaVoieLactee** [comment]
Hi,
I stumbled upon your software by accident and I'm happy!
On the other hand, I have to add 1 episode per episode each time, and after a while, I have the window offering me to download several episodes at once that appears! But this one doesn't work... Or it works by adding an episode to the list but then it doesn't work anymore :/
I attach a capture

sorry for my english, i use google translate

https://clipchamp.com/watch/qzbl0WjV6j9

**Comment by hama3254** [comment]
@bybpow i take a look at that when I have the time.

**Comment by hama3254** [comment]
@LaVoieLactee it seems to me from the video that you are using the first version of the v3.9_Indev.
Please try a newer version, this should fix the issues with the false positive on the series extractor.

**Comment by LaVoieLactee** [comment]
> @LaVoieLacteeil me semble d'après la vidéo que vous utilisez la première version de la v3.9_Indev. Veuillez essayer une version plus récente, cela devrait résoudre les problèmes de faux positif sur l'extracteur de série.

I downloaded another one, but I no longer have the option to download several episodes at once

**Comment by LaVoieLactee** [comment]
Oh ok, I didn't understand, thank you!

**Comment by hama3254** [comment]
@bybpow i have made [a new portable version](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) with major changes to the positions for the download items

**Comment by x3inspire** [comment]
> @bybpow i have made [a new portable version](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) with major changes to the positions for the download items

Newest version items in queue not started downloading after click to work off.

![image](https://user-images.githubusercontent.com/4635825/200151671-6ce3e9eb-54f2-4ac0-a475-ce48637df24d.png)

**Comment by hama3254** [comment]
@x3inspire i see, there is an issue with the tracking of the runing downloads inside the queue.
a workaround would be to remove the finished downloads either by the red `X` of each download or restarting the downloader.
The next version will this have fixed.

**Comment by LaVoieLactee** [comment]
Hi,
I have a problem downloading the anime Re Zero
The software only downloads 600/700mb per episode instead of the usual ~1.34gb
Which means that the download episode only works 10 minutes out of the 24...
![1](https://user-images.githubusercontent.com/117389582/200168463-b2fdf0e9-02f3-447a-9fa2-09127447df52.png)

**Comment by hama3254** [comment]
@LaVoieLactee please add a log file so i can see where the issue is.

The logfile can be obtained from the right click menu and then either saving it or copying it to the clipboard

![grafik](https://user-images.githubusercontent.com/52826614/136704200-5b10f94f-c74f-408c-9ba9-13d9a3298ddb.png)

**Comment by LaVoieLactee** [comment]
> @LaVoieLacteeveuillez ajouter un fichier journal afin que je puisse voir d'où vient le problème.
> 
> Le fichier journal peut être obtenu à partir du menu contextuel, puis soit en l'enregistrant, soit en le copiant dans le presse-papiers
> 
> ![graphique](https://user-images.githubusercontent.com/52826614/136704200-5b10f94f-c74f-408c-9ba9-13d9a3298ddb.png)

[Uploading log.txt.txt…]()

**Comment by hama3254** [comment]
This seems like issues either by the CR Servers, there CDN or your DNS Server.
I can not do anything about it.
```
06/11/2022 13:34:06 [hls @ 0000025c61403cc0] Opening 'crypto+https://v.vrv.co/[segmet]' for reading
06/11/2022 13:34:06 [tcp @ 0000025c614baac0] Failed to resolve hostname v.vrv.co: The name does not resolve for the supplied parameters
06/11/2022 13:34:06 [crypto @ 0000025c635a6800] Unable to open resource: https://v.vrv.co/[segmet]
06/11/2022 13:34:06 [hls @ 0000025c61403cc0] Failed to open segment 169 of playlist 0
```

You can only enable the error detection.
![grafik](https://user-images.githubusercontent.com/52826614/200174509-a2761a71-a766-4a38-8d99-5650e92a269c.png)

**Comment by LaVoieLactee** [comment]
Alright, so this is from them, so I have no choice but to wait for it to "work again"?
Alright, so how does it feel to turn it on?

**Comment by bybpow** [comment]
@LaVoieLactee I've tested and I could download Re:Zero eps. just fine. From ES but I used a FR VPN and worked too. So probably as @hama3254 said the CDN providing you with the video is broken. You'll probably just have to wait and try again later.
Tested with ep. 2 from S2.
![2022-11-06 16_13_32-Crunchyroll Downloader](https://user-images.githubusercontent.com/62562341/200178974-a6e47015-3f58-4909-812a-71162a8efca7.png)

**Comment by bybpow** [comment]
@hama3254 another thing I notice with this version is that the default save path is in Documents. I change the Temporary path in the settings but it still downloads to Documents. Is the option in another place or it is a bug?

**Comment by hama3254** [comment]
@bybpow the video output is set on the add window, the temporary path is just for the cache of the Hybrid mode to allow the use of a another storage medium than the output path. 
I personally have the files go to my NAS while the cache is on my PC (works faster).
And what version are you using? Your re:zero test shows issues with the download items, is that already the portable_2 or the old one?

**Comment by bybpow** [comment]
@hama3254 Thanks for the clarification and sorry for the delay. I used for the test the portable version but I did download them one asset each time, I've had no time to test the new version (2), sorry.

**Comment by bybpow** [comment]
In portable v3 I have the same situation that @xILikepuddingx . Although my experience has been weird so far. Sometimes CR backend fails and returns "Nothing". The same request again have no problems and downloads the series in one try with no problem. More frequently the app freezes around ep. 5 if downloaded in bulk. What I've tested and I'm sure is that:

- GUI is now displaying as expected with new items.
- If bulk download is selected, sometimes fails because of CR response, if not it downloads correctly but is most probably the app is going to get stuck around ep. 5. This happens if bulk download is selected to use a single file. If a bundle download is selected (2 or 3 files at the same time) the app will most probably crash.

**Comment by hama3254** [comment]
I did some minor changes that should not do much (reversed the display order) but the current state is that i have no issue at all.
I condensed my last long test to just less than 7 min https://www.youtube.com/watch?v=Q64eCWrSw30

This downloads 25 episodes in 1080p with 2 at the same time with hybrid mode and `hevc_nvenc` post processing.

i added the [TestFolder.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) if someone wants to try but it more or less the same as `portable_3.zip`.

**Comment by hama3254** [comment]
> Also da sonst keiner antwortet:

Ich hab immer noch probleme das bei mir festzustellen 

> Mit der U9 habe ich bisher am wenigsten Probleme allerdings ist mir da aufgefallen, dass wenn die CPU ausgelastet ist, dass da die Freezechance deutlich erhöht wird.

Das würde im umkehrschluss bedeuten mehr CPU leistung auf das problem zu werfen hilft, das könnte auch erklären warum ich kaum welche habe
<details>
  <summary>...</summary>

![grafik](https://user-images.githubusercontent.com/52826614/202427997-5985297a-2f0b-4577-8b11-589fa5912426.png)

</details>

**Comment by hama3254** [comment]
With the still unclear cause of the freezing problem inside the lastest versions i made some bigger changes to [Crunchyroll-Downloader-v3.9_portable_4.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/edit/v3.9-Portable)
This a a release from a new experimental version, the source can [be found here](https://github.com/hama3254/experimental-Crunchyroll-Downloader-v3.x)
The core change is the removal of the CefSharp Browser which has been replaced with the [WebView2 Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).
i also have seen a handfull of times that the log at the bottom can  block the UI so i added a timeout for the log.

**Comment by hama3254** [comment]
@xILikepuddingx Es könnte die [WebView2 Runtime fehlen, die gibs hier direkt von Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)

**Comment by hama3254** [comment]
Eigentlich sollte der garnicht mehr die seiten aufmachen müssen, sowohl für Staffeln als auch für folgen gibt es direkte API zugriffe, ich brauch den browser nur noch für die cookies bzw. als login UI.
Die meisten fallback laufen auch nicht mehr auf den browser sondern zeigen fehler an warum es nicht geht. 
Das log unten wäre da hilfreich zu wissen warum er überhaupt noch etwas läd.

**Comment by x3inspire** [comment]
https://www.crunchyroll.com/series/G0XHWM45M/cinderella-chef

Getting error status not found with the latest portable version

**Comment by hama3254** [comment]
@xILikepuddingx woher die 403 fehler kommen ist mir gerade ein rätsel, selbst ohne account sollte die angfrage durchgehen.
Das CR solange läd ist ungewöhnlich, ich hab für die zukunft die filter etwas genauer gemacht um eventutellen stau zu vermeiden.
Ich hab jetzt keinen release mit den änderungen, aber nur die exe zu tauschen sollte reichen wenn du willst.
[Crunchyroll Downloader.exe](https://github.com/hama3254/experimental-Crunchyroll-Downloader-v3.x/blob/d7598bab7770565ecc24330d971d52a28123d357/Crunchyroll%20Downloader.exe)

**Comment by hama3254** [comment]
@x3inspire if you have a log for me to see whats going on would be great.

**Comment by x3inspire** [comment]
> @x3inspire if you have a log for me to see whats going on would be great.

where can i get the log?

**Comment by ms-ku** [comment]
Hallo
Man könnte meinen das CR an einem Downloadschutz herumbastelt. 
Die neue Po V4Web hatte gestern halbwegs (ab und zu wurden Folgen übersprungen/ausgelassen) funtioniert, heute gar nicht - Nothing found. 
Die Po V2 geht ohne Probleme.
Was mir gestern bei der V4 aufgefallen ist, der URL Countdown beim Add Video ist gar nicht aufgetaucht, sondern die Abfrage für Serie und Folgen kam "fast" sofort. Heute wird wieder von 10 runtergezählt und dann kommt Nothing found.
Wobei es hier unterschiede gibt
Entweder der Fehler (403) kommt gleich also es wird nichts gefunden
oder
es werden Staffel und Folgen gefunden (man kann die Staffel und die Folgen zB 1-12 auswählen) und dann kommt der Fehler für jeder einzelne Folge.

Im zweiten Fall scheint es mir an der Antwortzeit/Geschwindigkeit zu liegen. Lässt man den CRD Browser nebenher mitlaufen werden die Folgen im Browser angespielt aber sie starten zu spät. Sprich CRD bringt den Fehler zb bei Folge 2, springt zur Folge 3 und dann wird erst im Browser die Folge 2 abgespielt (hoffe das ist verständlich). 
Das würde auch die übersprungen Folgen gestern bei mir erklären.

Was mir gestern noch bei der V4 aufgefallen ist
- Kein Freezing
- Insgesamt kam mir die Anwendung schneller vor

Die Testfolder Version hängte sich bei mir sofort auf.

Grüße
msku

**Comment by hama3254** [comment]
@x3inspire with a click on the bar you get to see the log, this is just a normal text field where you can copy the conten from.
![grafik](https://user-images.githubusercontent.com/52826614/202715015-2cf56682-79fc-4ba2-88ae-c4fb3dedc4ef.png)

**Comment by hama3254** [comment]
> Man könnte meinen das CR an einem Downloadschutz herumbastelt.

wenn sie wollten wäre das schon längst erledigt, bevor überhaupt 3.0 raus kam (Dezember 2019) hatten die schon kopiergeschützte stream. Die ohne hat CR bis heute nicht entfernt, sobald das passiert war es das eh mit dem downloader.


> Was mir gestern bei der V4 aufgefallen ist, der URL Countdown beim Add Video ist gar nicht aufgetaucht, sondern die Abfrage für Serie und Folgen kam "fast" sofort.

Den API zugriff hab ich mal hinzugefügt, es sollte jetzt komplett ohne browser gehen. Ich hab nur noch einen drinnen als fallback und als login option bzw. um an die Cookies zu kommen.

>Im zweiten Fall scheint es mir an der Antwortzeit/Geschwindigkeit zu liegen. 

Das langsame laden zusammen mit wie die webseite funktioniert macht es schwer festzustellen wann wirklich was da ist.
Ich hab schon überlegt das als timeout umzubauen, damit kann ich die zeit länger machen aber sobald was gefunden wird geht der dafür aus dem warten raus.


> Was mir gestern noch bei der V4 aufgefallen ist
> 
>     * Kein Freezing
> 
>     * Insgesamt kam mir die Anwendung schneller vor

Der neue browser is hardware beschleunigt, beim alten gabs da probleme (obwohl beides schlussendlich chromium ist)
![grafik](https://user-images.githubusercontent.com/52826614/202718393-ba0b4a0c-dbe0-44c2-8082-0747589e3fed.png)

**Comment by LaVoieLactee** [comment]
Hi,
I formatted my computer, and by downloading version 3.9 Indev, I have this error message... The application launches but impossible to download the browser is buggy
![image](https://user-images.githubusercontent.com/117389582/202867452-a1518c08-285b-40ce-b325-8e7cfdf1ff1f.png)

`************** Texte de l'exception **************
System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'CefSharp.Core.Runtime.dll' ou une de ses dépendances. Le module spécifié est introuvable.
Nom de fichier : 'CefSharp.Core.Runtime.dll'
   à CefSharp.CefSettingsBase..ctor()
   à Crunchyroll_Downloader.Main.Form8_Load(Object sender, EventArgs e) dans D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Main.vb:ligne 373
   à System.EventHandler.Invoke(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnLoad(EventArgs e)
   à MetroFramework.Forms.MetroForm.OnLoad(EventArgs e) dans D:\Projecte\Crunchyroll Downloader - v3.0-final\metroframework-modern-ui\MetroFramework\Forms\MetroForm.cs:ligne 471
   à System.Windows.Forms.Form.OnCreateControl()
   à System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   à System.Windows.Forms.Control.CreateControl()
   à System.Windows.Forms.Control.WmShowWindow(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à MetroFramework.Forms.MetroForm.WndProc(Message& m) dans D:\Projecte\Crunchyroll Downloader - v3.0-final\metroframework-modern-ui\MetroFramework\Forms\MetroForm.cs:ligne 585
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)




************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Crunchyroll Downloader
    Version de l'assembly : 3.9.0.0
    Version Win32 : 3.9
    CodeBase : file:///D:/T%C3%A9l%C3%A9chargements/Crunchyroll-Downloader-v3.9_Indev/Crunchyroll%20Downloader.exe
----------------------------------------
Microsoft.VisualBasic
    Version de l'assembly : 10.0.0.0
    Version Win32 : 14.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9075.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
MetroFramework
    Version de l'assembly : 1.4.0.0
    Version Win32 : 1.4.0.0
    CodeBase : file:///D:/T%C3%A9l%C3%A9chargements/Crunchyroll-Downloader-v3.9_Indev/lib/MetroFramework.DLL
----------------------------------------
CefSharp.WinForms
    Version de l'assembly : 103.0.90.0
    Version Win32 : 103.0.90.0
    CodeBase : file:///D:/T%C3%A9l%C3%A9chargements/Crunchyroll-Downloader-v3.9_Indev/lib/CefSharp.WinForms.DLL
----------------------------------------
CefSharp.Core
    Version de l'assembly : 103.0.90.0
    Version Win32 : 103.0.90.0
    CodeBase : file:///D:/T%C3%A9l%C3%A9chargements/Crunchyroll-Downloader-v3.9_Indev/lib/CefSharp.Core.DLL
----------------------------------------
CefSharp
    Version de l'assembly : 103.0.90.0
    Version Win32 : 103.0.90.0
    CodeBase : file:///D:/T%C3%A9l%C3%A9chargements/Crunchyroll-Downloader-v3.9_Indev/lib/CefSharp.DLL
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9065.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0`

**Comment by bybpow** [comment]
What version did you download?

**Comment by LaVoieLactee** [comment]
3.8.9 indev but even with another version I have the problem, I must be missing something

**Comment by bybpow** [comment]
To be sure, did you format your PC completely? Have you updated Windows and drivers? (I know this may be stupid but it's the most common cause of errors). Lastly, did you try the last portable version?
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/download/v3.9-Portable/TestFolder.zip

**Comment by LaVoieLactee** [comment]
Ok I was just missing Microsoft Visual C++ thank you!

**Comment by hama3254** [comment]
> Weil irgendwie schon wieder kein Feedback kommt und ich Feedback wichtig finde, hier mein Feedback:

das sollte sich mit dem fehler bald wieder ändern https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/550#discussioncomment-4242005, CR hat die m3u8 geändert so gehen neue folgen akutell nicht mehr zu downloaden.

> P4 hatte ich ja geschrieben, funktionierte bei mir zumindest kein Stück. Kam immer wieder Nothing Found wie bei vielen anderen auch.

den fehler hab ich gefunden, stellt sich herraus das der countdown das laden blockiert hat... 

> Es lädt die Serie deutlich schneller rein (obwohl der Timer bei 30 ist, wird meistens direkt nach der ersten Sekunde also bei 29 der erste Download gestartet). Die nachfolgenden Downloads schneien auch ziemlich schnell rein.

ich hab die art der verarbeitung geändert. Er wartet nicht mehr und schaut was sache ist, jetzt schaut er jede sekunde ob was da ist und wenn nicht zählt er runter. Das erlaubt mir die maximale zeit anzuheben (eben jetzt 30 sekunden) ohne das es immer so lange dauert. 


> Muss mich noch bisschen dran gewöhnen, dass die Downloads nun von oben reinkommen :D

Ich weiß echt nicht warum ich das je anders gemacht habe, das war nur ein workaround für die geänderte UI aber es macht schon sinn den neusten immer oben zu haben.

> Das Einzige was mir aufgefallen ist, dass der Download bisschen langsam ist. Ansonsten sieht es so aus, dass alles wieder wie früher funktioniert.

es gab immer schon massive unterschiede je nach folge, ich teste hauptsächlich mit einer show die kürzere folgen hat (RWBY S2) und da kann die 2:30 min folge schon mal länger dauernt als die 16min folge zum downloaden. Ich hab keinen plan warum.



> Kleiner Nachtrag:
> Ich muss allerdings noch erwähnen, dass ich seit gestern einen neuen PC habe und deswegen die ganzen Sachen nicht ganz Aussagekräftig sind. Es kann durchaus sein, dass bei älteren PCs weiterhin diese Probleme auftreten könnten.

Das hab ich auf dem schirm, kann aber nicht viel dagegen machen weil 12900k@5.1GHz ist neben der hauptfunktion als Heizung auch noch recht schnell unterwegs.

**Comment by hama3254** [comment]
>Und zwar die Anzeige der Auflösung stimmt nicht überein, wenn dieser in der angegeben Auflösung nicht verfügbar ist.

der erste download hat bei mir tatächlich soagar gepasst, das der downloader es sich mitlerweile merkt hat bei mir den standart wert anzeigen lassen weil die abfrage dafür nicht ausgelegt war.
Sieht aber jetzt gut aus.
![grafik](https://user-images.githubusercontent.com/52826614/204328083-b0cb10af-3f8b-4822-b348-d1c5e742a561.png)

> und auch bei None stand früher die ausgegebene Sprache.

Das war in der Beta nie vorhanden, ich weiß immer noch nicht wie ich das genau handhaben sollte, aktuell würde es so aussehen, zwei softsubs sollte kaum einer haben und hardsub geht eh nur einer.
![grafik](https://user-images.githubusercontent.com/52826614/204327416-01a38ef5-d982-4acf-a6d1-17c381a610d8.png)

**Comment by MattRBX** [comment]
Hey lil' question here. I was looking at the "ffmpeg command" tab and i saw this thing at the back which is grayed out no matter what you choose. Upon closer inspection i see "aac" is this for audio re-encoding? I'm assuming it is and I'm just wondering why it hasn't been added as an option yet. I know it's probably not priority #1 right now but It would be a nice feature to see.

screenshot: https://i.gyazo.com/fdf98245172f95be92eb6429104034de.png

**Comment by ManuelDiazIsaza** [comment]
Ey Hama... when im downloading AAC Audio please allow the simultaneos download more than 2, actually when im download video is fine, but for download audio is really bad

![image](https://user-images.githubusercontent.com/37357573/204952000-ae66445a-34a7-491e-9285-efc820c17d84.png)

I want when i select AAC Audio Only in Format i can download more than 2, i see i can do that when i put in the ffmpeg comand copy but is upset change all the ffmpeg comand every time i want download audio or video... thanks man

**Comment by hama3254** [comment]
> Hey lil' question here. I was looking at the "ffmpeg command" tab and i saw this thing at the back which is grayed out no matter what you choose. Upon closer inspection i see "aac" is this for audio re-encoding? I'm assuming it is and I'm just wondering why it hasn't been added as an option yet. I know it's probably not priority #1 right now but It would be a nice feature to see.
> 
> screenshot: https://i.gyazo.com/fdf98245172f95be92eb6429104034de.png

This is needed since I only specifiy the `-c:v` for the video in some cases so i had to add `-c:a copy` for the audio and save it into the command.
There is no processing planned for audio.

**Comment by hama3254** [comment]
@ManuelDiazIsaza i see what I can do about it, i simply did not think about your case for that limit.
The limit of 2 is triggered if a `nvenc` is selected due to driver limitations but with only AAC there should no `nvenc` used so it should be fine to allow more than 2 in this case.

**Comment by hama3254** [comment]
It seems to me that all questions are answered, i keep this open as read-only for a view more days.
For new issues or questions everyone can feel free to create a new issue.
