### ISSUE TITLE
Download multiple formats together

### ISSUE THREAD

**Issue by ZioBomba-AW** [hama3254/Crunchyroll-Downloader-v3.0#58]
Hello would it be possible to add a feature that downloads the video in all resolutions available on crunchyroll? for example Ahiru no sora episode 1 should download it in 1080p, 720p, 480p and 360p.
Thanks

**Comment by hama3254** [comment]
I don't see any use for this and it would be difficult so i don't add something like this.
You can however use a "bug" in the  downloader with the "[Auto]" settings and the "merge subs with video file" option.
It will download all available Streams of the set hard-sub language.
![grafik](https://user-images.githubusercontent.com/52826614/94271176-8bb3e080-ff41-11ea-8b9d-cb25bd66212c.png)
the output file will contain every resolution most likely twice :
[demo.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5282974/demo.txt)

**Comment by hama3254** [comment]
the requested "feature" is already in the downloader so i close this issue now.
