### ISSUE TITLE
Fehlermeldungen beim Download

### ISSUE THREAD

**Issue by LTech77** [hama3254/Crunchyroll-Downloader-v3.0#582]
Hi, bekomme leider beim Download gerade immer diese Fehlermeldung und es werden viele Dateien erzeugt, ohne dass diese gelöscht werden.
Benutze die v3.9_Indev_U9
LG
![image](https://user-images.githubusercontent.com/83650927/200035026-2232a9b1-6de6-4dc8-9491-e132fc1cba41.png)
![image](https://user-images.githubusercontent.com/83650927/200035510-282bc9ce-e4cb-4635-a4f5-dc61a63490df.png)

**Comment by hama3254** [comment]
ich bin bisher einfach nicht dazu gekommen die metadaten zu löschen, die kann man aber auch einfach per hand löschen.
Zum fehler kann ich nicht viel sagen, die zeilenangabe macht keinen sinn.
Ich müsste das selbst anschauen mit genau derselben folge um das nachvolziehen zu können.

**Comment by LTech77** [comment]
Metadata habe ich jetzt per Hand gelöscht. Der Fehler tritt aber relativ zufällig auf, egal welche Serie. Habe aber festgestellt, dass meist in Verbindung damit sich der Download aufhängt und ober "URL 10" steht.

**Comment by hama3254** [comment]
die neue [`Crunchyroll-Downloader-v3.9_portable_3.zip`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) räumt jetzt auch die metadaten auf.

**Comment by LTech77** [comment]
Habe jetzt die neue [https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable](url) ausprobiert. Läuft aber jetzt leider gar nicht mehr bei mir. Es bricht entweder nach 2 Episoden oder direkt beim Laden ab. (CR-Downloader Freezed)

**Comment by hama3254** [comment]
das die `portable_3` nicht geht hab ich schon gehört ich kann es aber überhaupt nicht nachvollziehen wie hier beschrieben: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/578#issuecomment-1312547035

**Comment by LTech77** [comment]
Der CRD sieht gerade wieder so aus und reagiert gar nicht mehr:
![image](https://user-images.githubusercontent.com/83650927/201533778-bcfe4f36-474e-45d8-aea7-e61c3d25a203.png)
Nach dem Schließen über Taskmanager läuft FFmpeg aber gerade weiter und der Error stop scheint auch nicht zu funktionieren:
![image](https://user-images.githubusercontent.com/83650927/201533937-bcb7e41d-49c7-433f-89d1-e4fd2cee18dd.png)
Meine Einstellungen:
![image](https://user-images.githubusercontent.com/83650927/201534008-c77663e8-e548-4988-a50b-04c3170e87e9.png)
![image](https://user-images.githubusercontent.com/83650927/201534028-ae9155a8-7d6a-4ecb-8066-076acf772129.png)
![image](https://user-images.githubusercontent.com/83650927/201534040-ca4a9ee4-1787-456c-bb79-c0afc6564bec.png)
![image](https://user-images.githubusercontent.com/83650927/201534054-2a2d7bbe-c5b3-413e-a934-1ae86d7eed99.png)

Getestet mit der "TestFolder", gleiches Problem aber auch mit der portabel U2 und U3.
Habe gesehen das du Hybrid anhast, probiere das gleich mal aus.

**Comment by LTech77** [comment]
Habe nochmal ein Test mit der "TestFolader" Version gemacht und die ist immer sofort eingefroren als ich etwas Herunterladen wollte. Egal ob Hybrid Modus an/aus bzw Queue an/aus. U3 mit Hybrid Modus an und Queue aus scheint gerade zu funktionieren.

**Comment by hama3254** [comment]
[--insecure`](https://curl.se/docs/manpage.html#-k) ist eine option für [curl](https://curl.se/)
für die freezing probleme haben wir sowohl #575 als auch #578
