### ISSUE TITLE
Start network scan failed, so could not download anything.

### ISSUE THREAD

**Issue by YFTX2015** [hama3254/Crunchyroll-Downloader-v3.0#589]
Enter your version below, it can be found in the "About" section of the settings.
Version : v3.9.10

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
2022/11/14-18:34:35.822 2d08 Reusing MANIFEST C:\Users\YFTX2\Desktop\TestFolder\CRD-Profile/MANIFEST-000001
2022/11/14-18:34:35.824 2d08 Recovering log #3

or 

<details>
  <summary>Insert the logtext before the second details</summary>
    
[000003.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10002125/000003.log)

</details>
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/201638214-74af41b4-7bdc-42de-a5c9-949a9a4f9c54.png)
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/201638219-5c93fb28-5f31-4516-9549-fc7521c4b09f.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/201640043-88555456-3e48-4fd8-aef9-857a8230603a.png)

**Comment by hama3254** [comment]
the `Error - Getting ObjectJson data` was caused in the past (#559) from invalid SSL/TLS settings, you can try the [`--insecure`](https://curl.se/docs/manpage.html#-k) option inside the settings.

**Comment by YFTX2015** [comment]
Even if I selected the --insecure option, the Error - Getting ObjectJson data still appeared.
![屏幕截图(4)](https://user-images.githubusercontent.com/12757305/202924768-ae1eb12f-6974-44c8-9b37-8bf24fe78969.png)
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/202924769-9a8e6145-3696-4f6e-9436-c1b92f8eaa4c.png)
