### ISSUE TITLE
error in v3.9 portable 4

### ISSUE THREAD

**Issue by YFTX2015** [hama3254/Crunchyroll-Downloader-v3.0#592]
Even if I selected the --insecure option, the Error - Getting ObjectJson data still appeared.
![屏幕截图(4)](https://user-images.githubusercontent.com/12757305/202924768-ae1eb12f-6974-44c8-9b37-8bf24fe78969.png)
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/202924769-9a8e6145-3696-4f6e-9436-c1b92f8eaa4c.png)

_Originally posted by @YFTX2015 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/589#issuecomment-1321236216_

**Comment by hama3254** [comment]
the error code `403` is one of the [HTTP response status codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses) and means in this case means [`Forbidden`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403).
the downloader should log the url it tries to open and can be found here.
![grafik](https://user-images.githubusercontent.com/52826614/202715015-2cf56682-79fc-4ba2-88ae-c4fb3dedc4ef.png)

**Comment by YFTX2015** [comment]
The log is here:
Thread Name: Main
Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
NavigationCompleted: 2022/11/24 18:19:51
2022/11/24 18:19:51.574
https://www.crunchyroll.com/
Just Browsing, exiting...
Start loading: 2022/11/24 18:19:52

CurlPost-E: curl: (28) Failed to connect to www.crunchyroll.com port 443 after 11327 ms: Timed out


CurlPost-E: curl: (28) Failed to connect to www.crunchyroll.com port 443 after 11273 ms: Timed out

Crunchyroll-Single: https://www.crunchyroll.com/cms/v2/US/M2/crunchyroll/videos/GPPFKP8QQ/streams?locale=en-US&Signature=a3BBfq-sZJyKMg3RLlxepzwWF0-VSkBM-QlmIoCwY0ZBMdnSvySVz2GSCfO~LpL32q3MjEqYR4THP9hangulEPHuUl3eETAZQjFC5kggekJdWhXaGL~~3K~9TNnscUIWLZTKSuSuCuOG239sKlPAGegS9QZx8HFww-nDVQF8lsGa08Ijv-c0oS6aP9M5ME5OuDpFOTf2iTNty2UX7PHaNydrnaoFY-toV3wUGCkzRc~LTBgIWE2RHhl7AgbrEECOe3g5fXVTyggRAnMdoPxBNmXlYfK5X9MBLbeq9ubF2udjrYw2LjBDuJajhVoLGaF5WgcRMrLmlcpL---wk5~hGQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY5MzcxNjIyfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
Crunchyroll-Season: https://www.crunchyroll.com/cms/v2/US/M2/crunchyroll/seasons?series_id=GG5H5XMWV&locale=en-US&Signature=a3BBfq-sZJyKMg3RLlxepzwWF0-VSkBM-QlmIoCwY0ZBMdnSvySVz2GSCfO~LpL32q3MjEqYR4THP9hangulEPHuUl3eETAZQjFC5kggekJdWhXaGL~~3K~9TNnscUIWLZTKSuSuCuOG239sKlPAGegS9QZx8HFww-nDVQF8lsGa08Ijv-c0oS6aP9M5ME5OuDpFOTf2iTNty2UX7PHaNydrnaoFY-toV3wUGCkzRc~LTBgIWE2RHhl7AgbrEECOe3g5fXVTyggRAnMdoPxBNmXlYfK5X9MBLbeq9ubF2udjrYw2LjBDuJajhVoLGaF5WgcRMrLmlcpL---wk5~hGQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY5MzcxNjIyfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
NavigationCompleted: 2022/11/24 18:20:19
2022/11/24 18:20:19.356
https://www.crunchyroll.com/watch/GMKUXKEZZ/the-holy-mans-voyage
LoadedUrls: 2
LoadedUrls: https://www.crunchyroll.com/cms/v2/US/M2/crunchyroll/videos/GPPFKP8QQ/streams?locale=en-US&Signature=a3BBfq-sZJyKMg3RLlxepzwWF0-VSkBM-QlmIoCwY0ZBMdnSvySVz2GSCfO~LpL32q3MjEqYR4THP9hangulEPHuUl3eETAZQjFC5kggekJdWhXaGL~~3K~9TNnscUIWLZTKSuSuCuOG239sKlPAGegS9QZx8HFww-nDVQF8lsGa08Ijv-c0oS6aP9M5ME5OuDpFOTf2iTNty2UX7PHaNydrnaoFY-toV3wUGCkzRc~LTBgIWE2RHhl7AgbrEECOe3g5fXVTyggRAnMdoPxBNmXlYfK5X9MBLbeq9ubF2udjrYw2LjBDuJajhVoLGaF5WgcRMrLmlcpL---wk5~hGQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY5MzcxNjIyfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
LoadedUrls: https://www.crunchyroll.com/cms/v2/US/M2/crunchyroll/seasons?series_id=GG5H5XMWV&locale=en-US&Signature=a3BBfq-sZJyKMg3RLlxepzwWF0-VSkBM-QlmIoCwY0ZBMdnSvySVz2GSCfO~LpL32q3MjEqYR4THP9hangulEPHuUl3eETAZQjFC5kggekJdWhXaGL~~3K~9TNnscUIWLZTKSuSuCuOG239sKlPAGegS9QZx8HFww-nDVQF8lsGa08Ijv-c0oS6aP9M5ME5OuDpFOTf2iTNty2UX7PHaNydrnaoFY-toV3wUGCkzRc~LTBgIWE2RHhl7AgbrEECOe3g5fXVTyggRAnMdoPxBNmXlYfK5X9MBLbeq9ubF2udjrYw2LjBDuJajhVoLGaF5WgcRMrLmlcpL---wk5~hGQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY5MzcxNjIyfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
2
2022/11/24 18:20:29 Thread Name: Main
Crunchyroll episode found
ProcessUrls
https://www.crunchyroll.com/cms/v2/US/M2/crunchyroll/videos/GPPFKP8QQ/streams?locale=en-US&Signature=a3BBfq-sZJyKMg3RLlxepzwWF0-VSkBM-QlmIoCwY0ZBMdnSvySVz2GSCfO~LpL32q3MjEqYR4THP9hangulEPHuUl3eETAZQjFC5kggekJdWhXaGL~~3K~9TNnscUIWLZTKSuSuCuOG239sKlPAGegS9QZx8HFww-nDVQF8lsGa08Ijv-c0oS6aP9M5ME5OuDpFOTf2iTNty2UX7PHaNydrnaoFY-toV3wUGCkzRc~LTBgIWE2RHhl7AgbrEECOe3g5fXVTyggRAnMdoPxBNmXlYfK5X9MBLbeq9ubF2udjrYw2LjBDuJajhVoLGaF5WgcRMrLmlcpL---wk5~hGQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY5MzcxNjIyfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA


Website: https://www.crunchyroll.com/watch/GMKUXKEZZ/the-holy-mans-voyage
https://www.crunchyroll.com/cms/v2/US/M2/crunchyroll/objects/GMKUXKEZZ?locale=en-US&Signature=a3BBfq-sZJyKMg3RLlxepzwWF0-VSkBM-QlmIoCwY0ZBMdnSvySVz2GSCfO~LpL32q3MjEqYR4THP9hangulEPHuUl3eETAZQjFC5kggekJdWhXaGL~~3K~9TNnscUIWLZTKSuSuCuOG239sKlPAGegS9QZx8HFww-nDVQF8lsGa08Ijv-c0oS6aP9M5ME5OuDpFOTf2iTNty2UX7PHaNydrnaoFY-toV3wUGCkzRc~LTBgIWE2RHhl7AgbrEECOe3g5fXVTyggRAnMdoPxBNmXlYfK5X9MBLbeq9ubF2udjrYw2LjBDuJajhVoLGaF5WgcRMrLmlcpL---wk5~hGQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjY5MzcxNjIyfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA

curl-E: curl: (28) Failed to connect to www.crunchyroll.com port 443 after 11267 ms: Timed out


curl-E: curl: (28) Failed to connect to www.crunchyroll.com port 443 after 11273 ms: Timed out

**Comment by YFTX2015** [comment]
No webserver started at:

**Comment by hama3254** [comment]
> No webserver started at:

The message about the webserver is only for the add-on support.

The reason it does not work for you is the timeout, the downloader requests resources from CR which they don't respond to within the 11000ms or just over 11 seconds which then gives you a timeout

**Comment by YFTX2015** [comment]
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/203799120-0dfd29f3-8975-4249-9834-49868419e68d.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/203799131-467c73a6-4d22-41a3-9cbe-8cec3f414c4d.png)
So how can I resolve this issue?

**Comment by hama3254** [comment]
i don't see any issues on the screenshots and the old issues are either timeouts or [HTTP response status code 403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) which seem to not be caused by the downloader.

**Comment by YFTX2015** [comment]
Added Crunchyroll url to Allow unsafe URLs in Clash Settings and resolved it.
