### ISSUE TITLE
Download Error - Crunchyroll Downloader 3.9

### ISSUE THREAD

**Issue by NICOHACKER2021** [hama3254/Crunchyroll-Downloader-v3.0#595]
![DAMN](https://user-images.githubusercontent.com/87403023/203540442-688dfbe3-4d7c-4af5-9736-afb427d6f819.png)

Does that mean I need to log in to my Crunchyroll account to download? :(

**Comment by hama3254** [comment]
The downloader has the same requirements as the CR website, this error apears if the respone of CR has not video streams in it.
This usually happens on episodes that require an premium account so loggin in inside the downloaders build-in webbrowser should be the solution.
