### ISSUE TITLE
Error nothing not found

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#596]
Crunchyroll-Downloader-v3.9_portable_4.zip

Got an error nothing not found, please check the log.
[error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10075657/error.log)

**Comment by hama3254** [comment]
[Crunchyroll-Downloader-v3.9_portable_5.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) should help with this type of issue

**Comment by lan2929** [comment]
Unfortunately it still doesn't work. It reports the following error:
"Error - Getting ObjectJson data
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above."

**Comment by hama3254** [comment]
@lan2929  this is a known issue but not on the client end, as mentioned inside #559 you can tell `curl` to ignore this issue which is done with this setting.
![grafik](https://user-images.githubusercontent.com/52826614/204052922-0871ce84-ca4c-4509-8c73-61593b2ee1c7.png)

**Comment by lan2929** [comment]
Works! Thank you!
