### ISSUE TITLE
In Dev Version verwirft US-Cookie beim Runterladen.

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#6]
Der Fehler Betrifft: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/3.x
Wenn ich mit den US-Cookie (Der jedes mal Funktioniert jetzt) Versuche was runterzuladen gehen die ersten 3 Videos und dann bekomme ich einen Error Spam "Enter a Valid URL" und es lädt halt nur die ersten 3 Folgen Runter.

Bei deinen [Basic Release 3.0.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/3.0) Funktioniert der US Key sobald er einmal Funktionierte, dauert halt nur bis der Funktioniert.

**Comment by KoroFX** [comment]
Und dein "Nutz n VPN" kannst du dir auch sparen da du es ja gefixt hast das das javascript so verbuggt war.

**Comment by hama3254** [comment]
ich kann den Fehler leider nicht nachvollziehen (siehe Video), ich kann jetzt sogar den Downloader schließen und dennoch bleibt der US cookie drinnen.
benutzt du für den Firefox/Gecko im downloader den selben Firefox Profilordner wie beim Normlen (wenn überhaupt installiert)? 
https://www.youtube.com/watch?v=eAWqEX90_40

**Comment by KoroFX** [comment]
Ich benutze kein Firefox persönlich, ich benutze die eingebauten sachen und muss auch jedes mal den cookie auswählen und wie gesagt wenn ich was runterlade kommt dann irgendwann der fehler enter a valid url und wenn ich nachgucke ist das weil der cookie weg ist.

**Comment by KoroFX** [comment]
Wie gesagt das setzen des cookies funktioniert in der neuen version einwandfrei aber es verwirft den cookie beim runterladen komischerweise.

**Comment by KoroFX** [comment]
Wenn du discord hast (sehe da nur TS) meld dich mal und ich zeig dir was ich meine (koro#0001) aber du müsstest doch selber wissen zu welchen fehler der fehlercode gehört, du hast ihn ja einprogrammiert ^^

**Comment by KoroFX** [comment]
Oder in den Moment kommt dann der Typische Vorführeffekt XD

**Comment by hama3254** [comment]
> BTW du müsstest doch selber wissen zu welchen fehler der fehlercode gehört, du hast ihn ja einprogrammiert ^^

ich weiß warum die fehlermeldung kommmt, in der website welche offen ist kein anzeichen einer gültigen url wie z.b. "hardsub_lang" für eine stream seite oder "season-dropdown content-menu block" und "wrapper container-shadow hover-classes" für eine übersicht

**Comment by KoroFX** [comment]
Auch weil die folge nicht verfügbar ist ? Weil wenn nicht kann das auch sein das, der cookie noch da ist, ich einfach blind bin und das n anderer fehler ist ?

**Comment by KoroFX** [comment]
Aber wenn es auch sein kann das die folge nicht verfügbar ist dann wirds der cookie sein der weg ist.

**Comment by hama3254** [comment]
versuch den Browser auf zu machen nachdem die Meldung kommt und schau ganz unten einfach welche Fahne da ist.
ich kann auch mit Windows 7 ohne Firefox problemlos downloaden.
(auch wenn es noch einen bug gibt in der auflösungs anzeige :O )
https://abload.de/img/testsf1jjd.png

**Comment by KoroFX** [comment]
Vielleicht versteh ich das mit den cookie auch komplett falsch und das ist n komplett anderer fehler.
Versuch du mal diesen anime mit englischen Hardsub runterzuladen (Ich hab 1080p ausgewählt)
http://www.crunchyroll.com/btooom

**Comment by KoroFX** [comment]
Jetzt komme ich nichtmehrmalmehr soweit den Cookie zu setzen :/
Dieser Java Code kommt und dann lädt der cookie auch nicht:
![image](https://user-images.githubusercontent.com/46395233/71647668-a29f0c80-2cfa-11ea-945e-37ead7827624.png)
![image](https://user-images.githubusercontent.com/46395233/71647676-b8143680-2cfa-11ea-965b-3b1af2828071.png)
![image](https://user-images.githubusercontent.com/46395233/71647678-bba7bd80-2cfa-11ea-8d71-e4a9e4c850be.png)
![image](https://user-images.githubusercontent.com/46395233/71647680-be0a1780-2cfa-11ea-90bf-6d28e095c020.png)
-
Btw die Flagge war nachdem der Cookie gesetzt wurde immer der US Cookie, nachdem die Fehlermeldung kam weiß ich leider nicht, das wollte ich gerade probieren komme aber nichtmehr soweit.

**Comment by hama3254** [comment]
> ## Jetzt komme ich nichtmehrmalmehr soweit den Cookie zu setzen :/
> Dieser Java Code kommt und dann lädt der cookie auch nicht:
> ![image](https://user-images.githubusercontent.com/46395233/71647668-a29f0c80-2cfa-11ea-945e-37ead7827624.png)
> ![image](https://user-images.githubusercontent.com/46395233/71647676-b8143680-2cfa-11ea-965b-3b1af2828071.png)
> ![image](https://user-images.githubusercontent.com/46395233/71647678-bba7bd80-2cfa-11ea-8d71-e4a9e4c850be.png)
> ![image](https://user-images.githubusercontent.com/46395233/71647680-be0a1780-2cfa-11ea-90bf-6d28e095c020.png)
> Btw die Flagge war nachdem der Cookie gesetzt wurde immer der US Cookie, nachdem die Fehlermeldung kam weiß ich leider nicht, das wollte ich gerade probieren komme aber nichtmehr soweit.

das es teilweise geht und dann wieder nicht liegt an CR und da kann ich nicht viel machen.
ist halt ein buga use welcher nicht immer klappt.

ich habe auch gerade 3x versuchen müssen bis es geklappt hat.
aber btooom funktioniert bei mir 
https://www.youtube.com/watch?v=Fs9TOQvpP_A
.
.
btw Btooom sollte man eh den manga lesen der Anime ist vlt die hälfte davon.

**Comment by KoroFX** [comment]
Ich benutze mal deine neue Version und wenn der nochmal den error ballert guck ich nach ob die Flagge noch US Anzeigt.

**Comment by KoroFX** [comment]
https://myanimelist.net/animelist/Koro-Nut
https://myanimelist.net/mangalist/Koro-Nut

**Comment by KoroFX** [comment]
Ich bin nen Neuer Weeb und solange es nen Anime gibt, werde ich den Anime gegenüber den Manga bevorzugen

**Comment by KoroFX** [comment]
Ich habe gerade nen komplett anderen fehler bekommen als es die 4te folge herunterladen wollte aber jetzt geht es. 
![image](https://user-images.githubusercontent.com/46395233/71648087-fcee9c00-2cff-11ea-9dfc-c75ae2da2a55.png)

**Comment by KoroFX** [comment]
Ich habe continue gedrückt und jetzt lädt es alles runter was es soll....

**Comment by KoroFX** [comment]
Jetzt hat es einfach die Download Que abgebrochen .-.
![image](https://user-images.githubusercontent.com/46395233/71648096-290a1d00-2d00-11ea-95e5-fd560415f922.png)

**Comment by KoroFX** [comment]
Es ist aber immernoch der US Key 
![image](https://user-images.githubusercontent.com/46395233/71648103-3fb07400-2d00-11ea-90a8-55e10427c153.png)

**Comment by KoroFX** [comment]
@hama3254

**Comment by KoroFX** [comment]
Ich habe jetzt wieder den Download ab folge 6 gestartet aber nervig währe das schon das es die exeception bekommt und dann die que nicht fortsetzt

**Comment by KoroFX** [comment]
Jetzt hat es folge 7-8 gestartet und die que ist wieder im idle anstatt das nächste video einzuquen das triggert ja mehr als wenn der cookie nicht geht:
![image](https://user-images.githubusercontent.com/46395233/71648250-96b74880-2d02-11ea-8fba-756120b26d47.png)

**Comment by KoroFX** [comment]
Also anstatt das zu behalten und durchzugehen,
![image](https://user-images.githubusercontent.com/46395233/71648273-f31a6800-2d02-11ea-9617-4dbb075ae294.png)
fängt der einfach an zu idlen, ob das mit den Visual Studio Error zusammenhängt ?

**Comment by KoroFX** [comment]
Es hat mir aber auch nur einen Error gegeben wo ich Continue geklickt habe und seit dem fängt der andauernd an zu idlen, ohne weiteren Error Code, ka ob das zusammenhängt oder random ist aber hm .-.

**Comment by hama3254** [comment]
versuch mal das neuste build :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x

**Comment by KoroFX** [comment]
Okay.

**Comment by KoroFX** [comment]
Scheint alles gut zu Funktionieren, kann geschlossen werden.
-
Ich würde sagen das könnteste jetzt so als 4.0 Raushauen, da du einiges verändert hast und da sind keine bugs / errors mehr da sind soweit ich das sehe.
