### ISSUE TITLE
 Firefox was unable to establish a connection to the server at 127.0.0.1.

### ISSUE THREAD

**Issue by Killuad** [hama3254/Crunchyroll-Downloader-v3.0#60]
Hi, i was trying to use the add-on for crunchyroll but i doesn´t works. It shows me this error
![Captura de pantalla (4)](https://user-images.githubusercontent.com/71679711/94583103-ad171400-0242-11eb-8e59-ea0359aa68e0.png)
![Captura de pantalla (5)](https://user-images.githubusercontent.com/71679711/94583107-af796e00-0242-11eb-97ec-34974773c324.png)

I've tried to use the add-on before but i always get this error, I'm from Mexico btw

**Comment by hama3254** [comment]
the add-on access the http server of the downloader, it need to be turned on to work and you need v3.4.5 for the add-on version 0.2
![grafik](https://user-images.githubusercontent.com/52826614/94584124-8545a180-027e-11eb-825a-8dd3315986fe.png)

**Comment by Killuad** [comment]
Sorry i don´t know anything about this :(. I enabled the http server and the opcion "use Firefox Profil Folder" but i'm wondering, what is that opcion for?

**Comment by hama3254** [comment]
`"Use Firefox Profil Folder"` was desingt to import automaticity the cookies from Firefox, this does not longer work due to changes on Firefox and it will be removed with the next major update.
the http server is all you need.
