### ISSUE TITLE
Press the paly button again to retry

### ISSUE THREAD

**Issue by 619beave** [hama3254/Crunchyroll-Downloader-v3.0#600]
When downloading Welcome to Demon School! Iruma-kun Season 3 Episode 08 Can We Make 100 Friends The Students I'm Proud Of

the downloader downloads the Subtitle but getting "Press the paly button again to retry" .

[CR Downloader Error-20221126.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10096472/CR.Downloader.Error-20221126.txt)
<img width="632" alt="CR Downloader Error-20221126" src="https://user-images.githubusercontent.com/41927382/204095146-c316d8f9-a701-40b5-9e0d-5dd2f1180d96.png">

**Comment by hama3254** [comment]
this is a known issue https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/550#discussioncomment-4241819 and a [fixed version is already released](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable)

**Comment by 619beave** [comment]
Thanks, I got it working with the latest version of the portable.
