### ISSUE TITLE
Partial download only

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#602]
I have tried to download the whole [Blue Lock season](https://www.crunchyroll.com/it/series/G4PH0WEKE/bluelock), that has 8 episodes.

I have set the hybrid downloader to 4 max parallel downloads and the last stable portable has downloaded the first 4 only and not the other 4.

Perhaps it's a temporary hiccup or a regional problem but any feedback would be welcome.

**Comment by hama3254** [comment]
The downloader should start a new download until the max count of in your case 4 is reached, this had nothing to do with anything CR releated so if just one of the 4 is finished it should start the 5th one.
if you could add how you did the download (queue or season mode) would help to see if the downloader did just count the running downloads wrong. 
I tried that series and did not see issues personaly.
