### ISSUE TITLE
Exception when adding CR download using version 3.9 WebView

### ISSUE THREAD

**Issue by DJPlaya** [hama3254/Crunchyroll-Downloader-v3.0#603]
**Describe the bug**
Exception when adding a download from CR using the latest portable version (26.11.22) followed by "something is wrong here ...".

**Where does the issue happen?**
 - Platform: [Crunchyroll Beta(meanwhile migrated i think), Cruchyroll Classic, Funimation(untested)?]
 - Settings [Default, same results with with --insecure curl option]
 - Version [v3.9.12 WebView2_Test]
 - Win 11 x64

**Screenshots**
Exception:
![Exception](https://user-images.githubusercontent.com/24898714/204130265-13b9ae47-1ca1-4021-a4ea-3b90f32b40ce.png)

**Additional context**
CR Downloader was freshly installed, running as admin results in the same exception.
A premium account was used.

[EVTX Eventlogs](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10098095/Eventlogs.zip)
[WebView GPU Report](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10098029/Edge.GPU.Report.txt)

**Comment by hama3254** [comment]
please check the `curl.exe` that is supossed to be located inside the `lib` folder, the downloader should include it at the right place but the according the the error it was not to be found.

**Comment by DJPlaya** [comment]
Ah, it seems that my 7Z was set to not reconstruct paths, so the lib files where extracted in the main folder.
TY
