### ISSUE TITLE
Specific episode causes an exeption

### ISSUE THREAD

**Issue by DJPlaya** [hama3254/Crunchyroll-Downloader-v3.0#604]
**Describe the bug**
Don't Hurt Me, My Healer S1 E6 OmU causes an exception in the link grabber.
Happens with the direct url and grabbing from the series page.
>https://www.crunchyroll.com/de/series/G3KHEV3NN/dont-hurt-me-my-healer
>https://www.crunchyroll.com/de/watch/G8WUN4NXE/as-usual-alvin-and-carla-have-to-overcome-a-series-of-crises

If i had to guess, i would say it may be related to the hilarious long episode title. For downloading the other EPs, i turned off episode names in the settings because they where too long in file length, even under C:/ .
But i have also tried to set the webpages language from de to en-us, with the same result sadly.

**Where does the issue happen?**
 - Platform: [Crunchyroll Beta, Cruchyroll Classic]
 - Settings [Default]
 - Version [3.9.12 WebView2_test]

**Additional context**
Stacktrace multi-link Grabber:
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei Crunchyroll_Downloader.Anime_Add.LoadBrowser(String Url) in D:\Projecte\experimental-Crunchyroll-Downloader-v3.x\Crunchyroll Downloader\Anime_Add.vb:Zeile 27.
   bei Crunchyroll_Downloader.Anime_Add.Timer2_Tick(Object sender, EventArgs e) in D:\Projecte\experimental-Crunchyroll-Downloader-v3.x\Crunchyroll Downloader\Anime_Add.vb:Zeile 869.
   bei System.Windows.Forms.Timer.OnTick(EventArgs e)
   bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Stacktrace single link:
![image](https://user-images.githubusercontent.com/24898714/204160540-555c202d-a1c6-40a4-91be-48f82c990047.png)

**Comment by hama3254** [comment]
the `series` inside the url `a-series-of-crises` leads to a wrong code path which is made for series urls.
until i release a fixed version you can shorten the url like so `https://www.crunchyroll.com/de/watch/G8WUN4NXE/`
