### ISSUE TITLE
specific episode download error (Chainsaw Man 8)

### ISSUE THREAD

**Issue by ET1982** [hama3254/Crunchyroll-Downloader-v3.0#606]
Hi, there's no way to download the latest episode of Chainsaw Man, while I have no problems with any other episodes of that series or other series. 

I tried with U9 version and also the 3.9_4 portable version

Attached log and screenshot:

![1](https://user-images.githubusercontent.com/108487686/204725461-46793cfb-3727-4b59-87e7-972a4d9e3569.png)
[log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10120295/log.txt)

**Comment by hama3254** [comment]
The latest (and for now only) release of the [Portable Version ](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Portable) has a fix for this issue.
