### ISSUE TITLE
Getting a 403 errror

### ISSUE THREAD

**Issue by cimmy01** [hama3254/Crunchyroll-Downloader-v3.0#608]
This started this afternoon every download I've tried after 3:00 PM EST has returned with an error Curl-e curl (22) the requested URl returned error : 403
Im using V10 
Here is a screen shot and the log file.
![Screenshot 2022-12-04 153339](https://user-images.githubusercontent.com/56510595/205514147-6e56d753-12ff-4c01-9acf-b436314b54ca.png)

<details>
  <summary>Log</summary>

  ```
Thread Name: Main
Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
NavigationCompleted: 12/4/2022 3:28:46 PM
12/4/2022 3:28:46 PM.572
https://www.crunchyroll.com/
Just Browsing, exiting...
Start loading: 12/4/2022 3:29:32 PM
8
CurlPost-E: curl: (22) The requested URL returned error: 400

CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6Ik4yN0ZHTDlyN0FZUnZweFJkUkVpd3ciLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJjbGllbnRfaWQiOiJjcl9iYWNrZW5kIiwiY2xpZW50X3RhZyI6IjEuMC4wIGJldGEiLCJjb3VudHJ5IjoiVVMiLCJleHAiOjE2NzAxODkzNzQsImp0aSI6ImYyYjFkMjRiLTllMjUtNGI0NC04MGIwLWM5OTEyZTg3NGE4NSIsIm1hdHVyaXR5IjoiTTIiLCJvYXV0aF9zY29wZXMiOiJhY2NvdW50IGNvbnRlbnQgb2ZmbGluZV9hY2Nlc3MiLCJzdGF0dXMiOiJBTk9OWU1PVVMiLCJ0bnQiOiJjciJ9.g1o9l6bp_uw84fGasMhLCjjhjJLWIGp4-0--YWBeFe7WZxNk30TAKtu5PWUyBtPliR_V9itVHM6wgqQgjP94DD0qSUIrd542NfXCUbZUsyQxabBxG0Y1kPyD5-jcIuQXSJLEXMSYscSfwQiLHtqHfk4xeCFDEUNM530yaKXBMLqo1C6rwZOuQCZmIXPFaKfyLvKozLMMyjyH6U9pzrRea3O6PJIh37f06PWJ1AU6HqMTDiy6Ddwb_x5YG2mGk2vBuyd0YUt-ysvxX8j2mlJsnK_sfZqfjmIbm3ZhfNSSGQq4hxZnIAYQw26fp4UGOJbPh1mSB_fIhC4VhUDetKqh9Q","expires_in":3600,"token_type":"Bearer","scope":"account content offline_access","country":"US"}
CurlAuth-O: {"cms":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00yLy0vKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY3MDI3MjE3NX19fV19","signature":"LZj9eAjp10-VJOCOXb30CUw8w1pXgPA8PLkkk~L1Q7DCBqGZCgQhVe8ZSlzFYZOaFwEgxDAEJFp3dgzBtCfSK2Iyet8Xpyi0MHScE2xMvG-0Eo7D4Ppx8n2jzyVvm0ZNCmjOfnyawv8JsAxEL0afCfwDDmVtW4BDcEGVhoo3uSksmMFDWgF47AzMUzL48X~eSKYzWQTZ4YT7Jljt7n1Dc7zMwIY6IOklWJIoh2Q5l48ZdUEbGFf4psPERgfU8EIzJ3HgphZZXABYgDXtb86~KsyBhIpfHY3kB8pBeAB2THrmHPvpQZqkTfsK4UEHFfcnkRHV-tlx2Wavg2yBmHfaBA__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:29:35Z"},"cms_beta":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLmNydW5jaHlyb2xsLmNvbS9jbXMvdj8vVVMvTTIvLS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjcwMjcyMTc1fX19XX0_","signature":"E~KfcSUBHFSY6MfnXPiyOVi7l9Zqp~bRy~Nx1qRLUPXJ3nMtQQ7qlCznpGaeaZ0j9OSLDbaIxcyvrEc3YGMrX3A0bPt8Ykvh8-ahTdi1v9t2V8cbqN1Cm91IOuDRr2jLqyUGDPDEdL6cVsb3XBF~JhkcyMm8cl14vnDyJ23VsIlHvA3bD5RyTxDGahTOgiCKE1F0LtHuITo6o2eeYw~tkxRA8jQykU5VDenGL~VT9HPzKwnG-RWbN-jZF7L3dZgPN6S748QRGDrRrPC6kwG5vvr1SDmZ4Rs~bxQTeK~-70H-ke6nyEttbbHuMo5si4BJ3CysOjiLrC7CnVild5oSSQ__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:29:35Z"},"cms_web":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi8tLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzAyNzIxNzV9fX1dfQ__","signature":"bQ3KXvEl5Kwmoz2KVXZQdfVYJ-J7dDjrb5OKrKtOwrwrxkUT55jacIHoDt2~nvYmwODcuT0dpK-rwssIN6p5S4lD-P54XanMvtmjhUXZ8d8tJeOttO9pBscl1mli~p-~3dCFMrQrPPrItkXgKFuwbMacTkq33WjiIkqjVZ0UwCj2HFpJV90lOpfDDt0VoScfd-Q9hnmChhpWrv4uEREjYy4J~HMKo1zR5GXBY3jZeOgF4amyz55KnjlwCcKVhqdFlmq00Dl~zBfBZRhccrBpk6J7AsbF4iGh-jpBFzRKG6Vn~oPYeaPgToXfh-kE6EsU4uCTqS89iTIBO9iD6MLmvw__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:29:35Z"},"service_available":true,"default_marketing_opt_in":true}
curl-E: curl: (22) The requested URL returned error: 403

Start loading: 12/4/2022 3:30:28 PM
8
CurlPost-E: curl: (22) The requested URL returned error: 400

CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6Ik4yN0ZHTDlyN0FZUnZweFJkUkVpd3ciLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJjbGllbnRfaWQiOiJjcl9iYWNrZW5kIiwiY2xpZW50X3RhZyI6IjEuMC4wIGJldGEiLCJjb3VudHJ5IjoiVVMiLCJleHAiOjE2NzAxODk0MzAsImp0aSI6IjZlNjU0YTQ5LWNhZGEtNGFkZi05N2E1LWViYzBiZmZjOTFmMiIsIm1hdHVyaXR5IjoiTTIiLCJvYXV0aF9zY29wZXMiOiJhY2NvdW50IGNvbnRlbnQgb2ZmbGluZV9hY2Nlc3MiLCJzdGF0dXMiOiJBTk9OWU1PVVMiLCJ0bnQiOiJjciJ9.ACndOk7Iroh6svx3R-ylAFFsgUXFjUd3rYT0_j3-4i5FJe_INiizcKRfDpC_0NACTMKkDTOGChZqZ8ZNTm76OBRzCgczMNQFkI_0Zj2_JQo73sBsZm0VmRh2dEpSf-mQMaJpYAObtQqtduFNXDCM46LLOfKPMYuerktdqj4O_epxrfaO4mqplRP06o2gGkr-ER3lBY-fWAk5NbBj92Ta8WicK4dJSiYa8jbIHFA13AoSsh2KLesJJnTptJsAr8RKNSdF4JgaIooaM9ABPAlJuvwXhQkX4OziWgW8LYEd424dux50pJTruaRwDlJgQTMd7njTYAqPfk_lOw1IpM0H-Q","expires_in":3600,"token_type":"Bearer","scope":"account content offline_access","country":"US"}
CurlAuth-O: {"cms":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00yLy0vKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY3MDI3MjIzMX19fV19","signature":"RQ0EmPMrtMmZNXCQfN9B0O7RVQGT3QL3wY6euRpiBLZSCJ-P4uOaUve0uoJnEVW95LCqWwrdhZEz9Zi4qRlnFL74Pz40pSVuyvbFZIEpSkjzDoMM2Vs3PKwO4WiVD2gcJEnrxt6GJsm6Rth-28J4UNhc3VcMNziy~BGcqG3MDk8w4oEL2KVpQdAm7hqtzAKtfi4XWN7MHAgAY5ApW64FM-eG~gGqciB4C-do4D7OmHwnvPqG5m7Hzxm6F-fdXDlpk5vR~uCGhLt3cQrsF5~AUCiM3CLDelzPkamI-3Rc4EPPJwD0ClLc0IUcRFFyx8y8g3lt8kMJ8zc4mKPfMcnJ2g__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:30:31Z"},"cms_beta":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLmNydW5jaHlyb2xsLmNvbS9jbXMvdj8vVVMvTTIvLS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjcwMjcyMjMxfX19XX0_","signature":"rx61oWqEoiD~GxXVlBAsoYQ3QnZTQq9TKJG2f8sJNvryfmQF~0ek7ou5OrbWxSzlH6Q7mBr8DukGdkJCshY7TFTbxS7leCyQvJtAl1SWFlIos9~7vLX7AgOBRBqNCvh2y5yNQTjl1bMbQl5IazCh8zqRrl-EVxFRT3AxYWQR44oS~HUnbXLNVcICopquLxmDiqQh1HNDONbU05S410VDX8v1mkO9yjzc3OgyFhRWksrJVW~yASHSkVJm0i6FobtdsA7zOjYvQuVXTDcGkxOP7Z9PjzZSIKoM5xCo2bRMwTxkcbRwtKXZr0QQvqkGHeBT9be7409P71wGBeT7myh6RA__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:30:31Z"},"cms_web":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi8tLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzAyNzIyMzF9fX1dfQ__","signature":"mD090NdZfOtOCFfDXuOKCGXPmHxn46H9QRyqLcGF0i6zbkuukBiGFiqKWv--Yu6m-rvmUxvvTC7Jq0~QeLK4JW4uK1rVXMtMwS~vIDbu096PA1BKXTvTeBglay7lPGd~q-ZNralEro09YKfawliyBFZlAT~jMvY-mqQQ~af2uwxgv81ru9SbZEv92skG~FQ8Mwy0MqSw~TYPBtTPODKOwtNH~F5fk8ZuTx8mLDG1~DwkOmonrzMz0rvCeZRV9tO3EmjmRX6b~E8K3-ZiPBCv879meKFbSCq1EYIfhF9rDtHbViJhDsE4X4JJuMlIV1uG2uoActW8FBEOvAEcEiTslg__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:30:31Z"},"service_available":true,"default_marketing_opt_in":true}
curl-E: curl: (22) The requested URL returned error: 403

Start loading: 12/4/2022 3:33:11 PM
8
CurlPost-E: curl: (22) The requested URL returned error: 400

CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6Ik4yN0ZHTDlyN0FZUnZweFJkUkVpd3ciLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJjbGllbnRfaWQiOiJjcl9iYWNrZW5kIiwiY2xpZW50X3RhZyI6IjEuMC4wIGJldGEiLCJjb3VudHJ5IjoiVVMiLCJleHAiOjE2NzAxODk1OTMsImp0aSI6Ijk2ZGY1NTBhLTIzOTItNDI1YS05NTg4LWVjOTQwYjcyZTcyNyIsIm1hdHVyaXR5IjoiTTIiLCJvYXV0aF9zY29wZXMiOiJhY2NvdW50IGNvbnRlbnQgb2ZmbGluZV9hY2Nlc3MiLCJzdGF0dXMiOiJBTk9OWU1PVVMiLCJ0bnQiOiJjciJ9.PwHN9dDXWBVCud78UT9-hQSOfAZzoIN1sftFvKYhEeaefkkVV4gif5SXJFbrdoprt9iGh9DmAcYB-JXG1xQVkkbeGhLCC7Ty02Kb-LKqSBkOsHH6O4Gk2S4xxrLai7ro56_oflP4PX8epOZ_UwDx5zeB9jJXkylHt4kSaWX7hSBsIhPt_5T05sIDTAoGcYJqjgrVe2REdygkaJ5hrOBp43pwGVU9ASyW6ad405D0KJ2Jzq2mSk6h6KlE_laignibYYDOlHicOyElwhFLsFJy7eAF_HX-h--Ukep3b0PRhICtenzaSx2PMpUGMqaiFcqJifw8Gm8_DF8F-d62E4k7qQ","expires_in":3600,"token_type":"Bearer","scope":"account content offline_access","country":"US"}
CurlAuth-O: {"cms":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L1VTL00yLy0vKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY3MDI3MjM5M319fV19","signature":"T5yw~4pFAXS9qWDsWF0mOoXFp7l-2E4Nn4APt9IUP2GhymluuKQqT90mLDTkC2H8aZgGn7brj1CfDW3kQviOq5S91ZDxWdXdqEWF3HALlnmJM2EXzFdJmcfM-fLMHhIWN5uop0~~pIunfQLW4gJDAstjRX-z~JZCwbho-rzEdQRGbQmcln1oa5icFFPHVIa3SJ3tkhmoYX~VtQZlVJH5CZZvNR32CnsakxvjKM4KRJtAyVPRigN3A9o5LoSoK3iM-K2Do~oj6BK96ZKbYm1cq-54267Kms3NVwJZmdVjrpH8~FvhLhzseGfwjfezR04fRzALcDn69EoLtGRP7w6OJQ__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:33:13Z"},"cms_beta":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLmNydW5jaHlyb2xsLmNvbS9jbXMvdj8vVVMvTTIvLS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjcwMjcyMzkzfX19XX0_","signature":"A-eUs8r~Nf6TKmEFfGCIqHKdtO0yxRbh81bMSnUUZoqLbO-7heqTuGJFs8Fqq8p4drhAdYYiXU8rYUiu1Jv5xLdTHh6AwisgVBrcTVF54PYgYMtraqLXuBRnh5fDAo0AdsH6u46xDxufefg~9dG-GfkKe2KtCZ8XQrNaj1-ggiqdN~SoHH5VWPPmKos7ktxMQ~97t4H1Vn1sS3-248dwi1c61DFiLssO3VKliiTyR4-6dMYZsoOTOk~WJTEQReZP9UvXboCxWYm1MVVAwLFplT-1V2o9sqjZReiQXKZBi42Cqpq61TvLX4SfvbGIwrgprymI0KhR4YEK2aZB6RQTxQ__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:33:13Z"},"cms_web":{"bucket":"/US/M2/-","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9VUy9NMi8tLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzAyNzIzOTN9fX1dfQ__","signature":"RhaBe0hH8Z6dsfI1XYpq7KWXvkUGnX5UXsayVFJEdpD5D-32ILGk5XRfm-BynNBXLS5YJQpdRwcOIyAIr3u7YDmb16bu-9zdzMW1LN68iykCfc38zjQLQK6FxXJfLBj2j5ZAqePQgvfNqYWSlRpvm6OCG4lItIADb2YiTX6qvUaqjRLr54Vv8z6L1Pzk1ZRtrYwOH-Lo4xHuyTBjSTI~GvIK1HLEPgDoUII2ySD04Mu~eQhtTIhM3tznvXoq4KDNtfnt6fvGIsjeR~nu5LoCJKwpDJnQZllT~ljx6FoAy34a9-iSz12anBbftynURfF01LyWANYparZsgIt-7ra2zA__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-05T20:33:13Z"},"service_available":true,"default_marketing_opt_in":true}
curl-E: curl: (22) The requested URL returned error: 403

  ```
  
</details>

**Comment by hama3254** [comment]
it is still unkown where the `403` error comes from, i don't have this issue for myself and with the way the request works it should error out at the first or second request (the post or auth request) since they give the `policy`, `signature `and `key_pair_id`.

>This started this afternoon

Did the same version work for you before that time and did you change something (VPN, Proxy)?

How do both your Webbrowser and the build-in webbrowser behave do they load the episodes, title and video or are the not working as well?

**Comment by cimmy01** [comment]
It did work earlier this morning the last show I downloaded was Rwby at 11:30 am EST. When I open the browser both internal and external ,Chrome, it loads the page and will even play an episode no issues. I have been seeing a lot of errors 404 errors from crunchy but the page is working for the most part. I am not running a vpn nor have I made any changes to my internet settings.

**Comment by deadlynjdj** [comment]
I have the same issue

https://static.crunchyroll.com/skip-events/production/G31UXGVP3.json
https://static.crunchyroll.com/datalab-intro-v2/G31UXGVP3.json

are the only urls that where giving 403 and the datalab-intro-v2 is the only one being called. 
I have chapiters off but i have subtitles on it seems like a crunchyroll issue

**Comment by Tobolobo** [comment]
I've got the same error. It started around 9PM GMT+1 from one episode to the next.
![grafik](https://user-images.githubusercontent.com/89733815/205524010-0a9a04f8-0f8e-4659-9abd-2d5a8aad606e.png)
For some reason, sometimes when i click download it reloads the page and it asks me to get Premium even though I have a Mega Fan Subscription. After reloading the page, it shows my membership normally again. Maybe that could be a hint?

I've got a week off now, maybe I can have a look at it tomorrow too.

Kind regards & schöne Grüße!

**Comment by hama3254** [comment]
From the amount of new error reports within a short time frame would i asume CR (or cloudflare) changed something.
I need to look at what's going on exactly after I get home from work.
If you want to download something you can use the old [Crunchyroll-Downloader-v3.9_Indev](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) that could still work since it was before the `curl` method was added.
But please remember the description of that version: `A somewhat working release.`

**Comment by ManuelDiazIsaza** [comment]
I cant download even with the [Crunchyroll-Downloader-v3.9_Indev](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev) 

Thanks for your effort

**Comment by Azzuray** [comment]
> I cant download even with the [Crunchyroll-Downloader-v3.9_Indev](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.9-Indev)
> 
> Thanks for your effort

What version did you try the U9 ?

**Comment by ManuelDiazIsaza** [comment]
Was my bad, i wasnt login on CR..

Now is working fine

**Comment by hama3254** [comment]
This issue was either temporary or just for some locations since i can not replicate it.
However i added [Crunchyroll-Downloader-v3.10.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.10) which includes a new type of fallback for the `ObjectJson` and `VideoJson` which are required for a single download, `SeasonJson` for series download is not included with this fallback.

**Comment by Azzuray** [comment]
Ok so Season DL return errors : 

![image](https://user-images.githubusercontent.com/76765834/205704224-3881b3d6-ab1c-4144-b623-ef877816f50c.png)

`
15
CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6InNvUWk5UV96UG5PNk9xbkUyLU1YdEEiLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJiZW5lZml0cyI6WyJjYXRhbG9nIiWtJdA3kg7mA","refresh_token":"65f8bfa0-95fb-43c0-9148-57752ac863ad","expires_in":300,"token_type":"Bearer","scope":"account content offline_access reviews talkbox","country":"FR","account_id":"688b3110-b1a1-53ea-b746-3c72b26893e6"}
CurlAuth-O: {"cms":{"bucket":"/FR/M3/crunchyroll","policy":"eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9iZXRhLWFwaS5jcnVuY2h5cm9sbC5jb20vY21zL3Y~L0ZSL00zL2NydW5jaHlyb2xsLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzAzNDgwOTl9fX1dfQ__","signature":"hb5ifzbO5fkMMMyhFi43agdkl2ukw__","key_pair_id":"APKAJMWSQ5S7ZB3MF5VA","expires":"2022-12-06T17:34:59Z"},"service_available":true,"default_marketing_opt_in":false}
curl-E: curl: (22) The requested URL returned error: 403
`

But not issue on Single Episode download so probably smth with the .json season

**Comment by hama3254** [comment]
>Ok so Season DL return errors :

>But not issue on Single Episode download so probably smth with the .json season

this is to be exptected, the current fallback uses cached data to replace the nor working requests before they throw the error.
For the season download i don't have enough data since each season has it's own data.

**Comment by hama3254** [comment]
a workaround for the missing season download could be the [add-on](https://github.com/hama3254/CRD-add-on) currently only for chrome and it needs to be install manual: [Chrome add on installation](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-installation)

**Comment by cimmy01** [comment]
I got home todaay and tried the new 3.10.1 version and it seems to be working just fine Ive down loaded a couple of episodes and its working fast and with out any issues. Thanks for the hard work!

**Comment by Saam97** [comment]
Hello, the latest version 3.10.1, it works perfect, thanks.

**Comment by Ravn73** [comment]
> This issue was either temporary or just for some locations since i can not replicate it. However i added [Crunchyroll-Downloader-v3.10.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.10) which includes a new type of fallback for the `ObjectJson` and `VideoJson` which are required for a single download, `SeasonJson` for series download is not included with this fallback.

Thanks for the fast workaround! It works fine =)

**Comment by Azzuray** [comment]
Alright, it seems the issue that was present yesterday is gone today, no more Error even on older versions , so it was probably an issue on CR's end 

For anyway for the work !

**Comment by ManuelDiazIsaza** [comment]
Hi @hama3254 today im getting the same error

![image](https://user-images.githubusercontent.com/37357573/207450394-e2cce0a2-7ac1-45c9-aeb0-2391ab60bce5.png)

Im using the 3.10.1 version

**Comment by hama3254** [comment]
@ManuelDiazIsaza I still can not fix the error since it is the behavior of CR or cloudflare.
There are workarounds for single episodes if the browser can get access to the resources.
It is known that the Seasons DL is not working with this workaround.

>>Ok so Season DL return errors :
>
>>But not issue on Single Episode download so probably smth with the .json season
>
>this is to be exptected, the current fallback uses cached data to replace the nor working requests before they throw the error.
For the season download i don't have enough data since each season has it's own data.

But the add-on helps with this issue.

> a workaround for the missing season download could be the [add-on](https://github.com/hama3254/CRD-add-on) currently only for chrome and it needs to be install manual: [Chrome add on installation](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-installation)

**Comment by Lynacchi** [comment]
I got the same error as @ManuelDiazIsaza since today. Made it work over the browser in CDL, but while downloading I got this error.

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Crunchyroll_Downloader.Browser.VB$StateMachine_31_GetCookies.MoveNext() in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0 - CefSharp\Crunchyroll Downloader\Browser.vb:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
