### ISSUE TITLE
Error with WebView

### ISSUE THREAD

**Issue by Mayansito** [hama3254/Crunchyroll-Downloader-v3.0#609]
![b319f403405e653ea20089a1badeee35](https://user-images.githubusercontent.com/98242308/205514841-033cc947-ac1a-472b-ab09-6c39da50bdda.png)

**Comment by hama3254** [comment]
if google traslate is right then the error would be `cannot read or write to data directory:` which maybe either have no permission to write/read files from the folder.

**Comment by Mayansito** [comment]
How can I give permission?

**Comment by hama3254** [comment]
Moving the downloader to an other path would be best option.
You can use the Windows Documents folder.

**Comment by Mayansito** [comment]
Okey, now there is not url.

![Sin título](https://user-images.githubusercontent.com/98242308/205516021-dd282aa8-9b04-4551-825c-d835d274091c.png)

**Comment by Mayansito** [comment]
I only have this problem with 3.10

**Comment by hama3254** [comment]
>You may also require the [WebView2 Runtime from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) and to login into Crunchyroll with the build-in webbrowser.

_Originally posted by @hama3254 in [release-v3.10](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.10)_

**Comment by Mayansito** [comment]
I have WebView2 installed.

**Comment by hama3254** [comment]
That usually the issue.
I have to look tomorrow what that could be, it's already late for me.

**Comment by hama3254** [comment]
The downloader should include all files required to run it exept the runtime.
The only other thing i can imagine that might be wrong would be the runtime version, the downloader is build as `x64` application and the runtime should match that.

**Comment by Mayansito** [comment]
I have x64 version. Anyway, i'm using 3.9. That works for me.

**Comment by hama3254** [comment]
the older version has a different webbrowser build-in, there won't be any new build with that webbrowser so for the future so the issue will return.
