### ISSUE TITLE
Add proxy functionality 

### ISSUE THREAD

**Issue by Abu3safeer** [hama3254/Crunchyroll-Downloader-v3.0#61]
Hello,

is it possible to add proxy support?

**Comment by hama3254** [comment]
You can use the "US unlock" in the settings to get access to the US content from crunchyroll.
A real Proxy support is not possible, but you can just use a VPN with the downloader.

**Comment by Abu3safeer** [comment]
Actually I use a server, this server is blocked from Crunchjyroll, and if I use a VPN, the server will disconnect since the ip is changed. 

Do you have any information about why implementing proxy support is not possible?

**Comment by hama3254** [comment]
> Actually I use a server, this server is blocked from Crunchjyroll, and if I use a VPN, the server will disconnect since the ip is changed.

I don't support Server anyway since this entire project is made to just make private copys as [allowed by the German law](https://www.gesetze-im-internet.de/urhg/__53.html) you can use the Downloader local with VPN without any known issues.

**Comment by Abu3safeer** [comment]
I thought Visual Basic does not allow Proxy, May I ask you what do you use to connect? I might try to impalement proxy feature if possible.

**Comment by hama3254** [comment]
you might get away with just a proxy in the webbrowser. 
you can change the `about:config` like in a normal Firefox :
![grafik](https://user-images.githubusercontent.com/52826614/94722121-2142dc00-0357-11eb-98cc-238b5efc23c0.png)

but i don't know it the stream server also block your Server so you can just try yourself

**Comment by Abu3safeer** [comment]
I see, so this app is actually using Geckofx to fetch the content?

**Comment by hama3254** [comment]
> I see, so this app is actually using Geckofx to fetch the content?

i just need to access the crunchyroll website, without a valid browser i just get http error 403. 
the m3u8 video playlists can be accessed by the .net webclient for the most part

**Comment by Abu3safeer** [comment]
The CDN part (m3u8 and subtitles) is not blocked, only the main domain is blocked. 
![image](https://user-images.githubusercontent.com/12091003/94724158-851ed200-0362-11eb-8287-4d44db24156a.png)

**Comment by Abu3safeer** [comment]
Unfortunately ``about:config`` is not editable.

**Comment by Abu3safeer** [comment]
Thank you for your time, sorry for the inconvenience

**Comment by hama3254** [comment]
> Unfortunately `about:config` is not editable.

that unfortunate but you still can download the project and hardcode the settings for the startup like i did:
![grafik](https://user-images.githubusercontent.com/52826614/94725316-d7a8c000-035b-11eb-83c6-27d7323c8b23.png)

**Comment by Abu3safeer** [comment]
Thank you.

If you are not planning to support proxy, close this issue.
