### ISSUE TITLE
How can I install this in Ubuntu

### ISSUE THREAD

**Issue by dkb007** [hama3254/Crunchyroll-Downloader-v3.0#62]
Can someone tell me how can I install this linux/ Ubuntu system? with the same GUI

**Comment by hama3254** [comment]
I used PlayOnLinux to install it on my ubuntu PC : https://www.youtube.com/watch?v=GB-lL3Hn8rQ
but i don't get the Windows build to run without changing some details, so i uploaded the linux debug version from the video ago : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Debug
