### ISSUE TITLE
--API changed--Use v3.11--

### ISSUE THREAD

**Issue by Agr882** [hama3254/Crunchyroll-Downloader-v3.0#623]
Started suddenly getting this error yesterday when i want to download an episode it says "subtitle language not found select another one below" when i do so it gives me another error as can be seen in the screenshots, this seems to happen with random episodes and no matter how many times i retry or restart it wont work

![crdl1](https://user-images.githubusercontent.com/120562301/207569088-b2b8aacf-1cc3-4834-853f-137e85634989.png)

![crdl2](https://user-images.githubusercontent.com/120562301/207569106-e703a140-54f1-453b-abe4-0b527c294806.png)

**Comment by hama3254** [comment]
The data CR served have not been processed right, to verify this i need the url of the anime.

**Comment by hama3254** [comment]
crunchyroll changes there API so the downloader can currently not process the ne style (left).
The direct API requests seem to work fine for now but every fallback is not working anymore.
![grafik](https://user-images.githubusercontent.com/52826614/207648910-2625f893-e85e-4ebf-bf59-f5ee06f8e984.png)

**Comment by hama3254** [comment]
[Crunchyroll-Downloader-v3.11](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11) should work now with the changed api.

**Comment by AlexyFoxy** [comment]
Hi,
I am sorry to bother you.
But could you please apply this fix on the Browserless version?
Best regards.

**Comment by hama3254** [comment]
@AlexyFoxy probably not, i currently don't have the time to maintain two projects.
I could try to merge the versions and use the cookies.txt if available this however will not happen this year since I won't be home for Christmas so i won't be doing anything at the downloader at all.

**Comment by AlexyFoxy** [comment]
Alright. Thank you for your effort and your reply. Happy holidays in advance and have a good time.

**Comment by hama3254** [comment]
@AlexyFoxy if you don't mind playing lab rat i did just throw the code for getting the cookies from the txt inside the [Crunchyroll-Downloader-v3.11.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11) release.
I expect it to brake easaly since it is really botched so i would not advice to run morem than one download at a time.

**Comment by scopion1745** [comment]
Cheers,

i'm currently using the 3.11 and the issue still persist.
Can i provide you any logs or debugging information?

i noticed that it also often skipps the episode where the error occurs.

**Comment by hunk78** [comment]
another new error 
Error - Getting SeasonJson data
"curl: (22) The requested URL returned error: 403"

**Comment by hama3254** [comment]
@hunk78 the 403 error in known and i try my best to combat it but there limits to what i can do from the request side of the server refuses the request.
