### ISSUE TITLE
helpme

### ISSUE THREAD

**Issue by joeldark2015** [hama3254/Crunchyroll-Downloader-v3.0#624]
help me dear friend hamma, i always follow you since you started this project but i'm having problems send photo of the problem tell me what to do or what to install

Crunchyroll-Downloader-v3.10.1

![image](https://user-images.githubusercontent.com/69058182/207732825-6949f414-8331-4c1c-bbbe-95a3b2c4777c.png)

**Comment by joeldark2015** [comment]
![image](https://user-images.githubusercontent.com/69058182/207735664-9c233744-8b82-407e-8c6b-1d879a32d4db.png)

**Comment by ManuelDiazIsaza** [comment]
I have the same error.... i try download for example 5 episodes, the first one download fine, in the second one i got this error, but when i close the window with the error the third video download fine, the fourth video got this error and so on...

![image](https://user-images.githubusercontent.com/37357573/207764719-3712bb76-c311-4b2b-9e74-13693cdf599e.png)

Like i said, one video download fine, the second not download, the third one download fine

**Comment by joeldark2015** [comment]
mine does not download the video, it stays processing

![image](https://user-images.githubusercontent.com/69058182/207767840-d0eab30e-1ef3-4fa3-b1d3-2db20e9170e7.png)

**Comment by hama3254** [comment]
The issues and answers are still the same as the two open ones.
The first one is already explained in #623 which also includes that the workarounds for #608 don't work any more because of that.
The 403 error is also still not fixable since it's server side and i for example never got it.

**Comment by ManuelDiazIsaza** [comment]
@hama3254 you already try download more than 2 episodes one by one?.... i only got the error when i try more than 1 episode one by one

**Comment by hama3254** [comment]
My time is currently very limited, if i download then it's two episodes due to the `nvenc` limit (from our Nvidia overloards).
I did not notice the behavior you have but i take a closer look as soon as I can.

**Comment by hama3254** [comment]
[Crunchyroll-Downloader-v3.11](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11) is available i need more data how the new api reacts to the downloader.
