### ISSUE TITLE
subtitle language not found while downloading

### ISSUE THREAD

**Issue by YFTX2015** [hama3254/Crunchyroll-Downloader-v3.0#629]
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/208306530-5e2d3836-d0e2-43fc-a683-45275b7a5260.png)
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/208282872-1d8c6742-ff4f-432d-b2ed-f0c51343c91e.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/208282874-91ce43b6-d667-4b93-99f7-2c2ebd24ae44.png)
![屏幕截图(4)](https://user-images.githubusercontent.com/12757305/208282875-11196cf4-3143-45d5-8ea3-4a817dfab96e.png)
**Describe the bug**

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll Beta, Cruchyroll Classic, Funimation]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.8.7.2]

**Screenshots**

**Additional context**

**Comment by YFTX2015** [comment]
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/208306500-37aac276-04a3-45db-a0bd-ed2a8eb7c08a.png)

**Comment by ET1982** [comment]
It happens to mee too, sometimes. In most of cases I resolve the problem by just downloading the same episode with another version (I have 3.10.1, the latest 3.9 and the latest portable versions) but today there's no way to download this:
https://www.crunchyroll.com/it/watch/GEVUZ8M3Q/the-ojamanbo-murder-case

**Comment by hama3254** [comment]
@ET1982 i don't see any major issues for the episode (with Italian VPN) but [Crunchyroll-Downloader-v3.11](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11) is available with the new api as seen in #623.
