### ISSUE TITLE
"language not found" in "Subtitle download"

### ISSUE THREAD

**Issue by Tizioincognit0** [hama3254/Crunchyroll-Downloader-v3.0#63]
Because of the message "language not found" I can't download only subtitles from a video on Crunchyroll. You can see the error message in the screenshot which I attached to this issue. 
![Subtitle download](https://user-images.githubusercontent.com/40031873/95016481-8c402b80-0653-11eb-9883-8c502e38bb79.PNG)
The languages list, shown in the screenshot, is empty.

**Comment by hama3254** [comment]
it seems like the video is just not released yet.
![grafik](https://user-images.githubusercontent.com/52826614/95018616-31adcc00-0661-11eb-80ed-944d72b051e4.png)

**Comment by Tizioincognit0** [comment]
But I can view it on the Italian Crunchyroll website using a browser as you can see in this screenshot (the video is black because of a Crunchyroll protection). 
![Schermata 2020-10-04 alle 17 02 55](https://user-images.githubusercontent.com/40031873/95019144-0aa4c980-0664-11eb-9083-994fc486f7bb.png)
In addition to this, using Crunchyroll Downloader, I can download the video with subtitles but not the subtitles only.

**Comment by hama3254** [comment]
after a quick look it seems like the error message from the top should not even be in there.
this issue has been fixed with https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/64 but with bigger issues in the funimation part the release might take a week.

**Comment by hama3254** [comment]
should be fixed with v3.5.2

**Comment by hama3254** [comment]
without a complaint i guess the fix works so i close this, if there is any new problem just open a new issue
