### ISSUE TITLE
v3.11

### ISSUE THREAD

**Issue by xILikepuddingx** [hama3254/Crunchyroll-Downloader-v3.0#632]
Moinsen

hätte jetzt in dem anderen Channel geschrieben aber der ist anscheinend geschlossen :D 
Mit der neuen Version kommt dieser Fehler:

![alt text](https://i.imgur.com/KQkwdGJ.png)

Kommt wenn man versucht eine komplette Serie runterzuladen

**Comment by x3inspire** [comment]
Same...

![image](https://user-images.githubusercontent.com/4635825/208332558-010584c2-c9cc-453e-a99d-cccab113ac26.png)

**Comment by hama3254** [comment]
Unfortunately this has still not changed.

>I still can not fix the error since it is the behavior of CR or cloudflare.
There are workarounds for single episodes if the browser can get access to the resources.
It is known that the Seasons DL is not working with this workaround.

>>>Ok so Season DL return errors :
>>
>>>But not issue on Single Episode download so probably smth with the .json season
>
>this is to be exptected, the current fallback uses cached data to replace the nor working requests before they throw the error.
For the season download i don't have enough data since each season has it's own data.

>But the add-on helps with this issue.

>> a workaround for the missing season download could be the [add-on](https://github.com/hama3254/CRD-add-on) currently only for chrome and it needs to be install manual: [Chrome add on installation](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-installation)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/608#issuecomment-1351105399_

**Comment by scopion1745** [comment]
Had the same issue.
Seems something related to wha @hama3254  already said.

It's working again.

**Comment by 619beave** [comment]
I've noticed in 3.11 the language is always English Dub, even though the Screenshot is from Japanese Dub.

<img width="1920" alt="Screenshot 2022-12-24 10 13 49" src="https://user-images.githubusercontent.com/41927382/209447281-c53dcb55-9b03-482b-b21d-108790ec0654.png">

**Comment by Ravn73** [comment]
> Unfortunately this has still not changed.
> 
> > I still can not fix the error since it is the behavior of CR or cloudflare.
> > There are workarounds for single episodes if the browser can get access to the resources.
> > It is known that the Seasons DL is not working with this workaround.
> > > > Ok so Season DL return errors :
> > > 
> > > 
> > > > But not issue on Single Episode download so probably smth with the .json season
> > 
> > 
> > this is to be exptected, the current fallback uses cached data to replace the nor working requests before they throw the error.
> > For the season download i don't have enough data since each season has it's own data.
> > But the add-on helps with this issue.
> > > a workaround for the missing season download could be the [add-on](https://github.com/hama3254/CRD-add-on) currently only for chrome and it needs to be install manual: [Chrome add on installation](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-installation)
> 
> _Originally posted by @hama3254 in [#608 (comment)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/608#issuecomment-1351105399)_

I got the Addon installed, but how do i set it up? Which port do i have to put in there, do i have to do a port foward in my router?

**Comment by hama3254** [comment]
> I've noticed in 3.11 the language is always English Dub, even though the Screenshot is from Japanese Dub.
> 
> <img alt="Screenshot 2022-12-24 10 13 49" width="1920" src="https://user-images.githubusercontent.com/41927382/209447281-c53dcb55-9b03-482b-b21d-108790ec0654.png">

Is only the display language wrong or does this also effect the metadata of the video file?

**Comment by hama3254** [comment]
@Ravn73 
>I got the Addon installed, but how do i set it up? Which port do i have to put in there, do i have to do a port foward in my router?

The add-on only access the local downloader, it has to be running and the port has to be selected inside the settings: (note the screenshot is older so it might look a little bit different now)
![grafik](https://user-images.githubusercontent.com/52826614/108770196-50eabe80-755a-11eb-83df-2840859bb896.png)

**Comment by x3inspire** [comment]
> Same...
> 
> ![image](https://user-images.githubusercontent.com/4635825/208332558-010584c2-c9cc-453e-a99d-cccab113ac26.png)

@hama3254 when you can fix this problem T_T

**Comment by 619beave** [comment]
> > I've noticed in 3.11 the language is always English Dub, even though the Screenshot is from Japanese Dub.
> > <img alt="Screenshot 2022-12-24 10 13 49" width="1920" src="https://user-images.githubusercontent.com/41927382/209447281-c53dcb55-9b03-482b-b21d-108790ec0654.png">
> 
> Is only the display language wrong or does this also affect the metadata of the video file?

The Display Langue is wrong and the Meta Data is wrong as well.

<img width="632" alt="Screenshot 2022-12-25 05 49 51" src="https://user-images.githubusercontent.com/41927382/209470457-5b602cb0-5a68-4a1e-88eb-3eff797f344a.png">
This screenshot shows the dub. is displaying English

![image](https://user-images.githubusercontent.com/41927382/209470494-30df3a03-99b0-4ab3-809d-79f4bda2131c.png)
This shows the Meta Data of the Audio using MediaInfo.

![image](https://user-images.githubusercontent.com/41927382/209470529-6bafeb52-282b-4cef-be0c-c29df9c7abb6.png)
This shows what it looks like in MKVToolNIX GUI.

I hope this helps in getting the issue worked out

**Comment by x3inspire** [comment]
> > > I've noticed in 3.11 the language is always English Dub, even though the Screenshot is from Japanese Dub.
> > > <img alt="Screenshot 2022-12-24 10 13 49" width="1920" src="https://user-images.githubusercontent.com/41927382/209447281-c53dcb55-9b03-482b-b21d-108790ec0654.png">
> > 
> > 
> > Is only the display language wrong or does this also affect the metadata of the video file?
> 
> The Display Langue is wrong and the Meta Data is wrong as well.
> 
> <img alt="Screenshot 2022-12-25 05 49 51" width="632" src="https://user-images.githubusercontent.com/41927382/209470457-5b602cb0-5a68-4a1e-88eb-3eff797f344a.png">
> 
> This screenshot shows the dub. is displaying English
> ![image](https://user-images.githubusercontent.com/41927382/209470494-30df3a03-99b0-4ab3-809d-79f4bda2131c.png) This shows the Meta Data of the Audio using MediaInfo.
> 
> ![image](https://user-images.githubusercontent.com/41927382/209470529-6bafeb52-282b-4cef-be0c-c29df9c7abb6.png) This shows what it looks like in MKVToolNIX GUI.
> 
> I hope this helps in getting the issue worked out

how you can use the apps without error?

**Comment by Ravn73** [comment]
> @Ravn73
> 
> > I got the Addon installed, but how do i set it up? Which port do i have to put in there, do i have to do a port foward in my router?
> 
> The add-on only access the local downloader, it has to be running and the port has to be selected inside the settings: (note the screenshot is older so it might look a little bit different now) ![grafik](https://user-images.githubusercontent.com/52826614/108770196-50eabe80-755a-11eb-83df-2840859bb896.png)

Ok. I did that. The Downloader has the same error. CR changed something again.

**Comment by 619beave** [comment]
> > > > I've noticed in 3.11 the language is always English Dub, even though the Screenshot is from Japanese Dub.
> > > > <img alt="Screenshot 2022-12-24 10 13 49" width="1920" src="https://user-images.githubusercontent.com/41927382/209447281-c53dcb55-9b03-482b-b21d-108790ec0654.png">
> > > 
> > > 
> > > Is only the display language wrong or does this also affect the metadata of the video file?
> > 
> > 
> > The Display Langue is wrong and the Meta Data is wrong as well.
> > <img alt="Screenshot 2022-12-25 05 49 51" width="632" src="https://user-images.githubusercontent.com/41927382/209470457-5b602cb0-5a68-4a1e-88eb-3eff797f344a.png">
> > This screenshot shows the dub. is displaying English
> > ![image](https://user-images.githubusercontent.com/41927382/209470494-30df3a03-99b0-4ab3-809d-79f4bda2131c.png) This shows the Meta Data of the Audio using MediaInfo.
> > ![image](https://user-images.githubusercontent.com/41927382/209470529-6bafeb52-282b-4cef-be0c-c29df9c7abb6.png) This shows what it looks like in MKVToolNIX GUI.
> > I hope this helps in getting the issue worked out
> 
> how you can use the apps without error?

What I do at the moment is manually change it in MKVToolNIX GUI when I merge the Video,  Audio,  and Subtitle.

**Comment by Kyon86** [comment]
> @Ravn73
> ...Ok. I did that. The Downloader has the same error. CR changed something again.

I think it's related to #638 with my log hama found something but he can check only when he returns home, crunchyroll changed something yesterday in the afternoon. I start to have issues during that time.

**Comment by Ravn73** [comment]
Yeah, i think so too. Well, then have happy Holidays Hama and everbody!

**Comment by Ravn73** [comment]
Funny, it works again

**Comment by x3inspire** [comment]
> Funny, it works again

not funny because it not work...

**Comment by hama3254** [comment]
[i uploaded a build of the current master branch](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11), this should help with the 403 issues.

@619beave i did not try much but it seems like the new api has wrong data for the language 
i selected the `OmU` version (german for [original version with subtitles](https://de.wikipedia.org/wiki/OmU)) so it should be `ja-JP`
![grafik](https://user-images.githubusercontent.com/52826614/209692898-9a9f7f88-a90c-48c8-9db8-5c59e456c7d4.png)

**Comment by 619beave** [comment]
> [i uploaded a build of the current master branch](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11), this should help with the 403 issues.
> 
> @619beave i did not try much but it seems like the new api has wrong data for the language i selected the `OmU` version (german for [original version with subtitles](https://de.wikipedia.org/wiki/OmU)) so it should be `ja-JP` ![grafik](https://user-images.githubusercontent.com/52826614/209692898-9a9f7f88-a90c-48c8-9db8-5c59e456c7d4.png)

Thanks.  Hopefully, it can be resolved soon.  It does not affect me much since I manually merge the Video/Audio and subtitles.  But others might have problems.  

THank you again and Happy New Year.

**Comment by 619beave** [comment]
Interesting with 3.11.3.  Recently having issues with Audio Locale.  With the last anime I downloaded, Utawarerumono Mask of Truth Episode 28 the Audio was displaying correctly.  

See Screenshots:
<img width="632" alt="Screenshot 2022-12-25 05 49 51" src="https://user-images.githubusercontent.com/41927382/210153243-87701c85-0c3e-49b6-9599-ad1108fc8b90.png">

<img width="775" alt="Screenshot 2022-12-31 10 46 52" src="https://user-images.githubusercontent.com/41927382/210153245-642a99a3-d3f6-465f-ab7d-0c9021e5431b.png">

Just thought I should let you know.

**Comment by hama3254** [comment]
@619beave good to see it work, this is proably due to the workaround mentioned on the [release page](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.11).

>invalid metadata https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/632#issuecomment-1366025808 will not be used if more than two subtitles are avalibe so it will use ja-JP as the value.
