### ISSUE TITLE
Resolution not found.

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#634]
While trying to download Planetarian, episode 5 presented me with an error.

**Where does the issue happen?**
Crunchyroll, insecure curl, hybrid mode, redirect multi, 480p, mkv format, copy, episode number episode name, dubbed not enabled, hardsubs for English, chapters enabled, 
version is v3.9.12

![image](https://user-images.githubusercontent.com/751507/208764146-13d48cdf-b0a7-4ed8-a238-d99b98560b8b.png)

I will download the latest version and try again, then update.
I tend to stick on versions that just work.  Until they don't.

**Comment by hama3254** [comment]
There have been API changes, please try the latest version before submitting issues.

**Comment by Serpentstar** [comment]
My apologies, that was all on me.

**Comment by JanKDP** [comment]
I have the same problem but i am using the v.3.11.3
