### ISSUE TITLE
Another new error 403

### ISSUE THREAD

**Issue by Kyon86** [hama3254/Crunchyroll-Downloader-v3.0#638]
Enter your version below, it can be found in the "About" section of the settings.
Version :  v3.11

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>
  <summary>Insert the logtext before the second details</summary>

 ```
Thread Name: Main
25/12/2022 08:16:17.265
Auth-Basic: Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
NavigationCompleted: 25/12/2022 08:16:21
25/12/2022 08:16:21.268
https://www.crunchyroll.com/it/
Just Browsing, exiting...
Start loading: 25/12/2022 08:18:36
16
CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6Im85OGdyZTlXeHY1c3EzT2lWUHYtQUEiLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJiZW5lZml0cyI6WyJjYXRhbG9nIiwiY29uY3VycmVudF9zdHJlYW1zLjEiLCJjcl9wcmVtaXVtIiwibm9fYWRzIiwic2ltdWxjYXN0Il0sImNsaWVudF9pZCI6ImNyX2JhY2tlbmQiLCJjbGllbnRfdGFnIjoiMS4wLjAgYmV0YSIsImNvdW50cnkiOiJJVCIsImV0cF91c2VyX2lkIjoiMTgyYWFlMDQtMWUzMS01NDc0LWJiZGMtMzg4OTk3ZThmMjVhIiwiZXhwIjoxNjcxOTUzMDE3LCJqdGkiOiI4YTAyNGY4YS02N2E4LTRlNzUtYTgwNy04MGQ0NjA3YjE1Y2UiLCJtYXR1cml0eSI6Ik0zIiwib2F1dGhfc2NvcGVzIjoiYWNjb3VudCBjb250ZW50IG9mZmxpbmVfYWNjZXNzIHJldmlld3MgdGFsa2JveCIsInJ0X2lkIjoiY2Vnc3M4b2RxbWp0c2swdWI3cjAiLCJzY29wZXMiOnsiY3IiOnsiYWNjX2lkIjoiMTgyYWFlMDQtMWUzMS01NDc0LWJiZGMtMzg4OTk3ZThmMjVhIiwiZXh0X2lkIjoiOTcyNTg3MCJ9fSwic3RhdHVzIjoiQUNUSVZFIiwidG50IjoiY3IifQ.OPwDzHNgCj9UfADQLGzCf22KFA3mEtdcLlEdu-HzGs0MaUwXNoSPzXl6gBzjMAEYb-PqYQKLCHAyNgzO8etmaXyMculuxkRFg6351ooNYvOC86E4Hoe267j2N9455MMsu8S8WrGuIjsCf6hLPGnpM6a7QBah0eIx7qnXDtefMVIXrYJBwnzzRx_ySZgviaE7Szpur_9fINmjUgSyJi0El3oLJwUBTS-YVDnxbM4jMbe47ifmFBJH6ybGwuR-XIfdu-jBSCzVx8rblhDLzi8sy8nJihBE0Yrj56rVzitgdKYCd69K53gO4eHe7YVFAKedfxntUXGMoMLo_1WRx_9puA","refresh_token":"5586de65-ff4c-4035-86e8-6da9b2d19f61","expires_in":300,"token_type":"Bearer","scope":"account content offline_access reviews talkbox","country":"IT","account_id":"182aae04-1e31-5474-bbdc-388997e8f25a"}
CurlAuth-E: curl: (3) URL using bad/illegal format or missing URL
curl: (22) The requested URL returned error: 403

NavigationCompleted: 25/12/2022 08:18:41
25/12/2022 08:18:41.978
https://www.crunchyroll.com/it/series/GXJHM3P19/bocchi-the-rock
Crunchyroll-Season: https://www.crunchyroll.com/cms/v2/IT/M3/crunchyroll/seasons?series_id=GXJHM3P19&locale=it-IT&Signature=dP2YMqWIKXy3KvnSa-BxTB14NmAD71C0To9lig5pe1ELQakGYpN7jRjJY9IPHpRtuB8BktMUBAamvXg7oSOWBLD-MSjk2-lTHDFuzt-kTbCK1pnugm5UDYBG21n47~Gfz5xLoOphWSD2yjws70LKxLv6TD1ijsd5BmexYleXGYVe~pqfbjcfWoREAXy9Y6I44sYn0nDgdHMauxz~3jNBCKodxsYQEkXNiVU9SBcHUNKQWTWNtA~UfjvS5TcGXGKIWut6Pd1wRb5t-rtuxAPgZaXYWth3W~8P1fZyz6j8F3~~-9r-pjB~pe7zDH6cXiIK-v6ghsCsOFknTSzxzWKKcQ__&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly93d3cuY3J1bmNoeXJvbGwuY29tL2Ntcy92Py9JVC9NMy9jcnVuY2h5cm9sbC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjcyMDM5MTIxfX19XX0_&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA
LoadedUrls: 2
ProcessUrls
2
25/12/2022 08:18:43 Thread Name: Main
Crunchyroll season found
curl-E: curl: (22) The requested URL returned error: 403
```

</details>

It's from yesterday evening that there will be an error 403 everytime I try to download a batch of a series from Crunchyroll. After that if you press ok in the episode selection screen you have only empty boxes and you cannot proceed further. If you procede episode with episode there isn't any issues.

![Errore Batch Download](https://user-images.githubusercontent.com/121374597/209460389-734bc080-083c-4a69-9d56-8125f2824d06.jpg)

This is a differente issues from #623 because it was solved with the 3.11 update i had done before and worked until yesterday evening.

I know it's a holiday and it can still work out episode by episode, so take your time and happy holidays.

**Comment by hama3254** [comment]
The 403 error is the same as usual.
This however is new.
`CurlAuth-E: curl: (3) URL using bad/illegal format or missing URL`
For everything more i have to get home first.

**Comment by DefaultLP** [comment]
Maybe it is unrelated, but when I opened the programs browser a prompt window from Sony Pictures about my privacy choices came up. It would not let me proceed before accepting it.

**Comment by Kyon86** [comment]
> Maybe it is unrelated, but when I opened the programs browser a prompt window from Sony Pictures about my privacy choices came up. It would not let me proceed before accepting it.

It doesn't appear to me because I've already accept them.

**Comment by Kyon86** [comment]
I tried it now by chance and it didn't give me the error and it seems to work, even if I notice from today that sometimes it stops downloading and I have to re-download the episodes all over again.

At this point I'm assuming they have the servers a bit overloaded for the holidays and can't handle the load properly.

**Comment by hama3254** [comment]
> This however is new.
> `CurlAuth-E: curl: (3) URL using bad/illegal format or missing URL`

it took a look at that and have no idea how this should even be possible, the url for the auth request is fixed
![grafik](https://user-images.githubusercontent.com/52826614/209692141-204841a6-776c-4007-9a05-e41f5ae06cb9.png)
