### ISSUE TITLE
 Cannot use subtitle download

### ISSUE THREAD

**Issue by Fpsroxas** [hama3254/Crunchyroll-Downloader-v3.0#64]
When I try to use the single download it keeps looking for subtitles forever (I left it waiting 24 hours to see if anything happened, nothing happened)
![Captura de tela 2020-10-04 124341](https://user-images.githubusercontent.com/45643566/95020186-1aaab200-0640-11eb-8b17-ec77157837cf.png)
and when I try to use multi download the menus are blank
![Captura de tela 2020-10-04 124435](https://user-images.githubusercontent.com/45643566/95020220-504f9b00-0640-11eb-9754-d2083a5f0c54.png)

**Comment by hama3254** [comment]
There are two issues, the singe download does just not update but it does work as long as one SoftSubs language is set and saved(!) 
<details>
<summary>SoftSubs</summary>
![grafik](https://user-images.githubusercontent.com/52826614/95025771-6c792980-068c-11eb-9a78-5be76c03d771.png)
</details> 
and the Mass DL just does not display the episodes.
The issues are fixed but i need to remove a view more bugs from the version before i can release it.
this might take a week.

**Comment by hama3254** [comment]
should be fixed with v3.5.2

**Comment by Fpsroxas** [comment]
yes fixed like a charm
