### ISSUE TITLE
curl: (60) error on the new v 3.11

### ISSUE THREAD

**Issue by dranas85** [hama3254/Crunchyroll-Downloader-v3.0#643]
I get this error when I click the download button right before the season and episode drop down menus pop up.
![CR dl error](https://user-images.githubusercontent.com/109874399/209476291-a2243b3e-be94-4127-9cef-b3d49abaf130.png)

**Comment by hama3254** [comment]
not the real solution but ignoring it with [--insecure](https://curl.se/docs/manpage.html#-k) should work.
![grafik](https://user-images.githubusercontent.com/52826614/209685530-69bd918d-7170-4ed3-a576-8c5a4c5db820.png)
