### ISSUE TITLE
Different Size with the same config

### ISSUE THREAD

**Issue by Nevan6** [hama3254/Crunchyroll-Downloader-v3.0#646]
A few months ago, the episodes that I downloaded were all like 1.33Gb, and I was happy with that. But now that I have downloaded the new version, and they are all like 500mb. (I've been trying various options of the ffmpeg command, and it always drops to 500mb). I am using the same configuration as in previous versions (-c copy)(MP4) (Default ffmpeg). I want to download them the same as they are on the web page, with the minimum modification. How do I download it again like before? And what is the way to get them out like the original? Thanks for your time and work.

**Comment by hama3254** [comment]
> A few months ago, the episodes that I downloaded were all like 1.33Gb,

that is still (more or less) the case for me

![grafik](https://user-images.githubusercontent.com/52826614/210235294-dadd096e-1186-4dfe-b812-a5833bfc3db4.png)

> I am using the same configuration as in previous versions (-c copy)(MP4) (Default ffmpeg).

one factor missing there is the resolution, 720p is usually half ther size as 1080p.

>And what is the way to get them out like the original?

`-c copy` is the best way you can use, the video itself will be like it's on CR and just some formating is done to get it into one file not the hundreds of segments the stream is made of.

Something to always keep in mind is the files from CR can change as well, they might use smaller files for some anime (like older ones).

**Comment by hama3254** [comment]
> I'm doing something wrong.

You can not do anything wrong there with `-c copy`.


> That could be what you say, that they have been modified.

i can neither confirm or deny this but i get the usuall file size , this may have technical reasons (like a [CDN](https://en.wikipedia.org/wiki/Content_delivery_network)) but i don't think i can do much there.


![grafik](https://user-images.githubusercontent.com/52826614/210273204-6a12e5ed-41a5-4b7c-bbcd-cf89b73020c9.png)
