### ISSUE TITLE
CPU throttled during download

### ISSUE THREAD

**Issue by TheUnproductive** [hama3254/Crunchyroll-Downloader-v3.0#648]
**Describe the bug**

During the download Process the Processor speed is throttled to below 1 GHz. Everything is working perfeclty using v3.11

**Where does the issue happen?**
 - Platform: Cruchyroll Beta
 - Settings default
 - Version v3.12

**Additional context**

I am using a Ryzen 7 3800XT

**Comment by hama3254** [comment]
The downloader does not change any settings of your hardware.
Two possible reasons are the windows power plans don't allow for more power if they are set to `Power saver`

<details>
  <summary>Image</summary>
  
![grafik](https://user-images.githubusercontent.com/52826614/210425650-51b4e350-41f4-4126-8f0b-1542005ca4a6.png)
  
</details>

Or you can hit a thermal limit especially with `libx264` or `libx265` as encoding option.
You can see the temperature with 3rd party software like  [HWMonitor](https://www.cpuid.com/downloads/hwmonitor/hwmonitor_1.48.exe) then you can see while downloading how the temperature changes.
![grafik](https://user-images.githubusercontent.com/52826614/210426243-ea10e026-95b8-43d9-b422-76e48b6f8a6c.png)
