### ISSUE TITLE
Download crashed

### ISSUE THREAD

**Issue by fedeangeles** [hama3254/Crunchyroll-Downloader-v3.0#65]
When I try to download a video with a duration of more than 30 minutes it fails.

![Screenshot_1](https://user-images.githubusercontent.com/71239003/95052332-2096a680-06c5-11eb-8434-1eededcca4e3.png)
![Screenshot_2](https://user-images.githubusercontent.com/71239003/95052334-21c7d380-06c5-11eb-95b8-ccdd7a295779.png)

**Comment by hama3254** [comment]
That's strange considering that I even used re:zero for the hybrid download tests due to it's length and I even used 1080p: https://youtu.be/s_SY3RM1F3Y

Please enable the log file in the settings and add it here (just drag and drop into the text field should work on a desktop computer)

**Comment by hama3254** [comment]
i assume it works now so i will close this, if you have still problems please make a new issue with a log file.

**Comment by fedeangeles** [comment]
That should i activate? Now where is the log file saved or what is it?
