### ISSUE TITLE
Feature request - dedicated "start queue" button

### ISSUE THREAD

**Issue by scopion1745** [hama3254/Crunchyroll-Downloader-v3.0#650]
I would love to see a dedicated "start queue" button at the front of that tool.

Kinda hate it, opening the download tab, since i use the Chrome Extension.

But nothing that needs any priority.

**Comment by hama3254** [comment]
The question is to where put it?
First of all should it be in the add-on or the downloader? The second would be better to control the downloader without switching to it.

**Comment by scopion1745** [comment]
Ich würd den im Downloader platzieren. Irgendwo oben neben dem Einstellungen-Button oder so.

**Comment by hama3254** [comment]
i just finished moving the queue to the new ui part, [you can try it with this version ](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/0.1)

**Comment by scopion1745** [comment]
Just updated to the new version. Already loving it, because i recognize the icon xD


a little bit off topic: is the queue written somewhere? Last week the downloader crashed while i had somewhere between 100 - 200 items queued. Would have loved to re-add them somehow .

**Comment by hama3254** [comment]
> Already loving it, because i recognize the icon xD

that is probly just your imagination xD 

> a little bit off topic: is the queue written somewhere?

the queue itself is just a `.net` list and therefore should just inside the memory.

The downloader is also not meant to be used with so many downloads, i build it to download what to watch not as archive tool.
