### ISSUE TITLE
Filenaming always sets "RepDub" for Audiolanguage

### ISSUE THREAD

**Issue by scopion1745** [hama3254/Crunchyroll-Downloader-v3.0#651]
**Describe the bug**
I activated the new Naming Feature for "Audio Language" and it always seems to set "RepDub" despite the acutal language.

**Where does the issue happen?**
 - Platform: CR
 - Settings (see screenshot, except that "Audio language" is ticked now)
![Snag_04-01-2023_00-59-22](https://user-images.githubusercontent.com/46906104/210463432-1a6fd960-6ebc-4857-8603-4d1ee1438e7a.png)
  - Version 3.12

**Screenshots**
![Snag_19531fb](https://user-images.githubusercontent.com/46906104/210462945-3eb0e3a9-fe46-42b8-af9a-c575c88e47be.png)

**Additional context**
I've tried it with two different Animes and two languages (JP & ENG).

Edit:
- Problem exists when using Chrome Addin
- Problem persist if the link is copied from a Browser to download dialog
- Problem event persist when using the build in browser. (now tested on three animes & three languages)

**Comment by hama3254** [comment]
I have to see where this i coming from, the display name seems right to me in the screenshot.
