### ISSUE TITLE
Filename settings don't save when you close the app

### ISSUE THREAD

**Issue by MattRBX** [hama3254/Crunchyroll-Downloader-v3.0#655]
When changing the settings for naming a file in CRD, then clicking Save & Exit it does save the settings temporarily in some weird way. It names the files according to what I set it as, but when I open the settings panel after clicking Save & Exit, it goes back to default or it at least shows the default settings, so I have to change it again so it doesn't name my files differently when clicking Save & Exit.

I hope this is explained well enough. It's a bit difficult to wrap it all up like this at once. Hope this gets fixed as I sometimes need to manually rename my files because I forgot to set it back to what I normally use which is a bit annoying.

**EDIT:** It appears to only happen, when closing the app fully and then re-opening it. When re-opened it then resets the naming back to default. And it seems to save the settings for the session that you're using the app, but when closed it then goes back to default.

**Comment by hama3254** [comment]
I noticed that and it should be fixed with the latest version.

**Comment by MattRBX** [comment]
I see.. I just had an old version and I updated and the naming issue seems to be fixed.
However I found another issue, which is very similar. Now the Hardsub language is doing the same thing to me.
Every time I re-open the app it sets the hard-sub to "English"

Maybe look into that? I'd assume it's the same thing that went wrong so you should be able to fix it.
