### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by unusualwilly** [hama3254/Crunchyroll-Downloader-v3.0#658]
![2023-01-11_14-13](https://user-images.githubusercontent.com/85754719/211899134-0cf3ba6d-8e15-4f4a-9bdd-281e576479ec.png)

what is this?

**Comment by hama3254** [comment]
>what is this?

it's a error.

the line would indicate that there was an issue with the cookies from the browser, it can happen somethimes tha the browser has not bootet up fully so getting the cookies fails.
please try to open the add window and wait a view seconds before clicking `Download`

**Comment by unusualwilly** [comment]
https://user-images.githubusercontent.com/85754719/212140742-25cca666-5ad7-45d7-b013-0742a367b6d2.mp4

**Comment by hama3254** [comment]
the webbrowser does not load at all for you, it seems you miss the [WebView2 Runtime from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).
