### ISSUE TITLE
Subtitle language not found issue

### ISSUE THREAD

**Issue by BadrOuassif** [hama3254/Crunchyroll-Downloader-v3.0#659]
**Describe the bug**
When i open the episode in the browser i do see Arabic subtitles, but when i try to download the episode with the Arabic subtitles using CRD it does tell me that there's no Arabic subtitle.

**Where does the issue happen?**
 - Platform: Cruchyroll Classic
 - Settings: Hardsubs
 - Version: v3.13

**Screenshots**
![Arabic](https://user-images.githubusercontent.com/122495617/211941944-72fae9f4-0768-461b-bfcb-3256a75c974d.png)
![No Arabic](https://user-images.githubusercontent.com/122495617/211941956-f5512284-f3fb-4b0b-ae23-c3ed7c710743.png)

**Comment by hama3254** [comment]
The crunchyroll website uses soft-subtitles and you try to download the hard-subtitle version which is missing on CR.
You can only get the video with softsubtitles, there is no other easy way to fix this.
![grafik](https://user-images.githubusercontent.com/52826614/212113128-26e31f95-7bc3-47d2-ae09-f50d4412fea1.png)

**Comment by BadrOuassif** [comment]
Thanks for making it clear.
