### ISSUE TITLE
NotABug

### ISSUE THREAD

**Issue by JomSpoons** [hama3254/Crunchyroll-Downloader-v3.0#66]
This isn't really an "issue" but I wanted to say I think you should either move this project or mirror it to notabug.org in case this repository gets taken down. Just a suggestion.

**Comment by hama3254** [comment]
well that would not be the first time something like this happens https://github.com/github/dmca/blob/master/2020/07/2020-07-14-crunchyroll.md so the mirror in online : https://notabug.org/hama3254/Crunchyroll-Downloader-v3.x
unfortunately they just allow 32MB for releases so it will be just mega.nz links.
