### ISSUE TITLE
watchlist download!

### ISSUE THREAD

**Issue by johnkennyuk** [hama3254/Crunchyroll-Downloader-v3.0#660]
Not able to download batches using watchlists / crunchylists,

a way to copy the url of a list page then add that url to batch download multiple titles at once.

no alternatives viable with crunchyroll downloader 

granted to work this additional feature other changes would be needed, such as being able to set the downloaded language in advance rather than the on download drop down as far as episodes as long as all episodes are pulled it would suffice.  lastly an override setting to overwrite files or skip files if it finds existing files would also be needed all so that batch processing is viable.

(FYI i have had a play with the code but coming from a Python background i haven't been able to make much progress to try myself being Visual Basic source code)

**Comment by hama3254** [comment]
I don't quite understand the issues, you can use the season page of CR to download an whole season with the choices you made in the settings.

**Comment by johnkennyuk** [comment]
fyi thia isn't an issue ita a feature request using the feature request template, i just thought it would be useful to be able to add crunchylists for batch series downloads rather than adding one series at a time...

**Comment by hama3254** [comment]
as i said i did not understand the request at all.

Now i think i understand the request.
You want this lists to work directly inside the downloader.
![grafik](https://user-images.githubusercontent.com/52826614/212429646-14bafe93-da03-4c63-8693-5a453637d6b8.png)

Not only would this take huge changes but it is also not required for the downloaders purpose to download what you want to watch.
You can right now download easily more with a view clicks than you want watch in a whole week, this has to be enough.

**Comment by johnkennyuk** [comment]
Thanks for the reply, as I originally mentioned I realise this would take many changes.  I will have another crack at Visual Studio to see if I can get my dependencies sorted to see about making my changes in my spare time (Doubt I will be able to make any headway as I hadn't been able so far, I couldn't work out how to get around my env telling me the MVC versions from the source project were invalid??  I could never manage to get my VS to build from the Git Repo??)  Anyway, I do see where you are coming from and I have been adding to the app's queue one series at a time, It would be a feature id love to see at some point, hence being a feature request.  Maybe archive this request on your project ToDo list??
