### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by GetUsedToMe** [hama3254/Crunchyroll-Downloader-v3.0#666]
**Describe the bug**
Browser inside the downloader opens but cant work with any links

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings Hardsubs, 1080p, mp4, merge disabled, -c copy
 - Version [e.g. v3.13.1]

**Screenshots**

![Capture](https://user-images.githubusercontent.com/122670905/212466027-5e2a69b3-44be-4360-b9aa-64ec03f4d6e1.PNG)
![Capture2](https://user-images.githubusercontent.com/122670905/212466052-702167f2-45bc-424e-9e5f-2dd24917fc43.PNG)

**Additional context**
Browser inside the downloader opens but cant work with any links so logging in and downloading premium episodes is not possible for me

**Comment by hama3254** [comment]
it seems you miss the [WebView2 Runtime from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).

**Comment by GetUsedToMe** [comment]
> it seems you miss the [WebView2 Runtime from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section).

Thank you now it works.
