### ISSUE TITLE
Problem with video download

### ISSUE THREAD

**Issue by Mayansito** [hama3254/Crunchyroll-Downloader-v3.0#667]
I have this problem:
![d3f40943495721941319e62a9a01983b](https://user-images.githubusercontent.com/98242308/212468028-636a043b-3868-4ce2-9a1a-5a49caf3d5ba.png)

And when i click Submit, this:
![faec68426a937b295c90c8d623452fdc](https://user-images.githubusercontent.com/98242308/212468043-edf2f9d3-aeaa-4033-8fec-46be0a30eb54.png)

**Comment by hama3254** [comment]
should be the same issue as #661 and the latest version should help with that.

**Comment by Mayansito** [comment]
I have WebView issue dowload with last version and i tried everything.
![b87160f9345a4ad674dcf5ab4dbb94fa](https://user-images.githubusercontent.com/98242308/212468265-21d96b7c-2e8a-4831-9f62-9694905b9237.png)

**Comment by hama3254** [comment]
if you have the downlader is located inside the `C:\Program Files` then move it on the Desktop and see if that solves the problem.

**Comment by Mayansito** [comment]
Working on Desktop. Nice.
