### ISSUE TITLE
sub folders not being created?

### ISSUE THREAD

**Issue by johnkennyuk** [hama3254/Crunchyroll-Downloader-v3.0#669]
**Describe the bug**
I was sure i had the app auto creating sub folders for the seasons below the series name, i have the setting to create season folders but for some reason what I'm downloading isn't creating them?

**Where does the issue happen?**
 - Platform: crunchyroll 
 - Settings auto create season sub folders is set
 - Version 3.13.1

**Screenshots**
![Screenshot_2023-01-14-23-32-08-02_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/64958468/212501612-61ead515-bd1c-4149-aa39-9e9ad69cfa7c.jpg)

the settings im using are pictured but im having to create the season folders manually at present.

**Additional context**
are there any conditions that could cause sun folders to work then just stop the next day, or would it matter if the series folder wasn't created by crunchyroll downloader itself?

**Comment by hama3254** [comment]
i can not find any combination of settings that would result in that behavior.
![grafik](https://user-images.githubusercontent.com/52826614/212542462-dea083ac-d2de-4fdd-af5d-0c9a6b2f6c68.png)

the only way this might happen that i can see if the downloader can not create the folder and falls back to the original path.

**Comment by johnkennyuk** [comment]
Yeah I thought it was strange too as it was working fine, I originally assumed id left it set to ignore the season naming for season 1 only but i hadn't.  But going back to my original post where i mentioned asking if it might have any relation if the download in progress already has a series folder there already made manually??  I will have another play to verify this theory but with new series downloads the sub folder creation appears to work if this app created the series tld folder.  So when I have another play ill double check permissions etc, i.e. what permissions are on app created paths to manually created paths.
