### ISSUE TITLE
Hybrid only works for CR releases

### ISSUE THREAD

**Issue by dkb007** [hama3254/Crunchyroll-Downloader-v3.0#67]
As the title suggests, Hybrid only works for Crunchyroll releases and not for funi, mainly because it cannot merge those ts files while hybrid is active. Please take a look at that issue .

Thanks,

**Comment by hama3254** [comment]
i see there is an issue, but this is not directly related to the hybrid mode.
from my tests : 
`10.10.2020 21:10:27[hls @ 06453ec0] Opening 'https://[...]Layer3_0.key' for reading`
`10.10.2020 21:10:28[https @ 064829c0] HTTP error 403 Forbidden`
`10.10.2020 21:10:28[hls @ 06453ec0] Unable to open key file https://[...]Layer3_0.key`

if you have a logfile please share it here, meanwhile i try to see why it's a 403 error for ffmpeg but not if it try the url in my webbrowser.

**Comment by hama3254** [comment]
the issue i found is fixed, the downloader will now also cache the .key files because ffmpeg just got `HTTP error 403 Forbidden` while the .net webclient can access the file without a problem
please try v3.5.3 and tell me if your issue is gone with the new version.
