### ISSUE TITLE
Sub/Dub changes

### ISSUE THREAD

**Issue by xILikepuddingx** [hama3254/Crunchyroll-Downloader-v3.0#673]
Einfach weil es früh am morgen ist und die Nachricht dazu topaktuell:

Crunchyroll wird nun Dub und Sub nach und nach gleichzeit anbieten wie man es hier in diesem Beispiel https://www.crunchyroll.com/de/series/GQWH0M455/dont-toy-with-me-miss-nagatoro gut sehen kann.

Es scheint auch so, dass der Downlaoder mit der Änderung nicht mehr klar kommt :D
Mit diesem Link wurde nichts gefunden

Es ist noch nicht überall wird aber nach und nach bei allem so kommen.

LG

**Comment by hama3254** [comment]
Ich werde bei Gelegenheit Mal drauf schauen, das die sowas immer mitten in der Woche machen müssen...
Bei solchen großen Änderungen ist das aber durchaus wahrscheinlich das er nix mehr findet.

**Comment by hama3254** [comment]
ich mach hier mal zu, für alles weitere ist #677 da.
