### ISSUE TITLE
Processing Url

### ISSUE THREAD

**Issue by AnAppleInABox** [hama3254/Crunchyroll-Downloader-v3.0#676]
Recently when ever I go to download something it will Process the Url for 30 seconds and the say "nothing found"

I was using version 3.11 but when I came here and downloaded the new version nothing changed. I made sure I was signed in on the browser. Still nothing.

This seems to have coincided with a new change to crunchyroll. The website asked me for my language preferences for audio and subtitles. When I checked any anime there are far less options. No more language options. I'm guessing you change those in settings.

Is there anyway to get around crunchyroll's new change on the current version of the downloader?

Also the instructions and diagrams on this website are outdated. I know you probably know and it isn't the highest priority but it'd be nice. Thank you for your time, program, and for reading.

**Comment by Rayxcer** [comment]
Crunchyroll changed how they display (maybe even serve) Sub/Dub variations.
This will not function in the current version. The author said as much in #673, albeit in german.

**Comment by hama3254** [comment]
> In the example you showed you were able to selected the different options however I couldn't reach that screen

This was already a issue in the past, for some reason the downloader would get `forbidden` as a response and not what was requested. This never happen to me so i still  don't know how to properly handle that. My workaround was to use the traffic of the browser which now does not work anymore.
You might find the error code `curl: (22) The requested URL returned error: 403` inside your own logs.

<details>
  <summary>The log is a the bottom hidden behind the bar</summary>

  ![grafik](https://user-images.githubusercontent.com/52826614/213559082-c544be36-8d4d-498f-bb22-87869282b254.png)
</details>

for everything else i need some days to work on the new api stuff.

**Comment by AnAppleInABox** [comment]
> The log is a the bottom hidden behind the bar

I went and tried downloading stuff again. I hadn't known about the bar before. I thought I'd confirm the error message you mention but then the downloader is working just fine until I viewed the episodes I downloaded and they had no subtitles. I try to download again and same as before. Processing Url

Looking at the bottom bar it says:
NavigationCompleted: 20/01/2023 8:25:44 AM
https://www.crunchyroll.com/series/GYZJ43JMR/that-time-i-got-reincarnated-as-a-slime
3508: nothing found

I have to assume that main problem is on crunchyroll's end. The subtitles however I have no idea. Before I used the softsub setting and I wanna try using hardsub but I have no idea if it'll work or even load.

**Comment by Serpentstar** [comment]
I am seeing the same thing as @AnAppleInABox 
I think it is back to timing.
![image](https://user-images.githubusercontent.com/751507/213831006-ae534ace-dc78-43cc-a179-d7844ad4ecc0.png)

Occasionally, it will bring up the series, other times it won't.
CR is at it again.  Sigh.

**Comment by ManuelDiazIsaza** [comment]
I have the same issue

![image](https://user-images.githubusercontent.com/37357573/213845937-c0fe79d7-721a-46b6-a9ba-d1ee2b9c8668.png)

**Comment by hama3254** [comment]
i am working on that, [v3.14](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14) is avalible with the basics done now i need as much data as possible to fix issues that may arrive.
To make things simpler for me i will lock this one here so please report any issues with v3.14 inside #677.
