### ISSUE TITLE
CR Dub changes

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#677]
As reported in #673 Crunchyroll added the option to change the audio.
![grafik](https://user-images.githubusercontent.com/52826614/213499420-4a441aa9-9d38-41fa-a0f4-a8d23f5cdb91.png)
The old API requests still work but if any of the request chain fails then the fallback only finds single episodes not series due to the changes made from CR.
<details>
  <summary>Example old APIs still work</summary>
  
https://user-images.githubusercontent.com/52826614/213502781-ff8d1d91-cd24-48f2-a082-696ca5b4def6.mp4
  
</details>

**Comment by tormento** [comment]
@hama3254 please add the capability to download multiple audio tracks at the same time, if possible, now that they unified the seasons.

**Comment by hama3254** [comment]
@tormento my priority is getting it to work, then CR still has full videos so i would have to download the video and audio to just get the audio for each version.

**Comment by Rayxcer** [comment]
It appears that I can't download/search for multiple episodes of a series.
I always get the error 1091, the log shows the following:
`CurlAuth-E: curl: (3) URL using bad/illegal format or missing URL`
`curl: (22) The requested URL returned error: 403`
This comes with every series I tried so far, for example:
`https://www.crunchyroll.com/series/GY1XX0N0Y/black-clover-dubs`
or
`https://www.crunchyroll.com/series/GRVNMG93Y/log-horizon`

I hope this helps you somewhat.

I thank you for all your hard work. Is there a way to buy you a coffee or something?

**Comment by Mytic-Slander** [comment]
here it appears for individual download
![image](https://user-images.githubusercontent.com/83298605/213865779-a394c982-c7aa-4e0c-b3ef-0c0ea479d23e.png)

**Comment by hama3254** [comment]
fix is uploaded, some codepaths use the cookie value different.

**Comment by hama3254** [comment]
@Mytic-Slander

**Comment by hama3254** [comment]
@Mytic-Slander please check your login inside the build in webbrowser.
if that is as it should be then add the data from the [CRD-Log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log)
![grafik](https://user-images.githubusercontent.com/52826614/213866172-8c50b767-dff7-4232-affc-baf95b32d9a8.png)

**Comment by Mytic-Slander** [comment]
> @Mytic-Slanderpor favor, verifique seu login dentro da compilação no webbrowser. se for assim, adicione os dados do [CRD-Log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log) ![gráfico](https://user-images.githubusercontent.com/52826614/213866172-8c50b767-dff7-4232-affc-baf95b32d9a8.png)

Now it's working, thanks
![image](https://user-images.githubusercontent.com/83298605/213866464-bd14ad27-eea0-4432-bf31-f051739c6ca7.png)

**Comment by Setolein** [comment]
hi 

after i changed the Version from 3.13  to 3.14.1
there are some errors
curl errors and so on
maybe crunchyroll makes the next changes with drm

![error](https://user-images.githubusercontent.com/73212059/213886591-e13d8d58-5705-46cc-9b5a-be9e76b3edbc.PNG)

**Comment by hama3254** [comment]
> sometimes this error occurs:
> 
> ![alt text](https://camo.githubusercontent.com/d7cead79e0cb03cbca2a5ff6ce45998127ac6ee5c632cf8e9cc45bdb597c46f7/68747470733a2f2f692e696d6775722e636f6d2f53374b527a38582e706e67)
> 
> ![alt text](https://camo.githubusercontent.com/294dc731c32e38e8f7a0f3af3a3e1729e21acc055c26cb172e039c613dc0573d/68747470733a2f2f692e696d6775722e636f6d2f637741514f6f692e706e67)


@Boshouko how often does that happen ?

**Comment by hama3254** [comment]
@Setolein not the real solution but you can ignoring the curl error with the [--insecure](https://curl.se/docs/manpage.html#-k) option.
![grafik](https://user-images.githubusercontent.com/52826614/209685530-69bd918d-7170-4ed3-a576-8c5a4c5db820.png)

**Comment by AnAppleInABox** [comment]
I can only download a max of 12 episodes at a time (as set) but when a download finishes no more episodes will begin to download. When I close the add video video and open it again I can't download anything else without reopening the program.

**Comment by Setolein** [comment]
> @Setolein not the real solution but you can ignoring the curl error with the [--insecure](https://curl.se/docs/manpage.html#-k) option. ![grafik](https://user-images.githubusercontent.com/52826614/209685530-69bd918d-7170-4ed3-a576-8c5a4c5db820.png)

i know i tried that but its the same problem
and it doesn't  find the real name for the season 
i'm actually try to download the new episodes from the new Winter Season of all ne Animes

**Comment by Grangorian** [comment]
I get an error that only comes when I try to download an episode from "The Fruit of Evolution: Before I Knew It, My Life Had It Made"
![CRDproblem01](https://user-images.githubusercontent.com/74862277/213887155-7feb291a-4a83-4b4f-8d33-9514514aa55d.jpg)

![CRDproblem02](https://user-images.githubusercontent.com/74862277/213887161-e9d773a0-6e63-4364-9cb2-a9694c6f2d1d.jpg)

And after that it shows way to many first seasons, but not the second season I was looking for.

![CRDproblem03](https://user-images.githubusercontent.com/74862277/213887167-1ab558f5-cafc-4388-b002-39ac5d7285af.jpg)

I tried a few other anime and they don't have this problem.
I also have the problem Setolein reported. It doesn't show the name of the season but the download works just fine for me.

**Comment by hama3254** [comment]
> i know i tried that but its the same problem
and it doesn't find the real name for the season
i'm actually try to download the new episodes from the new Winter Season of all ne Animes

according the curl documentation `This option makes curl skip the verification step` so it should ignorte the certificate and the issue with it.
and the other thing works fine for me, i would nee more data on that to find any potential issues.

<details>
  <summary>image</summary>
  
![grafik](https://user-images.githubusercontent.com/52826614/213887957-f59d606b-e052-40de-bc8f-824e96d4f55d.png)
  
</details>

**Comment by hama3254** [comment]
@Grangorian the error come from the fact that is is a season with `null` versions and the others are some combination from the old and new style so the downloader added all of them..
a small update for that has been released.

**Comment by lucky1804** [comment]
Are there any plans to support downloading multiple audio tracks as one video (without reencoding of course)

**Comment by hama3254** [comment]
@lucky1804 No, Dubs are still individual episodes that they now just hide.
This means i had to download the same epiode fully (video+audio) for each dub and then combine the audio tracks to the first downloaded video.

**Comment by LorenorZorro3000** [comment]
Hallo @hama3254 

Wenn ich zum Beispiel die Serie https://www.crunchyroll.com/de/series/G60XNJW4R/monster-girl-doctor
herunterladen will, dann läuft ein Timer von 30 Sekunden ab und es sagt Status: Nothing found und gibt diese Fehlermeldung aus:

![Screenshot 2023-01-22 130637](https://user-images.githubusercontent.com/123302757/213914864-1a68985d-dc3d-4a90-84a1-5ec4e7e7da4a.jpg)

Wenn ich dann wieder auf Download gehe, zeigt er mir 2x den japanischen und englischen Dub an, aber leider nicht den deutschen:

![Screenshot 2023-01-22 131008](https://user-images.githubusercontent.com/123302757/213915036-968842cc-a96e-454b-9866-6f442ef34692.jpg)

Hier noch was in der LOG steht:
<details>

> Thread Name: Main
Auth-Basic: Basic ***
NavigationCompleted: 22.01.2023 13:16:26
22.01.2023 13:16:26.842
https://www.crunchyroll.com/de/
Just Browsing, exiting...
what's going on?: 22.01.2023 13:16:28
8
CurlPost-O: {"access_token":"***","refresh_token":"***","expires_in":300,"token_type":"Bearer","scope":"account content offline_access reviews talkbox","country":"DE","account_id":"***9"}
https://www.crunchyroll.com/content/v2/cms/series/G60XNJW4R/seasons?preferred_audio_language=de-DE&locale=de-DE
CurlAuth-O: {"total":3,"data":[{"extended_maturity_rating":{},"id":"GREXN9JGY","is_subbed":true,"keywords":[],"slug_title":"monster-girl-doctor","title":"Monster Girl Doctor","series_id":"G60XNJW4R","versions":[{"audio_locale":"ja-JP","guid":"GREXN9JGY","original":true,"variant":""},{"audio_locale":"en-US","guid":"GR0XN0JMY","original":false,"variant":""}],"channel_id":"crunchyroll","mature_blocked":false,"number_of_episodes":12,"subtitle_locales":["es-419","es-ES","it-IT","ru-RU","pt-BR","fr-FR","de-DE","en-US"],"audio_locales":["ja-JP"],"identifier":"G60XNJW4R|S1","maturity_ratings":["TV-14"],"season_sequence_number":0,"seo_description":"","description":"","is_complete":false,"is_simulcast":false,"season_display_number":"","season_number":1,"availability_notes":"[link url=\"https://sevenseasentertainment.com/series/monster-girl-doctor//\"]Read the Monster Girl Doctor light novels, available from Seven Seas Entertainment![/link]","is_mature":false,"seo_title":"","audio_locale":"ja-JP","images":{},"is_dubbed":false,"season_tags":["Sommer-2020"]},{"season_tags":[],"images":{},"is_dubbed":true,"is_simulcast":false,"is_subbed":false,"subtitle_locales":["en-US"],"versions":[{"audio_locale":"ja-JP","guid":"GREXN9JGY","original":true,"variant":""},{"audio_locale":"en-US","guid":"GR0XN0JMY","original":false,"variant":""}],"availability_notes":"","mature_blocked":false,"identifier":"G60XNJW4R|S1","is_mature":false,"season_sequence_number":0,"title":"(EN) Monster Girl Doctor","audio_locales":["en-US"],"maturity_ratings":["TV-14"],"slug_title":"monster-girl-doctor-english-dub","number_of_episodes":12,"is_complete":false,"seo_description":"","channel_id":"crunchyroll","description":"","season_number":1,"seo_title":"","season_display_number":"","audio_locale":"en-US","extended_maturity_rating":{},"id":"GR0XN0JMY","keywords":[],"series_id":"G60XNJW4R"},{"is_simulcast":false,"slug_title":"monster-girl-doctor-german-dub","subtitle_locales":["de-DE"],"versions":null,"audio_locale":"de-DE","is_complete":false,"season_number":1,"series_id":"G60XNJW4R","identifier":"","keywords":[],"title":"Monster Girl Doctor (German Dub)","description":"","is_mature":false,"season_display_number":"","seo_title":"","extended_maturity_rating":{},"channel_id":"crunchyroll","id":"G6NQCJPZM","season_sequence_number":0,"audio_locales":["de-DE"],"availability_notes":"","images":{},"is_dubbed":true,"season_tags":[],"number_of_episodes":6,"mature_blocked":false,"maturity_ratings":["TV-14"],"seo_description":"","is_subbed":false}],"meta":{"versions_considered":false}}

</details>

Hat das etwas mit der neuen API zu tun?


LG LorenorZorro3000

**Comment by hama3254** [comment]
@LorenorZorro3000 Das sollte bereits gefixt sein, ist halt 1:1 das selbe wie die meldung davor.

**Comment by hama3254** [comment]
@Boshouko [`403`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) ist leider immer noch : 

>The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.

**Comment by tormento** [comment]
@hama3254 and other contributors: please keep the discussion in english, so that non german speakers can read and contribute too.

**Comment by AnAppleInABox** [comment]
Why don't you just speak German? You're assuming they no English but some
may not. How are they going to join in the convo? If you're that desperate
use Google translate and guess what they are saying

**Comment by hama3254** [comment]
> > @Boshouko [`403`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) ist leider immer noch :
> > > The HTTP 403 Forbidden response status code indicates that the server understands the request but refuses to authorize it.
> 
> Komisch ist halt nur, dass das auch kommt, nur wenn ich den Downloader offen habe und nichts mache. Weird thing das war vorher noch nie xD

Es kann durchaus sein der der Cookie abläuft, cloudflare macht damit so einiges was ich nicht wirklich verstehe.


> Dann kommt hin und wieder dieser Fehler:
> 
> ![alt text](https://camo.githubusercontent.com/29c116fa8abb5027c27e20a4b7ba38cf710abdbf407018c5104d02f689290950/68747470733a2f2f692e696d6775722e636f6d2f536d6d47496c4e2e706e67)
> 
> ![alt text](https://camo.githubusercontent.com/58b132142a89640cdaea7b3aaf9e20cac39befcaaac81bc4564be3ed598c74be/68747470733a2f2f692e696d6775722e636f6d2f346b6c61664a372e706e67)
> 
> ![alt text](https://camo.githubusercontent.com/f0358a4b0c859620f0cf63e1789f952c4a46d19207932b6626c6c28ed0cb7b25/68747470733a2f2f692e696d6775722e636f6d2f457459447334582e706e67)
> 
> ![alt text](https://camo.githubusercontent.com/06ac679051d0d7a492f9a374c9522d0e9f8a0acb69405ac65f9b0e7dad873f69/68747470733a2f2f692e696d6775722e636f6d2f41574d5a6d416f2e706e67)
> 
> Es wird dann nichts mehr reingeladen (das was bereits im Loader ist, wird fertig gemacht). Wenn man dann auf Cancel drückt und dann erneut auf Download, passiert nichts. Der Downloader muss neugestartet werden.

Naja [`502`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) ist ein server fehler also da läuft dann was schief bei CR, das bringt den Downloader dazu zu glauben er sucht noch nach einer folge obwohl das nicht so ist.

**Comment by hama3254** [comment]
@Boshouko Nothing i can do there...
![grafik](https://user-images.githubusercontent.com/52826614/215320572-fd31fdae-c4d4-4a67-926f-4a44cc099477.png)

**Comment by hama3254** [comment]
@Boshouko Die einstellung ist derzeit nur damit ich für `preferred_audio_language` einen wert habe ohne da stumpf `ja-JP` reinzuschreiben.
![grafik](https://user-images.githubusercontent.com/52826614/216790949-14793b2d-84c9-4f52-a887-5a0e7d357986.png)

Ich kann alternative versionen verarbeiten die daten sind mit der änderung da, ich weiß nur nicht ob ich es soll.
Das ist auch der Grund warum der multi-download alle dubs angezeigt anstatt wie bei CR mit "versteckten" einstellungen etwas auszuwählen.
![grafik](https://user-images.githubusercontent.com/52826614/216791156-152040e7-1e3c-46dd-8c59-724c90256bf4.png)
