### ISSUE TITLE
loading ... infinite

### ISSUE THREAD

**Issue by nunurs89** [hama3254/Crunchyroll-Downloader-v3.0#679]
**Describe the bug**
I am logged into the crunchyroll account but when I click on "download" it loops and displays in the log on the main page "what's going on?: 22/01/2023 15:12:49"
I have the latest version 3.14.0.2 on Windows 11 - 22H2.
I had this problem on the old version too.

**Where does the issue happen?**
 - Platform: Crunchyroll classic
 - Settings ffmpeg 1080p mkv copy,  softsub french and default sulbtitle french, with CR chapters enable or disable
 - Version 3.14.0.2

**Screenshots**
![log](https://user-images.githubusercontent.com/30862104/213920269-87e19e70-9d31-4011-a7ec-7ae4c3daa7e1.png)
![loading](https://user-images.githubusercontent.com/30862104/213920270-037256f7-6f8d-42d3-bee3-2c6ec56c9086.png)

**Comment by hama3254** [comment]
Please only use new urls, i know that there are for some reason not able to add the new ones to there calendar but they simply don't work with any active API.
Valid urls look like this, `https://www.crunchyroll.com/de/watch/GWDU8DZ40/ryoma-and-the-poster-girl` **not this** `https://www.crunchyroll.com/de/by-the-grace-of-the-gods/episode-3-ryoma-and-the-poster-girl-886847`

![grafik](https://user-images.githubusercontent.com/52826614/213926826-d1f4f771-295e-4028-b5e8-d8befae15ea1.png)

**Comment by nunurs89** [comment]
hum yes it's working with this, thank a lot :)
