### ISSUE TITLE
Has CR API changed again??

### ISSUE THREAD

**Issue by johnkennyuk** [hama3254/Crunchyroll-Downloader-v3.0#681]
**Describe the bug**
Id updated to the latest update which worked for 2 days but today its stopped again??

**Where does the issue happen?**
Adding URL's to the app,

 - Platform: [CR Beta]
 - Settings [FFMPEG Copy, Dubbed no hardsubs or subs]
 - Version [e3.14.0.1]

**Screenshots**
![Screenshot 2023-01-24 015826](https://user-images.githubusercontent.com/64958468/214197817-b1b1c5c0-920a-485c-9fd1-c9e1d276e061.png)

![Screenshot 2023-01-24 015851](https://user-images.githubusercontent.com/64958468/214197831-671cf08f-4738-499a-a0b7-79deeff6f07c.png)

![Screenshot 2023-01-24 015908](https://user-images.githubusercontent.com/64958468/214197847-af191e16-248b-4737-a1ba-04632ccf08e1.png)

**Additional context**
It will get to the language dropdown window but its not  how it should be?

**Comment by hama3254** [comment]
Please check out the [`v3.14.0.2`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14) and see if that solves the issue.

**Comment by FX-Drouard** [comment]
Same error for me with latest version

**Comment by FX-Drouard** [comment]
(settings: mkv, copy , french softsub no hardsub, default softsub: french)

**Comment by hama3254** [comment]
@FX-Drouard I am unable to recreate the issue with [v3.14.0.2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14).
![grafik](https://user-images.githubusercontent.com/52826614/214293561-b76ca1f9-50c8-454a-a6fe-fff068aa2ca1.png)

**Comment by FX-Drouard** [comment]
Oh sorry, I didn't see the new zip on the release (because I just check if new tag was released) It's working

**Comment by johnkennyuk** [comment]
> Please check out the [`v3.14.0.2`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14) and see if that solves the issue.

Your a star works again. keep up the magnificent work!!!
