### ISSUE TITLE
Some downloads are stuck at 0%

### ISSUE THREAD

**Issue by alll4m** [hama3254/Crunchyroll-Downloader-v3.0#683]
All episodes of S4 - One Piece: Water 7 (207-325), with the exception of some episodes, are stuck at 0% when downloading.
<img width="673" alt="Screenshot_2" src="https://user-images.githubusercontent.com/123755657/215130371-0a02ac32-8da3-40cf-8225-cf85f8e280fe.png">
<img width="674" alt="Screenshot_1" src="https://user-images.githubusercontent.com/123755657/215130395-ca113dda-e47a-4dbc-8f4e-bad56cdaad8c.png">

**Comment by hama3254** [comment]
i would need the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) to know the issue there.

**Comment by alll4m** [comment]
> i would need the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) to know the issue there.


27/01/2023 17:59:10 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/index-v1-a1.m3u8?res=1920x1080&Expires=1675025957&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9kODk0NWFhZjE0ZTU0YTJkOWZhMDVmYmU2YmU0NzE5ZS9hc3NldHMva254eWptMWFtZG1jMG5xXzE5NjMwNzMubXA0L2luZGV4LXYxLWExLm0zdTg~cmVzPTE5MjB4MTA4MCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY3NTAyNTk1N319fV19&Signature=h8EwCfIJLIl45k4gZAEJz60AHgw7rutso6HcfyQQ4pctg8qCda2Y8dn-XLe7dVnzbBOUF-trLwnU84XVxLsE-VrAsj~KDd6Z6rTdo5NS9MzQv1~l8AdIyhgsFnXZDfS6QvWlxa7BJIHxPlE-yavvs-jTBaWe1PbgYxg6H4zXnvhDZzdLc5gy8MhdTFJ-QkX82oB5-ZFcPL9190xnlY2frEBiYWlx7o4X1i3A3Zcw84ng9ieW4N2m~BiwAkyLjkvhRIQmtirSy1VyvlDST3pPCAR6BrCrcYl4oqzDPLBwDchH3Gc0GMwP6XNE9sO-GbKftmUd-xR1ONP4eFmRfquLtA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA" -c copy -c:a copy -bsf:a aac_adtstoasc "C:\Users\Alam\Documents\One Piece\Season 4\One Piece Season 4 Episode 208.mp4"

27/01/2023 17:59:10 ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
27/01/2023 17:59:10   built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
27/01/2023 17:59:10   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
27/01/2023 17:59:10   libavutil      57. 28.100 / 57. 28.100
27/01/2023 17:59:10   libavcodec     59. 37.100 / 59. 37.100
27/01/2023 17:59:10   libavformat    59. 27.100 / 59. 27.100
27/01/2023 17:59:10   libavdevice    59.  7.100 / 59.  7.100
27/01/2023 17:59:10   libavfilter     8. 44.100 /  8. 44.100
27/01/2023 17:59:10   libswscale      6.  7.100 /  6.  7.100
27/01/2023 17:59:10   libswresample   4.  7.100 /  4.  7.100
27/01/2023 17:59:10   libpostproc    56.  6.100 / 56.  6.100
27/01/2023 17:59:10 [https @ 000001639c355fc0] No trailing CRLF found in HTTP header. Adding it.
27/01/2023 17:59:10 [hls @ 000001639c355a40] Skip ('#EXT-X-ALLOW-CACHE:YES')
27/01/2023 17:59:10 [hls @ 000001639c355a40] Skip ('#EXT-X-VERSION:5')
27/01/2023 17:59:10 [hls @ 000001639c355a40] Opening 'https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/encryption.key?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:16 [tcp @ 000001639e1ed4c0] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:16 [hls @ 000001639c355a40] Unable to open key file https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/encryption.key?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:16 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-1-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:22 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:22 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-1-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:22 [hls @ 000001639c355a40] Failed to open segment 1 of playlist 0
27/01/2023 17:59:22 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-2-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:27 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:27 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-2-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:27 [hls @ 000001639c355a40] Failed to open segment 2 of playlist 0
27/01/2023 17:59:27 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-3-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:33 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:33 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-3-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:33 [hls @ 000001639c355a40] Failed to open segment 3 of playlist 0
27/01/2023 17:59:33 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-4-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:38 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:38 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-4-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:38 [hls @ 000001639c355a40] Failed to open segment 4 of playlist 0
27/01/2023 17:59:38 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-5-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:44 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:44 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-5-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:44 [hls @ 000001639c355a40] Failed to open segment 5 of playlist 0
27/01/2023 17:59:44 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-6-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:49 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:49 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-6-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:49 [hls @ 000001639c355a40] Failed to open segment 6 of playlist 0
27/01/2023 17:59:49 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-7-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 17:59:54 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 17:59:54 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-7-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 17:59:54 [hls @ 000001639c355a40] Failed to open segment 7 of playlist 0
27/01/2023 17:59:54 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-8-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 18:00:00 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 18:00:00 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-8-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 18:00:00 [hls @ 000001639c355a40] Failed to open segment 8 of playlist 0
27/01/2023 18:00:00 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-9-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 18:00:05 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 18:00:05 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-9-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 18:00:05 [hls @ 000001639c355a40] Failed to open segment 9 of playlist 0
27/01/2023 18:00:05 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-10-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading
27/01/2023 18:00:11 [tcp @ 000001639c40df00] Connection to tcp://prod.gccrunchyroll.com:443 failed: Error number -138 occurred
27/01/2023 18:00:11 [crypto @ 000001639e1f1700] Unable to open resource: https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-10-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg
27/01/2023 18:00:11 [hls @ 000001639c355a40] Failed to open segment 10 of playlist 0
27/01/2023 18:00:11 [hls @ 000001639c355a40] Opening 'crypto+https://prod.gccrunchyroll.com/evs3/d8945aaf14e54a2d9fa05fbe6be4719e/assets/knxyjm1amdmc0nq_1963073.mp4/seg-11-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvZDg5NDVhYWYxNGU1NGEyZDlmYTA1ZmJlNmJlNDcxOWUvYXNzZXRzL2tueHlqbTFhbWRtYzBucV8xOTYzMDczLm1wNC8&Expires=1675025957752&KeyName=cdn-prod-keyset&Signature=pwUyUXScPI8c_x5C51xLiDBS_xa3J0VWXWbgtSkF5q6x4iMJQOSmXI6Li8bJ6U4ByGXed4xK-LTrgLtBaBAiCg' for reading

**Comment by alll4m** [comment]
> i would need the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) to know the issue there.

[log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10523162/log.txt)

**Comment by hama3254** [comment]
The video libary can not connect to the server, you can try using the `Hybrid Mode` which lets the downloader handle the actual download by caching the stream.
If that does not work then the [CRD-Log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log) might have some more usefull data in it.
![grafik](https://user-images.githubusercontent.com/52826614/215271544-d2dc977d-2d0c-48ac-b7a9-b02416c1a68a.png)

**Comment by alll4m** [comment]
unfortunately it didn't work.

[CRD-Log in ffmpeg download mode.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10540192/CRD-Log.in.ffmpeg.download.mode.txt)

[CRD-Log in hybrid download mode.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10540193/CRD-Log.in.hybrid.download.mode.txt)

strange is that always the same links give problem, several others occur normally.

**Comment by hama3254** [comment]
If google tranlates this correctly

```
System.Net.WebException: Impossível conectar-se ao servidor remoto ---> System.Net.Sockets.SocketException: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu 34.104.32.36:443

```
then this would mean that is a network ot server issue and i don't see anything i can do here. 
```
System.Net.WebException: Unable to connect to remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected component did not respond
correctly after a period of time or the established connection failed
because the connected host did not respond 34.104.32.36:443
```

**Comment by alll4m** [comment]
The problem was with my network itself. I used a vpn and it downloaded normally, thanks for the help.
