### ISSUE TITLE
fix I have to re-enter my username and password every time

### ISSUE THREAD

**Issue by srmdnadem** [hama3254/Crunchyroll-Downloader-v3.0#684]
My issue is that when I exit your program after logging in, I have to re-enter my username and password upon returning. Please fix this issue, as I need the program to remember my login information.

**Comment by hama3254** [comment]
This has usually two causes of which i can fix none.
Either CR itself refuses the Cookies saved by the browser or the browser itself does clear the cookies for some reason.
I also don't have this issue so i would guess that the first one is the more likely option.

**Comment by srmdnadem** [comment]
> This has usually two causes of which i can fix none. Either CR itself refuses the Cookies saved by the browser or the browser itself does clear the cookies for some reason. I also don't have this issue so i would guess that the first one is the more likely option.

I accepted the cookies and fixed the issues now. Thank you.
