### ISSUE TITLE
Not start downloading error 403

### ISSUE THREAD

**Issue by ManuelDiazIsaza** [hama3254/Crunchyroll-Downloader-v3.0#685]
**Describe the bug**
When im downloading a season from any anime, download stop and i need close and reopen CR Downloader and start from the last episode

Is posible you can do something like a retry, sometimes i leave the computer and when i come back not download anything

**Where does the issue happen?**
 - Platform:Crunchyroll 
 - Settings
 - Version 3.14.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/37357573/215662240-b0b8da1a-d63b-483a-a285-db7e52b3f631.png)

![image](https://user-images.githubusercontent.com/37357573/215662692-81c2ec08-0c31-421e-880a-9dd12f7a988d.png)

**Additional context**

**Comment by hama3254** [comment]
i assume it is the same as here were probably the cookies or token expire.

>> > sometimes this error occurs:
>> > ![alt text](https://camo.githubusercontent.com/d7cead79e0cb03cbca2a5ff6ce45998127ac6ee5c632cf8e9cc45bdb597c46f7/68747470733a2f2f692e696d6775722e636f6d2f53374b527a38582e706e67)
>> > ![alt text](https://camo.githubusercontent.com/294dc731c32e38e8f7a0f3af3a3e1729e21acc055c26cb172e039c613dc0573d/68747470733a2f2f692e696d6775722e636f6d2f637741514f6f692e706e67)
>> 
>> @Boshouko how often does that happen ?
>
>Im not sure maybe every 30 mins or 1 hour

_Originally posted by @Boshouko in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/677#issuecomment-1399332528_

the next version has some changes in place to help with this issue.
