### ISSUE TITLE
Téléchargement impossible

### ISSUE THREAD

**Issue by lilian1502** [hama3254/Crunchyroll-Downloader-v3.0#686]
Bonjour,

Je n'arrive pas à télécharger des épisodes

![Capture](https://user-images.githubusercontent.com/124058780/215774408-9369ccf0-d766-44ac-b294-32fecd56a10b.PNG)

voici le message d'erreur

Merci d'avance pour votre aide

**Comment by lilian1502** [comment]
![image](https://user-images.githubusercontent.com/124058780/215774656-58876c0c-3f65-4f27-9936-c92941d467ee.png)

**Comment by hama3254** [comment]
not the real solution but ignoring it with [--insecure](https://curl.se/docs/manpage.html#-k) should work.
![grafik](https://user-images.githubusercontent.com/52826614/209685530-69bd918d-7170-4ed3-a576-8c5a4c5db820.png)
