### ISSUE TITLE
Queue halts until the browser window is refreshed?

### ISSUE THREAD

**Issue by johnkennyuk** [hama3254/Crunchyroll-Downloader-v3.0#687]
**Describe the bug**
ive been noticing with long queues of videos that now and then the queue halts without any notifications apart from the loading status, ive found that if the browser window is either restarted or just refreshed the queue resumes although it appears to skip a video of which im assuming may of caused the halt?  any suggestions?

**Where does the issue happen?**
 - Platform: CR
 - Settings Ffmpeg copy, 
 - Version 3.14.1

**Screenshots**
<details>
  <summary>see attachments</summary>

  ![Screenshot_2023-02-03-17-35-20-95_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/64958468/216670127-193c473b-966e-4ee0-b281-0f272ad3036c.jpg)
Above is when the queue halts

![Screenshot_2023-02-03-17-35-31-95_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/64958468/216670233-93b7d98a-540c-4783-b50e-a53e0e09fc62.jpg)
above is after refreshing the browser window 

![Screenshot_2023-02-03-17-36-05-02_2665fb67b16260a8d818298cef8dc107](https://user-images.githubusercontent.com/64958468/216670317-78d0b4dc-c864-4a3d-9181-9db2e75abb60.jpg)
above is where it parses through 30 urls then resumes the queue skipping an episode

</details>

**Additional context**
i have tried changing the settings main error handling field from 0 to different numbers but it didn't stop the occasional halts i mentioned.

**Comment by hama3254** [comment]
In short it skipped Episode 36 while you where doing something inside the build-in browser?
For me to know what the downloader did there i would need the [Log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log).

**Comment by johnkennyuk** [comment]
FYI the built in browser is only ever used for coping the url and then it just stays open or sometimes closed either way on latest queue its stopped on multiple episodes from multiple series.

where do i find the log you require?

**Comment by johnkennyuk** [comment]
[000281.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10609559/000281.log)

Would this be it? its the latest .log file in the dir the apps in?

**Comment by johnkennyuk** [comment]
[CR.LOG](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/10611409/CR.LOG)

FYI this session may contain the redownloads of the skipped Ep's, the last 9 to be exact were skipped from the queue freeze or halt.

Scrapped Princess was the last series on the queue with E14 being what it originally skipped.

**Comment by hama3254** [comment]
From a quick look it seems that you did over 200 download, this is just to much to look through and far more than the downloader is supposed to download.
I think of a session with about a season (12 to 14 episodes) since you are unlikely to watch more than that on a day.

![grafik](https://user-images.githubusercontent.com/52826614/216838201-1e66b312-246b-48d4-8ff6-ac39e0461053.png)

**Comment by johnkennyuk** [comment]
sorry i missed this reply, it seems the latest build is slightly better as now it prompts 403 error popups which look like CR rate limits.  FYI your app is the best app I have used so far for ripping from CR
