### ISSUE TITLE
Missing resolution for a specific episode

### ISSUE THREAD

**Issue by Kyouma95** [hama3254/Crunchyroll-Downloader-v3.0#688]
**Describe the bug**
The downloader cant seem to find the resolution for a specific Episode of "Reborn". Every other Episode worked without any issue.
The resoulution missing is the 480p version. You can see that in the screenshots.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: Hardsub, hybrid mode
 - Version: 3.14.1

**Screenshots**
https://imgur.com/Pf9nR4T
https://imgur.com/eQC7x2V

**Additional context**
Out of the 203 Episodes, only episode 46 has this issue.

**Comment by hama3254** [comment]
This might be a temporary issue or some [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) issue.
It works as intended for me.
![grafik](https://user-images.githubusercontent.com/52826614/216813516-8757b269-8f17-4d66-aaba-10814ee2a08e.png)

**Comment by Kyouma95** [comment]
Did you do it with Hardsubs? Just tried it and it wont work with hardsubs, but it will work with sofstubs or no subs at all.
Is it the same on your end?

**Comment by hama3254** [comment]
>Did you do it with Hardsubs? 

I did not think about that and it seems that with hardsubs 360p is the best what CR offers.
![grafik](https://user-images.githubusercontent.com/52826614/216824863-199fe370-8501-4bad-8a5d-27cd551afc56.png)

**Comment by Kyouma95** [comment]
So it´s not just me, ok. I can work with Softsubs, so i will close this. Thank you!
