### ISSUE TITLE
downloading doesn't work

### ISSUE THREAD

**Issue by IkeasIkea** [hama3254/Crunchyroll-Downloader-v3.0#69]
![Crunchyroll_Downloader_IThrOjsN7w](https://user-images.githubusercontent.com/60763280/95806888-d457f180-0cd6-11eb-946d-e9b178848ea3.png)
everytime i try to download a konosuba episode, this is what happens

**Comment by hama3254** [comment]
From the timestamps I assume you pressed 'yes' for the episode `https://www.crunchyroll.com/konosuba-gods-blessing-on-this-wonderful-world/episode-2-an-explosion-for-this-chunibyo-780942`.
This would mean I got the error message `System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest` which tells me it's a random error and no programming issue.  
But I take a look at later (is 6am in central europe right now 🤫)

**Comment by hama3254** [comment]
I can not see a problem from my side.
Please try it again, maybe crunchyroll had just some sort of issue.

**Comment by GAIJIN-EpH** [comment]
unfortunately i also have the same problem.

**Comment by hama3254** [comment]
> unfortunately i also have the same problem.

I just got one Bug report since yesterday so if you pressed yes then `System.Net.WebException: Error en el servidor remoto: (502) Puerta de enlace no vlida.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest`  is your error.
And that's again some server side error that I just can not fix.
If you did not press yes then I have no way to tell what's wrong for you.

**Comment by hama3254** [comment]
> ok, i will try to do something here, if it works out i'll come back here to make a report.

if you tryed `https://www.crunchyroll.com/de/chain-chronicle-the-light-of-haecceitas-/episode-5-snowy-mountain-screams-728835` several times then i would suggest you check your download path 
`System.IO.PathTooLongException: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollstndig qualifizierte Dateiname muss krzer als 260 Zeichen und der Pfadname krzer als 248 Zeichen sein.
   bei System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.InternalGetDirectoryName(String path)
   bei System.IO.Path.GetDirectoryName(String path)
   bei Crunchyroll_Downloader.Main.GrappURL() in D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\Main.vb:Zeile 1222.`
