### ISSUE TITLE
Hide destination subdirectories

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#691]
Would be possible to have a way to delete the subfolder history present in the Add video window?

After months of use, it becomes so cluttered.

**Comment by tormento** [comment]
Ah, ok ;)

I change my request to: please add a switch to hide/show directories. I have too many and it's a mess.

**Comment by hama3254** [comment]
I don't see why you would want to hide all since if you don't use it than you also don't change the value.
Well i added it like this, show or hide all and some common time frames.
![grafik](https://user-images.githubusercontent.com/52826614/217810608-22a7d2b7-2914-472a-9884-0c2050af33e4.png)

**Comment by tormento** [comment]
Great, thank you!

**Comment by hama3254** [comment]
[v3.14.3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.14.3) is now here!
