### ISSUE TITLE
Download multiple dubs at once

### ISSUE THREAD

**Issue by ItsLuk** [hama3254/Crunchyroll-Downloader-v3.0#693]
Currently im downloading both the original and german dub, and merge both audio streams by hand. I like having the original audio but also my native language.

Could you make it possible to download multiple languages at once and merged into a single mkv file? Just like the softsubs? I don't know how easy that would be, if it is possible at all.

**Comment by ItsLuk** [comment]
I just saw an older issue.. #538

**Comment by hama3254** [comment]
I would be able to get all the required data from the current Crunchyroll website, but the processing gets a lot more complicated.

Without going into to much details i would need to get a `main` video from CR and then look up another stream to get a 2nd video stream to get it's audio. I can workaround the fact that this would be a full video again by using a lower resolution to reduce the download size. But the thing i fear the most is the `ffmpeg` stuff i would have to do, it get's already overwhelming with merged subtitles and metadata for both audio and subtitles.

**Comment by ItsLuk** [comment]
I see i see, dont worry. My method also works :)
Thank you.
