### ISSUE TITLE
Error - Getting VideoJson data

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#699]
I keep getting this error even already ticked 'add "--insecure" to curl requests.

![image](https://user-images.githubusercontent.com/4635825/219922557-9b395659-f0c5-45c4-8ac0-d48972fa0203.png)

Also, if this error happaned all my queue list will gone and need to put the link again. Possible to put the queue link list in temp folder or somehing?

**Comment by hama3254** [comment]
>I keep getting this error even already ticked 'add "--insecure" to curl requests.

the `--insecure` is only there to ignore SSL/TLS issues and has no effect on the response of the CR servers which is the issue here.

>Also, if this error happaned all my queue list will gone and need to put the link again.

Any info how this clears the queue? do every episodes error out or is it just gone?

>Possible to put the queue link list in temp folder or somehing?

Probably, but the downloader is desingt to download the episodes you want to watch so 12 per session should not be to hard to add again.

**Comment by x3inspire** [comment]
> > I keep getting this error even already ticked 'add "--insecure" to curl requests.
> 
> the `--insecure` is only there to ignore SSL/TLS issues and has no effect on the response of the CR servers which is the issue here.
> 
> > Also, if this error happaned all my queue list will gone and need to put the link again.
> 
> Any info how this clears the queue? do every episodes error out or is it just gone?
> 
> > Possible to put the queue link list in temp folder or somehing?
> 
> Probably, but the downloader is desingt to download the episodes you want to watch so 12 per session should not be to hard to add again.

Example all link is 50 link, 20 link already completed download. The link 21 start show those error, the program keep stuck and not downloading or anything. I had to close the program and open back. So all link in queue gone. And fyi i added more than 100 link per time.

**Comment by hama3254** [comment]
>the program keep stuck and not downloading or anything. 

it only softlocks then, the error makes the downloader exit the extractor but does not set the extractor to be ready for the next episode.
