### ISSUE TITLE
N paar vorschläge für den Final Release (4.0), da jetzt alles Bugfrei ist.

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#7]
A: Bau doch sowas ein das der Automatisch ohne Usereingabe den Cookie setzt befor das Programm richtig startet und nur wenn er den Us Cookie gesetzt bekommt lädt das Programm sonst kommt n Fehler und es schließt sich. 

B: Das der US Cookie Bugabuse nicht so lange dauert und 2tens sich das Fenster nicht öffnet sondern einfach die Bestätigung obs funktioniert hat oder nicht.

C: Das man den Maximalen Download Speed auswählen kann. (Automatisch ist der immer auf Max)

D: Nen Link Kopier Button im Browser das man sich den Link von den Anime leichter Kopieren Kann.

E: Nen Button der erscheint, wenn nen Bug / Error kommt der Automatisch hier n Ticket Erröfnet mit dem Error als Titel und n Screenshot als Beschreibung, das machts für dich einfacher Bugs zu fixend die du vielleicht garnicht so mitbekommst.

**Comment by hama3254** [comment]
> A: Bau doch sowas ein das der Automatisch ohne Usereingabe den Cookie setzt befor das Programm richtig startet und nur wenn er den Us Cookie gesetzt bekommt lädt das Programm sonst kommt n Fehler und es schließt sich.

Warum? ist nicht so das jeder einen US Cookie will bzw. braucht, manche sachen wie z.b. nicht englische Dubs gehen dann u.a. nicht einmal.

> B: Das der US Cookie Bugabuse nicht so lange dauert und 2tens sich das Fenster nicht öffnet sondern einfach die Bestätigung obs funktioniert hat oder nicht.

das fenster ist als user feedback offen damit die sehen es passiert was, und es dauert auch nichtmal 10 sekunden etwas geduld sollte man schon haben.

> C: Das man den Maximalen Download Speed auswählen kann. (Automatisch ist der immer auf Max)

ich wünschte ich könnte daran irgendwas machen, geht aber einfach nicht

> D: Nen Link Kopier Button im Browser das man sich den Link von den Anime leichter Kopieren Kann.

in welchem Browser ? der normale oder vom Downloader?  in die adresszeile zu klicken und CTRL + a dann CTRL + C  und dann im Downloader CTRL +V sollte ja einfach genug sein.
 
> E: Nen Button der erscheint, wenn nen Bug / Error kommt der Automatisch hier n Ticket Erröfnet mit dem Error als Titel und n Screenshot als Beschreibung, das machts für dich einfacher Bugs zu fixend die du vielleicht garnicht so mitbekommst.

hab sowas ähnliches schon länger drinnen, ich hab vorhin erst mit dem pre-release einen bug gefixt das die Fehlererkennung wieder funktionieren sollte  
Demo: https://youtu.be/SgFcS2wwO8E?t=47
erhobene daten :https://abload.de/img/crdfeedbackq6jb2.png

**Comment by KoroFX** [comment]
> D: Nen Link Kopier Button im Browser das man sich den Link von den Anime leichter Kopieren Kann.
> 
> in welchem Browser ? der normale oder vom Downloader? in die adresszeile zu klicken und CTRL + a dann CTRL + C und dann im Downloader CTRL +V sollte ja einfach genug sein.
Der eingebaute vom Downloader, es gibt keine Adresszeile in den eingebauten das ist ja das problem.
