### ISSUE TITLE
A way to download more?

### ISSUE THREAD

**Issue by RavnHH** [hama3254/Crunchyroll-Downloader-v3.0#70]
Hi! I like your work and it works very well! I just want to ask, is there a way to make a batch, or else to download more than 1 anime, after the other one is finished from crunchyroll?

**Comment by hama3254** [comment]
The simplest way would be to use the Firefox add-on : https://youtu.be/ZHCH3rNWYS8

**Comment by x3inspire** [comment]
If using Firefox add on, and in the same time we are using VPN with Firefox, can the downloader download the video?

**Comment by RavnHH** [comment]
Sorry but the fowarding still works. There is no Java link like in your video. And i get an Error when using it:

Error: Connection failed

Firefox cannot establish a connection to the server under 127.0.0.1.

The website may be temporarily unavailable, please try again later.
If you cannot access another website either, please check your network / internet connection.
If your computer or network is protected by a firewall or proxy, please ensure that Firefox is allowed to access the Internet.

I'm not using a VPN and Adblockers are deactivated. I dont use NoScript if that is a question.

**Comment by hama3254** [comment]
> Firefox cannot establish a connection to the server under 127.0.0.1.

You need to enable the http server in the settings of the downloader.

**Comment by hama3254** [comment]
> If using Firefox add on, and in the same time we are using VPN with Firefox, can the downloader download the video?

That depends, if you are on crunchyroll and on the video site then the add-on just sends the entire html website and it should work.
If you on an anime overview then it will not work, the add-on just gives the urls to the downloader.
If funimation it's always the case that the downloader only receives the URLs for the download

**Comment by RavnHH** [comment]
> > Firefox cannot establish a connection to the server under 127.0.0.1.
> 
> You need to enable the http server in the settings of the downloader.

Ok that works. But when i start to Download, this happens: 
![Screenshot 2020-10-13 150604](https://user-images.githubusercontent.com/72796068/95864499-c0a79c00-0d65-11eb-9d0b-2790fb88cc2c.jpg)

![2](https://user-images.githubusercontent.com/72796068/95864534-cbfac780-0d65-11eb-9bda-76cd45d6f2e9.jpg)


When i paste the URL, then i get to choose the episodes per dropdown again. It doesnt work like in your video someway.

**Comment by RavnHH** [comment]
Everything works perfect for me now! Would just be nice to have the Addon for chrome. But i think it doesnt work. Dont matters, it works like it is!!!

Big thanks!!!

**Comment by hama3254** [comment]
> Would just be nice to have the Addon for chrome

i see what i can do, some stuff seems to be not as good as in firefox like chrome just ignores the answer from the downloader after urls got added and just does nothing https://www.youtube.com/watch?v=IDrVxkMpWV0
i build in the status display otherwise you would see nothing :/

**Comment by hama3254** [comment]
@RavnHH The Chrome add-on is now available with v3.5.4 https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.5.4 
you just need to install it manual :

1. open chrome://extensions/

2. enable developer mode

3. load unpacked add-on (the folder with the "manifest.json")

![grafik](https://user-images.githubusercontent.com/52826614/96129394-dd270e00-0ef6-11eb-8936-8a76b0cee92b.png)

**Comment by TaigaChiquita** [comment]
im getting the same problem in chrome where i try to add stuff to queue but it just wont do it and i hace to download 1 by one, also i figured out that in some cases you would have to start CRDWL as administrator to make the http server work or be recognized by the Chrome extension

**Comment by hama3254** [comment]
> im getting the same problem in chrome where i try to add stuff to queue but it just wont do it and i hace to download 1 by one

i'm sorry but i'm not sure on which problem you revering to, is it my video? that does work to add the number goes from 28 to 32 but chrome just does not care to display the answer from the webserver like firefox does. 

> i figured out that in some cases you would have to start CRDWL as administrator to make the http server work or be recognized by the Chrome extension

please check i there is anything in the server console 
you can find it at the bottom after pressing the line :

![grafik](https://user-images.githubusercontent.com/52826614/96183639-7249f700-0f37-11eb-89c8-64de5b649568.png)

**Comment by TaigaChiquita** [comment]
![image](https://user-images.githubusercontent.com/8277764/96187388-4b79c980-0f13-11eb-85a2-341187fefe79.png)
i was refering to this where i try to add stuff to the queue so it downloads multiple videos but wont start downloading anything and regarding to the http server not starting or not being recognized by the app, for some reason now its working just fine without needing to start the program as admin

**Comment by hama3254** [comment]
> Edit: i didnt realised that i had to look on the add download button so the downloads start, my bad, btw nice program now its working without any problems

With the add-on this might be a bit to good hidden.
In the past the same queue was used for the case that you enter a URL manual while the max current download was reached so had the add window open.

**Comment by hama3254** [comment]
i guess everything work now here so i close this.
