### ISSUE TITLE
unable to get master.m3u8

### ISSUE THREAD

**Issue by Shouyadra** [hama3254/Crunchyroll-Downloader-v3.0#702]
moin moin

hab hier ein kleines problem

wenn ich versuche https://www.crunchyroll.com/de/series/GRDKVP34Y/tsurune runterzuladen kommt bei manchen Folgen eine Fehlermeldung:

![alt text](https://i.imgur.com/ZmewWje.png)

![alt text](https://i.imgur.com/Rf59TEw.png)

Danke für die Aufmerksamkeit 

edit: scheint teilweise random zu sein. wartet man paar mins dann gehts - dafür gehen dann andere wieder nicht :D

**Comment by hama3254** [comment]
>edit: scheint teilweise random zu sein. wartet man paar mins dann gehts 

ist scheinbar das selbe auf deren webseite, daraus würde ich schliesen das die irgendwelche probleme haben...

![grafik](https://user-images.githubusercontent.com/52826614/222454995-1ff657d0-0f14-4068-a0aa-79355b74782f.png)

**Comment by Shouyadra** [comment]
I see

Stimmt Error SHAK-1002 wurde neulich bei Crunchyroll schonmal irgendwo erwähnt. 
Dachte Crunchy hätte da wieder eine Kleinigkeit geändert.

Dann nevermind und danke =)

**Comment by Shouyadra** [comment]
Error SHAK-1002 - Crunchyroll Error
