### ISSUE TITLE
403

### ISSUE THREAD

**Issue by bybpow** [hama3254/Crunchyroll-Downloader-v3.0#703]
**Describe the bug**
Since yesterday I got a lot of random 403 in any download.

**Where does the issue happen?**
 - Platform: Crunchyroll 
 - Settings Softsubs,
 - Version 3.14.2

**Screenshots**
![2023-03-02 18_24_47-Add Video](https://user-images.githubusercontent.com/62562341/222505087-ea3a57bd-01cc-4057-ae8c-6d7829a129c2.png)

**Additional context**
It happens with or without VPN.

**Comment by hama3254** [comment]
i checked that just a view hours ago due to #702 which gave me the same issue on there own website... so i honestly don't know what i should or can do about this.
![grafik](https://user-images.githubusercontent.com/52826614/222454995-1ff657d0-0f14-4068-a0aa-79355b74782f.png)

**Comment by bybpow** [comment]
So maybe a CR problem?

**Comment by Sacred-Shadow** [comment]
Believe Cloudflare strikes. If the error at CR is 403, as an example, the search on Google also does not work. 

If you change the IP via VPN ... comes with the next call on CR a Cloudflare Captcha. Can it be that the downloader triggers a detection at Cloudflare and is therefore blocked?
