### ISSUE TITLE
Add Subtitle Type to Filename when Downloading to Avoid Overwriting Files

### ISSUE THREAD

**Issue by MaxMFC** [hama3254/Crunchyroll-Downloader-v3.0#705]
Hello,

I would like to request a feature to add the subtitle type to the filename of subtitles. Currently, when merging multiple audio streams, the naming convention for sub and cap versions is the same, which leads to files being overwritten.

To avoid this, I suggest adding the subtitle type to the filename along with the language. For example:

    Subtitles: "[S01 E01] Season 1 Episode 01 The Last One To Your Eternity.sub.eng.ass"
    Closed Captions: "[S01 E01] Season 1 Episode 01 The Last One To Your Eternity.cap.eng.ass"

I have attached a picture for reference.

Thank you for considering my request.

![Screenshot 2023-03-07 223330](https://user-images.githubusercontent.com/113120273/223557961-56832ff6-0b78-4700-bb01-d2f0723a7404.png)

**Comment by hama3254** [comment]
> the naming convention for sub and cap versions is the same, 

I assume that you refer with `cap` to subtitles of dubbed episodes and the data are the same so it gets processed the same.

![grafik](https://user-images.githubusercontent.com/52826614/223756028-617d376d-637f-4418-a478-a3ae508c9cbe.png)


This should not be an issues downloader just ignore subtiles if it merges the audio stream.

This means you have to download them in `Subtitle only` mode where you can use the [`++` modifier](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/645) to add the `.cap` or `.sub`

![grafik](https://user-images.githubusercontent.com/52826614/223768430-752779a7-3851-4781-9ded-7191cc21f872.png)

also the `.ger` and `.eng` could be added by chaning the options to include the `ISO639-2-Codes` for all subtitles
![grafik](https://user-images.githubusercontent.com/52826614/223771979-5ba9d6f1-9c7d-4e4a-a19c-dddc8e245528.png)
