### ISSUE TITLE
TMP File Not Deleted After Merging Audio with Existing Files on Crunchyroll

### ISSUE THREAD

**Issue by MaxMFC** [hama3254/Crunchyroll-Downloader-v3.0#706]
Hello,

I have noticed a bug when using the "Merge Audio with existing files" feature on Crunchyroll. After downloading a second audio stream, the tmp file is not being deleted. This issue is occurring on version V3.14.5.1.

I have attached a screenshot for reference.

Thank you for your attention to this matter.

![Screenshot 2023-03-07 225139](https://user-images.githubusercontent.com/113120273/223561451-f18226d5-5773-47a5-ac41-31f48eecf5bf.png)

**Comment by hama3254** [comment]
I did that on purpose. 
I released v3.14.4 with that feature as test version and i did not get any feedback.
There are some issues and design choices to be made with different dubs.
Some are limited by the programming while other behaviors are just opinions how it is the best.

For now i would just suggested to remove them by hand.
