### ISSUE TITLE
Cloudflare loop

### ISSUE THREAD

**Issue by lawliet675** [hama3254/Crunchyroll-Downloader-v3.0#707]
Im having this issue:

![2023-03-08](https://user-images.githubusercontent.com/11916495/223901451-2578d638-d2dc-4e1c-a3b9-61d56b997ca3.png)

![2023-03-08 (1)](https://user-images.githubusercontent.com/11916495/223901472-679a3edb-8c0e-44f1-8c1c-eaa1f3a5fa9b.png)

I can´t open just the main page of crunchyroll. i don´t know why and it stuck at that page in a loop.

I'm using this version "Crunchyroll-Downloader-v3.14.0.2" 

I hope that tomorrow will be ok, but it's weird this issue.

To clarify im not over a strange vpn or proxy 

Thanks!

**Comment by hama3254** [comment]
I can not tell why this might happen, this problem is either from cloudflare, your Internet or very unlikely the webbrowser.
I can do nothing to all 3 cases.
