### ISSUE TITLE
I keep getting Newtonsoft error

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#708]
![image](https://user-images.githubusercontent.com/4635825/224050878-76428d6b-7cfd-4e10-8b2b-b04ea32af972.png)

Hi, what error is this?

**Comment by hama3254** [comment]
The Json file CR gave out seems invalid.
did all messages get there at the same time?

**Comment by x3inspire** [comment]
Now not getting those error anymore, mostly this error always happen.

![image](https://user-images.githubusercontent.com/4635825/226110833-74e041e5-6fe2-46a9-bdcb-445f61aae4fe.png)

**Comment by hama3254** [comment]
This is a known issue and can not be fixed.
