### ISSUE TITLE
Can't open the program

### ISSUE THREAD

**Issue by Zackxs3** [hama3254/Crunchyroll-Downloader-v3.0#71]
Every time I try to open this program I get an error saying "---------------------------
Crunchyroll Downloader
---------------------------
System.BadImageFormatException: You have tried to open a program with an incorrect format. (HRESULT exception: 0x8007000B)

   en Gecko.Xpcom.Alloc(IntPtr size)

   en Gecko.nsAString..ctor()

   en Gecko.nsAString..ctor(String value)

   en Gecko.Xpcom.Initialize(String binDirectory)

   en Crunchyroll_Downloader.My.MyApplication.OnStartup(StartupEventArgs eventArgs) en D:\Projecte\Crunchyroll Downloader - v3.0-final\Crunchyroll-Downloader-v3.0\Crunchyroll Downloader\ApplicationEvents.vb:line 47

I would really love some help. Thanks in advance

**Comment by hama3254** [comment]
You need to have the x86 version from the `Visual C++ redistributable`  Wich you can find here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Zackxs3** [comment]
> 
> 
> You need to have the x86 version from the `Visual C++ redistributable` Wich you can find here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Thank you very much. I thought the 64 bit version worked with it.
