### ISSUE TITLE
"The download process seems to have crashed" Error

### ISSUE THREAD

**Issue by Elwador** [hama3254/Crunchyroll-Downloader-v3.0#710]
Since no one brought it up yet i wanted to ask if that is a general problem or it is only a problem for me. I keep getting more and more "The download process seems to have crashed" errors after the episodes finished downloading. The logs of the downloads end like this: 

> 15.03.2023 22:13:01 Input #0, hls, from 'H:\Crunchyroll-Downloader\CRD-Temp-File-IeRddXEZBFUINDeV\index.m3u8':
15.03.2023 22:13:01   Duration: 00:23:10.42, start: 0.101000, bitrate: 0 kb/s
15.03.2023 22:13:01   Program 0 
15.03.2023 22:13:01     Metadata:
15.03.2023 22:13:01       variant_bitrate : 0
15.03.2023 22:13:01   Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 24 fps, 24 tbr, 90k tbn
15.03.2023 22:13:01     Metadata:
15.03.2023 22:13:01       variant_bitrate : 0
15.03.2023 22:13:01   Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
15.03.2023 22:13:01     Metadata:
15.03.2023 22:13:01       variant_bitrate : 0
15.03.2023 22:13:01   Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
15.03.2023 22:13:01     Metadata:
15.03.2023 22:13:01       variant_bitrate : 0
15.03.2023 22:13:01 H:\Crunchyroll-Downloader\CRD-Temp-File-IeRddXEZBFUINDeV\mdata.txt: Invalid data found when processing input

I am still using the Version v3.14.4 the first time i encountert this problem was when i tried to download "Free! - Iwatobi Swim Club - Season 3" Season 1 & 2 worked fine. It also happend with some In/Spectre Season 1 episodes that worked fine a couple of weeks ago and now with an episode from "The Last Summoner".

![image](https://user-images.githubusercontent.com/75888166/225446197-1d67f84a-071c-419b-bbe7-8ab326043f14.png)
![image](https://user-images.githubusercontent.com/75888166/225447578-21f8ba5e-403e-4ab0-96a5-7089876c4d2c.png)

**Comment by hama3254** [comment]
The Crunchyroll chapters seems to be invalid in some way.
I am currently unable to work on the downloader but disabling the Chapters in the settings should solve the issue for now.
