### ISSUE TITLE
stuck on Cloudflare page

### ISSUE THREAD

**Issue by ET1982** [hama3254/Crunchyroll-Downloader-v3.0#712]
Hi, until yesterday evening the software was working fine. This morning the softwr's browser is stuck on a Cloudflare page and I cannot download anything. I use the 3.14.2 version.

By the way, crunchyroll.com works perfectly on my Chrome broswser, the problem is only on the Crunchyroll Downloader's browser.
I also tried copying the download URL from Chrome and paste it on Crunchyroll Downloader, but it still doesn't work.

![Immagine](https://user-images.githubusercontent.com/108487686/226094964-fc96097f-cb0e-42ef-9ea3-554104ad7c17.png)

Any idea?

Thanks

**Comment by x3inspire** [comment]
Same

![image](https://user-images.githubusercontent.com/4635825/226095342-a34cd2d2-e552-4a88-a93d-34d44821d5c5.png)

**Comment by ET1982** [comment]
I'm afraid Cruchyroll added a control page on Cloudflare to block downloader softwares...

**Comment by ms-ku** [comment]
Hello
Same to me for some hours. 
In my case a update of Microsoft Edge WebView2 has fixed the problem (but it could also have been coincidental).
Greetings

**Comment by ET1982** [comment]
Unfortunately, I already have Microsoft Edge WebView2

**Comment by ms-ku** [comment]
Hello
for me was an update available. 
Old Vers 1.3.169.31 -> new Vers 1.3.173.49. Old Version must be uninstalled first.
At the moment the DL works with CRD 3.14.3.
Greetings

**Comment by ET1982** [comment]
Hi, you are right. I uninstalled WebView2 and installed the latest version and it works again.
https://developer.microsoft.com/it-it/microsoft-edge/webview2/#download-section
Thanks for the suggestion.

**Comment by ExPlayer21** [comment]
I updated WebView2, but the message from cloudflare still appears. How can this be fixed?

**Comment by ms-ku** [comment]
Hello
do you use a vpn?
Greetings

**Comment by Rissocka** [comment]
Hi, I'm having the same problem.
I tried uninstalling WebView2 and installing it again about 4x and it didn't work.
I don't use VPN.
Using CRD ver. 3.15.1

**Comment by hama3254** [comment]
@ExPlayer21 and @Rissocka can you access CR with a normal webbrowser (Chrome, Edge or Firefox)?

**Comment by Rissocka** [comment]
@hama3254  Yes, it works normally in both Chrome and Edge

**Comment by hama3254** [comment]
we have now two options, i added [v3.15.2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.15.1) which has the `user agent string` changed to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34`  
You can also check the edge version with `edge://system/` maybe there is something outdated there.
![grafik](https://user-images.githubusercontent.com/52826614/230760893-36862c15-a534-4bb2-86b6-92c451b0626a.png)

**Comment by Rissocka** [comment]
Now it worked perfect!!! I tested it several times using v3.15.2 and now I always get past the CloudFlare page.
I've attached a picture with the edge://system/ for you to see.

Thanks so much for your help, you're awesome!!
![infos](https://user-images.githubusercontent.com/3679903/230786007-36cbd0ec-fed0-4f91-a1fa-ed80a57ff4ea.png)

**Comment by ExPlayer21** [comment]
@ms-ku , @hama3254 

Yes, I use VPN!
With version 3.15.2, everything has become much better:
1. The page from CloudFlare opened;
2. Checked the box "I'm not a robot" (before it was impossible to tick);
3. The crunchyroll site has opened.

Thanks a lot!

**Comment by ExPlayer21** [comment]
Stupid cloudflare or VPN or Crunchyroll..! 

The message "Checking if the site connection is secure" constantly appears and again you cannot check the box "I'm not a robot."

@hama3254 , is it possible to add a proxy or VPN to the program?

**Comment by hama3254** [comment]
> @hama3254 , is it possible to add a proxy or VPN to the program?

this is not doable.

> But! At the same time, the site opens normally through FireFox (regardless of whether VPN is enabled or not).

i can not really tell what CR or cloudflare have there, i can also not do much with the webbrowser.

**Comment by Rissocka** [comment]
Yes, I have the same problem as @ExPlayer21 again :(
I noticed that when I open the Browser through the CRD it continues using Edge as the Browser (when I right-click the Edge menu appears) even using ver. 3.15.2, I don't know if that has anything to do with it.

![crd](https://user-images.githubusercontent.com/3679903/233866329-1dbec043-fde7-4ad9-a4ca-2b0d07576687.png)

**Comment by ExPlayer21** [comment]
@hama3254 Is it possible to use another browser (Chromium, Google Chrome or Firefox)?

**Comment by hama3254** [comment]
> Is it possible to use another browser (Chromium, Google Chrome or Firefox)?

i already had pretty much all browsers that work as libary used. 
We ended here since they Gecko (the core of Firefox) is outdated as .net framework libary, CefSharp as chromium framework was unstable and i guess was to blame for most of the random freezess we hat at some point.
The new Webview2 work for me the best and other than CefSharp is also nice to work with.

The only thing i can offer is the browser bypass from the [Mac version request](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/617#discussioncomment-4335974) , in short you can export cookies from your normal webbrowser and save them as `Netscape HTTP Cookie File` ([there are add-ons for that](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/)) in the folder of the `Crunchyroll Downloader.exe`.
This may work but i would not call using the downloader this way stable so i would recommend to just do 1 download at the time.

**Comment by hama3254** [comment]
this folder should contain all data for the WebView2, you can try deleting it.
![grafik](https://user-images.githubusercontent.com/52826614/234097764-93e8c773-11b1-4b18-8311-77e97fd0c594.png)

**Comment by ExPlayer21** [comment]
@hama3254 tried - does not help.
it seems that the cache / cookies are still stored somewhere in the system.

**Comment by hama3254** [comment]
I get logged out without the folder and CR acts like it does not know me (cookie banners).

I can not do more than mention the browser bypass via `cookies.txt` again.

> The only thing i can offer is the browser bypass from the [Mac version request](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/617#discussioncomment-4335974) , in short you can export cookies from your normal webbrowser and save them as `Netscape HTTP Cookie File` ([there are add-ons for that](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/)) in the folder of the `Crunchyroll Downloader.exe`.
> This may work but i would not call using the downloader this way stable so i would recommend to just do 1 download at the time.

**Comment by ExPlayer21** [comment]
> I can not do more than mention the browser bypass via `cookies.txt` again.

Tried. Does not work. A message from Cloudflare still appears.

1. Is it possible to add a configuration file from where the program would get the user agent, or make it so that the user himself can edit the user agent?
2. If the answer to question 1 is no, then you can add a user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0?

**Comment by hama3254** [comment]
> Tried. Does not work. A message from Cloudflare still appears.

Can you add a screenshot of the error message?

Also the user agent string is 
> `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34`

For the next version i was planning to pull it out of the Webview2 so it updates itself with it.

**Comment by ExPlayer21** [comment]
> Can you add a screenshot of the error message?

I can add a screenshot, but you are unlikely to understand something, because it is in Russian.

> For the next version i was planning to pull it out of the Webview2 so it updates itself with it.

Fine. Thank you. I am waiting. 👍

**Comment by hama3254** [comment]
i added [v3.15.3 here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.15.1) which now uses the Webview2 useragent.
![grafik](https://user-images.githubusercontent.com/52826614/236272395-590a6dd5-8d27-4020-a766-f7aa3f7fd8bf.png)

**Comment by ExPlayer21** [comment]
So. After updating the program to version 3.15.3, the message from cloudflare appears again, BUT, now you can check the "Confirm that you are not a robot" checkbox. That is, everything works. Thank you, @hama3254 !

P.S. How long it will last - I do not know :)
