### ISSUE TITLE
"Error in url" webbrowser bug

### ISSUE THREAD

**Issue by Monst3rX** [hama3254/Crunchyroll-Downloader-v3.0#714]
**Describe the bug**
The build in Webbrowser does not work

**Where does the issue happen?**
Any version

**Screenshots**
first if we click on the webbrowser icon this will appear : but nothing will load
![Crunchyroll_Downloader_qc1V3DdIxU](https://user-images.githubusercontent.com/69420019/226201017-c59a7d90-300d-4063-be23-438bcd3cfdb2.png)

if you manually add the crunchyroll link, this will happen : 
![opera_U9tcKdb8qp](https://user-images.githubusercontent.com/69420019/226201057-73ed8b92-cbc3-4dba-8815-b1ae3ad969cb.png)

**Comment by hama3254** [comment]
please check if you have the [WebView2 Runtime which you get from this Microsoft page](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed.

**Comment by Monst3rX** [comment]
> please check if you have the [WebView2 Runtime which you get from this Microsoft page](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed.

Yes i do have it installed
![MicrosoftEdgeUpdate_KrdMTvLquG](https://user-images.githubusercontent.com/69420019/226207693-6461b380-f801-4d97-9561-12b1c40f3b4c.png)
here is what happen when i download it 
translated from french : "installation failure. The microsoft edge webview2 runtime is already installed for the system"

and those are the differents way i tried : 
![image](https://user-images.githubusercontent.com/69420019/226207757-13ed34cb-1df5-4531-9efa-8e93baa4a694.png)
