### ISSUE TITLE
Allow download of closed captions

### ISSUE THREAD

**Issue by Gotos** [hama3254/Crunchyroll-Downloader-v3.0#716]
It would be great if it was possible to download not just the subtitles, but also the closed captions of shows. I am not entirely sure if #705 is maybe asking about the same thing and was just misunderstood or if maybe I am missing an option to download the closed captions, but so far it seems like the Downloader can only download subtitles.

**Comment by hama3254** [comment]
I had to look up the difference between captions and subtitles for #705 and as far i know CR has no captions.
The online definition of captions would include all sound as text for people with hearing issues which as far i know are not available on CR.
The screenshot on #705 show the data entry `closed_caption` but it is empty.
CR only has the usual subtitles and subtitles for dubbed shows which include text like signs.

**Comment by Gotos** [comment]
My Hero Academia does have both subtitles and closed captions, at least in the web interface. I'm not sure where the json on your screenshot is from, so I couldn't verify if the caption entry is empty for MHA as well, but I assume it's just a matter of only few shows having closed captions at this point.

**Comment by hama3254** [comment]
For me on `My Hero Academia` i only get one subtitle for Episode 1 at least.
![grafik](https://user-images.githubusercontent.com/52826614/226329908-dcc61643-e172-479b-bbcb-26b9775792fd.png)

**Comment by Gotos** [comment]
On German crunchyroll that might be true, but on American crunchyroll I have access to closed captions. As far as I know, MHA season 6 is available in English even on German crunchyroll, can you check if you have CCs available there?
![grafik](https://user-images.githubusercontent.com/991937/226331392-a3b6ded8-100b-450c-96ca-f1c1a648babe.png)

**Comment by hama3254** [comment]
On season 6 (Episode 114) with englisch dub i have some there.
I can add this like suggested in #705 but if you need CCs than you probably don't need normal subtitles anymore so a setting that preferess CCs over subs would be my choice for the rare cases we even get CCs.
![grafik](https://user-images.githubusercontent.com/52826614/226336319-c79c5e5e-e3b6-47b0-919a-a3d17989d36c.png)

**Comment by Gotos** [comment]
Sounds good to me. If in doubt I could then still download one first and the other afterwards.
Thanks! :)
