### ISSUE TITLE
Error - Getting videojson data

### ISSUE THREAD

**Issue by Salehx47** [hama3254/Crunchyroll-Downloader-v3.0#718]
Enter your version below, it can be found in the "About" section of the settings.
Version : Crunchyroll-Downloader-v3.14.2

https://i.imgur.com/Pdn5Odj.png

When I download the program stops working, it happens to me a lot, I don't know why?

**Comment by hama3254** [comment]
>it happens to me a lot, I don't know why?

This is some sort of server side refusal, it does happen to you a lot because you download a lot based on that scroll bar.

This is not fixable.

**Comment by Salehx47** [comment]
@hama3254 
Your words are correct, it has become a lot to me after I downloaded a lot

But now it works perfectly without any problems

But there must be a reason for this problem
