### ISSUE TITLE
Chrome addon cannot download with VPN

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#72]
I'm using VPN with Chrome extension and connected to US Country, when i started to download the video i'm getting this message.

![Capture](https://user-images.githubusercontent.com/4635825/96361482-9df7f780-1158-11eb-982c-a1eb3dd6b905.JPG)

Seem like the program cannot download even my browser can watch the video.

**Comment by hama3254** [comment]
If the VPN is just a Chrome add-on this can not work.
You need a system wide VPN or use the us unlock for crunchyroll us.

**Comment by x3inspire** [comment]
> us unlock for crunchyroll us

Where is "us unlock for crunchyroll us"? Seem like i cant see those option on this new version.

**Comment by hama3254** [comment]
it's in the crunchyroll settings tab 
![grafik](https://user-images.githubusercontent.com/52826614/96363887-41381500-1137-11eb-9817-e2577675897e.png)

**Comment by x3inspire** [comment]
Is this normal?

Should i choose without or with login?

![Capture](https://user-images.githubusercontent.com/4635825/96367113-73209a00-117e-11eb-892c-3b4ba84154b6.JPG)

**Comment by hama3254** [comment]
> Is this normal?

 it should not but it seems like it is, however it still works for me and it get fixed in the next version

> Should i choose without or with login?

that depends if you want to login 

> Update:
> you can close this 👍
 
Done
