### ISSUE TITLE
ffmpeg crashing cause of UTF-8 BOM  encoding

### ISSUE THREAD

**Issue by Azzuray** [hama3254/Crunchyroll-Downloader-v3.0#724]
**Describe the bug**
Hallo there, since i've restarted my subscription to Crunchyroll i have downloaded again animes with he same tool i used to , but it seems that the lasts version after v3.14.0.2 (Wich is working fine no issue), i i wanted to have the lastest update and such, and updated the tool, but what ever i try to download it download fine, but got the "seems the player crash" at the end , and upon digging into the issue it seems that its related to the fact the cmd line used to "merge" content with ffmpeg use the .txt from the "CRD-Tempfile" folder but the issue is that ".txt" file is incoded in UTF-8 with BOM , and ffmpeg doesnt like it at all, i dont know if its an issue with my setup, but if i try to merge manualy with the file inside the "CRD-Tempfile" it just spit an error that ffmpeg encoutered and error with the file, but if i merge it with the file inside the application directory (which is encoded as UTF-8) no error append . Could you check it please? Thanks 

edit : I do talk about the "mdata.txt" file

btw, im on W10. 22H2

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll Beta,]
 - Settings [e.g. ffmpeg options]
 - Version [e.g. v3.14.4 ++]

**Comment by hama3254** [comment]
I will have a look at that later, i know the hybrid mode `m3u8` had some issues with the encoding but for the `mdata.txt` i though about the start time as issues since some files have the start at 0.1 sec or something.
