### ISSUE TITLE
Bug when i'm download a hole Season

### ISSUE THREAD

**Issue by MuffinCody** [hama3254/Crunchyroll-Downloader-v3.0#725]
**Describe the bug**
The Bug comes when i download a hole season of a series on Crunchyroll

**Where does the issue happen?**
 - Platform:  Crunchyroll Beta
 - Settings Hardsubs,  ffmpeg 
 - Version 3.15.1

**Screenshots**
![NVIDIA_Share_kyXYlbrO8f](https://user-images.githubusercontent.com/50471042/228663841-5fcc4985-a726-48db-ab3d-fc917bf056b3.png)

**Comment by hama3254** [comment]
This is a random issue caused by invalid data from CR and should just be temporary.
