### ISSUE TITLE
It won't let me download series and the crunchyroll browser doesn't appear in the app, a blank screen appears

### ISSUE THREAD

**Issue by nicooc18g** [hama3254/Crunchyroll-Downloader-v3.0#727]
**Describe the bug**
A clear and concise description of what the bug is.System.nullreferenceexception:Object reference not set to an instance of an object

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll, Funimation]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.8.7.2]

![Add Video 03-04-2023 17_21_27](https://user-images.githubusercontent.com/129798624/229630301-891249b7-1d26-4f42-847a-f99bc881ddb8.png)

**Comment by hama3254** [comment]
please check if you have the [WebView2 Runtime which you get from this Microsoft page](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed.
