### ISSUE TITLE
Index out of Range

### ISSUE THREAD

**Issue by NekomataUwU** [hama3254/Crunchyroll-Downloader-v3.0#729]
Hi,

firstly, greate Downloader. 
Any idea why the download for new files give me this error after X Downloads?

![2023-04-20 13_16_58-Crunchyroll Downloader](https://user-images.githubusercontent.com/67867443/233356378-45c3fb58-26b8-4a46-8c99-a3c2c875b5b5.png)

Greetz

**Comment by NekomataUwU** [comment]
Worth noting, i dont have a Drive D.

**Comment by hama3254** [comment]
> Worth noting, i dont have a Drive D.

the path points to the source file at compile time.

>Any idea why the download for new files give me this error after X Downloads?

without any additional information it's hard to tell, could be a lot of things.
random erros or invalid data from CR ?

**Comment by NekomataUwU** [comment]
What information do you need? Maybe i could provide it. 
I´ve seen recent posts with this problem, i couldnt try the fixes tho because i already have the latest version.

Its literally random after some downloads, may happen after 7 or after 59, its no pattern. 
When it happens tho, all following downloads have the exact same error.

**Comment by hama3254** [comment]
>Its literally random after some downloads, may happen after 7 or after 59, its no pattern.
When it happens tho, all following downloads have the exact same error.

The random part is interesting and that all following downloads fail may indicate some missing error handling.
Please check the build in Webbrowser after the download start failing and see if you get any issue accessing CR.
If that works try to download again, this could be some kind of hidden cloudflare block.

**Comment by NekomataUwU** [comment]
Sorry for the late reply, i wasnt at home for some time. ^^ 

I tried that, i cant see anything wrong in the Webbrowser. 
Download still fails. When i try to access CR with Firefox, Chrome etc. i also dont get any Cloudflare warning or Check.
