### ISSUE TITLE
Hybrid mode not working

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#73]
Hello, attached you log form Hybrid mode.

Seem like i cannot any single video using Hybrid mode.
[Is the Order a Rabbit Season 2 Episode 3.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5397509/Is.the.Order.a.Rabbit.Season.2.Episode.3.log)
[Is the Order a Rabbit Season 2 Episode 4.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5397510/Is.the.Order.a.Rabbit.Season.2.Episode.4.log)
[Is the Order a Rabbit Season 2 Episode 5.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5397511/Is.the.Order.a.Rabbit.Season.2.Episode.5.log)
[Is the Order a Rabbit Season 2 Episode 1.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5397512/Is.the.Order.a.Rabbit.Season.2.Episode.1.log)
[Is the Order a Rabbit Season 2 Episode 2.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5397513/Is.the.Order.a.Rabbit.Season.2.Episode.2.log)

**Comment by hama3254** [comment]
Seems like you try resolution [Auto] with hybride mode, this is not supportet and invalid.
Please choose a fixed resolution

**Comment by hama3254** [comment]
resolution [Auto] with hybride mode should now return the video in 1080p.
