### ISSUE TITLE
Hardsub/softsub switch

### ISSUE THREAD

**Issue by khyinn** [hama3254/Crunchyroll-Downloader-v3.0#731]
Hi,

I use hardsubs when i downloaded dubbed shows in my own language and softsubs for japanese only shows. With the actual configuration, when i download dubbed shows, i have to disable softsubs and enable hardsubs (and "skip hardsubs when unavailable").
Is there a way to add a switch between softsubs/hardsubs configuration ?

Sorry for my english, hope you'll understand.

**Comment by hama3254** [comment]
There is no function for that but all settings are saved in the local downloader folder as `User.config.dat`.
You can copy the downloader and set it up a second time and just switch to the version you need or want.

That said i would use settings that work for both of your cases.
If you use `mkv` with merged subs as `copy` 
![grafik](https://user-images.githubusercontent.com/52826614/233829571-41e6ee99-e7c6-4868-aa7d-d8be03233824.png)

then you can set `Hardsub` to `[null]` and only use the softsub you want which can be default toggeld on by the `Default Subtitle` option.
![grafik](https://user-images.githubusercontent.com/52826614/233829574-04ed88a3-b38f-44a2-9cdc-d23bc4c87b3e.png)

This way you have softsubs that act like hardsubs without the downside of hardsubs, only your player needs to be able to handle it (which VLC and most other easy do)

**Comment by khyinn** [comment]
Yes, that's what I'm doing now, however I have very poor eyesight so I have to extract the subtitles when watching in Japanese to increase their size.
I don't have this problem when I watch anime in my language since the subtitles are then almost only about the episode titles and some not really useful notes.
So I will save both configurations and switch from one to the other by renaming the file for the moment. Thanks for the answer.
