### ISSUE TITLE
Japan DUB and German Dub and German Subtitle in one MKV File

### ISSUE THREAD

**Issue by sanipai** [hama3254/Crunchyroll-Downloader-v3.0#735]
Hello, is it possible to directly merge Japan DUB Audio File and German DUB Audio File and the German Sub Titles into one MKV file?

**Comment by LoneNomadBlue** [comment]
I was also wondering this. It seems that there isn't a way to choose multiple dubs to create a dual audio file export. I wish there was since this seems to be the best CR downloader with only having this one feature missing.

**Comment by hama3254** [comment]
The downloader has limited options for multi dub videos.
The most information can be found in #701 which also includes some reason why this is not a good idea on CR.
The short explanation would be to not use the dub override from the settings, selecting `Merge Audio with existing files` and just setup the download to use merged softsubs (with or without a default sub) and start by downloading all Japanese episodes.
If this is done you can download all episodes with Ger Dub.
The `Merge Audio with existing files` will rename the output file if it exists and use it as main input and only add the audio track (**subs are ignores**).
The simplest option to select the dub inside the downloaer for a season is the season download, just use the overview page url (the one where you see all episodes on CR) and than you should get a selection of all seasons and there episodes.
As with #721 i filter all episodes that not match the dub episode 1 per season.
