### ISSUE TITLE
Option to download other languages - Portguese (Portugal)

### ISSUE THREAD

**Issue by koggins** [hama3254/Crunchyroll-Downloader-v3.0#737]
I am trying to download CR subs for Portuguese (Portugal) but this option does not appear to be supported, only Brazil. Is there a way to download subs from languages that are not listed in the settings?

![image](https://user-images.githubusercontent.com/132588955/236243033-078c627a-4aa9-4fb4-9d8c-3b0fd84e2b3e.png)
![image](https://user-images.githubusercontent.com/132588955/236243108-dd9107a6-4976-441d-8e5b-a0b2bdfd8288.png)

**Comment by hama3254** [comment]
I would need to add it.
it would help if you link me the anime you tried there because i have never noticed that this version even exists.

**Comment by koggins** [comment]
Thanks for your response! 

I have been trying to preserve all subs for this title: https://www.crunchyroll.com/watch/GWDU8DX0W/persona5-the-stage

It's quite niche, so they can't be found elsewhere. The Portuguese (Portugal) option for this title was only added very recently. It may not be common on other CR titles.

**Comment by hama3254** [comment]
i added [v3.15.3 here](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.15.1) which now has the option to select Português (Portugal).

**Comment by koggins** [comment]
Amazing! Thank you so much!
