### ISSUE TITLE
login failure

### ISSUE THREAD

**Issue by cimmy01** [hama3254/Crunchyroll-Downloader-v3.0#74]
Every time I have tried to log in today I have been getting an invalid credentials error or invalid crs token error even though I am inputting the correct info.

**Comment by hama3254** [comment]
Thats a crunchyroll issue and has nothing to do with the downloader.

**Comment by cimmy01** [comment]
this is only happening on the built in browser. I can log in in all of by other browsers and apps

**Comment by hama3254** [comment]
i'm sorry but both is server side and happens for me sometimes on the normal browser as well.
i can not fix that CR has an invalid token in there HTML page or that they don't accept the login information you have entered.
