### ISSUE TITLE
[API change?] Crunchyroll DRM

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#740]
while working on #739 i was unable to find the `streams` json file
the `object` json file is still there and and stil links to the `streams` but it is missing (it should be there on the left)
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/0a95d097-9076-45be-b59d-0df2cba62138)

further more there is a different `play` json with only `DASH` video streams

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/8ecb5e8b-37c5-4298-9bb7-4096ec07a9e9)

The new streams are also protected with [`microsoft:playready`](https://en.wikipedia.org/wiki/PlayReady)
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/72ce3224-85d7-4e75-81cf-00d5097b47f5)

**Comment by MyNameIsDark01** [comment]
it's widevine (provided by castlabs), it shuld work with streams as well until they don't disable it

**Comment by AnimeDL** [comment]
It's also worth noting as far as I can tell, so far it only exists like this via chrome (and likely chromium based browsers, but I haven't tested).

**Comment by wraith4081** [comment]
Recently, when I was writing a cli with typescript to download something from Crunchyroll, they switched from m3u8 to MPEG Dash (MPD) in front of my eyes. This requires a lot of tweaking and I think that the m4s's in the MPD file are encrypted, so it's a lot of work.

**Comment by wraith4081** [comment]
@hama3254 any update? I broke /drm/auth in my own experiments, but I can't figure out how to create the body part of widevine lisance create request. This is the only and huge obstacle if I can find something. I'll let you know, I need this program fixed, I need to download an episode but I can't.

**Comment by hama3254** [comment]
@wraith4081 I still use old API and I don't plan on using any DRM streams for legal reasons.
As far I know only logged-in users get newer API so I don't know what CR is even planning to do.

**Comment by wraith4081** [comment]
@hama3254 Right now I think they're trying to DRM all content, and I think it's going to be mixed with the current system until the problems are over.

**Comment by MyNameIsDark01** [comment]
The only solution is to change and add DRM decryption with user own widevine device. Btw if u don't know how to properly use could get a ban and the streaming on device u got the key won't work anymore.

**Comment by hama3254** [comment]
The new API also now adds the limit.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/a0afa360-b13a-4111-91e9-919c25ed6fdb)


![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9db03809-ff12-4091-8fc4-e015e69f69f5)

**Comment by MyNameIsDark01** [comment]
wdym? They already have these plan since the legacy api, and of course u can't open streams on more devices than your plan

**Comment by hama3254** [comment]
@MyNameIsDark01 I know that they have that tier system for a while now but i never see them actually enforce it.

I also got that message pretty fast by just using the downloader and the webbrowser at the same time.

**Comment by tamodolo** [comment]
> @hama3254 Right now I think they're trying to DRM all content, and I think it's going to be mixed with the current system until the problems are over.

This is easy to understand. historicaly CR is a company made by fansub people. They started as a pirate site. The fun thing is even on Brazil, where I live, the ones that run it was from fansubs originaly. I don't think these people were to akin to switch on DRM. The thing is Sony bough them. Now let's see what Sony is: A mega corporation that has open capital (it means stonks). Now you get all the streamlined bs out of the box:

Investors are very insecure and ansious people. They won't put money on something that isn't protected. So DRM is just this: make investors to sleep well. The general public knows that DRM never blocked piracy ever. (probably DENUVO is the one that are wining the game for now. I don't doubt people will rise again against it eventualy). For passive midia you just need to record the framebuffer if the objective is just share the thing. But this is not my objective... I just hate CR players. They junt will not deliver 1080p stream no matter what you do. I have a LG TV and tested the new app. It's ok as a browser but the player can't stream more than 720p. To make things worser the app is limited to 1080p and does not scale anything. The final result is an insult.
