### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Jordan88ark** [hama3254/Crunchyroll-Downloader-v3.0#742]
When I try to download I receive this message : ¨Status: Failed - no video, check CR login¨

**Comment by Jordan88ark** [comment]
Please help :´)

**Comment by hama3254** [comment]
Are you logged in within the build-in Webbrowser?

**Comment by Jordan88ark** [comment]
I already did it but the error continues

**Comment by hama3254** [comment]
This may be that the [trigger](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/ffcce61e1d2ccb48fa9bc22f0cba2a9bab9919dd/Crunchyroll%20Downloader/Main.vb#L4515) is the API that was replaced with the one I found in #740.

If this is the case than the download will stop working for ever.

**Comment by hama3254** [comment]
Without any more information or the episode to test it myself i am unable to help here any further.

**Comment by Jordan88ark** [comment]
Can you try with this please: https://www.crunchyroll.com/es/watch/G60X9EZVR/smoke-signal

**Comment by hama3254** [comment]
I can not see anything wrong with that on my side.

the [CRD-Log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log) might help me to find your issue with that episode.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/08811c1b-870b-4f6b-b864-9b191b24815c)

**Comment by Jordan88ark** [comment]
I think is a issue related with my device bc with my previous device i could download the episodes normaly

Thread Name: Main
5/21/2023 1:47:38 PM.319
Auth-Basic: Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
NavigationCompleted: 5/21/2023 1:47:40 PM
Just Browsing, exiting...
what's going on?: 5/21/2023 1:47:55 PM
13
###Cookie: _ga_SYYQC1VW88=GS1.1.1684698132.5.1.1684698459.60.0.0;ab.storage.deviceId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%2218e8f6a7-ceb0-38af-f599-dc4717879259%22%2C%22c%22%3A1684698231911%2C%22l%22%3A1684698231911%7D;_gcl_au=1.1.1921375845.1684096383;ab.storage.userId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22ec5fa01b-c2d3-57a8-8909-f3eaaf02b28b%22%2C%22c%22%3A1684698231900%2C%22l%22%3A1684698231907%7D;_ga=GA1.1.1839138877.1684096383;__cf_bm=6udBc_i30_RKPR06jrAX5Tg1y1U8cIeZj4opB4fVkgE-1684698134-0-ARspS3A0kEj93R5IjNHVxJ7lDrrb3qhHyPCX3BF65bZ2zkFWilj75nGmUBuTdpU2OANeTbKQW7ectFZGX6VIQ0QMvfJp1zp+0SkoeHQnxcc2;_ttp=b1RCGKuERPCze0yamiQwvxRhFCh;etp_rt=f3fbeb74-c909-480b-8126-6d1015559539;_dd_s=rum=2&id=ecb57c4c-5013-4608-be5a-5d2a22bc1b91&created=1684698131997&expire=1684699359500;_tt_enable_cookie=1;ajs_user_id=ec5fa01b-c2d3-57a8-8909-f3eaaf02b28b;ab.storage.sessionId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%220661becd-c33c-7629-ca97-2a1f81be7b10%22%2C%22e%22%3A1684700031921%2C%22c%22%3A1684698231904%2C%22l%22%3A1684698231921%7D;ajs_anonymous_id=4db46d37-d85a-46d7-91e6-99325a49af43;###
CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IlNXdGk0c0UwYTVCeFl6SmxmTjJ6aVEiLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJjbGllbnRfaWQiOiJjcl9iYWNrZW5kIiwiY2xpZW50X3RhZyI6IjEuMC4wIGJldGEiLCJjb3VudHJ5IjoiTVgiLCJldHBfdXNlcl9pZCI6ImVjNWZhMDFiLWMyZDMtNTdhOC04OTA5LWYzZWFhZjAyYjI4YiIsImV4cCI6MTY4NDY5ODc3OSwianRpIjoiYjZiODgwNjktZWRmMy00MzZmLWJkZDEtNTJhODY4ZTY4NjdmIiwibWF0dXJpdHkiOiJNMyIsIm9hdXRoX3Njb3BlcyI6ImFjY291bnQgY29udGVudCBvZmZsaW5lX2FjY2VzcyByZXZpZXdzIHRhbGtib3giLCJydF9pZCI6ImNoZ3M3NDdzaHVydHNiY2ptZDEwIiwic2NvcGVzIjp7ImNyIjp7ImFjY19pZCI6ImVjNWZhMDFiLWMyZDMtNTdhOC04OTA5LWYzZWFhZjAyYjI4YiIsImV4dF9pZCI6IjEwNjIyNzA5MzgifX0sInN0YXR1cyI6IkFDVElWRSIsInRudCI6ImNyIn0.Uwq_jon3g0O0lTUhs5hXV7neQETpXsjcGRddLglMQUJIjnLnCWLeISII17gYijqCGGRHGOQwefIIowGI0lfpWOiSAkNdQ2YXiGQIpJOhHGPwK0Npe1EqPZkNOB98S_WDuJopNcIAFHV781_kCiclfIPfY5vEG1xP19H20Apg0nS1cshGSYFWBDfw2MGCIJxiOzk_Z8mjHET8Xlbqq8lhwQRjLwSgLVzCigojDh5YHWlE1KHzuZJ7RXWG5yhyghOZZSeODoYFy17BW79pkJA0BwmWhQKvbDX7eOEMKIEyX5HRLlaXMltEaeJWAG7BfAZH7jbS1emSQDUOZkLMC7KddQ","refresh_token":"f3fbeb74-c909-480b-8126-6d1015559539","expires_in":300,"token_type":"Bearer","scope":"account content offline_access reviews talkbox","country":"MX","account_id":"ec5fa01b-c2d3-57a8-8909-f3eaaf02b28b"}
ObjectsUrl: https://www.crunchyroll.com/content/v2/cms/objects/G6QW47G26?preferred_audio_language=ja-JP&locale=en-US
Status: Failed - no video, check CR login

**Comment by hama3254** [comment]
I can not see any reason why the `streams` should be missing from the data other than the login.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/c3a7b0ec-c324-4c40-b21d-5c28a676797c)
