### ISSUE TITLE
Is the CR DRM news true? I am unable to download few video.

### ISSUE THREAD

**Issue by pratyushpati11** [hama3254/Crunchyroll-Downloader-v3.0#744]

**Comment by San3-Cod3** [comment]
Can't speak for logged in DL via credentials inside built-in browser - but CR downloading works when logged out at least, to download the free stuff I.E "Celebrate Ani-May with Free-to-Watch Shows!" - shows like the following can be grabbed for free whilst logged out: [My Hero Academia](https://www.crunchyroll.com/series/G6NQ5DWZ6/my-hero-academia)
[Toilet-bound Hanako-kun](https://www.crunchyroll.com/series/G24H1N3ZP/toilet-bound-hanako-kun)
[JUJUTSU KAISEN](https://www.crunchyroll.com/series/GRDV0019R/jujutsu-kaisen)
[Cowboy Bebop](https://www.crunchyroll.com/series/GYVNXMVP6/cowboy-bebop) [Assassination Classroom](https://www.crunchyroll.com/series/GRE59JGX6/assassination-classroom)
[Fire Force](https://www.crunchyroll.com/series/GYQWNXPZY/fire-force)
[GOBLIN SLAYER](https://www.crunchyroll.com/series/G6VDMN306/goblin-slayer)
[Miss Kobayashi's Dragon Maid](https://www.crunchyroll.com/series/G6497Z43Y/miss-kobayashis-dragon-maid)
[That Time I Got Reincarnated as a Slime](https://www.crunchyroll.com/series/GYZJ43JMR/that-time-i-got-reincarnated-as-a-slime)
 [Tokyo Ghoul](https://www.crunchyroll.com/series/G6NV7Z50Y/tokyo-ghoul)

**Comment by hama3254** [comment]
> Don't have Premium/paid account to test whilst logged in on my end.

this was just a quick look at the German Dub version left is without any account and i got the old api while on the right i was logged in and it used the new one with only DRM protected videos.
That is the exact same episode....
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/1cac572c-e229-4047-bce2-b70658e471da)

The download does still work for at least that one episode with account.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/4e7095d3-b98d-4c88-88b5-fdcbb13da628)

**Comment by San3-Cod3** [comment]
Does Nintendo switch have a specific User-Agent to spoof to, I wonder?

> @hama3254 Seems CR still no DRM on Android API and Nintendo Switch.

**Comment by hama3254** [comment]
> @hama3254 Seems CR still no DRM on Android API and Nintendo Switch.

At least the web version does not work anymore with Firefox since i has no DRM support.

![Screenshot_2023-05-17-06-28-26-99_3aea4af51f236e4932235fdada7d1643](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/76ca0527-588f-4548-b005-f4d0343936b2)

![Screenshot_2023-05-17-06-30-14-84_3aea4af51f236e4932235fdada7d1643](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/35af84ef-c39b-4aff-a424-f436a1110fbc)


> Edit2: Would spoofing to one of those change how the DRM affects the content, I wonder?

No, i thinks we use Safari and still enable some sort of DRM.

**Comment by pratyushpati11** [comment]
For Me I can still download. Let's see what happens in future.
