### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by ivanmusik** [hama3254/Crunchyroll-Downloader-v3.0#747]
It doesn't start for some reason, i don't get an error code or anything, simply loads the site, I select the chapter, it opens on the web browser, and that's it, it doesn't download or do anything

Where does the issue happen?

Platform: Crunchyroll, Windows 11
Settings: Softsub, hybrid mode, using libx265
Version: 3.15.3

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/3241619/1145c9f7-5bf3-421e-891f-f0854f8c478d)

**Comment by hama3254** [comment]
I can not see anything wrong with that on my side.

the [CRD-Log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log) might help me to find your issue.

**Comment by ivanmusik** [comment]
Sorry I completely forgot about the logs

Thread Name: Main
21/05/2023 10:07:52 a. m..718
Auth-Basic: Basic bm9haWhkZXZtXzZpeWcwYThsMHE6
NavigationCompleted: 21/05/2023 10:07:53 a. m.
21/05/2023 10:07:53 a. m..281
https://www.crunchyroll.com/
Just Browsing, exiting...
what's going on?: 21/05/2023 10:09:11 a. m.
15
###Cookie: _ga_SYYQC1VW88=GS1.1.1684685189.6.1.1684685272.43.0.0;ab.storage.sessionId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22fc0930df-5fe9-182d-872a-6a49b93962c3%22%2C%22e%22%3A1684687057104%2C%22c%22%3A1684685257084%2C%22l%22%3A1684685257104%7D;ab.storage.deviceId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22ada4bf27-33f5-344e-ead2-fae913192394%22%2C%22c%22%3A1684685257086%2C%22l%22%3A1684685257086%7D;_gcl_au=1.1.725148227.1679421429;ab.storage.userId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22794ef3f4-1e16-57fb-8677-62ba06171a56%22%2C%22c%22%3A1684685257082%2C%22l%22%3A1684685257084%7D;etp_rt=27ce4329-ea3c-41ff-8f3c-a4bc320a9010;_ga=GA1.1.1046484464.1679421429;__cf_bm=2CyM3Es4G9ruCW3vH_9fpaSihA70VgYLV.9V9_rsG.w-1684685188-0-Ae37w63tTUz307qZ1v6rF8D7Q+Y5YN33MfZuWzweZuakTZOUUMWnJSZmdWgsjIhCgb4QwaAoYychWbX7KYFbFGliG30fixOAvYNkK17iJX4G;c_visitor=28f40c01-3eaf-4690-809f-e250f77c3865;ajs_user_id=794ef3f4-1e16-57fb-8677-62ba06171a56;_ttp=IQ00Wq99wqNR-fHWbeGZe-K1Wya;_dd_s=rum=0&expire=1684686172791;_tt_enable_cookie=1;ajs_anonymous_id=a4c7b525-d5d0-4b3d-b4ad-754e05c30709;###
CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IlNXdGk0c0UwYTVCeFl6SmxmTjJ6aVEiLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJiZW5lZml0cyI6WyJjYXRhbG9nIiwiY29uY3VycmVudF9zdHJlYW1zLjQiLCJjcl9mYW5fcGFjayIsImNyX3ByZW1pdW0iLCJtYW5nYV9saWJyYXJ5Iiwibm9fYWRzIiwib2ZmbGluZV92aWV3aW5nIiwic2ltdWxjYXN0Il0sImNsaWVudF9pZCI6ImNyX2JhY2tlbmQiLCJjbGllbnRfdGFnIjoiMS4wLjAgYmV0YSIsImNvdW50cnkiOiJNWCIsImV0cF91c2VyX2lkIjoiNzk0ZWYzZjQtMWUxNi01N2ZiLTg2NzctNjJiYTA2MTcxYTU2IiwiZXhwIjoxNjg0Njg1NjUxLCJqdGkiOiI1YTkxNGJkNi02MDdjLTQ0YWYtOTQyNi1iZDNjZTE0OTNhMjAiLCJtYXR1cml0eSI6Ik0zIiwib2F1dGhfc2NvcGVzIjoiYWNjb3VudCBjb250ZW50IG9mZmxpbmVfYWNjZXNzIHJldmlld3MgdGFsa2JveCIsInJ0X2lkIjoiY2hsNDNobTI1bjdkc3BxaW5saGciLCJzY29wZXMiOnsiY3IiOnsiYWNjX2lkIjoiNzk0ZWYzZjQtMWUxNi01N2ZiLTg2NzctNjJiYTA2MTcxYTU2IiwiZXh0X2lkIjoiMzE4MjIxNTcifX0sInN0YXR1cyI6IkFDVElWRSIsInRudCI6ImNyIn0.V_0krzI_5qX8RX5EtHjf19BerixoXD5sgpiqTRYadbb4eVMOU_0LhFZhdwOCjBJLs7_ihm_XkdtABDe1EjzFFz3KAPHYzCazVnmCw9msFpwm364ily5tnjPsY-ybWaXllnYD1quRS9KM9hz8EkRYzIW3jdhb9Z80QAJa5I-N8C7-v5A4737nmF67WgR-3NvvMh-nNmDQTlcSsjAsFZlZO6qIYBX0wXcQChPRiAoA-pDSNy7Uf3E0F88RWAkudpFbgb6_qBeRo6icqYlxhmYmuZ0fE42Wh2r8g7L02JzltngP0e87ZJE0Shs63ixJXP3lAdlgxjw9ZASUg5mk7tDaAA","refresh_token":"27ce4329-ea3c-41ff-8f3c-a4bc320a9010","expires_in":300,"token_type":"Bearer","scope":"account content offline_access reviews talkbox","country":"MX","account_id":"794ef3f4-1e16-57fb-8677-62ba06171a56"}
https://www.crunchyroll.com/content/v2/cms/series/GYEXQKJG6/seasons?preferred_audio_language=ja-JP&locale=en-US
b: False
15
###Cookie: ab.storage.sessionId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22d7564683-b454-c197-d712-9968f523272c%22%2C%22e%22%3A1684687074363%2C%22c%22%3A1684685274357%2C%22l%22%3A1684685274363%7D;ab.storage.deviceId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22044cb24c-5052-5d42-68ba-e679a0153d31%22%2C%22c%22%3A1684685274359%2C%22l%22%3A1684685274359%7D;_ga_SYYQC1VW88=GS1.1.1684685189.6.1.1684685272.43.0.0;etp_rt=27ce4329-ea3c-41ff-8f3c-a4bc320a9010;_ga=GA1.1.1046484464.1679421429;__cf_bm=2CyM3Es4G9ruCW3vH_9fpaSihA70VgYLV.9V9_rsG.w-1684685188-0-Ae37w63tTUz307qZ1v6rF8D7Q+Y5YN33MfZuWzweZuakTZOUUMWnJSZmdWgsjIhCgb4QwaAoYychWbX7KYFbFGliG30fixOAvYNkK17iJX4G;c_visitor=28f40c01-3eaf-4690-809f-e250f77c3865;ajs_user_id=794ef3f4-1e16-57fb-8677-62ba06171a56;_ttp=IQ00Wq99wqNR-fHWbeGZe-K1Wya;_dd_s=rum=0&expire=1684686249698;_tt_enable_cookie=1;ajs_anonymous_id=a4c7b525-d5d0-4b3d-b4ad-754e05c30709;ab.storage.userId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22794ef3f4-1e16-57fb-8677-62ba06171a56%22%2C%22c%22%3A1684685274355%2C%22l%22%3A1684685274358%7D;_gcl_au=1.1.725148227.1679421429;###
CurlPost-O: {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IlNXdGk0c0UwYTVCeFl6SmxmTjJ6aVEiLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiIiLCJiZW5lZml0cyI6WyJjYXRhbG9nIiwiY29uY3VycmVudF9zdHJlYW1zLjQiLCJjcl9mYW5fcGFjayIsImNyX3ByZW1pdW0iLCJtYW5nYV9saWJyYXJ5Iiwibm9fYWRzIiwib2ZmbGluZV92aWV3aW5nIiwic2ltdWxjYXN0Il0sImNsaWVudF9pZCI6ImNyX2JhY2tlbmQiLCJjbGllbnRfdGFnIjoiMS4wLjAgYmV0YSIsImNvdW50cnkiOiJNWCIsImV0cF91c2VyX2lkIjoiNzk0ZWYzZjQtMWUxNi01N2ZiLTg2NzctNjJiYTA2MTcxYTU2IiwiZXhwIjoxNjg0Njg1NjY5LCJqdGkiOiI1NmEyMDZmMy0yZTcyLTQ2MjUtYTUwNi05NGVlOWIwNTY5NWUiLCJtYXR1cml0eSI6Ik0zIiwib2F1dGhfc2NvcGVzIjoiYWNjb3VudCBjb250ZW50IG9mZmxpbmVfYWNjZXNzIHJldmlld3MgdGFsa2JveCIsInJ0X2lkIjoiY2hsNDNobTI1bjdkc3BxaW5saGciLCJzY29wZXMiOnsiY3IiOnsiYWNjX2lkIjoiNzk0ZWYzZjQtMWUxNi01N2ZiLTg2NzctNjJiYTA2MTcxYTU2IiwiZXh0X2lkIjoiMzE4MjIxNTcifX0sInN0YXR1cyI6IkFDVElWRSIsInRudCI6ImNyIn0.JTwXIYOS99RQHPYMwpbAM8VRGtG9BsuSbSwBWNbXITNGM_WzCgaYwgko-xF0V-PMpKksbHdmTTkL_aMZlI6unHbVbH8b7nxNTCYxE8Prg4RWMgd2bGZlox5hPryPGUgZtUGEYWLdbz6zcUsW66QIwiLA0cA8GwnZ97gaXeLYr4D8RrMRQWVclemgqq9VZLR7EbvSzyqYvpzChKg-QuUwFMeQ7JW21abZ_rnO1a7r-BO-DB5wgdN-LI_FfHSJw1RA-jiWaEDrqBcmG6zrnKRE0eeSfR5jD_oaj_1RaGbFY8kdh3Fp3WxEbgE3hYDc-Aihlf4V2cRqa9YoMeDHDJVVRg","refresh_token":"27ce4329-ea3c-41ff-8f3c-a4bc320a9010","expires_in":300,"token_type":"Bearer","scope":"account content offline_access reviews talkbox","country":"MX","account_id":"794ef3f4-1e16-57fb-8677-62ba06171a56"}
ObjectsUrl: https://www.crunchyroll.com/content/v2/cms/objects/GRMEW51PY?preferred_audio_language=ja-JP&locale=en-US
Website: https://www.crunchyroll.com/watch/GRMEW51PY/buddies-back-to-back/
https://www.crunchyroll.com/content/v2/cms/objects/GRMEW51PY?preferred_audio_language=ja-JP&locale=en-US
NavigationCompleted: 21/05/2023 10:09:31 a. m.
21/05/2023 10:09:31 a. m..232
https://www.crunchyroll.com/watch/GRMEW51PY/buddies-back-to-back
Just Browsing, exiting...

**Comment by hama3254** [comment]
it seem like it failed a request and the fallback is not working.
i don't get the fallback working again due to changes from CR (#740) a new version would only display a error message at that point.
I don't know what CR does with it's service and potential differents for there server for our regions.

**Comment by Alethi94** [comment]
@ivanmusik are you using a VPN at all? 
it won't let me download anything while running my VPN, I have tried multiple servers. 
as soon as I switch it off and restart the downloader it finds the episodes instantly

**Comment by ivanmusik** [comment]
@Alethi94  I've tried both, on VPN and off VPN but neither seem to work I guess I'll wait for an update and hope it works again haha :(
