### ISSUE TITLE
Windows 10/11 Security Deletes the Compressed Downloads

### ISSUE THREAD

**Issue by Technous285** [hama3254/Crunchyroll-Downloader-v3.0#750]
Pretty much what it says in the title.
I have tried 5 times to download v3.15.3.zip file and only on the fifth try I managed to keep Windows from yeeting the download to the shadow realm by opening the downloading Folder (not on C: drive thankfully) Properties -> Security -> Disable Inheritance (Convert Inherited Permissions to Explicit Permissions) -> Delete Group/User "SYSTEM" -> Apply -> Close Properties.

Windows Defender/Anti-Malware "security" suite uses the "SYSTEM" account to yeet files it thinks are sus/bad actors, and this project has been classified as such a download to be shadowbanned on Windows 10/11.

**Comment by hama3254** [comment]
I can not reproduce the issue and a quick check with VirusTotal gives `0/60 `.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/75219646-3271-4e35-883e-ff2092833911)

**Comment by Technous285** [comment]
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/15863/7416f6cc-3f0f-4414-98a6-5babfcab847b

![Win11 version](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/15863/e465173a-40b8-4097-9bcd-2bbb7c3014d9)


In this video I have to try three times to get the compressed file to download as the first 2 times are deleted by Windows Defender in what's known as "silent deletion" or "silent quarantine" because Microsoft runs its own malware definition updates that aren't always shared with folks like VirusTotals in order to do the "silent deletion" trick unless you remove a folder from being able to be controlled by Windows Defender (as shown in the vid by removing permissions apart from Users, as it seems even with SYSTEM being removed from the list of permissions, Defender can still use Administrators as backup paths to operate with).

**Comment by hama3254** [comment]
Since i am unable to reproduce it there is not much i can do and there are also no other reports with only the v3.15.3 having `1894` downloads so i don't see thins as a big issue.
