### ISSUE TITLE
i cant get subtitles direclty on the videos

### ISSUE THREAD

**Issue by YoXpertguyZ** [hama3254/Crunchyroll-Downloader-v3.0#752]
I dont want the subtitle files but i want the video to download with the subtitles already recorded onto the video so when i play it it has the subtitle for crunchyroll i tried messing with it but it keeps giving me the subtitles seperatly idk if its a bug or not but please help thanks
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/62682645/9edba52b-21dd-4ae8-bf75-60a79bfb3220)

**Comment by hama3254** [comment]
You can either look at the output tab and select to the right of the format the merge option ( recommend is `mkv` as format with `copy` as merge option) or you unselect all softsubs for CR and use Hard subs which then is part of the video image instead of a timestamped Textfile.

**Comment by YoXpertguyZ** [comment]
So uncheck use captions if available and select English for hard subs?Sent from my iPhoneOn Jun 1, 2023, at 9:56 PM, hama3254 ***@***.***> wrote:﻿
You can either look at the output tab and select to the right of the format the merge option ( recommend is mkv as format with copy as merge option) or you unselect all softsubs for CR and use Hard subs which then is part of the video image instead of a timestamped Textfile.

**Comment by hama3254** [comment]
## 1st option
My favorit is this option, use `mkv` as video format which allows to use `copy` for the substitles 
 ![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/f14d1cfb-e7f2-42d1-9e29-d6da9388c9cc)
this saves the subtitles as they are in the video file as text which could be turned off if you want,
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/aa18330e-e73d-40ca-87de-101201c1fc0c)
to have it the subs on by default you need to set it as default sub here.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/4ca4bbb1-2b87-4244-8366-3b76420ae130)

## 2nd option

but you have also the option to just unselect soft subtitles (blue) and select hard subtitles (red) this makes the subs part of the video image so you can not turn them off.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/324ace34-1945-4ceb-a4c1-91aa1345ccfe)
