### ISSUE TITLE
Funimation Download problem

### ISSUE THREAD

**Issue by CBecker100** [hama3254/Crunchyroll-Downloader-v3.0#753]
Hello,
I have a problem with the Funimation download function.
When I try to enter the url, it simply says:
![error](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/134368939/0f1e6897-fd45-4506-96de-23fe3c634438)
Can you tell me what's wrong?
The URL I tried to enter is this one:
https://www.funimation.com/shows/youre-being-summoned-azazel/

The site isn't even opened in the integrated web browser.

**Comment by hama3254** [comment]
it seems the funimation part is somewhat broken in the latest version, you can try some older versions if you want, there have not been any updates for a while but i also don't know if funimation changed something on there end.

**Comment by hama3254** [comment]
it seems like i fixed the base funiton that i broke with #698 and #701 without adding any advanced funtions (default should work fine)

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9c65093b-adc7-4adf-8fb1-d530971ac563)
