### ISSUE TITLE
Hey, can you help me? Please

### ISSUE THREAD

**Issue by Tony2234** [hama3254/Crunchyroll-Downloader-v3.0#76]
It's just that when I try to download some episode of crunchyroll in crunchyroll downloader 3.5.5 it tells me an error "press the play button again to retry" and also says "we run into a unknown problem here
What can I do? I'd appreciate it if you'd help me.![IMG_20201020_184531.jpg](https://user-images.githubusercontent.com/73205041/96659545-73e33880-1304-11eb-97c7-2180229eafac.jpg)

**Comment by hama3254** [comment]
For the bug report you do at the best press "yes" that way I get the exact error message send to a Google form.
For the failing download I would need the log file to determine what's wrong.
Please enable it in the settings and send it to me here.
You will find the log after an download attempt in the same folder as the video should be.

**Comment by Tony2234** [comment]
[Error 20.10.2020 19.16.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5416443/Error.20.10.2020.19.16.txt)
Will this file be?

**Comment by hama3254** [comment]
> 
> [Error 20.10.2020 19.16.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5416443/Error.20.10.2020.19.16.txt)
> Will this file be?

not what i have meant but that's also nice to have. 
that file is the local copy of the data the program send to me.
Unfortunately this is not a error that i can fix `Error en el servidor remoto: (503) Servidor no disponible.`  503  tells me that this is a server issue.

for the crashed download i need the log file from the download process which needs to be enabled in the settings. 

![grafik](https://user-images.githubusercontent.com/52826614/96755230-bc692780-13d2-11eb-8541-b181ef882191.png)

the log will be saved in the same folder as the mp4 file 
![grafik](https://user-images.githubusercontent.com/52826614/96755315-d7d43280-13d2-11eb-9120-d280d2b65e32.png)

**Comment by Tony2234** [comment]
> It's just that when I try to download some episode of crunchyroll in crunchyroll downloader 3.5.5 it tells me an error "press the play button again to retry" and also says "we run into a unknown problem here
> What can I do? I'd appreciate it if you'd help me.![IMG_20201020_184531.jpg](https://user-images.githubusercontent.com/73205041/96659545-73e33880-1304-11eb-97c7-2180229eafac.jpg)
Hey thank you very much for responding, now try downloading an episode and started downloading normally, thank you very much for your time 😀

**Comment by Tony2234** [comment]
> > 
> > [Error 20.10.2020 19.16.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/5416443/Error.20.10.2020.19.16.txt)
> > Will this file be?
> 
> not what i have meant but that's also nice to have. 
> that file is the local copy of the data the program send to me.
> Unfortunately this is not a error that i can fix `Error en el servidor remoto: (503) Servidor no disponible.`  503  tells me that this is a server issue.
> 
> for the crashed download i need the log file from the download process which needs to be enabled in the settings. 
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/96755230-bc692780-13d2-11eb-8541-b181ef882191.png)
> 
> the log will be saved in the same folder as the mp4 file 
> ![grafik](https://user-images.githubusercontent.com/52826614/96755315-d7d43280-13d2-11eb-9120-d280d2b65e32.png)
> 
> 

Hey thank you very much for responding, now try downloading an episode and started downloading normally, thank you very much for your time 😀

**Comment by hama3254** [comment]
> 
> Hey thank you very much for responding, now try downloading an episode and started downloading normally, thank you very much for your time 😀

i hate such random errors but if it works then i guess i can close this. 
if you have any more questions or error just make a new issue.
