### ISSUE TITLE
File name error.

### ISSUE THREAD

**Issue by pruebark9** [hama3254/Crunchyroll-Downloader-v3.0#760]
A minor problem that has started is that in the Naming option, I had always had it set to ignore session 1 in the filename extras part. That is to say, the videos I was left with Name of the anime-Season number (except if it was the first one that in that case nothing came out)-Episode number.

But since a few days ago, I always get a "1" in the season number even if I have it set to ignore the first one. It started out of nowhere without touching any option and now, there is no way to set it to work as usual.

![243110148-bcfcef2c-a66b-4fc0-90a5-e9b2f913fcc8](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/92517051/e0637013-3d41-4b8f-a935-ef2a9b29798a)

**Comment by hama3254** [comment]
The next release should fix this.

**Comment by luccaslil** [comment]
![Captura de Tela (1)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139336136/ce0c8369-ac19-4216-ae16-d3f526f63d1d)
help pls
