### ISSUE TITLE
Can't Download Anything [Error 400]

### ISSUE THREAD

**Issue by Amy54Desu** [hama3254/Crunchyroll-Downloader-v3.0#761]
Anytime I attempt to download no matter what setting, it will straight up refuse, giving this error followed by it saying "Something is wrong". This essentially makes it unusable.

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/69287652/926a1f01-1de3-4ba2-97dd-8f3217635832)

**Comment by 619beave** [comment]
I get this error sometimes.  Just close the program and reload it. It
always works for me. Also, make sure the video plays in a browser your
getting the link from

**Comment by Amy54Desu** [comment]
> 

I tried that multiple times, the video does indeed play to. But I still could not manage to download anything because of that exact same error

**Comment by jorensanbar** [comment]
The error is with the latest version apparently. I use the previous version: 3.15.1 and it does not present the error.

**Comment by hama3254** [comment]
@jorensanbar did you try the v3.15.4 or does v3.15.1 just work fine for you?


@Amy54Desu i am unable to find any issue here, with a premium account i was able to download the episode and without a premium account i am not able to watch or download this video.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/8258e914-a12c-4789-9448-3f87c8845180)

**Comment by jorensanbar** [comment]
Yes, I update to last 3.15.4 and get the error 400 message. So I return to 3.15.1 and Works again.

Same URL (One Piece E1065) in both version.

**Comment by hama3254** [comment]
i can not find any issue with the latest version, i also have no idea what change might affect the download behavior.
Are the settings the same in both versions?
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/b94783d5-992f-4e69-8ad0-ea1745654f02)

**Comment by jorensanbar** [comment]
Correct. Same settings in both version. (3.15.1-3.15.5).

I even even copy the User.config.dat file to test, and the error is always displayed. (I don't have a crunchyroll account)

Just pasted the link in version 3.15.1, everything works great.

**Comment by jorensanbar** [comment]
Tested: 3.15.6.

Bug fixed, download correct.
