### ISSUE TITLE
Random close

### ISSUE THREAD

**Issue by Aiyomi-Irirako** [hama3254/Crunchyroll-Downloader-v3.0#762]
Moinsen

Der Downloader schließt sich teilweise ohne irgendwelche Vorwarnung oder Crashmeldungen.
Passiert immer während dem Download oder wenn man ein Download hinzufügen möchte.

LG

**Comment by hama3254** [comment]
Ohne genauere informationen hab ich es schwer das nachzuvollziehen.
Beim nächsten mal bitte in die Windows Ereignisanzeige schauen, da sollte unter `Anwendung` ein fehler zu finden sein. 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/54f319ed-fe96-4642-b55c-7246eb158ae4)

**Comment by Aiyomi-Irirako** [comment]
Wie gewünscht hier die Infos:

<details>
  <summary>.NET Runtime Error:</summary>

Anwendung: Crunchyroll Downloader.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.InvalidCastException
   bei Microsoft.Web.WebView2.Core.CoreWebView2Cookie.get__nativeICoreWebView2Cookie()

Ausnahmeinformationen: System.NotImplementedException
   bei Microsoft.Web.WebView2.Core.CoreWebView2Cookie.get__nativeICoreWebView2Cookie()
   bei Microsoft.Web.WebView2.Core.CoreWebView2Cookie.get_Domain()
   bei Crunchyroll_Downloader.Main.LoadBrowser(System.String, Int32)
   bei Crunchyroll_Downloader.Main.GetCRVideo(System.String, System.String, System.String, Int32)
   bei Crunchyroll_Downloader.Main+_Closure$__298-0._Lambda$__0()
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()
</details>

<details>
  <summary>App Error:</summary>
Name der fehlerhaften Anwendung: Crunchyroll Downloader.exe, Version: 3.15.4.0, Zeitstempel: 0x647b436f
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.17763.4377, Zeitstempel: 0x4c0e81b1
Ausnahmecode: 0xe0434352
Fehleroffset: 0x00000000000349b9
ID des fehlerhaften Prozesses: 0x2740
Startzeit der fehlerhaften Anwendung: 0x01d99e0faf4c09b2
Pfad der fehlerhaften Anwendung: ???\Crunchyroll Downloader.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 984e141c-d1be-4185-8503-ed48ebb791e6
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
</details>

<details>
  <summary>Windows Error Reporting:</summary>
Fehlerbucket 2220844837756668359, Typ 5
Ereignisname: CLR20r3
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: Crunchyroll Downloader.exe
P2: 3.15.4.0
P3: 647b436f
P4: Microsoft.Web.WebView2.Core
P5: 1.0.1418.22
P6: 635799c6
P7: ff
P8: 8
P9: System.NotImplementedException
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4776.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER494C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER496C.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER496C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER497D.tmp.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Crunchyroll Down_5a44a609bebabc41e63c2c1e122589fee3c0bf_9f38dc43_15a44c1a

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 984e141c-d1be-4185-8503-ed48ebb791e6
Berichtstatus: 268435456
Bucket mit Hash: 2c71ccc704f742306ed2069d07bf09c7
CAB-Datei-Guid: 0
</details>

Wusste nicht genau was du benötigst, deswegen einfach mal alles was ich gefunden habe

**Comment by hama3254** [comment]
Der Fehler selbst kommt scheinbar bei. Auslesen des Cookies von dem Webview2 (Edge) Element.
Der Browser muss zum auslesen offen sein, was normalerweise gegeben ist weil ich den öffne und außerhalb des Bildschirm parke.

Was mich irritiert ist die `System.NotImplementedException` die vermutlich meint das die Funktion noch nicht eingebaut ist.
Das kann eigentlich nur heißen das du vlt mal deine [ Version der WebView2 Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) nachschaust und ggf. updatest

**Comment by Aiyomi-Irirako** [comment]
Also ich bin jetzt aufjedenfall auf der aktuellen Version.
Nur leider habe ich weiterhin das Problem, dass sich der Downloader sich zufällig schließt.

Soll ich nochmal die Ereignismeldungen schicken?

**Comment by hama3254** [comment]
Beim selben fehler bild wird es vermutlich die selbe meldung geben.
Beim genauen hinsehen ist mir aber aufgefallen das die windows version als `10.0.17763.4377` angebeben ist.
Was laut einer schnellen google suche Windows 10 von 2018 ist, damit würde auch `System.NotImplementedException` sinn machen.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/087c46ca-c17b-4f14-bc15-c2e5bade0da3)

Ich hab das leider nie auf was älterem als Windows 11 22H1 oder Windows 10 22H2 getestet.

**Comment by hama3254** [comment]
Kein plan ob das jetzt gelöst ist aber versuch ein update auf Windows 10 22H2 bis dahin mach ich hier zu.
