### ISSUE TITLE
There isn't Spanish from Spain

### ISSUE THREAD

**Issue by Mayansito** [hama3254/Crunchyroll-Downloader-v3.0#763]
There is not Español from Spain on 3.15.4 softsubs of CR. Only from LA.

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/98242308/595e2d9e-b8d6-40aa-9547-1d705a97ec88)

**Comment by hama3254** [comment]
>The form is to small which hides `Español (España)` below italian.
The next release will have fixed that.
>
>A fast workaround would be to use the [Tab-key](https://en.wikipedia.org/wiki/Tab_key) to nagivate to `Español (España)`  and enable it by using spacebar.
you can see what is selected by its black checkbox in this case one more press of tab would select `Español (España)` which than could be enabled with spacebar.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/a2bbd4c7-f46a-427b-b337-42d7e0cfadb1)
>
>you can verify that it is enabled with the default subs option since only active subs are option in there.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/d0b883a1-9777-4eb6-b267-8409655a6c23)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/754#discussioncomment-6080246_

**Comment by Mayansito** [comment]
Oke, thx!
