### ISSUE TITLE
"ScaledBorderAndShadow:yes" in subtitles scripts

### ISSUE THREAD

**Issue by MetalBat28** [hama3254/Crunchyroll-Downloader-v3.0#764]
**Is your feature request related to a problem? Please describe.**
I've noticed CR subs don't have the `ScaledBorderAndShadow: yes` header under the [Script Info], which leads to an incorrect display of them, because borders and shadows are not scaled correctly.

Without `ScaledBorderAndShadow: yes`:
![Screenshot 2023-06-17 130226](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/136856549/746afc6d-11e8-41a3-a8b2-9124a93a7aae)
![mpv-shot0083](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/136856549/14711b21-4d3d-454c-ad96-23de4ea4c734)

With `ScaledBorderAndShadow: yes`:
![Screenshot 2023-06-17 125128](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/136856549/07335fb4-5b27-41a2-b938-39b7a2b6491e)
![mpv-shot0085](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/136856549/9b26a0f1-8ed9-42a8-876e-6bfaf257de19)

**Describe the solution you'd like**
Could it be possible for this downloader to automatically add the `ScaledBorderAndShadow: yes`  header in each subtitles script?

**Describe alternatives you've considered**
It's not really an issue for me since I use mpv with some filters applied and so the subs are shown correctly. But using VLC, mpv without filters or other video players could lead to this problem. Adding the `ScaledBorderAndShadow: yes` or setting the correct resolution in `PlayRes{X,Y}` should fix the problem for all video players.

**Additional context**
I want to clarify that it's not downloader's fault (it works fine) but of CR subtitles.

**Comment by hama3254** [comment]
The downloader is not build to modify the subtitles.
This leads to the issue that there are 3 ways the downloader access the subtilte file from CR.

Without merged subs i use `curl` to get the subtitles as text and save them, here i could simply modify the data.

Merged with `ffmpeg - Default` download gives the urls for the video and subtitles to `ffmpeg` so the downloader is not in between the output and the source.

Merged with `Hybrid Mode` or `Hybrid Mode - keep cache` lets the downloader copy the input before getting it to ffmpeg for processing, here i also could add the line.

I probaly add a setting (Default - Off) for this on `Output` settings tab where i can toggle it based on those factors, this way i only have to modify the data at the hybrid mode and unmerged part without having to deal with any ffmpeg comand directly.

**Comment by hama3254** [comment]
it seems to work for me 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9a6ca630-9be2-493c-b0b6-64ee72b037ea)

**Comment by MetalBat28** [comment]
I tried with the Hybrid Mode and the new option activated and it worked! Thank you!
