### ISSUE TITLE
Queue changes

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#765]
I have some requests about queue:

1. Have process queue switch enabled as default
2. Arrows to change download order of selected onese plus a button to delete them
3. Have episodes index processed separately from queue, so that we can add more episodes when others are alread queued.

**Comment by hama3254** [comment]
> 1. Have process queue switch enabled as default

The default is off.

> 2\. Arrows to change download order of selected onese

The downloader is not build for bulk downloads, you rarely watch more than a season (12 epidsodes) per day so that is what i set as session target. 

> plus a button to delete them

a double click should delete items from the queue.

> 3\. Have episodes index processed separately from queue, so that we can add more episodes when others are alread queued.

i have no idea what you want to do but the last time i checked everything worked as intended.

**Comment by tormento** [comment]
> The default is off.

Ok. A matter of personal preferences.

> The downloader is not build for bulk downloads, you rarely watch more than a season (12 epidsodes) per day so that is what i set as session target.

Sometimes I download whole seasons in a row. If not possible, it's ok :)

> a double click should delete items from the queue.

Didn't know that. Will try ASAP.

> i have no idea what you want to do but the last time i checked everything worked as intended.

When you ask for the index of an entire anime/season, it goes in the queue and you need all the episodes to be downloaded to have what you want.

**Comment by hama3254** [comment]
> > The default is off.
> 
> Ok. A matter of personal preferences

You have to keep in mind there are more than just we two using the downloader.
The last version (v3.15.5) already has 304 downloads with the old v3.8.9 having close to 8800 downloads.
So i chose opt-in rather than opt-out if i have no strong reason otherwise.


> When you ask for the index of an entire anime/season, it goes in the queue and you need all the episodes to be downloaded to have what you want.

The season download can be redirect into the queue but does not have to.
So you can close the queue and use the season download without it.

**Comment by tormento** [comment]
> The season download can be redirect into the queue but does not have to. So you can close the queue and use the season download without it.

I mean download the index of a season, not a season itself. If you download an index when the queue is processing, it will go in queue too.

**Comment by hama3254** [comment]
I think i now see what you mean, it just adds the series url to the queue.
This seems due to the download count being full with the queued videos.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/b6645790-dd82-447c-9298-e13eb3e8d3d3)

**Comment by hama3254** [comment]
Series urls won't be added to the queue anymore if it's running.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/6a860da2-4ec1-438d-998c-eb8f885dcb43)

**Comment by tormento** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/2351785/e3e17cd4-2400-4c5a-97e9-6c027ed1714d)

Not exactly what I wanted. I'd prefer to have the index loaded in a new process separated from queue, so that we can add other seasons/episodes while the queue is downloading.

**Comment by hama3254** [comment]
>loaded in a new process separated from queue

the queue and the mass download run on the same thread and need to access shared ressurcess so this it not going to work even if wanted to.
