### ISSUE TITLE
Finished status

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#766]
Sometimes an episode reaches finished status, i.e. 100% written to disk, but the finished status is never shown.

It seems that happens more often, if not always, when processing from queue.

**Comment by hama3254** [comment]
i would need a [log file](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) to check why the downloader does not set the download as finished

**Comment by hama3254** [comment]
i can not help without any log.

**Comment by tormento** [comment]
@hama3254 
I have looked for errors in the log but I can't find any. I can do a video if needed.
