### ISSUE TITLE
Remove when finished

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#767]
Please add an option to remove downloaded episodes when completed without errors.

**Comment by hama3254** [comment]
You already can remove finished downloads. 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/a045297d-e072-4e7d-b7c4-86b2e9165dae)

**Comment by tormento** [comment]
I mean *all* of them at once. When you have 20/30 episodes, it'a a PITA do individually remove them.

**Comment by hama3254** [comment]
The simple solution would be to close the downloader and reopen it.

**Comment by tormento** [comment]
> The simple solution would be to close the downloader and reopen it.
If you close the downloadee, the program simply quits.

I want to remove downloaded files while still processing queue.
