### ISSUE TITLE
closed captions CC are not downloaded when English dub selected 

### ISSUE THREAD

**Issue by Dijitul1029** [hama3254/Crunchyroll-Downloader-v3.0#769]
**Describe the bug**
No matter what options I choose, I can’t download closed captions from crunchyroll softsub inside the video, mkv or mp4. I can download them if I choose subtitles only, but when I mux them back in then they’re positioned incorrectly with odd placement to the left. Regular Japanese subtitles work fine, but not closed captions when English dub is selected. Yes I’ve made sure the closed captions box is ticked in the program and enabled on the site, and I’ve tried in a different video player, the regular English subtitles are downloaded instead of closed captions. 

**Where does the issue happen?**
crunchyroll, softsub, latest version 15.4

**Comment by hama3254** [comment]
i would need the video you tried to check this since CC are pretty rare on CR.

**Comment by Dijitul1029** [comment]
An example of a show that has CC is AOT https://www.crunchyroll.com/watch/GMKUX507P/above-and-below

**Comment by hama3254** [comment]
it seems to me like they don't use the subtitle format as it is supposed to [(from what i can read in this article)](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API)
i added a `Crunchyroll-Downloader-v3.15.5.1.zip` to the latest release, `mkv` with `srt` looks fine to me with the new option 'remove CC Style' below the merge option.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/01a8d14e-5d80-4182-8539-8bad95438496)

**Comment by hama3254** [comment]
without any negativ answers i assume it works fine and close this, if there is anything new feel free to re-open this issue or a new one.
