### ISSUE TITLE
Simultaneus Downloads not working

### ISSUE THREAD

**Issue by Setolein** [hama3254/Crunchyroll-Downloader-v3.0#77]
Hi there

I've downloaded the new version of your Crunchyroll Downloader version 3.55 and have a Problem with it.

a long time ago i downloaded a complete anime in a row, 12 episodes, it was showing in the window of the downloader but since today i can not download multiple episodes in one time is there a reason for that? systemchanges from crunchyroll? or your programm?

when i go to settings and want change the settings to 12 simultaneus downloads and hit the save/exit button it doesn't save the settings at all

please help

**Comment by hama3254** [comment]
If you have re-encoding enabled in the output settings then the simultaneus downloads is maxed out with 2 for "nvec" due to nvidia driver limitations and 1 for "libx26x" because the re-encoding takes mostly 100% CPU anyways.

**Comment by Setolein** [comment]
thanks for the reply 

i don't have re-encoding enabled,
i don't have a Nvidia Card 

Cpu : Ryzen 7 2700x
GPU: Radeon Graphics Card

so that's that :-)

**Comment by hama3254** [comment]
There should no other way that the setting can be applied wrong. I directly use the number from the controll :
`If InStr(FFMPEG_CommandP1.Text, "nvenc") Then`
 `           NumericUpDown1.Value = 2`
`ElseIf InStr(FFMPEG_CommandP1.Text, "libx26") Then`
 `           NumericUpDown1.Value = 1`
`End If`
` rk.SetValue("SL_DL", NumericUpDown1.Value, RegistryValueKind.String)`
`Main.MaxDL = NumericUpDown1.Value`
 Please send me screenshots of your current settings.

**Comment by Setolein** [comment]
So here are the screens

![1](https://user-images.githubusercontent.com/73212059/96803967-fd326200-140d-11eb-87a1-940f6100a93d.PNG)
![2](https://user-images.githubusercontent.com/73212059/96803968-fdcaf880-140d-11eb-954a-2026c5c605f9.PNG)
![3](https://user-images.githubusercontent.com/73212059/96803971-fe638f00-140d-11eb-840f-ded47f6a0ff0.PNG)
![4](https://user-images.githubusercontent.com/73212059/96803972-fe638f00-140d-11eb-86d3-c433ad6e0afa.PNG)

**Comment by hama3254** [comment]
> i don't have re-encoding enabled,



> So here are the screens
> 

That looks to me as it is enabled.

> ![2](https://user-images.githubusercontent.com/73212059/96803968-fdcaf880-140d-11eb-954a-2026c5c605f9.PNG)

Please check the checkbox at the bottom and change the "-c:v libx264" to "-c copy" that disables the re-encoding and you can change the download count again.

Note : the checkbox is just there to keep users from accidently changing the setting and not an enabled/disabled button.

**Comment by Setolein** [comment]
after i checked the checkbox and changed the settings it worked thank you. 
my question is 
how does this work. i downloaded a new archive from the version 3.55 and i didn't change the settings after i first run the program.

thank you again it worked ;-)

Stay Safe and Strong

**Comment by hama3254** [comment]
The default is "-c copy" but the settings does get saved in the windows registry so each version uses the same settings.
