### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by nigoki2** [hama3254/Crunchyroll-Downloader-v3.0#772]
Hi.
Since this morning the downloader can't connect to Crunchyroll with a 403 error.
I tried with the last three releases.

<a href='https://www.hebergeur-image.com/'><img src='https://www.hebergeur-image.com/upload/31.187.69.210-6499318878d12.JPG'/></a>

No problem using Firefox from PC.
Thank you.

**Comment by hama3254** [comment]
please check the version of your WebView2 by opening `edge://system/` in the downloader.

i for example have version `114.0.1823.58`

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/f3882e4a-805b-4625-b3b1-6cf47b7c4e6b)

**Comment by nigoki2** [comment]
I have the same.
<a href='https://www.hebergeur-image.com/'><img src='https://www.hebergeur-image.com/upload/92.167.243.236-6499acd4007ed.JPG'/></a>
After some research, maybe the problem is that CR blocks the downloader after serveral downloads, considering it like spam.

**Comment by nigoki2** [comment]
Finally the probem comes from my antivirus. I don't know why since I changed nothing.

**Comment by hama3254** [comment]
It's good to know that you found the cause.
If you could add the specific software you have this could be helpful for similar cases in the future.

**Comment by nigoki2** [comment]
I use Kaspersky.
By the way hama, thank you for your program and for updating it!
