### ISSUE TITLE
Hardsubs not found

### ISSUE THREAD

**Issue by FarahNakahara** [hama3254/Crunchyroll-Downloader-v3.0#775]
**Describe the bug**

When I start the program, I put the settings so that it downloads the anime with the hardsubs placed directly in the video, and I put it to download, it throws me a dialog box that cannot find the hardsubs and an error line that I show below.

The funny thing is that if I download the app and put a video to download for the first time, it does it without problems, but the others no longer work.

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll, Funimation]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.15.5.1]

**Screenshots**

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/137580595/fd4a79e2-e52b-4bd5-86de-3c8d7247fc2e)

**Additional context**

**Comment by hama3254** [comment]
It is possible for dubbed episodes to have the hardsubs missing.
I added a settings to account for that a while ago.
Otherwise there should be a dialog with a drop-down that allows you to select the raw version.
The error from the screenshot happens if you don't input anything and close the dialog.
