### ISSUE TITLE
error in URL

### ISSUE THREAD

**Issue by belgarrub** [hama3254/Crunchyroll-Downloader-v3.0#776]
[**Describe the bug**

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll, Funimation]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.8.7.2]

**Screenshots**

**Additional context**
Add any other context about the problem here.]
![error](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/138143963/95cdf20c-b173-46e6-b9be-a4a9c38998f3)
![error2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/138143963/0f4a9942-41da-4cda-83f3-3f98aaf550b4)
I get this error in the application's web browser and it won't let me open the crunchyroll page or any other page.

**Comment by hama3254** [comment]
This looks like you just need to get the  [WebView2 Runtime from this Microsoft page](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)

**Comment by belgarrub** [comment]
if that was the problem, thank you very much, thank you for creating and updating this wonderful application.

**Comment by hama3254** [comment]
i assume it worked for you so i get to close this.
