### ISSUE TITLE
Crunchyroll Chapter doesn't work

### ISSUE THREAD

**Issue by werewolf004** [hama3254/Crunchyroll-Downloader-v3.0#779]
**Describe the bug**
On Crunchyroll, CR chapter is ticked, but it doesn't work, no chapter in the MKV. Already try to generate a new config file from a fresh download of the apps but nothing change. Checked the config.dat, CR Chapter is on True.
It already work on previous rlz but not since few month (maybe something stored in regedit or others??)

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: CR Chapter enable, hybrid mode (default mode tested and same probem), 
 - Version 3.5.15.3 but already have problem in 3.5.14 and previous rlz

**Screenshots**

**Additional context**

**Comment by hama3254** [comment]
CR chapters can only work if CR has some available.
As I added that feature it looked liked they roll that out to all episodes but this is not the case, I have even seen some examples of chapters getting removed again.

**Comment by werewolf004** [comment]
Ok, weird because when I dl some (example "mashle"), I've got chapter on, 10 11 but not 12, same for 8, I've downloaded the 8 2 times, the first time it don't have the second time it got chapter (downloaded the first time 2 weeks ago and the second time yesterday). But ok no problem ;)

**Comment by hama3254** [comment]
The downloader requests the data for the chapters from there api on every download if enabled.
If there are not available or any other error occurs for the chapter data it's simply ignored since it is not any real issue just a mild inconvenience.

**Comment by BattouKen** [comment]
only first chapter in CR downloader 3, cxrunchi-cli all chapters same video

https://www.crunchyroll.com/es/watch/GQJUG359N/succeeding-the-past
![Sin título](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/81390696/cd4618ff-c4b6-48ee-a386-2c5bcd487677)
