### ISSUE TITLE
Funimation subtitles is unknown

### ISSUE THREAD

**Issue by zenkomenko** [hama3254/Crunchyroll-Downloader-v3.0#78]
Funimation downloader downloads sub and mp4 file separately, is there any way to fix it?

**Comment by hama3254** [comment]
thats the default setting you have.
you can merge the subtitle either as soft-subtitle with the output settings or burn the subs into the video as hardsub
![grafik](https://user-images.githubusercontent.com/52826614/97010293-7bddeb00-1545-11eb-8304-f51f668a5e4d.png)
