### ISSUE TITLE
System.Exception: Error - Getting curl: [22] The requested URL returned error: 400

### ISSUE THREAD

**Issue by buonda** [hama3254/Crunchyroll-Downloader-v3.0#784]
When I launch a download, I receive the attached error.

![error](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139282869/fd593f93-7c3f-4b72-8d69-8de31aa86b84)

**Comment by hama3254** [comment]
This looks the same as #761 where one user uses a older version as workaround and another claimed a restart helps with this issue.
I could not find any cause for that issue yet.
