### ISSUE TITLE
system.Exeception: Error - Getting

### ISSUE THREAD

**Issue by luccaslil** [hama3254/Crunchyroll-Downloader-v3.0#785]
Enter your version below, it can be found in the "About" section of the settings.
Version : v3.15.5.3

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>
  <summary>Insert the logtext before the second details</summary>
    
</details>

![Captura de Tela (1)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139336136/ce28342d-32b3-453e-b999-62f5471fccd3)

**Comment by hama3254** [comment]
See #784 or #761
