### ISSUE TITLE
Curl SSL issue

### ISSUE THREAD

**Issue by gcanti73** [hama3254/Crunchyroll-Downloader-v3.0#788]
I'm using actual latest release 3.15.6, when I try to start download I have the error

System.Exception.Error - Getting curl: (60) SSL certificate problem: unable to get local issuer certificate 

I attach the complete error report.

![Crunchyroll SSL eror](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139678967/ce91e7d3-7e17-4822-ad9e-cdc45820db48)

**Comment by hama3254** [comment]
This is some kind of issue with the `curl` application. 
I work with it as they describe here [https://curl.se/docs/sslcerts.html](https://curl.se/docs/sslcerts.html) below point 4.

>>If you are using the curl command line tool on Windows, curl will search for a CA cert file named "curl-ca-bundle.crt" in these directories and in this order:
>>
>>    1.application's directory
>>    2.current working directory
>>    3.Windows System directory (e.g. C:\windows\system32)
>>    4.Windows Directory (e.g. C:\windows)
>>    5.all directories along %PATH%
>>

This mean you should have a `curl-ca-bundle.crt` inside the `lib` folder of the downloader.
If this is the case and it does not work than the downloader has the option below:

> not the real solution but ignoring it with [--insecure](https://curl.se/docs/manpage.html#-k) should work.
![grafik](https://user-images.githubusercontent.com/52826614/209685530-69bd918d-7170-4ed3-a576-8c5a4c5db820.png)

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/643#issuecomment-1365972076_

**Comment by gcanti73** [comment]
Thank you for the quick reply, but I already tested the "add --insecure"... whith no results, i have the same error.

I will try it on a different PC, maybe it works.

**Comment by gcanti73** [comment]
Just to make you know: I found what was the problem. The Avast antivirus blocks the application, disabling it the issue disappears.

**Comment by hama3254** [comment]
> but I already tested the "add --insecure"... whith no results, i have the same error.

that should not be possible, since that error is part of a check that is supposed to be skipped [according the documentation](https://curl.se/docs/manpage.html#-k)


> Just to make you know: I found what was the problem. The Avast antivirus blocks the application, disabling it the issue disappears.

Good to know that it works now and that the anti virus can cause this.
