### ISSUE TITLE
Remove limitation

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#789]
Hello, could you removed the daily download limitation?

**Comment by hama3254** [comment]
There is no artificial limit by me.

**Comment by x3inspire** [comment]
> There is no artificial limit by me.

But as i remember, last time you got replied to someone you said the program was limited to XX download daily. It's more than enough for normal user to watch for daily.

**Comment by hama3254** [comment]
> you said the program was limited to XX download daily.

This is not exactly what I said, I said more or less if the Downloader is able to get 12 episodes than I see this as working.

12 episodes ( close to 5h at 24min per episode) should be enough for most as you already know.

>It's more than enough for normal user to watch for daily.
