### ISSUE TITLE
2 english subtitles

### ISSUE THREAD

**Issue by TheWizard-maker** [hama3254/Crunchyroll-Downloader-v3.0#790]
Hello, thanks for this awesome downloader.
I have a french account on crunchyroll. There is two differente animes my hero academia on a french account : 
- My hero academia (Vo) japanese dub + subs
- My hero academia (Vf) multi dub + subs (exept japanese)

When i select the english one, I have only one of the 2 subs available. I have only the forced one and i don't have the full one
I don't have the same issue with other dub because the other dubs have only a forced subtitle. Only english dub has forced + full subtitle

I wonder if it is me who have not well configured the downloader or if something is missing ?
thank in advance

**Comment by TheWizard-maker** [comment]
the name on crunchyroll are "english" and "english CC"

**Comment by hama3254** [comment]
This anime has closed caption, this are subtitles for people with hearing issues.
The normal subtitles for dubbed episodes only contain text on the screen (if there are even some).

**Comment by TheWizard-maker** [comment]
Ok is it possible to download them also by changing the parameters of the downloader or is it impossible ?

**Comment by hama3254** [comment]
If you use the `use captions if available` option then the Downloader will get captions instead of subtitles ( if they are available).
