### ISSUE TITLE
Check for missing/corrupted pieces

### ISSUE THREAD

**Issue by Overrage14** [hama3254/Crunchyroll-Downloader-v3.0#794]
Sometimes when my network goes down or similar, some of the pieces the downloader should download don't get downloaded at all, or the pieces get only partially downloaded.

After the download, there should be a check that checks if all of the pieces got downloaded and if there are abnormally small pieces (excluding the last piece). The downloader should then download the missing/corrupted pieces or at least inform about them.

**Comment by hama3254** [comment]
We already have a system for that which you can turn on and set to your personal error toleranz.
[grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/d9a0f205-e845-4448-a466-a1f50a11fc30)

**Comment by Overrage14** [comment]
So if I set that to 1, it will stop the download if it can't download one of the pieces?

**Comment by hama3254** [comment]
It should pause the Download and you can restart it but it's hard to test for me.

**Comment by Overrage14** [comment]
At least when I tried to replicate it artificially it looked like it was working.
