### ISSUE TITLE
Browser won't load, stays blank

### ISSUE THREAD

**Issue by wraith4081** [hama3254/Crunchyroll-Downloader-v3.0#796]
**Describe the bug**
For the last few weeks the browser has not loaded. It stays empty. When I try to enter through chrome myself, there is no problem. I can't download anything because the browser won't load.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: Default or Other Settings
 - Version: 3.15.6, 3.15.1, 3.15

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/54374743/fc8209ef-c2ba-4c29-9e74-4328484073c7)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/54374743/b0cb8386-2518-4105-87ef-4dc10eb4342a)

**Additional context**
I thought it might be related to #740 , but the problem is actually in a very different place

**Comment by hama3254** [comment]
you probably miss the [WebView2 Runtime (which you get from this Microsoft page)](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)

**Comment by wraith4081** [comment]
It's still the same. Could it be related to the fact that my current operating system is Windows Server?

**Comment by hama3254** [comment]
I don't test and support Windows Server at all.
The downloader is only for personal use.

**Comment by MechKyo** [comment]
I have the exact same problem, and it didn't solve by downloading the WebView2 Runtime (from the link above), or at least I couldn't install it, if it had to be installed.
I have win 8.1

**Comment by hama3254** [comment]
> or at least I couldn't install it, if it had to be installed.

Windows 8.1 is not supportet since WebView2 Runtime version 109. ([source](https://learn.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms))
