### ISSUE TITLE
Error: "Status: nothing found" - Concerts/music videos

### ISSUE THREAD

**Issue by GHCripto** [hama3254/Crunchyroll-Downloader-v3.0#797]
Hi, I can't download concerts/music videos
When I try to download one of these, it says "Status: Processing URL" with a 30 second countdown, but upon completion I get another message saying "Status: nothing found".

It works fine with Anime Eps, but sadly it doesn't work with concerts/music videos for me.
I'm on v3.15.6

**Screenshot**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/64995694/e573c4af-7d2f-4073-baef-b067f0f7383f)

**Comment by hama3254** [comment]
with #740 there are some api calls missing. 
i directly added the calls for that type of content but we can only see how long the old api is still working.
[You find an updated release here as `Crunchyroll-Downloader-v3.15.6.1.zip` ](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.15.6)

**Comment by GHCripto** [comment]
thank you very much, now it works fine :) 

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/64995694/bcc8bdf7-7224-4d41-8780-3a6b186a4a9b)
