### ISSUE TITLE
RE: Vorschlag wegen den Links 

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#8]
>> D: Nen Link Kopier Button im Browser das man sich den Link von den Anime leichter Kopieren Kann.

> in welchem Browser ? der normale oder vom Downloader?  in die adresszeile zu klicken und CTRL + a dann CTRL + C  und dann im Downloader CTRL +V sollte ja einfach genug sein.
 
Der eingebaute Gecko Browser, es gibt ja keine URL Leiste man muss ja den Link sich irgendwie erschnorren von den Teilen in Twitter Button, währe cool wenn man nen Knopf oben oder an der seite von den Browser hat um den Link zu Kopieren oder ne Adressleiste.

**Comment by hama3254** [comment]
> > > D: Nen Link Kopier Button im Browser das man sich den Link von den Anime leichter Kopieren Kann.
> 
> > in welchem Browser ? der normale oder vom Downloader?  in die adresszeile zu klicken und CTRL + a dann CTRL + C  und dann im Downloader CTRL +V sollte ja einfach genug sein.
> 
> Der eingebaute Gecko Browser, es gibt ja keine URL Leiste man muss ja den Link sich irgendwie erschnorren von den Teilen in Twitter Button, währe cool wenn man nen Knopf oben oder an der seite von den Browser hat um den Link zu Kopieren oder ne Adressleiste.

Ne leiste in den Browser zu bauen geht, nur warum sollte das nötig sein?
Entweder man hat die URL eingegeben oder man hat die Übersicht hinzugefügt also sollte es in normalen Browser ein Klick sein die selbe Seite aufzurufen.
