### ISSUE TITLE
Audio segments missing and other bugs

### ISSUE THREAD

**Issue by LioMajor** [hama3254/Crunchyroll-Downloader-v3.0#80]
Crunchyroll Downloader: Version 3.5.6

Internet: Broadband 100mbit
CPU: Intel i9 9900k
RAM: 64 GB DDR4
GFX: nVidia GTX 1080 Ti
HDD: 2x 4 TB
Re-encoding is disabled
Re-direct multi-download to queue doesn't matter if on of off
Simultaneous Downloads: 1
I tried resolution in 1080 and 720
Softsub, no hardsub

- There are a lot missing audio segments, almost every second file at least once. The audio is ' silent ' at the missing part
(downloading again works or has missing audio segment at another timing)
- Sometimes the program closes itself when downloading only subtitle using ' subtitle downloader '
- Every now and then, the download just stops and downloads the next file even if it's set to 1 per time
- After the dl stopped itself when a file is not complete, the program ignores adding video's, but works adding the second time
- There is no error handling when the log shows ' failed '. No marking the file as bad or offering to download it again nor fixing

**Comment by hama3254** [comment]
>There are a lot missing audio segments, almost every second file at least once. The audio is ' silent ' at the missing part
>(downloading again works or has missing audio segment at another timing)

please [enable the log file](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) and send it to me here (just drag and drop it into github) 

>Sometimes the program closes itself when downloading only subtitle using ' subtitle downloader '

i would need the windows event log from the time that happens to see the issue 

>Every now and then, the download just stops and downloads the next file even if it's set to 1 per time

if the first download stopped and it is marked as "finished" ( the process has stopped) then the current download count will be 0 and it does the next video.
 
>After the dl stopped itself when a file is not complete, the program ignores adding video's, but works adding the second time

Please add some details what you want to do, if the download failed and is resisted as not running then the adding should work, if is false counted as running then it should tell you that the new episode has been added to the queue. 


>There is no error handling when the log shows ' failed '. No marking the file as bad or offering to download it again nor fixing

there is a error handling if the process has crashed without being at 100% then you should get this :

![grafik](https://user-images.githubusercontent.com/73110502/96442467-1915e800-1203-11eb-8211-1df067b2fc7f.png)

**Comment by LioMajor** [comment]
I noticed the missing audio very late and i was already at episode 50 of world trigger, 30+ files had ' failed ' in logs, thus i deleted everything bcuz the subs have the same timing to the files i already own. I remember it said ' failed xxx segment ', when i checked it where it happened, audio was missing.

**Windows-log:**```

Name der fehlerhaften Anwendung: Crunchyroll Downloader.exe, Version: 3.5.6.0, Zeitstempel: 0x5f909f1a
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.18362.476, Zeitstempel: 0x540698cd
Ausnahmecode: 0xe0434352
Fehleroffset: 0x001135d2
ID des fehlerhaften Prozesses: 0x4c44
Startzeit der fehlerhaften Anwendung: 0x01d6aeb974a28a89
Pfad der fehlerhaften Anwendung: F:\Crunchyroll-Downloader.v3.5.6\Crunchyroll Downloader.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: e89de136-eb2a-46c0-b864-6d1b65109fa7
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

The file that stopped, never was marked finished or added ' press the play button again to retry '.
It just hung not downloading anymore and the next file from queue started.
I had to stop queue manually and add the file again that was clearly broken to dl it again.
Also the files with missing audio, even the log contained ' failed ', they counted as finished without retry notice.
PS: The pause button didn't work to simply restart the file that stopped.

**Comment by hama3254** [comment]
>  I remember it said ' failed xxx segment ', when i checked it where it happened, audio was missing.

do you mean something like that?

`10.10.2020 22:23:14[hls @ 063e3ec0] Failed to open segment 240 of playlist 0`

in any case not only the audio but also the video should be missing with that kind of error (the picture should be freezed for a view seconds) 

<details>
<summary> for the windows log, there should be two logs, i need that from the .net runtime that looks like this : 
</summary>

![grafik](https://user-images.githubusercontent.com/52826614/97777883-63885480-1b73-11eb-861f-ecdb372815d6.png)
</details>


> The file that stopped, never was marked finished or added ' press the play button again to retry '.
> It just hung not downloading anymore and the next file from queue started.

i don't see a way how this even can happen, the current code for detecting the current download count has the same criteria as the crash handling.
The crash handling just also checks if the process is not already 100% 


> Also the files with missing audio, even the log contained ' failed ', they counted as finished without retry notice.

well the code for finished detection is different, i look at the ffmpeg log for `muxing overhead:` as message but i can add the detection of `Failed to open segment` into the next version to catch the failed download directly when it happens. 


> PS: The pause button didn't work to simply restart the file that stopped.

i looked at code for that and rememberer another thing i forgot to ask did you use the hybride mode ? 
it seems like i did not change the try again function to work with the hybride mode that could be a reason why that did not work.


> After a file hung, the first attempt to add a new queue to dl the broken file again didn't work, i had to do this twice.

there should be a message if you want to delete the already existing file, if you press "Yes" was the first file deleted without a problem or did that message showed up at the second try again?

**Comment by LioMajor** [comment]
It's possible that there were missing frames too, at least the once i checked looked okayish except for the audio.

**That's the other log i found:**
```
Anwendung: Crunchyroll Downloader.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.Net.WebException
   bei System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
   bei System.Net.WebClient.DownloadString(System.Uri)
   bei System.Net.WebClient.DownloadString(System.String)
   bei Crunchyroll_Downloader.Main.DownloadSubsOnly()
   bei System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()
```

Hybride mode was deactivated.

The 'delete' message appeared only on the second time.
At the first try, it doesn't download and empties either the url or name after clicking download.

**Comment by hama3254** [comment]
> One thing that would be good to add, is to show the download speed as well.

that's already available with the Hybride Mode : https://www.youtube.com/watch?v=s_SY3RM1F3Y

> The 'delete' message appeared only on the second time.
> At the first try, it doesn't download and empties either the url or name after clicking download.

Then the add process does not what it should, i take a look on that later.

> The file that hung was still in download mode, I guess there a problem with the timeout check if the datastream stops incomplete.

i can try to change the detection of crashed downloads from if the process is not running and is not at 100% to a timeout since the last data have been revived from the ffmpeg process.

> It seems that without proper checks, defective files are possible without noticing.

I'm working on that : https://www.youtube.com/watch?v=3jEd5BS7TuE 
i simulated an error with an self made console app and that seems to work.


> That's the other log i found:

thanks for that i will work on that after the download problems

**Comment by hama3254** [comment]
the problem with the subs download crashes should be gone now, it will display an error now.

the segment fail detection has been added, however you can choose to ignore it ( as seen in the video : https://www.youtube.com/watch?v=3jEd5BS7TuE )

> i can try to change the detection of crashed downloads from if the process is not running and is not at 100% to a timeout since the last data have been revived from the ffmpeg process.

that is not yet been done, but i added the `process.Exited` event to deal with a not running process.

**Comment by hama3254** [comment]
everting from here should be done and working in the v3.6 pre release, i close this now if there are any other question just make a new issue.
