### ISSUE TITLE
Hindi dubs show up as Error

### ISSUE THREAD

**Issue by cumbreadsticks** [hama3254/Crunchyroll-Downloader-v3.0#800]
**Describe the bug**
In the drop down menu to select Languages and season to download , the language Hindi is hsown as Error

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Language Options
 - Version v3.15.6.1

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/93240936/e42cc92e-6d29-4176-81b2-8abf7e7c275b)

**Additional context**
Crunchyroll has started to add new Hindi Dubs to its Crunchyroll India catalog recently. The Download works fine its just a visual Bug showing Hindi as error.

**Comment by hama3254** [comment]
As noted in #792 there are a lot languages to add but i don't have much time right now.

**Comment by cumbreadsticks** [comment]
Its totally fine. I dont care much about small issues like this. The tool works perfectly and thats enough.
