### ISSUE TITLE
Audio download problem

### ISSUE THREAD

**Issue by Rexfarid2** [hama3254/Crunchyroll-Downloader-v3.0#801]
Hello Good morning, is it normal that when I choose the option to download AAC Audio all the chapters say 480p? I ask because maybe the audio is downloaded at low quality, I hope you can fix it please...
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/135890020/17a0fe74-9924-449b-a489-b0888b4b3044)

**Comment by hama3254** [comment]
That is on purpose, 480p has the same audio as 1080p and since I can not download only the audio using 480p was the way to go to save bandwidth.

**Comment by Rexfarid2** [comment]
> That is on purpose, 480p has the same audio as 1080p and since I can not download only the audio using 480p was the way to go to save bandwidth.

but there you can see that the audio weighs 16.99MB instead I tried downloading the entire chapter with video in 1080p and the audio weighs 22MB which is the normal weight of a chapter...

**Comment by Luskk-hl** [comment]
> Hello Good morning, is it normal that when I choose the option to download AAC Audio all the chapters say 480p? I ask because maybe the audio is downloaded at low quality, I hope you can fix it please... ![image](https://user-images.githubusercontent.com/135890020/263585265-17a0fe74-9924-449b-a489-b0888b4b3044.png)

The audio is really downloading on low quality, i have the same problem

**Comment by Rexfarid2** [comment]
> > Hello Good morning, is it normal that when I choose the option to download AAC Audio all the chapters say 480p? I ask because maybe the audio is downloaded at low quality, I hope you can fix it please... ![image](https://user-images.githubusercontent.com/135890020/263585265-17a0fe74-9924-449b-a489-b0888b4b3044.png)
> 
> The audio is really downloading on low quality, i have the same problem, to work around this problem, it's better to download the entire episode dubbed in 1080p and extract the audio later, I'm doing it like this.

Hello, yes at the moment I'm doing that downloading with video, I hope they fix it soon 😞

**Comment by hama3254** [comment]
i really don't think we need that but i added a hidden option to get 720p and 1080p 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/491781a9-c51f-4b02-856c-078072a74b0f)

**Comment by Rexfarid2** [comment]
> Realmente no creo que necesitemos eso, pero agregué una opción oculta para obtener 720p y 1080p. ![gráfico](https://user-images.githubusercontent.com/52826614/264413146-491781a9-c51f-4b02-856c-078072a74b0f.png)



> i really don't think we need that but i added a hidden option to get 720p and 1080p ![grafik](https://user-images.githubusercontent.com/52826614/264413146-491781a9-c51f-4b02-856c-078072a74b0f.png)
