### ISSUE TITLE
Crunchyroll error

### ISSUE THREAD

**Issue by Darkschneider77** [hama3254/Crunchyroll-Downloader-v3.0#804]
good evening I have a problem with crunchyroll when I copy the link and start the download I get an error message I have attached the photo. I wanted to know if it can be solved. Thanks

**Comment by Darkschneider77** [comment]
/
![IMG_20230904_191730](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/144053737/20630f0a-3e4d-472c-83b3-c507c6be487c)

**Comment by hama3254** [comment]
In issue #788 this was caused by the anti virus.
you can try disabling your antivirus or read #788 for other suggestions.

**Comment by Darkschneider77** [comment]
ok thanks it was the antivirus
