### ISSUE TITLE
Only English Subtitles are getting downloaded

### ISSUE THREAD

**Issue by Niwu34** [hama3254/Crunchyroll-Downloader-v3.0#805]
I'm trying to download the first episode of One piece with English and German Subtitles (Softsubs):
When I select to download them booth only the english subtitles get downloaded, when only german is chosen no subtitle file is getting downlaoded. I'm not sure if I have the wrong settings (See Screenshot). Any help is appreciated :)

**Where does the issue happen?**
 - Platform: [Crunchyrol]
 - Settings [Softsub]
 - Version [e.g. v3.15.6]

**Screenshots**
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/67392333/16aab89b-036d-461c-b6f3-8e1a4d2fd5d5)
**Additional context**

**Comment by hama3254** [comment]
The downloader skips softsubs if unavalible and for me only German is avalible so this might be the exact opposite for you.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/4ae9fb37-9ddf-4a84-ad01-46f93471bb26)

**Comment by Niwu34** [comment]
Thanks for the quick reply!
I found the culprit: I was using a VPN and even tho I was connected to a german Server only the following subtitle options were available:
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/67392333/f6492f9f-da96-4c50-8aee-cf37287a04a1)
So I either need to find a vpn server that booth support english and german or be happy with only english subtitles as I don't really feel comfortable using this wonderful piece of software without a VPN in germany haha
