### ISSUE TITLE
The application is unable to connect, please help!

### ISSUE THREAD

**Issue by Ishravi34482** [hama3254/Crunchyroll-Downloader-v3.0#806]
**Describe the bug**
App fails to connect after hitting download button

**Where does the issue happen?**
 - Platform: Crunchyroll
- Settings:
      - softsubs: english
      - simultaneous downloads: 4
      - dub: jap
      - default subtitles: [English]
 - Version 3.15.7

**Screenshots**

![Crunchyroll Issue](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/144633148/4e77a210-520d-4d21-b21e-ba95af6c9640)

**Additional context**

**Comment by hama3254** [comment]
In issue #788 the same error message was displayed due to the antivirus software interfering.

**Comment by Ishravi34482** [comment]
> In issue #788 the same error message was displayed due to the antivirus software interfering.

Thanks man! Sorry if I came off a bit rude, I just didn't know how to word my message. I promise, it was in good spirits. Thanks for your continued support for your program and for always helping to resolve issues! :)

**Comment by hama3254** [comment]
> Sorry if I came off a bit rude, I just didn't know how to word my message.

All good, i hope my answer was not not Rude either.

I assume the `Thanks man!` means this resolved the issue?
This also means I will close this issue in a view days.
Feel free to close it yourself if you read this and the downloader is working fine.
