### ISSUE TITLE
Series add blocked?

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#809]
Hi, after que list completed download and i tried to added new series i got these error:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/4635825/79a3fd1b-9902-4127-b1ed-7f3b03dd0a34)

I had to close the apps and open again to download, is that normal?

**Comment by hama3254** [comment]
the queue has be off.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/106b6546-0d77-4f70-a432-0af9d34d91a8)
