### ISSUE TITLE
Request: A subtitle only mode

### ISSUE THREAD

**Issue by KorigamiK** [hama3254/Crunchyroll-Downloader-v3.0#81]
Can you add a feature that downloads only the subtitle files in batch like by supplying it a url like [this](https://www.crunchyroll.com/naruto-shippuden/), please.

**Comment by hama3254** [comment]
> Can you add a feature that downloads only the subtitle files in batch like by supplying it a url like [this](https://www.crunchyroll.com/naruto-shippuden/), please.

Already in the downloader.
Settings -> Crunchyroll settings -> subtitle download

**Comment by KorigamiK** [comment]
Ooh, I didn't know that. Sorry. But I was wondering, since you have made such an elaborate, easy to use and a software that could be someone's dream. Why, haven't you added a readme file, showing all of its features and capabilities. Please consider making it.

Thank you very much
Regards.

**Comment by hama3254** [comment]
> Why, haven't you added a readme file, showing all of its features and capabilities.

to say it in one word : laziness 

A readme file is just pure work, nothing to enjoy other than the development itself.
To see at the end that every working is just satisfying [like this,](https://www.youtube.com/watch?v=ZHCH3rNWYS8) or [this](https://www.youtube.com/watch?v=s_SY3RM1F3Y) or [the new error detection.](https://www.youtube.com/watch?v=3jEd5BS7TuE)

**Comment by KorigamiK** [comment]
Hey, no problem. I understand that its your call to make a readme, I'll sub to your youtube channel for further updates : ) But I also wanted to ask if there is an option to use a proxy to access crunchyroll or funimation as many anime in my country are geoblocked. I wouldn't be surprised if you have already implemented this.
 
Thanks in advance
Regards

**Comment by hama3254** [comment]
> Hey, no problem. I understand that its your call to make a readme, I'll sub to your youtube channel for further updates : ) But I also wanted to ask if there is an option to use a proxy to access crunchyroll or funimation as many anime in my country are geoblocked. I wouldn't be surprised if you have already implemented this.

For crunchyroll is a feature in the crunchyroll settings to get the US selection, for funimation that does not work since even the videos itsef check for the country.

**Comment by KorigamiK** [comment]
Thanks I just needed to set the us cookie. Sorry for bothering you.
