### ISSUE TITLE
Download same episode twice or more times

### ISSUE THREAD

**Issue by Ivoyko** [hama3254/Crunchyroll-Downloader-v3.0#812]
I am in the last version even if i had same trouble with every version.
I download something and like i am not sure if everything was fine i download it a second time.
Result its that i have 2 files that should be exact file but isnt bc one its bigger than the other.
And that is all, i never know when i have the right file-episode.

**Comment by hama3254** [comment]
#798 has some explanation for possible download errors and option to reduce them.

I also need to add that Crunchyroll has different formats that the download can use which I never checked of they are identical in the output.
