### ISSUE TITLE
Error - Getting curl: (60) SSL certificate problem

### ISSUE THREAD

**Issue by Risaiola** [hama3254/Crunchyroll-Downloader-v3.0#815]
I'm using the latest version (3.15.7) on Windows 11 updated to the last version, when I try to download any series or single episode I receive that error:

![Crunchyroll-Downloader Error](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/145420514/93f76499-89be-4c77-845b-f90076781ec3)

I've tried to use version 3.15.6.1 and 3.15.4 and don't work, I receive that error every time

**Comment by hama3254** [comment]
It is likely the antivirus software like in #795

**Comment by Risaiola** [comment]
> It is likely the antivirus software like in #795

I am using kaspersky, do you know how I could handle it without closing the antivirus every time?

**Comment by Aiyomi-Irirako** [comment]
uninstall and use the one from windows which is anyway much better than other antivirus programs

**Comment by hama3254** [comment]
@Risaiola i would personally agree with @Aiyomi-Irirako that removing kaspersky is the best option.

Other options might be to use the [--insecure](https://curl.se/docs/manpage.html#-k) ( as seen here https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/795#issuecomment-1672753679) but i don't know how far kaspersky get's into the downloader in general.

the probably overkill option would be a [VM (Virtual machine)](https://en.wikipedia.org/wiki/Virtual_machine) for just the downloader
