### ISSUE TITLE
Softsubs are very small

### ISSUE THREAD

**Issue by zmarotrix** [hama3254/Crunchyroll-Downloader-v3.0#818]
**Is your feature request related to a problem? Please describe.**
The softsubs seem to come out WAY too small. 

**Describe the solution you'd like**
Make them scale up a bit larger. 

**Describe alternatives you've considered**
I tried to see if VLC had options to scale them up myself, but it seems the only way you can is to reencode the video. 

**Additional context**
Look how small. This is a normally 1080p monitor with a full screen window. 
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/3902321/ac76ca11-2a53-453a-807e-f3033e374df6)

**Comment by hama3254** [comment]
You can try the `ScaledBorderAndShadow:yes` from #764 and see if that helps with the size.
