### ISSUE TITLE
[Feature Request] Download and mux font

### ISSUE THREAD

**Issue by moi15moi** [hama3254/Crunchyroll-Downloader-v3.0#819]
**Is your feature request related to a problem?**
The mkv produced doesn't contains the font.

**Describe the solution you'd like**
An option to download and mux the font into the mkv.
It is needed to display properly the .ass sub

**Describe alternatives you've considered**
I am pretty sure there is an endpoint for the font.
It is needed, I can try to look for them.

**Comment by hama3254** [comment]
Please check #764, it contains options for the subtitles and has comparisons in it.
For me I look basically like on with that.

You should find the `ScaledBorderAndShadow: yes` on the `Output` tab of the settings.

**Comment by moi15moi** [comment]
I don't see how ``ScaledBorderAndShadow`` is related to this issue.
The issue is about muxing font, not about an problem with the subtitle.

**Comment by hama3254** [comment]
>I don't see how ScaledBorderAndShadow is related to this issue.
The issue is about muxing font, not about an problem with the subtitle.

Your claim why you need the font is:

>It is needed to display properly the .ass sub

And that option changes the subs as seen here.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9a6ca630-9be2-493c-b0b6-64ee72b037ea)

 Which also means you don't need the font.

**Comment by moi15moi** [comment]
Your player display the subtitle only because you have installed the font into your system.

If you would not have them installed, it wouldn't display the subtitle properly.

This is a common problem for .ass. We always need to mux the font into the mkv.

**Comment by hama3254** [comment]
This seems some individual problem of you.
I checked some subtitles and i see the most default fonts possible.
Something like `Trebuchet MS` or `Arial`.
