### ISSUE TITLE
The download process crashes just as it finds the video.

### ISSUE THREAD

**Issue by TheLastBrightShadow** [hama3254/Crunchyroll-Downloader-v3.0#82]
I had been downloading acouple of episodes of Yugioh ArcV just fine, but then realized that I had chosen the wrong download settings. I retried downloading them again and the software asks me if I want to overwrite the new ones. I select "Yes", but then the download quickly reaches 100% competition and just crushes. I went and deleted the repository folder that the software had created for the anime and tried downloading the episodes again, but it just repeated the same thing.

This is the log file: https://cl1p.net/uqziirvypfdvm
Crash window: https://snipboard.io/5IVklW.jpg

Note: (Im not using neither hybrid mode nor softsub mode, as i just want the raw episode.)

**Comment by hama3254** [comment]
You have enabled the re-encoding using the nvidia h264 encoder which can not be found.
`h264_nvenc @ 0734c240] Cannot load nvcuda.dll`
Disable it in the output settings (change the bottom setting to "-c copy" in the output settings) and try again.

**Comment by TheLastBrightShadow** [comment]
Oh, my fault. I appreciate your quick reply, and thanks for this amazing software!!!

**Comment by hama3254** [comment]
If everything is fine now I close this.
If you have any other questions please make a new issue.
