### ISSUE TITLE
Error while trying to start the Download of an episode

### ISSUE THREAD

**Issue by Nigueres** [hama3254/Crunchyroll-Downloader-v3.0#827]
**Describe the bug**
Error while trying to start the Download of an episode. I've tried different Animes.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: I've tried  different settings with and without subs etc.
 - Version 3.15.7

**Screenshots**
[Error Screenshot here](https://ibb.co/5F5ZZwp
)

**Comment by hama3254** [comment]
please check your anti virus, this has been the most common source if isses regarding curl.
