### ISSUE TITLE
My IP banned

### ISSUE THREAD

**Issue by x3inspire** [hama3254/Crunchyroll-Downloader-v3.0#83]
`The owner of this website (api.crunchyroll.com) has banned the autonomous system number (ASN) your IP address is in (24940) from accessing this website.`

Possible to allow my server IP for using US cookies please?

**Comment by hama3254** [comment]
> Possible to allow my server IP for using US cookies please?

No, `api.crunchyroll.com` is a server from Crunchyroll.
