### ISSUE TITLE
Incomplete series on Crunchyroll

### ISSUE THREAD

**Issue by NatsuFT36** [hama3254/Crunchyroll-Downloader-v3.0#832]
Hello, I have a doubt since in Crunchyroll the download is incomplete although finished since there are several incidents such as Our Dating Story: The Experienced You and The Inexperienced Me episode 2 since the original lasts 23:40 and the download lasts 23:37 as it could be some error.

**Comment by hama3254** [comment]
I guess you mean the same thing as #822.
Please check #822 for details but the short version is that CR has data missing from the stream file and I added a guess to the downloader but I can 
 only do that in `Hybrid Mode`.
