### ISSUE TITLE
SSL error when trying to download an episode

### ISSUE THREAD

**Issue by MinionAttack** [hama3254/Crunchyroll-Downloader-v3.0#836]
**Describe the bug**

Unable to download episode from Crunchyroll, SSL certificate error.

**Where does the issue happen?**

 - Platform: Crunchyroll
 - Settings: 
![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10078549/f582873e-ef02-4484-b4ba-609fdb2e240a)
![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10078549/cd8b1c0c-ee4f-48b3-816d-6269e731f44c)
![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10078549/26a48e86-9e78-49af-85a2-7e93a047d1eb)
![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10078549/8bf56afa-0666-4d2d-947e-c6f73f04628b)
![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10078549/68daecd3-e57e-4c13-b6b8-665085481053)
 - Version: 3.15.7 (clean installation)

**Screenshots**

![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/10078549/683d3d92-4eb5-4b2a-a3a2-83d691e5239a)

**Additional context**

N/A

**Comment by Kallango2003** [comment]
Since yesterday, I haven't been able to download any anime; it's showing the same error described above.

**Comment by hama3254** [comment]
With #788 the issue was caused by the antivirus software. if you use any other than the Winndows Defender than i would suggest you disable it.

@Kallango2003 did you install anything before the downloader stopped working?

**Comment by MinionAttack** [comment]
Hi, reading the other issue I saw that I also have Avast and the application added in exceptions but I still have the same problem.

**Comment by Kallango2003** [comment]
> With #788 the issue was caused by the antivirus software. if you use any other than the Winndows Defender than i would suggest you disable it.
> 
> @Kallango2003 did you install anything before the downloader stopped working?

I ran some tests here, and the issue was with Avast. I didn't realize the antivirus was the problem. I disabled it for 10 minutes, and it started working again. I apologize for the inconvenience and thank you for your quick response.

**Comment by MinionAttack** [comment]
Since our problems were related to Avast, I understand that nothing can be done by the application, right? If so, you can close the issue. Thank you for your time.
