### ISSUE TITLE
The chapter does not download completely and the video file cannot be opened

### ISSUE THREAD

**Issue by stiven0200h** [hama3254/Crunchyroll-Downloader-v3.0#837]
**Describe the bug**
When I try to download the next chapter ( https://www.crunchyroll.com/es/watch/GWDU8ED5Q/attack-on-titan-final-season-the-final-chapters-special-2 ) from crunchyroll the download starts normally , but when the download reaches 83% it skips the last 17% and goes to 100% without completely downloading the chapter, leaving a video file that I cannot open because I get the following error:

Can't play

This file cannot be played. The item's file format may not be supported, the file extension may be incorrect, or the file may be corrupted.

0xc00d36c4

( this happens to me with ffmpeg mode and hybrid mode )

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: ( Hardsubs: English ), ( Softsubs: null ), ( Download mode: ffmpeg ), ( Format: MP4 )
 - Version: 3.15.7.2

**Screenshots**
![Captura de pantalla (29)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/e4c1e3fd-b30c-4ce7-8927-448a47f47f76)
![Captura de pantalla (33)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/a93f7219-e7ce-4cb8-ac8e-8378226a4aa7)
![Captura de pantalla (34)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/e84cdd8d-df23-41b4-aafd-8630a02afa83)
![Captura de pantalla (35)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/72c4e2e6-6734-4d26-a0a8-df28aef8bb46)
![Captura de pantalla (31)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/eab6d883-5711-4734-a8b5-e42ea1b572e4)
![Captura de pantalla (36)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/42c70b73-9f8d-4727-a841-3d0e0780b87d)
![Captura de pantalla (32)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139007907/ebfad648-db34-450a-ac47-d19853825472)

**Additional context**
I have tried version 3.15.7 and 3.15.7.2 but the same problem occurs in both.

**Comment by hama3254** [comment]
This is an unusual behavior.
You can add the [ `ffmpeg log`](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) which gives details about the video file processing.
The strange part is I have never seen an unplayable file, the get corrupt past that failed point but not completely.
You can also try setting the `Download Mode` from `Default - ffmpeg` to `Hybrid Mode`.

**Comment by stiven0200h** [comment]
I was able to download it, I don't really know why I couldn't but I tried from another PC and if I was able to download it, I think it was a problem with the storage space on my PC.  Anyway, thank you very much for responding.
