### ISSUE TITLE
funimation error when i downloaded video about 2hr

### ISSUE THREAD

**Issue by teogaming201** [hama3254/Crunchyroll-Downloader-v3.0#838]
Enter your version below, it can be found in the "About" section of the settings.
Version : funimation

For version v3.15.7.2, I had a issue downloaded video about 2hrs, when downloaded, seem had stopped and 100%. sorry i had a bad english.

**Comment by hama3254** [comment]
Please check the log file and add it to here.

The logfile can be obtained from the right click menu and then either saving it or copying it to the clipboard

![grafik](https://user-images.githubusercontent.com/52826614/136704200-5b10f94f-c74f-408c-9ba9-13d9a3298ddb.png)

**Comment by teogaming201** [comment]
> Please check the log file and add it to here.
> 
> The logfile can be obtained from the right click menu and then either saving it or copying it to the clipboard
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/136704200-5b10f94f-c74f-408c-9ba9-13d9a3298ddb.png)

No, i mean from Funimation website, not chrunchyroll

**Comment by teogaming201** [comment]
Yes i will, wait

**Comment by teogaming201** [comment]
![Crunchyroll Downloader 13_11_2023 21_48_21](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/150650648/e083030b-2b05-4003-b5f2-1d15e29ea693)

man, this screenshot when download get stuck, but even had finished the video still crash when played

here the link:
[https://www.funimation.com/v/demon-slayer-kimetsu-no-yaiba/siblings-bond-4e3c5aec-26e7-11ec-b6c4-0242ac110002](url)

help me thanks

**Comment by hama3254** [comment]
> Also if you could add the URL I can try to check the Episode myself (if available for free since I don't have premium there as European)

This Movie is behind there paywall.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/dc86c68e-683c-42e9-8b28-11788c2ae1a8)

For now i can only recomment to change the download mode to `Hybrid Mode`

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/e5761b78-c775-457a-bddf-98ce7411962b)

For more details you can save the logfile and add it here, this should be enough to find your issue.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/aa3dc383-b82f-455b-8f6e-ecdfaec3f6a6)

**Comment by hama3254** [comment]
I guess you either gave up or successfully downloaded the episode.
Either way I will close this.
