### ISSUE TITLE
Something is wrong here 

### ISSUE THREAD

**Issue by dutchdragon3** [hama3254/Crunchyroll-Downloader-v3.0#839]
Perhaps it's my fold but when i try to add a video like: 

https://www.crunchyroll.com/watch/GYDK1Q796/i-recalled-the-memories-of-my-past-life
(first ep of My Next Life as a Villainess: All   Routes Lead to Doom! )

I'll get the error something is wrong here...

Can anyone help me please

**Comment by hama3254** [comment]
Please check your version and check the build in browser if you can access the episode.

Overall i can not see any issue with that Episode.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/6aa38a26-b639-43fa-812e-54a9e7ea968c)

**Comment by Nakatsan** [comment]
I got the same Error Message, only have this Error on my Windows 11 Laptop, on my Windows 10 Desktop there is no Issue.
![Screenshot 2023-11-18 190116](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/151395803/b8ecc612-3ea0-4b29-b9c2-b1e7cb51b81c)
![Screenshot 2023-11-18 190129](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/151395803/7df16920-d7f0-4f18-998c-8f80cb9615a3)

**Comment by hama3254** [comment]
The error in the first screenshot basicly says it can not find the server, which is not part of the downloader and should get handelt by Windows and your Router.

Check your internet connection and maybe the DNS settings.

**Comment by Nakatsan** [comment]
> The error in the first screenshot basicly says it can not find the server, which is not part of the downloader and should get handelt by Windows and your Router.
> 
> Check your internet connection and maybe the DNS settings.

Thanks alot, it helped :)
