### ISSUE TITLE
No namings

### ISSUE THREAD

**Issue by quamt** [hama3254/Crunchyroll-Downloader-v3.0#84]
When downloading content the titles are not being copied.
It only shows Show  Season - Episode 1 for example but not the title of the episode.
It would be great if it would have the full title of the episode too.

**Comment by hama3254** [comment]
This is actually the first time someone ask for this, they usually don't care because the current name system is good enough to know the order.
You can however if you download single episodes add the name below the URL.

**Comment by quamt** [comment]
Thank you for the enhancement

**Comment by hama3254** [comment]
You can i added the option to select  between the [episode number] the [episode name] and both 
it can be found in the " 2-Pre-Release-Crunchyroll-Downloader.v3.6.zip" from the "LA" test version : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation 

![grafik](https://user-images.githubusercontent.com/52826614/99878863-a2f11080-2c08-11eb-8bdc-e994bca146ea.png)

**Comment by Schizo1987** [comment]
Ist die Episoden Benennung nur für Crunchyroll gedacht? Da Funktioniert sie auch Tadellos aber bei Anime on Demand hingegen nicht.

**Comment by hama3254** [comment]
> Ist die Episoden Benennung nur für Crunchyroll gedacht? Da Funktioniert sie auch Tadellos aber bei Anime on Demand hingegen nicht.

Das kommt später, ich muss da die ganze Unterordnen Funktion eh noch hinzufügen und das kommt da gleich mit in einem.

**Comment by hama3254** [comment]
@Schizo1987 Sollte jetzt alles auch bei AoD gehen, sowohl Unterordner als auch die die Episoden namen

**Comment by hama3254** [comment]
Naming is added if there are any problem with it please make a new issue.

**Comment by Schizo1987** [comment]
Vielen Dank für die Umsetzung, du bist der Beste!!
Ich habe es jetzt getestet bei AOD und mir ist aufgefallen sobald ein Bindestrich im Episodentitel ist beschneidet er den Episodennamen. Als Beispiel bei der Episode 934 von One Piece ist alles in Ordnung.

One Piece 20 Staffel Wano-Land Sub Episode 934 Das Blatt wendet sich Der Dreischwertstil überwindet die Todesschwelle

**Bei den Episoden 935, 936 938 fehlen dann Textabschnitte.**

_Falsch: One Piece 20 Staffel Wano-Land Sub Episode 935 Zorro ist verblüfft_
**Richtig: One Piece 20 Staffel Wano-Land Sub Episode 935 Zorro ist verblüfft - Die schockierende Identität der mysteriösen Schönheit**

_Falsch: One Piece 20 Staffel Wano-Land Sub Episode 936 Meistere die Technik_
**Richtig: One Piece 20 Staffel Wano-Land Sub Episode 936 Meistere die Technik - Das Haki Wano-Lands, Ryuo**

_Falsch: One Piece 20 Staffel Wano-Land Sub Episode 938 Hohe Wellen werden geschlagen_
**Richtig: One Piece 20 Staffel Wano-Land Sub Episode 938 - Die Identität des edlen Diebes Kozo Ushimitsu**


Vielen Dank schon mal! MFG Schizo1987
