### ISSUE TITLE
Something is Wrong here Pt.2 

### ISSUE THREAD

**Issue by Canishan** [hama3254/Crunchyroll-Downloader-v3.0#840]
So basically my program kinda crashed and i don't know why. I saw someone else had the same problem but I couldn't fix mine by changing my DNS server. 
![problem](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/143884925/fe873ec3-381a-411b-b1b9-f6bf49ae2222)

**Comment by hama3254** [comment]
Your issue is most likely related to an antivirus software.
Is is more like to #788.
