### ISSUE TITLE
Can't download the subtitle files

### ISSUE THREAD

**Issue by jorensanbar** [hama3254/Crunchyroll-Downloader-v3.0#841]
Can't download the subtitle files. Last episode of One Piece. Spanish-Latam.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings Softsubs copy MKV File.
 - Version v3.15.7.2

**Comment by hama3254** [comment]
Please check if the desired subs are available on CR. New episodes are often available without all subs.
