### ISSUE TITLE
Cannot download anything

### ISSUE THREAD

**Issue by anmovi** [hama3254/Crunchyroll-Downloader-v3.0#842]
Nothing can be downloaded, the integrated browser does not load and does not allow login
![img](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/148601238/7e399c41-e6d5-4b00-81dc-237f5843140b)

**Comment by anmovi** [comment]
I have uninstalled everything related to Edge, is WebView2 part of the Edge browser?
Is it a mandatory requirement?

**Comment by hama3254** [comment]
The WebView2 is basically just a way to bring the edge browser into .net applications.
I use it to manage the cookies used for request.

I did a version without the browser in the past (see https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/617#discussioncomment-4335974) and while the code for that is in the downloader I more or less scrapped that idea.

> Is it a mandatory requirement?

So the answer is technically no, but you are on your own here.

Alternatives would be using a VM for the Downloader or a command line tool like `yt-dlp`

**Comment by anmovi** [comment]
At the moment I have opted for the quickest and easiest way, download Edge again and its functionalities, even so, I will try that alternative version without browser, thanks for answering and resolving my doubts, now everything works perfectly again.
