### ISSUE TITLE
Erro 403

### ISSUE THREAD

**Issue by flaviokalleu** [hama3254/Crunchyroll-Downloader-v3.0#843]
Hello, okay, I'm accepting this error, what could it be?
![Erro](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/145366104/6354b028-9c70-43ce-976c-4f803f112774)

**Comment by hama3254** [comment]
I assume the 5 to 6 downloads downloads you have running/finished did take longer than the Crunchyroll session is valid for
You can check that by restart the downloader and see if the episodes after 75 work fine now.
