### ISSUE TITLE
next download doesn't start until i clear completed

### ISSUE THREAD

**Issue by taiyoko** [hama3254/Crunchyroll-Downloader-v3.0#845]
So for bandwidth reasons i have this set to download one episode at a time, however, once the current episode is finished downloading, it won't start the next one in my queue until i clear the completed one. If it finished without errors, i want it to proceed to the next item without me having to go clear out the completed one every time.

**Comment by hama3254** [comment]
This is strange the intended behavior is to finish the download and then start the next one.
I am not aware that this is not working.
Please add a screenshot of the queue and the main settings page.

Also the [Log file](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) would be great.

You also should see the state of the download while deleting it, there are different Info/Error messages if you do it on a running download vs on a finished one.
