### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by uaetoon** [hama3254/Crunchyroll-Downloader-v3.0#85]
Hi, is there any possibility to add search feature , it will search in crunchyroll database and you can add to download

**Comment by hama3254** [comment]
The crunchyroll website has a search feature, every possible solution I can make would just be based on that so it would not bring any benefit.

**Comment by uaetoon** [comment]
I was thinking if i don't want to use the browser, and want to use the app only, you can close they issue, I will think for something else to add .
