### ISSUE TITLE
Download multiple dub at the same time?

### ISSUE THREAD

**Issue by Ansem93** [hama3254/Crunchyroll-Downloader-v3.0#857]
Hi,
I wanted to know if it would be possible to download an episode with multiple dub at the same time.
If it's not a feature already, would it be possible to add it?

**Comment by hama3254** [comment]
This feature has been requested in the past, but it's not directly possible.
The best we got can you see in #701 where the experience of other users is listed which also explain why i can't support this.

Also keep in mind with #853 most features are basicly untested so i don't know if this works currently.
