### ISSUE TITLE
Zero padding

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#858]
If possible, I'd like to have a zero padding option, i.e. how many digits the episode number has to have.

I find more readable:

01
02
03
…
12

instead of

1
2
3
…
12

and it's even worse when there are hundreds if not thousands of episodes.

**Comment by hama3254** [comment]
We already have this, i am just bad at naming things.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/8dea6899-3d22-42a2-9882-b094c87f11ee)

**Comment by tormento** [comment]
That's why I didn't notice it! ;)

Thanks.
