### ISSUE TITLE
In v3.16.2 no download is possible due to SSL curl error.

### ISSUE THREAD

**Issue by salvatoredimaro** [hama3254/Crunchyroll-Downloader-v3.0#859]
**In v3.16.2 no download is possible due to SSL curl error despite the option add "--insecure" to curl request is selected (please see the screenshot error).**

Thank you so much for you precious job!

Details:

 - Platform: Crunchyroll
 - Settings: see screenshots
 - Version: v3.16.2

<img width="416" alt="image" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/6160611/0d7fea37-aeab-4e7c-88da-7639b09fd30c">

<img width="416" alt="image" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/6160611/b67241da-b0b1-4e7d-9dc6-01068e2b72f0">

<img width="416" alt="image" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/6160611/61138b5d-cc7c-4b7e-95ed-1dc7a5fabf46">

<img width="306" alt="image" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/6160611/5ec95fa1-0818-44b3-aeb6-c77786732e66">

**Comment by hama3254** [comment]
please check your anti-virus since the same issue was caused by the anti-virus in the past see #788.

**Comment by salvatoredimaro** [comment]
Thank you for the quick reply. It's true! Avast Antivirus blocks the connection and doesn't notify about anything. I didn't realize it. Sorry and thanks a lot! Congrats for your project!
