### ISSUE TITLE
Multiple Subs in Funi Options?

### ISSUE THREAD

**Issue by danny-ml** [hama3254/Crunchyroll-Downloader-v3.0#86]
Hello. Can you add or enable the option to select subtitles from other languages in the Funi option? I would be very grateful. Thanks for everything.

**Comment by hama3254** [comment]
> Hello. Can you add or enable the option to select subtitles from other languages in the Funi option? I would be very grateful. Thanks for everything.

I'm not understanding what you want exactly, if you want Spanish and Portuguese selection then you can already test the new options with the "Funimation_mx-es_pt-br.zip" version from here: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6 
keep in mind this is a untested version, i'm just have a US VPN so i can not access the same site as you might get in that country.


if you want to be able to use more than one subtitle on funimation at the same time like it is on crunchyroll then i'm not sure how to handle that currently because of the hard sub option which would make problems with the processing since i need to add hard subs myself for funimation unlike crunchyroll where i just choose the videostream with the hard subs you can choose.

**Comment by danny-ml** [comment]
Thank you very much for answering.
The application works, Download the video and Subs from funimation, but the downloaded sub is only in English Language, not in Spanish or Portuguese.

https://www.funimation.com/es-mx/shows/how-heavy-are-the-dumbbells-you-lift/why-dont-you-try-strength-training/?qid=undefined for example.

Thanks for all!

**Comment by hama3254** [comment]
> but the downloaded sub is only in English Language

did you use the test version i have mentioned? 
  
> if you want Spanish and Portuguese selection then you can already test the new options with the "Funimation_mx-es_pt-br.zip" version from here: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6

that version should like this 
![grafik](https://user-images.githubusercontent.com/52826614/99711616-470c7780-2aa2-11eb-985c-1f8f864b89bd.png)

**Comment by danny-ml** [comment]
Hello! The link download the pre-release version. That version does not have those options. Could you give me the version that you use to do my tests? Sorry for the inconvenience.

![imagen](https://user-images.githubusercontent.com/15720798/99716779-21fe1180-2a6e-11eb-9430-86339e0025dc.png)

**Comment by hama3254** [comment]
@danny-ml did you see the new release? https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation

**Comment by theruleof4** [comment]
I've tried the new version, when I paste the link, for example, https://www.funimation.com/pt-br/shows/18if/?qid=None the link is not loaded, show a message "fail?"
When I do with the browser and try to add the likes via browser show me this message:

![image](https://user-images.githubusercontent.com/62116034/99727367-9cdb2280-2a96-11eb-9985-581f9713f0cb.png)

**Comment by hama3254** [comment]
@theruleof4  you have either a free account or you are not logged in at the downloader. 
Press the "World" icon at the main windows of the downloader and the Browser should open (most likely on crunchyroll.com) then you just need to navigate to funimation and login like a normal browser.

**Comment by danny-ml** [comment]
Hello! The new version "LA" downloads an srt file, but it is not a subtitle.

The SRT File shows this inside.

{"items": [{"src": "https://d33et77evd9bgg.cloudfront.net/FunimationStoreFront/2021429/Japanese/2021429_Japanese_7477749_8d28d8b7-fe9c-e911-82a8-dd291e252010.mp4?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMDIxNDI5L0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDU4MjU4ODR9fX1dfQ__&Signature=E3LqNyI4yQ-BtuIZufNXIY10DezvQON1ILNkvY7QTGX8RJjW68UVgQi1HexoiX6Zj6Sw-EEQGRCGJJ7mJRXve0RjElJZ4UGlitYeMymB7QgjHRpgPhhijA-wdT4~tQ824O8xnvybtvrH0HLovN7glDeaSf0aPcOtpIHBcw3qlwdZ1hSQD6NvfAhyyNbjOYLOMItHEglg8fhUImWBrlFpaKP3C6Ry5HE4JWRhdnDtf9kGxejc7QHvZATWwU0RuLa29wiL58S0wOppUNIuSMlVEaekyN8heEuq724BxIC0swSYyobZk-f~T6nRVJ~XT9xC1xVCso~Wnl5eYrLABAKDcA__&Key-Pair-Id=APKAIHNXECY27H4O6NIA&rt=1430005", "kind": "SVOD", "isPromo": false, "videoType": "mp4", "aips": [{"out": 190, "in": 190}, {"out": 478, "in": 478}, {"out": 965, "in": 965}], "experienceId": "916937", "showAds": false, "id": 1209267}, {"src": "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/2021429/Japanese/2021429_Japanese_7477749_8d28d8b7-fe9c-e911-82a8-dd291e252010.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC8yMDIxNDI5L0phcGFuZXNlLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2MDU4MjU4ODR9fX1dfQ__&Signature=E3LqNyI4yQ-BtuIZufNXIY10DezvQON1ILNkvY7QTGX8RJjW68UVgQi1HexoiX6Zj6Sw-EEQGRCGJJ7mJRXve0RjElJZ4UGlitYeMymB7QgjHRpgPhhijA-wdT4~tQ824O8xnvybtvrH0HLovN7glDeaSf0aPcOtpIHBcw3qlwdZ1hSQD6NvfAhyyNbjOYLOMItHEglg8fhUImWBrlFpaKP3C6Ry5HE4JWRhdnDtf9kGxejc7QHvZATWwU0RuLa29wiL58S0wOppUNIuSMlVEaekyN8heEuq724BxIC0swSYyobZk-f~T6nRVJ~XT9xC1xVCso~Wnl5eYrLABAKDcA__&Key-Pair-Id=APKAIHNXECY27H4O6NIA&rt=1430005", "kind": "SVOD", "isPromo": false, "videoType": "m3u8", "aips": [{"out": 190, "in": 190}, {"out": 478, "in": 478}, {"out": 965, "in": 965}], "experienceId": "916937", "showAds": false, "id": 1209268}], "watchHistorySaveInterval": 30}

**Comment by hama3254** [comment]
@danny-ml  i see the error was that i just saved the wrong text into the file, i updated the release.
Please re-download this version:
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation

**Comment by STRATOS99K** [comment]
> @danny-ml i see the error was that i just saved the wrong text into the file, i updated the release.
> Please re-download this version:
> https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation

so far it is working, it downloads the 3 languages, could you add an option to download vtt instead of srt?

**Comment by danny-ml** [comment]
> 
> 
> > @danny-ml i see the error was that i just saved the wrong text into the file, i updated the release.
> > Please re-download this version:
> > https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation
> 
> so far it is working, it downloads the 3 languages, could you add an option to download vtt instead of srt?

Or both files. .vtt and .srt. Thank you for all.

**Comment by theruleof4** [comment]
> @theruleof4 you have either a free account or you are not logged in at the downloader.
> Press the "World" icon at the main windows of the downloader and the Browser should open (most likely on crunchyroll.com) then you just need to navigate to Funimation and login like a normal browser.

I've logged via browser with a free account now. When I tried to download pasting the link, now this error appears: 
![image](https://user-images.githubusercontent.com/62116034/99737349-e6cc0480-2aa6-11eb-8331-133258a92876.png)

When I navigate to the series page and add to queue, show this message:
![image](https://user-images.githubusercontent.com/62116034/99737771-bb95e500-2aa7-11eb-91dc-6c03a60bbd14.png)

and I need to manually select the resolution for each episode and the browser needs to be opened, if I close the browser the queue stops. The video and the subtitle I've tested downloaded well.

**Comment by hama3254** [comment]
> I've logged via browser with a free account now. When I tried to download pasting the link, now this error appears:
 ![image](https://user-images.githubusercontent.com/62116034/99737349-e6cc0480-2aa6-11eb-8331-133258a92876.png)

The url from the screenshot does not work. Multi download from the main page is not possible for funimation, you either need to use the browser add-ons ( [Firefox](https://addons.mozilla.org/de/firefox/addon/crunchyroll-downloader-addon/) or [Chrome](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-guide)) or you use the [Funimation-button](https://www.youtube.com/watch?v=18qBIUYdlEM)



> When I navigate to the series page and add to queue, show this message:
> ![image](https://user-images.githubusercontent.com/62116034/99737771-bb95e500-2aa7-11eb-91dc-6c03a60bbd14.png)
> 
> and I need to manually select the resolution for each episode 

For the resolution popup did you find the resolution you had set in the settings ? 
another problem is that i currently don't save the manual selected resolution i guess i should add that.

>and the browser needs to be opened, if I close the browser the queue stops. The video and the subtitle I've tested downloaded well.

that not how the queue should work, the only window that needs to be open is the queue itself

**Comment by theruleof4** [comment]
> For the resolution popup did you find the resolution you had set in the settings ?
> another problem is that i currently don't save the manual selected resolution i guess i should add that.

The resolution I wanted was available, in this case, 1080p, but as I said, for each episode to add to the queue this pop-up shows up

> that not how the queue should work, the only window that needs to be open is the queue itself

Yeah, strange too...

I'll make more tests later, I did know that funi link doesn't work, only via browser, maybe a did something wrong and the program not worked well, I'll follow the video guide

**Comment by hama3254** [comment]
> > 
> > 
> > so far it is working, it downloads the 3 languages, could you add an option to download vtt instead of srt?
> 
> Or both files. .vtt and .srt. Thank you for all.

i have added the sub file selection, but if none of that is selected or the selected is not to be found than it uses the order .srt -> .vtt -> .dfxp  

available here: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation 

![grafik](https://user-images.githubusercontent.com/52826614/99876509-7385d800-2bf7-11eb-9342-179b387f49a6.png)

**Comment by danny-ml** [comment]
> 
> 
> > > so far it is working, it downloads the 3 languages, could you add an option to download vtt instead of srt?
> > 
> > 
> > Or both files. .vtt and .srt. Thank you for all.
> 
> i have added the sub file selection, but if none of that is selected or the selected is not to be found than it uses the order .srt -> .vtt -> .dfxp
> 
> available here: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/99876509-7385d800-2bf7-11eb-9342-179b387f49a6.png)

You are amazing!. Thank you so much for everything.

**Comment by theruleof4** [comment]
> > I've logged via browser with a free account now. When I tried to download pasting the link, now this error appears:
> > ![image](https://user-images.githubusercontent.com/62116034/99737349-e6cc0480-2aa6-11eb-8331-133258a92876.png)
> 
> The url from the screenshot does not work. Multi download from the main page is not possible for funimation, you either need to use the browser add-ons ( [Firefox](https://addons.mozilla.org/de/firefox/addon/crunchyroll-downloader-addon/) or [Chrome](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/Chrome-add-on-guide)) or you use the [Funimation-button](https://www.youtube.com/watch?v=18qBIUYdlEM)
> 
> > When I navigate to the series page and add to queue, show this message:
> > ![image](https://user-images.githubusercontent.com/62116034/99737771-bb95e500-2aa7-11eb-91dc-6c03a60bbd14.png)
> > and I need to manually select the resolution for each episode
> 
> For the resolution popup did you find the resolution you had set in the settings ?
> another problem is that i currently don't save the manual selected resolution i guess i should add that.
> 
> > and the browser needs to be opened, if I close the browser the queue stops. The video and the subtitle I've tested downloaded well.
> 
> that not how the queue should work, the only window that needs to be open is the queue itself

I tried again as the video, but now is showing this message:
![image](https://user-images.githubusercontent.com/62116034/99883276-2e68a280-2c05-11eb-900f-9ae3bdeb51fd.png)

Do I need a premium account to download? Is it not like Crunch which a free account is enough?

**Comment by hama3254** [comment]
> 
> I tried again as the video, but now is showing this message:
> ![image](https://user-images.githubusercontent.com/62116034/99883276-2e68a280-2c05-11eb-900f-9ae3bdeb51fd.png)
> 
> Do I need a premium account to download? Is it not like Crunch which a free account is enough?

that means you need an premium account, as far i can tell funimation is completed random for what you need premium and for what not.   

if we take Overloard as example the videos with the purple icon are premium only.
![grafik](https://user-images.githubusercontent.com/52826614/99884330-d2664400-2c2d-11eb-9101-4addfbf86bc7.png)

**Comment by danny-ml** [comment]
yroll-Downloader-v3.0/releases/tag/Funimation
> 
> ![grafik](https://user-images.githubusercontent.com/52826614/99876509-7385d800-2bf7-11eb-9342-179b387f49a6.png)

You are amazing!. Thank you so much for everything.

**Comment by danny-ml** [comment]
Hello! What about temporary files? (CRD-Temp-File) Could they be deleted automatically?

**Comment by hama3254** [comment]
> Hello! What about temporary files? (CRD-Temp-File) Could they be deleted automatically?

the main temp files for the hybride mode should be deletet a view seconds after the download has finished, the temp files in the program folder stay there until you close the downloader then they get automaticity deleted

**Comment by danny-ml** [comment]
Hi good day! Is it likely to implement an option in the future that only allows downloading the sub or the audio in funi and CR? Thanks for everything. Sorry for the disturbances.

**Comment by hama3254** [comment]
> Hi good day! Is it likely to implement an option in the future that only allows downloading the sub or the audio in funi and CR? Thanks for everything. Sorry for the disturbances.

Subs only is already there for Crunchyroll, maybe i will add this sometime to Funimation as well but that's a low priority.
Downloading only the audio is not planned in any way i mean just why?

**Comment by danny-ml** [comment]
> 
> 
> > Hi good day! Is it likely to implement an option in the future that only allows downloading the sub or the audio in funi and CR? Thanks for everything. Sorry for the disturbances.
> 
> Subs only is already there for Crunchyroll, maybe i will add this sometime to Funimation as well but that's a low priority.
> Downloading only the audio is not planned in any way i mean just why?

Hello! Thanks for answering. I prefer to create a multi-audio mkv, and downloading the video multiple times in different languages ​​takes a long time. Thanks for everythig!

**Comment by hama3254** [comment]
> 
> Hello! Thanks for answering. I prefer to create a multi-audio mkv, and downloading the video multiple times in different languages ​​takes a long time. Thanks for everythig!

I still wonder why? even if you speak all three languages it would be to much of an hassle for me to watch something in another language as my native one.

The only reason I see is Piracy and I don't support that !

**Comment by danny-ml** [comment]
Hello! Thanks for answering! No friend, I do not use this for those purposes, you can be sure of that. I like to collect and it is a very rare hobby, because a collector likes to have all versions of something. But I assure you, I don't use it for that. Sorry if my question made you think that.

**Comment by hama3254** [comment]
> Hello! Thanks for answering! No friend, I do not use this for those purposes, you can be sure of that. I like to collect and it is a very rare hobby, because a collector likes to have all versions of something. But I assure you, I don't use it for that. Sorry if my question made you think that.

Anyways I will not add this so I guess everything here is done so I close this.
If you have any other questions please open a new issue.
