### ISSUE TITLE
Error when downloading Link Click Italian Audio

### ISSUE THREAD

**Issue by fixx1983** [hama3254/Crunchyroll-Downloader-v3.0#861]
Try to download italian audio or full episode with italian audio for the Link Click serie gives me an error. It works for original chinese version and for subtitles

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings Softsub, 1080p, standard options, Hybrid mode enabled
 - Version 3.16.2

**Screenshots**
![Senza nome](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/20750352/14fb4e1f-2dbb-4002-9b49-42d727f634d0)

**Comment by hama3254** [comment]
i would need the url which causes the issue to check it out myself.

**Comment by fixx1983** [comment]
> i would need the url which causes the issue to check it out myself.

Yup sorry

https://www.crunchyroll.com/it/series/GP5HJ8E81/link-click

I added the serie link, selected Italian version, and when it starts downloading this error appears

**Comment by hama3254** [comment]
I fail to see your issue, for me it just complains about the resolution since its 21:9 not 16:9 but that is catched by the error handler as it should be.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/171440fc-bd29-4e53-8c30-533b48745540)

**Comment by fixx1983** [comment]
> I fail to see your issue, for me it just complains about the resolution since its 21:9 not 16:9 but that is catched by the error handler as it should be. ![grafik](https://private-user-images.githubusercontent.com/52826614/293469249-171440fc-bd29-4e53-8c30-533b48745540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NTY5NTUsIm5iZiI6MTcwMzk1NjY1NSwicGF0aCI6Ii81MjgyNjYxNC8yOTM0NjkyNDktMTcxNDQwZmMtYmQyOS00ZTUzLThjMzAtNTMzYjQ4NzQ1NTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE3MTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMjIwZDZmNjc5Yjc1ZTRmZDYxNWFiODdjYjdkN2JjMTk2NWZiMmEyOGU4ZGJlMmM3M2Q0NWVjNGJlNTJiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZjve5lIkd2V0Oe629rMgqEiLKYoCN-6coen9aAO-m4)

I"ve never seen this box, it simply gives my the error until i press download with italian dub

**Comment by hama3254** [comment]
A deeper look into the settings and possible code path showed that the issue only happen with either merged audio or audio only.
This is caused because the error handling i have shown was not triggerd in that case.
This means you can download the show with the download mode set to `default`.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/01924f14-7c14-4028-ac00-56f7bc5c02a6)
