### ISSUE TITLE
GPU (AMD/CUDA) acceleration for faster reencoding?

### ISSUE THREAD

**Issue by pbz134** [hama3254/Crunchyroll-Downloader-v3.0#864]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Video encoding should happen on the GPU instead of the CPU, resulting in way faster reencoding speed.

**Describe alternatives you've considered**

**Additional context**

**Comment by hama3254** [comment]
>Video encoding should happen on the GPU instead of the CPU

By default there is no video encoding inside the downloader, it only changes the format from a stream `.ts` to `.mp4` or `.mkv` which are just some headers in the file the video is a 1:1 copy.

>resulting in way faster reencoding speed.

while true, i want to note that some users perceive it as compromising on overall video quality

but you are lucky, the downloader gives you basic options for reencoding with all GPU brands.
please check what your GPU supports and you need to switch the `ffmpeg.exe` for av1 support

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/cf1ae81f-ca11-43f3-a830-0ca4f99f913e)

**Comment by pbz134** [comment]
Yes, that's exactly what I was looking for. Seems like I just didn't see it. Thanks!
