### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by TheWizard-maker** [hama3254/Crunchyroll-Downloader-v3.0#866]
**Describe the bug**
By looking the log file, i see 1 every 5 episodes this error

Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00024.ts
Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00023.ts
Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00025.ts
Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00212.ts
Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00211.ts
Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00238.ts
Download error #1: D:\path\CRD-Temp-File-JWBBCcCIVgJDXBIC\00237.ts

I am using the latest update of the downloader : 3.16.2

**Comment by hama3254** [comment]
If you don't see a `#2` then the file was downloaded within the 2nd try successfully.
Networking errors happen so I build a retry into the hybrid mode.
You can try to reduce the chance this gets an issue by not downloading to much episodes at the same time.

**Comment by TheWizard-maker** [comment]
Which mode is the most safe and do you advise between default ffmpeg and hybrid ?
If the download ends with the errorhandling parameter equal to 1, are we sure absolutely there is no problem with the episode ? Some part of the episode cannot be missing ?

i have noticed with this version the download speed goes at some period to 0 and after several minutes it goes up again. Is this a source or error ?
