### ISSUE TITLE
some language missing

### ISSUE THREAD

**Issue by TheWizard-maker** [hama3254/Crunchyroll-Downloader-v3.0#868]
I have seen some situation when the downloader cannot download a dub or a sub that is available on crunchyroll.

Some of them are included with demon slayer S02 like english (india). I can see it through crunchyroll but i cannot download

**Comment by hama3254** [comment]
The last time I checked I added all languages CR had, if they added some obscure ones since then I don't even notice that.
This also leads to the question if we really need them, in this case we already have English or are there any major differences on English and English for India?

**Comment by TheWizard-maker** [comment]
Yes there is a major difference between English and Englis for India, it is not the same dub (differente voice for every characters).

demon slayer is really a good example, i see 4 dubs that are apparently not taken into consideration by the downloader 

english (india) + le 3 last ones on the picture
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/231dcd99-9c6c-45ba-aa8c-194a31b4aa11)

**Comment by TheWizard-maker** [comment]
Thanks for the new update adding dubs.

Regarding the name of the file i get for those 3 dubs. Would it be possible to add the name of the dub in europeen letter just after like it is the case with russian and arabic [ex : Русский (Russian)]. 

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110522591/52325581-351e-4b9c-ad97-7cff08b85abf)

**Comment by hama3254** [comment]
for me its just text i can change, the only issue is that have no idea what languages that even are i just copy pasted from CR.

**Comment by TheWizard-maker** [comment]
if we refer to the screen :
1) mkvtoolnix says "Tamil" (ta)
2) mkvtoolnix says "Telegu" (te)
3) mkvtoolnix says "Hindi" (hi)

mkvtoolnix always says right for other dubs in crunchyroll so i guess it is also right for those 3

**Comment by hama3254** [comment]
I added those 3
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/397ece20-9729-457e-b963-2f84cd556d54)

It looks fine to me.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/5096684e-f550-4a10-b2c0-04ebed5369fc)

**Comment by TheWizard-maker** [comment]
Great thanks, could you please add the same for the for last language of the list
i know the last one is thai but i don't know for the 3 other ones
