### ISSUE TITLE
Download German Dub not working

### ISSUE THREAD

**Issue by Tom-94** [hama3254/Crunchyroll-Downloader-v3.0#869]
I've tested on two animes. When choosing Settings > Crunchyroll > Dubbed >"Deutsch" it will download Japanese DUB. When choosing English it works correct and will be english.

Tested on these animes:
https://www.crunchyroll.com/de/series/GW4HM79VM/ive-been-killing-slimes-for-300-years-and-maxed-out-my-level
https://www.crunchyroll.com/de/series/GRGG9798R/rezero--starting-life-in-another-world-

Thanks for your amazing work ;)

**Comment by hama3254** [comment]
I need to take look at this later but I would not use the setting to override the dub.
It's much simpler to use the overview URL and select the dub from there together with the season.

**Comment by hama3254** [comment]
i had done a view test and found no issue on my side. You can try the latest version with the urls you posted here and get to select the right episodes without needing the setting.
