### ISSUE TITLE
AoD 1080p+ is not 1080p+

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#87]
If I download an episode of One Piece (episode 933) at Anime on Demand via your program in 1080p+ the episode has only 844 megabyte but if I download the episode with Youtube-DL (which takes a lot longer and is not that comfortable) the episode has 1.83 gigabyte! So something is not quite right.

**Comment by hama3254** [comment]
i see AoD does list this different than usual, the normal download that i tryed are listed as 1080p but with higher bitrate.
The episode you have the issue with is listed as 1081p so the downloader just uses the highest 1080p version which is just the normal 1080p in this case.
![grafik](https://user-images.githubusercontent.com/52826614/99722139-804be400-2ab0-11eb-821c-5a9e9251a24b.png)

**Comment by hama3254** [comment]
Das sieht so schon besser aus : download ist hier https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation 
![grafik](https://user-images.githubusercontent.com/52826614/99724883-9491e000-2ab4-11eb-9c74-aaf1c8acd5dc.png)

**Comment by Schizo1987** [comment]
Hammer! Vielen Dank du bist der Beste! Ich teste es gleich mal.

**Comment by Schizo1987** [comment]
Habe es jetzt mal mit der [https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/Funimation) Version getestet aber er scheint immer noch die 1080p und nicht die 1081p zu laden. Habe auch im Settings Menü bei AoD 1080p+ ausgewählt. 

Vielen Dank schon mal!  MFG Schizo1987

**Comment by hama3254** [comment]
@Schizo1987 Bei welcher Folge genau? wieder die gleiche ?

**Comment by Schizo1987** [comment]
Sorry war mein Fehler! hatte auch noch die Alte Version von dir im Download Ordner und die Ausversehen entpackt......

Die Aktuelle version von dir Funktioniert jetzt!

Vielen vielen Dank.    MFG Schizo1987

**Comment by hama3254** [comment]
> 
> 
> Sorry war mein Fehler! hatte auch noch die Alte Version von dir im Download Ordner und die Ausversehen entpackt......
> 
> Die Aktuelle version von dir Funktioniert jetzt!
> 
> Vielen vielen Dank. MFG Schizo1987

Ich mach dann hier zu, falls wieder was ist einfach einen neuen issue aufmachen.
