### ISSUE TITLE
"Copy" / Default Subtitle Options are Wrong, Leading to Incorrect Styling and Sizing for .ass Subs

### ISSUE THREAD

**Issue by Anonymous327** [hama3254/Crunchyroll-Downloader-v3.0#871]
**Describe the bug**

After downloading a video with this program, the subtitles, whether soft or external, are not sized or styled properly in a media player. I believe 'ScaledBorderAndShadow:yes' not being checked by default or included in the "Copy" settings is the culprit. Moreover, it chooses the lowest PlayResX/Y resolution (640x360) automatically instead of the actual video size.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: Softsubs, No Merge
 - Version: v3.16.2

**Screenshots**
VLC:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/96669859/76d814ff-f1a0-46ef-a09c-4fd59316f5f3)
Plex:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/96669859/80ad954d-921f-4b4f-83de-5416f5184803)
Plex after fixing ASSA resolution:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/96669859/67e6a711-b3c4-4913-af52-3d4273f9b765)

**Additional context**
For whatever reason, the subs (copy/merge disabled) always look wrong in VLC, even after doing the fixes.

**Edit:**

After some further investigation, I discovered that you have to:
1. Go to Output. Choose merge disabled. "Copy" will not give you the desired options.
2. Check "add 'ScaledBorderAndShadow:yes' to subtitles".
3. Subtitles should display correctly now.
4. (Optional) You can change the resolution to 1080p via notepad or a subtitle editor as well just for completeness, but what this means is you'll have to edit all the subs manually if you want to change the resolution. Can be done with a batch convert, but it's an extra step that we shouldn't have to take, in my opinion...
5. Merge with video files to create softsubs.

**Comment by hama3254** [comment]
> I believe 'ScaledBorderAndShadow:yes' not being checked by default or included in the "Copy" settings is the culprit.

The default settings should be as universell as possible.
Subtilte options are dependent on your setup (Hardsubs/Softsubs) so i can not enable any settings that changes the output file.

> 1. Go to Output. Choose merge disabled. "Copy" will not give you the desired options.

You can enable `ScaledBorderAndShadow:yes` with `MKV` on `copy` if the `Hybrid Mode` is enable at the top.
Why this option does not work otherwise can be found here : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/764#issuecomment-1595774856

**Comment by Anonymous327** [comment]
Good to know, thanks. Will take a look.

**Comment by Anonymous327** [comment]
> > I believe 'ScaledBorderAndShadow:yes' not being checked by default or included in the "Copy" settings is the culprit.
> 
> The default settings should be as universell as possible. Subtilte options are dependent on your setup (Hardsubs/Softsubs) so i can not enable any settings that changes the output file.
> 
> > 1. Go to Output. Choose merge disabled. "Copy" will not give you the desired options.
> 
> You can enable `ScaledBorderAndShadow:yes` with `MKV` on `copy` if the `Hybrid Mode` is enable at the top. Why this option does not work otherwise can be found here : [#764 (comment)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/764#issuecomment-1595774856)

Though, would still prefer for the PlayResX/Y resolution to be whatever video resolution you choose in the settings, even though it works currently. I imagine that `ScaledBorderAndShadow:yes` makes it so it doesn't matter what PlayResX/Y resolution it is.
So, for example, if you choose 1080, it'll do 1920x1080 for the PlayResX/Y, and so on and so forth. Is it possible to specify that in the script? Or is it locked to 640x360?
