### ISSUE TITLE
Funimation Video Movie Download Process Completed, but Failed

### ISSUE THREAD

**Issue by teogaming201** [hama3254/Crunchyroll-Downloader-v3.0#872]
![Crunchyroll Downloader 08_01_2024 10_25_59](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/150650648/23ebe333-f384-4e93-8c25-c1b3576d8968)

Version : 3.17

When downloaded funimation movies KNY TV Series duration almost 2 hours, everything seems fine, but when opened video had duration only 30 min, above 30 min crashed. This video downloaded about 5-6 GB, but that screenshoot just 1.4 GB which mean disapointed. Help me.

The links:
https://www.funimation.com/v/demon-slayer-kimetsu-no-yaiba/the-hashira-meeting-arc-63cc26f4-9e10-11eb-b23a-0242ac110003?lang=&a=1&qid=

**Comment by hama3254** [comment]
i don't have the required subscription to check this for myself.
If you can please provide the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) for that movie, from there i can check the issue.

>This video downloaded about 5-6 GB, but that screenshoot just 1.4 GB which mean disapointed

From this part the error description i would assume you use the `Hybrid Mode` to download and the size of >5GB should have been the full download volume (or at least more than 30min of playtime) this mean the issue is somewhere in the download routine.

**Comment by teogaming201** [comment]
I send it about log file

**Comment by teogaming201** [comment]
[de.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/13867218/de.txt)
here the logfile, it's long

**Comment by teogaming201** [comment]
When used hybrid mode, i can't find that file, how to do it?

**Comment by teogaming201** [comment]
And not saved in to a file

**Comment by teogaming201** [comment]
Hey, did you find the solutions

**Comment by hama3254** [comment]
i checked the log and it looks to me that it was downloaded fully.
` Duration: 01:46:04.11, start: 9.957333, bitrate: 3 kb/s`
`frame=42439 fps=3.8 q=-1.0 Lsize= 1481823kB time=01:46:04.20 bitrate=1907.4kbits/s speed=0.573x    `
This means i have not problem to work on.

**Comment by teogaming201** [comment]
Or you can try it used my account

**Comment by teogaming201** [comment]
If you don't belive it

**Comment by teogaming201** [comment]
If you don't believe it, i give you account for test

**Comment by teogaming201** [comment]
Well?

**Comment by teogaming201** [comment]
But privately

**Comment by hama3254** [comment]
Please be a little more patient, all your comments have been made in the middle of the night for me.

For your issue I can only work with the data you have given me so far.
This is some kind of issue with the download.
I quoted what Infos I got from the log which indicates to me that the log was a successful but very slow download.

If you want share your account to help me test then you can contact me on Discord Hama#4155.
Before you share the account I want to point out that I am from central Europe so the account is used with a VPN which may not be allowed in there ToS.

**Comment by teogaming201** [comment]
Done

**Comment by teogaming201** [comment]
Contact me in discord
