### ISSUE TITLE
New Shows are throwing this error in version 3.17

### ISSUE THREAD

**Issue by cimmy01** [hama3254/Crunchyroll-Downloader-v3.0#874]
**Describe the bug**
If I try and download a show by using the "show's" address I receive the error in the screen shot. Plus the next window is something went wrong and all of the pull downs are blank. If I copy the episode address it will go through without issue. i can just X out of the add screen and hit the plus again and it will allow another selection to be made. So far it has done this on theses shows
['TIS TIME FOR "TORTURE," PRINCESS](https://www.crunchyroll.com/tis-time-for-torture-princess)
[HOKKAIDO GALS ARE SUPER ADORABLE!](https://www.crunchyroll.com/hokkaido-gals-are-super-adorable)
[THE FOOLISH ANGEL DANCES WITH THE DEVIL](https://www.crunchyroll.com/the-foolish-angel-dances-with-the-devil)
[FLUFFY PARADISE](https://www.crunchyroll.com/fluffy-paradise)
[7TH TIME LOOP: THE VILLAINESS ENJOYS A CAREFREE LIFE MARRIED TO HER WORST ENEMY!](https://www.crunchyroll.com/7th-time-loop-the-villainess-enjoys-a-carefree-life-married-to-her-worst-enemy)
[MR. VILLAIN'S DAY OFF](https://www.crunchyroll.com/mr-villains-day-off)

So far those are the ones that have thrown the error. It has worked just fine on some of the ongoing shows from earlier this and last season

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Version 3.17

**Screenshots**
![Screenshot 2024-01-08 152916](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/56510595/59f90bda-9f10-4ac1-9f96-2dba1e90d393)

**Comment by hama3254** [comment]
I have to take a look at this later but this would mean CR did not Tag any dub to the series yet.
This leads the downloader to error out since the 1st entry in a empty list is not there.
