### ISSUE TITLE
Please add Thai subtitles

### ISSUE THREAD

**Issue by ruk011** [hama3254/Crunchyroll-Downloader-v3.0#875]
Now there are some stories with Thai subtitles.

Could you please add some more? in SoftSubs

**Comment by hama3254** [comment]
if you can refere me a episode with the subtitles then i should be able to add them.

**Comment by ruk011** [comment]
![418421616_685177317143541_830301396176047296_n](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/156052910/a616bf2f-36e4-454c-9641-8237a904c81f)

Villainess Level 99 , Tis Time for "Torture," Princess

Crunchyroll This season has already started to have Thai subtitles. But subtitles will be delayed by about 2-3 hours.

**Comment by hama3254** [comment]
it seems to me that i already got :
`LangValueEnum.Add(New NameValuePair("ไทย", "tha", "th-TH", Nothing))`
i would guess than the bad UI makes it dissapear like in #876
