### ISSUE TITLE
Hybrid Download modus bei Anime on Demand

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#88]
Hy, mir ist aufgefallen das der Hybrid Download Modus bei Anime on Demand einen Fehler hat. Er lädt die Datei runter und speichert sie auch aber wenn ich die Folge durchzappe dann merkt Mann das Audio und Video nicht synchron laufen als würden ein paar Parts von der m3u nicht verarbeitet worden sein. Ich habe es mit mehreren Serien und Folgen getestet und ich habe den selben Fehler immer wieder.

Wenn ich den Hybrid Download Modus deaktiviere ist alles in Ordnung.

MFG Schizo1987

**Comment by hama3254** [comment]
Ist das bei einem bestimmen Anime/Folge oder bei allen?

**Comment by Schizo1987** [comment]
Also bei One Piece ist es mir aufgefallen z.b. Folge 934 und 935 oder bei Domestic Girlfriend Dub Folge 1

**Comment by hama3254** [comment]
Ich weiß nicht ob das was ich gefunden habe das eigentlich Problem ist, aber bei
 mir sind einzelne fragmente vertauscht, deshalb kommt ffmpeg da bei zusammenbauen durcheinander. 
Ich muss das mal anschauen wie das überhaupt der fall sein kann.

**Comment by hama3254** [comment]
aus reiner Neugier, welche CPU hast du drinnen ? 
Hintergrund ist der das sich der Hybrid Download anhand der Anzahl  der CPU Kerne die Download Threads regelt. 
Meine aktuelle Theorie ist das der AoD Server nicht mit allen anfragen gleichzeitig zurecht kommt, bei mir wären das beim Start direkt 8 Stück bis gewatet wird das einer fertig ist bevor der nächste darf.

Du kannst es vlt einfach mal testen hier die "3-Pre-Release-Crunchyroll-Downloader.v3.6.zip" nehmen. 
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6

**Comment by Schizo1987** [comment]
Ich habe eine Intel Core i7 6950X (10 Kerne mit 20 Threads)

Vielen Dank schon mal werde die Version gleich testen 👍

**Comment by hama3254** [comment]
> Ist aber auf jeden fall immer noch schneller als ohne Hybrid Download 👍

ffmpeg läd halt einfach eins nach dem anderen anstatt bei einem 10 Kerner 10 Fragmente auf einmal 

> So liegt jetzt vielleicht auch an der Uhrzeit aber mit der 2-Pre-Release-Crunchyroll-Downloader.v3.6.zip Version mit Hybrid Download habe ich jetzt mit 12 MB/s Runterladen können (Vor paar stunden mit 15 MB/s) aber da haben die Videos ja einen knacks.
> 
> Mit der 3-Pre-Release-Crunchyroll-Downloader.v3.6.zip Version mit Hybrid Download lade ich mit 7,3 MB/s Runter und die Videos Funktionieren!

das könnte auch am delay liegen was ich eingebaut habe, davor ist der Code einfach die Playlist welche AoD verwendet durchgegangen nur begrenzt auf maximal halb so viele Downloads wie die CPU Threads hat, jetzt wartet der Prozess trotzdem noch 1 Sekunde bevor er loslegt.

**Comment by Schizo1987** [comment]
Passt jetzt alles. Habe es jetzt ausgiebig getestet lade mit 12 - 13 MB/s runter PERFEKT!!
Vielen vielen dank nochmal für deine mühen.
