### ISSUE TITLE
Can't work it

### ISSUE THREAD

**Issue by lessyy** [hama3254/Crunchyroll-Downloader-v3.0#881]
The previous drama was able to run, but now it keeps prompting this, and the anti-virus software is also turned off.

![微信截图_20240112211911](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/108445071/530f06c8-e6f2-4bf1-9bb1-736f392b616c)

**Comment by hama3254** [comment]
The error code `403` is a standart code for http traffic and means `Forbidden` which is different to `401` also known as `Unauthorized` this means to me that there should not be a issue withe the request the downloader is doing but some other variable.
I don't have the insight on there system to know the reason for this but this is an essential request and CR should not work without it so please check if your browser can access any show on CR.
