### ISSUE TITLE
OutOfRangeException when downloading

### ISSUE THREAD

**Issue by ZortexSenpai** [hama3254/Crunchyroll-Downloader-v3.0#883]
**Description**
OutOfRangeException when dowloading.

**Info**
 - Platform: Crunchyroll
 - Crunchyroll URL: https://www.crunchyroll.com/series/G9VHN9QVN/tearmoon-empire
 - Crunchyroll Language: English (US)
 - Settings: Screenshots down below
 - Version Crunchyroll-Downloader-v3.17

**Screenshots**

Steps to reproduce:
1:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/65411800/05605357-2e4b-4a76-b24b-3393b2edf7c1)
2: Error:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/65411800/36b4c80b-5250-4c85-9682-38eb86a9cb6c)

Settings:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/65411800/220dfb37-bd0d-4b28-b1f2-30748421eeb3)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/65411800/7218f832-12c1-444f-8dde-082a2444956e)
(Everything else is default)

**Comment by hama3254** [comment]
The [v3.17 Release](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.17) includes a new build v3.17.1 which should solve the issue.
