### ISSUE TITLE
status failed issue

### ISSUE THREAD

**Issue by egi01k** [hama3254/Crunchyroll-Downloader-v3.0#884]
When i try to download one piece episodes it doesnt even start downloading

status: failed - no video, check CR login 

or : "video not found"

**Comment by hama3254** [comment]
You can only download anime you can watch so you need a premium account to download premium episodes and it has to be logged in inside the downloaders built-in web browser.

**Comment by egi01k** [comment]
wow its functioning !! thx .... i overlooked this step
