### ISSUE TITLE
Deleting of temporary folders created in Hybrid Mode - keep cache

### ISSUE THREAD

**Issue by Vorffeed** [hama3254/Crunchyroll-Downloader-v3.0#886]
Good ^_^
As I put in the title, you could add a function in the Hybrid Mode - keep cache that after downloading the episode automatically delete the temporary folders created with the files, because you find them occupying twice the space and you have to delete them manually and it is a pain when you download daily 7-8 episodes and you have to look for folder by folder the downloaded episodes and the externally generated CRD-Temp-File that creates them outside the folders where you have the save directory, and at the end you find a lot of these empty folders in the download directory.

**Comment by hama3254** [comment]
The `Hybrid Mode - keep cache` is designed to keep the temporarily files.
You can change the it to just `Hybrid Mode` to delete the files after the download.
Files inside the downloaders folder get deleted while exiting the downloader.

![282532192-e5761b78-c775-457a-bddf-98ce7411962b](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/29b1585a-5419-4763-a5fe-4c7812f9f073)
