### ISSUE TITLE
Merged Audio, added dub is off

### ISSUE THREAD

**Issue by dammpf** [hama3254/Crunchyroll-Downloader-v3.0#888]
Hi,
when I download japanese dub with softsubs and merge it with another dub the new dub is a few seconds behind.
I tried it in ffmpeg, hybrid mode and MP4/MKV always was the audio off.

Or am I doing something wrong?

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Version v3.17.1

![2024-01-23 18_54_52-StreamFab](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/154911745/03b36813-bbde-4821-9b5e-19b922ea4b58)

**Comment by hama3254** [comment]
This is what i was expecting, some anime are worse other better.
More details can be found in the original discussion.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/701#discussioncomment-5502742
