### ISSUE TITLE
Can't download with portuguese (Brazil) dub

### ISSUE THREAD

**Issue by EduardoV-V** [hama3254/Crunchyroll-Downloader-v3.0#889]
Even after choosing Portuguese (Brazil) in the options, it still downloads the Japanese dub. Tried forcing with harddub, but not even that works.

**Comment by EduardoV-V** [comment]
Ok. After some testings, I noticed that this problem occurs with only some episodes. Darling in the franxx episode 1 downloads fine with the correct dub, but episode 4 will only download with japanese dub. I checked on the crunchyroll website and it has a portuguese dub available.

**Comment by hama3254** [comment]
On Crunchyroll all episodes have unique urls with there default dub, the `override Dub language` tells the downloader to look for the preferred dub. If that one is not found or the option is not enabled the downloader uses the default dub for the given Url.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/b7f67323-1711-49db-b445-65e27d54d0b5)

This worked fine for me and the season download also found all episodes for the dub.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9b2869d9-4d68-4725-93eb-9cfd05ed9c87)
