### ISSUE TITLE
Keine Folgen zum auswählen bei Detektiv Conan (AoD)

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#89]
Hallo, Entschuldigung falls ich dich nerven sollte.

Mir ist ein Fehler aufgefallen wenn ich im Programm den link von [Detektiv Conan](https://anime-on-demand.de/anime/415) hinzufüge habe ich im Auswahl Menü keine Folgen zum auswählen.
![aod](https://user-images.githubusercontent.com/74493510/99902140-cb861280-2cbb-11eb-977d-0b71e62994ae.png)

Vielen Dank schon mal!

**Comment by hama3254** [comment]
Das problem sollte bei allen Dub only anime auftreten und mit dem Relase hier nicht mehr passieren :  "4-Pre-Release-Crunchyroll-Downloader.v3.6.zip" von https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6

**Comment by Schizo1987** [comment]
Hammer! Vielen Dank das du das immer so zeitnah fixt!

Ich habe die Version jetzt ausprobiert und ich kann die Folgen jetzt auch auswählen aber sobald ich auf Download drücke stürzt das Programm ab!

**Comment by hama3254** [comment]
> Hat des vielleicht damit zu tun das es die Folgen nur maximal in 720p gibt und in den Download Einstellungen ist 1080p+ aktiv!?

genau das wars, ich weiß nicht warum aber ich bin scheinbar davon ausgegangen das immer eine passt was nicht der fall ist.

hab den fix hochgeladen du kennst dich ja mittlerweile aus... https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.6

**Comment by Schizo1987** [comment]
Wow jetzt funktioniert es. Vielen vielen Dank ❗👍
