### ISSUE TITLE
Download stuck at 0%

### ISSUE THREAD

**Issue by SupahFox** [hama3254/Crunchyroll-Downloader-v3.0#891]
I'm trying to download a full season but it got stuck at 0%

![imagen](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/31490939/45335eab-c71b-48dd-8ebf-a1120b3bbc63)

**Comment by SupahFox** [comment]
Tried with a different anime but the issue persists

**Comment by hama3254** [comment]
please add the [FFMPEG-Logfile](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile) then i take a look at the cause of the issue.

**Comment by SupahFox** [comment]
`

25/1/2024 23:07:23 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs3/6e7b0e3785edf0873901763677504ec3/assets/3611ebde494464c1efaaee98ceaa6f67_4479501.mp4/index-v1-a1.m3u8?res=1920x1080&Expires=1706407643&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy82ZTdiMGUzNzg1ZWRmMDg3MzkwMTc2MzY3NzUwNGVjMy9hc3NldHMvMzYxMWViZGU0OTQ0NjRjMWVmYWFlZTk4Y2VhYTZmNjdfNDQ3OTUwMS5tcDQvaW5kZXgtdjEtYTEubTN1OD9yZXM9MTkyMHgxMDgwIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzA2NDA3NjQzfX19XX0_&Signature=ja0MpOYnQMS0Es40K27YUVIaAXlwkCdA0007b3iGEYjZkkVEiKCAZVM2BSFZSfzNQg5j6XijtklF0NTOqko78WZTVb8E8ODJF2dbCDAn8JoWt-HbB8u9jxC4rA2Thqje~aJPungPawdaGY43MU4avxFUHpQCK5uqr1dz7dN95kKiihBUB2KPrYxwb29CaP~N1dLG0UiOhXqlTpIYV1EcW3X0WyQsrZ49~pAGtiI9~WT4mSgyUyJyh118kECGdZm-LNuE7c22h87IjZ5V3laZsOrIeHexubV8FbhSGAE6BsIRIG4cBwXHPX-g6cDcenld8vj2m8u5-qkOXvwrvtmmmA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA" -metadata:s:a:0 language=jpn -c copy -c:a copy -bsf:a aac_adtstoasc "E:\Users\fabuz\Desktop\CRDL\Valkyrie Drive -Mermaid- Season 1 Episode 1.mp4"

25/1/2024 23:07:25 ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
25/1/2024 23:07:25   built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
25/1/2024 23:07:25   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
25/1/2024 23:07:25   libavutil      57. 28.100 / 57. 28.100
25/1/2024 23:07:25   libavcodec     59. 37.100 / 59. 37.100
25/1/2024 23:07:25   libavformat    59. 27.100 / 59. 27.100
25/1/2024 23:07:25   libavdevice    59.  7.100 / 59.  7.100
25/1/2024 23:07:25   libavfilter     8. 44.100 /  8. 44.100
25/1/2024 23:07:25   libswscale      6.  7.100 /  6.  7.100
25/1/2024 23:07:25   libswresample   4.  7.100 /  4.  7.100
25/1/2024 23:07:25   libpostproc    56.  6.100 / 56.  6.100
25/1/2024 23:07:25 [https @ 0000015b74445c40] No trailing CRLF found in HTTP header. Adding it.
`

**Comment by hama3254** [comment]
This seems like `ffmpeg` itself is getting stuck for some reason.
You could try the hybrid mode then `ffmpeg` only need to process local files.

![282532192-e5761b78-c775-457a-bddf-98ce7411962b](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/29b1585a-5419-4763-a5fe-4c7812f9f073)

**Comment by SupahFox** [comment]
Hybrid works fine. I've tried to delete ffmpeg from my path env but the issue still remains

**Comment by SupahFox** [comment]
This didn't happened until now

**Comment by hama3254** [comment]
The path to the `ffmpeg.exe` is hard coded to the Downloaders path and it finds some executable.

![Screenshot_2024-01-26-12-59-43-62_3aea4af51f236e4932235fdada7d1643](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/fc587db4-1a78-4354-a510-5c7c1054e6d0)

The log is also just cut of with no error.

> This didn't happened until now

If it worked and now it stopped than I would ask if you changed something.

**Comment by hama3254** [comment]
> Hybrid works fine.

Does it work fully? It should call ffmpeg with a local cache copy of the download to decrypt the stream and assemble it. (ts to mp4/mkv)

**Comment by SupahFox** [comment]
> > Hybrid works fine.
> 
> Does it work fully? It should call ffmpeg with a local cache copy of the download to decrypt the stream and assemble it. (ts to mp4/mkv)

it does

**Comment by hama3254** [comment]
> > > Hybrid works fine.
> > 
> > 
> > Does it work fully? It should call ffmpeg with a local cache copy of the download to decrypt the stream and assemble it. (ts to mp4/mkv)
> 
> it does

this would mean ffmpeg is found and ok

>I didn't change anything, which is weird.

maybe something you did not notice (anti virus update? firewall update?)

what we know is ffmpeg works on it's own, we know your interne can connect to the stream (with hybrid mode) so only ffmpeg fails to do anything so something like the AV oder firewall might be the cause.

 i want to add that i am just guessing at this point since this issue is strange.
 If the Hybrid mode works good enough for you than i would just ignore this issue and use the hybrid mode.

**Comment by SupahFox** [comment]
I guess you're right
