### ISSUE TITLE
audio synch

### ISSUE THREAD

**Issue by egi01k** [hama3254/Crunchyroll-Downloader-v3.0#892]
hi , the video i have downloaded is not well synched with the audio... maybe 1 one second off ... do you know a way to fix this ?

**Comment by hama3254** [comment]
this is known to be an issue with merged audio as i added in the original discussion https://github.com/hama3254/Crunchyroll-Downloader-v3.0/discussions/701#discussioncomment-5502742.
If your audio is not merged than i would need more details about the service (crunchyroll or funimation?) and the episode.
