### ISSUE TITLE
Error if skip hardsubs is not selected and there are no hardsubs

### ISSUE THREAD

**Issue by tkirkland** [hama3254/Crunchyroll-Downloader-v3.0#893]
**Describe the bug**
If you have the attempt to grab hardsubs and the downloader detects that there are no hardsubs in your default language, you are prompted to select another language.  If you select 'No hardsubs' either because there are none or you don't want any of the available choices, this is when the error in image three happens.  Your only option now is to cancel, go into preferences for CrunchyRoll and enable 'skip hardsubs...'

Apologies for the large images... On a 4k display and saw no way to resize them.  If I missed it let me know.

**Where does the issue happen?**
 - Crunchyroll (site as of 1/24/04)
 - Settings shown in image
 - Version 3.17.1 (it was occurring in 3.17 as well, updated to test)
 - My target url was "https://www.crunchyroll.com/series/GDKHZEJ0K/solo-leveling" on a subscribed account

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/18052612/167e6b42-cb57-425e-b788-fa79ebc05c15)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/18052612/0385034a-cb06-46df-a96f-1b2e27c074a3)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/18052612/ab66eea7-65ff-4d88-beb4-e488367870da)

**Comment by hama3254** [comment]
the whole code of the hardsub error handling was outdated and is now replaced with a new version.
i wonder why this was not a bigger issue since half the sub would have caused the same issue as `No Hardsubs` did.

Anyway  the new [v3.17.2 build](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.17) should fix this now.

**Comment by tkirkland** [comment]
Perfect, I'll test it and let you know.

**Comment by tkirkland** [comment]
Working fine.  Thanks.  Closing.
