### ISSUE TITLE
Cannot download the english version of Attack on Titan Season 1

### ISSUE THREAD

**Issue by CBecker100** [hama3254/Crunchyroll-Downloader-v3.0#898]
I can download every other season (2-4), but season 1 comes up as two unnumbered episodes from which I can only download one episode, which happens to be 13.5

 - Platform: Crunchyroll
 - Settings Hardsubs & Softsubs are eng (with ignore if not available) and hybrid download mode
 - Version v3.17

![D](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/134368939/646f7865-0f1e-41a1-b7db-2567eba428ca)

**Comment by hama3254** [comment]
Please check out the newer [v3.17.2 build](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.17).

**Comment by CBecker100** [comment]
Oh, I missed the new version. That's my bad. And v3.17.2 fixed it, thank you.
