### ISSUE TITLE
Funimation information

### ISSUE THREAD

**Issue by Aiyomi-Irirako** [hama3254/Crunchyroll-Downloader-v3.0#899]
hey,

funimation will be closed on April 2, .2024.

is just an information

**Comment by hama3254** [comment]
That explains the message i just got on Crunchyroll since my E-Mail was used for both services.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/ad35a6b7-cada-4fb9-b1e0-2c3202c92122)
