### ISSUE TITLE
URL Adresse oder URL Kopier Knopf BITTE !

### ISSUE THREAD

**Issue by KoroFX** [hama3254/Crunchyroll-Downloader-v3.0#9]
![image](https://user-images.githubusercontent.com/46395233/71742690-e2810380-2e62-11ea-9dc5-a81f74b893d7.png)
Es funktioniert halt nur in 2/10 Fällen den Link aus den share a link zu kopieren und in den anderen 8 kopiert es den Gesamten HTML Code obwohl du nur den link makierst und stg + c drückst...
Bitte baue oben eine URL Adressleiste ein oder  mach nen knopf neben den X um den link der aktiven seite zu kopieren, bitte du währst mein Held (Bist du eh schon aber dann noch mehr).

**Comment by KoroFX** [comment]
Das zum Beispiel wird Kopiert anstatt der Link obwohl ich den Link makiert habe, ich kann komischerweise den link so wie ich ihn kopiert habe im feld dort normal einfügen, will ich ihn woanders einfügen kommt in 8/10 fällen dieser Bullshit bei raus....




<div class="optanon-alert-box-wrapper  hide-cookie-setting-button" role="alertdialog" aria-labelledby="alert-box-title" aria-describedby="alert-box-message" style="display:none"><div class="optanon-alert-box-bottom-top"><div class="optanon-alert-box-corner-close"><button class="optanon-alert-box-close banner-close-button" aria-label="Close" title="Close" onclick="Optanon.TriggerGoogleAnalyticsEvent('OneTrust Cookie Consent', 'Banner Close Button');" tabindex="4"></button></div></div><div class="optanon-alert-box-bg"><div class="optanon-alert-box-logo"> </div><div class="optanon-alert-box-body"><p class="optanon-alert-box-title legacy-banner-title sr-only" id="alert-box-title" role="heading" aria-level="2">Cookie Notice</p><p class="banner-content" id="alert-box-message">We use cookies to understand how you use our site and to improve your experience. This includes personalizing content and advertising. To manage or opt out of the use of cookies, <a class="optanon-toggle-display banner-policy-link" tabindex="1" aria-label="click here">click here</a>. By continuing to use this website or closing this banner, you accept our use of <a class="optanon-toggle-display banner-policy-link" tabindex="2" aria-label="first- and third-party cookies">first- and third-party cookies</a>.</p></div><div class="optanon-clearfix"></div><div class="optanon-alert-box-button-container"><div class="optanon-alert-box-button optanon-button-close"><div class="optanon-alert-box-button-middle"><button class="optanon-alert-box-close" aria-label="Close">Close</button></div></div><div class="optanon-alert-box-button optanon-button-allow"><div class="optanon-alert-box-button-middle accept-cookie-container"><button class="optanon-allow-all accept-cookies-button" title="I accept" aria-label="I accept" onclick="Optanon.TriggerGoogleAnalyticsEvent('OneTrust Cookie Consent', 'Banner Accept Cookies');" tabindex="3">I accept</button></div></div></div><div class="optanon-clearfix optanon-alert-box-bottom-padding"></div></div></div><div id="optanon" class="modern"><div id="optanon-popup-bg"></div><div id="optanon-popup-wrapper" role="dialog" aria-modal="true" tabindex="-1" lang="en-GB"><div id="optanon-popup-top"><button onclick="Optanon.TriggerGoogleAnalyticsEvent('OneTrust Cookie Consent', 'Preferences Close Button');" aria-label="Close" class="optanon-close-link optanon-close optanon-close-ui" title="Close"><div id="optanon-close" style="background: url(https://cdn.cookielaw.org/skins/5.9.0/default_flat_bottom_two_button_black/v2/images/optanon-pop-up-close.png);width:34px;height:34px;"></div></button></div><div id="optanon-popup-body"><div id="optanon-popup-body-left"><div id="optanon-popup-body-left-shading"></div><div id="optanon-branding-top-logo" style="background-image: url('https://cdn.cookielaw.org/logos/10/10:www.crunchyroll.com/CR%20White%20LG.png') !important;"></div><ul id="optanon-menu" aria-label="Navigation Menu" role="tablist"><li class="menu-item-on menu-item-about" title="Your Privacy"><p class="preference-menu-item"><button role="tab" aria-selected="true" aria-controls="Your-Privacy" id="Your-Privacy">Your Privacy</button></p></li><li class="menu-item-necessary menu-item-on" title="Strictly Necessary Cookies"><p class="preference-menu-item"><button role="tab" aria-selected="false" aria-controls="Strictly-Necessary-Cookies" id="Strictly-Necessary">Strictly Necessary Cookies</button></p></li><li class="menu-item-on menu-item-advertising" title="Advertising Cookies"><p class="preference-menu-item"><button role="tab" aria-selected="false" aria-controls="Advertising-Cookies" id="Advertising-Cookies">Advertising Cookies</button></p></li><li class="menu-item-on menu-item-social" title="Social Media Cookies"><p class="preference-menu-item"><button role="tab" aria-selected="false" aria-controls="Social-Media-Cookies" id="Social-Media">Social Media Cookies</button></p></li><li class="menu-item-moreinfo menu-item-off" title="More Information"><p class="preference-menu-item"><a target="_blank" aria-label="More Information" href="https://cookiepedia.co.uk/giving-consent-to-cookies" onclick="Optanon.TriggerGoogleAnalyticsEvent('OneTrust Cookie Consent', 'Preferences Cookie Policy');">More Information</a></p></li></ul></div><div><div id="optanon-popup-body-right"><p role="heading" aria-level="2" class="legacy-preference-banner-title h2" aria-label="Privacy Preference Centre">Privacy Preference Centre</p><div class="vendor-header-container"><p class="header-3" role="heading" aria-level="3"></p><div id="optanon-popup-more-info-bar"><div class="optanon-status"><div class="optanon-status-editable"><form><span class="fieldset"><p><input value="check" id="chkMain" checked="checked" class="legacy-group-status optanon-status-checkbox" type="checkbox"><label for="chkMain">Active</label></p></span></form></div><div class="optanon-status-always-active optanon-status-on"><p>Always Active</p></div></div></div></div><div class="optanon-main-info-text" role="tabpanel"></div></div><div class="optanon-bottom-spacer"></div></div></div><div id="optanon-popup-bottom"> <a href="https://onetrust.com/poweredbyonetrust" target="_blank" rel="noopener"><div id="optanon-popup-bottom-logo" alt="OneTrust Website" style="background: url(https://cdn.cookielaw.org/skins/5.9.0/default_flat_bottom_two_button_black/v2/images/cookie-collective-top-bottom.png);width:155px;height:35px;" title="powered by OneTrust"></div></a><div class="optanon-button-wrapper optanon-save-settings-button optanon-close optanon-close-consent"><div class="optanon-white-button-left"></div><div class="optanon-white-button-middle"><button title="Save Settings" aria-label="Save Settings" onclick="Optanon.TriggerGoogleAnalyticsEvent('OneTrust Cookie Consent', 'Preferences Save Settings');">Save Settings</button></div><div class="optanon-white-button-right"></div></div><div class="optanon-button-wrapper optanon-allow-all-button optanon-allow-all" style="display: none;"><div class="optanon-white-button-left"></div><div class="optanon-white-button-middle"><button title="Allow All" aria-label="Allow All" onclick="Optanon.TriggerGoogleAnalyticsEvent('OneTrust Cookie Consent', 'Preferences Allow All');">Allow All</button></div><div class="optanon-white-button-right"></div></div></div></div></div>
  <header id="header_beta" class="site-header" itemscope="" itemtype="http://schema.org/WPHeader">
  <div id="header_container" class="content">
    <div class="header-navigation">
      <div class="home">
        <h1 id="logo_beta" class="header-logo logo-enUS" itemscope="" itemtype="http://schema.org/Organization">
          <link href="/" itemprop="url">
          <meta content="God Eater" itemprop="name">
          <a href="/" id="home_link">
            <svg viewBox="0 0 96 18">
              <title>Crunchyroll</title>
              <use xlink:href="/i/svg/header.svg#cr_logo_noTagline"></use>
            </svg>
          </a>
        </h1>

        <button id="header_mobilemenu_beta" class="mini-menu-button" type="button">
          <svg class="open-icon" viewBox="0 0 48 48">
            <title>Open Menu</title>
            <use xlink:href="/i/svg/header.svg#cr_drawer"></use>
          </svg>

          <svg class="close-icon" viewBox="0 0 48 48">
            <title>Close Menu</title>
            <use xlink:href="/i/svg/header.svg#cr_close"></use>
          </svg>
        </button>
      </div>

      <nav id="header_menubar_beta" class="header-menubar" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
        <ul>
          <li class="state-selected">
            <a href="/videos/anime" itemprop="url" token="topbar">Shows</a>
          </li>

                      <li class="">
              <a href="/comics/manga" itemprop="url" token="topbar">Manga</a>
            </li>
          
                      <li class="">
              <a href="/news" itemprop="url" token="topbar">News</a>
            </li>
          
          <li class="games">
  <a id="games_button" href="/games" itemprop="url" token="topbar">Games</a>
</li>

  <style>
    .games {
      background-color: #FFFFFF !important;
    }

    .games:hover {
      background-color: #FFFFFF !important;
    }

    #games_button {
      color: #363136 !important;
    }

    #games_button:hover {
      color: #DF6300 !important;
    }
  </style>


            <li class="store">
    <a id="store_button" data-position="header" href="/store" itemprop="url" token="topbar">Store</a>
  </li>

      <style>
      .store {
        background-color: #FFFFFF !important;
      }

      .store:hover {
        background-color: #FFFFFF !important;
      }

      #store_button {
        color: #363136 !important;
      }

      #store_button:hover {
        color: #DF6300 !important;
      }
    </style>
  

          
                  </ul>
      </nav>

      <nav id="header_userpanel_beta" class="header-userpanel" itemscope="" itemtype="http://schema.org/SiteNavigationElement">
        <ul>
                      <li class="userpanel-item queue ">
  <a class="header-icon" href="/home" token="topbar">
    <div class="icon-container">
      <svg viewBox="0 0 48 48">
        <use xlink:href="/i/svg/header.svg#cr_bookmark_header"></use>
      </svg>
    </div>

    <div class="caption">Queue</div>
  </a>
</li>
<li class="userpanel-item random">
  <a class="header-icon" href="/random/anime?random_ref=topbar" token="topbar">
    <div class="icon-container">
      <svg viewBox="0 0 48 48">
        <use xlink:href="/i/svg/header.svg#cr_random"></use>
      </svg>
    </div>

    <div class="caption">Random</div>
  </a>
</li>

<li class="userpanel-item user">
  <div class="dropdown js-dropdown">
    <button id="header_profile_button" class="header-icon js-dropdown-toggle" type="button">
      <div class="icon-container">
        <svg viewBox="0 0 48 48">
          <use xlink:href="/i/svg/header.svg#cr_profile"></use>
        </svg>

              </div>

      <div class="caption">Profile</div>
    </button>

    <div class="dropdown-menu">
      <ul>
        <li class="username">
          <a href="/user/KoroAnime" token="topbar">
            KoroAnime
          </a>
        </li>

                  <li class="has-num">
            <a href="/acct/?action=guestpass" itemprop="url" token="topbar">
              Guest Pass
            </a>
          </li>
        
        <li>
          <div class="border"></div>
        </li>

        <li class="has-num">
          <a href="/inbox" itemprop="url" token="topbar">
            <div class="clearfix cf">
              <span class="left">Inbox</span>
                          </div>
          </a>
        </li>

        <li class="has-num">
          <a href="/notifications" itemprop="url" token="topbar">
            <div class="clearfix cf">
              <span class="left">Notifications</span>
                          </div>
          </a>
        </li>

        <li>
          <div class="border"></div>
        </li>

        
        <li>
          <a id="header_account_settings" href="/acct" itemprop="url" token="topbar">
            Settings
          </a>
        </li>

        <li>
          <a href="http://www.crunchyroll.com/orderstatus" itemprop="url" token="topbar">
            Order History
          </a>
        </li>

                <li>
          <a href="/logout" rel="nofollow" token="topbar">
            Log Out
          </a>
        </li>
      </ul>
    </div>
  </div>
</li>
<li id="header_search_userpanel_item" class="userpanel-item search">
  <button id="header_show_search_button" class="header-icon" type="button">
    <div class="icon-container">
      <svg viewBox="0 0 48 48">
        <use xlink:href="/i/svg/header.svg#cr_search"></use>
      </svg>
    </div>

    <div class="caption">Search</div>
  </button>
</li>

                  </ul>
      </nav>
    </div>

    <form id="header_search_form" class="header-search-form" action="/search" method="get" itemprop="potentialAction" itemscope="" itemtype="http://schema.org/SearchAction">
      <link href="/search?q={q}" itemprop="target">

      <div class="content">
        
        <input name="from" value="god-eater" type="hidden">

        <input id="header_search_input" class="header-searchbox" autocomplete="off" name="q" placeholder="Anime, drama, etc." itemprop="query-input" type="search">

        <button id="header_search_submit_beta" class="header-searchbox-submit" title="Search">
          <svg viewBox="0 0 48 48">
            <use xlink:href="/i/svg/header.svg#cr_search"></use>
          </svg>

          <span class="button-label">Search</span>
        </button>

        <div id="header_search_autocomplete" class="header-search-autocomplete" style="display: none;"></div>
      </div>
    </form>
  </div>
</header>
  <div id="template_scroller" class="ad-skin">
    <div id="template_container">
      <div id="template_body" class="cf new-template-body">
                  <div id="message_box" style="display:none"><div class="message-container cf message-container-only-errors"><img class="message-list-hide" src="/i/icons/remove_grey_14_14.gif"><div class="message-list"></div></div></div>
          <script type="text/javascript">
            Page.messaging_box_controller = new MessageBox({"render_to": "#message_box"});
            Page.messaging_box_controller.addItems([]);
          </script>
                <div style="height:0;visibility:hidden;" class="clearfix"></div>
          <script>
    window.page.ShowView = {
      parameters: {}
    };
  </script>
  <div id="showview-content-header">
    <div class="ch-left">
      <h1 class="ellipsis">
                <span>God Eater</span>
      </h1>
    </div>
    <div class="ch-right">
      <div class="share-buttons cf">
        <div class="facebook">
          <div class="fb-share-button fb_iframe_widget" data-href="http://www.crunchyroll.com/god-eater" data-layout="button" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=&amp;container_width=100&amp;href=http%3A%2F%2Fwww.crunchyroll.com%2Fgod-eater&amp;layout=button&amp;locale=en_US&amp;sdk=joey"><span style="vertical-align: bottom; width: 68px; height: 20px;"><iframe name="fd2dc6edc8e848" title="fb:share_button Facebook Social Plugin" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" style="border: medium none; visibility: visible; width: 68px; height: 20px;" src="https://www.facebook.com/v2.5/plugins/share_button.php?app_id=&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D45%23cb%3Df2099cc4ef5d242%26domain%3Dwww.crunchyroll.com%26origin%3Dhttps%253A%252F%252Fwww.crunchyroll.com%252Ff2c8e4688bafd54%26relation%3Dparent.parent&amp;container_width=100&amp;href=http%3A%2F%2Fwww.crunchyroll.com%2Fgod-eater&amp;layout=button&amp;locale=en_US&amp;sdk=joey" class="" width="1000px" height="1000px" frameborder="0"></iframe></span></div>
        </div>
        <div class="twitter">
          
  <script>
    window.WM.UserConsent.addScript({
      async: true,
      id: 'twitter-wjs',
      src: 'https://platform.twitter.com/widgets.js'
    }, ['social-general']);

    if (!window.WM || window.WM.UserConsent.inUserConsentState(['social-general'])) {
      document.write(`  <a href="https://twitter.com/share" class="twitter-share-button"

          data-url="http://www.crunchyroll.com/god-eater"
    
    
          data-text="Watch God Eater at Crunchyroll"
    
          data-hashtags="crunchyroll"
    
          data-via="Crunchyroll"
    
    
     data-count="horizontal"
     data-dnt="true"

  >Tweet</a>
`);
    }
  </script>  <iframe id="twitter-widget-1" scrolling="no" allowtransparency="true" allowfullscreen="true" class="twitter-share-button twitter-share-button-rendered twitter-tweet-button" style="position: static; visibility: visible; width: 61px; height: 20px;" title="Twitter Tweet Button" src="https://platform.twitter.com/widgets/tweet_button.69e02060c7c44baddf1b5629549acc0c.en.html#dnt=true&amp;hashtags=crunchyroll&amp;id=twitter-widget-1&amp;lang=en&amp;original_referer=https%3A%2F%2Fwww.crunchyroll.com%2Fgod-eater&amp;size=m&amp;text=Watch%20God%20Eater%20at%20Crunchyroll&amp;time=1578077638340&amp;type=share&amp;url=http%3A%2F%2Fwww.crunchyroll.com%2Fgod-eater&amp;via=Crunchyroll" data-url="http://www.crunchyroll.com/god-eater" frameborder="0"></iframe>




        </div>
      </div>
    </div>
  </div>
  
  <div id="source_showview">
    <div id="container" class="cf">
      <div id="main_content" class="left">
        <div id="tabs" class="medium-margin-bottom container-shadow">
          <div class="main-tabs cf">
                          <a id="main_tab_videos" href="/god-eater/videos" class="left selected">Videos</a>
                          <a id="main_tab_reviews" href="/god-eater/reviews" class="left">Reviews</a>
                          <a id="main_tab_discussions" href="/god-eater/discussions" class="left">Comments</a>
                          <a id="main_tab_more" href="/god-eater/more" class="left">More Info</a>
                      </div>
          <div class="sub-tabs cf">
            <div id="subtabs_videos" class="sub-tabs-menu cf " style="1">
              <a id="subtabs_videos_newest" token="sort-newest" href="" class="left block-link sub-tabs-category selected">
                Newest
              </a>
              <a id="subtabs_videos_oldest" token="sort-oldest" href="" class="left block-link sub-tabs-category">
                Oldest
              </a>
            </div>
                        <div id="subtabs_reviews" class="sub-tabs-menu cf" style="display:none;">
              <a href="/god-eater/reviews/helpful/page1" class="left block-link sub-tabs-category selected">
                Most Helpful
              </a>
              <a href="/god-eater/reviews/newest/page1" class="left block-link sub-tabs-category ">
                Newest
              </a>
              <a href="/god-eater/reviews/oldest/page1" class="left block-link sub-tabs-category ">
                Oldest
              </a>
            </div>
          </div>
        </div>
        <div id="showview_content">
          <div id="showview_content_videos">
                          
  <ul class="list-of-seasons cf">
                
              <li class="season">
          <ul class="portrait-grid">
                          <li id="showview_videos_media_684647" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-13-lotus-684647" title="God Eater Episode 13" class="portrait-element block-link titlefix episode">
              <img alt="Lotus" src="https://img1.ak.crunchyroll.com/i/spire2-tmb/955db5c9ffc7bf9bba50cde9da9018c21461609233_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684647" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 13
                              </span>
      <p class="short-desc" dir="auto">
                  Lotus
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684647").data('bubble_data', {"name":"Episode 13 - Lotus","description":"Leaving Lindow to deal with Deus Pita, Lenka and the others rush to Asyl to rescue the people there. But Pita catches up to them, with Lindow's bracelet hanging from its mouth... The 1st Unit is in shock, but they have no time to waste. Suddenly, Pita threatens the safety of Asyl. Lenka beseeches the members of the 1st Unit to remember Lindow's wish and his orders, and inspires the team with his words, \"Believe in your friends! Destroy it!\"","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684645" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-12-united-they-stand-684645" title="God Eater Episode 12" class="portrait-element block-link titlefix episode">
              <img alt="United They Stand" src="https://img1.ak.crunchyroll.com/i/spire3-tmb/4d0b2e53fb611d245f097c314793fb0f1460960335_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684645" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 12
                              </span>
      <p class="short-desc" dir="auto">
                  United They Stand
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684645").data('bubble_data', {"name":"Episode 12 - United They Stand","description":"There is a high possibility that the irregularity in the guiding devices may have been due to internal hacking. Surrounded by Vajra, Lindow continues his lone battle. Lenka acquires a new God Arc and gets Lindow out of harm's way in the knick of time. Reasoning that someone must have set another guiding device that suddenly distracted the Aragami, Lindow sets out to find and destroy it. But Deus Pita appears before him. It is an uphill battle for Lenka and Lindow, but the 1st Unit arrives to help. ","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684643" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-11-operation-meteorite-684643" class="portrait-element block-link titlefix episode">
              <img alt="Operation Meteorite" src="https://img1.ak.crunchyroll.com/i/spire1-tmb/e7d1d73bbeb66fc8539659578a60feb51460384633_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684643" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 11
                              </span>
      <p class="short-desc" dir="auto">
                  Operation Meteorite
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684643").data('bubble_data', {"name":"Episode 11 - Operation Meteorite","description":"Operation Meteorite, a plan to lure Aragami with a newly developed guiding device, is critical to the completion of the Aegis Plan. Lenka is unable to join the unit due to adjustments that must be made on his God Arc, but Lindow recommends him to command the advance base camp. Alisa rejoins the unit, but the others seem to feel uncomfortable around her. Operation Meteorite starts successfully, but suddenly the Aragami turn away from the guiding devices and head northwest. Lindow is sent to do reconnaissance and realizes that the Aragami are converging on Asyl, the settlement that Lindow has been helping.","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684641" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-10-scattered-petals-684641" class="portrait-element block-link titlefix episode">
              <img alt="Scattered Petals" src="https://img1.ak.crunchyroll.com/i/spire3-tmb/577fb21919fceb8321db9aa3dd4ca8dd1459749832_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684641" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 10
                              </span>
      <p class="short-desc" dir="auto">
                  Scattered Petals
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684641").data('bubble_data', {"name":"Episode 10 - Scattered Petals","description":"Fifteen years ago, the Utsugi family finds an abandoned baby and decide to take him in. They name the infant Lenka, and he is raised lovingly by his adoptive mother, father and older sister Iroha. They live in Agir, a refugee commune. One day, Lindow Amamiya, a God Eater, appears and encourages everyone to take the patch test. Anyone testing positive is considered to have attributes of a God Eater, and will be allowed into Fenrir, including any blood-related kin. Lenka's father despises this discriminatory method of selection. However...","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684639" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-9-soma-schicksal-684639" title="God Eater Episode 9" class="portrait-element block-link titlefix episode">
              <img alt="Soma Schicksal" src="https://img1.ak.crunchyroll.com/i/spire1-tmb/1711741b5d87ec4bc59865fd0dcbc9bc1445901284_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684639" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 9
                              </span>
      <p class="short-desc" dir="auto">
                  Soma Schicksal
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684639").data('bubble_data', {"name":"Episode 9 - Soma Schicksal","description":"A change is occurring in Lenka\u2019s body due to over-adaptation to the Oracle Cell. Lenka is in a dilemma when told that while he cannot escape inevitable death, if he resigns as a God Eater, he may be able to prolong his life for a little while. Meanwhile, a briefing is being held on the \u201cMeteorite Strategy,\u201d the crucial mission necessary to execute the Aegis Plan. Lenka\u2019s tactical skills have been recognized and he is appointed a leader. Lenka learns that members of other units avoid Soma who has been labeled a \u201cshinigami\u201d (harbinger of death) and is told by Sakaki, \u201cFate is cruel... It can be said both you and he are its victims.\u201d Soma\u2019s hidden past is revealed to him, but Lenka...","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684637" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-8-sakuya-tachibana-684637" title="God Eater Episode 8" class="portrait-element block-link titlefix episode">
              <img alt="Sakuya Tachibana" src="https://img1.ak.crunchyroll.com/i/spire4-tmb/0ac42b8ec8eb2fe53df9c118621974131444868038_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684637" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 8
                              </span>
      <p class="short-desc" dir="auto">
                  Sakuya Tachibana
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684637").data('bubble_data', {"name":"Episode 8 - Sakuya Tachibana","description":"Lenka and Alisa make it back to the Fenrir Far East Branch. But Alisa suffers from post-traumatic stress and Lenka\u2019s God Arc is badly damaged, so they are put on temporary leave. Flashbacks of her battle with the variant Vajra, the brutal Dyaus Pita, continue to haunt Alisa, and her inability to conquer her fears frustrate her. When Lindow questions why powerful Aragami are heading toward the Far East region, Tsubaki shows him data which shocks him. Meanwhile, Dr. Sakaki looks into how Lenka\u2019s God Arc could possibly be broken. And despite the lack of both New-Types, the Branch Director is about to begin a new battle strategy.","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684635" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-7-a-flower-in-bloom-684635" title="God Eater Episode 7" class="portrait-element block-link titlefix episode">
              <img alt="A Flower in Bloom" src="https://img1.ak.crunchyroll.com/i/spire1-tmb/65b268c017ff7f10c157c2d0952cbb081444167101_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684635" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 7
                              </span>
      <p class="short-desc" dir="auto">
                  A Flower in Bloom
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684635").data('bubble_data', {"name":"Episode 7 - A Flower in Bloom","description":"Lenka and Alisa are rescued from a violent attack of Aragami, then taken by Lindow to Asyl (asylum), a place where people who were turned away at the Fenrir Far East Branch refugee center live and support each other. Making the rounds with Lindow, Lenka comes upon a shocking sight. Lenka is unable to answer when Lindow pointedly asks why he wants to destroy Aragami. A Vajra appears and moves threateningly toward Asyl, and Lindow orders Lenka to \u201cGo back and protect everyone. No one is to die...including yourself.","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684633" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-6-stay-true-684633" class="portrait-element block-link titlefix episode">
              <img alt="STAY TRUE" src="https://img1.ak.crunchyroll.com/i/spire3-tmb/250a833d2508a41eeceb0f2d5526705d1443547137_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684633" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 6
                              </span>
      <p class="short-desc" dir="auto">
                  STAY TRUE
              </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684633").data('bubble_data', {"name":"Episode 6 - STAY TRUE","description":"Lenka, Alisa, Kota and Sakuya are out on a mission to hunt two large-type Aragami known as Vajra when they encounter an unusual black Vajra that devours even its own species. This Vajra is ridiculously powerful and the 1st Unit ends up scattered. Lenka takes Alisa who has lost consciousness and escapes into an abandoned building. His God Arc is fractured and Lenka\u2019s confidence takes a serious blow. Alisa, who also loses her God Arc in the fray, is overcome with terror as childhood memories of her parents being killed by the black Vajra come flooding back. But it\u2019s not over for the battered and wounded duo as a pack of Ogretails threateningly advance toward them in the abandoned building where they sought refuge.","offsetLeft":157,"offsetTop":-1});
</script>
                          <li id="showview_videos_media_684631" class="hover-bubble group-item">
  <div class="wrapper container-shadow hover-classes" data-classes="container-shadow-dark">
    <a href="/god-eater/episode-5-an-eye-for-an-eyeall-in-vain-684631" title="God Eater Episode 5" class="portrait-element block-link titlefix episode">
              <img alt="An Eye for an Eye/All in Vain" src="https://img1.ak.crunchyroll.com/i/spire4-tmb/9856089aaa188e51771e5e50854319491442295874_wide.jpg" class="landscape">
            <div class="episode-progress-bar">
        <div class="episode-progress" media_id="684631" style="width: 0%;"></div>
      </div>
      <span class="series-title block ellipsis" dir="auto">
                                          Episode 5
                              </span>
      <p class="short-desc" dir="auto">
                  An Eye for an Eye/All in... </p>
    </a>
  </div>
</li>
<script>
  $("#showview_videos_media_684631").data('bubble_data', {"name":"Episode 5 - An Eye for an Eye\/All in Vain","description":"Lenka is frustrated to learn that the Aegis Project has a long, long way to go. In order to complete the project.

**Comment by KoroFX** [comment]
Als wenn er die gesamte HTML der seite kopiert anstatt nur den Link, deshalb währe nen URL Kopieren Knopf oder ne URL Leiste sehr gut für mich....

**Comment by hama3254** [comment]
die neue version läd gerade noch hoch und sollte gleich verfügbar sein :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x

**Comment by KoroFX** [comment]
Cool

**Comment by KoroFX** [comment]
#10
