### ISSUE TITLE
Datei als MKV speichern

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#90]
Hallo ich hätte einen kleinen Verbesserungsvorschlag. 

Es wäre toll wenn es eine Option im Settings-Output Reiter geben würde wo man
einstellen kann das die Datei als MKV gespeichert wird.

Des müsste ja mit FFMPEG machbar sein oder?

z.b. `ffmpeg -i input1 -i input2 -c copy -map 0 -map 1 output.mkv`

Vielen Dank schon mal.  MFG Schizo1987

**Comment by hama3254** [comment]
Möglich wäre es, es macht aber keinen Unterschied ob man mkv oder mp4 nimmt.
Beides sind nur Container für verschiedene Video und Audio Formate/Codecs. 
Ich sehe keinen Vorteil von mkv und damit auch keinen Sinn dahinter das aufwendig einzubauen.

**Comment by Schizo1987** [comment]
Ok alles klar du hast ja Recht ;-)
