### ISSUE TITLE
Save on folders

### ISSUE THREAD

**Issue by egoitzro** [hama3254/Crunchyroll-Downloader-v3.0#901]
Hello, I think that in previous versions you could choose an option that allowed you to create folders for each anime, and in the latest version it is either not there or I am unable to find it. Thank you

**Comment by hama3254** [comment]
You can select to create either subfolders for only the series or for the series and each season.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/a704ad80-c44f-4a49-826d-f39af309282b)

**Comment by egoitzro** [comment]
Because I have updated to the latest version and I had a small problem logging in, which I already solved, I deleted the configurations I had from previous versions and when I added the downloads I did not remember where that option was, I thought it was somewhere else.

Thank you so much
