### ISSUE TITLE
Dual-Audio possible on movies?

### ISSUE THREAD

**Issue by Kyouma95** [hama3254/Crunchyroll-Downloader-v3.0#902]
Hi, is it possible to get a movie with Japanese and german dub together in one file?

Or do i need to download them separately und extract the audio file?

**Comment by AndroidFire9704** [comment]
du kannst auch zweite Tonspur so runterladen und anschließend in die bspw. mkv Datei einfügen

**Comment by Kyouma95** [comment]
Hab jetzt allerdings keine Option gefunden, mit der man nur die Tonspur runterladen kann.

**Comment by hama3254** [comment]
Im `Add Video` fenster gibt es ein drop down mit der option nur Ton zu laden oder sogar die tonspur gleich auf in bestehende datei hinzuzufügen.
Dabei ist ein bekanntes Probleme das der ton nicht zwangsläufig passt (siehe #701).

**Comment by Kyouma95** [comment]
Danke, hat wunderbar geklappt. 

Besteht denn überhaupt die Möglichkeit direkt mit 2 Audio-Spuren eine/einen Serie/Film runterzuladen?

**Comment by hama3254** [comment]
> Besteht denn überhaupt die Möglichkeit direkt mit 2 Audio-Spuren eine/einen Serie/Film runterzuladen? Bzw. gibt es Pläne dazu?

Durch verschiedene probleme ist das nicht wirklich möglich, sowohl falsche metadaten von CR als auch verschiedene Videospuren führen zu keinem guten ergebnis.

**Comment by Kyouma95** [comment]
Alles klar, danke für die Antwort.
