### ISSUE TITLE
Error downloading Music Videos

### ISSUE THREAD

**Issue by GHCripto** [hama3254/Crunchyroll-Downloader-v3.0#903]
**Summary**
When I try to download a music video I get this error:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/64995694/f4def839-7f03-46be-9051-8b9da05b27e5)
"Index out of bounds of array"

This doesn't happen with anime episodes, it just doesn't work with Music Videos :'(
I am on version `3.17.2`

**Comment by GHCripto** [comment]
Oh, since I hadn't used this tool in a while, I thought the version I had would no longer work well and updated, but it seems to still work fine on `3.15.6.1`

**Comment by hama3254** [comment]
This is probably some collateral damage from #853.
I see how I can merge both versions of the API.
