### ISSUE TITLE
Auto download videos with the home link

### ISSUE THREAD

**Issue by tiao1314** [hama3254/Crunchyroll-Downloader-v3.0#904]
Hi wondering if there is a way to save time if you put the home page of a anime it will download all the episodes instead of putting each episodes 1 by 1. Just to save a lot of time

**Comment by hama3254** [comment]
This is already added possible.
Just select the Dub at the top, below that you can choose the season and the last two drop downs are for episodes (start to end)
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9b2869d9-4d68-4725-93eb-9cfd05ed9c87)
