### ISSUE TITLE
Cannot download while logged into browser 

### ISSUE THREAD

**Issue by SaintXye** [hama3254/Crunchyroll-Downloader-v3.0#907]
**Describe the bug**
When logged into the downloader browser I am unable to download anything and get the error "Status: Failed - no video, Check CR login" when I log out of the browser I can download non-premium content as usual however it will not download any language other than Japanese (possibly any language other than the original I haven't tested that)
![Screenshot 2024-03-04 140435](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/76862251/287e9bc4-b87d-487c-91f5-57b647106845)

 - Platform: Crunchyroll
 - Settings [e.g. Null, English, Default ffmpeg
![Screenshot 2024-03-04 134837](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/76862251/69625605-fad2-40f2-a947-b62b2ec638ff)
![Screenshot 2024-03-04 134855](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/76862251/aa4875c7-c59c-4e78-8edd-cc5567265046)
]
 - Version: v3.17.1

**Additional context**
After some messing around I got it to work again but I'm not sure why or what may have helped by 

1. I logged out of CR on the CD browser
2. Reset my edge browser
3. logged into CR on the edge browser
4. waited for awhile

then next time I did try it (about 24 hrs later) it did work as intended again and I was able to sign in and download content and have it download both Japanese and English but then it reverted to the same thing after about 15 downloads.
Not sure if any of what I did really had an affect but figured I'd put it here

**Comment by hama3254** [comment]
>When logged into the downloader browser I am unable to download anything and get the error "Status: Failed - no video, Check CR login"

The error message means the downloader made a successful request to CR and got the data for the title etc. but the video stream was missing from it.
To my knowledge this is only on premium episodes without a premium account.

**Comment by SaintXye** [comment]
> > When logged into the downloader browser I am unable to download anything and get the error "Status: Failed - no video, Check CR login"
> 
> The error message means the downloader made a successful request to CR and got the data for the title etc. but the video stream was missing from it. To my knowledge this is only on premium episodes without a premium account.

This was happening with Chainsaw Man which I don't think is premium anymore
I am not premium atm but I will pay sub and lyk if it changes for me

**Comment by SaintXye** [comment]
> > When logged into the downloader browser I am unable to download anything and get the error "Status: Failed - no video, Check CR login"
> 
> The error message means the downloader made a successful request to CR and got the data for the title etc. but the video stream was missing from it. To my knowledge this is only on premium episodes without a premium account.

While using Premium I haven't had the issue but strange that it happened without on Chainsaw Man since it isn't premium content

**Comment by hama3254** [comment]
I have not seen incorrectly tagged premium episodes on CR yet, only on Funimation.

If premium solves the issue than you should be fine for a month or so.
There is also no download limit, I only would recommend to restart the download after 12 episodes to refresh the session/cookies.
