### ISSUE TITLE
VTT/Crunchyroll?

### ISSUE THREAD

**Issue by anmovi** [hama3254/Crunchyroll-Downloader-v3.0#909]
Hay alguna opción para descargar subtítulos en formato .vtt para Crunchyroll, manteniéndolos limpios y sin estilos, si es así, podrían implementarlo, estoy haciendo conversiones con editores como Subtitle Edit, pero siempre hay líneas basura superpuestas, y tengo que editar cada línea manualmente, si hubiera una opción para elegir formato sería genial.

translated by DeepL.com
Is there any option to download subtitles in .vtt format for Crunchyroll, keeping them clean and without styles, if so, could you implement it, I'm doing conversions with editors like Subtitle Edit, but there are always overlapping junk lines, and I have to edit each line manually, if there was an option to choose format it would be great.

**Comment by hama3254** [comment]
Some Videos have Captions which are VTT but they are an accessibility feature and include sounds.
I also have any seen not much of them.
Normally Crunchyroll uses `ass` for it's feature set (it can replace text on the screen like signs).

**Comment by anmovi** [comment]
Lo siento, pero no me quedo claro, ¿entonces no se puede?
¿Esto ayuda en algo? y ¿cómo activarlo?
-
I'm sorry, but I'm not clear, so you can't?
Does this help at all, and how to activate it?
![2024-03-14_17-46-08](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/148601238/49246355-a1c2-4c8b-a94a-3e57e917a48d)
