### ISSUE TITLE
Not being able to change the number of simultaneous downloads on the v3.6 5-Pre-release

### ISSUE THREAD

**Issue by TaigaChiquita** [hama3254/Crunchyroll-Downloader-v3.0#91]
As the title says Im not being able to download more than the 2 default amount of simultaneous downloads with this Pre-release version 
![image](https://user-images.githubusercontent.com/8277764/99952516-8b2ba080-2d5e-11eb-818e-26805bb55984.png)
Every time i try to change that number and click on "SAVE & EXIT" i come back to the settings tab and it is still on the default 2 when using the 3.5.7 version i was not getting this problem so for now i will keep using that one instead

**Comment by hama3254** [comment]
If you have re-encoding enabled in the output settings then the simultaneus downloads is maxed out with 2 for "nvec" due to nvidia driver limitations and 1 for "libx26x" because the re-encoding takes mostly 100% CPU anyways.

**Comment by TaigaChiquita** [comment]
I have the next settings under the Output tab 
![image](https://user-images.githubusercontent.com/8277764/99962173-7820cc80-2d6e-11eb-8254-22f6cbb150cd.png)
I haven't touched the re-encoding stuff since i don't know much about what that does

**Comment by TaigaChiquita** [comment]
also my CPU will stay around 40% used and my gpu won't even go above 10%
I have an i7 7700K and a RTX2080 if that matters at all

**Comment by hama3254** [comment]
> I have the next settings under the Output tab
> ![image](https://user-images.githubusercontent.com/8277764/99962173-7820cc80-2d6e-11eb-8254-22f6cbb150cd.png)
> I haven't touched the re-encoding stuff since i don't know much about what that does

Well it looks to me that below the "ffmpeg command" is `h264_nvenc` selected.
Check the box above and then select `-c copy` there.

**Comment by TaigaChiquita** [comment]
thanks now im able to have more downloads, for some reason any release i download gets that h264_nvenc tag on there but just in the 3.6 pre-release it wont let me get more than 2 downloads, anyway problem solves, thanks again.

**Comment by hama3254** [comment]
> thanks now im able to have more downloads, for some reason any release i download gets that h264_nvenc tag on there but just in the 3.6 pre-release it wont let me get more than 2 downloads, anyway problem solved, thanks again.

The default is `- c copy` but in the moment you change the setting it will be saved in the windows registry so new versions always use the same settings as the old one.
