### ISSUE TITLE
download maximum reached how to fix ?

### ISSUE THREAD

**Issue by khalidSA111** [hama3254/Crunchyroll-Downloader-v3.0#912]
**Describe the bug**
i use Crunchyroll-Downloader-v3.18
if i download any anime this will happen
download maximum reached how to fix ?
i have crunchyroll mega fan premium account

**Where does the issue happen?**
crunchyroll downloader

**Screenshots**
![0000000000000000](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/163581429/f5a0cf91-3ea5-454a-861e-453db938f14b)

**Additional context**
the download process seems to have crashed
press the play button again to retry
download maximum reached
press ok to ignore
the download process seems to have crashed again

log
`
3/15/2024 9:00:35 PM -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0" -headers "ACCEPT-ENCODING: *" -i "https://pl.crunchyroll.com/evs3/ed9de66828e653af4139210de9b38736/assets/937lratk51h0pgz_,2470533.mp4,2470529.mp4,2470525.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9lZDlkZTY2ODI4ZTY1M2FmNDEzOTIxMGRlOWIzODczNi9hc3NldHMvOTM3bHJhdGs1MWgwcGd6XywyNDcwNTMzLm1wNCwyNDcwNTI5Lm1wNCwyNDcwNTI1Lm1wNCwudXJsc2V0L21hc3Rlci5tM3U4IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzEwNjk4NDMwfX19XX0_&Signature=P5gtP1EH1qJv11iciNrYwkJpPqsnHsHMg0C8D8KLw1NlVvCnDzc4kLmWdrMGtG1GHFBPH6AbFSlxktATl-reFmAQ245Z~4fhIfwP1nWQqajhzhLZEVaca9RpcUl9KuSYr0Hrukh~8oJddKaIaoqiV47RUkPvgGctIitJBgEgthx3QtXSUBmB5eFRGla6OVDyynsREg4UIIdUiSWikP8m1gimNeIi33ZK7rGkK2SFDqN5MQKkYBowsXrCql~rvQ5BuDIHdD7Vgz4-6CkB1KvGME-LTx1e~tnaV-P4oJGNHyt0UZr~I8B59ZorR-AHVJHJ19P-Hrgp4pBRLkpb0ijIEw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA" -metadata:s:a:0 language=jpn -c copy -c:a copy -bsf:a aac_adtstoasc "D:---1 ANIME\1-Naruto\Naruto Season 1 Episode 1.mp4"

3/15/2024 9:00:35 PM ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
3/15/2024 9:00:35 PM built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
3/15/2024 9:00:35 PM configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
3/15/2024 9:00:35 PM libavutil 57. 28.100 / 57. 28.100
3/15/2024 9:00:35 PM libavcodec 59. 37.100 / 59. 37.100
3/15/2024 9:00:35 PM libavformat 59. 27.100 / 59. 27.100
3/15/2024 9:00:35 PM libavdevice 59. 7.100 / 59. 7.100
3/15/2024 9:00:35 PM libavfilter 8. 44.100 / 8. 44.100
3/15/2024 9:00:35 PM libswscale 6. 7.100 / 6. 7.100
3/15/2024 9:00:35 PM libswresample 4. 7.100 / 4. 7.100
3/15/2024 9:00:35 PM libpostproc 56. 6.100 / 56. 6.100
3/15/2024 9:00:35 PM [https @ 0000028a05cc6380] No trailing CRLF found in HTTP header. Adding it.
3/15/2024 9:00:36 PM [https @ 0000028a05cc6380] HTTP error 403 Forbidden
3/15/2024 9:00:36 PM https://pl.crunchyroll.com/evs3/ed9de66828e653af4139210de9b38736/assets/937lratk51h0pgz_,2470533.mp4,2470529.mp4,2470525.mp4,.urlset/master.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9lZDlkZTY2ODI4ZTY1M2FmNDEzOTIxMGRlOWIzODczNi9hc3NldHMvOTM3bHJhdGs1MWgwcGd6XywyNDcwNTMzLm1wNCwyNDcwNTI5Lm1wNCwyNDcwNTI1Lm1wNCwudXJsc2V0L21hc3Rlci5tM3U4IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzEwNjk4NDMwfX19XX0_&Signature=P5gtP1EH1qJv11iciNrYwkJpPqsnHsHMg0C8D8KLw1NlVvCnDzc4kLmWdrMGtG1GHFBPH6AbFSlxktATl-reFmAQ245Z~4fhIfwP1nWQqajhzhLZEVaca9RpcUl9KuSYr0Hrukh~8oJddKaIaoqiV47RUkPvgGctIitJBgEgthx3QtXSUBmB5eFRGla6OVDyynsREg4UIIdUiSWikP8m1gimNeIi33ZK7rGkK2SFDqN5MQKkYBowsXrCql~rvQ5BuDIHdD7Vgz4-6CkB1KvGME-LTx1e~tnaV-P4oJGNHyt0UZr~I8B59ZorR-AHVJHJ19P-Hrgp4pBRLkpb0ijIEw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA: Server returned 403 Forbidden (access denied)

**Comment by khalidSA111** [comment]
i found the fix

just make resolution auto it s will work

**Comment by khalidSA111** [comment]
the problem come back again

**Comment by hama3254** [comment]
most likley the same cause as #911
