### ISSUE TITLE
Exception with download not having a episode title

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#914]
**Describe the bug**
When I at tempt to download 
https://www.crunchyroll.com/watch/GK9U3KPEW/
I receive an exception error

**Where does the issue happen?**

 - Platform: Crunchyroll
 - Settings:
 - Output: Hybrid, 480p, MKV, Copy, 
 - Naming AnimeTitle;Season;EpisodeNR;EpisodeName;, The rest is defaults
 - Crunchyroll. Dubbed Japanese. Hardsub unchecked and null, softsubs set to English, CC is checked, Chapters is checked
 - Version 3.18

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/751507/266fee83-422a-41c9-9b4c-8e476ea3f2f3)

I can provide screenshots of config if needed.
 
**Additional context**
My first attempt to download ended up with English dub and subtitles.

**Comment by napgiver** [comment]
I'm getting the same error now. Worked fine about 6 and a half hours ago.

**Comment by orosee** [comment]
The same here. Identical to the above description including the error report. I had used 3.15 before until previous Friday (Frieren new release), today it wouldn't work anymore (m3u error?), updated to 3.18, now stuck with the above error.

**Comment by pruebark9** [comment]
Same here, I have checked if I am logged in and yes, everything is fine. I am using the latest version.

**Comment by hama3254** [comment]
this is a bigger issue that may mean the end of the downloader more about that is in #911
