### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by tormento** [hama3254/Crunchyroll-Downloader-v3.0#915]
With 3.18, when trying to download [Frieren E27](https://www.crunchyroll.com/it/watch/GEVUZD0V9/an-era-of-humans), I get:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/2351785/fd1550e5-fc98-4221-91ca-db84f70f0f34)

Rolling back to 3.17.3, I get:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/2351785/29d116a5-55c6-4d46-9011-0275d93969a7)

**Comment by hama3254** [comment]
this is a bigger issue that may mean the end of the downloader more about that is in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/911
