### ISSUE TITLE
The download process seems to have crashed

### ISSUE THREAD

**Issue by guitarjorge24** [hama3254/Crunchyroll-Downloader-v3.0#917]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.18

Logfile/Logtext : [KAGUYA-SAMA LOVE IS WAR Season 2 Episode 12.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/14626031/KAGUYA-SAMA.LOVE.IS.WAR.Season.2.Episode.12.The.Student.Council.Would.Like.a.Group.Photo.The.Student.Council.Is.Going.to.Get.That.Group.Photo.Chika.Fujiwara.Wants.to.Inflate.log)

When I try to download an episode it fails immediately saying "The download process seems to have crashed". 
I have tried restarting the app and restarting my PC.
I tried downloading an episode of Kaguya-sama and also Frieren and both failed in the same way.
I have a Crunchyroll subscription.

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/12472021/c38ccdbf-066e-4abc-8632-c4c84ab0e65e)

**Comment by deadlynjdj** [comment]
check https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/911

**Comment by guitarjorge24** [comment]
does that issue have the same root cause?

**Comment by hama3254** [comment]
@guitarjorge24 if you use `[Auto]` as resolution than this is very likely the same as #911 where the video is not accessible anymore.

**Comment by guitarjorge24** [comment]
oh I see, yeah, I do use Auto as my resolution. If I change it to 1080, then I get:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/12472021/fb356ce0-bb42-45bb-b0e5-b20686982326)

**Comment by Primelikes01** [comment]
> oh I see, yeah, I do use Auto as my resolution. If I change it to 1080, then I get:
> 
> ![image](https://private-user-images.githubusercontent.com/12472021/313455135-fb356ce0-bb42-45bb-b0e5-b20686982326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NjkxNjgsIm5iZiI6MTcxMDY2ODg2OCwicGF0aCI6Ii8xMjQ3MjAyMS8zMTM0NTUxMzUtZmIzNTZjZTAtYmI0Mi00NWJiLWIwZTUtYjIwNjg2OTgyMzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmU5N2NhY2FmZjc5NTk4ZGFjNWExOTk5ZjgxZDYwOGZmMGU0NzA2NDNiNTEzMjBiN2FjOGI4MTU1YmFhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xu1y1D9Gq8eN9Lc7SwnzrSlLIEZ_7y8EuTTX2ozWaRE)

Same Problem me also face. i think this is my pc problem & tried to uninstall & reinstall So many times 😁

**Comment by Primelikes01** [comment]
Same Problem me also face. i think this is my pc problem & tried to uninstall & reinstall So many times 😁  
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/158451701/e8b1b27b-889e-4d8f-a22f-94e6b49f694e)
