### ISSUE TITLE
This is (Not) the END!

### ISSUE THREAD

**Issue by hama3254** [hama3254/Crunchyroll-Downloader-v3.0#918]
The current status is very clear, [i don't have any working video streams anymore](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/911#issuecomment-2000647112).

The only streams left are DRM protected which i was not able to downloader yet and i can not try **legaly** anyways.

>Gesetz über Urheberrecht und verwandte Schutzrechte (Urheberrechtsgesetz)
§ 95a Schutz technischer Maßnahmen
>>
>>(1) Wirksame technische Maßnahmen zum Schutz eines nach diesem Gesetz geschützten Werkes oder eines anderen nach diesem Gesetz geschützten Schutzgegenstandes dürfen ohne Zustimmung des Rechtsinhabers nicht umgangen werden, soweit dem Handelnden bekannt ist oder den Umständen nach bekannt sein muss, dass die Umgehung erfolgt, um den Zugang zu einem solchen Werk oder Schutzgegenstand oder deren Nutzung zu ermöglichen.

ChatGPT translates it to english like this.

>>
>>(1) Effective technical measures for the protection of a work protected under this law or any other subject matter protected under this law may not be circumvented without the consent of the rights holder, provided that the person undertaking such action knows or ought to know, given the circumstances, that the circumvention is carried out to enable access to such work or subject matter, or its use.

**Comment by AsIFall** [comment]
Okay, this seems to be the end of downloading and watching anime in 1080p offline. Thank you for your work and all those fixes on the CR Downloader.

**Comment by HiSHiR0** [comment]
Years ago, your Tool was one of the first I ever used for Downloading.
It's sad to see this Project is now EOL.
Thank you for your hard Work and all the Time you invested in this Project <3

**Comment by tamodolo** [comment]
You can legally decrypt drm but you can't provide keys. Instead you can ask the user to provide one. I read in yt-dlp that cr is using widevine now. And there's plenty of decrypt software here on github to decrypt that without bundling any keys (so it's legal to distribute). Guides do exist to get keys. This is a solution.

**Comment by pruebark9** [comment]
The end of a great .... for a few days. I'm sure you'll find a solution. I hope so from the bottom of my heart.

**Comment by NyloFigueiraPinto** [comment]
I also hope you find a solution. Thank you very much for your work!

**Comment by DaStar22** [comment]
it's been a good run guys GG.

**Comment by 619beave** [comment]
I'm sorry to see this program go.  It was a great way to watch the anime, in my case. 

I hope you are well in the future Hama.

**Comment by guiskas** [comment]
It's bad news. but thank you very much for the effort made during these years. Thank you very much

**Comment by petenun** [comment]
@hama3254 , Thank you very much for the years of hard and diligent work you've put into developing and supporting your application and your users. I know all this was no small effort on your part, and you are very much appreciated! Thank you!!

**Comment by daviddanielng** [comment]
Oh nooo, this cant be... tears more tears. 
Just finished a downloader few hours ago.

**Comment by daviddanielng** [comment]
> You can legally decrypt drm but you can't provide keys. Instead you can ask the user to provide one. I read in yt-dlp that cr is using widevine now. And there's plenty of decrypt software here on github to decrypt that without bundling any keys (so it's legal to distribute). Guides do exist to get keys. This is a solution.

tell me more, how do i go about this?

**Comment by tamodolo** [comment]
> > You can legally decrypt drm but you can't provide keys. Instead you can ask the user to provide one. I read in yt-dlp that cr is using widevine now. And there's plenty of decrypt software here on github to decrypt that without bundling any keys (so it's legal to distribute). Guides do exist to get keys. This is a solution.
> 
> tell me more, how do i go about this?

What do you want to know?

**Comment by daviddanielng** [comment]
> > > You can legally decrypt drm but you can't provide keys. Instead you can ask the user to provide one. I read in yt-dlp that cr is using widevine now. And there's plenty of decrypt software here on github to decrypt that without bundling any keys (so it's legal to distribute). Guides do exist to get keys. This is a solution.
> > 
> > 
> > tell me more, how do i go about this?
> 
> What do you want to know?

How can I download DRM protected streams and decrypt it.

**Comment by ms-ku** [comment]
Hallo Hama
Auch von meiner Seite ein großes DANKESCHÖN für die Arbeit, den Gehirnschmalz und das Herzblut das du und dein Team in dieses Projekt gesteckt habt. Heutzutage ist es nicht mehr gang und gäbe das man z.B. teilweise mitten in der Nacht noch für andere Leute sein Projekt pflegt, vor allem wenn dies kostenlos passiert!
Es ist m.M.n. auch traurig das dieses Aus fremdgesteuert ist und man es nicht zu seinem selbstbestimmten Zeitpunkt machen kann.
Nochmals Danke und Grüße
msku

**Comment by tamodolo** [comment]
> Can you point to a source or something that would help me even if it just 10%.

Google is your friend. Or Duck Duck Go... Take a look in other issues in this hub or in other tools that did the same. You'll get valuable hints too. If you want the easy exit, there's paid software called streamfab that still can download CR (but is crazy expensive). yt-dl still can download .ass subtitles as streamfab convert to .srt. The free exit doesn't exist now so is harder and will demand that you improve your knoledge at @hama3254 level (or you'll eventually step over a 3rd party that already solved this as time passes).

This freedom is a game of mouse and cat. We are at the cat's turn. The good thing is the solution is already out there.

**Comment by daviddanielng** [comment]
👍

**Comment by napgiver** [comment]
Just a heads up to anyone looking at streamfab. Please correct me if I'm wrong but, from testing, I believe it only grabs the English Dub Hardsub stream. No Softsubs. Which is a disappointment.

**Comment by Nightcore974** [comment]
> > Can you point to a source or something that would help me even if it just 10%.
> 
> Google is your friend. Or Duck Duck Go... Take a look in other issues in this hub or in other tools that did the same. You'll get valuable hints too. If you want the easy exit, there's paid software called streamfab that still can download CR (but is crazy expensive). yt-dl still can download .ass subtitles as streamfab convert to .srt. The free exit doesn't exist now so is harder and will demand that you improve your knoledge at @hama3254 level (or you'll eventually step over a 3rd party that already solved this as time passes).
> 
> This freedom is a game of mouse and cat. We are at the cat's turn. The good thing is the solution is already out there.

Any tutorial on how to download only subtitles in the language we need please?

**Comment by pruebark9** [comment]
> > > Can you point to a source or something that would help me even if it just 10%.
> > 
> > 
> > Google is your friend. Or Duck Duck Go... Take a look in other issues in this hub or in other tools that did the same. You'll get valuable hints too. If you want the easy exit, there's paid software called streamfab that still can download CR (but is crazy expensive). yt-dl still can download .ass subtitles as streamfab convert to .srt. The free exit doesn't exist now so is harder and will demand that you improve your knoledge at @hama3254 level (or you'll eventually step over a 3rd party that already solved this as time passes).
> > This freedom is a game of mouse and cat. We are at the cat's turn. The good thing is the solution is already out there.
> 
> Any tutorial on how to download only subtitles inj ass format in the language we need using yt-dlp (i dont know how to use that software) please?


The CR Downloader still works for subtitles.

**Comment by Nightcore974** [comment]
> > > > Can you point to a source or something that would help me even if it just 10%.
> > > 
> > > 
> > > Google is your friend. Or Duck Duck Go... Take a look in other issues in this hub or in other tools that did the same. You'll get valuable hints too. If you want the easy exit, there's paid software called streamfab that still can download CR (but is crazy expensive). yt-dl still can download .ass subtitles as streamfab convert to .srt. The free exit doesn't exist now so is harder and will demand that you improve your knoledge at @hama3254 level (or you'll eventually step over a 3rd party that already solved this as time passes).
> > > This freedom is a game of mouse and cat. We are at the cat's turn. The good thing is the solution is already out there.
> > 
> > 
> > Any tutorial on how to download only subtitles inj ass format in the language we need using yt-dlp (i dont know how to use that software) please?
> 
> The CR Downloader still works for subtitles.

Oh that's great, i thought it wouldn't work. Streamfab + CR downloader subs are kinda a great way to get it done i guess. So how come streamfab can still download videos from CR?

**Comment by tamodolo** [comment]
> > > > > Can you point to a source or something that would help me even if it just 10%.
> > > > 
> > > > 
> > > > Google is your friend. Or Duck Duck Go... Take a look in other issues in this hub or in other tools that did the same. You'll get valuable hints too. If you want the easy exit, there's paid software called streamfab that still can download CR (but is crazy expensive). yt-dl still can download .ass subtitles as streamfab convert to .srt. The free exit doesn't exist now so is harder and will demand that you improve your knoledge at @hama3254 level (or you'll eventually step over a 3rd party that already solved this as time passes).
> > > > This freedom is a game of mouse and cat. We are at the cat's turn. The good thing is the solution is already out there.
> > > 
> > > 
> > > Any tutorial on how to download only subtitles inj ass format in the language we need using yt-dlp (i dont know how to use that software) please?
> > 
> > 
> > The CR Downloader still works for subtitles.
> 
> Oh that's great, i thought it wouldn't work. Streamfab + CR downloader subs are kinda a great way to get it done i guess. So how come streamfab can still download videos from CR?

They use widevine decryption.

**Comment by tamodolo** [comment]
btw, yt-dlp just locked an issue saying that they only discuss DRM-free extractors. yt-dlp is pretty much useles for CR in the foreseeable future.

**Comment by Nightcore974** [comment]
> btw, yt-dlp just locked an issue saying that they only discuss DRM-free extractors. yt-dlp is pretty much useles for CR in the foreseeable future.
> 
> [yt-dlp/yt-dlp#9453 (comment)](https://github.com/yt-dlp/yt-dlp/issues/9453#issuecomment-2005133169)

Oh okay, thanks for the answer.

**Comment by LiderOscuro** [comment]
Es una verdadera lastima ver que ya no se puede arreglar, la verdad es que disfruté mucho de este programa, poder ver capitulos de anime sin conexión y en alta calidad era lo mejor, Saludos Hama.

**Comment by xFanexx** [comment]
**DEU:** Danke für deine investierte Zeit und den Aufwand, den Downloader für (hoffentlich) viele Nutzer zugänglich zu machen!

**ENG:** Thank you for your invested time and effort in making the downloader accessible to (hopefully) many users!

**Comment by Jaynator495** [comment]
> Oh that's great, i thought it wouldn't work. Streamfab + CR downloader subs are kinda a great way to get it done i guess. So how come streamfab can still download videos from CR?

You may want to look into anidl for a more streamlined approach than that

**Comment by tamodolo** [comment]
> > Oh that's great, i thought it wouldn't work. Streamfab + CR downloader subs are kinda a great way to get it done i guess. So how come streamfab can still download videos from CR?
> 
> You may want to look into anidl for a more streamlined approach than that

Was reading about it just now. They can download CR DRM if you provide a CDM key. If you don't have one it can use the android api and download a crappy quality video without DRM.

**Comment by hama3254** [comment]
> btw, yt-dlp just locked an issue saying that they only discuss DRM-free extractors. yt-dlp is pretty much useles for CR in the foreseeable future.

i expected them to stop the CR extractor but that reaction seems a little bit `too heated`.

While i don't think the old links will work again, there are still there which is (part of) the reason i did not yet change this project into a public archive.

In the same time i would also like everyone to stay "educational" so please no direct instructions about DRM circumvention.

**Comment by pruebark9** [comment]
Couldn't you do something like anidl? Update the program but for it to work, each user would have to dump the cdm and each one would take care of that.

**Comment by hama3254** [comment]
> Couldn't you do something like anidl? Update the program but for it to work, each user would have to dump the cdm and each one would take care of that.

I don't understand how this even works, getting the dump is the easy part there.
Also i think this is already illegal for me and i don't risk anything since that can destroy once life ([Jail?](https://www.youtube.com/watch?v=U6H4iv1iOOU) Money?)  

And the most important issue  
<details>
  <summary>I am kind of busy for the next year(s) with my house</summary> 

![küche](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/82893754-978e-4a54-a3f9-c88d4c77535b)
  
</details>

**Comment by stephan1978** [comment]
for me it is legal, i pay for looking crunchyroll and in my country i have the right too make 1 legal copy for
 what i pay. so no onepiece and dragonball again. that make me sad.

**Comment by pruebark9** [comment]
> > Couldn't you do something like anidl? Update the program but for it to work, each user would have to dump the cdm and each one would take care of that.
> 
> I don't understand how this even works, getting the dump is the easy part there. Also i think this is already illegal for me and i don't risk anything since that can destroy once life ([Jail?](https://www.youtube.com/watch?v=U6H4iv1iOOU) Money?)
> 
> And the most important issue
> 
> I am kind of busy for the next year(s) with my house

Wow, yes, that house has many hours of work ahead xd. Thanks again for your work.

**Comment by stephan1978** [comment]
no i cant do this things. sorry.

    Am Dienstag, 19. März 2024 um 20:25:43 MEZ hat Sabrina ***@***.***> Folgendes geschrieben:  
 
 




Couldn't you do something like anidl? Update the program but for it to work, each user would have to dump the cdm and each one would take care of that.


I don't understand how this even works, getting the dump is the easy part there. Also i think this is already illegal for me and i don't risk anything since that can destroy once life (Jail? Money?)

And the most important issue

I am kind of busy for the next year(s) with my house


Wow, yes, that house has many hours of work ahead xd. Thanks again for your work.

**Comment by karurosu15** [comment]
This is the end of downlad?

**Comment by bybpow** [comment]
Thank you for your work, Hama. This was a wonderful app. Hope you can continue on it in the future.

**Comment by Zanatus** [comment]
Any plans of adding a feature where the user adds his L3 key to it so it can decrypt?

**Comment by daviddanielng** [comment]
> Any plans of adding a feature where the user adds his L3 key to it so it can decrypt?

Not at the moment, according to repo owner [comment](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/918#issuecomment-2007889854).

**Comment by pjohan** [comment]
> Any plans of adding a feature where the user adds his L3 key to it so it can decrypt?

https://github.com/anidl/multi-downloader-nx

**Comment by petenun** [comment]
Not to beat a dead horse, but I think a lot of people are missing the point that the CRDL project has been terminated indefinitely and the developer no longer has time to invest in keeping it alive in any way.

**Comment by Haldrie** [comment]
Is it possible to at least modify it to still download the metadata and subtitles even without video streams?

**Comment by tamodolo** [comment]
> Is it possible to at least modify it to still download the metadata and subtitles even without video streams?

I opened an issue on anidl and the devs liked the idea of expose the api json to the user (but not available yet). This will allow to create scripts for it easier. Go take a look.

**Comment by hama3254** [comment]
> Is it possible to at least modify it to still download the metadata and subtitles even without video streams?

@Haldrie you can still download subtitles for now, but there is no guarantee that it will work in the future.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/8a8a067a-d078-4ec2-91be-4bf0b6c9c828)

**Comment by Haldrie** [comment]
> > Is it possible to at least modify it to still download the metadata and subtitles even without video streams?
> 
> @Haldrie you can still download subtitles for now, but there is no guarantee that it will work in the future. ![grafik](https://private-user-images.githubusercontent.com/52826614/316271803-8a8a067a-d078-4ec2-91be-4bf0b6c9c828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDI2MjAsIm5iZiI6MTcxMTI0MjMyMCwicGF0aCI6Ii81MjgyNjYxNC8zMTYyNzE4MDMtOGE4YTA2N2EtZDA3OC00ZWMyLTkxYmUtNGJmMGI2YzljODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAxMDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Yjc4MmQ4YzQ1YmVlODEzMjc4YTk3NTk5ZWVhM2Q2ZDYxZTAxNjE0NmEyOWUwMTcyMGNlZjZjM2RlMDBjMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vRgQO72y5jsL-DoYsxYU5guGKWvKSjfAfK-5t33ZvhQ)

Oh I'm still using the command line version. What would be the command to get past the "No video formats found!" error message? I tried --skip-download but I still get that error even though it seems it's seeing the subtitles.

**Comment by GringoTM** [comment]
StreamFab for exaple inside convert the ASS format to TTS and lost all the formattation like colors and position, but can download video and different audio by decripting the stream.
Problem are the DRM, in much country Bypass Them are not legal.
AnyDVD and FabDVD have bypass the problem by moving his society in neutral country, but for normal people this is the END of Developing of Tools.
Sony are a BIG COMPANY and like NINTENDO are aggressive, and this is the only solution, stop the developping and stop to buy Cruncyroll Subscription.

**Comment by joseant0910** [comment]
Dmn! :( I just needed to download one last episode of Frieren and the program suddenly crashed:(

If CR Downloader comes back to life again, It would be amazing. Anyway, thanks Hama for your hard work these years.
![aaaa](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/164775840/ee9f1b5b-26ae-4792-9e2b-b45229c033c9)

**Comment by jalari06** [comment]
NOOOOOOOO!!!!!!! Wow, this is sooo depressing. I only recently discovered this downloader. That is a real shame. FRAKING CR! Damned crooks. First they take away my whole Funimation digital library, and now this!

**Comment by AnAppleInABox** [comment]
Thank you for all the hard work you put in. Truly a legend worth remembering.

**Comment by MinionAttack** [comment]
Thank you for your work all this time!

**Comment by kaleb112494** [comment]
Thank you for your many years of effort. It's sad to see this project go, but I understand your position. Cheers!

**Comment by Borufanss** [comment]
Ya que llego a su fin podrías con intetar crear uno para Netflix como lo fue con CR Downloader y gracias por tus años de esfuerzo!!!

**Comment by GHCripto** [comment]
Gracias por todo tu trabajo en estos años, fue una herramienta increíble

**Comment by gamer191** [comment]
@hama3254 I don't expect you to fix this, since you said you're very busy. Just in case though, here's a fix: https://github.com/yt-dlp/yt-dlp/issues/9453#issuecomment-2033587499

**Comment by hama3254** [comment]
@gamer191 that is definitely interesting I take a look at it.
I also find it funny that it is from the switch API while Nintendo is hard for there IP.

**Comment by hama3254** [comment]
I am still at work (psshh) but I think we can work with that.
But the `[Auto]` resolution will not work anymore.
![IMG_20240403_141327](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/86b5f60b-47ed-4cb4-8862-e6d506fc8f3a)

**Comment by hama3254** [comment]
> Did it work for you?

It kind of worked, I get some strange 403 errors with the new API (both the switch and the edge version) so they did something since last time I checked that.


> Is there a reason why one might choose auto instead of 1080p?

Some people wanted it and it was not hard to do so I just added it back then.

**Comment by hama3254** [comment]
@Anonymous327 I am looking into it but this takes time since the whole API is different with other requirements.
Also CR can change it any time, the request for example worked with the `web/edge/play` version but now it returns `403` as error/status the same as the switch API.
I don't know why yet, I will see.

**Comment by gamer191** [comment]
@hama3254 are you getting a 403 on the API request, or on the manifest?
Are you passing a bearer token? Have you tried generating another token? How are you generating the tokens? I tried using `curl -X POST -H "Authorization: Basic Y3Jfd2ViOg==" -d "grant_type=client_id&scope=offline_access" "https://www.crunchyroll.com/auth/v1/token" -H "User-Agent: literallyAnythingExceptTheDefaultUserAgent"`, and it generated an invalid token which then gave me a 403 on the API request

**Comment by bytedream** [comment]
For anonymous login you need to add the `ETP-Anonymous-ID` header (https://github.com/bytedream/yt-dlp/blob/bf2a0476551ef4599b826e1bab50e0b0de68a28f/yt_dlp/extractor/crunchyroll.py#L89-L90). This header represents a device id but any non-empty value works. I just went with a random UUID.

**Comment by Jaynator495** [comment]
> @gamer191 and @bytedream thanks for your insight.
> I abuse the WebView2 to get some data like [Basic](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/04bb552ec6dcd73a779bf9ca976de585ccdf812c/Crunchyroll%20Downloader/Browser.vb#L278) token.
> And i just see that i also got the `Bearer` token there back in the beta website days before they used the DRM stream.
> This gives me some ideas i have to test after work.
> 
> 
> 

It's also worth noting, that the new API doesn't use media_guid, it instead uses guid

**Comment by Anonymous327** [comment]
Wow. It's fixed?!

**Comment by gamer191** [comment]
Should this issue be renamed?

**Comment by DaVinci1987** [comment]
Apparently I'm not smart enough to get the 3.20 to work.
I'm getting an error message attached down below and need some advice

![Screenshot 2024-04-05 130016](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/44339471/2550a196-9d8d-4db0-bad1-53a9758af4ca)

**Comment by DaVinci1987** [comment]
Yes I've tried both Hybrid Mode versions without success

**Comment by joseant0910** [comment]
> Yes I've tried both Hybrid Mode versions without success

Make sure you're logged in or try re installing the software. It worked to me earlier!

**Comment by Anonymous327** [comment]
Yeah. It's still working just fine for me. What exact settings are you using? @DaVinci1987

**Comment by jalari06** [comment]
> I am still at work (psshh) but I think we can work with that. But the `[Auto]` resolution will not work anymore. ![IMG_20240403_141327](https://private-user-images.githubusercontent.com/52826614/319177775-86b5f60b-47ed-4cb4-8862-e6d506fc8f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMTY3OTUsIm5iZiI6MTcxMjMxNjQ5NSwicGF0aCI6Ii81MjgyNjYxNC8zMTkxNzc3NzUtODZiNWY2MGItNDdlZC00Y2I0LTg4NjItZTZkNTA2ZmM4ZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDExMjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZjQzYmYzNTU2YmY1NjllMWEzMTMwMjQwN2NlZTc4MDk5YTM3MGUwODdhMDRiYjlhMWUyM2FlMzQ0M2EzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRty0z0On6cxmjt-TGCgnicHWruAQUFoEFkR0j5uSwA)

I don't want top put this in the official fix thread for the new version but THANK YOU!!!! I am so happy you decided to take a look at the fix! You are gods to me! While I am tech savy to some degree, I just don't have the time to figure out the API and all that, so thank you for fixing this!

I can finally get the remaining of Frieren! I know I can always get it via "other means", but I like to control how its made and what subs/dubs it has for my own use. I will eventually get the blu-rays for anything I want anyway, but until they dubbed and released to the US, or I can secure the Japanese blu-rays, this is my next best option without being forced to need an active connection to watch every time. Its my main reason for having a CR sub aside from the discounts in their store. Again, thanks!!!

**Comment by DaVinci1987** [comment]
Now I feel stupid... to log in did the trick

**Comment by Anonymous327** [comment]
Yeah...you have to be logged in, with or without a sub, to use the downloader.

**Comment by Nightcore974** [comment]
Nice job you did there. So just to be sure, the quality of the video and subs will remain the same? It won't change because of the switch API?

**Comment by Jaynator495** [comment]
> Thanks @hama3254 and @bytedream for merging fixes into your Crunchyroll downloading projects🎉
> 
> It's so awesome to see multiple projects using my Crunchyroll workaround❤️

Don't forget mine

**Comment by gamer191** [comment]
> Nice job you did there. So just to be sure, the quality of the video and subs will remain the same? It won't change because of the switch API?

I don’t think anyone can know for sure, although you can test it by seeing what quality the video downloads at, and seeing the maximum quality of the video on the website. It should download at the same quality that it plays at on Nintendo Switch devices, which could potentially be a lower quality



> Don't forget mine

@Jaynator495 may I ask what project? I can’t seem to find it?

**Comment by Jaynator495** [comment]
> @Jaynator495 may I ask what project? I can’t seem to find it?

multi-downloader-nx

**Comment by hama3254** [comment]
i think we are done here (for now).

**Comment by skillz4me5** [comment]
Since its legal to download the streams unencrypted and let us find our own keys will you be willing to update for that?

**Comment by tamodolo** [comment]
> Since its legal to download the streams unencrypted and let us find our own keys will you be willing to update for that?

Another tool do that. It was already mentioned here.

**Comment by jesuspkane** [comment]
how to make Crunchyroll-Downloader-v3.0-3.99.0 work in Crunchyroll-Downloader-v3.24.0 because I don't finish clarifying how to do it 
Thanks a lot

**Comment by diosyue02** [comment]
Tengo el streamfab  trabajando  con  cruncryroll   perfecta mente  el que lo quiera  para  agregar  un aporte y disifrar    como son los en laces ahi lo  comparto

**Comment by diosyue02** [comment]
TENGO EL PROGRAMA DE STREAMFAB   FUNCIONANDO   CON CRUNCHYROLL SIN  ERRORES    QUIEN LO QUIERA  MANDEME UN MENSAJE  O UN WHATSSAP   3221627379   AI LES PONGO EN ENLACE DE DESGARGA  PARA QUE SAQUEN LA INFO DE COMO DESCARGAR

**Comment by dreezy-official** [comment]
here is a possible alternative to download from crunchyroll **L3 Widevine keys**. https://github.com/OpenSTDL/CrunchyDL
and https://github.com/OpenSTDL/CrunchyDL/discussions/23

**Comment by x3inspire** [comment]
> here is a possible alternative to download from crunchyroll **L3 Widevine keys**. https://github.com/OpenSTDL/CrunchyDL and [OpenSTDL/CrunchyDL#23](https://github.com/OpenSTDL/CrunchyDL/discussions/23)

Where to get Widevine L3 key?

**Comment by smile-2023** [comment]
> > here is a possible alternative to download from crunchyroll **L3 Widevine keys**. https://github.com/OpenSTDL/CrunchyDL and [OpenSTDL/CrunchyDL#23](https://github.com/OpenSTDL/CrunchyDL/discussions/23)
> 
> Where to get Widevine L3 key?

[/cryptonek/widevine-l3-decryptor](https://github.com/cryptonek/widevine-l3-decryptor)

**Comment by dreezy-official** [comment]
> > here is a possible alternative to download from crunchyroll **L3 Widevine keys**. https://github.com/OpenSTDL/CrunchyDL and [OpenSTDL/CrunchyDL#23](https://github.com/OpenSTDL/CrunchyDL/discussions/23)
> 
> Where to get Widevine L3 key?

https://github.com/OpenSTDL/CrunchyDL/discussions/23
