### ISSUE TITLE
Add Multi Audio downloading option

### ISSUE THREAD

**Issue by 2204852** [hama3254/Crunchyroll-Downloader-v3.0#919]
We want to download Multi Audio so please add Multi Audio downloading option

**Comment by hama3254** [comment]
Does the Downloader work for you?
with Issue #911 it should not and in #918 i announced the **end** of the project since there is nothing i can do.

**Comment by 2204852** [comment]
No downloader is not working for me either you have to fix the it

**Comment by hama3254** [comment]
> i announced the **end** of the project since there is nothing i can do.
