### ISSUE TITLE
Can't start the application

### ISSUE THREAD

**Issue by pstrings** [hama3254/Crunchyroll-Downloader-v3.0#92]
I downloaded the 3.5.7 version and after extracting it tried to start Crunchyroll Downloader.exe but got error message instead.

![image](https://user-images.githubusercontent.com/29589412/100002715-f458f580-2dea-11eb-837d-8bff9f84da77.png)

**Comment by hama3254** [comment]
something like this are usual due to missing librarys.
Please get the x86 version from the `Visual C++ redistributable` which you can find here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by pstrings** [comment]
Thanks!

**Comment by hama3254** [comment]
i guess it worked so i close this.
