### ISSUE TITLE
Switch API

### ISSUE THREAD

**Issue by Aiyomi-Irirako** [hama3254/Crunchyroll-Downloader-v3.0#925]
Hi,

Erstmal vielen Dank für all die Jahre die du uns mit Updates und Co beschert hast.

DRM ist ja schon länger ein Thema und fing ja dchon letztes Jahr im normalen Web API an.
Kurze Zeit später fand man die Android API, die, wie jeder weiß,  ebenfalls ein DRM Upgrade bekommen hat.
Es schien als wäre das das Ende von Non-DRM Stuff allerdings scheint die Switch API noch mit Non-DRM zu laufen.

Wäre es möglich sich das nochmal anzuschauen? 

Ich danke dir aber schonmal, auch wenn es nicht klappen sollte.

LG

**Comment by hama3254** [comment]
Ich hab's schon Mal angeschaut, bekomme aber Probleme mit dem authentifizieren.
Mal schauen ob sich das lösen lässt und auch wie lange das dann wieder hält.
Was ich schon sagen kann, es ist die selbe Datei wie bei anderen APIs aber der token scheint zu entscheiden ob DRM oder kein DRM was etwas ekelhaft ist zu erkennen.

**Comment by hama3254** [comment]
ich lock das hier mal, neue version und neuer thread sind raus.
