### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fedeangeles** [hama3254/Crunchyroll-Downloader-v3.0#93]
Windows 10

![Screenshot_1](https://user-images.githubusercontent.com/71239003/100633307-b25d1180-330c-11eb-95c2-a70c4f106e2b.png)

**Comment by hama3254** [comment]
You need the x86 version from the visual c++ redistributable 2019
[which you can download here:](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

![grafik](https://user-images.githubusercontent.com/52826614/93120687-03714800-f6c4-11ea-9109-2538679ad19a.png)
