### ISSUE TITLE
Download only audio track or 240p download add pls

### ISSUE THREAD

**Issue by Ashwinking11** [hama3254/Crunchyroll-Downloader-v3.0#930]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hama3254** [comment]
Crunchyroll does not offer a separate audio stream. this mean we can only download the full video and disregard the video.
This is already in the downloader see #701.
I set the quality to 480p for that since if we go lower the audio quantity goes worse.

**Comment by Ashwinking11** [comment]
240p just add audio quality low ok add pls just feature request

**Comment by fabrebatalla18** [comment]
> Crunchyroll does not offer a separate audio stream. this mean we can only download the full video and disregard the video. This is already in the downloader see #701. I set the quality to 480p for that since if we go lower the audio quantity goes worse.

You already can:

just delete "-v1" from segments urls.

**Comment by ToHOSEru** [comment]
I receive now this message

![2024-04-19](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/163932081/9d4976e7-842b-4ad8-adea-c42b52c8bbaf)

**Comment by fabrebatalla18** [comment]
> > Crunchyroll does not offer a separate audio stream. this mean we can only download the full video and disregard the video. This is already in the downloader see #701. I set the quality to 480p for that since if we go lower the audio quantity goes worse.
> 
> You already can:
> 
> just delete "-v1" from segments urls.
> 
> example:
> 
> only audio stream: -a1
> 
> only video stream: -v1
> 
> both: -v1-a1

@hama3254 do you tried my trick?

**Comment by acteiaa** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/163225023/b1c1d7d9-c440-4e22-b6b0-bfb616064e61)

**Comment by Teknikator** [comment]
> ![image](https://private-user-images.githubusercontent.com/163225023/324166092-b1c1d7d9-c440-4e22-b6b0-bfb616064e61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Mjk1NzQsIm5iZiI6MTcxMzYyOTI3NCwicGF0aCI6Ii8xNjMyMjUwMjMvMzI0MTY2MDkyLWIxYzFkN2Q5LWM0NDAtNGUyMi1iNmIwLWJmYjYxNjA2NGU2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxNjA3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjA4YzI1MTVmY2UyMzA5NTBiMmY5YTdjOGEwMWRkM2ViNmI5ZjI5ZDQ3ZTk0YWZjMTZmY2E5ODdhZTFmNmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LDAIM4dBYkh9Ec_c0CwH66lKRljYygucTpCRDFZ189w)

Same I also had this problem since yesterday.
On Thursday I downloaded without Problems Videos with the version 3.20.1
![Bild_2024-04-20_181057659](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/99121057/61fc5bad-ce29-4417-9d7a-09571a3a367b)

**Comment by hama3254** [comment]
> > > Crunchyroll does not offer a separate audio stream. this mean we can only download the full video and disregard the video. This is already in the downloader see #701. I set the quality to 480p for that since if we go lower the audio quantity goes worse.
> > 
> > 
> > You already can:
> > just delete "-v1" from segments urls.
> > example:
> > only audio stream: -a1
> > only video stream: -v1
> > both: -v1-a1
> 
> @hama3254 do you tried my trick?

That is interesting and i seems to work but i don't have the time to properly add this for now
