### ISSUE TITLE
Downloading not starting and crashed.

### ISSUE THREAD

**Issue by Primelikes01** [hama3254/Crunchyroll-Downloader-v3.0#931]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/158451701/efa88dcb-d3ab-4db5-b284-5c70d4095d1e)

**Comment by Primelikes01** [comment]
I tried many times to download video & audio, but I couldn't; I was only able to download subtitles. It always crashes. Please check the problem 😐

**Comment by hama3254** [comment]
> Please check the problem 😐

i could try if you give me any kind of usefull information.
i just added the v3.20.1 that includes fix for a known issue from #926 

>> Did some more investigating as well. ffmpeg mode and hardsubs won't work. 
>> ffmpeg works fine, but _only_ when I have MKV, copy/srt, and softsubs enabled though. Did not work with MP4.
>
>that issue was just a view lines that changed the `ffmpeg` command.
without merged subs it made it like that.
>
>`05.04.2024 07:29:55 -user_agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0" -headers "ACCEPT-ENCODING: *" -protocol_whitelist file,http,https,tcp,tls,crypto,data -allowed_extensions ALL -i "C:\Crunchyroll-Downloader-v3.20\CRD-Temp-File-xqo8mmdsaqp1hhoj.m3u8" -metadata:s:a:0 language=eng -c copy -c:a copy -bsf:a aac_adtstoasc "C:\Documents\RWBY Season 2 Episode 4.5.mp4"`
>
>`05.04.2024 07:29:55 Option user_agent not found.`
>
>just to not find the option since it's using a local copy not a `http` request where it could use the headers.
>
_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/926#issuecomment-2040173034_

please check your version and update if you are not on v3.20.1.

if you are on v3.20.1 or an update does not fix your issue than please provide the ffmpeg log.
[The wiki entry how to option the ffmpeg log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/FFMPEG-Logfile)

**Comment by IchYoIo** [comment]
Hi hama3254 I have download crashed only with some episodes, I'll attach all info.
![Clip_8](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/d12a608a-ddca-4296-a99f-050ce4cc2d11)
![Clip_9](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/9374ec93-81d1-41ee-9dca-cbc2b3e8ac53)
![Clip_10](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/05822864-b9b1-4a02-813e-daaabac83e70)

**Comment by IchYoIo** [comment]
My config on 3.20.1 version
I have had some other episodes with the same crash, but in general, the App Works perfect as usual!!!

Thanks, Thanks and thanks again for your work.

![Clip_2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/62b97b75-2fce-4318-a2b1-201ec46e0aa1)
![Clip_3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/73045b16-c268-4b1e-b347-26cf3d1f74ec)
![Clip_4](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/73072490-0d4f-4e92-9aef-3371b9c466d2)
![Clip_5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/da92c046-61a2-491d-bada-6ba0bf858850)
![Clip_6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166774426/bfce6532-9d01-4400-bc23-7d3def480d0a)

**Comment by IchYoIo** [comment]
If you need I can post all the links of all episodes with the same crash..,.

**Comment by IchYoIo** [comment]
12/04/24 20:33:24: CR fix failed to access unlisted file #882
12/04/24 20:33:11 -allowed_extensions ALL -i "E:\Crunchiroll\Crunchyroll-Downloader-v3.20.1\CRD-Temp-File-ivvw0e7d1y0vog7o.m3u8" -metadata:s:a:0 language=jpn -c copy -c:a copy -bsf:a aac_adtstoasc

12/04/24 20:33:25 -allowed_extensions ALL -i "L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\index.m3u8" -metadata:s:a:0 language=jpn -c copy -c:a copy -bsf:a aac_adtstoasc "L:\0-NEW\The Witch and the Beast S1 E11.mp4"
12/04/24 20:33:25 ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
12/04/24 20:33:25   built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
12/04/24 20:33:25   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
12/04/24 20:33:25   libavutil      57. 28.100 / 57. 28.100
12/04/24 20:33:25   libavcodec     59. 37.100 / 59. 37.100
12/04/24 20:33:25   libavformat    59. 27.100 / 59. 27.100
12/04/24 20:33:25   libavdevice    59.  7.100 / 59.  7.100
12/04/24 20:33:25   libavfilter     8. 44.100 /  8. 44.100
12/04/24 20:33:25   libswscale      6.  7.100 /  6.  7.100
12/04/24 20:33:25   libswresample   4.  7.100 /  4.  7.100
12/04/24 20:33:25   libpostproc    56.  6.100 / 56.  6.100
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Skip ('#EXT-X-VERSION:5')
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Opening 'L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\CRD-Temp-File-HJHbbbfHZRgGYRYC.key' for reading
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Unable to open key file L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\CRD-Temp-File-HJHbbbfHZRgGYRYC.key
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Opening 'crypto:L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00000.ts' for reading
12/04/24 20:33:25 [crypto @ 00000000006f2980] Unable to open resource: L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00000.ts
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Failed to open segment 1 of playlist 0
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Opening 'crypto:L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00001.ts' for reading
12/04/24 20:33:25 [crypto @ 00000000006f2980] Unable to open resource: L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00001.ts
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Failed to open segment 2 of playlist 0
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Opening 'crypto:L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00002.ts' for reading
12/04/24 20:33:25 [crypto @ 00000000006f2980] Unable to open resource: L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00002.ts


3 to 361

12/04/24 20:33:25 [hls @ 00000000006c8dc0] Failed to open segment 362 of playlist 0
12/04/24 20:33:25 [hls @ 00000000006c8dc0] Error when loading first segment 'L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\00000.ts'
12/04/24 20:33:25 L:\0-NEW\CRD-Temp-File-VQMaUZdUfGMQODcX\index.m3u8: Invalid data found when processing input
12/04/24 20:33:25 
12/04/24 20:33:25
