### ISSUE TITLE
Multi Audio Download

### ISSUE THREAD

**Issue by ManuelDiazIsaza** [hama3254/Crunchyroll-Downloader-v3.0#932]
**Is your feature request related to a problem? Please describe.**
Ey hama can you please add download multi audio option for episodes, maybe can download like .aac with the same that the subtitle.
For example: One Piece Season 14 Episode 1100.English.aac

**Describe the solution you'd like**
When you download some episodes download multiple audios for that episodes

**Describe alternatives you've considered**
When i want a serie with multiples audios, first i download the video and after download diferents audios one by one, i want download all and do some scripting and merge to mkv

**Additional context**

**Comment by hama3254** [comment]
The closest we get to this is #701 where you also see what issues will arrive.
