### ISSUE TITLE
Hardsub in Dub video

### ISSUE THREAD

**Issue by Raphael1512** [hama3254/Crunchyroll-Downloader-v3.0#933]
Hi, is it possible to add the functionality to imprint subtitles in dubbed videos? (the language in question is Italian)
For example, episode title or signs, etc.
The softsubs work perfectly while the hardsubs do not print them.

**Comment by hama3254** [comment]
We got the setting for hardsubs.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/bfff9bc5-d151-4a9f-8cb4-c86c085657ee)

this will tell the downloader to use the stream tagged as hardsub in the language you selected.
What this files contains comes from CR.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/142574d7-4fae-4e8a-8e55-05b0f4d2e22b)

**Comment by Raphael1512** [comment]
It's very strange... I checked the settings and they are correct, I tried to download an episode in Italian but the forced subtitles are not printed on the video.  I can't understand why

**Comment by hama3254** [comment]
> EDIT: I noticed that it doesn't work with all anime, in some it makes me hardsub easily, while in others it doesn't print.. for example my hero academy season 6 it can't print.

with the way this works the downloader only check the tag of the stream so if the hardsubs are not there then CR did not include it.
Did you check if the text is included in the softsubs for that dubbed episode?

**Comment by Raphael1512** [comment]
Yes, I checked, and the text is always downloaded in softsub

**Comment by hama3254** [comment]
If the same settings give different results than this is on CR.

But i can offer a workaround.

If you select the softsub and set it as the default subtilte while using `mkv` and `copy` this will add the subtitle text file into the video file and just give you One `.mkv` file that almost all modern player can use.

For bonus points i would recomment the `Hybrid Mode` and the `ScaledBorderAndShadow:yes` option to fix some issues (#764 and #871)

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/298025e9-c6ac-4d4e-bbc1-afe037f197af)

**Comment by Raphael1512** [comment]
If it's a CR problem, then I'll do as you said, thank you very much🙏
