### ISSUE TITLE
System exception getting curl 22

### ISSUE THREAD

**Issue by d8ity** [hama3254/Crunchyroll-Downloader-v3.0#934]
This bug pops up after I click download, it sayings loading for a second then the error box shows up. Ive tried using previous version ive also tried restarting and even updating my windows. It keeps showing this error, ive tried other anime url's aswell but no luck came, idk how to fix this.

I tried to use crunchyroll one piece, I dont have an account but that shouldnt matter since I can access it right?
I have no hardsubs no soft subs and I just use the default ffmpeg options but I still tried hybrid and that has same issue aswell. 
Ive tried v3.20.1 and v3,20

![crunchy roll error](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166762084/5042ac42-d712-4baf-8af7-882866296eea)

**Comment by hama3254** [comment]
>`401` would mean `unauthorized` which may because the anonymous request is not added yet (https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/918#issuecomment-2036908991) try to login into any type of account (free or premium).

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/926#issuecomment-2046510832_
