### ISSUE TITLE
Just to be clear about the DRM changes

### ISSUE THREAD

**Issue by SaintXye** [hama3254/Crunchyroll-Downloader-v3.0#935]
Does this mean Crunchyroll-Downloader is done?

**Comment by SaintXye** [comment]
Was trying to download something and kept getting "Failed getting master.m3u8" and the page said 3.0 was deprecated so I thought the project was done. Thanks for answering the question though unfortunately at least for me it doesn't seem to be working atm

**Comment by hama3254** [comment]
i don't see any problem, if you give me a screenshot of the error than i can take a loot at it.
You can also check that you use the latest version and you need to be logged in for the downloader to work (even for free episodes, but a free account is enough for that)

**Comment by SaintXye** [comment]
Updating to latest version did the trick!

Thanks for the application and helping with the issue.
