### ISSUE TITLE
Is the a possibility to make a viki.com tool?

### ISSUE THREAD

**Issue by ijorel** [hama3254/Crunchyroll-Downloader-v3.0#936]
Hello,

First i want ot thank you so much for your work , you are a true hero for this contribution.

I want to ask is there any possibility on make a similar tool for site viki.com? (rakuten viki)

much aprecciate and thanks again.

Best regards

**Comment by hama3254** [comment]
Not possible for me.
The content is protected with DRM.
![Screenshot_2024-04-17-06-55-25-67_3aea4af51f236e4932235fdada7d1643](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/aaa8867d-708d-4b50-aab4-1a5fac5e5a70)
