### ISSUE TITLE
Failed to download Crunchyroll episode

### ISSUE THREAD

**Issue by KeronCyst** [hama3254/Crunchyroll-Downloader-v3.0#937]
**Describe the bug**
Repeatedly tried to download at default settings: https://www.crunchyroll.com/watch/G4VUQMQ55/am-i-getting-ahead-of-myself

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: Default
 - Version: 3.20.1

**Screenshots**
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/13827055/f904c13e-8588-4ae2-9001-ec5a5f7e655b)

**Comment by hama3254** [comment]
>`401` would mean `unauthorized` which may because the anonymous request is not added yet (https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/918#issuecomment-2036908991) try to login into any type of account (free or premium).

_Originally posted by @hama3254 in https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/926#issuecomment-2046510832_
