### ISSUE TITLE
ERROR 403

### ISSUE THREAD

**Issue by JOXX3** [hama3254/Crunchyroll-Downloader-v3.0#938]
Hello.  Today I tried to download some episodes of One Piece, but I get error #403.  I already tried the new version and registered my account in the downloader and even used the hybrid version, but I have not been successful in downloading.  Until yesterday the downloads worked, but not today.  I attach the message:

Error Obtención de curva (22) La URL solicitada, error devuelto: 403

En crunchyroll downloader. Obtener datos. CurlAuthNoticias (Streing Url String Cookies, String Auth, Boolean Testi in C-Projecte Crunchyroll Downloader v3.0-final Crunchyroll-Downloader-v3.0- CefSharp Crunchyroll Descargar GetData.vb línea 197 en Crunchyroll Downloader Main GetCRVideo (String Streams, String AuthToken, String WebsiteURL, Int32 RI Count en CAProjecte Crunchyroll Downloader- v3.0-final Crunchyroll-Downloader-3.0-CefSharp Crunchrayll Downloader.Mamb-Mamb- 1907

**Comment by ZolXick** [comment]
I also have that problem, I already updated to v3.21 since before I had v3.20.1 but I still have the problem with error 403
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/167433166/bec657d1-54dd-4358-a252-22128888460a)

**Comment by jalari06** [comment]
Sigh, I knew it was too good to last. I'll bet they nerfed things again to prevent us again. FING CR!!! I hope it can be fixed, but its probably an uphill battle as any time we find a fix or a way around it, they will just change something again. Just so depressing!

**Comment by SquadCraftFTW** [comment]
Same issue here.

**Comment by sahtanoj** [comment]
Unfortunately this problem reoccurred. I hope it can be easily bypassed by @hama3254 . ^^

**Comment by TaMaGo-TTV** [comment]
Yeah same, not even Subs are Downloading Big F

**Comment by hama3254** [comment]
The API endpoint does not seem to work at all.
We used `/console/switch/play` which now returns http code `403` with the data `{"error":"Invalid client id"}`.

The default respone should be `{"error":"Unsupported device type"}` with 403 if the request is nonsene.

Other option still work but are all DRM protected (all that i found with trial and error).

web enpoints

`/web/firefox/play` 
`/web/edge/play`
`/web/safari/play`
`/web/chrome/play`
`/web/fallback/play`

console enpoints 

`/console/switch/play` 
`/console/ps4/play` 
`/console/ps5/play`
`/console/xbox_one/play`  

also the apple stuff 

`/ios/iphone/play`
`/ios/ipad/play`


older versions *might* be able to still get the subtitles

**Comment by TaMaGo-TTV** [comment]
> The API endpoint does not seem to work at all. We used `/console/switch/play` which now returns http code `403` with the data `{"error":"Invalid client id"}`.
> 
> The default respone should be `{"error":"Unsupported device type"}` with 403 if the request is nonsene.
> 
> Other option still work but are all DRM protected (all that i found with trial and error).
> 
> web enpoints
> 
> `/web/firefox/play` `/web/edge/play` `/web/safari/play` `/web/chrome/play` `/web/fallback/play`
> 
> console enpoints
> 
> `/console/switch/play` `/console/ps4/play` `/console/ps5/play` `/console/xbox_one/play`
> 
> also the apple stuff
> 
> `/ios/iphone/play` `/ios/ipad/play`
> 
> older versions _might_ be able to still get the subtitles

Alles klar dann versuche ich mich da mal durch, hab zwar noch Streamlabs aber dort bekommt man nur SRT Files womit ich absolut nichts anfangen kann.

**Comment by pratyushpati11** [comment]
Crunchy added additional security to the endpoint for non-DRM streams

**Comment by pratyushpati11** [comment]
But it's still non DRM.

**Comment by AsIFall** [comment]
So, I will patiently for a fixed version of CR Downloader as I have no clue to solve those problems at all.

**Comment by BlastedMarble** [comment]
Going back to a previous version of the downloader doesn't fix things at all, unfortunately. Just pointing it out in case people were gonna try that.

**Comment by bytedream** [comment]
@hama3254 the switch endpoint updated its behavior, the most interesting for you is probably that the `etp_rt` cookie login method doesn't work anymore (well it works, but not for the switch endpoint)

**Comment by Ashwinking11** [comment]
> The API endpoint does not seem to work at all. We used `/console/switch/play` which now returns http code `403` with the data `{"error":"Invalid client id"}`.
> 
> The default respone should be `{"error":"Unsupported device type"}` with 403 if the request is nonsene.
> 
> Other option still work but are all DRM protected (all that i found with trial and error).
> 
> web enpoints
> 
> `/web/firefox/play` `/web/edge/play` `/web/safari/play` `/web/chrome/play` `/web/fallback/play`
> 
> console enpoints
> 
> `/console/switch/play` `/console/ps4/play` `/console/ps5/play` `/console/xbox_one/play`
> 
> also the apple stuff
> 
> `/ios/iphone/play` `/ios/ipad/play`
> 
> older versions _might_ be able to still get the subtitles

I don't understand pls fix and upload

**Comment by Ashwinking11** [comment]
P0

> @hama3254 the switch endpoint updated its behavior, the most interesting for you is probably that the `etp_rt` cookie login method doesn't work anymore (well it works, but not for the switch endpoint)

Any other option to download

**Comment by AsIFall** [comment]
> > The API endpoint does not seem to work at all. We used `/console/switch/play` which now returns http code `403` with the data `{"error":"Invalid client id"}`.
> > The default respone should be `{"error":"Unsupported device type"}` with 403 if the request is nonsene.
> > Other option still work but are all DRM protected (all that i found with trial and error).
> > web enpoints
> > `/web/firefox/play` `/web/edge/play` `/web/safari/play` `/web/chrome/play` `/web/fallback/play`
> > console enpoints
> > `/console/switch/play` `/console/ps4/play` `/console/ps5/play` `/console/xbox_one/play`
> > also the apple stuff
> > `/ios/iphone/play` `/ios/ipad/play`
> > older versions _might_ be able to still get the subtitles
> 
> Alles klar dann versuche ich mich da mal durch, hab zwar noch Streamlabs aber dort bekommt man nur SRT Files womit ich absolut nichts anfangen kann.
> 
> Edit: Ja, die 3.19 Sub only Version funktioniert

Fragen: Ich habe jetzt vermehrt darüber gelesen, dass man mit SRT-Dateien (ich glaube, das sind die Untertitel) nicht viel anfangen kann. Was genau ist das Problem mit diesen Dateien?
Ich benutze neben den CR Downloader auch eine Software namens Avidemux, um die heruntergeladenen Files zu kodieren und zu komprimieren. Mit dem Programm kann man auch Untertitel einfügen, wenn das Video keine Untertitel hat.
Wie viel kostet Streamlabs? Ich möchte mir (für den Fall der Fälle) eine Alternative besorgen, sollte der Crunchyroll Downloader in der Zukunft nicht mehr nutzbar sein.

**Comment by pratyushpati11** [comment]
Seems anidl has fixed their service.

**Comment by AsIFall** [comment]
> Seems anidl has fixed their service.

Which means?

**Comment by Aiyomi-Irirako** [comment]
> > > The API endpoint does not seem to work at all. We used `/console/switch/play` which now returns http code `403` with the data `{"error":"Invalid client id"}`.
> > > The default respone should be `{"error":"Unsupported device type"}` with 403 if the request is nonsene.
> > > Other option still work but are all DRM protected (all that i found with trial and error).
> > > web enpoints
> > > `/web/firefox/play` `/web/edge/play` `/web/safari/play` `/web/chrome/play` `/web/fallback/play`
> > > console enpoints
> > > `/console/switch/play` `/console/ps4/play` `/console/ps5/play` `/console/xbox_one/play`
> > > also the apple stuff
> > > `/ios/iphone/play` `/ios/ipad/play`
> > > older versions _might_ be able to still get the subtitles
> > 
> > 
> > Alles klar dann versuche ich mich da mal durch, hab zwar noch Streamlabs aber dort bekommt man nur SRT Files womit ich absolut nichts anfangen kann.
> > Edit: Ja, die 3.19 Sub only Version funktioniert
> 
> Fragen: Ich habe jetzt vermehrt darüber gelesen, dass man mit SRT-Dateien (ich glaube, das sind die Untertitel) nicht viel anfangen kann. Was genau ist das Problem mit diesen Dateien? Ich benutze neben den CR Downloader auch eine Software namens Avidemux, um die heruntergeladenen Files zu kodieren und zu komprimieren. Mit dem Programm kann man auch Untertitel einfügen, wenn das Video keine Untertitel hat. Wie viel kostet Streamlabs? Ich möchte mir (für den Fall der Fälle) eine Alternative besorgen, sollte der Crunchyroll Downloader in der Zukunft nicht mehr nutzbar sein.

Du siehst,doch wir hübsch die untertitel von cr sind. Srt kann das einfach nicht deswegen ist das Format auch scheiße

**Comment by dok1100** [comment]
> > Seems anidl has fixed their service.
> 
> Which means?

Das heist das bei anidl der download funktioniert, genauso wie bei crunchy-cli von bytedream. Gib hama2354 etwas Zeit die Info von bytedream umzusetzen.
Um noch schnell zu den 2 anderen Sachen zu kommen.
Bei den srt Untertiteln gibt es keine Schriftarten, keine bewegten Texte und noch einiges mehr. Ich würde ass immer bevorzugen wenn es um Crunchy geht.
Die zweite Sache mit Streamlabs, zahl niemals Geld für sowas. Es gibt einige tools die das umsonst können. 
Und ich bin bytedream, hama2354, AnimeDL und noch weitere, sehr dankbar das sie ihre Freizeit opfern und uns solche tools zur verfügung stellen.

English
This means that the download works with anidl, just like with crunchy-cli from bytedream. Give hama2354 some time to implement the information from bytedream.
To quickly get to the other two things.
With srt subtitles there are no fonts, no moving texts and much more. I would always prefer ass when it comes to crunchy.
The second thing with Streamlabs, never pay money for something like that. There are some tools that can do this for free.
And I am very grateful to bytedream, hama2354, AnimeDL and others for sacrificing their free time and making such tools available to us.

**Comment by AsIFall** [comment]
> > > Seems anidl has fixed their service.
> > 
> > 
> > Which means?
> 
> Das heißt das bei anidl der download funktioniert, genauso wie bei crunchy-cli von bytedream. Gib hama3254 etwas Zeit die Info von bytedream umzusetzen. Um noch schnell zu den 2 anderen Sachen zu kommen. Bei den srt Untertiteln gibt es keine Schriftarten, keine bewegten Texte und noch einiges mehr. Ich würde ass immer bevorzugen wenn es um Crunchy geht. Die zweite Sache mit Streamlabs, zahl niemals Geld für sowas. Es gibt einige tools die das umsonst können. Und ich bin bytedream, hama2354, AnimeDL und noch weitere, sehr dankbar das sie ihre Freizeit opfern und uns solche tools zur verfügung stellen.
> 
> English This means that the download works with anidl, just like with crunchy-cli from bytedream. Give hama3254 some time to implement the information from bytedream. To quickly get to the other two things. With srt subtitles there are no fonts, no moving texts and much more. I would always prefer ass when it comes to crunchy. The second thing with Streamlabs, never pay money for something like that. There are some tools that can do this for free. And I am very grateful to bytedream, hama2354, AnimeDL and others for making the tools in their free time and making them available to us.

Danke für die Informationen bezüglich SRT.
Ja, ich warte auch ganz brav und geduldig. :-)
Natürlich bin ich hama und co. sehr dankbar für ihre Arbeit und Zeit, die sie für uns investieren, damit wir ihre Software nutzen können.

**Comment by hama3254** [comment]
@bytedream many thanks it works nice.

for everyone else i see that i add this without hardcoding my own login data into the downloader, i dont have any UI/process for login details because until now i just used the cookies from the browser.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/09d85ee3-2895-4220-b906-2415c4804747)

**Comment by gamer191** [comment]
> web enpoints
> 
> `/web/firefox/play` `/web/edge/play` `/web/safari/play` `/web/chrome/play` `/web/fallback/play`
> 
> console enpoints
> 
> `/console/switch/play` `/console/ps4/play` `/console/ps5/play` `/console/xbox_one/play`
> 
> also the apple stuff
> 
> `/ios/iphone/play` `/ios/ipad/play`

Sorry, I forgot to include the endpoints I’d tested in my original message about the Switch endpoint. Here’s some more endpoints (all are DRM protected, last time I checked):
```
/android/phone/play
/android/tablet/play
/ios/vision/play (Apple Vision Pro)
/tv/samsung/play
/tv/lg/play
```

**Comment by sahtanoj** [comment]
> @bytedreammuito obrigado, funciona bem.
> 
> para todos os outros, vejo que adiciono isso sem codificar meus próprios dados de login no downloader, não tenho nenhuma UI/processo para detalhes de login porque até agora eu apenas usei os cookies do navegador. ![gráfico](https://private-user-images.githubusercontent.com/52826614/324183420-09d85ee3-2895-4220-b906-2415c4804747.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzYyOTQsIm5iZiI6MTcxMzYzNTk5NCwicGF0aCI6Ii81MjgyNjYxNC8zMjQxODM0MjAtMDlkODVlZTMtMjg5NS00MjIwLWI5MDYtMjQxNWM0ODA0NzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE3NTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2OThiZTU5ODcyMGRkODFiMzY3MmNkZDc4NzdlNmZiNGU4OGQ2OTU4Zjg2MmI3MmIyN2ZjY2VlMzEzYmFlZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0F0qGJPFh4PFM2-rAgeaxK0snGYZNtQvpdxnJ8dylxE)

I'm glad you managed to find a solution. Now we just have to wait for the functional update. ^^

**Comment by jalari06** [comment]
> @bytedream many thanks it works nice.
> 
> for everyone else i see that i add this without hardcoding my own login data into the downloader, i dont have any UI/process for login details because until now i just used the cookies from the browser. ![grafik](https://private-user-images.githubusercontent.com/52826614/324183420-09d85ee3-2895-4220-b906-2415c4804747.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDI3NTYsIm5iZiI6MTcxMzY0MjQ1NiwicGF0aCI6Ii81MjgyNjYxNC8zMjQxODM0MjAtMDlkODVlZTMtMjg5NS00MjIwLWI5MDYtMjQxNWM0ODA0NzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE5NDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YmE0M2RkNzgwMTVjY2RlOTAyMGZhZmNhN2Q2MmI4ODdjYjA2NjllODEyOTQzMTE4MWFiNmY1ODNmZjFkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1TBa83hICF-Ve4WAocYwZFwTTphlwFLvUHnmdMqNbI)

Forgive me as I don't read german (at least I think those posts were in german), does this mean that there is a solution, you just need to code in a way for us to enter our actual login info instead of trying to pull the info from the cookies? I REALLY hope I am reading that right as since losing this program a second time, I've been very sad. I really hope this will solve it once and for all. Thanks!

**Comment by Serpentstar** [comment]
I am clearly not a coder, but I bet if he added an edit point into the configuration file (or created a cred file) and had us all manually enter our own credentials, it could resolve the base issue without him having to hard code his own login into the application.  He has done some damned fine work already.

**Comment by hama3254** [comment]
[v3.22 is live](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.22) and all issue with it should be added to #941

**Comment by segurafifa2006** [comment]
v3.22 already fails
system exception error

**Comment by jalari06** [comment]
> v3.22 already fails system exception error gettingad main 4494 Error Obtención de curva (22) La URL solicitada, error devuelto: 401

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/39065678/13a553a7-dea3-43fe-9faa-ffb1c897127a)

Not sure what you mean as its working fine for me. May want to double check your user name and password you used.

**Comment by issamrehabi** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/37936713/4514b608-5443-4c64-bc7d-9214c3f2bae4)
help

**Comment by jalari06** [comment]
> ![image](https://private-user-images.githubusercontent.com/37936713/324790899-4514b608-5443-4c64-bc7d-9214c3f2bae4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Njc1NDEsIm5iZiI6MTcxMzg2NzI0MSwicGF0aCI6Ii8zNzkzNjcxMy8zMjQ3OTA4OTktNDUxNGI2MDgtNTQ0My00YzY0LWJjN2QtOTIxNGMzZjJiYWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEwMTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZThmYzczZTE3OGRkOGVjZWJlNDdmMWIzMWYwYTcxMDIyMmZjNjdjYmQ0Njg2MDk3YmY2MzE5YmJhNWY4OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SkxUNeXPrOrx54VKza1ukAAStZV5eTQn1a435C3XWgU) help

Exactly what it says, you need to your your Crunchyroll login info directly now because of the API changes.

**Comment by issamrehabi** [comment]
merci beaucoup

**Comment by teogaming201** [comment]
> @hama3254 the switch endpoint updated its behavior, the most interesting for you is probably that the `etp_rt` cookie login method doesn't work anymore (well it works, but not for the switch endpoint). As far as I can tell any token that is generated by the browser cannot be used for the switch endpoint (anymore). The 403 response has "invalid_client" as part of its error message. This probably refers to the `client_id` field in the jwt/token payload which is `cr_backend` or `cr_web` if generated with the browser. The only method left to generate a valid token is an api request to the token endpoint with a switch specific `Authorization` header.
> 
> _These are the requests that will produce a working token_:
> 
> Gain jwt/access token (and refresh token that is requred to re-request the access token after it's expired) with email and password:
> 
> ```
> POST https://www.crunchyroll.com/auth/v1/token
> Authorization: Basic dC1rZGdwMmg4YzNqdWI4Zm4wZnE6eWZMRGZNZnJZdktYaDRKWFMxTEVJMmNDcXUxdjVXYW4=
> Content-Type: application/x-www-form-urlencoded
> 
> username=<email>&password=<password>&grant_type=password&scope=offline_access
> ```
> 
> Request new jwt/access token with a refresh token:
> 
> ```
> POST https://www.crunchyroll.com/auth/v1/token
> Authorization: Basic dC1rZGdwMmg4YzNqdWI4Zm4wZnE6eWZMRGZNZnJZdktYaDRKWFMxTEVJMmNDcXUxdjVXYW4=
> Content-Type: application/x-www-form-urlencoded
> 
> refresh_token=<refresh token>&grant_type=refresh_token&scope=offline_access
> ```

still don't get it, you need to screenshot to let me know how do this?

**Comment by santamnata** [comment]
use this method : open [crunchyroll](https://apkskart.com/crunchyroll-mod-apk/) and reset your account to test
