### ISSUE TITLE
Error 403 pls update 

### ISSUE THREAD

**Issue by Ashwinking11** [hama3254/Crunchyroll-Downloader-v3.0#939]
**Describe the bug**

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll, Funimation]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.8.7.2]

**Screenshots**

**Additional context**

**Comment by hama3254** [comment]
see #938
