### ISSUE TITLE
Simultaneous download more than 2 when only audio download

### ISSUE THREAD

**Issue by ManuelDiazIsaza** [hama3254/Crunchyroll-Downloader-v3.0#942]
**Is your feature request related to a problem? Please describe.**
Like tittle say, when you download only audio, please allow to download max 12 audios at time

**Comment by hama3254** [comment]
I don't remember to have a limit there.
The only limit should be the video encoder, change it to `-c copy` should unlock it.

**Comment by ManuelDiazIsaza** [comment]
@hama3254 maybe you can add in simultaneos download another box only for audio download?

Is for not always moving that -c copy because that reset the configurations for video download, its posible?

**Comment by ManuelDiazIsaza** [comment]
Something like this in the configs
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/37357573/4be9b177-cb54-4e58-9c11-83d3f8e77748)

And when you select AUDIO ONLY AAC use the valor in AUDIO

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/37357573/908c0903-1bf6-4c00-8a3e-78bb89ab9c9e)

**Comment by ManuelDiazIsaza** [comment]
This help a lot when you need download diferents audios for series

**Comment by hama3254** [comment]
> And when you select AUDIO ONLY AAC use the valor in AUDIO

It's not that simple, there would be huge changes to make this work and I simply don't have the time for that right now.
