### ISSUE TITLE
Subtitles not downloading with version 3.22.2

### ISSUE THREAD

**Issue by HiroHaro** [hama3254/Crunchyroll-Downloader-v3.0#943]
Hello, When I try to download the French subtitle only of a French language anime on crunchyroll , it shows me that it is downloading, but it is not created, when i try with the subtitles of the Japanese language version, I have no problem and it download correctly.

Edit: I try with the subtitle english and i have the same problem as french 
Default mode downloads video and audio, but not subtitle in non-Japanese versions

**Comment by HiroHaro** [comment]
I saw that on crunchyroll there was no subtitle, I'm so stupid not to have checked before!

**Comment by hama3254** [comment]
without any further info i assume this was fixed by having subtitles
