### ISSUE TITLE
V3.23 - EpisodeName not shown on download / file

### ISSUE THREAD

**Issue by progithub2** [hama3254/Crunchyroll-Downloader-v3.0#944]
Episode-Title not shown on download / file

 - Platform: Crunchyroll
 - Version [3.23]

V3.23
![test](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166246771/4c660a34-6421-4482-b10d-803528b1d9c3)

V3.22
![test2](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166246771/5e1ff73d-28ec-401d-8a5b-f08025e9d5ac)

same settings

any ideas? ^^

**Comment by hama3254** [comment]
>Episode-Title not shown on download / file
>same settings
>
>any ideas? ^^


That part of the code was not even changed so i guess the API data of CR is at fault here?
It works for me and i got a different Thumbnail as you for the same episode.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/955b1b00-ac96-47f9-a5c5-354bc57cf6f3)

**Comment by progithub2** [comment]
hattest du den Link für die Episode direkt oder für die komplette Serie genommen?

serie: https://www.crunchyroll.com/de/series/G0XHWM1Q0/gods-games-we-play (ohne Titel)

Episode: https://www.crunchyroll.com/de/watch/GN7UD11GN/world-games-tour (mit Titel)


![test3](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166246771/bac19e4c-9052-4b1b-ad87-c35b1e2ed0c4)

**Comment by hama3254** [comment]
Ich hab den fehler gefunden, passiert scheinbar (nur?) bei deutschen Dub.

Die datei mit dem Namen wurde nicht richtig aufgerufen.

`https://www.crunchyroll.com/content/v2/cms/objects/GJWU20032?preferred_audio_language=ja-JP&locale=`

anstelle von 

`https://www.crunchyroll.com/content/v2/cms/objects/GJWU20032?preferred_audio_language=ja-JP&locale=de-DE`

damit kommt bei CR wirklich müll raus, es fehlt einfach alles was an die `locale` angepasst wird. 
Bei der Japanischen Dub version kommt dann einfach englisch raus (was hier nicht auffällt weil der titel eigentlich englisch ist)

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/f6612def-f01e-45b0-832f-705d1eae4926)
