### ISSUE TITLE
Downloading Dubbed Anime not possible

### ISSUE THREAD

**Issue by AsIFall** [hama3254/Crunchyroll-Downloader-v3.0#945]
Hi hama,
it seems that there is a problem when I try to download dubbed anime. I wanted to download the German language dub for Unnamed Memory which seemed to have started yesterday. I tried changing the language from Japanese to German (but it still downloaded the the Japanese version). After changing back to Japanese, I tried using the bulk download where I was able to change language to German but then an error message opened saying: "no available options found".
I made some screenshots to visualize the issue.
![001](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110290203/a91f5dc1-77f2-4720-af4c-5e0cd442b826)
![002](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110290203/feeddf42-0b56-41fa-961c-803c2aa7313f)
![003](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110290203/cfec5738-9c70-4f42-9789-e65cd82d5e71)
![004](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110290203/686d437a-b391-4e87-8d2e-0d9dee49aca2)
![005](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/110290203/2fb207ee-a9c1-4f6d-876b-ca89821f3c9a)

I use CR Downloader v. 3.22
Hope anyone can help.
Kindest regards!

**Comment by Elwador** [comment]
if you go into the first episode and change the language to german and take the new url you should be able to download the episode - that is the ID of the german episode "GZ7UVGD3E"

**Comment by AsIFall** [comment]
> workaround: if you go into the first episode on crunchyroll and change the language to german and take the new url you should be able to download the episode - that is the ID of the german episode "GZ7UVGD3E"

I tried as you said but the error message still shows up.

**Comment by Elwador** [comment]
have you tried it with v3.23 with the german episode url it worked fine - the batch download didn't work either but i didn't get an error

**Comment by AsIFall** [comment]
> have you tried it with v3.23 with the german episode url it worked fine - the batch download didn't work either but i didn't get an error

There is another issue with v3.23 which is why I don't have tried yet. See #946

**Comment by hama3254** [comment]
> with v3.23 with the german episode url it worked fine - the batch download didn't work either but i didn't get an error

I take a look at this later

> I use CR Downloader v. 3.22

> There is another issue with v3.23 which is why I don't have tried yet.

Please update to the latest version, for debugging I can only use the latest code so errors from older version (if not the same) are hard to find.

**Comment by hama3254** [comment]
this may be related to #944 since the cause was an inproper handeling of the empty `locale` value.
my tests with the current code (avalible as [v3.23.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.1) worked fine)

**Comment by hama3254** [comment]
> I downloaded and tried v3.23.1 but the error remains on my side. Maybe, I am just to stupid to find the correct settings.

I just checked with the release build and fresh settings, it seems that the error handling causes the isse.
if you set the settings to skip the hardsub it should work
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/c06d7f1b-de25-417b-b171-557946abbf1c)

**Comment by AsIFall** [comment]
Okay, this works even with v3.22.
