### ISSUE TITLE
fatal! Failed to download 'encryption.key'

### ISSUE THREAD

**Issue by rbfmamah** [hama3254/Crunchyroll-Downloader-v3.0#946]
Describe the bug
After updating to v3.23, when I attempt to download any title, an error labeled "fatal! Failed to download 'encryption.key'" appears.

Where does the issue occur?
 - Platform: Crunchyroll
 - Settings: Hardsubs: null, Softsubs: en and es-la subs, ffmpeg options: -c copy -c:a copy -bsf:a aac_adtstoasc, download mode: hybrid mode - keep cache]
 - Version v3.23
 - Microsoft Edge WebView2 Runtime version: 124.0.247867

![Screenshot (138)](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/168682115/072a2317-0fe3-4eb5-bb62-32fd4942be99)

Additional context
I attempted to run as an admin, but the issue persisted.
I attempted to relocate the downloader to both the desktop and "C:/" (previous versions were hosted in "C:/Crumchyroll-Downloader"), but it had no effect on the outcome.
The Windows version remains unchanged, furthermore, the antivirus services are disabled.
Additionally, I attempted to delete the downloader (along with all its settings) and extract from a new compressed folder to ensure it is not the culprit of the issue.

Log:

01/05/2024 18:23:04: C:\TEMP\Date-A-Live-Season-2-Episode-1-Daily-Life\CRD-Temp-File-aHHEdDGfMCVBSVag.key - https://fy.v.vrv.co/evs3/23e49d329261456d8d0e40990ca5decc/assets/60dddee70aef6877c28bce310c706579_3438333.mp4/encryption.key?t=exp=1714620200~acl=/evs3/23e49d329261456d8d0e40990ca5decc/assets/60dddee70aef6877c28bce310c706579_3438333.mp4/*~hmac=ca8b4c9691d98b2aa7c136d99fd550c868fdf8d0ae2b5a343c6c954e4125b0bc
01/05/2024 18:23:04: C:\TEMP\Date-A-Live-Season-2-Episode-1-Daily-Life\\CRD-Temp-File-aHHEdDGfMCVBSVag.key - https://fy.v.vrv.co/evs3/23e49d329261456d8d0e40990ca5decc/assets/60dddee70aef6877c28bce310c706579_3438333.mp4/encryption.key?t=exp=1714620200~acl=/evs3/23e49d329261456d8d0e40990ca5decc/assets/60dddee70aef6877c28bce310c706579_3438333.mp4/*~hmac=ca8b4c9691d98b2aa7c136d99fd550c868fdf8d0ae2b5a343c6c954e4125b0bc
01/05/2024 18:23:04: C:\TEMP\Date-A-Live-Season-2-Episode-1-Daily-Life\00000.ts - https://fy.v.vrv.co/evs3/23e49d329261456d8d0e40990ca5decc/assets/60dddee70aef6877c28bce310c706579_3438333.mp4/seg-1-v1-a1.ts?t=exp=1714620200~acl=/evs3/23e49d329261456d8d0e40990ca5decc/assets/60dddee70aef6877c28bce310c706579_3438333.mp4/*~hmac=ca8b4c9691d98b2aa7c136d99fd550c868fdf8d0ae2b5a343c6c954e4125b0bc
01/05/2024 18:23:04 -allowed_extensions ALL -i "C:\Crunchyroll-Downloader\CRD-Temp-File-gfw1fboegb0mg08m.m3u8" -metadata:s:a:0 language=jpn -c copy -c:a copy -bsf:a aac_adtstoasc

**Comment by rbfmamah** [comment]
Any ideas? Any help is welcome, and thank you very much in advance :)

**Comment by AsIFall** [comment]
Go back to v3.22 (that version still works fine).

**Comment by rbfmamah** [comment]
"Okay, I'll give it a try and let you know what happens. Thank you very much :)"

**Comment by rbfmamah** [comment]
"it worked for me, thank you very much :)"

**Comment by AsIFall** [comment]
> "it worked for me, thank you very much :)"

You're welcome. :-)
Neithertheless, this issue should be kept open.

**Comment by hama3254** [comment]
I have take a look later but I see you use 

>hybrid mode - keep cache

Did you try without `keep cache`?

**Comment by rbfmamah** [comment]
now it works, thanks so much :)

**Comment by hama3254** [comment]
@rbfmamah just on case you still want to keep the cache [v3.23.1](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.1) should work fine now.
