### ISSUE TITLE
Stretched and different subtitle types

### ISSUE THREAD

**Issue by ITlerOhneKnowledge** [hama3254/Crunchyroll-Downloader-v3.0#951]
When the output is set to MKV, the subtitle is different and "streched" from the "normal" or rather desired subtitle style that is displayed when outputting as MP4.
For reference, please use the attached images

**Settings:**
Format: _MP4 / mov_text_
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/169167952/628717be-7f70-4af0-9c40-576bd73eb435)

Format: _MKV / copy_
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/169167952/2184b6d8-7aa4-4e44-b032-ff36e3029026)

Format: _MKV / srt_
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/169167952/4361bb20-5da8-41c9-9f7e-5fdaca72dde3)

It would be perfect if the "MP4 style" could also be applied to the MKV outputs.

**Comment by hama3254** [comment]
`ScaledBorderAndShadow:yes` from #764 might help you here.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/cbf01f07-4b51-451e-9a1d-cb43f230046e)

**Comment by ITlerOhneKnowledge** [comment]
Thanks for the quick reply. It does indeed look similar to the MP4 subtitles. However, the subtitles are no longer combined into the MKV, which leads to subtitle files (but its understandable by "merge diabled")
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/169167952/b134d8c2-6b22-4985-a4bc-0a095adf1112)

**Comment by PlayTics** [comment]
I have found a working solution by following the steps mentioned here: https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/871#issuecomment-1879675344

> You can enable `ScaledBorderAndShadow:yes` with MKV on `copy `if the `Hybrid Mode` is enable at the top.

It does look very different in English or German Subtitle
(Both used the same settings)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/82596249/31256db6-212d-4a51-98ca-e1c27558f2a0)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/82596249/6490fb19-bc44-40e2-aa9f-06d11a228edd)

**Comment by hama3254** [comment]
> Thanks for the quick reply. It does indeed look similar to the MP4 subtitles. However, the subtitles are no longer combined into the MKV, which leads to subtitle files (but its understandable by "merge diabled")

Depeding on the settings i can not intercept the subtitle file from CR, i tryed my best to explain it here https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/764#issuecomment-1595774856


> It does look very different in English or German Subtitle
> (Both used the same settings)

I never understood why some settings are not player side, this is one example.
Those settings are inside the `ass` file and can differ for German and Englisch, i don't think the downloader is supposed to deal with that.
