### ISSUE TITLE
Default subtitle option does not work

### ISSUE THREAD

**Issue by josedu2a** [hama3254/Crunchyroll-Downloader-v3.0#955]
**Describe the bug**
in version 3.23.2 the default subtitle option does not work. 
I did some tests downloading with different configurations and the default subtitle option does not work.

**Where does the issue happen?**
 - Platform:  Crunchyroll
 - Settings: Crunchyroll > Default Subtitle option
 - Version  v3.23.2

**Comment by hmm-star** [comment]
hi...i have one question. can it download the premium content from crunchyroll too ? and also is it still working ?

**Comment by hama3254** [comment]
@hmm-star please stay in your issues or make new ones for other problems, this helps me to keep track about the status more easily.

To answer your question, the latest version works fine but requires login details to get the required tokens.
You can download all content the account is able to access this means a free account works fine for free anime but a premium account is required for premium episodes.

**Comment by hama3254** [comment]
> I did some tests downloading with different configurations and the default subtitle option does not work.

I am unable to reproduce the issue, `mkv` with `copy` and at least one softsubs selected allows to set the default subtile.

the `ffmpeg` command also looks totaly fine.

`-allowed_extensions ALL -i "CRD-Temp-File-7ytrhebnxw8gn0yt.m3u8" -i "subs.txt" -map 0:v -map 0:a -map 1 -c copy -c:a copy -bsf:a aac_adtstoasc -c:s copy -metadata:s:s:0 language=ger -metadata:s:s:0 title="Deutsch" -metadata:s:s:0 handler_name="Deutsch" -disposition:s:0 default -metadata:s:a:0 language=eng`
