### ISSUE TITLE
Softsubs also get downloaded in Hardsub mode

### ISSUE THREAD

**Issue by 21R01A7263** [hama3254/Crunchyroll-Downloader-v3.0#957]
While trying to download Hardsub stream of an episode, the corresponding soft subs also get downloaded and the result looks like this

![Screenshot 2024-05-20 082338](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/128503039/4a7fe920-38eb-4f3e-87a4-441e9570a240)

Is it a bug in the program or did i setup in the wrong way?

![Screenshot 2024-05-20 091538](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/128503039/6ce37d3f-7e0f-42a5-9509-814de5120306)

![Screenshot 2024-05-20 091607](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/128503039/5122c232-4598-4da0-b790-16a13f91f697)

**Comment by hama3254** [comment]
> Is it a bug in the program or did i setup in the wrong way?

There is no check in place since like you did both works fine for the downloader.
You can just deselect all subtitles in the Softsubs menu and it should be fine.

**Comment by 21R01A7263** [comment]
> You can just deselect all subtitles in the Softsubs menu

 I will be doing that, but isn't it a little ironic that i get Softsubs in my face too when i particulary selected Hardsub

**Comment by hama3254** [comment]
> but isn't it a little ironic that i get Softsubs in my face too when i particulary selected Hardsub

You have at least english selected as softsub since you need to get it under `Default Subtitle`.

Hard and softsubs don't exclude themself since hardsubs change the video input and softsubs are there own text file.

**Comment by 21R01A7263** [comment]
Makes sense. I will be closing this now ✌
