### ISSUE TITLE
MyProvider.dll is not found in the codebase coz it's getting gitignored

### ISSUE THREAD

**Issue by F04C** [hama3254/Crunchyroll-Downloader-v3.0#958]
`Error	BC30002	Type 'MyProvider.MyProvider.DirectorySettingsProvider' is not defined` Got this and saw that  `<Reference Include="MyProvider">
      <HintPath>..\..\..\MyProvider\MyProvider\bin\x64\Debug\MyProvider.dll</HintPath>
    </Reference>` is in your bin. However you gitignored the bin together with the said dll. Also this error `Error	BC30002	Type 'DirectorySettings' is not defined` is due to the MyProvider getting gitignored.

    
`<Global.System.Configuration.SettingsProvider(GetType(MyProvider.MyProvider.DirectorySettingsProvider))>`

**Comment by hama3254** [comment]
You can find the `MyProvider.dll` within the Release builds inside the `lib` folder.
The projects links to another local projects, the original source code can be found in this [german forum post from 10 years ago](https://www.vb-paradise.de/index.php/Thread/101710-UserSettingsProvider-Persistieren-von-UserSettings/?pageNo=1&s=21f5b5753290312d4aa7fe7e470f638c5fe2e4aa)

**Comment by F04C** [comment]
I mean on the source code, it's not included. I have to transfer the `MyProvider.dll` from the release to the project folder after you said that it was on the release build. 


Further, the `MetroFramework.MetroCheckBoxSize.SomethingInBetween` is not used by `MetroFramework 1.2.0.3`. Instead it now uses `MetroFramework.MetroCheckBoxSize.(Small/Medium/Large)`

**Comment by hama3254** [comment]
> Further, the `MetroFramework.MetroCheckBoxSize.SomethingInBetween` is not used by `MetroFramework 1.2.0.3`. Instead it now uses `MetroFramework.MetroCheckBoxSize.(Small/Medium/Large)`

I was not happy with the limited option `MetroFramework` so the version in the downloader has some small modifications.
This is one of them, another is the add-on port combo box where we have both a textbook and the combo box behavior.


> I mean on the source code, it's not included.

The source is it's own local project, I just never made a public repository for it.
I linked the original source with the first release to use it and then never touched it again.

**Comment by F04C** [comment]
can't PR anything to this project since I changed everything with regards to metroframework and also the location of the myprovider.dll 😢 if you could update the latest source code(the debug and not the release one), it would be helpful for other developers in solving issues by submitting PRs

**Comment by hama3254** [comment]
I added the libarys to the repository and changed the linking for the project to them.

**Comment by F04C** [comment]
Thank you for updating
