### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by TaMaGo-TTV** [hama3254/Crunchyroll-Downloader-v3.0#959]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/61699515/5606ff8b-a0c7-4d99-b111-eac23ee32741)
Am i the only one?

**Comment by jwhitfield10** [comment]
I am having the same issue as you. Just installed the latest version and got this error. Went back to 3.23.1 and the same thing is happening for me.

**Comment by TaMaGo-TTV** [comment]
> Same for me, Crunchy probably changed something

Big F 

we get more information tomorow, I guess. Its 1am in germany.

**Comment by napgiver** [comment]
Same here.

**Comment by kuriidev** [comment]
![Captura de pantalla 2024-05-21 170821](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/162527923/26286620-732b-48b1-9c50-69a43b282cf2)

**Comment by Flame-Rider** [comment]
Glad to see that i am not the only one with this problem i hope it is fixed soon

**Comment by Daigh** [comment]
Same problem to me :(

**Comment by hama3254** [comment]
It seems like they changes the API again.
I am not sure righ now if (or what) i can do about it.
It also may take some days for me to take a proper look at this.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/5504176f-7245-4b7e-be4c-33c394e3f874)

**Comment by stratuma** [comment]
@hama3254 just add 'User-Agent': 'Crunchyroll/1.8.0 Nintendo Switch/12.3.12.0 UE4/4.27' to the playlist fetch

**Comment by drunknmonkie** [comment]
@Elwador thank you

**Comment by acteiaa** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/163225023/3b735ae1-18c9-426e-b106-495114d2fdd2)
I downloaded 6 videos and it stopped working

**Comment by ZioBomba** [comment]
I think there is still some problem, I tried to download a 50-episode series, but after the first 5-6 episodes it gives me error, every now and then it downloads one and many it skips with the error 420
https://i.imgur.com/apZaNMz.png

**Comment by acteiaa** [comment]
Unlike the other version, this one you have to wait a while for it to work again, you can't download several episodes ç.ç

**Comment by stratuma** [comment]
It looks like a token error, maybe refresh the user token more often

**Comment by acteiaa** [comment]
The limit is 5 every 5 minutes

**Comment by acteiaa** [comment]
To get it working again, you need to close the app and open it again.

**Comment by stratuma** [comment]
@hama3254 could you please add more logging so we can see the crunchyroll response not only the error code.

**Comment by stratuma** [comment]
because since the new api update the switch endpoint also has a active stream limit.
After you fetch the mpd you have to invalidate the video token:

JS example:
`const response = await fetch(`https://cr-play-service.prd.crunchyrollsvc.com/v1/token/${contentid}/${videotoken}/inactive`, {
        method: 'PATCH'
    })
`

**Comment by stratuma** [comment]
> It looks like a token error, maybe refresh the user token more often

At this point its wrong, the error should be the activestream limit

**Comment by hama3254** [comment]
> @hama3254 could you please add more logging so we can see the crunchyroll response not only the error code.

Last time I tried that I was unable to change the `curl` command to do so.

> because since the new api update the switch endpoint also has a active stream limit. After you fetch the mpd you have to invalidate the video token:
> 
> JS example: `const response = await fetch('https://cr-play-service.prd.crunchyrollsvc.com/v1/token/${contentid}/${videotoken}/inactive', { method: 'PATCH' }) `

I see, I add this after I get home from work.
This should be a simple fix.

**Comment by CarrilloTlx** [comment]
Hello everyone!

I want to share my Crunchyroll project, which is designed to download anime episodes. Currently, I've encountered a JSON Web Token (JWT) authentication issue. It seems that there are difficulties in authenticating access to the Crunchyroll API, preventing the download process from functioning correctly.

This project is programmed in C#.

If anyone has experience with these types of issues or is interested in contributing, it would be great to have your help in resolving this problem!

Here's the link to the project repository: [Crunchyroll Project Repository](https://github.com/CarrilloTlx/Crunchyroll)

Any contributions or suggestions would be greatly appreciated! Thank you!
![01](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/124406352/2319daf4-ef7d-416e-8ca1-360d5b10dcef)
![02](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/124406352/3f07e1be-e6ba-4c89-ad99-f77e131c55e9)

**Comment by hama3254** [comment]
@CarrilloTlx I removed the image since I am not sure about all the data that have been shown on it.
For security reasons I would recommend to check all data on a screenshot or log for any kind of authorization information. 

if you get the same JSON response you might need to use the suggested by @stratuma 

`User-Agen': Crunchyroll/1.8.0 Nintendo Switch/12.3.12.0 UE4/4.27`

>It seems like they changes the API again.
I am not sure righ now if (or what) i can do about it.
It also may take some days for me to take a proper look at this.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/5504176f-7245-4b7e-be4c-33c394e3f874)

**Comment by Elwador** [comment]
@CarrilloTlx i have also created a downloader in c# maybe you find a solution there

**Comment by cr-ytdlp** [comment]
this works also
```
await fetch('https://cr-play-service.prd.crunchyrollsvc.com/v1/token/${episodeId}/${videoStreamToken}', { method: 'DELETE' })
```

**Comment by hama3254** [comment]
[v3.23.4](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.4) is now online and should add the token deletion.


@stratuma i also changed the error output 
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/9c1a95fb-2e73-492d-acf9-3b6778bf458e)

**Comment by stratuma** [comment]
> this works also
> 
> ```
> await fetch('https://cr-play-service.prd.crunchyrollsvc.com/v1/token/${episodeId}/${videoStreamToken}', {method: 'DELETE'});
> ```
> 
> and you should see an error `TOO_MANY_ACTIVE_STREAMS` and at that point you can clear all active streams, if wanted e.g.
> 
> ```
> if (exception.error === 'TOO_MANY_ACTIVE_STREAMS' && exception.activeStreams?.length) {
>   for (const activeStream of exception.activeStreams) {
>     await fetch('https://cr-play-service.prd.crunchyrollsvc.com/v1/token/${activeStream.contentId}/${activeStream.token}', {method: 'DELETE'});
>   }
> }
> ```

The problem here if you delete all active streams it could happen that you delete a token you are using, that results a mpd fetch error.

**Comment by acteiaa** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/163225023/6a14dc8d-cb91-402f-bfe5-14c9bf65c7bb)
I was even scared by the size of the error

**Comment by acteiaa** [comment]
but it is working it was only one episode that this error appeared

**Comment by stratuma** [comment]
> ![image](https://private-user-images.githubusercontent.com/163225023/333463329-6a14dc8d-cb91-402f-bfe5-14c9bf65c7bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDQ3NzcsIm5iZiI6MTcxNjU0NDQ3NywicGF0aCI6Ii8xNjMyMjUwMjMvMzMzNDYzMzI5LTZhMTRkYzhkLWNiOTEtNDAyZi1iZmU1LTE0YzliZjY1YzdiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwOTU0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODk3MjAyNjg4MGEyNDgxNDM1Njk4YjRlM2RjMzMwNWIxNjI2MzFjZTFjNDY5ZGZmMTVmYTVjZWM5MGRhOWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rScCFVJ_j-Jc0cJ6w4A2cx8TAn7MHVKN3woFbbB9arg) I was even scared by the size of the error

Cloudflare error, interesting. Never got one over that endpoint

**Comment by hama3254** [comment]
>I was even scared by the size of the error 

i should probably rebuild something like the .net crash message.
having the error code at the top and the details with the text.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/e8ec7792-4154-44f9-8ce3-c4a8cb93c8b1)


>Cloudflare error, interesting. Never got one over that endpoint

This is at the objects request which is still a rebuild of what the webbrowser does.

**Comment by hama3254** [comment]
@Borufanss due to changes on CR side the login of the webbrowser does not work anymore.
We need to fake it as a Switch app login, the downloader does that but i need the login details for that.

**Comment by stratuma** [comment]
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166541445/8cd53b0b-2146-4274-95dc-66c8d2b15ed9)

Idk what crunchyroll changed but I have so many fetch fails since the new update, maybe they added a new ratelimit.
(Failed already after downloading the audio of the 3rd video added in download list)

**Comment by hama3254** [comment]
@stratuma where do you get that message from?
I see no problem fully downloading 8 episodes within 8 minutes.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/8db0106b-7b6f-40af-b223-1df74f8e0ee6)

**Comment by hama3254** [comment]
>No i'm speaking of the api not of your downloader, this is a error I get with my downloader.

that is why i asked where you get the error from, both of your projects are based on the same APIs thats why i was surprised since my downloader works fine.

**Comment by stratuma** [comment]
> > No i'm speaking of the api not of your downloader, this is a error I get with my downloader.
> 
> that is why i asked where you get the error from, both of your projects are based on the same APIs thats why i was surprised since my downloader works fine.

Do you check if every part gets downloaded correctly?

**Comment by hama3254** [comment]
> Do you check if every part gets downloaded correctly?

My files look fine but i also still use the `hls` stream.

**Comment by stratuma** [comment]
> > Do you check if every part gets downloaded correctly?
> 
> My files look fine but i also still use the `hls` stream.

Oh ok, I use the dash stream
