### ISSUE TITLE
Unable to download anime

### ISSUE THREAD

**Issue by drunknmonkie** [hama3254/Crunchyroll-Downloader-v3.0#960]
**Describe the bug**
Placing URL loads videos into the queue but when the queue is initialized an error happens.
<img width="712" alt="image" src="https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/129485202/6969f004-5185-4d52-b533-33f7a922fc0a">

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings: Default
 - Version: v3.23.2

**Additional context**
This was not an issue last week when I downloaded this series, thought maybe there was a problem with another series I was downloading so re-tried Goblin Slayer and the same issue happens.

Maybe something on the website Crunchyroll has changed?

**Comment by Elwador** [comment]
see - https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959 

fix will probably come later
