### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#961]
I was downloading as s series _That Time I Got Reincarnated as a Slime_ and was starting at season 1  After the 8th successful download, I received an index out out bounds error.

 - Platform: [e.g. Crunchyroll, ]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Add insecure, 480P, Add scaled border, Override dub w/ japanese, hardsub language, English, use captions, enable CR chapters
 - Version [e.g. v3.8.7.2]3.23.4

**Screenshots**
No screenshot, but exception text
[exception text.zip](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/15440782/exception.text.zip)

I had just downloaded this and copied my dat file from the previous version to the new one. when it suddenly just crashed.

**Comment by Serpentstar** [comment]
I was working on season 2 and then it threw this one.
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/751507/c349416d-eac8-4d67-b5e0-667649d610a6)
I did at tempt to highlight just the text, but it wouldn't let me.

**Comment by stratuma** [comment]
@hama3254 Instead of using that endpoint:
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/166541445/ea012b25-25d7-4a3d-8863-18f9c4e3846e)

Use this endpoint, it doesn't has cloudflare blocking/rate-limiting: https://beta-api.crunchyroll.com/auth/v1/token

**Comment by hama3254** [comment]
this looks like some random queue issue.
i am not able to reproduce it on my side.

**Comment by Serpentstar** [comment]
I agree with the randomness.  I think I have only had it occur once more after going to the 3.23.5 version.  Downloads do appear to be more stable after checking for token expiry, but I know I don't pull nearly as much as a lot of the other users.
