### ISSUE TITLE
No video, check CR login

### ISSUE THREAD

**Issue by dreezy-official** [hama3254/Crunchyroll-Downloader-v3.0#963]
**No video, check CR login**
When I try to download some content, for example https://www.crunchyroll.com/pt-pt/series/G24H1N3MP/mushoku-tensei-jobless-reincarnation episode 17 and 18 I get the error In the video, check CR login. Note: I checked and I was correctly logged into the premium account.

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Version [v3.23.4](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.4)

<details>
  <summary>Settings</summary>
  
![2024-05-25_15-39-49](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/7936300c-ed8f-4e1e-a0c5-3f9298917c26)
![2024-05-25_15-39-52](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/d99a7bd9-271a-4b16-98c3-953be16b78cc)
![2024-05-25_15-39-55](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/a28fb192-6087-48af-87e8-b46bb3905e68)
![2024-05-25_15-39-58](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/415b7ac6-d5fd-4ebd-96e6-d64a7f6c8fcc)

  </details>

<details>
  <summary>Screenshots of the issue</summary>
  
When I insert the link to get the episodes nothing happens.
![2024-05-25_15-41-34](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/cf7b55b9-e402-4b25-adca-8f897e5656ce)
But when it goes to the Queue part, it gives me the error:
![2024-05-25_15-41-48](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/1601da7a-bfdb-476d-9e44-7a8a6c7ec7d1)
![2024-05-25_15-41-56](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/c099ba01-0115-49e3-97c0-8891daa429ef)
![2024-05-25_15-42-00](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/c56173ad-8586-44a8-8cad-eae2cbd960f1)

  
</details>

**Note:**
Isn't it because there is now a new feature in cruchrollhy to skip profiles that could be causing this problem when searching for the download? I leave the note here because this was the only change that happened on the site and I even tried the old version that was functional and now it no longer works.

**Comment by hama3254** [comment]
The error message is kind of badly made from my side to really tell what going on.
It just checks that the data recived from CR contain the streams link.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/ddf7a81b-3864-4b40-aac5-c628a15c9f23)
This check is now technically not required anymore since that streamlink is now unused.
I have to overhall error messages in general like #961 to look more like (not exactly) like https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959#issuecomment-2129427325

**Comment by hama3254** [comment]
this is hard to debug, i updated the latest version with some improvments.
it also should allow to both ignore the check (if it fails) and it has a details button to get the raw data for the response.

**Comment by dreezy-official** [comment]
Platform: Crunchyroll
Version [v3.23.5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.5)
![2024-05-26_20-42-45](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/503624cc-9d3c-4981-9f0d-c9ff8813a26c)
![2024-05-26_20-42-57](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/2968f82f-b1af-44b9-8bfa-c8f42d4df139)
![2024-05-26_20-43-07](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/02912556-a9ab-4333-adc5-4f7344596f62)
**Here are the details so that you can carry out a more detailed analysis of the problem.**
{"total":1,"data":[{"promo_title":"","description":"Rudeus fica sabendo que sua irmã tornou-se uma reclusa, assim como ele era no passado. Agora ele quer fazer de tudo para que sua irmã não passe pelas mesmas coisas que ele.","slug_title":"my-older-brothers-feelings","id":"G50UZ0K2K","images":{"thumbnail":[[{"height":180,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":320},{"height":338,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/600x338/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":600},{"height":360,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/640x360/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":640},{"height":450,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/800x450/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":800},{"height":675,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1200},{"height":810,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1440x810/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1440},{"height":900,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1600x900/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1600},{"height":1080,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1920x1080/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1920}]]},"promo_description":"","title":"Os Sentimentos de um Irmão mais Velho","episode_metadata":{"ad_breaks":[{"offset_ms":0,"type":"preroll"},{"offset_ms":355011,"type":"midroll"},{"offset_ms":710022,"type":"midroll"},{"offset_ms":1065033,"type":"midroll"}],"audio_locale":"ja-JP","availability_ends":"9998-11-30T08:00:00Z","availability_notes":"","availability_starts":"9998-11-30T08:00:00Z","available_date":null,"available_offline":true,"closed_captions_available":false,"content_descriptors":["Nudity","Profanity","Sexual Violence","Smoking","Sexual Content","Violence"],"duration_ms":1420046,"eligible_region":"PT","episode":"17","episode_air_date":"2024-05-06T00:00:00+09:00","episode_number":17,"extended_maturity_rating":{"level":"M2","rating":"16","system":"cr-tv"},"free_available_date":"9998-11-30T08:00:00Z","identifier":"G24H1N3MP|S2|E17","is_clip":false,"is_dubbed":true,"is_mature":false,"is_premium_only":true,"is_subbed":true,"mature_blocked":false,"maturity_ratings":["TV-14"],"premium_available_date":"2024-05-05T15:30:00Z","premium_date":null,"season_display_number":"2","season_id":"G6NQCJ9P1","season_number":2,"season_sequence_number":2,"season_slug_title":"mushoku-tensei-jobless-reincarnation-season-2","season_title":"Mushoku Tensei: Jobless Reincarnation","sequence_number":17,"series_id":"G24H1N3MP","series_slug_title":"mushoku-tensei-jobless-reincarnation","series_title":"Mushoku Tensei: Jobless Reincarnation","subtitle_locales":["en-US","es-419","es-ES","fr-FR","pt-BR","ar-SA","it-IT","de-DE","ru-RU","th-TH","ms-MY","id-ID","vi-VN"],"upload_date":"2024-05-06T00:00:00+09:00","versions":[{"audio_locale":"ja-JP","guid":"G50UZ0K2K","is_premium_only":true,"media_guid":"G07FN2G3G","original":true,"season_guid":"G6NQCJ9P1","variant":""},{"audio_locale":"en-US","guid":"G8WUNJQWJ","is_premium_only":true,"media_guid":"GQ9FG5895","original":false,"season_guid":"GR75CDZJ8","variant":""},{"audio_locale":"pt-BR","guid":"G8WUNJK41","is_premium_only":true,"media_guid":"GQ9FG5XP3","original":false,"season_guid":"G6Q4CZ125","variant":""},{"audio_locale":"fr-FR","guid":"GD9UVM1J9","is_premium_only":true,"media_guid":"GWMF824WV","original":false,"season_guid":"G65VCD91K","variant":""},{"audio_locale":"de-DE","guid":"G50UZ089D","is_premium_only":true,"media_guid":"G07FN2V1X","original":false,"season_guid":"GYWEC3WQM","variant":""},{"audio_locale":"es-ES","guid":"G0DUN2V1Z","is_premium_only":true,"media_guid":"G9XFE0KQ4","original":false,"season_guid":"GYE5CQ2NW","variant":""},{"audio_locale":"es-419","guid":"GG1U2JKQX","is_premium_only":true,"media_guid":"G71F47GZ3","original":false,"season_guid":"GRDQCGJX3","variant":""},{"audio_locale":"it-IT","guid":"GEVUZ712V","is_premium_only":true,"media_guid":"GXMFQEVG8","original":false,"season_guid":"GR09CX1JN","variant":""}]},"external_id":"EPI.926574","slug":"","type":"episode","channel_id":"crunchyroll","linked_resource_key":"cms:/episodes/G50UZ0K2K"}],"meta":{}}

**Comment by hama3254** [comment]
The data you provided contain ad-break infomation and miss the streams url.
Both indictes to me that you don't have any premium on the account you used within the login form of the downloader.
If you are sure that the account used for this form is premium than you can try the `Ignore` button on the error form.
![Captura](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/116229346/10713753-9826-4520-a853-7bfd1e928b0f)

**Comment by dreezy-official** [comment]
> The data you provided contain ad-break infomation and miss the streams url. Both indictes to me that you don't have any premium on the account you used within the login form of the downloader. If you are sure that the account used for this form is premium than you can try the `Ignore` button on the error form. ![Captura](https://private-user-images.githubusercontent.com/116229346/333583704-10713753-9826-4520-a853-7bfd1e928b0f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMjI1MjIsIm5iZiI6MTcxNzAyMjIyMiwicGF0aCI6Ii8xMTYyMjkzNDYvMzMzNTgzNzA0LTEwNzEzNzUzLTk4MjYtNDUyMC1hODUzLTdiZmQxZTkyOGIwZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQyMjM3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTE0MGI5YzgxYzlkYjNjYTEwNzE2YmYzZTJmZTU4MGIxOTVlYzg2NDVlODc5YzM0YzU5MDcwZGU0NjA0NDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kdss1rIzxWO3L0M8cIb_dC-s-codPxtP4ihOsLemnhw)

**In your image I don't even see the option to log in, would it be possible to create an option in the cruchrollhy tab to log in manually when it doesn't appear?**

![2024-05-29_23-33-51](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/00c527f4-9c53-46e7-b085-5dc048e10ffd)
![2024-05-29_23-38-20](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/11a58422-16ce-490c-b1c5-df0b8a82ab31)
![2024-05-29_23-39-17](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/38385846-33eb-475a-ac81-484ce1396edd)
![2024-05-29_23-41-44](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/75680397/cf871d2d-7bd3-4604-a1a3-fb293a07e8d1)

Platform: Crunchyroll
Version [v3.23.7](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.7)

**Details:**
{"total":1,"data":[{"episode_metadata":{"ad_breaks":[{"offset_ms":0,"type":"preroll"},{"offset_ms":355011,"type":"midroll"},{"offset_ms":710022,"type":"midroll"},{"offset_ms":1065033,"type":"midroll"}],"audio_locale":"ja-JP","availability_ends":"9998-11-30T08:00:00Z","availability_notes":"","availability_starts":"9998-11-30T08:00:00Z","available_date":null,"available_offline":true,"closed_captions_available":false,"content_descriptors":["Nudity","Profanity","Sexual Violence","Smoking","Sexual Content","Violence"],"duration_ms":1420046,"eligible_region":"PT","episode":"17","episode_air_date":"2024-05-06T00:00:00+09:00","episode_number":17,"extended_maturity_rating":{"level":"M2","rating":"16","system":"cr-tv"},"free_available_date":"9998-11-30T08:00:00Z","identifier":"G24H1N3MP|S2|E17","is_clip":false,"is_dubbed":true,"is_mature":false,"is_premium_only":true,"is_subbed":true,"mature_blocked":false,"maturity_ratings":["TV-14"],"premium_available_date":"2024-05-05T15:30:00Z","premium_date":null,"season_display_number":"2","season_id":"G6NQCJ9P1","season_number":2,"season_sequence_number":2,"season_slug_title":"mushoku-tensei-jobless-reincarnation-season-2","season_title":"Mushoku Tensei: Jobless Reincarnation Season 2","sequence_number":17,"series_id":"G24H1N3MP","series_slug_title":"mushoku-tensei-jobless-reincarnation","series_title":"Mushoku Tensei: Jobless Reincarnation","subtitle_locales":["en-US","es-419","es-ES","fr-FR","pt-BR","ar-SA","it-IT","de-DE","ru-RU","th-TH","ms-MY","id-ID","vi-VN"],"tenant_categories":["Adventure","Drama","Fantasy"],"upload_date":"2024-05-06T00:00:00+09:00","versions":[{"audio_locale":"ja-JP","guid":"G50UZ0K2K","is_premium_only":true,"media_guid":"G07FN2G3G","original":true,"season_guid":"G6NQCJ9P1","variant":""},{"audio_locale":"en-US","guid":"G8WUNJQWJ","is_premium_only":true,"media_guid":"GQ9FG5895","original":false,"season_guid":"GR75CDZJ8","variant":""},{"audio_locale":"pt-BR","guid":"G8WUNJK41","is_premium_only":true,"media_guid":"GQ9FG5XP3","original":false,"season_guid":"G6Q4CZ125","variant":""},{"audio_locale":"fr-FR","guid":"GD9UVM1J9","is_premium_only":true,"media_guid":"GWMF824WV","original":false,"season_guid":"G65VCD91K","variant":""},{"audio_locale":"de-DE","guid":"G50UZ089D","is_premium_only":true,"media_guid":"G07FN2V1X","original":false,"season_guid":"GYWEC3WQM","variant":""},{"audio_locale":"es-ES","guid":"G0DUN2V1Z","is_premium_only":true,"media_guid":"G9XFE0KQ4","original":false,"season_guid":"GYE5CQ2NW","variant":""},{"audio_locale":"es-419","guid":"GG1U2JKQX","is_premium_only":true,"media_guid":"G71F47GZ3","original":false,"season_guid":"GRDQCGJX3","variant":""},{"audio_locale":"it-IT","guid":"GEVUZ712V","is_premium_only":true,"media_guid":"GXMFQEVG8","original":false,"season_guid":"GR09CX1JN","variant":""}]},"type":"episode","description":"Norn shuts herself in her dorm room and refuses to attend classes. Haunted by the specter of his past life, Rudeus sets out to solve his sister's problems, only to discover that he is the cause.","promo_title":"","title":"My Older Brother's Feelings","linked_resource_key":"cms:/episodes/G50UZ0K2K","id":"G50UZ0K2K","promo_description":"","slug_title":"my-older-brothers-feelings","channel_id":"crunchyroll","images":{"thumbnail":[[{"height":180,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/320x180/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":320},{"height":338,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/600x338/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":600},{"height":360,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/640x360/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":640},{"height":450,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/800x450/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":800},{"height":675,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1200},{"height":810,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1440x810/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1440},{"height":900,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1600x900/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1600},{"height":1080,"source":"https://www.crunchyroll.com/imgsrv/display/thumbnail/1920x1080/catalog/crunchyroll/2eaaf4e0383ee7ab92029508b17c5d69.jpe","type":"thumbnail","width":1920}]]},"slug":"","external_id":"EPI.926574"}],"meta":{}}

When I ignore it, it ends up not downloading the video...

**Comment by hama3254** [comment]
> In your image I don't even see the option to log in, would it be possible to create an option in the crunchyroll tab to log in manually when it doesn't appear?

The login form should pop-up if there are not login details saved.
It also shows if CR returns an error while using them.
You can change them manually with a right-click on any button (add, queue or settings) and there should be an option there

**Comment by hama3254** [comment]
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/2e71dc6d-91e1-4ca2-bf5f-3effc23c964e)

**Comment by dreezy-official** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/52826614/335134729-2e71dc6d-91e1-4ca2-bf5f-3effc23c964e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwODEwMzUsIm5iZiI6MTcxNzA4MDczNSwicGF0aCI6Ii81MjgyNjYxNC8zMzUxMzQ3MjktMmU3MWRjNmQtOTFlMS00Y2EyLWJmNWYtM2VmZmMyM2M5NjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0NTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNjQxMjc5MDYzYTg0MGZjNTExMGMyYTM1ZGEyNTY5OTA1MGRhYzBiNjM1NWE3ZDIzZDhjODMwOWNiZWNlZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3K3gyXucjNrv24INeWkoKra4x0Ou0ZIZBdSYKAdqx08)

**I removed the fields from the Crunchyroll account manually and re-inserted it and it worked, thank you.**

**Comment by KAK232** [comment]
![333583704-10713753-9826-4520-a853-7bfd1e928b0f](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/169140265/fc6afd1e-4478-4084-81f7-f91ab970dc49)
CRD-Login required ?
