### ISSUE TITLE
no all chapters in video

### ISSUE THREAD

**Issue by BattouKen** [hama3254/Crunchyroll-Downloader-v3.0#964]
**Describe the bug**
no all chapters in episode video, only first opening.

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll]
 - Settings [e.g. Softsubs, copy, ffmpeg etc.]
 - Version [e.g. v3.23.4 actual version]

**Screenshots**
![Sin título](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/81390696/8c68d649-f0fc-402e-abb3-dff847d3a020)

**Additional context**
with crunchy-cli that make all chapter same video.

**Comment by hama3254** [comment]
The downloader works as intended but it seems like they got a new API for more infos:
`https://static.crunchyroll.com/skip-events/production/[watch-id].json`
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/e05a4304-a5de-4bc4-b7be-418423eb27d4)
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/0a696a13-124a-43fe-934c-d844390e36cb)

The downloader uses the old one.
`https://static.crunchyroll.com/datalab-intro-v2/[watch-id].json`
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/fe0c4a29-7104-4447-aeb4-1b64ed2568df)

**Comment by TheWizard-maker** [comment]
Hello, thank again for this wonderful downloader that you keep updating. Would it be possible to use the new API with more chapters ? Thanks in advance

**Comment by hama3254** [comment]
@TheWizard-maker It is possible but i don't have any plans on adding this in the foreseeable future.
