### ISSUE TITLE
Auto-update?

### ISSUE THREAD

**Issue by NickQ29** [hama3254/Crunchyroll-Downloader-v3.0#969]
Since this app has to get patched fairly often to account for changes to the CR site proper, I was wondering if it'd be possible to add a way to automatically download its newest release? Not a high priority thing but it would be convenient.

**Comment by hama3254** [comment]
I don't know how good of an idea this really is, this would need some real world testing.
You can try [v3.23.6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.6) with no further functional updates and the next proper release will be compatible with the update feature.

**Comment by TaMaGo-TTV** [comment]
> I don't know how good of an idea this really is, this would need some real world testing. You can try [v3.23.6](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.6) with no further functional updates and the next proper release will be compatible with the update feature.

How does the auto updater work? Do I have to put the .exe in the CD folder?

**Comment by hama3254** [comment]
@TaMaGo-TTV 
with v3.23.7 i added an option to set the behavior you want.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/fda146b8-d8d3-4c16-b2ee-598ad478c4ce)

`Skip Updates` just disabels the function. 

`Notify Only` and `Notify Only (Beta Versions)` show that a new version is available.

![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/8aa207ab-ad3f-4796-b5da-da875f2819e7)


`Automatic Updates` and `Automatic Updates (Beta Versions)` download the `Auto_Update_v3.xx.exe` if available and save them as `Auto_Updated.exe`.

the downloader also starts the newer version after it has finished downloading, it also checks if there was already an update downloaded and starts that file.

**Comment by TheWizard-maker** [comment]
That's looks like a good thing, and good that we have "skip updates" choice. Just a question : with automatic update : do we have the same settings or the default ones are back ?

**Comment by hama3254** [comment]
> with automatic update : do we have the same settings or the default ones are back ?

old setting should just work, new settings will have a default value.

**Comment by hama3254** [comment]
the latest version crashes with auto update for some reason.
I keep it up as full download but the auto update file was removed.

**Comment by hama3254** [comment]
i think we don't need this anymore?
