### ISSUE TITLE
Stagnant Downloads

### ISSUE THREAD

**Issue by Azul772** [hama3254/Crunchyroll-Downloader-v3.0#97]
Crunchyroll Downloader Ver. 3.6.1

Some files keep downloading while others download only a little and then freeze and do nothing for hours.
<img width="881" alt="error 6" src="https://user-images.githubusercontent.com/75436296/101073496-f141d000-3575-11eb-8660-26c89ea032ca.png">

**Comment by hama3254** [comment]
The download itself is normally done by the media library [ffmpeg](https://www.ffmpeg.org/about.html).
You can try to reduce the amount of downloads at the same time with the "simultaneous downloads" setting or you can try the "hybrid mode" [more on that here](https://www.youtube.com/watch?v=s_SY3RM1F3Y)

**Comment by Azul772** [comment]
Thanks

**Comment by Azul772** [comment]
I reduced the amount of downloads to 1 and the download won't even start. It stays at 0%. The same thing with hybrid download.

**Comment by hama3254** [comment]
For debugging please try to make two double clicks on the settings icon, a message box with `Debug activated`  should aper.

You can now try one episode and just after it get added to the list there should be a message box look like this 
![grafik](https://user-images.githubusercontent.com/52826614/101045039-4682df00-3580-11eb-9418-0d23f3239a76.png)
Please send me a the text of that box, you can copy the text easy with CTRL+C while it is in focus.

**Comment by Azul772** [comment]
![error10](https://user-images.githubusercontent.com/75436296/101163626-3e6f8180-360a-11eb-80d1-5804491c82b2.png)

**Comment by Azul772** [comment]
![error10](https://user-images.githubusercontent.com/75436296/101163693-59da8c80-360a-11eb-9bb0-112c43ec692b.png)

**Comment by hama3254** [comment]
That looks so far, did you try to stream from the crunchyroll website ? 
Maybe it is a network issue from Cruchyroll aka vrv.

**Comment by Azul772** [comment]
What do you mean by streaming from the Crunchyroll website?

**Comment by hama3254** [comment]
The question is where is your problem, if the streaming itself does not work well for you than it could be a internet or issue from crunchyroll itself.

**Comment by Azul772** [comment]
I verified my internet connection and that was the problem. It was connecting and disconnecting. thanks for the help.
