### ISSUE TITLE
Idle after creating the CRD-TEMP-File

### ISSUE THREAD

**Issue by EstebanRestoy** [hama3254/Crunchyroll-Downloader-v3.0#970]
**Describe the bug**
When i add a video it create a .m3u8 file and put the status into idle but no download occured :'(

**Where does the issue happen?**
 - Platform: Crunchyroll
 - Settings (test multiples settings)
 - Version  v3.23.5

**Additional context**
**I may not know how to use the software.**

**Comment by hama3254** [comment]
The description is nothing out of the ordinary.
You should see the download added to the main window where the download itself is preocessed.
![grafik](https://user-images.githubusercontent.com/52826614/136704200-5b10f94f-c74f-408c-9ba9-13d9a3298ddb.png)

**Comment by EstebanRestoy** [comment]
I have no download after pasting the crunchyroll media url, is there a log file by any chance?

**Comment by EstebanRestoy** [comment]
thi is what i get 
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/55629825/9cbf14a1-ee65-45fe-873a-3471758b50e8)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/55629825/3649ce0e-a745-4b0c-b45f-9078210fe0bb)

**Comment by hama3254** [comment]
This is a new one, i would expect some kind of error to show up.

>You can find a log hidden behind the bottom bar that will be shown by clicking on the bar.
This log is a textbox and you can select (Ctrl+A) and copy (Ctrl+C) the text.
 ![grafik](https://user-images.githubusercontent.com/52826614/213559082-c544be36-8d4d-498f-bb22-87869282b254.png)

from _https://github.com/hama3254/Crunchyroll-Downloader-v3.0/wiki/CRD-Log_

**Comment by EstebanRestoy** [comment]
ok thx, i get a 403 :

Thread Name: Main
Web server started at: 127.0.0.1:80
what's going on?: 29/05/2024 11:01:19
StatusLabel: 29/05/2024 11:01:19 - Status: using login to authenticate
StatusLabel: 29/05/2024 11:01:22 - Status: Url match - Anime episode
ObjectsUrl: https://beta-api.crunchyroll.com/content/v2/cms/objects/GK9U3K7NX?preferred_audio_language=en-US&locale=en-US
Website: https://www.crunchyroll.com/watch/GK9U3K7NX/dragged-into-another-world
29/05/2024 11:01:24 CR-Title: Dragged into Another World!
NewAPI: https://cr-play-service.prd.crunchyrollsvc.com/v1/GK9U3K7NX/console/switch/play
StatusLabel: 29/05/2024 11:01:25 - Status: API data received
0 Streams-1988: en-US fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3K7NX/evs3/e9ec2702336948fcb0cd5cc6d309c2ee/assets/p/ba202ee12a0507620615e21fac1de56f_,5400986.mp4,5400987.mp4,5400985.mp4,5400984.mp4,5400983.mp4,3633.txt,.urlset/master.m3u8?playbackGuid=08-607739c0-9fcb-4fcc-8370-aaf068745e0b&accountid=56daeed6-5b96-5980-8339-7cd3643f21f2
1 Streams-1988: null fake_hls https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GK9U3K7NX/evs3/e9ec2702336948fcb0cd5cc6d309c2ee/assets/p/ba202ee12a0507620615e21fac1de56f_,5400764.mp4,5400765.mp4,5400763.mp4,5400761.mp4,5400762.mp4,3633.txt,.urlset/master.m3u8?playbackGuid=08-607739c0-9fcb-4fcc-8370-aaf068745e0b&accountid=56daeed6-5b96-5980-8339-7cd3643f21f2
StatusLabel: 29/05/2024 11:01:25 - Status: Language found
anime
C:\Users\hacki\Desktop\
Checking chapters
Checking chapters ended
StatusLabel: 29/05/2024 11:01:26 - Status: Resolution found

HTTP Status: 000
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.</p>
</body></html>

HTTP Status: 403

HTTP Status: 000

HTTP Status: 000

HTTP Status: 000

HTTP Status: 000
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /20100101
on this server.</p>
</body></html>

HTTP Status: 403
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /126.0
on this server.</p>
</body></html>

HTTP Status: 403

HTTP Status: 204

**Comment by EstebanRestoy** [comment]
it work with solo leveling anime
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/55629825/75d3fdbb-cd4b-45ae-a7bf-93c3aeb850af)

**Comment by hama3254** [comment]
It looks like there was `"` missing in the `curl` command.
you can see if the [v3.23.7](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.23.7) helps.

**Comment by hama3254** [comment]
without further complaints, i assume this fixed the issue.

**Comment by EstebanRestoy** [comment]
Yeah thx a lot !
