### ISSUE TITLE
Crunchyroll-Downloader-v3.23.5

### ISSUE THREAD

**Issue by Amanojaku-97** [hama3254/Crunchyroll-Downloader-v3.0#971]
Platform : Crunchyrool
![Capture d'écran 2024-05-29 112754](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/92400449/2419281a-581f-4dc8-b378-52eb7c5164bb)

**Comment by hama3254** [comment]
any further details?
Just a random issue or does it happen regularly?

**Comment by x3inspire** [comment]
Tried to download 13 episode, stuck at episode 7 and getting these error:
https://www.crunchyroll.com/series/G0XHWM1EK/the-wrong-way-to-use-healing-magic

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/4635825/d23177ba-6137-4c5b-ba00-4be3a7134343)

**Comment by Elwador** [comment]
@x3inspire you should not post that first screenshot anyone can use your account with the information shown

**Comment by x3inspire** [comment]
Now getting new error:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/4635825/983cf0f1-2e95-49df-8160-5224be05dcac)

**Comment by Serpentstar** [comment]
As an FYI for anyone posting images, there is a wonderful program out there called greenshot.  It is free and allows for some pretty useful editing features without having to use paint.  I personally use it when creating documentation and for all of the screenshots I post here.  It has this most wondrous obfuscation tool in its editor tools.  getgreenshot.org.   
It is most useful.

**Comment by hama3254** [comment]
@Amanojaku-97 did not add anything, the fist debug message from @x3inspire was removed and the invalid token issue was not reproducible.
the last debug message is behind the debug mode and is not persistent between restarts.
if there is not anything new i will close this soon.
