### ISSUE TITLE
Again there is the problem of not downloading the last part of the video.

### ISSUE THREAD

**Issue by Vorffeed** [hama3254/Crunchyroll-Downloader-v3.0#973]
Again it happens again that does not finish downloading 100% of the video the last time was solved by putting the hybrid mode, now in this mode it happens again that does not take the last block of the video.

here are two of the links in which I have noticed that this problem is returning
https://www.crunchyroll.com/es-es/watch/G0DUN2EZP/to-bring-a-smile-to-ones-face
https://www.crunchyroll.com/es-es/watch/GVWU0MN0P/grandpa-and-grandma-and-a-summer-festival

**Comment by hama3254** [comment]
I removed the fix since it seems to do nothing since the API switch.
Interresting that the exact same issue happens with different Servers/APIs.

I re-add the fix soon.
