### ISSUE TITLE
An error occurred: JWT error

### ISSUE THREAD

**Issue by swordnikolav** [hama3254/Crunchyroll-Downloader-v3.0#975]
Hi  haven't had any problems before, but now when I run under CLI on Linux the app throws me this error, which I think has to do with the token.
An error occurred: JWT error (https://cr-play-service.prd.crunchyrollsvc.com/v1/GG1U2JP1Q/console/switch/play)

**Comment by hama3254** [comment]
I am not sure if you are on the right project.

But we had a issues likes this a view weeks ago.
You can find it here : https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959#issuecomment-2124318700
The solution was posted directly below, see here https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959#issuecomment-2124598368
And to get around the stream limit we got either this method https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959#issuecomment-2125424975 or the one I used (against the advice) https://github.com/hama3254/Crunchyroll-Downloader-v3.0/issues/959#issuecomment-2127655825
