### ISSUE TITLE
Either Im dumb or its a bug...

### ISSUE THREAD

**Issue by AndrewEPrince** [hama3254/Crunchyroll-Downloader-v3.0#979]
Hi! Im assuming this is a bug but im honestly not too sure as this is my first time using this program. Im pasting in the link then it asks me to use the add "--insecure" to curl requests. so I checkmarked it.
I then go to add a video again:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/90168409/3b25d9c0-dfcb-434a-8077-42647b510c76)

and get this:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/90168409/b6fd886c-64d3-41e4-a3d1-da6e3cbc0ecc)

Then I go to the queue to see the download in the queue and check process:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/90168409/444ad14c-68c6-44c3-a29e-eabbc7a10fd8)

but I find that it doesnt seemingly do anything and just goes away.
am I missing a step?
thanks

**Comment by AndrewEPrince** [comment]
Its also saying this after I press process Queue
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/90168409/f0149029-49f8-4817-93fe-b25bee757ce4)

**Comment by AndrewEPrince** [comment]
You can tell by my token being not expired but I have logged in with my Crunchyroll account

**Comment by hama3254** [comment]
if you get any error like in #929 then please try to disable your anti virus software and see if the downloader then works.

**Comment by AndrewEPrince** [comment]
The only popup like that that ive gotten has been to use the --insecure

before I checked that box I would get this:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/90168409/aaf51507-dc2b-4a38-b66c-e8df96af53d9)

I just allowed it on my antivirus and got this:

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/90168409/75e50583-e979-4bb4-8631-c0c153c6157c)

**Comment by hama3254** [comment]
>The only popup like that that ive gotten has been to use the --insecure

i probably have to redo/remove the error message.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/588fc587f2e8c4682d540ba73baeb5d429d7573b/Crunchyroll%20Downloader/Main.vb#L2925
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/blob/588fc587f2e8c4682d540ba73baeb5d429d7573b/Crunchyroll%20Downloader/Main.vb#L2926

>But now it doesnt show up in the queue

Does it now download the episode? it should update the status regualry and then add the video to the main window.

**Comment by AndrewEPrince** [comment]
I was using StreamFab but it just stopped being able to get the info for the website all of a sudden so I tried using this. maybe Cloudflare is being tricky with my account specifically?

**Comment by Elwador** [comment]
i tried streamfab a few months back for a few days but i got so annoyed that i made my own downloader to easily check for new episodes on CR 😆 

also are you using a vpn maybe that is causing the problem here

**Comment by AndrewEPrince** [comment]
Yes, I was using a vpn. I took it off and am still having the same problem. Im not sure if this helps but it only shows up in the queue if I have the "Process Queue" set to on before I press download

**Comment by AndrewEPrince** [comment]
Does it connect with an API or does it use a Browser or the default browser? I assume it would show up in In the my devices section on Crunchyroll itself

**Comment by AndrewEPrince** [comment]
UPDATE! Just tried it on my laptop and it works. the question is what on my computer is stopping it from working?

**Comment by AndrewEPrince** [comment]
UPDATE: Its avast. works after I turn off firewall and core sheilds

**Comment by hama3254** [comment]
> UPDATE: I have no clue what specific URL to add the exception to.

If you can add domains to the exception list than `beta-api.crunchyroll.com` would be it.
The request url changes for each anime.

**Comment by AndrewEPrince** [comment]
That one helps. when I added that as an exception, it could then find the anime but it would still disappear as if it had already processed that episode. are there any other domains it could be using?

**Comment by hama3254** [comment]
I forgott the media files are hosted on different [CDNs](https://en.wikipedia.org/wiki/Content_delivery_network), i don't have a list of all possible sub-domains.
If you have another device where it works then i would suggest you use that and then tranfser the file between the devices as you need. The other options are to either disable avast for the usage of the downloader or even uninstall it.
