### ISSUE TITLE
AOD Episoden Namen (Fehler mit Bindestrichen im Episoden-Titel)

### ISSUE THREAD

**Issue by Schizo1987** [hama3254/Crunchyroll-Downloader-v3.0#98]
Vielen Dank für die Umsetzung mit der Folgen Benennung, du bist der Beste!!
Ich habe es jetzt getestet bei AOD und mir ist aufgefallen sobald ein Bindestrich im Episodentitel ist beschneidet er den Episodennamen. Als Beispiel bei der Episode 934 von One Piece ist alles in Ordnung.

One Piece 20 Staffel Wano-Land Sub Episode 934 Das Blatt wendet sich Der Dreischwertstil überwindet die Todesschwelle

Bei den Episoden 935, 936 938 fehlen dann Textabschnitte.

Falsch: One Piece 20 Staffel Wano-Land Sub Episode 935 Zorro ist verblüfft
Richtig: One Piece 20 Staffel Wano-Land Sub Episode 935 Zorro ist verblüfft - Die schockierende Identität der mysteriösen Schönheit

Falsch: One Piece 20 Staffel Wano-Land Sub Episode 936 Meistere die Technik
Richtig: One Piece 20 Staffel Wano-Land Sub Episode 936 Meistere die Technik - Das Haki Wano-Lands, Ryuo

Falsch: One Piece 20 Staffel Wano-Land Sub Episode 938 Hohe Wellen werden geschlagen
Richtig: One Piece 20 Staffel Wano-Land Sub Episode 938 - Die Identität des edlen Diebes Kozo Ushimitsu

Vielen Dank schon mal! MFG Schizo1987

**Comment by hama3254** [comment]
Die verwenden halt einfach die selbe Zeichenfolge wie zwischen der Episoden nummer und dem eigentlichen Namen... 
Ich denke aber das passt so jetzt.
![grafik](https://user-images.githubusercontent.com/52826614/101204658-d9994300-366c-11eb-8483-5d13fd1cfd42.png)

**Comment by Schizo1987** [comment]
Wahnsinn! Vielen vielen Dank das du die Bugs immer so schnell Fixt!
Jetzt funktioniert es 👍

MFG Schizo
