### ISSUE TITLE
Missing Browser in version 3.23.8 cruncyroll downloader

### ISSUE THREAD

**Issue by Amaterasu91** [hama3254/Crunchyroll-Downloader-v3.0#980]
**Describe the bug**
I can't download without webbrowser

**Where does the issue happen?**
 - Platform: [e.g. Crunchyroll]
 - Settings [e.g. Hardsubs, Softsubs, ffmpeg options]
 - Version [e.g. v3.23.8]

**Screenshots**
Version 3.23.8
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/171918286/0146d0e4-3750-4759-b687-2b04a3bcd7a0)
Version 3.23.5
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/171918286/667c96a4-8008-4a4d-bc6e-3fe2374c2e6b)

**Additional context**

**Comment by AndrewEPrince** [comment]
How did you get that screen to show?!

**Comment by hama3254** [comment]
> I can't download without webbrowser

Any reason why? The downloader is not using the browser since v3.22.
The functions of the browser was replaced with a direct api login.

**Comment by Amaterasu91** [comment]
> > Non riesco a scaricare senza browser web
> 
> Qualche motivo? Il downloader non utilizza il browser dalla versione 3.22. Le funzioni del browser sono state sostituite con un accesso API diretto.

I have been using the program for almost a year and I have always used the second icon on the left of version 3.23.5 to access Cruncyroll to get the download link. 
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/171918286/9404f331-06fd-4016-9da3-5b10dfdfd2bd)
Maybe from version 3.22 you can access directly from your browser (chrome, brave, firefox) to get the link with premium access?
My only request is to reinsert the browser that was already in version 3.23.5.

**Comment by Aiyomi-Irirako** [comment]
why? you can just use a normal browser of your choice for the link?

i have never used ithe browser in the downloader

**Comment by hama3254** [comment]
Since the only reason the browser was in there is now gone i see no point of keeping it or adding it back.
this may be a small inconvenience but there in no point of keeping code/dependencies that does nothing for the average user.
