### ISSUE TITLE
How to Download MULTI Audio

### ISSUE THREAD

**Issue by naniworks124** [hama3254/Crunchyroll-Downloader-v3.0#986]
Hi bro How can Download a video in MULTI Can You Please Bring an Update For this

**Comment by hama3254** [comment]
without changes from Crunchyroll the end result will not be good.
We had a discussions about that in #701 with user feedback.

**Comment by loddar66** [comment]
@naniworks124 if you're not afraid of using command line tools, '[crunchy-cli](https://github.com/crunchy-labs/crunchy-cli)' might be worth to check. But other than for the CR-Downloader, it also requires some familiarization time to get what you want. There are always pros and cons...
