### ISSUE TITLE
Series music videos fail to download.

### ISSUE THREAD

**Issue by Serpentstar** [hama3254/Crunchyroll-Downloader-v3.0#987]
Attempting to download a music video that is part of a given series is failing

**Where does the issue happen?**
 - Platform:  Crunchyroll  (I thought Funimation was now gone)
 - Settings [e.g. Hardsubs-English, Softsubs-English, Hybrid mode, 480P]
 - Version [e.g. v3.23.8]

![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/751507/8ad1baa4-4e19-4eae-91d3-b29221121080)
![image](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/751507/da713b41-a83e-4c77-a03b-c16c9dd7ca85)

After hitting submit, the window just closes with no download.

**Additional context**
I have also tried to skip hard sub if unavailable.  The add video status go es back to idle.

**Comment by jesuspkane** [comment]
gives this error Failed dowload encryption key
