### ISSUE TITLE
How to change the logged user

### ISSUE THREAD

**Issue by bybpow** [hama3254/Crunchyroll-Downloader-v3.0#988]
I have not used the app in a while. Now I wanted to download some eps and I needed to change accounts but I could not. Is there an option to do so? I had to delete the .dat file and reset everything.

**Comment by hama3254** [comment]
You can access the login form from the context menu via a right click.
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/f953a99d-61ca-4f8c-9538-1514ef576752)

**Comment by jesuspkane** [comment]
gives this error Failed dowload encryption key

**Comment by bybpow** [comment]
Thanks
