### ISSUE TITLE
Download Subtitles

### ISSUE THREAD

**Issue by MrFanservice-png** [hama3254/Crunchyroll-Downloader-v3.0#989]
How do I only download the subtitles from Crunchyroll? Again, do I need a premium account if I want to download them from premium videos?

**Comment by hama3254** [comment]
I never tested it but can try if you get soft subs via the `Subtitles Only` option.
I doubt that it will work for premium videos without any premium.
Also the video is now not downloadable (see #991) so I would think twice before I subscribe to Crunchyroll.
