### ISSUE TITLE
v3.24.0

### ISSUE THREAD

**Issue by Horutoi** [hama3254/Crunchyroll-Downloader-v3.0#993]
hello Hama3254,
there is a problem with the audio files
problem of conformity and stream flow

**Comment by hama3254** [comment]
Due to added copy protection, the downlader is no longer working.

**Comment by Sebasj6** [comment]
So this program will not undergo any further updates?

**Comment by hama3254** [comment]
> So this program will not undergo any further updates?

see #994.
