### ISSUE TITLE
Hardsub

### ISSUE THREAD

**Issue by Greyghost82** [hama3254/Crunchyroll-Downloader-v3.0#995]
good day to everyone im having problem just  getting hardsub subtitle look like there dowmloaded but the files isnt there can anyone help 

<details>
  <summary>Images</summary>
  

![Screenshot 2024-06-26 131140](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139466236/3f584b24-b6ea-4cfe-89ea-5f62d85c3f6f)
![Screenshot 2024-06-26 131213](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139466236/15e194a2-b100-4e57-82de-7d063c9c396b)
![Screenshot 2024-06-26 131234](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139466236/49541d7a-d68e-4375-b998-9a3a06d20159)
  
</details>

**Comment by hama3254** [comment]
Hardsubs are part of the video, since the video can not be downloaded anymore they don't work.

For `Subtitles only` you need to select the langues as `SoftSubs`
![grafik](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/52826614/47bb2569-e713-4ef9-b965-c42974a3c6a7)

**Comment by Greyghost82** [comment]
![Screenshot 2024-06-26 194623](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/assets/139466236/7f175d98-b72c-4d39-b41f-51aac8040297)
mainly for signs/song etc etc as family memeber has hard for hearing is there any  another way to get those sign/song subtites instead of soft subs as i get them anyway your program.  your progam is  best one i used and still is just made life really easly when it come to my plex server, a frend let me use the streamfab but not the same as yours only can get soft sub hopefully you be back up and running soon thank you for all you hard work cant wait to use your program again

**Comment by hama3254** [comment]
I don't understand what you try to accomplish. If you need subtitle for hearing issues you need to look into [`captions`](https://www.3playmedia.com/blog/closed-captioning-vs-subtitles/) which my downloader never really had.
Also the downloader is deprecated/abandoned since Crunchyroll now only uses protected stream to prevent the download.
