### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by BrownyEz** [hama3254/Crunchyroll-Downloader-v3.0#997]
Enter your version below, it can be found in the "About" section of the settings.
Version : 3.99.0

Please provide a logfile or text.
For version below v3.7 the logfile needs be be activated in the settings before the download has started, newer version can copy the log to the clipboard or save it as file in the context menu (right click on the failed download)  
Logfile/Logtext : click at the end of the line an Drag&Drop the .log file here 
or 
<details>
  <summary>Insert the logtext before the second details</summary>
    
</details>

System.ComponentModel.Win32Exception (0x80004005): Le fichier spécifié est introuvable
à System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
à Crunchyroll Downloader.GetData.CurlPost(String Url, String Cookies, String Auth, String Post, String Sender) dans C:\Users\Browny\Desktop\Crunchyroll-Downloader-v3.0-3.99.0\Crunchyr
oll Downloader GetData.vb:ligne 101
à Crunchyroll Downloader.Main.LoadBrowser(String Url, Int32 RT_count) dans
C:\Users\Browny\Desktop\Crunchyroll-Downloader-v3.0-3.99.0\Crunchyr oll Downloader\Main.vb:ligne 2924
à Crunchyroll
Downloader.Anime_Add.Btn_dl_Click(Object sender,
EventArgs e) dans
C:\Users\Browny\Desktop\Crunchyroll-Downloader-v3.0-3.99.0\Crunchyr
oll Downloader\Anime_Add.vb:ligne 268

**Comment by hama3254** [comment]
The Project is deprecated, v3.99 is just a Dummy release to link the issue on the download page.
